Repository sagemath/sage, pull requests merged in 2023-03, with the labels that each got.

#34961 qqbar.clear_denominators: crude but fast alternative algorithm
  src/sage/rings/qqbar.py
Labels: p: major / 3, s: positive review, c: algebra

#34995 Support for tachyon >= 0.99.2
  src/sage/interfaces/tachyon.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#35021 Implement check for Lorentzian polynomials #28252
  src/doc/en/reference/references/index.rst
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review

#35023 Remove upstream urls from checksums.ini that point to trac
  build/pkgs/giac/checksums.ini
  build/pkgs/iml/checksums.ini
  build/pkgs/mathjax/checksums.ini
  build/pkgs/msolve/checksums.ini
Labels: s: positive review, p: trivial / 5, t: refactoring

#35024 fix usage of verbose with positional argument
  src/sage/schemes/elliptic_curves/gal_reps.py
Labels: s: positive review

#35025 Implement __getitem__ and alias weight methods for quasimodular forms
  src/sage/modular/quasimodform/element.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: modular forms

#35027 gitignore another (temporary) autoconf file
  .gitignore
Labels: p: minor / 4, s: positive review

#35033 sage.schemes: Replace imports from sage.*.all for namespace packages
  src/sage/schemes/affine/affine_morphism.py
  src/sage/schemes/elliptic_curves/BSD.py
  src/sage/schemes/elliptic_curves/cardinality.py
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_modular_symbols.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/ell_tate_curve.py
  src/sage/schemes/elliptic_curves/ell_torsion.py
  src/sage/schemes/elliptic_curves/formal_group.py
  src/sage/schemes/elliptic_curves/gal_reps.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/height.py
  src/sage/schemes/elliptic_curves/hom_velusqrt.py
  src/sage/schemes/elliptic_curves/isogeny_class.py
  src/sage/schemes/elliptic_curves/isogeny_small_degree.py
  src/sage/schemes/elliptic_curves/lseries_ell.py
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
  src/sage/schemes/elliptic_curves/modular_parametrization.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/schemes/elliptic_curves/padics.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/schemes/elliptic_curves/saturation.py
  src/sage/schemes/elliptic_curves/sha_tate.py
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
  src/sage/schemes/generic/spec.py
  src/sage/schemes/hyperelliptic_curves/hypellfrob.pyx
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
  src/sage/schemes/hyperelliptic_curves/jacobian_endomorphism_utils.py
  src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
  src/sage/schemes/hyperelliptic_curves/kummer_surface.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/plane_conics/con_rational_field.py
  src/sage/schemes/plane_conics/con_rational_function_field.py
  src/sage/schemes/projective/proj_bdd_height.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/schemes/projective/projective_point.py
  src/sage/schemes/toric/library.py
  src/sage/schemes/toric/morphism.py
  src/sage/schemes/toric/points.py
Labels: p: major / 3, s: positive review, t: refactoring

#35035 make _multiple_x_*() methods work for all n≠0
  src/sage/schemes/elliptic_curves/ell_generic.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#35040 Document argument is_open in ManifoldSubset.complement and difference
  src/sage/manifolds/subset.py
Labels: p: minor / 4, s: positive review, c: documentation, c: manifolds

#35059 Add Hadamard matrices up to order 1000
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/matrices/hadamard_matrix.py
Labels: s: positive review, c: linear algebra, c: combinatorics

#35060 a bijectionist's toolkit
  build/pkgs/configure/checksums.ini
  build/pkgs/configure/package-version.txt
  src/sage/combinat/bijectionist.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics

#35063 Add notes about recent changes on KnotInfo
  src/sage/knots/knotinfo.py
Labels: s: positive review, p: critical / 2, c: algebraic topology

#35064 removing some unused imports
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_element.pxd
Labels: s: positive review

#35067 Upgrade eclib to 20221012
  build/pkgs/eclib/checksums.ini
  build/pkgs/eclib/package-version.txt
  build/pkgs/eclib/spkg-configure.m4
Labels: c: packages: standard, s: positive review

#35070 Document sage installation method with pip
  README.md
Labels: s: positive review, c: documentation

#35073 refactor(34773): combinatorial polyhedron: move list of pairs to dedicated class
  src/sage/data_structures/list_of_pairs.pxd
  src/sage/data_structures/list_of_pairs.pyx
  src/sage/data_structures/sparse_bitset.pxd
  src/sage/geometry/polyhedron/base.py
  src/sage/geometry/polyhedron/base0.py
  src/sage/geometry/polyhedron/base1.py
  src/sage/geometry/polyhedron/base2.py
  src/sage/geometry/polyhedron/base3.py
  src/sage/geometry/polyhedron/base4.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/geometry/polyhedron/base6.py
  src/sage/geometry/polyhedron/base7.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/conversions.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_data_structure.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_list_data_structure.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_list_data_structure.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/list_of_faces.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pyx
  src/sage/graphs/generic_graph.py
  src/sage/rings/number_field/order.py
Labels: p: major / 3, s: positive review, c: geometry, t: refactoring

#35076 Add ABCs CommutativePolynomial, MPolynomial_libsingular, InfinitePolynomial; deprecate is_Polynomial, is_MPolynomial
  src/sage/algebras/fusion_rings/shm_managers.pyx
  src/sage/combinat/kazhdan_lusztig.py
  src/sage/combinat/schubert_polynomial.py
  src/sage/combinat/sf/sfa.py
  src/sage/crypto/boolean_function.pyx
  src/sage/crypto/mq/rijndael_gf.py
  src/sage/crypto/sbox.pyx
  src/sage/crypto/stream.py
  src/sage/groups/affine_gps/group_element.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/libs/symmetrica/sb.pxi
  src/sage/libs/symmetrica/symmetrica.pxi
  src/sage/manifolds/differentiable/characteristic_cohomology_class.py
  src/sage/modular/modsym/ambient.py
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/constructions.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/finite_field_constructor.py
  src/sage/rings/finite_rings/finite_field_givaro.py
  src/sage/rings/finite_rings/finite_field_ntl_gf2e.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/function_field/function_field.py
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/padic_template_element.pxi
  src/sage/rings/polynomial/__init__.py
  src/sage/rings/polynomial/commutative_polynomial.pxd
  src/sage/rings/polynomial/commutative_polynomial.pyx
  src/sage/rings/polynomial/infinite_polynomial_element.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial.pxd
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pxd
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/padics/polynomial_padic_capped_relative_dense.py
  src/sage/rings/polynomial/polynomial_element.pxd
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_ntl.pyx
  src/sage/rings/qqbar.py
  src/sage/schemes/berkovich/berkovich_cp_element.py
  src/sage/schemes/curves/constructor.py
  src/sage/schemes/cyclic_covers/constructor.py
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/jacobian.py
  src/sage/schemes/generic/hypersurface.py
  src/sage/schemes/hyperelliptic_curves/constructor.py
  src/sage/schemes/hyperelliptic_curves/jacobian_homset.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/plane_conics/constructor.py
  src/sage/schemes/plane_quartics/quartic_constructor.py
  src/sage/structure/element.pyx
Labels: p: major / 3, s: positive review, t: refactoring

#34970 add is_supergreedy() to linear extensions
  src/doc/en/reference/references/index.rst
  src/sage/combinat/posets/linear_extensions.py
Labels: s: positive review, c: combinatorics

#34979 deprecate constructing number-field fractional ideals via orders' .ideal() method
  src/sage/matrix/matrix2.pyx
  src/sage/modular/dirichlet.py
  src/sage/rings/number_field/bdd_height.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/order.py
  src/sage/rings/padics/padic_valuation.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/quotient_ring.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/projective/projective_point.py
Labels: p: major / 3, t: bug, s: positive review, c: number theory, c: algebra

#34980 is_prime for ideals uses factorization, can be VERY slow
  src/sage/rings/number_field/number_field_ideal.py
Labels: c: basic arithmetic, t: bug, s: positive review, p: critical / 2

#34988 Integer-valued polynomial ring
  src/doc/en/reference/polynomial_rings/polynomial_rings_univar.rst
  src/sage/rings/polynomial/all.py
  src/sage/rings/polynomial/integer_valued_polynomials.py
Labels: p: major / 3, t: enhancement, s: positive review, c: commutative algebra

#35026 Drinfeld modules
  src/doc/en/reference/drinfeld_modules/conf.py
  src/doc/en/reference/drinfeld_modules/index.rst
  src/doc/en/reference/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/categories/drinfeld_modules.py
  src/sage/rings/function_field/all.py
  src/sage/rings/function_field/drinfeld_modules/__init__.py
  src/sage/rings/function_field/drinfeld_modules/action.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/homset.py
  src/sage/rings/function_field/drinfeld_modules/morphism.py
  src/sage/rings/ring_extension.pyx
Labels: t: enhancement, s: positive review, c: algebra

#35043 fix the method monomials_of_degree
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#35045 Convert result of multivariate polynomial evaluation into correct parent
  src/sage/modular/modform_hecketriangle/graded_ring_element.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/schemes/riemann_surfaces/riemann_surface.py
  src/sage/schemes/toric/points.py
Labels: s: positive review

#35099 sage.{coding,groups}: Replace imports from sage.*.all for namespace packages
  src/sage/coding/bch_code.py
  src/sage/coding/binary_code.pyx
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/cyclic_code.py
  src/sage/coding/delsarte_bounds.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/linear_code.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/dual_abelian_group_element.py
  src/sage/groups/abelian_gps/element_base.py
  src/sage/groups/affine_gps/affine_group.py
  src/sage/groups/class_function.py
  src/sage/groups/generic.py
  src/sage/groups/libgap_mixin.py
  src/sage/groups/matrix_gps/finitely_generated.py
  src/sage/groups/matrix_gps/group_element.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pyx
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/groups/perm_gps/permgroup_named.py
Labels: s: positive review, t: refactoring

#35104 Remove direct use of "setup.py sdist", add targets "make SPKG-sdist"
  Makefile
  build/make/Makefile.in
  build/pkgs/sage_conf/spkg-src
  build/pkgs/sage_docbuild/spkg-src
  build/pkgs/sage_setup/spkg-src
  build/pkgs/sage_sws2rst/spkg-install
  build/pkgs/sage_sws2rst/spkg-src
  build/pkgs/sagelib/spkg-src
  build/pkgs/sagemath_categories/spkg-src
  build/pkgs/sagemath_environment/spkg-src
  build/pkgs/sagemath_objects/spkg-src
  build/pkgs/sagemath_repl/spkg-src
Labels: s: positive review, c: build

#35105 sage.{functions,interfaces,symbolic}: Replace imports from sage.*.all for namespace packages
  src/sage/functions/hypergeometric.py
  src/sage/functions/piecewise.py
  src/sage/interfaces/axiom.py
  src/sage/interfaces/fricas.py
  src/sage/interfaces/genus2reduction.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/octave.py
  src/sage/interfaces/sage0.py
  src/sage/interfaces/scilab.py
  src/sage/interfaces/singular.py
  src/sage/interfaces/sympy.py
  src/sage/symbolic/pynac_impl.pxi
  src/sage/symbolic/substitution_map_impl.pxi
Labels: s: positive review, c: symbolics, t: refactoring

#35044 #27428 fix use of sig_on()/sig_off() in CBF.integral()
  src/sage/rings/complex_arb.pyx
Labels: s: positive review

#35054 Implementing q-commuting Laurent polynomials.
  src/sage/algebras/catalog.py
  src/sage/algebras/q_commuting_polynomials.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35082 Upgrade scipy to 1.10.1
  build/pkgs/meson/checksums.ini
  build/pkgs/meson/package-version.txt
  build/pkgs/meson/spkg-configure.m4
  build/pkgs/meson_python/checksums.ini
  build/pkgs/meson_python/package-version.txt
  build/pkgs/meson_python/patches/ARCHFLAGS_empty.patch
  build/pkgs/pythran/checksums.ini
  build/pkgs/pythran/package-version.txt
  build/pkgs/scipy/checksums.ini
  build/pkgs/scipy/package-version.txt
Labels: c: packages: standard, s: positive review

#35083 build/pkgs/pcre: Remove
  build/pkgs/_prereq/distros/fedora.txt
  build/pkgs/pcre/SPKG.rst
  build/pkgs/pcre/checksums.ini
  build/pkgs/pcre/dependencies
  build/pkgs/pcre/distros/conda.txt
  build/pkgs/pcre/distros/cygwin.txt
  build/pkgs/pcre/distros/debian.txt
  build/pkgs/pcre/distros/fedora.txt
  build/pkgs/pcre/distros/freebsd.txt
  build/pkgs/pcre/distros/homebrew.txt
  build/pkgs/pcre/distros/macports.txt
  build/pkgs/pcre/distros/opensuse.txt
  build/pkgs/pcre/distros/repology.txt
  build/pkgs/pcre/distros/slackware.txt
  build/pkgs/pcre/distros/void.txt
  build/pkgs/pcre/package-version.txt
  build/pkgs/pcre/patches/8.39-cygwin-jit.patch
  build/pkgs/pcre/spkg-configure.m4
  build/pkgs/pcre/spkg-install.in
  build/pkgs/pcre/type
  build/pkgs/r/SPKG.rst
  build/pkgs/r/dependencies
  configure.ac
Labels: c: packages: standard, s: positive review

#35085 Upgrade polymake to 4.9
  build/pkgs/polymake/checksums.ini
  build/pkgs/polymake/dependencies
  build/pkgs/polymake/package-version.txt
  build/pkgs/polymake/spkg-install.in
Labels: s: positive review, c: packages: optional, c: geometry

#35086 move single_valued method of MZV to auxiliary F ring
  src/doc/en/reference/references/index.rst
  src/sage/modular/multiple_zeta.py
  src/sage/modular/multiple_zeta_F_algebra.py
Labels: s: positive review

#35087 refactor: Use enum for face iterator status
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
Labels: s: positive review, c: geometry, t: refactoring

#35091 fix and activate W391 in pyx files
  src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.pyx
  src/sage/algebras/fusion_rings/poly_tup_engine.pyx
  src/sage/algebras/fusion_rings/shm_managers.pyx
  src/sage/numerical/backends/generic_backend.pyx
  src/tox.ini
Labels: s: positive review, t: refactoring

#35097 Simplicial set group
  src/sage/categories/simplicial_sets.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_catalog.py
  src/sage/topology/simplicial_set_examples.py
Labels: s: positive review, c: algebraic topology

#35098 sage.{topology,homology}: Replace imports from sage.*.all for namespace packages
  src/sage/homology/chain_complex.py
  src/sage/homology/koszul_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review, t: refactoring

#35100 New ABC sage.structure.element.NumberFieldElement, deprecate is_NumberFieldElement
  src/sage/interfaces/maxima_lib.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/number_field/__init__.py
  src/sage/rings/number_field/number_field_element.pxd
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_base.pxd
  src/sage/rings/number_field/number_field_element_base.pyx
  src/sage/rings/universal_cyclotomic_field.py
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/structure/element.pyx
  src/sage/symbolic/expression_conversions.py
Labels: s: positive review, c: number fields, t: refactoring

#35101 scip_backend: Remove use of deprecated sage.ext.memory_allocator
  src/sage/numerical/backends/scip_backend.pyx
Labels: t: bug, s: positive review, c: linear programming

#35151 fix all pycodestyle E303 warnings in all folders c*
  src/sage/calculus/calculus.py
  src/sage/categories/affine_weyl_groups.py
  src/sage/categories/algebras_with_basis.py
  src/sage/categories/category.py
  src/sage/categories/classical_crystals.py
  src/sage/categories/coalgebras.py
  src/sage/categories/complex_reflection_or_generalized_coxeter_groups.py
  src/sage/categories/crystals.py
  src/sage/categories/examples/graded_connected_hopf_algebras_with_basis.py
  src/sage/categories/examples/sets_cat.py
  src/sage/categories/examples/with_realizations.py
  src/sage/categories/filtered_hopf_algebras_with_basis.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/finite_dimensional_semisimple_algebras_with_basis.py
  src/sage/categories/generalized_coxeter_groups.py
  src/sage/categories/graded_modules_with_basis.py
  src/sage/categories/hecke_modules.py
  src/sage/categories/semigroups.py
  src/sage/categories/sets_cat.py
  src/sage/categories/topological_spaces.py
  src/sage/categories/weyl_groups.py
  src/sage/coding/encoder.py
  src/sage/coding/extended_code.py
  src/sage/coding/golay_code.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/coding/punctured_code.py
  src/sage/coding/self_dual_codes.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/ext_rep.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/designs/steiner_quadruple_systems.py
  src/sage/combinat/k_tableau.py
  src/sage/combinat/root_system/type_B.py
  src/sage/combinat/root_system/type_D.py
  src/sage/combinat/t_sequences.py
  src/sage/combinat/vector_partition.py
  src/sage/crypto/block_cipher/miniaes.py
  src/sage/crypto/lwe.py
  src/sage/crypto/mq/sr.py
Labels: s: positive review, t: refactoring

#35159 update msolve to 0.4.9
  build/pkgs/msolve/SPKG.rst
  build/pkgs/msolve/checksums.ini
  build/pkgs/msolve/package-version.txt
Labels: s: positive review, c: packages: optional, c: commutative algebra

#35162 Fix a slow doctest in matrix_integer_dense_hnf.py
  src/sage/matrix/matrix_integer_dense_hnf.py
Labels: s: positive review, t: tests

#35163 Fix the documentation for the so matrix Lie algebra
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/examples.py
Labels: t: bug, p: minor / 4, s: positive review, c: documentation

#35164 compute the matrix of an isogeny on a given n-torsion subgroup
  src/sage/schemes/elliptic_curves/hom.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#35165 activate W293 and E714 in pyx files
  src/sage/graphs/graph_coloring.pyx
  src/sage/matrix/matrix_polynomial_dense.pyx
  src/sage/modular/hypergeometric_misc.pyx
  src/tox.ini
Labels: s: positive review, t: refactoring

#35170 Fix bug in is_eulerian
  src/sage/graphs/generic_graph.py
Labels: t: bug, s: positive review, c: graph theory

#35173 Speedup of Poset characteristic polynomial
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#35174 cleaning and enhancement to PolyDict
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/polydict.pxd
  src/sage/rings/polynomial/polydict.pyx
  src/sage/rings/tate_algebra_ideal.pyx
Labels: s: positive review, t: performance, c: algebra

#35177 Matplotlib 3.7.0 support
  src/sage/plot/complex_plot.pyx
  src/sage/plot/contour_plot.py
  src/sage/plot/graphics.py
  src/sage/plot/multigraphics.py
  src/sage/plot/plot3d/plot_field3d.py
Labels: p: major / 3, c: packages: standard, s: positive review

#35180 fix(docs): use double backquotes for a command
  src/doc/de/tutorial/introduction.rst
  src/doc/es/tutorial/introduction.rst
  src/doc/fr/tutorial/introduction.rst
  src/doc/ja/tutorial/introduction.rst
  src/doc/pt/tutorial/introduction.rst
  src/doc/ru/tutorial/introduction.rst
Labels: s: positive review

#35186 Various improvements to Weyl character rings
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/combinat/root_system/weyl_characters.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35189 Add typing to tangent vectors
  src/sage/manifolds/differentiable/diff_map.py
  src/sage/manifolds/differentiable/scalarfield.py
  src/sage/manifolds/differentiable/tangent_space.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/tensor/modules/free_module_element.py
  src/sage/tensor/modules/free_module_morphism.py
  src/sage/tensor/modules/free_module_tensor.py
Labels: s: positive review, c: manifolds

#35193 symbolics: add derivative operator
  src/sage/symbolic/all.py
  src/sage/symbolic/operators.py
Labels: s: positive review, c: symbolics

#35195 Workaround for an ecl race in maxima init
  src/sage/interfaces/maxima_lib.py
Labels: p: major / 3, t: bug, c: packages: standard, s: positive review, c: doctest framework

#35197 Fix bug with Set equality/inequality
  src/sage/sets/set.py
Labels: t: bug, s: positive review

#35203 sagemath-standard: Add dependencies `typing_extensions`, `importlib_resources`, `importlib_metadata`
  build/pkgs/importlib_metadata/SPKG.rst
  build/pkgs/importlib_metadata/checksums.ini
  build/pkgs/importlib_metadata/install-requires.txt
  build/pkgs/importlib_metadata/package-version.txt
  build/pkgs/importlib_resources/checksums.ini
  build/pkgs/importlib_resources/install-requires.txt
  build/pkgs/importlib_resources/package-version.txt
  build/pkgs/sagelib/dependencies
  build/pkgs/typing_extensions/checksums.ini
  build/pkgs/typing_extensions/install-requires.txt
  build/pkgs/typing_extensions/package-version.txt
  src/doc/en/developer/coding_in_python.rst
  src/requirements.txt.m4
  src/setup.cfg.m4
Labels: c: packages: standard, s: positive review

#35204 Remove directories leftover from improper shutdown so sage-cleaner won't kill random processes
  src/bin/sage-cleaner
Labels: t: bug, s: positive review, p: critical / 2, c: scripts

#35205 remove deprecated slicing semantics of polynomials
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/padics/polynomial_padic_capped_relative_dense.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/power_series_poly.pyx
Labels: s: positive review, c: commutative algebra

#35056 Make automatic codecov report less noisy
  .codecov.yml
Labels: p: major / 3, s: positive review

#35080 Use the Docker images published on ghcr.io without 'docker' in the name
  .devcontainer/portability-Dockerfile
  src/doc/en/developer/portability_testing.rst
  tox.ini
Labels: s: positive review, p: blocker / 1

#35111 Partly fix conda ci and update python versions tested
  .github/workflows/ci-conda.yml
Labels: s: positive review, c: porting

#35113 added check for invalid range in contour_plot and derivatives
  src/sage/plot/misc.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: graphics

#35115 Make the key polynomials know their degree
  src/sage/combinat/key_polynomial.py
Labels: t: bug, s: positive review, p: critical / 2, c: combinatorics

#35117 fix pep E303 in modular/ and algebras/
  src/sage/algebras/splitting_algebra.py
  src/sage/modular/abvar/cuspidal_subgroup.py
  src/sage/modular/abvar/morphism.py
  src/sage/modular/arithgroup/arithgroup_perm.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/local_comp/local_comp.py
  src/sage/modular/modform/ambient_R.py
  src/sage/modular/modform/cuspidal_submodule.py
  src/sage/modular/modform/eis_series.py
  src/sage/modular/modform/numerical.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform/vm_basis.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/constructor.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/subspace.py
  src/sage/modular/modsym/tests.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/modsym.py
Labels: s: positive review, t: refactoring

#35118 `sage.env.sage_include_directories`: Don't use `distutils` and `SAGE_LIB`
  src/sage/env.py
Labels: s: positive review

#35123 fixing most of pycodestyle E271
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/categories/function_fields.py
  src/sage/coding/information_set_decoder.py
  src/sage/combinat/matrices/hadamard_matrix.py
  src/sage/combinat/t_sequences.py
  src/sage/crypto/mq/sr.py
  src/sage/databases/knotinfo_db.py
  src/sage/games/quantumino.py
  src/sage/geometry/cone.py
  src/sage/geometry/hyperbolic_space/hyperbolic_isometry.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/geometry/ribbon_graph.py
  src/sage/geometry/riemannian_manifolds/parametrized_surface3d.py
  src/sage/graphs/generic_graph.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/perm_gps/cubegroup.py
  src/sage/interacts/library.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/tides.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/manifolds/differentiable/affine_connection.py
  src/sage/manifolds/differentiable/vectorfield.py
  src/sage/modular/hecke/hecke_operator.py
  src/sage/modular/overconvergent/all.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/quadratic_form__ternary_Tornaria.py
  src/sage/sets/non_negative_integers.py
  src/sage/symbolic/units.py
  src/sage/tensor/modules/tensor_with_indices.py
Labels: s: positive review

#35127 Fix a very slow doctest in `sage/data_structures/stream.py`
  src/sage/data_structures/stream.py
Labels: s: positive review, p: critical / 2, t: tests

#35128 Fix French notation for Tableau plots
  src/sage/combinat/tableau.py
Labels: s: positive review, c: combinatorics, c: graphics

#35131 PR for issue 32136: Add parameter 'induced' to `connected_subgraphs_iterator`
  src/sage/graphs/base/static_dense_graph.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: graph theory

#35132 fix pep8 E303 in various folders (plot, quadratic forms, etc)
  src/sage/plot/animate.py
  src/sage/plot/matrix_plot.py
  src/sage/plot/plot.py
  src/sage/plot/plot3d/tri_plot.py
  src/sage/plot/primitive.py
  src/sage/quadratic_forms/constructions.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/quadratic_form__count_local_2.py
  src/sage/quadratic_forms/quadratic_form__equivalence_testing.py
  src/sage/quadratic_forms/quadratic_form__local_density_interfaces.py
  src/sage/quadratic_forms/quadratic_form__local_field_invariants.py
  src/sage/quadratic_forms/quadratic_form__local_normal_form.py
  src/sage/quadratic_forms/quadratic_form__mass.py
  src/sage/quadratic_forms/quadratic_form__mass__Conway_Sloane_masses.py
  src/sage/quadratic_forms/quadratic_form__mass__Siegel_densities.py
  src/sage/quadratic_forms/quadratic_form__siegel_product.py
  src/sage/quadratic_forms/quadratic_form__split_local_covering.py
  src/sage/quadratic_forms/quadratic_form__theta.py
  src/sage/repl/rich_output/output_graphics3d.py
  src/sage/sandpiles/examples.py
  src/sage/sets/disjoint_union_enumerated_sets.py
  src/sage/sets/set_from_iterator.py
  src/sage/structure/factorization.py
  src/sage/structure/set_factories.py
  src/sage/symbolic/constants.py
  src/sage/symbolic/units.py
Labels: s: positive review, t: refactoring

#35135 `sage.geometry.integral_points`: Use generic impl if no `matrix_integer_dense`
  src/sage/geometry/integral_points.pxi
  src/sage/geometry/integral_points.py
  src/sage/geometry/integral_points_generic_dense.pyx
  src/sage/geometry/integral_points_integer_dense.pyx
  src/sage/matrix/matrix_space.py
Labels: s: positive review, c: geometry, c: cython, t: refactoring

#35138 Allow skew tableaux to be hashed
  src/sage/combinat/skew_tableau.py
Labels: p: minor / 4, s: positive review, c: combinatorics

#35140 Update normaliz to 3.10.0, update e_antic, pynormaliz
  build/pkgs/e_antic/checksums.ini
  build/pkgs/e_antic/package-version.txt
  build/pkgs/normaliz/checksums.ini
  build/pkgs/normaliz/package-version.txt
  build/pkgs/pynormaliz/checksums.ini
  build/pkgs/pynormaliz/install-requires.txt
  build/pkgs/pynormaliz/package-version.txt
Labels: s: positive review, c: packages: optional, c: commutative algebra, c: geometry

#35141 Revise the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s: positive review

#35142 Fix broken link in README
  README.md
Labels: s: positive review

#35146 Equal hashes for non-isomorphic bipartite graphs with edge labels
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/digraph.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
Labels: p: major / 3, t: enhancement, s: positive review, c: graph theory

#35153 `sage.matrix.operation_table`: Modularization and code style fixes
  src/sage/matrix/operation_table.py
Labels: s: positive review, c: graphics, t: refactoring

#35155 Update the logo at README.md
  README.md
Labels: t: enhancement, s: positive review, p: critical / 2, c: documentation

#35156 Fix index out of range exception (#35031)
  src/sage/plot/arrow.py
Labels: s: positive review, c: graphics

#35160 Move `filterwarnings` calls from `sage.all` to `sage.all__sagemath_repl`
  src/sage/all.py
  src/sage/all__sagemath_repl.py
Labels: s: positive review, c: doctest framework, t: refactoring
