Repository sagemath/sage, pull requests merged in 2023-02, with the labels that each got.

#34964 Fix linter issues
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/combinat/vector_partition.py
  src/sage/modular/modform/notes.py
  src/sage/rings/generic.py
  src/sage/sat/solvers/dimacs.py
Labels: s: positive review, p: blocker / 1

#34987 add missing #long time markers to ell_number_field
  src/sage/schemes/elliptic_curves/ell_number_field.py
Labels: s: positive review, p: blocker / 1

#34983 Add issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/failure_building_from_source.yml
  .github/ISSUE_TEMPLATE/feature_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s: positive review, p: critical / 2

#35018 undo ancient hack to resolve #35017
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: t: bug, s: positive review, t: tests, c: elliptic curves, p: blocker / 1

#35022 Add best-practices for PR titles to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s: needs review

#34984 Fix deployment of docs to netlify
  .github/workflows/doc-build.yml
  .github/workflows/doc-publish.yml
Labels: s: positive review, c: documentation, p: blocker / 1

#35109 Fix W391 linter issues
  src/sage/combinat/key_polynomial.py
  src/sage/combinat/schubert_polynomial.py
  src/sage/groups/cactus_group.py
  src/sage/groups/finitely_presented_named.py
  src/sage/groups/kernel_subgroup.py
  src/sage/groups/misc_gps/misc_groups_catalog.py
Labels: s: positive review, p: blocker / 1

#35126 tox.ini (fedora-33): Do not set IGNORE_MISSING_SYSTEM_PACKAGES=no
  tox.ini
Labels: s: needs review, c: porting

#35058 Mark unstable tests in klyachko.py due to #32773
  src/sage/schemes/toric/sheaf/klyachko.py
Labels: s: positive review, p: critical / 2, c: algebraic geometry

#35125 ci-linux: Remove unmaintained local-conda runs
  .github/workflows/ci-linux.yml
Labels: s: positive review, c: porting

#35052 Fix Cygwin CI after #32841
  .github/workflows/ci-cygwin-minimal.yml
  .github/workflows/ci-cygwin-standard.yml
Labels: s: positive review, p: blocker / 1

#35072 Add default devcontainer using conda
  .devcontainer/devcontainer.json
  .devcontainer/onCreate-conda.sh
  .gitignore
  src/doc/en/developer/portability_testing.rst
Labels: p: major / 3, s: positive review

#34960 Improve camera positioning for threejs
  src/sage/ext_data/threejs/threejs_template.html
Labels: t: enhancement, p: minor / 4, s: positive review, c: graphics

#34967 show explicit formulas in documentation of WeierstrassIsomorphism
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#34968 compute matrix kernels modulo composites
  src/sage/geometry/polyhedron/ppl_lattice_polytope.py
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_modn_dense_template.pxi
Labels: p: major / 3, t: enhancement, s: positive review, c: linear algebra

#34972 Cross-link matrix methods image and column_space
  src/sage/matrix/matrix2.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: linear algebra

#34974 SignedPermutation should allow iterables as input
  src/sage/combinat/colored_permutations.py
Labels: p: major / 3, t: bug, s: positive review, c: combinatorics

#34982 add .torsion_basis() method to EllipticCurve_finite_field
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#34963 Add doctest for #20847
  src/sage/rings/power_series_poly.pyx
Labels: t: bug, p: minor / 4, s: positive review, c: algebra

#34981 add .twists() to EllipticCurve_finite_field
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#34985 Add new skew hadamard matrices
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/matrices/hadamard_matrix.py
Labels: p: major / 3, t: enhancement, s: positive review, c: linear algebra, c: combinatorics

#34994 fix doctests to support numpy 1.24
  src/sage/misc/persist.pyx
  src/sage/plot/complex_plot.pyx
  src/sage/plot/histogram.py
  src/sage/repl/ipython_extension.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#34997 Fix bug due to UB in conversion from python int to ZZ (python 3.11, 32 bit, gcc12)
  src/sage/arith/long.pxd
Labels: c: basic arithmetic, s: positive review, p: blocker / 1

#34999 Enable dependabot for github action updates
  .github/dependabot.yml
Labels: p: major / 3, s: positive review

#35001 add doctest for #20846
  src/sage/symbolic/expression.pyx
Labels: s: positive review

#35003 add doctest for #16031
  src/sage/symbolic/expression.pyx
Labels: p: minor / 4, s: positive review, t: tests, c: symbolics

#35004 Speed up some methods for quasimodular forms ring elements
  src/sage/modular/quasimodform/element.py
Labels: p: major / 3, t: enhancement, s: positive review, c: modular forms

#35007 Fix some cannot
  src/sage/combinat/alternating_sign_matrix.py
  src/sage/combinat/decorated_permutation.py
  src/sage/combinat/derangements.py
  src/sage/data_structures/bounded_integer_sequences.pyx
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/parent.py
  src/sage/libs/giac/giac.pyx
  src/sage/libs/pari/convert_sage.pyx
  src/sage/libs/singular/function.pyx
  src/sage/modules/vector_rational_dense.pyx
  src/sage/rings/asymptotic/asymptotic_ring.py
  src/sage/rings/integer.pyx
  src/sage/rings/number_field/number_field.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_real_mpfr_dense.pyx
  src/sage/rings/real_double.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/universal_cyclotomic_field.py
  src/sage/schemes/generic/ambient_space.py
  src/sage/structure/coerce_maps.pyx
  src/sage/structure/element.pyx
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/ring.pyx
  src/sage/symbolic/series_impl.pxi
  src/sage/symbolic/subring.py
  src/sage/symbolic/units.py
Labels: p: minor / 4, s: positive review, t: refactoring

#35010 add doctest for #13569
  src/sage/groups/perm_gps/permgroup_element.pyx
Labels: s: positive review, t: tests, c: group theory

#34966 use NTL's MinPolyMod() for more rings
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra
