Repository sagemath/sage, pull requests merged in 2023-09, with the labels that each got.

#36088 add some links to python error classes in the doc
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra.py
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_morphism.py
  src/sage/algebras/free_algebra_quotient.py
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/algebras/fusion_rings/shm_managers.pyx
  src/sage/algebras/lie_algebras/verma_module.py
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/arith/long.pxd
  src/sage/arith/misc.py
  src/sage/arith/multi_modular.pyx
  src/sage/arith/rational_reconstruction.pyx
  src/sage/calculus/var.pyx
  src/sage/categories/map.pyx
  src/sage/combinat/binary_recurrence_sequences.py
  src/sage/combinat/descent_algebra.py
  src/sage/combinat/designs/covering_design.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/morphism.py
  src/sage/combinat/words/word_datatypes.pyx
  src/sage/cpython/getattr.pyx
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/homology/chain_complex_morphism.py
  src/sage/interfaces/magma.py
  src/sage/interfaces/mwrank.py
  src/sage/libs/eclib/constructor.py
  src/sage/libs/ntl/ntl_ZZX.pyx
  src/sage/libs/ntl/ntl_ZZ_pEX.pyx
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/manifolds/subsets/pullback.py
  src/sage/matrix/special.py
  src/sage/matroids/graphic_matroid.py
  src/sage/matroids/matroid.pyx
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/plot/graphics.py
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/function_field/function_field_rational.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/universal_cyclotomic_field.py
  src/sage/sets/condition_set.py
  src/sage/structure/coerce.pyx
  src/sage/symbolic/units.py
  src/sage/tensor/modules/tensor_with_indices.py
  src/sage/tests/cmdline.py
Labels: s: positive review, c: documentation

#36117 run GitHub actions locally using gh act
  src/doc/en/developer/github.rst
  src/doc/en/developer/portability_testing.rst
Labels: s: positive review, c: documentation

#36127 Bandaid for polynomial evaluation
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: commutative algebra

#36136 `sage.combinat.root_system`: Modularization fixes, `# needs`
  src/sage/combinat/root_system/ambient_space.py
  src/sage/combinat/root_system/associahedron.py
  src/sage/combinat/root_system/braid_move_calculator.py
  src/sage/combinat/root_system/branching_rules.py
  src/sage/combinat/root_system/cartan_matrix.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/combinat/root_system/coxeter_group.py
  src/sage/combinat/root_system/coxeter_matrix.py
  src/sage/combinat/root_system/coxeter_type.py
  src/sage/combinat/root_system/dynkin_diagram.py
  src/sage/combinat/root_system/extended_affine_weyl_group.py
  src/sage/combinat/root_system/fundamental_group.py
  src/sage/combinat/root_system/hecke_algebra_representation.py
  src/sage/combinat/root_system/integrable_representations.py
  src/sage/combinat/root_system/non_symmetric_macdonald_polynomials.py
  src/sage/combinat/root_system/pieri_factors.py
  src/sage/combinat/root_system/plot.py
  src/sage/combinat/root_system/reflection_group_c.pyx
  src/sage/combinat/root_system/reflection_group_complex.py
  src/sage/combinat/root_system/reflection_group_element.pyx
  src/sage/combinat/root_system/reflection_group_real.py
  src/sage/combinat/root_system/root_lattice_realization_algebras.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/root_system/root_space.py
  src/sage/combinat/root_system/root_system.py
  src/sage/combinat/root_system/type_A.py
  src/sage/combinat/root_system/type_A_affine.py
  src/sage/combinat/root_system/type_B.py
  src/sage/combinat/root_system/type_BC_affine.py
  src/sage/combinat/root_system/type_B_affine.py
  src/sage/combinat/root_system/type_C.py
  src/sage/combinat/root_system/type_C_affine.py
  src/sage/combinat/root_system/type_D.py
  src/sage/combinat/root_system/type_D_affine.py
  src/sage/combinat/root_system/type_E.py
  src/sage/combinat/root_system/type_E_affine.py
  src/sage/combinat/root_system/type_F.py
  src/sage/combinat/root_system/type_F_affine.py
  src/sage/combinat/root_system/type_G.py
  src/sage/combinat/root_system/type_G_affine.py
  src/sage/combinat/root_system/type_H.py
  src/sage/combinat/root_system/type_I.py
  src/sage/combinat/root_system/type_affine.py
  src/sage/combinat/root_system/type_dual.py
  src/sage/combinat/root_system/type_folded.py
  src/sage/combinat/root_system/type_marked.py
  src/sage/combinat/root_system/type_reducible.py
  src/sage/combinat/root_system/type_relabel.py
  src/sage/combinat/root_system/type_super_A.py
  src/sage/combinat/root_system/weight_lattice_realizations.py
  src/sage/combinat/root_system/weight_space.py
  src/sage/combinat/root_system/weyl_characters.py
  src/sage/combinat/root_system/weyl_group.py
Labels: s: positive review, c: combinatorics, t: refactoring

#36139 fix Conrey number of trivial Dirichlet character
  src/sage/modular/dirichlet.py
Labels: s: positive review, c: number theory

#36142 python-style loops in `sage.graphs`
  src/sage/graphs/chrompoly.pyx
  src/sage/graphs/matchpoly.pyx
Labels: s: positive review, c: graph theory

#36143 Fix two "Computational Math.." book doctests
  src/sage/tests/books/computational-mathematics-with-sagemath/integration_doctest.py
  src/sage/tests/books/computational-mathematics-with-sagemath/recequadiff_doctest.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: documentation

#36145 build/pkgs/mathjax/distros/gentoo.txt: Fix
  build/pkgs/mathjax/distros/gentoo.txt
Labels: s: positive review, c: distribution

#36148 fix the 2 broken linters
  src/sage/dynamics/arithmetic_dynamics/dynamical_semigroup.py
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
Labels: p: major / 3, s: positive review, t: refactoring

#36149 Fix doctest in `src/sage/algebras/quantum_groups/quantum_group_gap.py`
  src/sage/algebras/quantum_groups/quantum_group_gap.py
Labels: t: bug, s: positive review, p: trivial / 5

#36155 random elt for colored permutations
  src/sage/combinat/colored_permutations.py
Labels: s: positive review, c: combinatorics

#36156 detect the zero series when returning an exact stream
  src/sage/rings/lazy_series.py
Labels: s: positive review, c: algebra

#36157 some pep for E30 and more in quadratic forms
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/qfsolve.py
  src/sage/quadratic_forms/quadratic_form__neighbors.py
  src/sage/quadratic_forms/quadratic_form__siegel_product.py
  src/sage/quadratic_forms/special_values.py
Labels: s: positive review, c: quadratic forms, t: refactoring

#36095 Implementing a generic one method for unital algebras
  src/sage/categories/algebras.py
  src/sage/categories/algebras_with_basis.py
  src/sage/categories/unital_algebras.py
Labels: p: major / 3, t: bug, t: enhancement, s: positive review, c: algebra, c: categories

#36105 `sage.rings.finite_rings.element_*`: Remove unused imports
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_ntl_gf2e.py
Labels: s: positive review, c: finite rings, t: refactoring

#36115 small improvements for functorial composition
  src/sage/rings/lazy_series.py
Labels: s: positive review, c: algebra

#35338 improve performance of stream cauchy invert
  src/sage/data_structures/stream.py
Labels: s: positive review, c: combinatorics, c: algebra

#35376 Update Zariski-van Kampen functions
  src/doc/en/reference/curves/index.rst
  src/sage/groups/finitely_presented.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/curves/zariski_vankampen.py
Labels: t: enhancement, s: positive review, c: algebraic geometry, c: group theory

#36111 using PyLong API instead of legacy PyInt API
  src/sage/arith/long.pxd
  src/sage/data_structures/bounded_integer_sequences.pyx
  src/sage/geometry/triangulation/triangulations.cc
  src/sage/geometry/triangulation/triangulations.h
  src/sage/libs/gmp/pylong.pyx
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/modular/arithgroup/farey.cpp
  src/sage/modular/arithgroup/farey.hpp
  src/sage/rings/complex_arb.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/padics/FM_template.pxi
  src/sage/rings/padics/FP_template.pxi
  src/sage/rings/padics/common_conversion.pyx
  src/sage/rings/padics/padic_template_element.pxi
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_real_mpfr_dense.pyx
  src/sage/rings/real_arb.pyx
  src/sage/structure/coerce_actions.pyx
  src/sage/structure/list_clone.pyx
  src/sage/symbolic/ginac/numeric.cpp
Labels: p: major / 3, s: positive review, t: refactoring

#36112 Upgrades: scipy 1.11 and dependencies
  build/pkgs/cmake/checksums.ini
  build/pkgs/cmake/package-version.txt
  build/pkgs/gast/checksums.ini
  build/pkgs/gast/package-version.txt
  build/pkgs/meson/checksums.ini
  build/pkgs/meson/package-version.txt
  build/pkgs/meson/spkg-configure.m4
  build/pkgs/meson_python/checksums.ini
  build/pkgs/meson_python/package-version.txt
  build/pkgs/meson_python/patches/ARCHFLAGS_empty.patch
  build/pkgs/ninja_build/checksums.ini
  build/pkgs/ninja_build/package-version.txt
  build/pkgs/pybind11/checksums.ini
  build/pkgs/pybind11/package-version.txt
  build/pkgs/pyproject_metadata/checksums.ini
  build/pkgs/pyproject_metadata/package-version.txt
  build/pkgs/pythran/checksums.ini
  build/pkgs/pythran/package-version.txt
  build/pkgs/sagelib/dependencies
  build/pkgs/scipy/checksums.ini
  build/pkgs/scipy/install-requires.txt
  build/pkgs/scipy/package-version.txt
Labels: c: packages: standard, s: positive review, p: critical / 2

#36151 Coxeter arrangement
  src/doc/en/reference/references/index.rst
  src/sage/geometry/hyperplane_arrangement/library.py
Labels: t: enhancement, s: positive review, c: combinatorics

#36162 minor details in graph_plot
  src/sage/graphs/graph_plot.py
Labels: s: positive review, c: graphics

#36170 Fix the ascii art for the Heisenberg Lie algebras
  src/sage/algebras/lie_algebras/heisenberg.py
Labels: t: bug, s: positive review, c: algebra

#36173 Fix quadratic memory of berlekamp_massey
  src/sage/matrix/berlekamp_massey.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#36177 fix and activate pycodestyle E305 in py files
  .vscode/settings.json
  src/sage/algebras/lie_algebras/examples.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/ext_rep.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/matrix_gps/morphism.py
  src/sage/groups/perm_gps/cubegroup.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/libs/pari/__init__.py
  src/sage/matrix/matrix_polynomial_dense.pyx
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/modular/pollack_stevens/sigma0.py
  src/sage/modular/pollack_stevens/space.py
  src/sage/modules/fg_pid/fgp_morphism.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage_docbuild/__main__.py
  src/sage_docbuild/conf.py
  src/sage_docbuild/ext/sage_autodoc.py
  src/sage_setup/autogen/interpreters/storage.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#36179 Improve methods in `sage.misc.rest_index_of_methods` to fix the documentation of graphs.
  src/sage/graphs/digraph.py
  src/sage/graphs/generators/chessboard.py
  src/sage/graphs/isgci.py
  src/sage/misc/rest_index_of_methods.py
Labels: t: bug, s: positive review, c: documentation, c: graph theory

#36180 more fixes in quadratic forms
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/quadratic_form__local_normal_form.py
Labels: s: positive review, c: quadratic forms

#36182 fix E228 and E225 in algebras/
  src/sage/algebras/affine_nil_temperley_lieb.py
  src/sage/algebras/cellular_basis.py
  src/sage/algebras/down_up_algebra.py
  src/sage/algebras/free_algebra.py
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/algebras/hecke_algebras/ariki_koike_algebra.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/algebras/lie_algebras/heisenberg.py
  src/sage/algebras/lie_conformal_algebras/free_fermions_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_with_structure_coefs.py
  src/sage/algebras/nil_coxeter_algebra.py
  src/sage/algebras/orlik_solomon.py
  src/sage/algebras/quantum_clifford.py
  src/sage/algebras/splitting_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra_bases.py
  src/sage/algebras/steenrod/steenrod_algebra_misc.py
  src/sage/algebras/yokonuma_hecke_algebra.py
Labels: s: positive review, t: refactoring

#36183 `sage.misc.sageinspect`: fix doctest warnings due to modularisation
  src/sage/misc/sageinspect.py
Labels: s: positive review, p: trivial / 5, t: refactoring

#36185 src/sage/tests: fix another "Computational Math..." doctest
  src/sage/tests/books/computational-mathematics-with-sagemath/graphique_doctest.py
Labels: s: positive review

#36187 use semi-primitive root when checking kernel polynomials of isogenies
  src/sage/schemes/elliptic_curves/isogeny_small_degree.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#36191 fix E228 and E225 in schemes/
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/padics.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/generic/glue.py
  src/sage/schemes/generic/hypersurface.py
  src/sage/schemes/generic/morphism.py
  src/sage/schemes/generic/point.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_g2.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_rational_field.py
  src/sage/schemes/hyperelliptic_curves/jacobian_endomorphism_utils.py
  src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
  src/sage/schemes/hyperelliptic_curves/mestre.py
  src/sage/schemes/jacobians/abstract_jacobian.py
  src/sage/schemes/plane_conics/con_field.py
  src/sage/schemes/product_projective/homset.py
  src/sage/schemes/product_projective/morphism.py
  src/sage/schemes/product_projective/point.py
  src/sage/schemes/product_projective/space.py
  src/sage/schemes/product_projective/subscheme.py
  src/sage/schemes/projective/projective_homset.py
  src/sage/schemes/projective/projective_point.py
  src/sage/schemes/projective/projective_subscheme.py
Labels: s: positive review, t: refactoring

#36192 fix E228 then E225 in rings/
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/complex_interval_field.py
  src/sage/rings/finite_rings/conway_polynomials.py
  src/sage/rings/finite_rings/finite_field_givaro.py
  src/sage/rings/finite_rings/finite_field_ntl_gf2e.py
  src/sage/rings/finite_rings/homset.py
  src/sage/rings/function_field/constructor.py
  src/sage/rings/function_field/divisor.py
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/function_field/function_field_rational.py
  src/sage/rings/function_field/order.py
  src/sage/rings/function_field/order_basis.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/function_field/order_rational.py
  src/sage/rings/function_field/place_polymod.py
  src/sage/rings/function_field/place_rational.py
  src/sage/rings/homset.py
  src/sage/rings/ideal.py
  src/sage/rings/invariants/invariant_theory.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/number_field/S_unit_solver.py
  src/sage/rings/number_field/class_group.py
  src/sage/rings/number_field/homset.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/number_field_ideal_rel.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/number_field/selmer_group.py
  src/sage/rings/number_field/splitting_field.py
  src/sage/rings/number_field/totallyreal_phc.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/rings/number_field/unit_group.py
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/padics/lattice_precision.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/misc.py
  src/sage/rings/padics/padic_base_generic.py
  src/sage/rings/padics/padic_base_leaves.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/padics/padic_valuation.py
  src/sage/rings/polynomial/ideal.py
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_quotient_ring_element.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/symmetric_ideal.py
  src/sage/rings/polynomial/term_order.py
  src/sage/rings/power_series_ring.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/valuation/valuation.py
  src/sage/rings/valuation/valuation_space.py
  src/sage/rings/valuation/value_group.py
Labels: s: positive review, t: refactoring

#36195 schemes/elliptic_curves: disable a test that takes too long
  src/sage/schemes/elliptic_curves/ell_rational_field.py
Labels: s: positive review

#36200 Fixing the iterator of SemistandardMultiSkewTableaux
  src/sage/combinat/ribbon_tableau.py
Labels: p: major / 3, t: bug, s: positive review, c: combinatorics

#36202 some micro-details in Dyck words and Parking functions
  src/sage/combinat/dyck_word.py
  src/sage/combinat/parking_functions.py
Labels: s: positive review, c: combinatorics

#36207 Remove self-`cimport`s
  src/sage/algebras/quatalg/quaternion_algebra_element.pyx
  src/sage/graphs/base/boost_graph.pyx
  src/sage/graphs/comparability.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/libs/flint/fmpz_poly.pyx
  src/sage/libs/flint/qsieve.pyx
  src/sage/matrix/matrix_modn_sparse.pxd
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/modules/vector_modn_sparse.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/ring_extension.pxd
  src/sage/symbolic/constants_c_impl.pxi
  src/sage/symbolic/expression.pyx
Labels: s: positive review, c: cython, t: refactoring

#35380 GH Actions: Run incremental portability tests on "c: packages: standard" PRs
  .github/workflows/ci-conda.yml
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/docker.yml
  build/make/Makefile.in
  build/pkgs/kissat/checksums.ini
  build/pkgs/kissat/package-version.txt
  build/pkgs/libbraiding/package-version.txt
Labels: c: packages: standard, s: positive review

#35907 Deprecate rename_vertices parameter in disjoint_union
  src/sage/topology/simplicial_complex.py
Labels: t: enhancement, s: positive review, c: algebraic topology

#35985 More improvements for braid groups involving permutations, and a 2-generator presentation
  src/doc/en/reference/groups/index.rst
  src/sage/groups/artin.py
  src/sage/groups/braid.py
Labels: t: enhancement, s: positive review, c: group theory

#36006 Fix tests with gmp 6.3
  src/sage/ext/memory.pyx
  src/sage/rings/integer.pyx
Labels: s: positive review, p: critical / 2

#36021 Improve method is_planar
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/planarity.pyx
Labels: t: bug, s: positive review, c: graph theory

#35939 Support for exponential and gamma distribution
  src/sage/probability/probability_distribution.pyx
Labels: t: enhancement, s: positive review

#36186 Drop obsolete html5lib package
  build/pkgs/html5lib/SPKG.rst
  build/pkgs/html5lib/checksums.ini
  build/pkgs/html5lib/dependencies
  build/pkgs/html5lib/distros/arch.txt
  build/pkgs/html5lib/distros/conda.txt
  build/pkgs/html5lib/distros/debian.txt
  build/pkgs/html5lib/distros/fedora.txt
  build/pkgs/html5lib/distros/gentoo.txt
  build/pkgs/html5lib/distros/macports.txt
  build/pkgs/html5lib/distros/opensuse.txt
  build/pkgs/html5lib/distros/repology.txt
  build/pkgs/html5lib/distros/void.txt
  build/pkgs/html5lib/install-requires.txt
  build/pkgs/html5lib/package-version.txt
  build/pkgs/html5lib/spkg-configure.m4
  build/pkgs/html5lib/spkg-install.in
  build/pkgs/html5lib/type
  build/pkgs/nbconvert/dependencies
Labels: t: enhancement, c: packages: standard, s: positive review

#36206 Remove some obsolete "six" dependencies
  build/pkgs/cycler/dependencies
  build/pkgs/matplotlib/dependencies
  build/pkgs/traitlets/dependencies
Labels: s: positive review

#36210 configure.ac: disable mathjax with --disable-doc
  configure.ac
Labels: s: positive review

#36212 singular: added missing #endif
  build/pkgs/singular/spkg-configure.m4
Labels: s: positive review, p: critical / 2

#36213 Fix sync labels issues for step 2 going live
  .github/sync_labels.py
Labels: s: positive review

#36218 src/bin/sage-env: set PYDEVD_DISABLE_FILE_VALIDATION=1
  src/bin/sage-env
Labels: s: positive review, c: packages: optional

#36219 configure.ac: disable webencodings,tinycss2 with --disable-notebook
  configure.ac
Labels: s: positive review, c: build: configure

#36221 get rid of xrange again
  src/sage/cpython/_py2_random.py
  src/sage/geometry/integral_points.pxi
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_sets.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/misc/misc_c.pyx
  src/sage/modular/modsym/relation_matrix_pyx.pyx
  src/sage/numerical/backends/generic_backend.pyx
  src/sage/numerical/mip.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review

#36224 Add cycle_type() and fix to_cycle() to SignedPermutation.
  src/sage/combinat/colored_permutations.py
  src/sage/combinat/permutation.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics

#36225 improve the use of graphs in `sage/combinat/posets/*`
  src/sage/combinat/posets/d_complete.py
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/mobile.py
  src/sage/combinat/posets/posets.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: graph theory

#36232 Make `min_spanning_tree` robust to incomparable vertex labels
  src/sage/graphs/base/boost_graph.pyx
  src/sage/graphs/generic_graph.py
  src/sage/graphs/spanning_tree.pyx
  src/sage/matroids/utilities.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review, c: graph theory

#36235 support for ecl 23.9.9
  src/sage/libs/ecl.pyx
  src/sage/libs/eclsig.h
Labels: c: packages: standard, s: positive review, p: blocker / 1

#36247 fix E228 and E225 in categories/
  src/sage/categories/bimodules.py
  src/sage/categories/cartesian_product.py
  src/sage/categories/category.py
  src/sage/categories/category_types.py
  src/sage/categories/commutative_ring_ideals.py
  src/sage/categories/commutative_rings.py
  src/sage/categories/covariant_functorial_construction.py
  src/sage/categories/crystals.py
  src/sage/categories/dual.py
  src/sage/categories/enumerated_sets.py
  src/sage/categories/examples/algebras_with_basis.py
  src/sage/categories/examples/commutative_additive_monoids.py
  src/sage/categories/examples/commutative_additive_semigroups.py
  src/sage/categories/examples/crystals.py
  src/sage/categories/examples/finite_dimensional_algebras_with_basis.py
  src/sage/categories/examples/finite_monoids.py
  src/sage/categories/examples/finite_semigroups.py
  src/sage/categories/examples/finite_weyl_groups.py
  src/sage/categories/examples/hopf_algebras_with_basis.py
  src/sage/categories/examples/monoids.py
  src/sage/categories/examples/semigroups.py
  src/sage/categories/examples/sets_cat.py
  src/sage/categories/examples/with_realizations.py
  src/sage/categories/facade_sets.py
  src/sage/categories/fields.py
  src/sage/categories/finite_coxeter_groups.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/finite_dimensional_semisimple_algebras_with_basis.py
  src/sage/categories/finite_enumerated_sets.py
  src/sage/categories/finite_fields.py
  src/sage/categories/finite_groups.py
  src/sage/categories/finite_posets.py
  src/sage/categories/g_sets.py
  src/sage/categories/groupoid.py
  src/sage/categories/groups.py
  src/sage/categories/hecke_modules.py
  src/sage/categories/homset.py
  src/sage/categories/homsets.py
  src/sage/categories/modules_with_basis.py
  src/sage/categories/poor_man_map.py
  src/sage/categories/principal_ideal_domains.py
  src/sage/categories/pushout.py
  src/sage/categories/regular_crystals.py
  src/sage/categories/schemes.py
  src/sage/categories/sets_cat.py
  src/sage/categories/unique_factorization_domains.py
  src/sage/categories/vector_bundles.py
  src/sage/categories/vector_spaces.py
  src/sage/categories/weyl_groups.py
Labels: s: positive review, t: refactoring

#36248 some care for unused variables in matrix/
  src/sage/matrix/args.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
  src/sage/matrix/matrix_sparse.pyx
  src/sage/matrix/matrix_window.pyx
  src/sage/matrix/strassen.pyx
Labels: s: positive review, c: linear algebra, t: refactoring

#36249 E228 and E225 in groups,interfaces,modules,plot
  src/sage/groups/cubic_braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/finitely_presented_named.py
  src/sage/groups/fqf_orthogonal.py
  src/sage/groups/free_group.py
  src/sage/groups/libgap_morphism.py
  src/sage/interfaces/axiom.py
  src/sage/interfaces/four_ti_2.py
  src/sage/interfaces/frobby.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/gap3.py
  src/sage/interfaces/genus2reduction.py
  src/sage/interfaces/gnuplot.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/jmoldata.py
  src/sage/interfaces/lisp.py
  src/sage/interfaces/macaulay2.py
  src/sage/interfaces/magma_free.py
  src/sage/interfaces/maxima.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/maxima_lib.py
  src/sage/interfaces/mupad.py
  src/sage/interfaces/mwrank.py
  src/sage/interfaces/octave.py
  src/sage/interfaces/psage.py
  src/sage/interfaces/qepcad.py
  src/sage/interfaces/quit.py
  src/sage/interfaces/r.py
  src/sage/interfaces/scilab.py
  src/sage/interfaces/singular.py
  src/sage/interfaces/tests.py
  src/sage/interfaces/tides.py
  src/sage/modules/fg_pid/fgp_element.py
  src/sage/modules/fg_pid/fgp_morphism.py
  src/sage/modules/free_module.py
  src/sage/modules/free_module_morphism.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/vector_callable_symbolic_dense.py
  src/sage/modules/with_basis/morphism.py
  src/sage/plot/animate.py
  src/sage/plot/circle.py
  src/sage/plot/density_plot.py
  src/sage/plot/ellipse.py
  src/sage/plot/hyperbolic_regular_polygon.py
  src/sage/plot/matrix_plot.py
  src/sage/plot/misc.py
  src/sage/plot/plot.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/plot/plot3d/tri_plot.py
  src/sage/plot/plot_field.py
Labels: s: positive review, t: refactoring

#36250 various details in sets/disjoint_set
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review, t: refactoring

#36255 numpy-1.25 compatibility
  src/sage/doctest/parsing.py
  src/sage/tests/books/computational-mathematics-with-sagemath/graphique_doctest.py
Labels: s: positive review, p: critical / 2

#35485 New comparison mode to lazy series and better undefined check
  src/sage/combinat/species/recursive_species.py
  src/sage/data_structures/stream.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
Labels: t: bug, s: positive review, c: algebra

#35767 add .basis_matrix() wrapper to quaternion orders
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: quadratic forms

#35875 Implementing moment angle complexes
  src/doc/en/reference/references/index.rst
  src/doc/en/reference/topology/index.rst
  src/sage/topology/all.py
  src/sage/topology/moment_angle_complex.py
  src/sage/topology/simplicial_complex.py
Labels: t: enhancement, s: positive review, c: algebraic topology

#35964 Matroids: Don't forget to check rank in `equals`, `is_isomorphism`
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/matroid.pyx
Labels: t: bug, s: positive review, c: matroid theory

#35970 src/sage/combinat/affine_permutation.py: Fix docstring markup
  src/sage/combinat/affine_permutation.py
Labels: s: positive review, c: documentation, c: combinatorics

#36165 Fix reduction of cusps for Gamma(N)
  src/sage/modular/arithgroup/congroup_gamma.py
Labels: s: positive review, c: modular forms

#36209 build/pkgs/ipython/dependencies: drop jinja2
  build/pkgs/ipython/dependencies
  build/pkgs/sagelib/dependencies
  src/setup.cfg.m4
Labels: s: positive review

#35038 Implement Milnor fiber and Coxeter complexes
  src/sage/categories/finite_complex_reflection_groups.py
  src/sage/categories/finite_coxeter_groups.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics

#35362 Implement infinite sums and products for lazy series
  src/sage/data_structures/stream.py
  src/sage/rings/lazy_series_ring.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#36122 Added hash function to elements of the fundamental group of an extended affine Weyl group
  src/sage/combinat/root_system/fundamental_group.py
Labels: t: bug, s: positive review, c: group theory

#36264 `sage --fixdoctests --update-known-test-failures`; silence modularized distributions in CI
  build/pkgs/sagemath_objects/spkg-install
  pkgs/sagemath-categories/known-test-failures.json
  pkgs/sagemath-categories/tox.ini
  pkgs/sagemath-environment/tox.ini
  pkgs/sagemath-objects/tox.ini
  pkgs/sagemath-repl/known-test-failures.json
  pkgs/sagemath-repl/tox.ini
  pkgs/sagemath-standard/tox.ini
  src/bin/sage-fixdoctests
  src/doc/en/developer/doctesting.rst
  src/sage/doctest/control.py
  src/sage/doctest/parsing.py
  src/sage/doctest/reporting.py
Labels: s: positive review, c: doctest framework, c: scripts

#36278 `sage.graphs`: some care with return ... else statements in some .pyx files
  src/sage/graphs/bliss.pyx
  src/sage/graphs/centrality.pyx
  src/sage/graphs/comparability.pyx
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/genus.pyx
  src/sage/graphs/graph_coloring.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/line_graph.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/views.pyx
  src/sage/graphs/weakly_chordal.pyx
Labels: t: enhancement, s: positive review, c: graph theory

#36279 Support for matplotlib-3.8.0
  src/sage/plot/graphics.py
Labels: c: packages: standard, s: positive review, p: critical / 2, c: graphics

#36281 remove unused vars in matrix/
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_sparse.pyx
Labels: s: positive review, c: linear algebra, t: refactoring

#36282 CI: Remove ubuntu-kinetic (defunct)
  .github/workflows/ci-linux.yml
  .github/workflows/docker.yml
  tox.ini
Labels: s: positive review

#36296 remove duplicate args in @options() in region_plot
  src/sage/plot/contour_plot.py
Labels: s: positive review, c: build, c: graphics

#36297 using more libgap instead of gap
  src/doc/en/thematic_tutorials/lie/weyl_groups.rst
  src/sage/arith/misc.py
  src/sage/combinat/matrices/latin.py
  src/sage/combinat/root_system/weyl_group.py
  src/sage/modular/arithgroup/arithgroup_perm.py
Labels: c: packages: standard, s: positive review, t: refactoring

#36300 Remove deprecated files from src/sage/homology (see #31925)
  src/sage/homology/cell_complex.py
  src/sage/homology/cubical_complex.py
  src/sage/homology/delta_complex.py
  src/sage/homology/examples.py
  src/sage/homology/simplicial_complex.py
  src/sage/homology/simplicial_complex_homset.py
  src/sage/homology/simplicial_complex_morphism.py
  src/sage/homology/simplicial_set.py
  src/sage/homology/simplicial_set_constructions.py
  src/sage/homology/simplicial_set_examples.py
  src/sage/homology/simplicial_set_morphism.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebraic topology

#36303 Remove `sage.finance`, deprecated in #32427 (2021)
  src/doc/en/reference/finance/conf.py
  src/doc/en/reference/finance/index.rst
  src/doc/en/reference/index.rst
  src/sage/all.py
  src/sage/finance/__init__.py
  src/sage/finance/all.py
  src/sage/finance/easter.py
  src/sage/finance/fractal.pyx
  src/sage/finance/markov_multifractal.py
  src/sage/finance/markov_multifractal_cython.pyx
  src/sage/finance/option.pyx
  src/sage/finance/stock.py
  src/sage/finance/time_series.py
  src/sage/stats/time_series.pyx
  src/sage/tests/books/computational-mathematics-with-sagemath/graphique_doctest.py
Labels: t: enhancement, s: positive review

#36305 `sage.media`, `sage.structure.graphics_file`: Remove; deprecated in #12673, #32988
  src/doc/en/reference/misc/index.rst
  src/sage/all.py
  src/sage/media/__init__.py
  src/sage/media/all.py
  src/sage/media/channels.pyx
  src/sage/media/wav.py
  src/sage/structure/graphics_file.py
Labels: t: enhancement, s: positive review

#36306 `sage.docs`: Remove; deprecated in #33763
  src/doc/en/reference/misc/index.rst
  src/sage/docs/__init__.py
  src/sage/docs/conf.py
  src/sage/docs/instancedoc.py
Labels: t: enhancement, s: positive review

#36307 `sage.rings`: Remove code deprecated in #23204, #24483, #24371, #24511, #25848, #26105, #28481, #29010, #29412, #30332, #30372, #31345, #32375, #32606, #32610, #32612, #32641, #32660, #32750, #32869, #33602
  src/sage/rings/all.py
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_field.py
  src/sage/rings/complex_interval_field.py
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/complex_number.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/morphism.pyx
  src/sage/rings/number_field/homset.py
  src/sage/rings/number_field/morphism.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/numbers_abc.py
  src/sage/rings/padics/all.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/polynomial/pbori/__init__.py
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/qqbar.py
  src/sage/rings/real_double.pyx
  src/sage/rings/real_interval_field.py
  src/sage/rings/real_mpfr.pyx
Labels: t: enhancement, s: positive review

#36128 Compute the characteristic varieties of a finitely presented group
  src/doc/en/reference/references/index.rst
  src/sage/groups/finitely_presented.py
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
Labels: t: enhancement, s: positive review, c: group theory

#36188 remove some old deprecation warnings in elliptic curves
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/hom_composite.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#36205 build/pkgs: drop obsolete simplegeneric package
  build/pkgs/ipython/dependencies
  build/pkgs/simplegeneric/SPKG.rst
  build/pkgs/simplegeneric/checksums.ini
  build/pkgs/simplegeneric/dependencies
  build/pkgs/simplegeneric/distros/conda.txt
  build/pkgs/simplegeneric/distros/gentoo.txt
  build/pkgs/simplegeneric/distros/macports.txt
  build/pkgs/simplegeneric/distros/opensuse.txt
  build/pkgs/simplegeneric/distros/repology.txt
  build/pkgs/simplegeneric/distros/void.txt
  build/pkgs/simplegeneric/install-requires.txt
  build/pkgs/simplegeneric/package-version.txt
  build/pkgs/simplegeneric/spkg-configure.m4
  build/pkgs/simplegeneric/spkg-install.in
  build/pkgs/simplegeneric/type
Labels: c: packages: standard, s: positive review

#36230 build/pkgs/networkx/dependencies: drop decorator
  build/pkgs/networkx/dependencies
Labels: c: packages: standard, s: positive review

#36239 Disable more packages with various --disable-foo combinations
  configure.ac
Labels: s: positive review, c: build: configure

#36252 no generator for S1
  src/sage/groups/finitely_presented_named.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: s: positive review, c: group theory

#36020 Fixes #35804 by computing the DDT of non-square sboxes properly.
  src/sage/crypto/sbox.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: cryptography

#36326 more fixes for E228 and E225 in combinat and some other folders
  src/sage/combinat/affine_permutation.py
  src/sage/combinat/integer_vector.py
  src/sage/combinat/integer_vectors_mod_permgroup.py
  src/sage/combinat/k_tableau.py
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/partition.py
  src/sage/combinat/partition_kleshchev.py
  src/sage/combinat/partition_tuple.py
  src/sage/combinat/permutation.py
  src/sage/combinat/tableau.py
  src/sage/combinat/tableau_tuple.py
  src/sage/combinat/vector_partition.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/misc/inline_fortran.py
  src/sage/misc/sageinspect.py
  src/sage/misc/superseded.py
  src/sage/misc/temporary_file.py
  src/sage/monoids/free_abelian_monoid.py
  src/sage/monoids/free_monoid_element.py
  src/sage/monoids/hecke_monoid.py
  src/sage/monoids/string_monoid.py
  src/sage/quadratic_forms/ternary_qf.py
  src/sage/sandpiles/examples.py
  src/sage/sandpiles/sandpile.py
  src/sage/structure/formal_sum.py
  src/sage/structure/gens_py.py
  src/sage/structure/sequence.py
Labels: s: positive review, t: refactoring

#36330 src/sage/repl/load.py: replace tmp_dir()
  src/sage/repl/load.py
Labels: s: positive review, t: refactoring

#36335 using more itertools.product
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/set_partition_ordered.py
  src/sage/graphs/path_enumeration.pyx
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/tensor_operations.py
Labels: s: positive review, t: refactoring

#36336 add some class roles for linking Errors in doc
  src/sage/databases/conway.py
  src/sage/graphs/generic_graph.py
  src/sage/interfaces/singular.py
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_space.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/modules/vector_space_homspace.py
  src/sage/numerical/gauss_legendre.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/product_projective/space.py
  src/sage/schemes/projective/projective_space.py
  src/sage/structure/element.pyx
  src/sage/structure/parent.pyx
  src/sage/structure/parent_gens.pyx
  src/sage/structure/parent_old.pyx
Labels: s: positive review, c: documentation

#36338 CI: Merge open blocker PRs in all CI workflows + other improvements
  .ci/merge-fixes.sh
  .github/workflows/build.yml
  .github/workflows/ci-conda.yml
  .github/workflows/ci-macos.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/macos.yml
  build/pkgs/sagemath_coxeter3/distros/conda.txt
  build/pkgs/sagemath_mcqd/distros/conda.txt
  build/pkgs/sagemath_meataxe/distros/conda.txt
  build/pkgs/sagemath_tdlib/distros/conda.txt
  tox.ini
Labels: s: needs review, p: blocker / 1, c: scripts

#36339 fix expect interface for newer ptyprocess
  .github/workflows/ci-conda.yml
  build/pkgs/ptyprocess/checksums.ini
  build/pkgs/ptyprocess/install-requires.txt
  build/pkgs/ptyprocess/package-version.txt
  src/sage/interfaces/expect.py
Labels: t: bug, c: packages: standard, s: positive review, s: run conda ci

#36110 Update Cython to 3.0.2
  build/pkgs/cypari/patches/cython3-legacy.patch
  build/pkgs/cysignals/patches/cython3-fix-warning.patch
  build/pkgs/cysignals/patches/cython3-legacy.patch
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/dependencies
  build/pkgs/cython/install-requires.txt
  build/pkgs/cython/package-version.txt
  build/pkgs/cython/patches/0001-cython.trashcan-directive-to-enable-the-Python-trash.patch
  build/pkgs/cython/patches/0001-rebased-PR2946.patch
  build/pkgs/fpylll/patches/cython3-legacy.patch
  build/pkgs/numpy/patches/cython3-legacy.patch
  build/pkgs/pplpy/patches/cython3-legacy.patch
  build/pkgs/pplpy/patches/relative-import.patch
  build/pkgs/pythran/checksums.ini
  build/pkgs/pythran/dependencies
  build/pkgs/pythran/package-version.txt
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/arith/srange.pyx
  src/sage/combinat/sloane_functions.py
  src/sage/ext/stdsage.pxd
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/misc/cachefunc.pyx
  src/sage/misc/cython.py
  src/sage/misc/lazy_import.pyx
  src/sage/misc/lazy_list.pyx
  src/sage/misc/sageinspect.py
  src/sage/modules/free_module_element.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/structure/coerce_dict.pyx
  src/sage/tests/cmdline.py
  src/sage_setup/cython_options.py
Labels: c: packages: standard, s: positive review, p: critical / 2, s: run conda ci

#36166 Additions to the bigraded Betti number methods
  src/sage/topology/simplicial_complex.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebraic topology

#36234 Use patchelf from the system
  build/pkgs/patchelf/distros/conda.txt
  build/pkgs/patchelf/distros/debian.txt
  build/pkgs/patchelf/distros/fedora.txt
  build/pkgs/patchelf/distros/freebsd.txt
  build/pkgs/patchelf/distros/gentoo.txt
  build/pkgs/patchelf/distros/homebrew.txt
  build/pkgs/patchelf/distros/macports.txt
  build/pkgs/patchelf/distros/nix.txt
  build/pkgs/patchelf/distros/opensuse.txt
  build/pkgs/patchelf/distros/repology.txt
  build/pkgs/patchelf/distros/void.txt
  build/pkgs/patchelf/spkg-configure.m4
Labels: c: packages: standard, s: positive review, c: build: configure

#36267 Change `ipympl`/`pkgconfig`/`widgetsnbextension` to wheel packages, drop build deps
  build/pkgs/ipympl/checksums.ini
  build/pkgs/ipympl/dependencies
  build/pkgs/ipympl/package-version.txt
  build/pkgs/ipympl/requirements.txt
  build/pkgs/jupyter_packaging/SPKG.rst
  build/pkgs/jupyter_packaging/checksums.ini
  build/pkgs/jupyter_packaging/dependencies
  build/pkgs/jupyter_packaging/distros/conda.txt
  build/pkgs/jupyter_packaging/install-requires.txt
  build/pkgs/jupyter_packaging/package-version.txt
  build/pkgs/jupyter_packaging/spkg-install.in
  build/pkgs/jupyter_packaging/type
  build/pkgs/pkgconfig/checksums.ini
  build/pkgs/pkgconfig/dependencies
  build/pkgs/pkgconfig/install-requires.txt
  build/pkgs/pkgconfig/spkg-install.in
  build/pkgs/poetry_core/SPKG.rst
  build/pkgs/poetry_core/checksums.ini
  build/pkgs/poetry_core/dependencies
  build/pkgs/poetry_core/distros/conda.txt
  build/pkgs/poetry_core/install-requires.txt
  build/pkgs/poetry_core/package-version.txt
  build/pkgs/poetry_core/patches/5547.diff_bin
  build/pkgs/poetry_core/spkg-install.in
  build/pkgs/poetry_core/type
  build/pkgs/tomlkit/SPKG.rst
  build/pkgs/tomlkit/checksums.ini
  build/pkgs/tomlkit/dependencies
  build/pkgs/tomlkit/distros/conda.txt
  build/pkgs/tomlkit/install-requires.txt
  build/pkgs/tomlkit/package-version.txt
  build/pkgs/tomlkit/spkg-install.in
  build/pkgs/tomlkit/type
  build/pkgs/widgetsnbextension/SPKG.rst
  build/pkgs/widgetsnbextension/checksums.ini
  build/pkgs/widgetsnbextension/dependencies
  build/pkgs/widgetsnbextension/install-requires.txt
  build/pkgs/widgetsnbextension/package-version.txt
  build/pkgs/widgetsnbextension/spkg-install.in
  configure.ac
Labels: c: packages: standard, s: positive review

#36270 full pep8 for modular/hecke
  src/sage/modular/hecke/algebra.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/degenmap.py
  src/sage/modular/hecke/element.py
  src/sage/modular/hecke/hecke_operator.py
  src/sage/modular/hecke/homspace.py
  src/sage/modular/hecke/morphism.py
  src/sage/modular/hecke/submodule.py
Labels: s: positive review, t: refactoring

#36275 `sage.graphs.generic_graph`: some care with return ... else statements
  src/sage/graphs/generic_graph.py
Labels: t: enhancement, s: positive review, c: graph theory

#36284 improve checks
  src/sage/rings/lazy_series.py
Labels: t: enhancement, s: positive review, c: algebra

#36299 Generic implementation of fitting ideal
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
Labels: s: positive review, c: algebra

#36316 build/pkgs/lrcalc_python: add standard python spkg-configure.m4
  build/pkgs/lrcalc_python/spkg-configure.m4
Labels: s: positive review, c: build: configure

#36319 build/pkgs/setuptools_scm_git_archive: Remove (obsolete)
  build/pkgs/matplotlib/dependencies
  build/pkgs/setuptools_scm_git_archive/SPKG.rst
  build/pkgs/setuptools_scm_git_archive/checksums.ini
  build/pkgs/setuptools_scm_git_archive/dependencies
  build/pkgs/setuptools_scm_git_archive/install-requires.txt
  build/pkgs/setuptools_scm_git_archive/package-version.txt
  build/pkgs/setuptools_scm_git_archive/spkg-install.in
  build/pkgs/setuptools_scm_git_archive/type
Labels: c: packages: standard, s: positive review

#36323 src/sage/combinat/words/words.py: replace tmp_dir()
  src/sage/combinat/words/words.py
Labels: s: positive review, t: refactoring

#36327 fix the linter once more
  src/sage/coding/all.py
  src/sage/coding/source_coding/huffman.py
  src/sage/crypto/sbox.pyx
Labels: s: positive review, p: blocker / 1

#35537 Fix Sphinx markup in some file
  src/sage/categories/crystals.py
Labels: s: positive review, c: documentation, c: combinatorics

#35866 CI build.yml, doc-build.yml: Use output groups
  .github/workflows/build.yml
  .github/workflows/doc-build.yml
  build/bin/sage-logger
Labels: t: enhancement, s: positive review, c: scripts
