Repository sagemath/sage, pull requests merged in 2023-06, with the labels that each got.

#35562 Clear up left right confusion in `ore_polynomial_element.pyx`
  src/sage/rings/polynomial/ore_polynomial_element.pyx
Labels: c: basic arithmetic, p: minor / 4, s: positive review, c: documentation

#35644 make EllipticCurve.lift_x() deterministic
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/height.py
  src/sage/schemes/elliptic_curves/hom_composite.py
  src/sage/schemes/elliptic_curves/period_lattice.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#35650 Fix bug caused by cached representation in cohomology classes
  src/sage/algebras/commutative_dga.py
Labels: t: bug, s: positive review, c: algebra, c: algebraic topology

#35651 Installation guide: Document workaround for Jupyter server port clash on WSL
  src/doc/en/installation/launching.rst
Labels: c: user interface, s: positive review, c: documentation

#35657 cleanup and details in finite_word.py
  src/sage/combinat/words/finite_word.py
Labels: s: positive review, c: combinatorics, t: refactoring

#35658 Fix build with sphinx 7
  src/sage_docbuild/conf.py
  src/sage_docbuild/ext/sage_autodoc.py
Labels: p: major / 3, s: positive review, c: documentation

#35660 CI Linux: Update platforms
  .github/workflows/docker.yml
  tox.ini
Labels: s: positive review, c: porting

#35662 Sympy 1.12 upgrade
  build/pkgs/sympy/checksums.ini
  build/pkgs/sympy/package-version.txt
Labels: c: packages: standard, s: positive review

#35665 Changing the knot theory PD-code convention
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
Labels: p: major / 3, s: positive review, c: algebraic topology

#35672 cython-lint : removing unused imports in polynomials
  src/sage/rings/polynomial/cyclotomic.pyx
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polydict.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_real_mpfr_dense.pyx
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
  src/sage/rings/polynomial/real_roots.pyx
  src/sage/rings/polynomial/skew_polynomial_element.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
  src/sage/rings/polynomial/symmetric_reduction.pyx
Labels: s: positive review, t: refactoring

#35673 cylint: remove unused imports in pyx files in folders a*-geo*
  src/sage/algebras/letterplace/free_algebra_element_letterplace.pyx
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/algebras/quatalg/quaternion_algebra_cython.pyx
  src/sage/algebras/quatalg/quaternion_algebra_element.pyx
  src/sage/calculus/ode.pyx
  src/sage/calculus/riemann.pyx
  src/sage/coding/binary_code.pyx
  src/sage/coding/codecan/codecan.pyx
  src/sage/crypto/sbox.pyx
  src/sage/data_structures/bounded_integer_sequences.pyx
  src/sage/finance/fractal.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/conversions.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/list_of_faces.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pyx
Labels: s: positive review, t: refactoring

#35674 cylint: remove unused imports in graphs, groups, interacts
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/graph_decompositions/bandwidth.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/isoperimetric_inequalities.pyx
  src/sage/graphs/matchpoly.pyx
  src/sage/graphs/path_enumeration.pyx
  src/sage/graphs/spanning_tree.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/graphs/traversals.pyx
  src/sage/groups/group.pyx
  src/sage/groups/libgap_wrapper.pyx
  src/sage/groups/matrix_gps/group_element.pyx
  src/sage/groups/matrix_gps/group_element_gap.pyx
  src/sage/groups/old.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_python.pyx
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/interacts/library_cython.pyx
Labels: s: positive review, t: refactoring

#35675 cylint: remove unused imports in matrix folder
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_dense.pyx
  src/sage/matrix/matrix_gap.pyx
  src/sage/matrix/matrix_generic_sparse.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matrix/matrix_numpy_dense.pyx
  src/sage/matrix/matrix_polynomial_dense.pyx
  src/sage/matrix/matrix_rational_dense.pyx
  src/sage/matrix/matrix_sparse.pyx
  src/sage/matrix/matrix_symbolic_dense.pyx
  src/sage/matrix/misc.pyx
Labels: s: positive review, t: refactoring

#35677 Some pep8 in elliptic curves
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ec_database.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_modular_symbols.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/ell_wp.py
  src/sage/schemes/elliptic_curves/formal_group.py
  src/sage/schemes/elliptic_curves/gal_reps.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/gp_simon.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/height.py
  src/sage/schemes/elliptic_curves/hom_composite.py
  src/sage/schemes/elliptic_curves/hom_velusqrt.py
  src/sage/schemes/elliptic_curves/isogeny_class.py
  src/sage/schemes/elliptic_curves/isogeny_small_degree.py
  src/sage/schemes/elliptic_curves/kodaira_symbol.py
  src/sage/schemes/elliptic_curves/kraus.py
  src/sage/schemes/elliptic_curves/lseries_ell.py
  src/sage/schemes/elliptic_curves/mod5family.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/schemes/elliptic_curves/padics.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/schemes/elliptic_curves/saturation.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
Labels: s: positive review, c: elliptic curves

#35678 Fix building the Singular docstring dict when Singular info is built with recent texinfo
  src/sage/interfaces/singular.py
Labels: c: packages: standard, s: positive review

#35680 register magic modes for lazy imported interfaces
  src/sage/repl/interface_magic.py
Labels: t: bug, c: user interface, p: minor / 4, s: positive review, c: interfaces

#35683 deprecation warning for #34880
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/modular/quatalg/brandt.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#35685 unify input of matrices and vectors
  src/sage/combinat/k_regular_sequence.py
  src/sage/combinat/recognizable_series.py
Labels: p: major / 3, t: bug, s: positive review, c: combinatorics

#35686 fixing a lot of pycostyle warnings in calculus folder
  src/sage/calculus/all.py
  src/sage/calculus/calculus.py
  src/sage/calculus/desolvers.py
  src/sage/calculus/functional.py
  src/sage/calculus/functions.py
  src/sage/calculus/transforms/dft.py
  src/sage/calculus/wester.py
Labels: s: positive review, t: refactoring

#35687 some fixes for pycodestyle E275
  src/sage/algebras/lie_conformal_algebras/weyl_lie_conformal_algebra.py
  src/sage/crypto/block_cipher/des.py
  src/sage/crypto/mq/sr.py
  src/sage/games/quantumino.py
  src/sage/geometry/polyhedron/parent.py
  src/sage/interfaces/qepcad.py
  src/sage/logic/boolformula.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/hypergeometric_motive.py
  src/sage/modular/modform/l_series_gross_zagier.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/modsym/tests.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/modsym.py
  src/sage/modular/quatalg/brandt.py
  src/sage/modular/ssmod/ssmod.py
  src/sage/modules/free_module_homspace.py
  src/sage/modules/free_module_integer.py
  src/sage/modules/with_basis/morphism.py
  src/sage/monoids/automatic_semigroup.py
  src/sage/plot/plot3d/shapes2.py
  src/sage/quadratic_forms/quadratic_form__mass__Conway_Sloane_masses.py
  src/sage/sat/boolean_polynomials.py
  src/sage/sets/disjoint_union_enumerated_sets.py
  src/sage/sets/family.py
  src/sage/stats/distributions/discrete_gaussian_lattice.py
  src/sage/structure/dynamic_class.py
  src/sage/tests/benchmark.py
  src/sage/tests/finite_poset.py
  src/sage/topology/simplicial_set.py
Labels: s: positive review, t: refactoring

#35688 cython-lint : removed many unused imports in rings/
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/factorint.pyx
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/hom_finite_field_givaro.pyx
  src/sage/rings/finite_rings/hom_prime_finite_field.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/fraction_field_FpT.pyx
  src/sage/rings/fraction_field_element.pyx
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/element_polymod.pyx
  src/sage/rings/function_field/element_rational.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/number_field/totallyreal.pyx
  src/sage/rings/number_field/totallyreal_data.pyx
  src/sage/rings/power_series_mpoly.pyx
  src/sage/rings/power_series_poly.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/puiseux_series_ring_element.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/real_arb.pyx
  src/sage/rings/real_double.pyx
  src/sage/rings/real_interval_absolute.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_element.pyx
  src/sage/rings/semirings/tropical_semiring.pyx
  src/sage/rings/tate_algebra_element.pyx
  src/sage/rings/tate_algebra_ideal.pyx
Labels: s: positive review, t: refactoring

#35689 cylint: remove unused imports in folders [s-z]*
  src/sage/matrix/matrix_space.py
  src/sage/stats/time_series.pyx
  src/sage/structure/category_object.pyx
  src/sage/structure/coerce.pyx
  src/sage/structure/element.pyx
  src/sage/structure/formal_sum.py
  src/sage/structure/parent.pyx
  src/sage/symbolic/ring.pyx
Labels: s: positive review, t: refactoring

#35694 Correct spelling in permgroup_named: Diyclic => Dicyclic
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: p: minor / 4, s: positive review, c: group theory

#35695 Fix incorrect linear branch number for non-invertible SBox
  src/sage/crypto/sbox.pyx
Labels: s: positive review, c: cryptography

#35697 cylint: remove imports in misc/
  src/sage/misc/binary_tree.pyx
  src/sage/misc/fpickle.pyx
  src/sage/misc/misc_c.pyx
  src/sage/misc/parser.pyx
  src/sage/misc/randstate.pyx
  src/sage/misc/session.pyx
  src/sage/misc/weak_dict.pyx
Labels: s: positive review, t: refactoring

#35700 Fix corner case of ordered set partitions iteration
  src/sage/combinat/set_partition_ordered.py
Labels: s: positive review, c: combinatorics

#35701 GAP: fix definition of 'Int'
  src/sage/libs/gap/element.pxd
  src/sage/libs/gap/gap_includes.pxd
Labels: c: packages: standard, s: positive review

#35172 New workflow for synchronization of labels
  .github/sync_labels.py
  .github/workflows/sync_labels.yml
Labels: s: positive review, c: build, c: scripts

#35483 adding support for subschemes in _is_preperiodic
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/schemes/projective/projective_point.py
Labels: p: minor / 4, s: positive review, c: dynamics

#35544 Add "informational: true" to .codecov.yml
  .codecov.yml
Labels: s: positive review

#35554 Laurent polynomial/series modularization fixes
  src/sage/combinat/root_system/root_lattice_realization_algebras.py
  src/sage/data_structures/stream.py
  src/sage/rings/big_oh.py
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/polynomial/laurent_polynomial.pxd
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pxd
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review, c: algebra, t: refactoring

#35590 Implementing the Casimir elements of a finite dimensional Lie algebra
  src/sage/algebras/lie_algebras/poincare_birkhoff_witt.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: t: enhancement, s: positive review, c: algebra

#34965 sparse strategies for composite elliptic-curve isogenies
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/hom_composite.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#35245 GenericGraph.adjacency_matrix: using sort=True when getting vertices
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#35709 some cython-linting in quadratic forms
  src/sage/quadratic_forms/count_local_2.pyx
  src/sage/quadratic_forms/ternary.pyx
Labels: s: positive review, t: refactoring

#35711 fix all pep8 E251 in combinat
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/crystals/affine_factorization.py
  src/sage/combinat/crystals/alcove_path.py
  src/sage/combinat/crystals/fast_crystals.py
  src/sage/combinat/crystals/fully_commutative_stable_grothendieck.py
  src/sage/combinat/crystals/highest_weight_crystals.py
  src/sage/combinat/crystals/kirillov_reshetikhin.py
  src/sage/combinat/crystals/littelmann_path.py
  src/sage/combinat/crystals/tensor_product.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/group_divisible_designs.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/designs/orthogonal_arrays.py
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/combinat/designs/steiner_quadruple_systems.py
  src/sage/combinat/fully_packed_loop.py
  src/sage/combinat/growth.py
  src/sage/combinat/integer_vector.py
  src/sage/combinat/integer_vector_weighted.py
  src/sage/combinat/integer_vectors_mod_permgroup.py
  src/sage/combinat/k_tableau.py
  src/sage/combinat/ncsf_qsym/combinatorics.py
  src/sage/combinat/ncsf_qsym/generic_basis_code.py
  src/sage/combinat/ncsf_qsym/ncsf.py
  src/sage/combinat/ncsf_qsym/qsym.py
  src/sage/combinat/ncsym/ncsym.py
  src/sage/combinat/partition.py
  src/sage/combinat/permutation.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/combinat/root_system/extended_affine_weyl_group.py
  src/sage/combinat/root_system/fundamental_group.py
  src/sage/combinat/root_system/hecke_algebra_representation.py
  src/sage/combinat/root_system/pieri_factors.py
  src/sage/combinat/root_system/plot.py
  src/sage/combinat/root_system/reflection_group_real.py
  src/sage/combinat/root_system/root_lattice_realization_algebras.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/root_system/root_space.py
  src/sage/combinat/root_system/root_system.py
  src/sage/combinat/root_system/type_Q.py
  src/sage/combinat/root_system/type_affine.py
  src/sage/combinat/root_system/type_dual.py
  src/sage/combinat/root_system/type_relabel.py
  src/sage/combinat/root_system/weight_lattice_realizations.py
  src/sage/combinat/root_system/weight_space.py
  src/sage/combinat/sidon_sets.py
  src/sage/combinat/skew_partition.py
  src/sage/combinat/subsets_pairwise.py
  src/sage/combinat/vector_partition.py
  src/sage/combinat/words/word_generators.py
Labels: s: positive review, t: refactoring

#35712 fix pep8 E251 in rings/
  src/sage/rings/complex_interval_field.py
  src/sage/rings/finite_rings/conway_polynomials.py
  src/sage/rings/function_field/ideal.py
  src/sage/rings/function_field/place.py
  src/sage/rings/homset.py
  src/sage/rings/ideal.py
  src/sage/rings/lazy_series.py
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/number_field_ideal_rel.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/padic_base_leaves.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/padics/relative_extension_leaves.py
  src/sage/rings/padics/unramified_extension_generic.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/power_series_ring.py
  src/sage/rings/qqbar.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/rational_field.py
Labels: s: positive review, t: refactoring

#35718 `sage.graphs`: More modularization
  src/sage/graphs/all.py
  src/sage/graphs/base/boost_graph.pyx
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/bliss.pyx
  src/sage/graphs/centrality.pyx
  src/sage/graphs/comparability.pyx
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/digraph.py
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/dot2tex_utils.py
  src/sage/graphs/edge_connectivity.pyx
  src/sage/graphs/generators/basic.py
  src/sage/graphs/generators/classical_geometries.py
  src/sage/graphs/generators/degree_sequence.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/generators/families.py
  src/sage/graphs/generators/random.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/graph.py
  src/sage/graphs/graph_coloring.pyx
  src/sage/graphs/graph_decompositions/bandwidth.pyx
  src/sage/graphs/graph_decompositions/graph_products.pyx
  src/sage/graphs/graph_decompositions/modular_decomposition.py
  src/sage/graphs/graph_decompositions/vertex_separation.pyx
  src/sage/graphs/graph_input.py
  src/sage/graphs/graph_list.py
  src/sage/graphs/graph_plot_js.py
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/hypergraph_generators.py
  src/sage/graphs/isoperimetric_inequalities.pyx
  src/sage/graphs/line_graph.pyx
  src/sage/graphs/partial_cube.py
  src/sage/graphs/spanning_tree.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/views.pyx
Labels: s: positive review, c: graph theory, t: refactoring

#35721 cython-lint for imports in rings (mostly in padics)
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/padics/local_generic_element.pyx
  src/sage/rings/padics/morphism.pyx
  src/sage/rings/padics/padic_ZZ_pX_CA_element.pyx
  src/sage/rings/padics/padic_ZZ_pX_CR_element.pyx
  src/sage/rings/padics/padic_ZZ_pX_FM_element.pyx
  src/sage/rings/padics/padic_ext_element.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/padics/pow_computer_relative.pyx
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
Labels: s: positive review, t: refactoring

#35722 cython-lint for imports in libs/
  src/sage/libs/eclib/homspace.pyx
  src/sage/libs/eclib/mwrank.pyx
  src/sage/libs/gap/element.pyx
  src/sage/libs/giac/giac.pyx
  src/sage/libs/lcalc/lcalc_Lfunction.pyx
  src/sage/libs/linbox/linbox_flint_interface.pyx
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/libs/ntl/ntl_GF2.pyx
  src/sage/libs/ntl/ntl_GF2E.pyx
  src/sage/libs/ntl/ntl_GF2X.pyx
  src/sage/libs/ntl/ntl_ZZ.pyx
  src/sage/libs/ntl/ntl_ZZX.pyx
  src/sage/libs/ntl/ntl_ZZ_p.pyx
  src/sage/libs/ntl/ntl_ZZ_pE.pyx
  src/sage/libs/ntl/ntl_ZZ_pEContext.pyx
  src/sage/libs/ntl/ntl_ZZ_pEX.pyx
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/libs/ntl/ntl_lzz_p.pyx
  src/sage/libs/ntl/ntl_lzz_pX.pyx
  src/sage/libs/pari/convert_flint.pyx
  src/sage/libs/pari/convert_gmp.pyx
  src/sage/libs/pari/convert_sage.pyx
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/option.pyx
  src/sage/libs/singular/polynomial.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/libs/singular/singular.pyx
Labels: s: positive review, t: refactoring

#35723 some pep8 cleanup in rigged-configurations
  src/sage/combinat/rigged_configurations/bij_abstract_class.py
  src/sage/combinat/rigged_configurations/bij_infinity.py
  src/sage/combinat/rigged_configurations/bij_type_A.py
  src/sage/combinat/rigged_configurations/bij_type_A2_dual.py
  src/sage/combinat/rigged_configurations/bij_type_A2_even.py
  src/sage/combinat/rigged_configurations/bij_type_A2_odd.py
  src/sage/combinat/rigged_configurations/bij_type_B.py
  src/sage/combinat/rigged_configurations/bij_type_C.py
  src/sage/combinat/rigged_configurations/bij_type_D.py
  src/sage/combinat/rigged_configurations/bij_type_D_tri.py
  src/sage/combinat/rigged_configurations/bij_type_D_twisted.py
  src/sage/combinat/rigged_configurations/bij_type_E67.py
  src/sage/combinat/rigged_configurations/kleber_tree.py
  src/sage/combinat/rigged_configurations/rc_crystal.py
  src/sage/combinat/rigged_configurations/rigged_configuration_element.py
  src/sage/combinat/rigged_configurations/tensor_product_kr_tableaux.py
  src/sage/combinat/rigged_configurations/tensor_product_kr_tableaux_element.py
Labels: s: positive review, t: refactoring

#35731 build/pkgs/pyflakes: Remove
  build/pkgs/pyflakes/SPKG.rst
  build/pkgs/pyflakes/distros/conda.txt
  build/pkgs/pyflakes/distros/macports.txt
  build/pkgs/pyflakes/distros/opensuse.txt
  build/pkgs/pyflakes/distros/repology.txt
  build/pkgs/pyflakes/distros/void.txt
  build/pkgs/pyflakes/requirements.txt
  build/pkgs/pyflakes/type
Labels: s: positive review, c: packages: optional

#35733 more uses of yield from
  src/sage/combinat/interval_posets.py
  src/sage/combinat/necklace.py
  src/sage/combinat/non_decreasing_parking_function.py
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/species/functorial_composition_species.py
  src/sage/combinat/subset.py
  src/sage/combinat/tiling.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/yang_baxter_graph.py
  src/sage/databases/oeis.py
  src/sage/games/sudoku.py
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/pq_trees.py
  src/sage/groups/abelian_gps/dual_abelian_group.py
  src/sage/groups/libgap_mixin.py
  src/sage/modular/multiple_zeta.py
  src/sage/parallel/map_reduce.py
  src/sage/parallel/multiprocessing_sage.py
  src/sage/rings/asymptotic/growth_group_cartesian.py
  src/sage/rings/polynomial/groebner_fan.py
  src/sage/rings/polynomial/pbori/blocks.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/rational_field.py
  src/sage/rings/valuation/value_group.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/toric/points.py
  src/sage/sets/recursively_enumerated_set.pyx
  src/sage/symbolic/expression.pyx
  src/sage/tensor/modules/comp.py
  src/sage/tests/arxiv_0812_2725.py
  src/sage/typeset/character_art.py
Labels: s: positive review, t: refactoring

#35737 build/pkgs/maxima: Fix parallel build
  build/pkgs/maxima/spkg-install.in
Labels: c: packages: standard, s: positive review, c: build, p: blocker / 1

#35494 avoid computation of Conway polynomials when comparing elliptic-curve morphisms
  src/sage/schemes/elliptic_curves/hom.py
Labels: s: positive review, c: elliptic curves, t: performance

#35614 allow non-minimal equation for padic heights
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/ell_torsion.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_velusqrt.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/schemes/elliptic_curves/padics.py
Labels: s: positive review, c: elliptic curves

#35702 GAP: switch some code to use official libgap APIs
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
  src/sage/libs/gap/libgap.pyx
  src/sage/libs/gap/util.pyx
Labels: c: packages: standard, s: positive review

#35710 fix pep8 E251 in categories, coding, crypto, logic
  src/sage/categories/simplicial_sets.py
  src/sage/coding/code_constructions.py
  src/sage/coding/decoder.py
  src/sage/coding/encoder.py
  src/sage/coding/extended_code.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/coding/punctured_code.py
  src/sage/coding/subfield_subcode.py
  src/sage/crypto/cipher.py
  src/sage/crypto/classical_cipher.py
  src/sage/crypto/mq/sr.py
  src/sage/crypto/stream.py
  src/sage/crypto/stream_cipher.py
  src/sage/logic/logicparser.py
Labels: s: positive review, t: refactoring

#35713 update symengine(_py) to versions 0.10.0 and 0.10.1
  build/pkgs/symengine/checksums.ini
  build/pkgs/symengine/package-version.txt
  build/pkgs/symengine_py/checksums.ini
  build/pkgs/symengine_py/package-version.txt
  build/pkgs/symengine_py/patches/0001-Fix-getting-string-representation-of-sage-objects.patch
Labels: s: positive review, c: packages: optional, s: run conda ci

#35720 fix the linter and add more checks
  src/sage/algebras/commutative_dga.py
  src/sage/algebras/lie_algebras/affine_lie_algebra.py
  src/sage/knots/link.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/tox.ini
Labels: s: positive review, p: critical / 2, t: refactoring

#35739 .github/workflows/docker.yml: Remove defunct steps that refer to Trac
  .github/workflows/docker.yml
Labels: s: positive review

#35752 Clarification on the MAX_MODULUS of float matrices modulo `n`
  src/sage/matrix/matrix_modn_dense_double.pyx
  src/sage/matrix/matrix_modn_dense_float.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: linear algebra

#35754 remove deprecated in #32894 python module interfaces/primecount
  src/sage/interfaces/primecount.py
Labels: s: positive review, c: interfaces

#35757 Implementing the type B Ish arrangement.
  src/doc/en/reference/references/index.rst
  src/sage/geometry/hyperplane_arrangement/library.py
Labels: p: major / 3, t: enhancement, s: positive review, c: geometry

#35758 `sage.matrix.misc`: Split by library dependency
  src/doc/en/reference/matrices/index.rst
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/misc.pyx
  src/sage/matrix/misc_flint.pyx
  src/sage/matrix/misc_mpfr.pyx
Labels: s: positive review, c: linear algebra, t: refactoring

#35760 gap: adapt get_global to use official libgap API
  src/sage/libs/gap/libgap.pyx
Labels: c: packages: standard, s: positive review

#35764 fix all remaining E251 warnings
  src/sage/dynamics/arithmetic_dynamics/endPN_automorphism_group.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/dynamics/complex_dynamics/mandel_julia.py
  src/sage/modules/free_module.py
  src/sage/modules/submodule.py
  src/sage/modules/with_basis/morphism.py
Labels: s: positive review, t: refactoring

#35765 more fixes for superfluous cython imports
  src/sage/algebras/octonion_algebra.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/libs/mpmath/ext_libmp.pyx
  src/sage/matrix/matrix_symbolic_sparse.pyx
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/numerical/backends/ppl_backend.pyx
  src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
Labels: s: positive review, c: cython, t: refactoring

#35766 fixing most E222 warnings in py files
  src/sage/algebras/cluster_algebra.py
  src/sage/algebras/lie_algebras/heisenberg.py
  src/sage/algebras/splitting_algebra.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
  src/sage/coding/punctured_code.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/designs/steiner_quadruple_systems.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/root_system/type_D.py
  src/sage/combinat/sf/llt.py
  src/sage/combinat/t_sequences.py
  src/sage/combinat/words/morphic.py
  src/sage/crypto/cryptosystem.py
  src/sage/crypto/lwe.py
  src/sage/crypto/mq/rijndael_gf.py
  src/sage/crypto/mq/sr.py
  src/sage/databases/cremona.py
  src/sage/databases/knotinfo_db.py
  src/sage/functions/transcendental.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/geometry/ribbon_graph.py
  src/sage/graphs/graph_database.py
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/finitely_presented_named.py
  src/sage/groups/perm_gps/cubegroup.py
  src/sage/interfaces/singular.py
  src/sage/interfaces/tides.py
  src/sage/knots/knotinfo.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/manifolds/structure.py
  src/sage/matrix/benchmark.py
  src/sage/misc/rest_index_of_methods.py
  src/sage/modular/arithgroup/arithgroup_perm.py
  src/sage/modular/modform/ring.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/modules/torsion_quadratic_module.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/quadratic_form__siegel_product.py
  src/sage/quadratic_forms/quadratic_form__split_local_covering.py
  src/sage/quadratic_forms/special_values.py
  src/sage/repl/preparse.py
  src/sage/rings/function_field/differential.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/sat/converters/polybori.py
  src/sage/structure/factorization.py
  src/sage/symbolic/callable.py
  src/sage/symbolic/units.py
  src/sage/tests/benchmark.py
  src/sage/topology/delta_complex.py
  src/sage/topology/simplicial_set_constructions.py
Labels: s: positive review, t: refactoring

#35768 fix most E301 warnings
  src/sage/algebras/free_algebra.py
  src/sage/algebras/lie_conformal_algebras/finitely_freely_generated_lca.py
  src/sage/categories/category_with_axiom.py
  src/sage/categories/examples/sets_cat.py
  src/sage/categories/finitely_generated_lambda_bracket_algebras.py
  src/sage/categories/lambda_bracket_algebras.py
  src/sage/coding/golay_code.py
  src/sage/coding/goppa_code.py
  src/sage/crypto/mq/sr.py
  src/sage/databases/findstat.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/interacts/library.py
  src/sage/interfaces/magma_free.py
  src/sage/manifolds/differentiable/vectorfield_module.py
  src/sage/modular/abvar/homspace.py
  src/sage/modular/quasimodform/ring.py
  src/sage/monoids/free_abelian_monoid.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/repl/ipython_extension.py
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/padics/padic_base_generic.py
  src/sage/rings/quotient_ring.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/generic/point.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
  src/sage/sets/set_from_iterator.py
  src/sage/structure/formal_sum.py
  src/sage/symbolic/operators.py
Labels: s: positive review, t: refactoring

#35770 cylint: remove some unused variables in rings/
  src/sage/rings/bernoulli_mod_p.pyx
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/fast_arith.pyx
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/element_polymod.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/totallyreal.pyx
  src/sage/rings/number_field/totallyreal_data.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polydict.pyx
  src/sage/rings/polynomial/polynomial_compiled.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/symmetric_reduction.pyx
  src/sage/rings/real_arb.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/sum_of_squares.pyx
Labels: s: positive review, c: cython, t: refactoring

#35772 getting rid of many uses of xrange in pyx files
  src/sage/calculus/interpolators.pyx
  src/sage/calculus/riemann.pyx
  src/sage/coding/binary_code.pyx
  src/sage/coding/codecan/autgroup_can_label.pyx
  src/sage/crypto/boolean_function.pyx
  src/sage/data_structures/bitset.pyx
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/lfunctions/zero_sums.pyx
  src/sage/libs/coxeter3/coxeter.pyx
  src/sage/libs/flint/fmpz_poly.pyx
  src/sage/libs/singular/function.pyx
  src/sage/media/channels.pyx
  src/sage/misc/binary_tree.pyx
  src/sage/misc/random_testing.py
  src/sage/modular/arithgroup/farey_symbol.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/modules/vector_integer_dense.pyx
  src/sage/numerical/gauss_legendre.pyx
  src/sage/quadratic_forms/ternary.pyx
  src/sage/structure/element.pyx
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/getitem_impl.pxi
  src/sage/symbolic/series_impl.pxi
Labels: s: positive review, c: cython, t: refactoring

#35773 Document that GLPK/exact can be inexact
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/backends/glpk_exact_backend.pyx
Labels: s: positive review, c: documentation, c: linear programming

#35776 cylint: no more xrange in matroids
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/extension.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pxd
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/set_system.pyx
  src/sage/matroids/unpickling.pyx
Labels: s: positive review, c: cython, c: matroid theory, t: refactoring

#35620 doctester: Check for consistency of `# optional` annotations
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
  src/sage/doctest/sources.py
  src/sage/rings/big_oh.py
Labels: s: positive review, c: doctest framework

#35629 Implement the exceptional Jordan algebra
  src/sage/algebras/jordan_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35652 CI Build & Test: First build incrementally and test changed files only
  .github/workflows/build.yml
  .github/workflows/doc-build.yml
  .github/workflows/doc-publish.yml
  build/pkgs/ecl/dependencies
  build/pkgs/ecl/dependencies_order_only
  build/pkgs/maxima/dependencies
  build/pkgs/maxima/dependencies_order_only
  src/sage/doctest/control.py
  src/sage/doctest/test.py
Labels: s: positive review

#35719 `sage.matroids`: Modularization fixes
  src/sage/docs/instancedoc.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/ext/fast_callable.pyx
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/catalog.py
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/constructor.py
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/extension.pyx
  src/sage/matroids/graphic_matroid.py
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/matroids/minor_matroid.py
  src/sage/matroids/set_system.pyx
  src/sage/matroids/unpickling.pyx
  src/sage/matroids/utilities.py
  src/sage/misc/functional.py
  src/sage/repl/rich_output/pretty_print.py
  src/sage/structure/sage_object.pyx
Labels: s: positive review, c: matroid theory, t: refactoring

#35724 fix some pep8 warnings in modform_hecketriangle
  src/sage/modular/modform_hecketriangle/abstract_ring.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/analytic_type.py
  src/sage/modular/modform_hecketriangle/constructor.py
  src/sage/modular/modform_hecketriangle/functors.py
  src/sage/modular/modform_hecketriangle/graded_ring.py
  src/sage/modular/modform_hecketriangle/graded_ring_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/modular/modform_hecketriangle/series_constructor.py
  src/sage/modular/modform_hecketriangle/space.py
  src/sage/modular/modform_hecketriangle/subspace.py
Labels: s: positive review, c: modular forms, t: refactoring

#35728 New feature annotations `# optional - sage.schemes sage.modular sage.libs.flint` etc.
  src/sage/arith/functions.pyx
  src/sage/arith/misc.py
  src/sage/arith/multi_modular.pyx
  src/sage/categories/action.pyx
  src/sage/categories/hecke_modules.py
  src/sage/categories/homset.py
  src/sage/categories/modules_with_basis.py
  src/sage/features/sagemath.py
  src/sage/misc/cachefunc.pyx
  src/sage/misc/functional.py
  src/sage/misc/latex.py
  src/sage/misc/lazy_import.pyx
  src/sage/misc/lazy_list.pyx
  src/sage/misc/prandom.py
  src/sage/misc/randstate.pyx
  src/sage/misc/table.py
  src/sage/modules/module.pyx
  src/sage/structure/category_object.pyx
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_actions.pyx
  src/sage/structure/coerce_dict.pyx
  src/sage/structure/coerce_maps.pyx
  src/sage/structure/element.pxd
  src/sage/structure/element.pyx
  src/sage/structure/element_wrapper.pyx
  src/sage/structure/factorization.py
  src/sage/structure/factory.pyx
  src/sage/structure/formal_sum.py
  src/sage/structure/global_options.py
  src/sage/structure/indexed_generators.py
  src/sage/structure/nonexact.py
  src/sage/structure/parent.pyx
  src/sage/structure/parent_gens.pyx
  src/sage/structure/parent_old.pyx
  src/sage/structure/proof/proof.py
  src/sage/structure/sequence.py
  src/sage/structure/unique_representation.py
Labels: s: positive review, t: refactoring

#35729 sage.coding: Modularization fixes, doctest cosmetics, add `# optional`
  src/sage/coding/abstract_code.py
  src/sage/coding/ag_code.py
  src/sage/coding/ag_code_decoders.pyx
  src/sage/coding/bch_code.py
  src/sage/coding/binary_code.pyx
  src/sage/coding/bounds_catalog.py
  src/sage/coding/channel.py
  src/sage/coding/channels_catalog.py
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/codecan/autgroup_can_label.pyx
  src/sage/coding/codecan/codecan.pyx
  src/sage/coding/codes_catalog.py
  src/sage/coding/cyclic_code.py
  src/sage/coding/databases.py
  src/sage/coding/decoder.py
  src/sage/coding/decoders_catalog.py
  src/sage/coding/delsarte_bounds.py
  src/sage/coding/encoder.py
  src/sage/coding/encoders_catalog.py
  src/sage/coding/extended_code.py
  src/sage/coding/gabidulin_code.py
  src/sage/coding/goppa_code.py
  src/sage/coding/grs_code.py
  src/sage/coding/guava.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/guruswami_sudan/interpolation.py
  src/sage/coding/guruswami_sudan/utils.py
  src/sage/coding/hamming_code.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/kasami_codes.pyx
  src/sage/coding/linear_code.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/coding/linear_rank_metric.py
  src/sage/coding/parity_check_code.py
  src/sage/coding/punctured_code.py
  src/sage/coding/reed_muller_code.py
  src/sage/coding/self_dual_codes.py
  src/sage/coding/source_coding/huffman.py
  src/sage/coding/subfield_subcode.py
  src/sage/coding/two_weight_db.py
Labels: s: positive review, c: coding theory, t: refactoring

#35730 little refreshment of code in Weyl groups
  src/sage/combinat/root_system/weyl_group.py
  src/sage/groups/group.pyx
Labels: s: positive review, c: combinatorics, t: refactoring

#35734 Reference manual: Show modularized sagelib packages separately
  build/bin/sage-spkg-info
  src/doc/bootstrap
  src/doc/en/reference/misc/index.rst
  src/sage/features/bliss.py
  src/sage/features/cddlib.py
  src/sage/features/csdp.py
  src/sage/features/databases.py
  src/sage/features/ffmpeg.py
  src/sage/features/four_ti_2.py
  src/sage/features/gap.py
  src/sage/features/gfan.py
  src/sage/features/graph_generators.py
  src/sage/features/graphviz.py
  src/sage/features/igraph.py
  src/sage/features/imagemagick.py
  src/sage/features/interfaces.py
  src/sage/features/kenzo.py
  src/sage/features/latte.py
  src/sage/features/lrs.py
  src/sage/features/mcqd.py
  src/sage/features/meataxe.py
  src/sage/features/msolve.py
  src/sage/features/nauty.py
  src/sage/features/normaliz.py
  src/sage/features/palp.py
  src/sage/features/pandoc.py
  src/sage/features/pdf2svg.py
  src/sage/features/phitigra.py
  src/sage/features/pkg_systems.py
  src/sage/features/polymake.py
  src/sage/features/rubiks.py
  src/sage/features/singular.py
  src/sage/features/sphinx.py
  src/sage/features/tdlib.py
Labels: s: positive review, c: documentation

#35735 gap: use CALL_WITH_STREAM to redirect output to string
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
Labels: c: packages: standard, s: positive review

#35741 `sage.combinat`: Split some Cython modules (modularization fixes)
  src/doc/en/reference/combinat/module_list.rst
  src/sage/combinat/combinat_cython.pxd
  src/sage/combinat/combinat_cython.pyx
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/posets/hasse_cython.pyx
  src/sage/combinat/posets/hasse_cython_flint.pyx
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/linear_extension_iterator.pyx
  src/sage/combinat/posets/linear_extensions.py
  src/sage/combinat/set_partition.py
  src/sage/combinat/set_partition_iterator.pyx
Labels: s: positive review, c: combinatorics, t: refactoring

#35759 gap: fix a comment
  src/sage/libs/gap/element.pyx
Labels: c: packages: standard, s: positive review

#35564 `sage.misc.misc`, `sage.combinat`: Modularization fixes
  src/sage/algebras/quantum_clifford.py
  src/sage/arith/misc.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/finite_coxeter_groups.py
  src/sage/categories/loop_crystals.py
  src/sage/combinat/all.py
  src/sage/combinat/blob_algebra.py
  src/sage/combinat/combinat.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/diagram.py
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/integer_vector_weighted.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/permutation.py
  src/sage/combinat/root_system/cartan_matrix.py
  src/sage/combinat/root_system/coxeter_type.py
  src/sage/combinat/set_partition.py
  src/sage/combinat/subset.py
  src/sage/combinat/tableau.py
  src/sage/databases/jones.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/game_theory/cooperative_game.py
  src/sage/game_theory/normal_form_game.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/graphs/graph.py
  src/sage/misc/all.py
  src/sage/misc/misc.py
  src/sage/rings/abc.pyx
  src/sage/rings/function_field/ideal.py
  src/sage/rings/polynomial/cyclotomic.pyx
  src/sage/rings/universal_cyclotomic_field.py
  src/sage/sets/condition_set.py
Labels: s: positive review, c: combinatorics, t: refactoring
