Repository sagemath/sage, pull requests merged in 2023-05, with the labels that each got.

#35552 fix the linter once more
  src/sage/rings/real_double.pyx
  src/sage/rings/real_mpfr.pyx
Labels: s: positive review, p: critical / 2, t: refactoring

#35524 Accept system openblas 0.3.23 and newer (needed for archlinux)
  build/pkgs/openblas/spkg-configure.m4
Labels: s: positive review, p: critical / 2, c: build: configure

#35571 update openssl to 3.0.8
  build/pkgs/openssl/checksums.ini
  build/pkgs/openssl/package-version.txt
Labels: p: major / 3, c: packages: standard, s: positive review

#35637 remark that WSL needs a lot of RAM
  README.md
  src/doc/en/installation/index.rst
Labels: s: positive review, c: documentation

#35432 Some fixes for Specht modules and diagrams
  src/sage/combinat/diagram.py
  src/sage/combinat/specht_module.py
Labels: t: bug, p: minor / 4, s: positive review, c: combinatorics

#35484 Implement down-up algebras and their Verma modules
  src/doc/en/reference/algebras/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/algebras/catalog.py
  src/sage/algebras/down_up_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35502 `sage.rings.factorint`: Modularization fixes
  src/doc/en/reference/rings_standard/index.rst
  src/sage/libs/flint/fmpz_factor.pyx
  src/sage/rings/factorint.pyx
  src/sage/rings/factorint_flint.pyx
  src/sage/rings/factorint_pari.pyx
  src/sage/rings/integer.pyx
Labels: s: positive review, t: refactoring

#35505 Deprecate `is_SymbolicVariable`, `is_SymbolicEquation`
  src/sage/symbolic/expression.pyx
Labels: s: positive review, c: symbolics, t: refactoring

#35519 Make rank return an Integer object
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/polynomial/ore_polynomial_element.pxd
  src/sage/rings/polynomial/ore_polynomial_element.pyx
Labels: s: positive review, c: algebra

#35540 For groups: generic centralizer, subgroup methods; improving center
  src/sage/groups/libgap_mixin.py
  src/sage/groups/matrix_gps/heisenberg.py
Labels: p: major / 3, t: enhancement, s: positive review, c: group theory

#35548 Fvector for fans
  src/sage/geometry/fan.py
Labels: s: positive review, c: algebraic geometry, c: geometry

#35549 fixing some pycodestyle warnings E251
  src/sage/misc/test_nested_class.py
  src/sage/modular/btquotients/pautomorphicform.py
  src/sage/modular/modform_hecketriangle/abstract_ring.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/graded_ring.py
  src/sage/modular/modform_hecketriangle/graded_ring_element.py
  src/sage/modular/modform_hecketriangle/space.py
  src/sage/modular/pollack_stevens/modsym.py
  src/sage/numerical/knapsack.py
  src/sage/numerical/optimize.py
  src/sage/plot/matrix_plot.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/plot/plot3d/tri_plot.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/quadratic_form__local_normal_form.py
  src/sage/quadratic_forms/quadratic_form__split_local_covering.py
  src/sage/repl/preparse.py
  src/sage/sets/family.py
  src/sage/sets/finite_set_maps.py
  src/sage/sets/integer_range.py
  src/sage/sets/non_negative_integers.py
  src/sage/sets/set_from_iterator.py
  src/sage/sets/totally_ordered_finite_set.py
  src/sage/structure/formal_sum.py
  src/sage/structure/proof/proof.py
  src/sage/structure/sequence.py
  src/sage/tensor/modules/tensor_with_indices.py
  src/sage/tests/benchmark.py
  src/sage/topology/simplicial_complex_morphism.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_examples.py
Labels: s: positive review, t: refactoring

#35550 removing some unused imports in cython files
  src/sage/libs/gap/element.pyx
  src/sage/libs/meataxe.pyx
  src/sage/matrix/matrix_generic_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/rings/complex_arb.pyx
  src/sage/rings/convert/mpfi.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/element_polymod.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/skew_polynomial_element.pyx
  src/sage/rings/power_series_pari.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/structure/coerce_maps.pyx
  src/sage/structure/parent.pyx
  src/sage/structure/parent_gens.pyx
  src/sage/structure/parent_old.pyx
  src/sage/structure/richcmp.pyx
Labels: s: positive review, t: refactoring

#35551 Enable access to some methods in sage/graphs/graph_decompositions
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/bandwidth.pyx
  src/sage/graphs/graph_decompositions/cutwidth.pyx
Labels: s: positive review, c: graph theory

#35553 cython-lint cleaning in combinat/
  src/sage/combinat/crystals/pbw_datum.pyx
  src/sage/combinat/crystals/spins.pyx
  src/sage/combinat/crystals/tensor_product_element.pyx
  src/sage/combinat/degree_sequences.pyx
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/evenly_distributed_sets.pyx
  src/sage/combinat/designs/gen_quadrangles_with_spread.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/combinat/designs/subhypergraph_search.pyx
  src/sage/combinat/enumeration_mod_permgroup.pyx
  src/sage/combinat/expnums.pyx
  src/sage/combinat/integer_lists/base.pyx
  src/sage/combinat/permutation_cython.pyx
  src/sage/combinat/root_system/reflection_group_c.pyx
  src/sage/combinat/root_system/reflection_group_element.pyx
  src/sage/combinat/words/word_char.pyx
Labels: s: positive review, t: refactoring

#35563 Make doc preview message from github bot one liner
  .github/workflows/doc-publish.yml
Labels: s: positive review, p: trivial / 5

#35565 replace obsolescent egrep
  src/bin/sage-grep
  src/bin/sage-grepdoc
Labels: s: positive review, c: porting, t: refactoring

#35566 partial cython-lint in plot folder
  src/sage/plot/complex_plot.pyx
  src/sage/plot/plot3d/base.pyx
  src/sage/plot/plot3d/implicit_surface.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/plot/plot3d/parametric_surface.pxd
  src/sage/plot/plot3d/point_c.pxi
  src/sage/plot/plot3d/shapes.pyx
Labels: s: positive review, t: refactoring

#35570 4ti2: Update to 1.6.10, fixes `egrep` issue, adds GCC 13 support
  build/pkgs/4ti2/checksums.ini
  build/pkgs/4ti2/package-version.txt
Labels: s: positive review, p: critical / 2, c: packages: optional

#35208 Support tox 4.x for testing modularized distributions
  pkgs/sagemath-categories/tox.ini
  pkgs/sagemath-environment/tox.ini
  pkgs/sagemath-objects/tox.ini
  pkgs/sagemath-repl/tox.ini
  pkgs/sagemath-standard/tox.ini
  src/doc/en/developer/packaging_sage_library.rst
  src/sage/misc/package.py
Labels: s: positive review, c: distribution

#35260 Implement the logarithm and the exponential of a Drinfeld module
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
Labels: t: enhancement, s: positive review, c: algebra

#35354 Add a few operations from linear symplectic geometry
  src/sage/manifolds/differentiable/diff_form.py
  src/sage/manifolds/differentiable/manifold.py
  src/sage/manifolds/differentiable/symplectic_form.py
  src/sage/manifolds/differentiable/symplectic_form_test.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/manifolds/differentiable/tensorfield_paral.py
  src/sage/manifolds/differentiable/tensorfield_paral_test.py
  src/sage/manifolds/differentiable/vectorfield_module.py
  src/sage/tensor/modules/free_module_tensor.py
Labels: s: positive review, c: manifolds

#35371 `openblas`: Update to 0.3.23
  build/pkgs/openblas/checksums.ini
  build/pkgs/openblas/package-version.txt
Labels: c: packages: standard, s: positive review

#35387 The Fusion Ring of the Drinfeld Double of a Finite Group
  src/doc/en/reference/algebras/fusion_rings.rst
  src/doc/en/reference/references/index.rst
  src/sage/algebras/fusion_rings/all.py
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/algebras/fusion_rings/fusion_ring.py
Labels: t: enhancement, s: positive review, c: algebra

#35417 Remove tag fetching in docker workflow
  .github/workflows/docker.yml
Labels: s: positive review

#35430 Adding bigraded Betti numbers functionality
  src/sage/topology/simplicial_complex.py
Labels: t: enhancement, s: positive review, c: algebraic topology

#35108 src/doc/en/developer/portability_testing.rst: Update after migration
  .github/workflows/ci-linux.yml
  src/doc/en/developer/portability_testing.rst
Labels: s: positive review, c: documentation

#35145 add parallel algorithm to Graph chromatic_number
  src/sage/graphs/graph.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: graph theory

#35567 some typing and code tweaks in MZV
  src/sage/modular/multiple_zeta.py
Labels: s: positive review, c: algebraic geometry, t: performance, t: refactoring

#35574 details on complex reflection groups
  src/sage/categories/finite_complex_reflection_groups.py
Labels: s: positive review, t: refactoring

#35575 some details in commutative dga
  src/sage/algebras/commutative_dga.py
Labels: s: positive review, c: algebra

#35576 simplify some trivial iterations
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_element.py
  src/sage/categories/examples/commutative_additive_monoids.py
  src/sage/categories/group_algebras.py
  src/sage/categories/monoids.py
  src/sage/combinat/crystals/generalized_young_walls.py
  src/sage/combinat/crystals/littelmann_path.py
  src/sage/combinat/derangements.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/tableau.py
  src/sage/databases/findstat.py
  src/sage/functions/piecewise.py
  src/sage/games/sudoku.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/polyhedron/face.py
  src/sage/geometry/polyhedron/library.py
  src/sage/manifolds/differentiable/examples/euclidean.py
  src/sage/manifolds/utilities.py
  src/sage/modules/fp_graded/module.py
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/polynomial/polydict.pyx
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/sets/totally_ordered_finite_set.py
Labels: s: positive review, t: refactoring

#35577 refactor: outsource methods in combinatorial polyhedron
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
Labels: s: positive review, c: geometry, t: refactoring

#35578 refactor: improve initialization of combinatorial polyhedron
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
Labels: s: positive review, c: geometry, t: refactoring

#35581 `sage.{topology,homology}`: Modularization fixes
  src/sage/categories/simplicial_sets.py
  src/sage/features/standard.py
  src/sage/homology/algebraic_topological_model.py
  src/sage/homology/chain_complex.py
  src/sage/homology/chain_complex_homspace.py
  src/sage/homology/chain_complex_morphism.py
  src/sage/homology/chain_homotopy.py
  src/sage/homology/chains.py
  src/sage/homology/free_resolution.py
  src/sage/homology/graded_resolution.py
  src/sage/homology/hochschild_complex.py
  src/sage/homology/homology_group.py
  src/sage/homology/homology_morphism.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/topology/cell_complex.py
  src/sage/topology/cubical_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/filtered_simplicial_complex.py
  src/sage/topology/simplicial_complex.py
  src/sage/topology/simplicial_complex_examples.py
  src/sage/topology/simplicial_complex_homset.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_catalog.py
  src/sage/topology/simplicial_set_constructions.py
  src/sage/topology/simplicial_set_examples.py
  src/sage/topology/simplicial_set_morphism.py
Labels: s: positive review, c: linear algebra, c: algebraic topology, t: refactoring

#35582 Fix discrepancy in partitions between provided number and starting partition
  src/sage/categories/enumerated_sets.py
  src/sage/combinat/partition.py
Labels: t: bug, s: positive review, c: combinatorics

#35584 Support networkx 3.1
  src/sage/graphs/graph.py
Labels: c: packages: standard, s: positive review, p: critical / 2, c: graph theory

#35586 `sage.geometry`: Add some `# optional`, reformat doctests
  src/sage/geometry/cone.py
  src/sage/geometry/fan.py
  src/sage/geometry/fan_isomorphism.py
  src/sage/geometry/fan_morphism.py
  src/sage/geometry/hasse_diagram.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/hyperplane_arrangement/check_freeness.py
  src/sage/geometry/hyperplane_arrangement/hyperplane.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/geometry/hyperplane_arrangement/plot.py
  src/sage/geometry/integral_points.pxi
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/backend_cdd_rdf.py
  src/sage/geometry/polyhedron/backend_normaliz.py
  src/sage/geometry/polyhedron/base.py
  src/sage/geometry/polyhedron/base2.py
  src/sage/geometry/polyhedron/base4.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/geometry/polyhedron/base6.py
  src/sage/geometry/polyhedron/base7.py
  src/sage/geometry/polyhedron/base_QQ.py
  src/sage/geometry/polyhedron/base_RDF.py
  src/sage/geometry/polyhedron/base_number_field.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pyx
  src/sage/geometry/polyhedron/constructor.py
  src/sage/geometry/polyhedron/face.py
  src/sage/geometry/polyhedron/library.py
  src/sage/geometry/polyhedron/misc.py
  src/sage/geometry/polyhedron/parent.py
  src/sage/geometry/polyhedron/plot.py
  src/sage/geometry/polyhedron/ppl_lattice_polytope.py
  src/sage/geometry/pseudolines.py
  src/sage/geometry/relative_interior.py
  src/sage/geometry/riemannian_manifolds/parametrized_surface3d.py
  src/sage/geometry/toric_plotter.py
  src/sage/geometry/triangulation/element.py
  src/sage/geometry/triangulation/point_configuration.py
Labels: s: positive review, c: geometry, t: refactoring

#35589 `bootstrap-conda`: Skip the dummy package `_sagemath`
  bootstrap-conda
Labels: t: bug, s: positive review, p: critical / 2, c: distribution, s: run conda ci

#35591 Implement twisted affine Lie algebras
  src/sage/algebras/lie_algebras/affine_lie_algebra.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/lie_algebra.py
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
  src/sage/algebras/lie_algebras/structure_coefficients.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35596 Fix Max=Min warning in coin interacts
  src/sage/interacts/library.py
  src/sage/interacts/test_jupyter.rst
Labels: s: positive review

#35598 Remove global sage.all import in pytest
  src/bin/sage-runtests
  src/conftest.py
  src/conftest_test.py
  src/sage/numerical/backends/cvxpy_backend_test.py
  src/sage/numerical/backends/scip_backend_test.py
Labels: s: positive review, c: doctest framework

#35608 src/doc/common/python3.inv: Update
  src/doc/common/python3.inv
  src/doc/common/update-python-inv.sh
Labels: s: positive review, c: build, c: documentation

#35612 Support linbox 1.7.0 and 1.6.3 at the same time
  src/sage/libs/linbox/conversion.pxd
  src/sage/libs/linbox/linbox.pxd
  src/sage/matrix/matrix_modn_dense_template.pxi
Labels: c: packages: standard, s: positive review, p: critical / 2, s: run conda ci

#35619 upgrade Maxima to 5.46.0
  build/pkgs/ecl/dependencies
  build/pkgs/ecl/spkg-configure.m4
  build/pkgs/ecl/spkg-install.in
  build/pkgs/giac/spkg-configure.m4
  build/pkgs/info/distros/fedora.txt
  build/pkgs/info/spkg-configure.m4
  build/pkgs/info/spkg-install.in
  build/pkgs/info/type
  build/pkgs/maxima/checksums.ini
  build/pkgs/maxima/dependencies
  build/pkgs/maxima/distros/arch.txt
  build/pkgs/maxima/distros/cygwin.txt
  build/pkgs/maxima/distros/freebsd.txt
  build/pkgs/maxima/distros/gentoo.txt
  build/pkgs/maxima/package-version.txt
  build/pkgs/maxima/patches/matrixexp.patch
  build/pkgs/maxima/patches/maxima.system.patch
  build/pkgs/maxima/spkg-configure.m4
  build/pkgs/maxima/spkg-install.in
  build/pkgs/tox/spkg-configure.m4
  pkgs/sage-conf/_sage_conf/_conf.py.in
  src/bin/sage-env
  src/sage/calculus/calculus.py
  src/sage/functions/exp_integral.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/maxima.py
  src/sage/interfaces/maxima_lib.py
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_symbolic_dense.pyx
  src/sage/symbolic/integration/integral.py
  src/sage/symbolic/relation.py
Labels: c: packages: standard, s: positive review, c: symbolics, s: run conda ci

#35622 `Animation.ffmpeg`: Shell-quote filenames
  src/sage/plot/animate.py
Labels: t: bug, s: positive review, c: graphics

#35623 cython-linting of unused imports in modules and dynamics
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/modules/vector_integer_dense.pyx
  src/sage/modules/vector_mod2_dense.pyx
  src/sage/modules/vector_modn_dense.pyx
  src/sage/modules/vector_rational_dense.pyx
  src/sage/modules/with_basis/indexed_element.pyx
Labels: s: positive review, t: refactoring

#35627 Remove jupyter-packaging for conda
  build/pkgs/jupyter_packaging/distros/conda.txt
Labels: c: packages: standard, s: positive review, p: critical / 2, s: run conda ci

#35630 Implement the octonions
  src/doc/en/reference/algebras/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/algebras/all.py
  src/sage/algebras/catalog.py
  src/sage/algebras/octonion_algebra.pxd
  src/sage/algebras/octonion_algebra.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35631 simplify some all(all(...)) in combinat and geometry
  src/sage/combinat/combinat_cython.pyx
  src/sage/combinat/crystals/tensor_product.py
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/combinat/diagram.py
  src/sage/combinat/gelfand_tsetlin_patterns.py
  src/sage/combinat/path_tableaux/frieze.py
  src/sage/combinat/path_tableaux/semistandard.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/ribbon_shaped_tableau.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/geometry/fan_morphism.py
  src/sage/geometry/polyhedron/base_ZZ.py
  src/sage/geometry/polyhedron/constructor.py
Labels: s: positive review, t: refactoring

#35632 Use fixed random-seed in the "Build & Test" CI
  .github/workflows/build.yml
Labels: s: positive review, p: critical / 2

#35634 activating more pycodestyle checks
  .vscode/settings.json
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/combinat/designs/difference_family.py
  src/sage/manifolds/differentiable/diff_form.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage_docbuild/builders.py
  src/sage_setup/autogen/giacpy-mkkeywords.py
  src/sage_setup/command/sage_build_ext.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#35635 Support sympy 1.12
  src/sage/calculus/calculus.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#35641 Fix typo in documentation
  build/pkgs/gcc/spkg-configure.m4
  m4/ax_gcc_option.m4
  m4/ax_gxx_option.m4
  src/sage/libs/gap/element.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
Labels: s: positive review, c: documentation

#35643 Avoid redundant computations in finite field .conjugate() method
  src/sage/rings/finite_rings/element_base.pyx
Labels: s: positive review, t: performance, c: finite rings

#35407 pkg-config should be `_bootstrap`, not `_prereq`, on all distros
  build/pkgs/_bootstrap/distros/conda.txt
  build/pkgs/_bootstrap/distros/slackware.txt
  build/pkgs/_bootstrap/distros/void.txt
  build/pkgs/_prereq/distros/conda.txt
  build/pkgs/_prereq/distros/slackware.txt
  build/pkgs/_prereq/distros/void.txt
Labels: s: positive review, c: build
