Repository sagemath/sage, pull requests merged in 2023-11, with the labels that each got.

#36621 Build CI: Fix configuration of coverage upload action
  .github/workflows/build.yml
Labels: s: positive review, p: critical / 2, c: scripts

#36627 CI Linux: Build the default platform in one job
  .github/workflows/ci-linux.yml
Labels: s: positive review, c: scripts

#36632 .ci/merge-fixes.sh: Reduce output
  .ci/merge-fixes.sh
Labels: p: minor / 4, s: positive review, c: scripts

#36634 permutation_normal_form : case of empty matrices
  src/sage/matrix/matrix2.pyx
Labels: t: bug, s: positive review, c: linear algebra

#36635 clean the file hexad.py
  src/sage/games/hexad.py
Labels: s: positive review, c: game theory, t: refactoring

#36639 fix broken pyright in CI
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
Labels: s: positive review, p: blocker / 1

#36517 `sage.misc.lazy_attribute`: Add typestub file for pyright
  src/sage/misc/lazy_attribute.pyi
Labels: p: minor / 4, s: positive review, t: refactoring

#36543 Cleanup conditional assert
  src/sage/cpython/dict_del_by_value.pyx
Labels: s: positive review

#36544 Support networkx 3.2
  src/sage/graphs/generic_graph.py
Labels: c: packages: standard, s: positive review, p: critical / 2, c: doctest framework

#36546 refine category of RAAGs
  src/sage/groups/raag.py
Labels: p: major / 3, t: enhancement, s: positive review, c: group theory, c: categories

#36549 cleanup in number_field_element
  src/sage/rings/number_field/number_field_element.pxd
  src/sage/rings/number_field/number_field_element.pyx
Labels: s: positive review, c: number fields, t: refactoring

#36555 refresh the file cluster_algebra
  src/sage/algebras/cluster_algebra.py
Labels: s: positive review, c: algebra

#36556 some fixes for pycodestyle E221
  src/sage/crypto/lwe.py
  src/sage/crypto/mq/sr.py
  src/sage/crypto/sboxes.py
  src/sage/databases/cremona.py
  src/sage/databases/findstat.py
  src/sage/databases/knotinfo_db.py
  src/sage/interacts/library.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/octave.py
  src/sage/interfaces/singular.py
  src/sage/interfaces/tides.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/manifolds/differentiable/chart.py
  src/sage/manifolds/differentiable/scalarfield_algebra.py
  src/sage/manifolds/scalarfield_algebra.py
  src/sage/sat/solvers/dimacs.py
  src/sage/structure/factorization_integer.py
  src/sage/tensor/modules/tensor_free_submodule.py
Labels: s: positive review, t: refactoring

#36557 src/doc/en/developer: Describe static typing workflow
  src/doc/en/developer/coding_in_python.rst
Labels: s: positive review, c: documentation

#36559 care for E702 in fast_arith.pyx
  src/sage/rings/fast_arith.pyx
Labels: s: positive review, t: refactoring

#36563 `pkgs/sagemath-{objects,categories,environment,repl}`: Move metadata from `setup.cfg` to `pyproject.toml`
  m4/pyproject_toml_metadata.m4
  pkgs/sagemath-categories/pyproject.toml.m4
  pkgs/sagemath-categories/setup.cfg.m4
  pkgs/sagemath-environment/pyproject.toml.m4
  pkgs/sagemath-environment/setup.cfg.m4
  pkgs/sagemath-objects/pyproject.toml.m4
  pkgs/sagemath-objects/setup.cfg.m4
  pkgs/sagemath-repl/pyproject.toml.m4
  pkgs/sagemath-repl/setup.cfg.m4
Labels: p: minor / 4, s: positive review, c: distribution

#36565 Limit wait for slow mirrors
  build/sage_bootstrap/download/mirror_list.py
Labels: s: positive review, c: build, p: blocker / 1

#36567 `sage.numerical`: Update `# needs`
  src/sage/numerical/all.py
  src/sage/numerical/backends/cvxopt_backend.pyx
  src/sage/numerical/backends/cvxopt_sdp_backend.pyx
  src/sage/numerical/backends/cvxpy_backend.pyx
  src/sage/numerical/backends/generic_backend.pyx
  src/sage/numerical/backends/generic_sdp_backend.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/backends/glpk_graph_backend.pyx
  src/sage/numerical/backends/interactivelp_backend.pyx
  src/sage/numerical/backends/ppl_backend.pyx
  src/sage/numerical/gauss_legendre.pyx
  src/sage/numerical/interactive_simplex_method.py
  src/sage/numerical/knapsack.py
  src/sage/numerical/mip.pyx
  src/sage/numerical/optimize.py
  src/sage/numerical/sdp.pyx
Labels: s: positive review, t: refactoring

#36568 `sage.manifolds`, `sage.tensor`: Update `# needs`
  src/sage/manifolds/calculus_method.py
  src/sage/manifolds/chart.py
  src/sage/manifolds/chart_func.py
  src/sage/manifolds/differentiable/characteristic_cohomology_class.py
  src/sage/manifolds/differentiable/curve.py
  src/sage/manifolds/differentiable/examples/euclidean.py
  src/sage/manifolds/differentiable/integrated_curve.py
  src/sage/manifolds/differentiable/multivectorfield.py
  src/sage/manifolds/differentiable/pseudo_riemannian_submanifold.py
  src/sage/manifolds/differentiable/tangent_vector.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/manifolds/differentiable/vectorfield.py
  src/sage/manifolds/manifold.py
  src/sage/manifolds/point.py
  src/sage/manifolds/subset.py
  src/sage/manifolds/subsets/pullback.py
  src/sage/manifolds/utilities.py
Labels: s: positive review, c: manifolds, t: refactoring

#36569 `sage.matrix`, `sage.modules`: Update `# needs`
  src/sage/matrix/args.pyx
  src/sage/matrix/constructor.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_complex_ball_dense.pyx
  src/sage/matrix/matrix_complex_double_dense.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/matrix/matrix_double_sparse.pyx
  src/sage/matrix/matrix_gap.pyx
  src/sage/matrix/matrix_modn_dense_template.pxi
  src/sage/matrix/matrix_numpy_dense.pyx
  src/sage/matrix/matrix_polynomial_dense.pyx
  src/sage/matrix/matrix_real_double_dense.pyx
  src/sage/matrix/matrix_space.py
  src/sage/matrix/matrix_sparse.pyx
  src/sage/matrix/operation_table.py
  src/sage/matrix/special.py
  src/sage/matrix/tests.py
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/free_module_element.pyx
  src/sage/modules/free_module_integer.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/vector_double_dense.pyx
  src/sage/modules/vector_numpy_dense.pyx
  src/sage/modules/vector_real_double_dense.pyx
  src/sage/modules/vector_space_morphism.py
Labels: s: positive review, c: linear algebra, t: refactoring

#36571 Add method to check whether a (di)graph is geodetic
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#36573 Replace relative imports by absolute ones in structure
  src/sage/structure/all.py
  src/sage/structure/coerce.pxd
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_actions.pyx
  src/sage/structure/element.pxd
  src/sage/structure/factory.pyx
  src/sage/structure/parent.pyx
  src/sage/structure/parent_base.pxd
  src/sage/structure/parent_base.pyx
  src/sage/structure/parent_gens.pxd
  src/sage/structure/parent_old.pyx
  src/sage/structure/sage_object_test.py
Labels: t: bug, s: positive review, p: critical / 2

#36578 add an example of a divisor on a curve
  src/sage/schemes/curves/curve.py
Labels: s: positive review, c: documentation, c: algebraic geometry

#36590 Allow to import `sage.cpython` module multiple times
  src/sage/cpython/__init__.py
Labels: s: positive review

#36593 some cleanup in free algebras
  src/sage/algebras/free_algebra.py
Labels: s: positive review, c: algebra

#36595 Replace relative imports by absolute ones in `sage.{coding,combinat,graphs}`
  src/sage/coding/ag_code_decoders.pyx
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/evenly_distributed_sets.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/graphs/base/c_graph.pxd
  src/sage/graphs/base/dense_graph.pxd
  src/sage/graphs/base/graph_backends.pyx
  src/sage/graphs/base/sparse_graph.pxd
  src/sage/graphs/base/static_sparse_backend.pxd
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/base/static_sparse_graph.pyx
Labels: s: positive review, t: refactoring

#36596 Replace relative imports by absolute ones in `sage.{geometry,groups,numerical,plot}`
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/conversions.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/conversions.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_list_data_structure.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/list_of_faces.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/list_of_faces.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pyx
  src/sage/geometry/triangulation/base.pyx
  src/sage/groups/matrix_gps/group_element.pyx
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pxd
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
  src/sage/groups/perm_gps/partn_ref/canonical_augmentation.pxd
  src/sage/groups/perm_gps/partn_ref/canonical_augmentation.pyx
  src/sage/groups/perm_gps/partn_ref/double_coset.pxd
  src/sage/groups/perm_gps/partn_ref/double_coset.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pxd
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pxd
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_lists.pxd
  src/sage/groups/perm_gps/partn_ref/refinement_lists.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pxd
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_python.pxd
  src/sage/groups/perm_gps/partn_ref/refinement_python.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_sets.pxd
  src/sage/groups/perm_gps/partn_ref/refinement_sets.pyx
  src/sage/numerical/backends/cvxopt_backend.pyx
  src/sage/numerical/backends/cvxopt_sdp_backend.pyx
  src/sage/numerical/backends/glpk_backend.pxd
  src/sage/numerical/backends/glpk_exact_backend.pxd
  src/sage/numerical/backends/matrix_sdp_backend.pxd
  src/sage/numerical/backends/matrix_sdp_backend.pyx
  src/sage/numerical/backends/ppl_backend.pyx
  src/sage/numerical/backends/scip_backend.pxd
  src/sage/plot/plot3d/base.pyx
  src/sage/plot/plot3d/index_face_set.pxd
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/plot/plot3d/parametric_surface.pxd
  src/sage/plot/plot3d/parametric_surface.pyx
  src/sage/plot/plot3d/shapes.pxd
  src/sage/plot/plot3d/shapes.pyx
Labels: s: positive review, t: refactoring

#36598 Relativize header imports
  src/sage/ext/cplusplus.pxd
  src/sage/libs/ntl/convert.pyx
  src/sage/modular/arithgroup/farey_symbol.pyx
  src/sage/rings/padics/padic_capped_absolute_element.pyx
  src/sage/rings/padics/padic_capped_relative_element.pyx
  src/sage/rings/padics/padic_fixed_mod_element.pyx
  src/sage/rings/padics/padic_floating_point_element.pyx
Labels: s: positive review, t: refactoring

#36600 Support giac 1.9.0-67
  src/sage/libs/giac/__init__.py
Labels: c: packages: standard, s: positive review

#36601 Doc preview for all languages
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/doc-publish.yml
  src/sage/misc/sageinspect.py
Labels: s: positive review, c: scripts

#36604 Calculation of Maximum Leaf Number graph parameter
  src/sage/graphs/domination.py
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#36605 Replace relative imports by absolute ones in `sage.libs.ntl`
  src/sage/libs/ntl/GF2.pxd
  src/sage/libs/ntl/GF2E.pxd
  src/sage/libs/ntl/GF2EX.pxd
  src/sage/libs/ntl/GF2X.pxd
  src/sage/libs/ntl/ZZ.pxd
  src/sage/libs/ntl/ZZX.pxd
  src/sage/libs/ntl/ZZ_p.pxd
  src/sage/libs/ntl/ZZ_pE.pxd
  src/sage/libs/ntl/ZZ_pEX.pxd
  src/sage/libs/ntl/ZZ_pX.pxd
  src/sage/libs/ntl/__init__.py
  src/sage/libs/ntl/conversion.pxd
  src/sage/libs/ntl/convert.pxd
  src/sage/libs/ntl/error.pyx
  src/sage/libs/ntl/lzz_p.pxd
  src/sage/libs/ntl/lzz_pX.pxd
  src/sage/libs/ntl/mat_GF2.pxd
  src/sage/libs/ntl/mat_GF2E.pxd
  src/sage/libs/ntl/mat_ZZ.pxd
  src/sage/libs/ntl/ntl_GF2.pxd
  src/sage/libs/ntl/ntl_GF2E.pxd
  src/sage/libs/ntl/ntl_GF2E.pyx
  src/sage/libs/ntl/ntl_GF2EContext.pxd
  src/sage/libs/ntl/ntl_GF2EX.pxd
  src/sage/libs/ntl/ntl_GF2EX.pyx
  src/sage/libs/ntl/ntl_GF2X.pxd
  src/sage/libs/ntl/ntl_GF2X.pyx
  src/sage/libs/ntl/ntl_ZZX.pxd
  src/sage/libs/ntl/ntl_ZZ_p.pxd
  src/sage/libs/ntl/ntl_ZZ_pContext.pxd
  src/sage/libs/ntl/ntl_ZZ_pE.pxd
  src/sage/libs/ntl/ntl_ZZ_pEContext.pxd
  src/sage/libs/ntl/ntl_ZZ_pEContext.pyx
  src/sage/libs/ntl/ntl_ZZ_pEX.pxd
  src/sage/libs/ntl/ntl_ZZ_pX.pxd
  src/sage/libs/ntl/ntl_lzz_p.pxd
  src/sage/libs/ntl/ntl_lzz_pContext.pxd
  src/sage/libs/ntl/ntl_mat_GF2.pxd
  src/sage/libs/ntl/ntl_mat_GF2.pyx
  src/sage/libs/ntl/ntl_mat_GF2E.pxd
  src/sage/libs/ntl/ntl_mat_GF2E.pyx
  src/sage/libs/ntl/ntl_mat_ZZ.pxd
  src/sage/libs/ntl/ntl_mat_ZZ.pyx
  src/sage/libs/ntl/vec_GF2.pxd
  src/sage/libs/ntl/vec_GF2E.pxd
Labels: s: positive review, t: refactoring

#36606 ruff fix UP027 (list comprehension)
  src/sage/algebras/hecke_algebras/cubic_hecke_algebra.py
  src/sage/algebras/hecke_algebras/cubic_hecke_matrix_rep.py
  src/sage/calculus/calculus.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/permutation.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/geometry/hyperbolic_space/hyperbolic_isometry.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/geometry/polyhedron/plot.py
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/generators/classical_geometries.py
  src/sage/graphs/generators/random.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/graph_generators.py
  src/sage/misc/package_dir.py
  src/sage/modular/local_comp/liftings.py
  src/sage/modular/local_comp/local_comp.py
  src/sage/plot/contour_plot.py
  src/sage/plot/density_plot.py
  src/sage/plot/plot3d/plot_field3d.py
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/ternary_qf.py
  src/sage/rings/number_field/number_field.py
  src/sage/schemes/cyclic_covers/cycliccover_finite_field.py
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/height.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
  src/sage/topology/simplicial_set_examples.py
Labels: s: positive review, t: refactoring

#36607 write Weyl with a capital letter
  src/sage/categories/affine_weyl_groups.py
  src/sage/categories/category.py
  src/sage/categories/examples/finite_weyl_groups.py
  src/sage/categories/finite_weyl_groups.py
  src/sage/categories/weyl_groups.py
  src/sage/combinat/root_system/coxeter_group.py
  src/sage/combinat/root_system/weyl_group.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/misc/c3_controlled.pyx
Labels: t: enhancement, s: positive review, c: categories

#36608 some changes by ruff UP
  src/sage/env.py
  src/sage/features/__init__.py
  src/sage/features/latex.py
  src/sage/features/pkg_systems.py
Labels: s: positive review, t: refactoring

#36609 avoid using `itertools.pairwise`
  src/sage/graphs/generic_graph.py
Labels: s: positive review, p: blocker / 1, c: graph theory

#36611 fix the links to msolve spkg
  src/sage/rings/polynomial/msolve.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: t: bug, s: positive review, c: documentation, c: interfaces: optional

#36613 .github/workflows/dist.yml: Fix deprecation message
  .github/workflows/dist.yml
Labels: p: minor / 4, s: positive review, c: scripts

#36616 CI Linux: Increase max_parallel for `standard-pre`, decrease for `standard`, `minimal-pre`
  .github/workflows/ci-linux.yml
Labels: s: positive review, c: scripts

#36625 RSA primes must be odd (textbook code fix)
  src/sage/tests/book_stein_ent.py
Labels: t: bug, s: positive review, c: documentation

#36628 some simplifications in doctest/ folder (ruff C4)
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
  src/sage/doctest/reporting.py
  src/sage/doctest/sources.py
  src/sage/doctest/util.py
Labels: s: positive review, c: doctest framework, t: refactoring

#36453 Exclude Cython 3.0.3
  build/pkgs/cython/distros/conda.txt
  build/pkgs/cython/install-requires.txt
Labels: s: positive review, c: distribution

#36477 fplll 5.4.5, fpylll 0.6
  build/pkgs/fplll/checksums.ini
  build/pkgs/fplll/package-version.txt
  build/pkgs/fplll/spkg-configure.m4
  build/pkgs/fpylll/checksums.ini
  build/pkgs/fpylll/package-version.txt
  build/pkgs/fpylll/patches/cython3-legacy.patch
Labels: c: packages: standard, s: positive review

#35053 Added kth roots to Permutation
  src/sage/combinat/permutation.py
Labels: t: enhancement, s: positive review, c: combinatorics

#35269 Implement characteristic polynomial computation for Drinfeld modules of any Rank
  src/doc/en/reference/references/index.rst
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
Labels: s: positive review, c: algebra

#36533 `pkgs/sage-conf_pypi`: Repair after #36400, #36435
  pkgs/sage-conf/.gitignore
  pkgs/sage-conf_pypi/sage_root/.upstream.d
  pkgs/sage-conf_pypi/setup.py
  pkgs/sage-conf_pypi/tox.ini
Labels: s: positive review, p: blocker / 1, c: distribution

#36599 sage-env: identify the version of command-line tools (OS X) and set LDFLAGS accordingly
  src/bin/sage-env
Labels: t: enhancement, s: positive review, c: build, p: blocker / 1

#36648 CI macOS: Update
  .github/workflows/ci-macos.yml
  .github/workflows/macos.yml
Labels: s: positive review, p: blocker / 1, c: scripts

#36659 prompt_toolkit: Set version constraint for conda
  build/pkgs/prompt_toolkit/distros/conda.txt
Labels: s: positive review, p: blocker / 1, c: distribution

#36534 CI Linux: Fix `centos-7` after #36435, remove `gentoo-python3.12` for now, use `conda-forge` with `-python3.11`
  .github/workflows/docker.yml
  build/pkgs/_python3.10/distros/conda.txt
  build/pkgs/_python3.11/distros/conda.txt
  build/pkgs/_python3.12/distros/conda.txt
  build/pkgs/_python3.9/distros/conda.txt
  tox.ini
Labels: s: positive review, p: blocker / 1, c: scripts

#36669 Sage knows Hadamard matrices <1201, not 1001
  build/pkgs/configure/checksums.ini
  build/pkgs/configure/package-version.txt
  src/doc/en/reference/references/index.rst
  src/sage/combinat/matrices/hadamard_matrix.py
Labels: s: positive review, c: documentation, c: combinatorics, p: blocker / 1

#36671 build/pkgs/openblas: Stop openblas from using explicit `make -j N`; but use `make -j 1` on `ubuntu-trusty`
  build/pkgs/openblas/spkg-install.in
Labels: c: packages: standard, s: positive review, p: blocker / 1

#36698 src/sage/combinat/root_system/coxeter_group.py: Fix typo in lazy_import
  build/pkgs/configure/checksums.ini
  build/pkgs/configure/package-version.txt
  src/sage/combinat/root_system/coxeter_group.py
Labels: s: positive review, c: combinatorics, p: blocker / 1

#36529 src/sage/misc/latex.py: fix view()
  src/sage/misc/latex.py
Labels: s: positive review, p: blocker / 1

#36692 Make doc-pdf separate from doc-html
  src/doc/Makefile
  src/doc/en/reference/references/index.rst
  src/doc/en/website/root_index.html
  src/doc/en/website/templates/index.html
  src/doc/en/website/templates/index_furo.html
  src/sage/combinat/species/generating_series.py
  src/sage/rings/lazy_series.py
  src/sage_docbuild/builders.py
  src/sage_docbuild/conf.py
Labels: s: positive review, c: build, c: documentation, p: blocker / 1

#36696 Fix SSL timeout in doctest / internet feature
  src/sage/doctest/control.py
  src/sage/features/internet.py
Labels: s: positive review, p: blocker / 1

#36699 CI Linux: Follow-up fix for conda-forge-python3.11
  build/pkgs/_python3.10/distros/conda.txt
  build/pkgs/_python3.11/distros/conda.txt
  build/pkgs/_python3.12/distros/conda.txt
  build/pkgs/_python3.9/distros/conda.txt
  tox.ini
Labels: s: positive review, p: blocker / 1, c: scripts

#36707 `build/pkgs/nauty`: Handle `SAGE_FAT_BINARY`
  build/pkgs/nauty/package-version.txt
  build/pkgs/nauty/spkg-install.in
Labels: c: packages: standard, s: positive review, p: blocker / 1

#36708 CI Linux: Fixes for tests of optional packages
  .github/workflows/ci-linux.yml
  build/make/install
  build/pkgs/database_cubic_hecke/dependencies_check
  build/pkgs/database_knotinfo/dependencies_check
  build/pkgs/mathics/dependencies_check
Labels: s: positive review, p: blocker / 1, c: packages: optional, c: scripts

#36660 .github/workflows/ci-linux.yml: Fine-tune max-parallel
  .github/workflows/ci-linux.yml
Labels: s: positive review, p: blocker / 1, c: scripts

#36670 .github/workflows/docker.yml: Interrupt the build before the 6 hour cancellation
  .github/workflows/docker.yml
Labels: s: positive review, p: blocker / 1, c: scripts

#36712 `opensuse-tumbleweed-minimal`: Ensure gawk is present
  build/pkgs/_prereq/distros/opensuse.txt
Labels: s: positive review, p: blocker / 1, c: distribution

#36722 `openblas`: Update to 0.3.25
  build/pkgs/openblas/checksums.ini
  build/pkgs/openblas/package-version.txt
Labels: c: packages: standard, s: positive review, p: blocker / 1

#36617 CI: Make jobs more responsive to canceling
  .github/workflows/build.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/lint.yml
Labels: s: positive review, p: blocker / 1, c: scripts

#36731 `build/pkgs/pillow`: Allow discovery of libjpeg, upgrade to 10.1.0
  .github/workflows/ci-linux-incremental.yml
  build/bin/sage-build-env-config.in
  build/pkgs/_recommended/dependencies
  build/pkgs/libjpeg/SPKG.rst
  build/pkgs/libjpeg/distros/alpine.txt
  build/pkgs/libjpeg/distros/arch.txt
  build/pkgs/libjpeg/distros/debian.txt
  build/pkgs/libjpeg/distros/fedora.txt
  build/pkgs/libjpeg/distros/gentoo.txt
  build/pkgs/libjpeg/distros/homebrew.txt
  build/pkgs/libjpeg/distros/nix.txt
  build/pkgs/libjpeg/distros/opensuse.txt
  build/pkgs/libjpeg/distros/slackware.txt
  build/pkgs/libjpeg/distros/void.txt
  build/pkgs/libjpeg/spkg-configure.m4
  build/pkgs/libjpeg/type
  build/pkgs/pandoc/SPKG.rst
  build/pkgs/pillow/checksums.ini
  build/pkgs/pillow/package-version.txt
  build/pkgs/pillow/spkg-install.in
Labels: c: packages: standard, s: positive review, p: blocker / 1

#36737 Fix `make SPKG-uninstall` for Python packages after #36452
  build/sage_bootstrap/uninstall.py
Labels: s: positive review, p: blocker / 1
