Repository sagemath/sage, pull requests merged in 2023-10, with the labels that each got.

#36123 Upgrade numpy to 1.26.0, setuptools to 68.2.2
  build/pkgs/numpy/checksums.ini
  build/pkgs/numpy/dependencies
  build/pkgs/numpy/lapack_conf.py
  build/pkgs/numpy/package-version.txt
  build/pkgs/numpy/patches/21891.patch
  build/pkgs/numpy/patches/cython3-legacy.patch
  build/pkgs/numpy/spkg-install.in
  build/pkgs/pip/checksums.ini
  build/pkgs/pip/package-version.txt
  build/pkgs/setuptools/SPKG.rst
  build/pkgs/setuptools/checksums.ini
  build/pkgs/setuptools/install-requires.txt
  build/pkgs/setuptools/package-version.txt
  build/pkgs/setuptools_wheel/SPKG.rst
  build/pkgs/setuptools_wheel/checksums.ini
  build/pkgs/setuptools_wheel/install-requires.txt
  build/pkgs/setuptools_wheel/package-version.txt
  src/sage/repl/ipython_kernel/kernel.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#36261 `sage.rings.padics`: Import fixes (modularization)
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/padic_extension_generic.py
  src/sage/rings/padics/padic_extension_leaves.py
Labels: s: positive review, c: padics, t: refactoring

#36272 `sage.sets`: Update `# needs`
  src/sage/sets/cartesian_product.py
  src/sage/sets/condition_set.py
  src/sage/sets/disjoint_set.pyx
  src/sage/sets/disjoint_union_enumerated_sets.py
  src/sage/sets/family.py
  src/sage/sets/image_set.py
  src/sage/sets/integer_range.py
  src/sage/sets/non_negative_integers.py
  src/sage/sets/positive_integers.py
  src/sage/sets/primes.py
  src/sage/sets/real_set.py
  src/sage/sets/recursively_enumerated_set.pyx
  src/sage/sets/set.py
  src/sage/sets/set_from_iterator.py
  src/sage/sets/totally_ordered_finite_set.py
Labels: s: positive review, t: refactoring

#36277 `sage.graphs`: some care with return ... else statements in `graph.py`, `digraph.py` and `bipartite_graph.py`
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/digraph.py
  src/sage/graphs/graph.py
Labels: t: enhancement, s: positive review, c: graph theory

#36285 add Rémy Oudompheng's implementation of the BMSS algorithm
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves, t: performance

#36310 Mod 2 (co)homology as a module over the Steenrod algebra
  src/doc/en/reference/references/index.rst
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/topology/cell_complex.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebraic topology

#36314 add q-Fuss-Catalan numbers
  src/sage/combinat/q_analogues.py
Labels: p: minor / 4, s: positive review, c: combinatorics

#36324 src/sage/tests/cmdline.py: replace tmp_dir()
  src/sage/tests/cmdline.py
Labels: s: positive review, t: refactoring

#36343 src/sage/repl/interpreter.py: replace tmp_dir()
  src/sage/repl/interpreter.py
Labels: s: positive review, t: refactoring

#36344 src/sage/misc/cython.py: replace tmp_dir()
  src/sage/misc/cython.py
Labels: s: positive review, t: refactoring

#36357 CI: Remove ci-wsl, ci-cygwin-standard
  .github/workflows/ci-cygwin-standard.yml
  .github/workflows/ci-wsl.yml
Labels: s: positive review, c: scripts

#36358 CI: Fix the multi-stage build in ci-linux.yml, fix conda/centos/archlinux system packages
  .github/workflows/docker.yml
  .github/workflows/scan-logs.sh
  build/bin/write-dockerfile.sh
  build/pkgs/_bootstrap/distros/arch.txt
  build/pkgs/_python3.10/distros/fedora.txt
  build/pkgs/_python3.11/distros/fedora.txt
  build/pkgs/_python3.12/distros/fedora.txt
  build/pkgs/_python3.9/distros/fedora.txt
  build/pkgs/freetype/distros/debian.txt
  build/pkgs/pkgconf/distros/arch.txt
  tox.ini
Labels: s: positive review, p: critical / 2, c: scripts

#36359 a few details in combinat (designs)
  src/sage/combinat/designs/group_divisible_designs.py
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/combinat/designs/twographs.py
  src/sage/combinat/matrices/dlxcpp.py
  src/sage/combinat/tuple.py
Labels: s: positive review, c: combinatorics

#36362 a few more links to errors in the doc
  src/sage/categories/sets_with_partial_maps.py
  src/sage/graphs/generic_graph.py
  src/sage/interfaces/axiom.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/giac.py
  src/sage/interfaces/maple.py
  src/sage/interfaces/maxima.py
  src/sage/interfaces/mwrank.py
  src/sage/libs/gap/libgap.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/modular/abvar/abvar.py
  src/sage/modular/modsym/p1list.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/padics/padic_extension_generic.py
  src/sage/rings/padics/padic_floating_point_element.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/tensor/modules/tensor_with_indices.py
Labels: s: positive review, c: documentation

#36364 Do not run sage-env more than once, for real.
  src/bin/sage-env
Labels: s: positive review, p: critical / 2, c: scripts

#36365 Libgap cubegroup
  src/sage/groups/perm_gps/cubegroup.py
Labels: s: positive review, c: group theory

#36369 partial cython-lint cleanup in padics/
  src/sage/rings/padics/CA_template.pxi
  src/sage/rings/padics/CR_template.pxi
  src/sage/rings/padics/FM_template.pxi
  src/sage/rings/padics/FP_template.pxi
  src/sage/rings/padics/local_generic_element.pyx
  src/sage/rings/padics/morphism.pxd
  src/sage/rings/padics/morphism.pyx
  src/sage/rings/padics/padic_ZZ_pX_CA_element.pyx
  src/sage/rings/padics/padic_ZZ_pX_CR_element.pyx
  src/sage/rings/padics/padic_ZZ_pX_FM_element.pyx
  src/sage/rings/padics/padic_ZZ_pX_element.pyx
  src/sage/rings/padics/padic_capped_relative_element.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/padics/padic_relaxed_errors.pyx
  src/sage/rings/padics/padic_template_element.pxi
  src/sage/rings/padics/pow_computer.pyx
  src/sage/rings/padics/pow_computer_ext.pxd
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/padics/pow_computer_relative.pyx
  src/sage/rings/padics/qadic_flint_FP.pyx
  src/sage/rings/padics/relaxed_template.pxi
Labels: s: positive review, c: padics, t: refactoring

#36371 fix remaining W605 warnings in pxi files
  src/sage/libs/linkages/padics/API.pxi
  src/sage/libs/linkages/padics/fmpz_poly_unram.pxi
  src/sage/libs/linkages/padics/mpz.pxi
  src/sage/libs/linkages/padics/unram_shared.pxi
  src/sage/libs/symmetrica/sc.pxi
  src/sage/matrix/matrix_modn_dense_template.pxi
  src/sage/symbolic/series_impl.pxi
Labels: s: positive review, t: refactoring

#36373 Enable conda ci for all PRs and remove experimental label
  .github/workflows/ci-conda.yml
  src/doc/en/installation/conda.rst
Labels: s: positive review, c: scripts

#36374 refresh the cython file real_roots (pep8, range, etc)
  src/sage/rings/polynomial/real_roots.pyx
Labels: s: positive review, t: refactoring

#36375 src/sage/interfaces/gap_workspace.py: replace tmp_dir()
  src/sage/interfaces/gap_workspace.py
Labels: s: positive review, t: refactoring

#36376 src/sage/databases/sql_db.py: replace tmp_dir()
  src/sage/databases/sql_db.py
Labels: s: positive review, t: refactoring

#36377 clean one test file
  src/sage/tests/benchmark.py
Labels: s: positive review, t: refactoring

#36378 Add README.md Table of Contents and Links
  README.md
Labels: s: positive review, c: documentation

#36381 Python package upgrades cherry-picked from notebook 7 upgrade PR
  build/pkgs/attrs/checksums.ini
  build/pkgs/attrs/package-version.txt
  build/pkgs/babel/checksums.ini
  build/pkgs/babel/package-version.txt
  build/pkgs/certifi/checksums.ini
  build/pkgs/certifi/package-version.txt
  build/pkgs/importlib_metadata/checksums.ini
  build/pkgs/importlib_metadata/package-version.txt
  build/pkgs/importlib_resources/checksums.ini
  build/pkgs/importlib_resources/package-version.txt
  build/pkgs/markupsafe/checksums.ini
  build/pkgs/markupsafe/package-version.txt
  build/pkgs/pytz/checksums.ini
  build/pkgs/pytz/package-version.txt
  build/pkgs/tzlocal/checksums.ini
  build/pkgs/tzlocal/package-version.txt
Labels: c: packages: standard, s: positive review

#36382 `configure --enable-system-site-packages`: First check all non-site packages
  bootstrap
Labels: p: minor / 4, s: positive review, c: build: configure

#36383 Update flint to 2.9.0, arb to 2.23.0
  build/pkgs/arb/checksums.ini
  build/pkgs/arb/package-version.txt
  build/pkgs/flint/checksums.ini
  build/pkgs/flint/package-version.txt
  build/pkgs/flint/spkg-configure.m4
Labels: c: packages: standard, s: positive review, c: build: configure

#36388 fix typographic typos
  src/doc/en/thematic_tutorials/tutorial-implementing-algebraic-structures.rst
Labels: s: positive review, c: documentation

#35285 System package information tox ini gh actions for alpine linux
  build/bin/sage-print-system-package-command
  build/bin/write-dockerfile.sh
  build/pkgs/_bootstrap/distros/alpine.txt
  build/pkgs/_prereq/distros/alpine.txt
  build/pkgs/bzip2/distros/alpine.txt
  build/pkgs/curl/distros/alpine.txt
  build/pkgs/flint/distros/alpine.txt
  build/pkgs/freetype/distros/alpine.txt
  build/pkgs/gc/distros/alpine.txt
  build/pkgs/gdb/distros/alpine.txt
  build/pkgs/gengetopt/distros/alpine.txt
  build/pkgs/gf2x/distros/alpine.txt
  build/pkgs/gfortran/distros/alpine.txt
  build/pkgs/glpk/distros/alpine.txt
  build/pkgs/gmp/distros/alpine.txt
  build/pkgs/graphviz/distros/alpine.txt
  build/pkgs/gsl/distros/alpine.txt
  build/pkgs/libatomic_ops/distros/alpine.txt
  build/pkgs/libffi/distros/alpine.txt
  build/pkgs/libgd/distros/alpine.txt
  build/pkgs/liblzma/distros/alpine.txt
  build/pkgs/libpng/distros/alpine.txt
  build/pkgs/mpc/distros/alpine.txt
  build/pkgs/mpfr/distros/alpine.txt
  build/pkgs/ncurses/distros/alpine.txt
  build/pkgs/openblas/distros/alpine.txt
  build/pkgs/pari/distros/alpine.txt
  build/pkgs/patch/distros/alpine.txt
  build/pkgs/pcre/distros/alpine.txt
  build/pkgs/perl_cpan_polymake_prereq/distros/alpine.txt
  build/pkgs/perl_term_readline_gnu/distros/alpine.txt
  build/pkgs/qhull/distros/alpine.txt
  build/pkgs/r/distros/alpine.txt
  build/pkgs/sqlite/distros/alpine.txt
  build/pkgs/suitesparse/distros/alpine.txt
  build/pkgs/valgrind/distros/alpine.txt
  build/pkgs/xz/distros/alpine.txt
  build/pkgs/zeromq/distros/alpine.txt
  build/pkgs/zlib/distros/alpine.txt
  tox.ini
Labels: s: positive review, c: build: configure

#35373 Fix workflow "Build documentation (PDF)"
  .github/workflows/build.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
Labels: s: positive review, p: critical / 2, c: scripts

#35546 compute traces of elliptic-curve endomorphisms
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/hom.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#36161 Upgrade pplpy to 0.8.9
  build/pkgs/pplpy/checksums.ini
  build/pkgs/pplpy/package-version.txt
  build/pkgs/pplpy/patches/cython3-legacy.patch
  build/pkgs/pplpy/patches/relative-import.patch
Labels: c: packages: standard, s: positive review

#35008 Implement Covering Arrays
  src/doc/en/reference/combinat/module_list.rst
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/covering_array.py
  src/sage/combinat/designs/design_catalog.py
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/orthogonal_arrays.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: combinatorial designs

#35062 Enable merge_group trigger for merge queues
  .github/workflows/build.yml
  .github/workflows/doc-build.yml
  .github/workflows/lint.yml
Labels: s: positive review

#36354 added induced minor function to graph algorithms
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#36389 fix for ecl in distros/gentoo.txt
  build/pkgs/ecl/distros/gentoo.txt
  build/pkgs/maxima/distros/gentoo.txt
Labels: s: positive review, c: build: configure

#36391 checking that the system maxima has working help
  build/bin/write-dockerfile.sh
  build/pkgs/maxima/spkg-configure.m4
Labels: c: packages: standard, s: positive review, c: build: configure

#36392 a few details in combinat, as suggested by ruff
  src/sage/combinat/bijectionist.py
  src/sage/combinat/binary_recurrence_sequences.py
  src/sage/combinat/composition_tableau.py
  src/sage/combinat/crystals/crystals.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/matrices/hadamard_matrix.py
  src/sage/combinat/partition.py
  src/sage/combinat/root_system/root_lattice_realization_algebras.py
  src/sage/combinat/skew_partition.py
  src/sage/combinat/words/abstract_word.py
Labels: s: positive review, c: combinatorics

#36393 `sage --package list`: Sort output, add switches `--{in,ex}clude-dependencies`
  bootstrap
  build/bin/sage-package
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
  build/sage_bootstrap/expand_class.py
  build/sage_bootstrap/package.py
  src/doc/bootstrap
Labels: s: positive review, c: scripts

#36394 Deprecate the backslash operator
  src/doc/de/tutorial/tour_linalg.rst
  src/doc/en/tutorial/tour_linalg.rst
  src/doc/es/tutorial/tour_linalg.rst
  src/doc/fr/tutorial/tour_linalg.rst
  src/doc/ja/tutorial/tour_linalg.rst
  src/doc/pt/tutorial/tour_linalg.rst
  src/doc/ru/tutorial/tour_linalg.rst
  src/sage/combinat/binary_tree.py
  src/sage/features/sagemath.py
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_complex_ball_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/matrix_modn_dense_template.pxi
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_space.py
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/catalog.py
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/minor_matroid.py
  src/sage/misc/misc.py
  src/sage/tests/books/computational-mathematics-with-sagemath/linalg_doctest.py
  src/sage/tests/books/computational-mathematics-with-sagemath/linsolve_doctest.py
Labels: p: major / 3, t: enhancement, s: positive review

#36397 Fix element labeling in `OperationTable.color_table`
  src/sage/matrix/operation_table.py
Labels: s: positive review

#36398 two minor details in groups
  src/sage/groups/abelian_gps/dual_abelian_group.py
  src/sage/groups/artin.py
Labels: s: positive review, c: group theory

#36399 fixing category of ncsym and dual
  src/sage/combinat/ncsym/dual.py
  src/sage/combinat/ncsym/ncsym.py
Labels: s: positive review, c: combinatorics

#36402 bump cysignals to 1.11.4
  build/pkgs/cysignals/checksums.ini
  build/pkgs/cysignals/package-version.txt
  build/pkgs/cysignals/patches/cython3-fix-warning.patch
  build/pkgs/cysignals/patches/cython3-legacy.patch
Labels: c: packages: standard, s: positive review, p: critical / 2

#36405 `bootstrap-conda`: Refactor, generate versioned environment files
  .devcontainer/onCreate-conda.sh
  .github/workflows/ci-conda.yml
  .gitignore
  .gitpod.yml
  Makefile
  bootstrap
  bootstrap-conda
  build/pkgs/matplotlib/distros/conda.txt
  src/doc/en/installation/conda.rst
  tox.ini
Labels: s: positive review, c: scripts, s: run conda ci

#36412 Upgrade `scipy` to 1.11.3, `meson_python` to 0.14.0, `meson` to 1.2.2
  build/pkgs/meson/checksums.ini
  build/pkgs/meson/package-version.txt
  build/pkgs/meson_python/checksums.ini
  build/pkgs/meson_python/package-version.txt
  build/pkgs/scipy/checksums.ini
  build/pkgs/scipy/package-version.txt
Labels: c: packages: standard, s: positive review

#36413 various details in schemes
  src/sage/schemes/affine/affine_subscheme.py
  src/sage/schemes/curves/closed_point.py
  src/sage/schemes/curves/curve.py
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/isogeny_class.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/schemes/hyperelliptic_curves/constructor.py
  src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
  src/sage/schemes/plane_conics/con_number_field.py
  src/sage/schemes/plane_conics/con_rational_field.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
Labels: s: positive review, c: algebraic geometry, t: refactoring

#36415 README: Recommend `configure --config-cache --enable-ccache`
  README.md
  build/pkgs/glpk/spkg-configure.m4
  build/pkgs/mpc/spkg-configure.m4
  build/pkgs/mpfr/spkg-configure.m4
  build/pkgs/pkgconf/spkg-configure.m4
Labels: p: minor / 4, s: positive review, c: documentation, c: build: configure

#36418 .github/workflows/docker.yml: Free more disk space
  .github/workflows/docker.yml
Labels: c: packages: standard, s: positive review

#36420 fix for E702 in pyx outside rings
  src/sage/coding/binary_code.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/rings/polynomial/polynomial_complex_arb.pyx
Labels: s: positive review, t: refactoring

#36422 replace wrongly placed sig_on/off pair with sig_check
  src/sage/libs/mpmath/ext_main.pyx
Labels: t: bug, s: positive review, c: interfaces

#36424 adding some links for Errors in the doc
  src/sage/combinat/binary_recurrence_sequences.py
  src/sage/combinat/cartesian_product.py
  src/sage/combinat/dyck_word.py
  src/sage/combinat/free_module.py
  src/sage/combinat/fully_commutative_elements.py
  src/sage/combinat/integer_lists/invlex.pyx
  src/sage/combinat/nu_dyck_word.py
  src/sage/combinat/perfect_matching.py
  src/sage/combinat/ranker.py
  src/sage/combinat/root_system/associahedron.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/skew_partition.py
  src/sage/combinat/tableau_residues.py
  src/sage/crypto/sbox.pyx
  src/sage/databases/sloane.py
  src/sage/ext/fast_callable.pyx
  src/sage/ext/memory.pyx
  src/sage/game_theory/normal_form_game.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/gap.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/quivers/homspace.py
  src/sage/quivers/morphism.py
  src/sage/quivers/path_semigroup.py
  src/sage/quivers/representation.py
  src/sage/stats/distributions/discrete_gaussian_lattice.py
  src/sage/stats/time_series.pyx
  src/sage/topology/cubical_complex.py
  src/sage/topology/simplicial_complex.py
  src/sage_docbuild/utils.py
Labels: s: positive review, c: documentation

#36426 cleanup of gap3 interface file
  src/sage/interfaces/gap3.py
Labels: p: minor / 4, s: positive review, c: interfaces

#36313 tentative of random subset for random matrix
  src/sage/matrix/special.py
Labels: s: positive review, c: linear algebra

#36325 Refactor Drinfeld modules subclasses
  src/doc/en/reference/drinfeld_modules/index.rst
  src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
Labels: s: positive review, c: algebra, t: refactoring

#36461 fix the linters again
  src/sage/graphs/graph.py
Labels: s: positive review, p: blocker / 1, t: refactoring

#36464 fix doctest in `src/sage/combinat/posets/posets.py`
  src/sage/combinat/posets/posets.py
Labels: s: positive review, p: trivial / 5, c: combinatorics

#36468 Fix mamba install in conda ci workflow
  .github/workflows/ci-conda.yml
Labels: s: positive review, p: critical / 2

#36470 refresh macaulay2 interface a little bit
  src/sage/interfaces/macaulay2.py
Labels: s: positive review, c: packages: optional

#36474 add ruff to developer tools
  src/doc/en/developer/tools.rst
Labels: s: positive review, c: documentation

#36304 `sage.symbolics`: Remove code deprecated in #18036, #29738, #32386, #32638, #32665, #34215
  src/doc/en/reference/calculus/index.rst
  src/sage/combinat/words/alphabet.py
  src/sage/symbolic/all.py
  src/sage/symbolic/callable.py
  src/sage/symbolic/comparison.py
  src/sage/symbolic/constant.py
  src/sage/symbolic/constants_c.py
  src/sage/symbolic/expression.pxd
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/getitem.py
  src/sage/symbolic/pynac_constant.py
  src/sage/symbolic/ring.pyx
  src/sage/symbolic/series.py
  src/sage/symbolic/substitution_map.py
Labels: t: enhancement, s: positive review, c: symbolics

#36315 Replace shell bunzip2 with library code
  src/sage/misc/persist.pyx
Labels: s: positive review

#36320 Update `matplotlib` to 3.8.0, `pillow` to 10.0.1
  build/bin/sage-dist-helpers
  build/pkgs/contourpy/checksums.ini
  build/pkgs/contourpy/dependencies
  build/pkgs/contourpy/package-version.txt
  build/pkgs/contourpy/spkg-install.in
  build/pkgs/fonttools/checksums.ini
  build/pkgs/fonttools/package-version.txt
  build/pkgs/kiwisolver/checksums.ini
  build/pkgs/kiwisolver/package-version.txt
  build/pkgs/matplotlib/checksums.ini
  build/pkgs/matplotlib/package-version.txt
  build/pkgs/pillow/checksums.ini
  build/pkgs/pillow/package-version.txt
  build/pkgs/pillow/spkg-install.in
  build/pkgs/pyparsing/checksums.ini
  build/pkgs/pyparsing/package-version.txt
Labels: c: packages: standard, s: positive review, c: graphics

#36332 Yet more more spkgs confs
  build/pkgs/appnope/spkg-configure.m4
  build/pkgs/argon2_cffi_bindings/distros/alpine.txt
  build/pkgs/argon2_cffi_bindings/distros/arch.txt
  build/pkgs/argon2_cffi_bindings/distros/fedora.txt
  build/pkgs/argon2_cffi_bindings/distros/freebsd.txt
  build/pkgs/argon2_cffi_bindings/distros/gentoo.txt
  build/pkgs/argon2_cffi_bindings/distros/macports.txt
  build/pkgs/argon2_cffi_bindings/distros/opensuse.txt
  build/pkgs/argon2_cffi_bindings/spkg-configure.m4
  build/pkgs/calver/distros/alpine.txt
  build/pkgs/calver/distros/arch.txt
  build/pkgs/calver/distros/freebsd.txt
  build/pkgs/calver/distros/gentoo.txt
  build/pkgs/calver/distros/macports.txt
  build/pkgs/calver/distros/opensuse.txt
  build/pkgs/calver/distros/package-version.txt
  build/pkgs/calver/distros/void.txt
  build/pkgs/calver/spkg-configure.m4
  build/pkgs/cython/patches/5690.patch
  build/pkgs/cython/spkg-configure.m4
  build/pkgs/fastjsonschema/distros/alpine.txt
  build/pkgs/fastjsonschema/distros/arch.txt
  build/pkgs/fastjsonschema/distros/debian.txt
  build/pkgs/fastjsonschema/distros/fedora.txt
  build/pkgs/fastjsonschema/distros/freebsd.txt
  build/pkgs/fastjsonschema/distros/gentoo.txt
  build/pkgs/fastjsonschema/distros/macports.txt
  build/pkgs/fastjsonschema/distros/opensuse.txt
  build/pkgs/fastjsonschema/distros/void.txt
  build/pkgs/fastjsonschema/spkg-configure.m4
  build/pkgs/hatch_fancy_pypi_readme/distros/alpine.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/arch.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/debian.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/fedora.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/freebsd.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/gentoo.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/macports.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/opensuse.txt
  build/pkgs/hatch_fancy_pypi_readme/spkg-configure.m4
  build/pkgs/hatch_vcs/distros/alpine.txt
  build/pkgs/hatch_vcs/distros/arch.txt
  build/pkgs/hatch_vcs/distros/debian.txt
  build/pkgs/hatch_vcs/distros/fedora.txt
  build/pkgs/hatch_vcs/distros/freebsd.txt
  build/pkgs/hatch_vcs/distros/gentoo.txt
  build/pkgs/hatch_vcs/distros/macports.txt
  build/pkgs/hatch_vcs/distros/opensuse.txt
  build/pkgs/hatch_vcs/distros/void.txt
  build/pkgs/hatch_vcs/spkg-configure.m4
  build/pkgs/stack_data/distros/gentoo.txt
  build/pkgs/trove_classifiers/distros/alpine.txt
  build/pkgs/trove_classifiers/distros/arch.txt
  build/pkgs/trove_classifiers/distros/fedora.txt
  build/pkgs/trove_classifiers/distros/freebsd.txt
  build/pkgs/trove_classifiers/distros/gentoo.txt
  build/pkgs/trove_classifiers/distros/macports.txt
  build/pkgs/trove_classifiers/spkg-configure.m4
Labels: c: packages: standard, s: positive review, p: blocker / 1, c: build: configure

#36333 Revision of the knot theory colorings method
  src/sage/knots/link.py
Labels: t: bug, s: positive review, c: algebraic topology

#36385 Fixes for the push_to_docker_hub workflow
  .github/workflows/push_to_docker_hub.yml
  docker/Dockerfile
Labels: s: positive review, p: critical / 2, c: build

#36395 build/pkgs/singular: Update to 4.3.2p8
  build/pkgs/singular/checksums.ini
  build/pkgs/singular/package-version.txt
Labels: c: packages: standard, s: positive review

#36400 `build/pkgs/setuptools_scm`: Update to 8.0.4, add fixes for version 8
  build/pkgs/setuptools_scm/checksums.ini
  build/pkgs/setuptools_scm/dependencies
  build/pkgs/setuptools_scm/package-version.txt
  build/pkgs/setuptools_scm/spkg-install.in
  pkgs/sage-conf/setup.py
  pkgs/sage-conf_pypi/setup.py
  pkgs/sage-docbuild/setup.py
  pkgs/sage-setup/setup.py
  pkgs/sage-sws2rst/setup.py
  src/sage/misc/cython.py
  src/setup.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#36401 Allow lifting mvpolynomials over non-fields using singular
  src/sage/matrix/matrix0.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: s: positive review, c: algebraic geometry, c: algebra, s: run conda ci

#36407 Support python 3.12
  build/sage_bootstrap/package.py
  src/sage/all__sagemath_repl.py
  src/sage/arith/long.pxd
  src/sage/cpython/atexit.pyx
  src/sage/cpython/debug.pyx
  src/sage/cpython/dict_internal.h
  src/sage/cpython/pycore_long.h
  src/sage/cpython/pycore_long.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/lfunctions/dokchitser.py
  src/sage/lfunctions/pari.py
  src/sage/libs/gmp/pylong.pxd
  src/sage/libs/gmp/pylong.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/misc/dev_tools.py
  src/sage/misc/sageinspect.py
  src/sage/monoids/trace_monoid.py
  src/sage/sat/solvers/satsolver.pyx
  src/sage/symbolic/ginac/numeric.cpp
Labels: s: positive review, p: critical / 2

#36411 Fix conda install instructions after `setuptools` update
  .github/workflows/ci-conda.yml
  build/pkgs/setuptools/distros/conda.txt
  build/pkgs/setuptools_wheel/distros
  build/pkgs/setuptools_wheel/distros/repology.txt
  pkgs/sage-conf_conda/setup.py
  src/doc/en/installation/conda.rst
Labels: s: positive review, p: critical / 2, c: documentation, c: distribution, s: run conda ci

#36423 fix and activate E225 and E228
  .vscode/settings.json
  src/sage/databases/cremona.py
  src/sage/databases/db_class_polynomials.py
  src/sage/databases/knotinfo_db.py
  src/sage/databases/sql_db.py
  src/sage/doctest/control.py
  src/sage/doctest/parsing.py
  src/sage/doctest/reporting.py
  src/sage/doctest/util.py
  src/sage/functions/jacobi.py
  src/sage/functions/other.py
  src/sage/functions/piecewise.py
  src/sage/graphs/generators/basic.py
  src/sage/graphs/partial_cube.py
  src/sage/groups/abelian_gps/abelian_aut.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/abelian_group_gap.py
  src/sage/groups/abelian_gps/element_base.py
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/affine_gps/euclidean_group.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/groups/matrix_gps/isometries.py
  src/sage/groups/matrix_gps/orthogonal.py
  src/sage/groups/matrix_gps/unitary.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/interacts/library.py
  src/sage/libs/coxeter3/coxeter_group.py
  src/sage/libs/eclib/interface.py
  src/sage/manifolds/differentiable/examples/euclidean.py
  src/sage/matrix/benchmark.py
  src/sage/matrix/matrix_integer_dense_saturation.py
  src/sage/matrix/special.py
  src/sage/numerical/backends/logging_backend.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/numerical/optimize.py
  src/sage/repl/configuration.py
  src/sage/sat/boolean_polynomials.py
  src/sage/sat/solvers/dimacs.py
  src/sage/sat/solvers/sat_lp.py
  src/sage/tensor/modules/comp.py
  src/sage/tensor/modules/free_module_linear_group.py
  src/sage/tensor/modules/free_module_tensor.py
  src/sage_docbuild/conf.py
  src/sage_docbuild/ext/multidocs.py
  src/sage_setup/autogen/giacpy-mkkeywords.py
  src/sage_setup/autogen/interpreters/specs/python.py
  src/sage_setup/command/sage_build_ext.py
  src/sage_setup/run_parallel.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#36430 CI Linux: Run `ubuntu-focal-standard` without waiting for other platforms
  .github/workflows/ci-linux.yml
Labels: s: positive review, c: scripts

#36435 Retrieve upstream tarballs from GitHub release assets
  .upstream.d/10-SAGE_SERVER
  .upstream.d/20-github.com-sagemath-sage-releases
  .upstream.d/30-www.sagemath.org-mirror_list
  build/bin/write-dockerfile.sh
  build/sage_bootstrap/download/mirror_list.py
  build/sage_bootstrap/tarball.py
  src/bin/sage-update-version
Labels: s: positive review, p: blocker / 1, c: distribution

#36436 src/sage/misc/latex.py: replace tmp_dir()
  src/sage/misc/latex.py
Labels: s: positive review, t: refactoring

#36437 src/sage/parallel/map_reduce.py: replace tmp_dir()
  src/sage/parallel/map_reduce.py
Labels: s: positive review, t: refactoring

#36438 .github/workflows/dist.yml: Create release on release tag
  .github/workflows/dist.yml
Labels: s: positive review, c: scripts, c: distribution

#36440 trying ruff on some posets files
  src/sage/combinat/posets/incidence_algebras.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#36442 CI: Refactor `build*.yml` through a new script `.ci/retrofit-worktree.sh`
  .ci/retrofit-worktree.sh
  .github/workflows/build.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
Labels: p: minor / 4, s: positive review, c: scripts, t: refactoring

#36445 fix ZeroDivisionError in gcd of sparse polynomials
  src/sage/rings/polynomial/polynomial_element_generic.py
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#36451 tox.ini: Add gentoo-python3.12
  .github/workflows/docker.yml
  tox.ini
Labels: s: positive review, c: scripts

#36452 `make sagemath_categories-check`, `make pypi-wheels-check`
  .github/workflows/build.yml
  build/bin/sage-dist-helpers
  build/bin/sage-spkg
  build/make/Makefile.in
  build/pkgs/sage_sws2rst/spkg-check
  build/pkgs/sage_sws2rst/spkg-install
  build/pkgs/sagemath_categories/spkg-check
  build/pkgs/sagemath_environment/spkg-check
  build/pkgs/sagemath_objects/spkg-check
  build/pkgs/sagemath_objects/spkg-install
  build/pkgs/sagemath_repl/spkg-check
Labels: s: positive review, c: build, c: scripts

#36454 Remove `tomli` from some build dependencies
  build/pkgs/backcall/dependencies
  build/pkgs/entrypoints/dependencies
  build/pkgs/pyparsing/dependencies
  build/pkgs/tomli/spkg-install.in
Labels: p: minor / 4, c: packages: standard, s: positive review

#36460 add default legend_color to eliminate KeyError when plotting arrow2d or disk
  src/sage/combinat/root_system/plot.py
  src/sage/plot/arrow.py
  src/sage/plot/circle.py
  src/sage/plot/disk.py
  src/sage/plot/ellipse.py
  src/sage/plot/point.py
  src/sage/plot/polygon.py
Labels: p: major / 3, t: bug, s: positive review, c: graphics

#36463 remove unused variables in pyx files in groups/
  src/sage/groups/perm_gps/partn_ref/canonical_augmentation.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pyx
Labels: s: positive review, c: group theory, t: refactoring

#36467 Combine ci linter jobs
  .github/workflows/lint.yml
Labels: s: positive review, c: scripts

#36473 CI docbuild: Do not rebuild sagelib from scratch
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
Labels: s: positive review, c: scripts

#35978 Fix GradedModularFormElement multiplication
  src/sage/modular/modform/element.py
Labels: p: major / 3, t: bug, s: positive review, c: modular forms

#36416 `build/pkgs/cython`: Update to 3.0.4
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/package-version.txt
  build/pkgs/cython/patches/5690.patch
Labels: c: packages: standard, s: positive review

#36444 upgrade cypari2 to 2.1.4
  build/pkgs/cypari/checksums.ini
  build/pkgs/cypari/package-version.txt
  build/pkgs/cypari/patches/cython3-legacy.patch
Labels: c: packages: standard, s: positive review, p: critical / 2

#36466 Run incremental linux ci only when packages changed
  .github/workflows/ci-linux-incremental.yml
Labels: s: positive review, c: scripts

#36478 some details in pyx files in combinat
  src/sage/combinat/combinat_cython.pyx
  src/sage/combinat/debruijn_sequence.pyx
  src/sage/combinat/degree_sequences.pyx
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/gen_quadrangles_with_spread.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/combinat/expnums.pyx
  src/sage/combinat/fast_vector_partitions.pyx
  src/sage/combinat/matrices/dancing_links.pyx
  src/sage/combinat/partitions.pyx
  src/sage/combinat/posets/hasse_cython_flint.pyx
  src/sage/combinat/posets/linear_extension_iterator.pyx
  src/sage/combinat/root_system/braid_orbit.pyx
  src/sage/combinat/root_system/reflection_group_c.pyx
  src/sage/combinat/root_system/reflection_group_element.pyx
  src/sage/combinat/set_partition_iterator.pyx
  src/sage/combinat/subword_complex_c.pyx
  src/sage/combinat/words/word_char.pyx
  src/sage/combinat/words/word_datatypes.pyx
Labels: s: positive review, c: combinatorics, t: refactoring

#36482 Loosen version requirement on fpylll and align its conda version
  build/pkgs/fpylll/distros/conda.txt
  build/pkgs/fpylll/install-requires.txt
Labels: s: positive review, p: blocker / 1, c: distribution

#36483 Remove spurious diffs in doc build changes
  .github/workflows/doc-build.yml
  src/sage/calculus/transforms/dft.py
  src/sage/combinat/finite_state_machine.py
  src/sage/combinat/root_system/type_A.py
  src/sage/combinat/root_system/type_A_affine.py
  src/sage/combinat/root_system/type_A_infinity.py
  src/sage/combinat/root_system/type_B.py
  src/sage/combinat/root_system/type_BC_affine.py
  src/sage/combinat/root_system/type_B_affine.py
  src/sage/combinat/root_system/type_C.py
  src/sage/combinat/root_system/type_C_affine.py
  src/sage/combinat/root_system/type_D.py
  src/sage/combinat/root_system/type_D_affine.py
  src/sage/combinat/root_system/type_E.py
  src/sage/combinat/root_system/type_E_affine.py
  src/sage/combinat/root_system/type_F.py
  src/sage/combinat/root_system/type_F_affine.py
  src/sage/combinat/root_system/type_G.py
  src/sage/combinat/root_system/type_G_affine.py
  src/sage/combinat/root_system/type_dual.py
  src/sage/combinat/root_system/type_marked.py
  src/sage/combinat/root_system/type_reducible.py
  src/sage/combinat/root_system/type_relabel.py
  src/sage/combinat/root_system/type_super_A.py
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/graph_generators.py
  src/sage/misc/sageinspect.py
  src/sage/rings/polynomial/groebner_fan.py
Labels: t: enhancement, s: positive review, c: documentation

#36484 Fix typos in Italian docs
  README.md
  src/doc/it/faq/faq-contribute.rst
  src/doc/it/faq/faq-general.rst
  src/doc/it/faq/faq-usage.rst
  src/doc/it/tutorial/introduction.rst
  src/doc/it/tutorial/tour_algebra.rst
Labels: s: positive review, c: documentation

#36488 Fix func_persist: do not use the (now removed) inspect.formatargspec, but instead use inspect.signature.
  src/sage/misc/func_persist.py
Labels: c: user interface, p: minor / 4, s: positive review

#36491 Fix size of varchenko_matrix
  src/sage/geometry/hyperplane_arrangement/arrangement.py
Labels: s: positive review, c: geometry

#36493 improve method `cycle_basis` for graphs with multiple edges
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#36495 Conditional documentation
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/en/developer/sage_manuals.rst
  src/doc/en/reference/polynomial_rings/index.rst
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation

#36496 build*.yml: Fix application of CI fixes broken in #36442
  .ci/retrofit-worktree.sh
Labels: s: positive review, p: blocker / 1, c: scripts

#36497 lint.yml: Always run all 3 linters
  .github/workflows/lint.yml
Labels: s: positive review, c: scripts

#36499 Remove conda patchelf distro
  build/pkgs/patchelf/distros/conda.txt
Labels: s: positive review, c: distribution

#36506 Support launching notebook 7
  src/bin/sage-notebook
Labels: c: user interface, s: positive review, p: critical / 2

#36509 meson 1.2.3, numpy 1.26.1, require meson >= 1.2.0
  build/pkgs/meson/checksums.ini
  build/pkgs/meson/package-version.txt
  build/pkgs/meson/spkg-configure.m4
  build/pkgs/numpy/checksums.ini
  build/pkgs/numpy/package-version.txt
Labels: c: packages: standard, s: positive review, p: critical / 2

#36510 Add pyright ci annotations
  .github/workflows/build.yml
  src/doc/en/developer/tools.rst
  src/sage/functions/other.py
Labels: s: positive review, c: scripts

#36511 Exclude symlinks from vscode search config via glob pattern
  .vscode/settings.json
  src/doc/en/developer/packaging_sage_library.rst
Labels: s: positive review

#36513 `networkx`, `scipy`, `ipywidgets`: Update version ranges in `conda.txt`
  build/pkgs/ipywidgets/distros/conda.txt
  build/pkgs/networkx/distros/conda.txt
  build/pkgs/scipy/distros/conda.txt
Labels: s: positive review, c: distribution, s: run conda ci

#36514 `build/pkgs/sagenb_export`: Fix install-requires.txt
  build/pkgs/sagenb_export/install-requires.txt
Labels: s: positive review, c: distribution

#36516 `sage.schemes.toric`: Remove pyright 'is possibly unbound' warnings
  src/sage/schemes/toric/variety.py
Labels: p: minor / 4, s: positive review, t: refactoring

#36520 `pkgs/sagemath-{bliss,sirocco,tdlib}`: Fix sdists
  pkgs/sagemath-bliss/MANIFEST.in
  pkgs/sagemath-sirocco/MANIFEST.in
  pkgs/sagemath-tdlib/MANIFEST.in
Labels: s: positive review, p: critical / 2, c: distribution

#36521 GH Actions: Fix wheel build
  .github/workflows/dist.yml
Labels: s: positive review, p: critical / 2, c: distribution

#36522 Fix linter failure E401 multiple imports on one line
  src/sage/misc/persist.pyx
Labels: s: positive review, p: blocker / 1

#36535 build/pkgs/openssl: Update to 3.0.12
  build/pkgs/openssl/checksums.ini
  build/pkgs/openssl/package-version.txt
Labels: c: packages: standard, s: positive review

#36537 refresh the maple(tm) interface
  src/sage/interfaces/maple.py
Labels: s: positive review, c: interfaces: optional

#36540 `build/pkgs/pip`: Increase lower version bound; upgrade `pip`, `wheel`, `packaging`, `platformdirs`
  build/pkgs/packaging/checksums.ini
  build/pkgs/packaging/package-version.txt
  build/pkgs/pip/checksums.ini
  build/pkgs/pip/install-requires.txt
  build/pkgs/pip/package-version.txt
  build/pkgs/platformdirs/checksums.ini
  build/pkgs/platformdirs/package-version.txt
  build/pkgs/wheel/checksums.ini
  build/pkgs/wheel/package-version.txt
Labels: c: packages: standard, s: positive review, c: build: configure

#36541 `build/pkgs/nauty`: Upgrade to 2.8.6, require nauty >= 2.8
  build/pkgs/nauty/checksums.ini
  build/pkgs/nauty/package-version.txt
  build/pkgs/nauty/patches/nauty-2.8.6-gentreeg-gentourng.patch
  build/pkgs/nauty/spkg-configure.m4
  build/pkgs/nauty/spkg-install.in
Labels: c: packages: standard, s: positive review, c: graph theory

#36547 expurge parent_old from cryptosystem
  src/sage/crypto/cryptosystem.py
Labels: s: positive review, c: cryptography, t: refactoring

#36550 remove deprecated name parameter in category ; capital for Coxeter
  src/sage/categories/bimodules.py
  src/sage/categories/category.py
  src/sage/categories/category_types.py
  src/sage/categories/category_with_axiom.py
  src/sage/categories/complex_reflection_or_generalized_coxeter_groups.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/finite_complex_reflection_groups.py
  src/sage/categories/finite_coxeter_groups.py
  src/sage/categories/finite_weyl_groups.py
  src/sage/categories/weyl_groups.py
  src/sage/combinat/permutation.py
  src/sage/groups/matrix_gps/coxeter_group.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: s: positive review, c: combinatorics, c: categories, t: refactoring

#36552 `src/sage/misc/cython.py`: Fix the workaround for setuptools_scm
  src/sage/misc/cython.py
Labels: t: bug, s: positive review, p: blocker / 1

#36553 Add a hash function for the class TernaryQF.
  src/sage/quadratic_forms/ternary_qf.py
Labels: s: positive review, c: quadratic forms

#36144 Revive sage live doc using jupyter-sphinx
  build/pkgs/jupyter_sphinx/checksums.ini
  build/pkgs/jupyter_sphinx/package-version.txt
  build/pkgs/jupyter_sphinx/patches/0001-Patch-for-sage-live-doc.patch
  src/doc/common/static/custom-codemirror-monokai.css
  src/doc/common/static/custom-jupyter-sphinx.css
  src/doc/common/static/jupyter-sphinx-furo.js
  src/doc/common/static/thebe-sage.js
  src/doc/common/themes/sage-classic/layout.html
  src/doc/en/a_tour_of_sage/index.rst
  src/doc/en/installation/binary.rst
  src/doc/en/installation/index.rst
  src/doc/en/installation/linux.rst
  src/doc/en/installation/source.rst
  src/doc/en/tutorial/latex.rst
  src/doc/en/website/templates/index_furo.html
  src/sage/env.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/repl/ipython_kernel/interact.py
  src/sage/repl/rich_output/backend_ipython.py
  src/sage_docbuild/__main__.py
  src/sage_docbuild/conf.py
  src/sage_docbuild/sphinxbuild.py
Labels: p: major / 3, t: enhancement, s: positive review, c: documentation

#36246 Use URLs to online Sage documents for JupyterLab
  src/sage/repl/ipython_kernel/kernel.py
Labels: c: user interface, p: minor / 4, s: positive review

#36271 `sage.{dynamics,schemes}`: Modularization fixes, docstring cosmetics, update `# needs`
  src/sage/dynamics/arithmetic_dynamics/affine_ds.py
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/dynamics/arithmetic_dynamics/dynamical_semigroup.py
  src/sage/dynamics/arithmetic_dynamics/endPN_automorphism_group.py
  src/sage/dynamics/arithmetic_dynamics/endPN_minimal_model.py
  src/sage/dynamics/arithmetic_dynamics/generic_ds.py
  src/sage/dynamics/arithmetic_dynamics/product_projective_ds.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/dynamics/cellular_automata/elementary.py
  src/sage/dynamics/cellular_automata/glca.py
  src/sage/dynamics/complex_dynamics/mandel_julia.py
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/schemes/affine/affine_homset.py
  src/sage/schemes/affine/affine_morphism.py
  src/sage/schemes/affine/affine_point.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/affine/affine_subscheme.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/generic/homset.py
  src/sage/schemes/generic/morphism.py
  src/sage/schemes/generic/scheme.py
  src/sage/schemes/hyperelliptic_curves/hypellfrob.pyx
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/plane_conics/con_field.py
  src/sage/schemes/plane_conics/con_rational_field.py
  src/sage/schemes/plane_conics/con_rational_function_field.py
  src/sage/schemes/product_projective/morphism.py
  src/sage/schemes/product_projective/point.py
  src/sage/schemes/product_projective/rational_point.py
  src/sage/schemes/projective/projective_homset.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/schemes/projective/projective_point.py
  src/sage/schemes/projective/projective_rational_point.py
  src/sage/schemes/projective/projective_space.py
  src/sage/schemes/projective/projective_subscheme.py
  src/sage/schemes/toric/chow_group.py
  src/sage/schemes/toric/divisor.py
  src/sage/schemes/toric/fano_variety.py
  src/sage/schemes/toric/homset.py
  src/sage/schemes/toric/ideal.py
  src/sage/schemes/toric/points.py
  src/sage/schemes/toric/toric_subscheme.py
  src/sage/schemes/toric/variety.py
  src/sage/schemes/toric/weierstrass_covering.py
  src/sage/schemes/toric/weierstrass_higher.py
Labels: s: positive review, c: algebraic geometry, t: refactoring

#36292 Fix sync labels issues for step 2 going live completion
  .github/sync_labels.py
  .github/workflows/sync_labels.yml
Labels: s: positive review

#35302 update pari to 2.15.4, drop patch
  build/pkgs/pari/checksums.ini
  build/pkgs/pari/package-version.txt
  build/pkgs/pari/patches/bug2441.patch
  build/pkgs/pari/spkg-configure.m4
  src/sage/arith/misc.py
  src/sage/interfaces/gp.py
  src/sage/rings/number_field/order.py
Labels: c: packages: standard, s: positive review
