Repository sagemath/sage, pull requests merged in 2023-04, with the labels that each got.

#35220 add tests for solved issue about fraction fields
  src/sage/rings/fraction_field.py
Labels: s: positive review, c: algebra

#35233 systematically avoid checking of input
  src/sage/combinat/dyck_word.py
  src/sage/combinat/permutation.py
  src/sage/libs/gap/element.pyx
Labels: s: positive review, c: combinatorics, t: performance

#35236 Make Expression.simplify optionally use sympy
  src/sage/symbolic/expression.pyx
Labels: s: positive review, c: symbolics

#35244 fix pep E303 in all folders starting with [defghi]
  src/sage/data_structures/stream.py
  src/sage/databases/findstat.py
  src/sage/databases/knotinfo_db.py
  src/sage/doctest/reporting.py
  src/sage/features/__init__.py
  src/sage/finance/markov_multifractal.py
  src/sage/functions/exp_integral.py
  src/sage/games/hexad.py
  src/sage/games/sudoku.py
  src/sage/geometry/cone.py
  src/sage/geometry/fan_isomorphism.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/geometry/hyperplane_arrangement/plot.py
  src/sage/geometry/newton_polygon.py
  src/sage/geometry/polyhedron/backend_polymake.py
  src/sage/geometry/polyhedron/backend_ppl.py
  src/sage/geometry/polyhedron/base3.py
  src/sage/geometry/polyhedron/base_RDF.py
  src/sage/geometry/polyhedron/ppl_lattice_polytope.py
  src/sage/geometry/polyhedron/representation.py
  src/sage/geometry/riemannian_manifolds/parametrized_surface3d.py
  src/sage/geometry/toric_lattice.py
  src/sage/geometry/triangulation/element.py
  src/sage/geometry/triangulation/point_configuration.py
  src/sage/graphs/dot2tex_utils.py
  src/sage/graphs/graph.py
  src/sage/groups/abelian_gps/abelian_group_gap.py
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/class_function.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/libgap_morphism.py
  src/sage/groups/matrix_gps/linear.py
  src/sage/groups/matrix_gps/orthogonal.py
  src/sage/groups/matrix_gps/pickling_overrides.py
  src/sage/groups/matrix_gps/symplectic.py
  src/sage/groups/matrix_gps/unitary.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/interfaces/axiom.py
  src/sage/interfaces/fricas.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/matlab.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/mupad.py
  src/sage/interfaces/psage.py
  src/sage/interfaces/r.py
  src/sage/interfaces/rubik.py
  src/sage/interfaces/tides.py
Labels: s: positive review, t: refactoring

#35248 using "change_ring" in quadratic_forms
  src/sage/algebras/clifford_algebra.py
  src/sage/quadratic_forms/count_local_2.pyx
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/quadratic_form__local_field_invariants.py
  src/sage/quadratic_forms/quadratic_form__mass__Siegel_densities.py
Labels: s: positive review, c: quadratic forms

#35249 catch some more precise exceptions in combinat/
  src/sage/combinat/abstract_tree.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/permutation.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/sf/classical.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/symmetric_group_algebra.py
Labels: s: positive review, c: combinatorics

#35250 Fix doctests for nauty 2.8.6 output changes
  src/sage/graphs/generators/families.py
  src/sage/graphs/graph_generators.py
Labels: c: packages: standard, s: positive review, t: tests, c: graph theory

#35252 more standard shape for error messages in combinat
  src/sage/combinat/alternating_sign_matrix.py
  src/sage/combinat/binary_tree.py
  src/sage/combinat/cartesian_product.py
  src/sage/combinat/combinat.py
  src/sage/combinat/combinatorial_map.py
  src/sage/combinat/composition.py
  src/sage/combinat/constellation.py
  src/sage/combinat/core.py
  src/sage/combinat/derangements.py
  src/sage/combinat/e_one_star.py
  src/sage/combinat/fully_packed_loop.py
  src/sage/combinat/gelfand_tsetlin_patterns.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/ordered_tree.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/partition.py
  src/sage/combinat/ranker.py
  src/sage/combinat/recognizable_series.py
  src/sage/combinat/schubert_polynomial.py
  src/sage/combinat/set_partition.py
  src/sage/combinat/similarity_class_type.py
  src/sage/combinat/skew_partition.py
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/tableau_tuple.py
Labels: s: positive review, c: combinatorics, t: refactoring

#35253 Deprecate `is_Algebra`, `is_CommutativeAlgebra`
  src/sage/algebras/algebra.py
  src/sage/categories/algebra_ideals.py
  src/sage/categories/algebra_modules.py
  src/sage/categories/commutative_algebra_ideals.py
  src/sage/rings/commutative_algebra.py
Labels: s: positive review, c: categories, t: refactoring

#35254 Fix docstring of `src/sage/rings/lazy_series.py`
  src/sage/rings/lazy_series.py
Labels: s: positive review, c: documentation, p: trivial / 5

#35257 shorter doctests in finite monoids
  src/sage/categories/finite_monoids.py
Labels: s: positive review, c: categories

#35262 support calling PARI's qfbcornacchia() from BinaryQF
  src/sage/quadratic_forms/binary_qf.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: quadratic forms

#35263 `sage.topology`: Move imports from `sage.graphs`, `sage.homology` into methods
  src/sage/topology/cubical_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/simplicial_complex_morphism.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_constructions.py
  src/sage/topology/simplicial_set_examples.py
  src/sage/topology/simplicial_set_morphism.py
Labels: s: positive review, c: algebraic topology, t: refactoring

#35265 Improve approximate order on getitem calls
  src/sage/data_structures/stream.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
Labels: t: bug, s: positive review, c: algebra

#35270 construct AdditiveAbelianGroupWrapper from (not necessarily independent) generating set
  src/doc/en/reference/references/index.rst
  src/sage/groups/additive_abelian/additive_abelian_wrapper.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: t: enhancement, s: positive review, c: group theory

#35275 Drinfeld modules: Make some imports lazy
  src/sage/categories/drinfeld_modules.py
  src/sage/rings/function_field/all.py
  src/sage/rings/polynomial/polynomial_ring.py
Labels: s: positive review, c: algebra, t: refactoring

#35277 `sage.rings.polynomial.polynomial_ring[_constructor]`: Handle missing implementation modules
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring_constructor.py
Labels: s: positive review, c: commutative algebra, t: refactoring

#35278 Use the Docker images published on ghcr.io without 'docker' in the name (step 3)
  .github/workflows/build.yml
  .github/workflows/doc-build.yml
Labels: s: positive review, p: critical / 2

#35279 `sage.categories`: Modularization fixes for imports
  src/sage/categories/finite_complex_reflection_groups.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
  src/sage/categories/loop_crystals.py
  src/sage/categories/pushout.py
  src/sage/categories/rings.py
Labels: s: positive review, c: categories, t: refactoring

#35280 support all= keyword argument in AlgebraicClosureFiniteFieldElement.sqrt()
  src/sage/rings/algebraic_closure_finite_field.py
Labels: s: positive review, c: algebra, c: finite rings

#35284 primesieve/count update, add gentoo packages info for them
  build/pkgs/primecount/checksums.ini
  build/pkgs/primecount/distros/gentoo.txt
  build/pkgs/primecount/package-version.txt
  build/pkgs/primesieve/checksums.ini
  build/pkgs/primesieve/distros/gentoo.txt
  build/pkgs/primesieve/package-version.txt
Labels: c: packages: standard, s: positive review

#35287 add missing colon in `finite_drinfeld_module.py`
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
Labels: s: positive review, c: documentation, p: trivial / 5

#35289 pplpy*: update upstream info and deps
  build/pkgs/pplpy/SPKG.rst
  build/pkgs/pplpy/dependencies
  build/pkgs/pplpy_doc/SPKG.rst
Labels: c: packages: standard, s: positive review

#35290 update pplpy to 0.8.7 - to make gcc 12.2.1 happy
  build/pkgs/pplpy/checksums.ini
  build/pkgs/pplpy/package-version.txt
Labels: c: packages: standard, s: positive review

#35294 Avoid a square root computation in EllipticCurve_field.quadratic_twist
  src/sage/schemes/elliptic_curves/ell_field.py
Labels: t: enhancement, s: positive review, c: elliptic curves, t: performance, good first issue

#35303 `pyscipopt`: Update to 4.3.0, use tarball without generated .c files, run Cython instead
  build/pkgs/pyscipopt/checksums.ini
  build/pkgs/pyscipopt/dependencies
  build/pkgs/pyscipopt/package-version.txt
Labels: s: positive review, c: packages: optional, c: linear programming

#35304 HTML documentation: Add copy buttons to code blocks
  build/pkgs/sagemath_doc_html/dependencies
  build/pkgs/sphinx_copybutton/SPKG.rst
  build/pkgs/sphinx_copybutton/checksums.ini
  build/pkgs/sphinx_copybutton/dependencies
  build/pkgs/sphinx_copybutton/install-requires.txt
  build/pkgs/sphinx_copybutton/package-version.txt
  build/pkgs/sphinx_copybutton/type
  configure.ac
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation

#35307 Use StringIO to format polynomials
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: commutative algebra, t: performance

#35036 Implement Specht modules for diagrams
  src/doc/en/reference/combinat/module_list.rst
  src/sage/combinat/algebraic_combinatorics.py
  src/sage/combinat/composition.py
  src/sage/combinat/diagram.py
  src/sage/combinat/integer_vector.py
  src/sage/combinat/partition.py
  src/sage/combinat/permutation.py
  src/sage/combinat/skew_partition.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/symmetric_group_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics

#35037 Implement symmetry classes of plane partitions
  src/sage/combinat/plane_partition.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics

#35102 Introduce extension of scalars coercion of CombinatorialFreeModules
  src/sage/combinat/free_module.py
Labels: s: positive review, c: linear algebra, c: combinatorics, c: coercion

#35166 Improve CM testing for elliptic curves over number fields
  src/doc/en/reference/references/index.rst
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/nf_galois_groups.rst
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/special_values.py
  src/sage/rings/integer.pyx
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/heegner.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#35210 Refactor subs() of multivariate polynomials for readability and efficiency
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: c: basic arithmetic, t: enhancement, p: minor / 4, s: positive review

#35211 Add skew Hadamard matrices up to order 1000
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/matrices/hadamard_matrix.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: combinatorial designs

#35214 Some improvements for braids computations
  src/sage/groups/artin.py
  src/sage/groups/braid.py
Labels: p: major / 3, t: enhancement, s: positive review, c: group theory

#35215 Trac #34920: Fix description of inputs of primes.
  src/sage/arith/misc.py
Labels: s: positive review, c: number theory

#35218 reduce exponents of AbelianGroup elements modulo the respective orders
  src/sage/groups/abelian_gps/element_base.py
Labels: s: positive review

#35222 Reference Manual: fix definition of inverse Laplace transform
  src/sage/calculus/calculus.py
Labels: s: positive review

#35224 fixing some :class:, :meth: roles
  src/sage/combinat/integer_vector.py
  src/sage/modular/modform/element.py
Labels: s: positive review, c: documentation

#35228 large partial pep cleanup in cluster_seed
  src/sage/combinat/cluster_algebra_quiver/cluster_seed.py
Labels: s: positive review, t: refactoring

#35229 `sage.rings.polynomial.laurent_polynomial_ring_base`: Split out from `.laurent_polynomial_ring`
  src/doc/en/reference/polynomial_rings/index.rst
  src/sage/categories/pushout.py
  src/sage/rings/fraction_field.py
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/localization.py
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/symbolic/ring.pyx
Labels: s: positive review, c: commutative algebra, t: refactoring

#35240 ABC for `BooleanPolynomialRing`
  src/sage/rings/polynomial/multi_polynomial_ring_base.pxd
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/pbori/pbori.pxd
  src/sage/rings/polynomial/pbori/pbori.pyx
Labels: s: positive review, c: commutative algebra, t: refactoring

#35377 build/pkgs/openblas/spkg-configure.m4: Reject version 0.3.22
  build/pkgs/openblas/spkg-configure.m4
Labels: c: packages: standard, s: positive review, p: critical / 2, c: build: configure

#35381 Use Singular maMapPoly to avoid quadratic complexity in polynomial evaluation
  src/sage/libs/singular/decl.pxd
  src/sage/libs/singular/polynomial.pyx
Labels: s: positive review, c: commutative algebra, t: performance

#35382 Add missing backticks to correct formatting
  src/sage/matrix/matrix_modn_dense_float.pyx
Labels: s: positive review, c: documentation

#35384 `make dist`: Update git remotes
  build/bin/sage-clone-source
  src/bin/sage-env
  src/sage/cpython/__init__.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/repl/interpreter.py
Labels: s: positive review, c: distribution

#35385 src/tox.ini: Add cython-lint
  src/doc/en/developer/tools.rst
  src/tox.ini
  tox.ini
Labels: s: positive review

#35390 Typo: 'minumum' for 'minimum'
  src/sage/libs/eclib/mwrank.pyx
Labels: s: positive review, c: documentation, p: trivial / 5

#35394 Adding a save method to class Standalone/TikzPicture for compatibility with sagetex
  src/sage/doctest/external.py
  src/sage/features/latex.py
  src/sage/misc/latex_standalone.py
Labels: s: positive review

#35405 accept plain Python types in block_matrix()
  src/sage/matrix/special.py
Labels: s: positive review, c: linear algebra

#35409 fix pep8 E303 in folders starting with m
  src/sage/manifolds/chart.py
  src/sage/manifolds/differentiable/automorphismfield_group.py
  src/sage/manifolds/differentiable/chart.py
  src/sage/manifolds/differentiable/degenerate.py
  src/sage/manifolds/differentiable/degenerate_submanifold.py
  src/sage/manifolds/differentiable/diff_form.py
  src/sage/manifolds/differentiable/diff_map.py
  src/sage/manifolds/differentiable/integrated_curve.py
  src/sage/manifolds/differentiable/levi_civita_connection.py
  src/sage/manifolds/differentiable/manifold.py
  src/sage/manifolds/differentiable/manifold_homset.py
  src/sage/manifolds/differentiable/metric.py
  src/sage/manifolds/differentiable/scalarfield.py
  src/sage/manifolds/differentiable/tensorfield_paral.py
  src/sage/manifolds/differentiable/vectorfield.py
  src/sage/manifolds/differentiable/vectorfield_module.py
  src/sage/manifolds/differentiable/vectorframe.py
  src/sage/manifolds/scalarfield.py
  src/sage/manifolds/trivialization.py
  src/sage/matrix/benchmark.py
  src/sage/matrix/compute_J_ideal.py
  src/sage/media/wav.py
  src/sage/misc/gperftools.py
  src/sage/misc/sage_eval.py
  src/sage/modular/quasimodform/element.py
  src/sage/modules/fg_pid/fgp_element.py
  src/sage/modules/free_module.py
  src/sage/modules/vector_space_morphism.py
  src/sage/modules/with_basis/morphism.py
  src/sage/modules/with_basis/representation.py
  src/sage/monoids/free_abelian_monoid.py
Labels: s: positive review, t: refactoring

#35412 Activate codecov reports even if other checks are failing
  .codecov.yml
Labels: s: positive review

#35413 fixing some pep8 E303 (folders before l* and after t*)
  src/sage/categories/simplicial_sets.py
  src/sage/graphs/generic_graph.py
  src/sage/groups/braid.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/libs/eclib/interface.py
  src/sage/libs/gap/all_documented_functions.py
  src/sage/libs/gap/gap_functions.py
  src/sage/logic/logic.py
  src/sage/numerical/linear_tensor.py
  src/sage/tensor/modules/alternating_contr_tensor.py
  src/sage/tensor/modules/comp.py
  src/sage/tensor/modules/free_module_basis.py
  src/sage/tensor/modules/free_module_element.py
  src/sage/tensor/modules/free_module_homset.py
  src/sage/tensor/modules/free_module_linear_group.py
  src/sage/tensor/modules/free_module_morphism.py
  src/sage/tensor/modules/free_module_tensor.py
  src/sage/tensor/modules/tensor_with_indices.py
  src/sage/tests/benchmark.py
  src/sage/topology/simplicial_set_examples.py
Labels: s: positive review, t: refactoring

#35421 `WordMorphism`: remove keyword deprecated in #26307
  src/sage/combinat/words/morphism.py
Labels: s: positive review, c: combinatorics, t: refactoring

#35423 Fix doctests with ipython 8.12
  src/sage/repl/inputhook.py
Labels: c: packages: standard, s: positive review, t: tests

#35312 fixing most of pycodestyle E271 in pyx files
  src/sage/algebras/quatalg/quaternion_algebra_element.pyx
  src/sage/calculus/transforms/fft.pyx
  src/sage/categories/functor.pyx
  src/sage/combinat/integer_lists/invlex.pyx
  src/sage/libs/flint/fmpz_poly.pyx
  src/sage/libs/gap/element.pyx
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/libs/singular/polynomial.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matrix/matrix_rational_dense.pyx
  src/sage/modular/modsym/heilbronn.pyx
  src/sage/modular/modsym/p1list.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/backends/interactivelp_backend.pyx
  src/sage/numerical/backends/ppl_backend.pyx
  src/sage/numerical/mip.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/fraction_field_element.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
  src/sage/stats/intlist.pyx
  src/sage/stats/time_series.pyx
Labels: s: positive review, t: refactoring

#35313 Make `data_structures/bitset_base.pxd` use explicit integer division
  src/sage/data_structures/bitset_base.pxd
Labels: t: enhancement, s: positive review

#35316 Use PARI implementation of Frobenius morphism
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_pari_ffelt.py
  src/sage/rings/finite_rings/hom_finite_field.pyx
Labels: t: enhancement, s: positive review, t: performance, c: finite rings

#35317 fixing some E502 outside of schemes and combinat
  src/sage/algebras/lie_conformal_algebras/affine_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/bosonic_ghosts_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/fermionic_ghosts_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_element.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_with_structure_coefs.py
  src/sage/algebras/lie_conformal_algebras/neveu_schwarz_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/weyl_lie_conformal_algebra.py
  src/sage/categories/drinfeld_modules.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/crypto/mq/rijndael_gf.py
  src/sage/databases/sql_db.py
  src/sage/functions/wigner.py
  src/sage/groups/finitely_presented.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/rubik.py
  src/sage/interfaces/singular.py
  src/sage/libs/ntl/all.py
  src/sage/manifolds/differentiable/affine_connection.py
  src/sage/manifolds/differentiable/mixed_form.py
  src/sage/misc/map_threaded.py
  src/sage/quadratic_forms/quadratic_form__equivalence_testing.py
  src/sage/quadratic_forms/quadratic_form__reduction_theory.py
  src/sage/quadratic_forms/quadratic_form__theta.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/symbolic/assumptions.py
Labels: s: positive review, t: refactoring

#35323 Fix squarefree_decomposition failure over GF(2)
  src/sage/rings/finite_rings/finite_field_base.pyx
Labels: t: bug, s: positive review, c: commutative algebra

#35331 Add monotile to polgyon examples
  src/doc/en/reference/references/index.rst
  src/sage/plot/polygon.py
Labels: s: positive review, c: graphics

#35334 Improvements to squarefree_decomposition() for finite fields.
  src/sage/rings/finite_rings/finite_field_base.pyx
Labels: p: major / 3, s: positive review, c: commutative algebra, t: performance

#35335 Make FLINT polynomial factor() interruptible
  src/sage/libs/flint/nmod_poly_linkage.pxi
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
Labels: t: bug, s: positive review

#35336 Fix test output to pass with ipywidgets 8.0.5
  src/sage/interacts/library.py
Labels: c: packages: standard, s: positive review, t: tests

#35337 Fix warning with ipython 8.11 (was #35235)
  src/sage/repl/inputhook.py
Labels: c: packages: standard, s: positive review, t: tests

#35345 Allow completion() to return a lazy series for infinite precision
  src/sage/categories/graded_algebras_with_basis.py
  src/sage/groups/matrix_gps/finitely_generated.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/polynomial_ring.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35349 Correctly list develop packages in conda dev environment
  bootstrap-conda
Labels: s: positive review, c: build

#35350 Fix version specifiers of python packages for conda
  .github/workflows/ci-conda.yml
  build/pkgs/ipywidgets/distros/conda.txt
  build/pkgs/lrcalc_python/distros/conda.txt
  build/pkgs/networkx/distros/conda.txt
  build/pkgs/ptyprocess/distros/conda.txt
  build/pkgs/scipy/distros/conda.txt
  build/pkgs/sphinx/distros/conda.txt
Labels: s: positive review, s: run conda ci

#35351 Add minimum version of conda gap package
  build/pkgs/gap/distros/conda.txt
Labels: s: positive review

#35352 Add instructions on how to update existing conda environment
  src/doc/en/installation/conda.rst
Labels: s: positive review

#35353 Replace \mbox by \text in manifolds
  src/sage/manifolds/chart.py
  src/sage/manifolds/continuous_map.py
  src/sage/manifolds/differentiable/curve.py
  src/sage/manifolds/differentiable/diff_form_module.py
  src/sage/manifolds/differentiable/metric.py
  src/sage/manifolds/differentiable/mixed_form.py
  src/sage/manifolds/differentiable/multivector_module.py
  src/sage/manifolds/differentiable/symplectic_form.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/manifolds/differentiable/tensorfield_module.py
  src/sage/manifolds/differentiable/tensorfield_paral.py
  src/sage/manifolds/differentiable/vector_bundle.py
  src/sage/manifolds/differentiable/vectorfield_module.py
  src/sage/manifolds/manifold_homset.py
  src/sage/manifolds/point.py
  src/sage/manifolds/scalarfield.py
  src/sage/manifolds/section.py
Labels: s: positive review, c: manifolds

#35356 Fix documentation deployment
  .github/workflows/doc-publish.yml
Labels: s: positive review, p: critical / 2

#35358 Lighter construction of finite field elements from lists
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
Labels: s: positive review, t: performance, c: finite rings

#35367 Add output documentation on monte_carlo_integral
  src/sage/calculus/integration.pyx
Labels: t: enhancement, s: positive review, c: documentation, p: trivial / 5

#35225 SmallPermutationGroups
  src/sage/groups/perm_gps/all.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: t: enhancement, s: positive review, c: group theory

#35392 partial cython linting in algebras/
  src/sage/algebras/clifford_algebra_element.pxd
  src/sage/algebras/clifford_algebra_element.pyx
  src/sage/algebras/exterior_algebra_groebner.pxd
  src/sage/algebras/exterior_algebra_groebner.pyx
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_element.pyx
  src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.pxd
  src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.pyx
  src/sage/algebras/fusion_rings/fast_parallel_fusion_ring_braid_repn.pxd
  src/sage/algebras/fusion_rings/fast_parallel_fusion_ring_braid_repn.pyx
  src/sage/algebras/fusion_rings/poly_tup_engine.pxd
  src/sage/algebras/fusion_rings/poly_tup_engine.pyx
  src/sage/algebras/fusion_rings/shm_managers.pxd
  src/sage/algebras/fusion_rings/shm_managers.pyx
  src/sage/algebras/lie_algebras/lie_algebra_element.pxd
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
Labels: s: positive review, t: refactoring

#35408 some cython-linting inside categories/
  src/sage/categories/action.pyx
  src/sage/categories/category_cy_helper.pxd
  src/sage/categories/category_cy_helper.pyx
  src/sage/categories/category_singleton.pyx
  src/sage/categories/functor.pyx
  src/sage/categories/map.pxd
  src/sage/categories/map.pyx
  src/sage/categories/morphism.pyx
Labels: s: positive review, t: refactoring

#35414 conversion of complex_root_of to algebraic
  src/sage/interfaces/sympy.py
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/expression_conversions.py
Labels: s: positive review, c: symbolics

#35419 Add "flint" factorization algorithm and replace qsieve implementation
  .github/workflows/ci-cygwin-standard.yml
  COPYING.txt
  build/pkgs/flintqs/SPKG.rst
  build/pkgs/flintqs/checksums.ini
  build/pkgs/flintqs/dependencies
  build/pkgs/flintqs/distros/arch.txt
  build/pkgs/flintqs/distros/conda.txt
  build/pkgs/flintqs/distros/debian.txt
  build/pkgs/flintqs/distros/freebsd.txt
  build/pkgs/flintqs/distros/gentoo.txt
  build/pkgs/flintqs/distros/nix.txt
  build/pkgs/flintqs/distros/repology.txt
  build/pkgs/flintqs/distros/void.txt
  build/pkgs/flintqs/package-version.txt
  build/pkgs/flintqs/spkg-configure.m4
  build/pkgs/flintqs/spkg-install.in
  build/pkgs/flintqs/type
  src/doc/en/developer/portability_testing.rst
  src/doc/en/reference/interfaces/index.rst
  src/doc/en/reference/libs/index.rst
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/integer_factorization.rst
  src/sage/arith/misc.py
  src/sage/interfaces/all.py
  src/sage/interfaces/qsieve.py
  src/sage/libs/all.py
  src/sage/libs/flint/flint_wrap.h
  src/sage/libs/flint/fmpz_factor.pxd
  src/sage/libs/flint/fmpz_factor.pyx
  src/sage/libs/flint/qsieve.pxd
  src/sage/libs/flint/qsieve.pyx
  src/sage/libs/flint/types.pxd
  src/sage/misc/citation.pyx
  src/sage/rings/factorint.pyx
  src/sage/rings/integer.pyx
  src/sage/tests/book_stein_ent.py
Labels: s: positive review, c: interfaces

#35420 slight generalisation of MZV auxiliary F-algebra
  src/sage/modular/multiple_zeta_F_algebra.py
Labels: s: positive review, c: algebraic geometry

#35426 removed redundant imports from matrix_modn_dense_float.pyx
  src/sage/matrix/matrix_modn_dense_float.pyx
Labels: s: positive review, c: linear algebra

#35439 Fix doctests in oeis
  src/sage/databases/oeis.py
Labels: s: positive review, c: databases

#35441 Fix construction functor for p-adic relaxed types.
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/padic_base_leaves.py
  src/sage/rings/padics/padic_generic.py
Labels: t: bug, s: positive review, c: padics

#35449 Don't call `sylvester_matrix` with zero polynomials
  src/sage/rings/polynomial/multi_polynomial.pyx
Labels: s: positive review, t: tests

#35450 Replace remaining uses of `is_SymbolicEquation`, `is_SymbolicVariable`
  src/sage/calculus/calculus.py
  src/sage/calculus/desolvers.py
  src/sage/calculus/functional.py
  src/sage/calculus/functions.py
  src/sage/calculus/var.pyx
  src/sage/interfaces/maxima_lib.py
  src/sage/symbolic/assumptions.py
  src/sage/symbolic/callable.py
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/expression_conversions.py
  src/sage/symbolic/integration/integral.py
  src/sage/symbolic/operators.py
  src/sage/symbolic/relation.py
Labels: s: positive review, c: symbolics, t: refactoring

#35451 Add modules to modules/index.rst
  src/doc/en/reference/modules/index.rst
Labels: s: positive review, c: documentation

#35452 fix all pycodestyle E303 warnings in rings/
  src/sage/rings/asymptotic/asymptotic_expansion_generators.py
  src/sage/rings/asymptotic/asymptotic_ring.py
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/asymptotic/growth_group.py
  src/sage/rings/asymptotic/growth_group_cartesian.py
  src/sage/rings/asymptotic/term_monoid.py
  src/sage/rings/continued_fraction.py
  src/sage/rings/function_field/ideal_polymod.py
  src/sage/rings/infinity.py
  src/sage/rings/invariants/invariant_theory.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/number_field/S_unit_solver.py
  src/sage/rings/number_field/class_group.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/padics/lattice_precision.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/padics/padic_valuation.py
  src/sage/rings/polynomial/complex_roots.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/ore_function_field.py
  src/sage/rings/polynomial/padics/polynomial_padic.py
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/power_series_ring.py
  src/sage/rings/qqbar.py
  src/sage/rings/qqbar_decorators.py
  src/sage/rings/quotient_ring_element.py
  src/sage/rings/rational_field.py
  src/sage/rings/tate_algebra.py
  src/sage/rings/universal_cyclotomic_field.py
Labels: s: positive review, t: refactoring

#35453 partial cython-linting in graphs/
  src/sage/graphs/base/boost_graph.pyx
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/base/dense_graph.pyx
  src/sage/graphs/base/graph_backends.pyx
  src/sage/graphs/base/sparse_graph.pxd
  src/sage/graphs/base/sparse_graph.pyx
  src/sage/graphs/base/static_dense_graph.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/base/static_sparse_graph.pxd
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/graph_decompositions/bandwidth.pyx
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/graph_decompositions/cutwidth.pyx
  src/sage/graphs/graph_decompositions/fast_digraph.pxd
  src/sage/graphs/graph_decompositions/fast_digraph.pyx
  src/sage/graphs/graph_decompositions/graph_products.pyx
  src/sage/graphs/graph_decompositions/rankwidth.pxd
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/graphs/graph_decompositions/vertex_separation.pyx
Labels: s: positive review, c: graph theory

#35454 fix pycodestyle E502 in coding and crypto folders
  src/sage/coding/abstract_code.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/self_dual_codes.py
  src/sage/crypto/mq/sr.py
Labels: s: positive review, t: refactoring

#35455 Faster get_unsafe for NTL GF(p) polynomials
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
Labels: s: positive review, c: commutative algebra, t: performance

#35456 Faster computation of cached Frobenius powers
  src/sage/rings/finite_rings/finite_field_pari_ffelt.py
Labels: s: positive review, t: performance, c: finite rings

#35458 remove old deprecated properties in set_partition + pep8 cleanup
  src/sage/combinat/set_partition.py
Labels: s: positive review, c: combinatorics

#35459 pep8 and code details in weyl_characters.py
  src/sage/combinat/root_system/weyl_characters.py
Labels: s: positive review, c: combinatorics

#35466 refactor poset examples for better code coverage
  src/sage/combinat/posets/poset_examples.py
Labels: s: positive review, c: combinatorics

#35482 Update GitHub transition notices in the developer manual
  src/doc/en/developer/advanced_git.rst
  src/doc/en/developer/git_trac.rst
  src/doc/en/developer/index.rst
  src/doc/en/developer/manual_git.rst
  src/doc/en/developer/reviewer_checklist.rst
  src/doc/en/developer/trac.rst
  src/doc/en/developer/walk_through.rst
  src/doc/en/developer/workflows.rst
Labels: t: enhancement, s: positive review, p: critical / 2, c: documentation

#35271 add .conductor() and .order_of_conductor() methods for orders in quadratic fields
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/order.py
Labels: t: enhancement, s: positive review, c: number fields

#35318 fix E502 in schemes and combinat
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/finite_state_machine_generators.py
  src/sage/combinat/gelfand_tsetlin_patterns.py
  src/sage/combinat/integer_vector.py
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/ncsf_qsym/generic_basis_code.py
  src/sage/combinat/rigged_configurations/tensor_product_kr_tableaux.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/words/paths.py
  src/sage/combinat/words/suffix_trees.py
  src/sage/combinat/words/word_generators.py
  src/sage/schemes/affine/affine_morphism.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/berkovich/berkovich_space.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/ell_egros.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/mod5family.py
  src/sage/schemes/elliptic_curves/padics.py
  src/sage/schemes/generic/point.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
  src/sage/schemes/hyperelliptic_curves/mestre.py
  src/sage/schemes/product_projective/rational_point.py
  src/sage/schemes/projective/projective_morphism.py
Labels: s: positive review, t: refactoring

#35325 Correct NTL calls when computing modular powers of GF(2) polynomials
  src/sage/libs/ntl/ntl_GF2X_linkage.pxi
Labels: t: bug, s: positive review, c: commutative algebra

#35346 Do not require a multiplicative generator for finite field nth_root
  src/sage/rings/finite_rings/element_base.pyx
Labels: s: positive review, t: performance, c: finite rings

#35359 fix and activate pep E271 in python files
  src/sage/categories/simplicial_sets.py
  src/sage/modular/modform_hecketriangle/abstract_ring.py
  src/sage/modular/modform_hecketriangle/constructor.py
  src/sage/modular/modsym/ambient.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#35370 Faster Kohel isogenies without bivariate polynomials
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: s: positive review, c: elliptic curves, t: performance

#35379 Fix for `sage -package create --pypi --source wheel`
  build/sage_bootstrap/app.py
  build/sage_bootstrap/pypi.py
Labels: t: bug, s: positive review, c: build

#35397 cython-linting a few pyx files
  src/sage/functions/prime_pi.pyx
  src/sage/interfaces/process.pyx
  src/sage/interfaces/sagespawn.pyx
  src/sage/lfunctions/zero_sums.pyx
  src/sage/monoids/free_abelian_monoid_element.pxd
  src/sage/monoids/free_abelian_monoid_element.pyx
  src/sage/tests/cython.pyx
Labels: s: positive review, t: refactoring

#35039 add lazy_string in matrix2.pyx
  src/sage/matrix/matrix2.pyx
Labels: t: bug, s: positive review, c: linear algebra

#35462 Iterator over the minimal distance k dominating sets
  src/sage/graphs/domination.py
Labels: p: minor / 4, s: positive review, c: graph theory

#35463 Add iterator over minimum distance k dominating sets
  src/sage/graphs/domination.py
  src/sage/graphs/generic_graph.py
Labels: p: minor / 4, s: positive review, c: graph theory

#35465 Fix conda workflow
  .github/workflows/ci-conda.yml
  src/doc/en/installation/conda.rst
Labels: s: positive review, s: run conda ci

#35472 Implement the Feichtner-Yuzvinsky rings for lattices
  src/doc/en/reference/references/index.rst
  src/sage/combinat/posets/lattices.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: algebra

#35476 scipy: Patch out test requiring internet access
  build/pkgs/scipy/patches/tests_no_internet_dependency.patch
Labels: t: bug, c: packages: standard, s: positive review, p: critical / 2

#35478 Remove unused code from GAP interface
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
  src/sage/libs/gap/util.pyx
Labels: s: positive review

#35499 Fix test output for ipywidgets 8.0.5, part deux
  src/sage/interacts/test_jupyter.rst
Labels: c: packages: standard, s: positive review, t: tests

#35504 `build/pkgs/sphinx_{copybutton,basic_ng}`: Add conda info
  build/pkgs/sphinx_basic_ng/distros/conda.txt
  build/pkgs/sphinx_copybutton/distros/conda.txt
Labels: s: positive review, c: distribution

#35506 add check for pycodestyle E502 in python files
  src/sage/databases/sql_db.py
  src/sage/misc/sageinspect.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#35507 fix pycodestyle E303 in schemes
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/cyclic_covers/cycliccover_generic.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/formal_group.py
  src/sage/schemes/elliptic_curves/gal_reps.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/hom_scalar.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/schemes/elliptic_curves/padics.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/schemes/generic/divisor.py
  src/sage/schemes/generic/scheme.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
  src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/projective/projective_rational_point.py
Labels: s: positive review, t: refactoring

#35509 some cython-linting in matrix/ folder
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_complex_ball_dense.pyx
  src/sage/matrix/matrix_rational_dense.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
Labels: s: positive review, t: refactoring

#35510 Make BooleanPolynomial.variables() way faster
  src/sage/rings/polynomial/pbori/pbori.pxd
  src/sage/rings/polynomial/pbori/pbori.pyx
Labels: s: positive review, c: algebra

#35511 Fix Graph.add_clique() for one vertex
  src/sage/graphs/generic_graph.py
Labels: t: bug, s: positive review, c: graph theory

#35513 Silence initialization of giac
  src/sage/calculus/functional.py
  src/sage/calculus/tests.py
  src/sage/libs/giac/giac.pyx
  src/sage/symbolic/integration/integral.py
  src/sage/symbolic/relation.py
Labels: s: positive review, c: interfaces

#35514 Don't force ecl lisp with `maxima -l ecl` on command line.
  src/bin/sage
Labels: s: positive review, c: interfaces

#35515 Bug in integer valued polys
  src/sage/rings/polynomial/integer_valued_polynomials.py
Labels: s: positive review, c: commutative algebra

#35518 Improve PolynomialSequence.connected_components()
  src/sage/rings/polynomial/multi_polynomial_sequence.py
Labels: t: enhancement, s: positive review, c: algebra

#35521 `sage.combinat.sf`: re-enable a doctest
  src/sage/combinat/sf/sfa.py
Labels: s: positive review, c: combinatorics, t: tests

#35525 cython-lint and some doc cleanup for expression.pyx
  src/sage/symbolic/expression.pyx
Labels: s: positive review, c: symbolics, t: refactoring

#35526 fix pycodestyle E271 and E502 in pyx files
  src/sage/numerical/backends/cvxpy_backend.pyx
  src/sage/rings/function_field/element_rational.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/power_series_mpoly.pyx
  src/sage/rings/power_series_poly.pyx
Labels: s: positive review, t: refactoring

#35530 some minor details in interfaces
  src/sage/interfaces/axiom.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/fricas.py
  src/sage/interfaces/magma.py
Labels: s: positive review, c: interfaces, t: refactoring

#35533 Fix bug in graph.maximum_average_degree
  src/sage/graphs/graph.py
Labels: t: bug, s: positive review, c: graph theory

#35534 some cython-lint fixes in matroids/
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/extension.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pxd
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/set_system.pyx
Labels: s: positive review, c: matroid theory, t: refactoring

#35542 some fixes for cython-lint in various places
  src/sage/geometry/toric_lattice_element.pyx
  src/sage/geometry/triangulation/base.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/modules/vector_integer_dense.pyx
  src/sage/modules/vector_mod2_dense.pyx
  src/sage/modules/vector_modn_dense.pyx
  src/sage/modules/vector_numpy_integer_dense.pyx
  src/sage/numerical/backends/cvxpy_backend.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/backends/scip_backend.pyx
  src/sage/numerical/gauss_legendre.pyx
  src/sage/numerical/mip.pxd
  src/sage/numerical/mip.pyx
  src/sage/numerical/sdp.pxd
  src/sage/numerical/sdp.pyx
  src/sage/probability/probability_distribution.pyx
  src/sage/quivers/algebra_elements.pyx
  src/sage/quivers/paths.pyx
  src/sage/schemes/toric/divisor_class.pyx
  src/sage/sets/disjoint_set.pxd
Labels: s: positive review, t: refactoring

#35305 `sage.quadratic_forms`: Modularization fixes for imports
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/groups/misc_gps/argument_groups.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modules/fg_pid/fgp_module.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/modules/torsion_quadratic_module.py
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/constructions.py
  src/sage/quadratic_forms/count_local_2.pyx
  src/sage/quadratic_forms/extras.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/genera/normal_form.py
  src/sage/quadratic_forms/genera/spinor_genus.py
  src/sage/quadratic_forms/qfsolve.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/quadratic_form__automorphisms.py
  src/sage/quadratic_forms/quadratic_form__count_local_2.py
  src/sage/quadratic_forms/quadratic_form__equivalence_testing.py
  src/sage/quadratic_forms/quadratic_form__evaluate.pyx
  src/sage/quadratic_forms/quadratic_form__genus.py
  src/sage/quadratic_forms/quadratic_form__local_density_congruence.py
  src/sage/quadratic_forms/quadratic_form__local_density_interfaces.py
  src/sage/quadratic_forms/quadratic_form__local_field_invariants.py
  src/sage/quadratic_forms/quadratic_form__local_normal_form.py
  src/sage/quadratic_forms/quadratic_form__local_representation_conditions.py
  src/sage/quadratic_forms/quadratic_form__mass.py
  src/sage/quadratic_forms/quadratic_form__mass__Conway_Sloane_masses.py
  src/sage/quadratic_forms/quadratic_form__mass__Siegel_densities.py
  src/sage/quadratic_forms/quadratic_form__neighbors.py
  src/sage/quadratic_forms/quadratic_form__reduction_theory.py
  src/sage/quadratic_forms/quadratic_form__siegel_product.py
  src/sage/quadratic_forms/quadratic_form__split_local_covering.py
  src/sage/quadratic_forms/quadratic_form__ternary_Tornaria.py
  src/sage/quadratic_forms/quadratic_form__theta.py
  src/sage/quadratic_forms/quadratic_form__variable_substitutions.py
  src/sage/quadratic_forms/random_quadraticform.py
  src/sage/quadratic_forms/special_values.py
  src/sage/quadratic_forms/ternary.pyx
  src/sage/quadratic_forms/ternary_qf.py
  src/sage/rings/cfinite_sequence.py
  src/sage/rings/invariants/reconstruction.py
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/polynomial/polynomial_gf2x.pyx
  src/sage/schemes/plane_conics/constructor.py
Labels: s: positive review, c: quadratic forms, t: refactoring

#35306 `sage.groups.matrix_gps`: Modularization fixes for imports
  src/doc/en/reference/groups/index.rst
  src/sage/categories/primer.py
  src/sage/combinat/root_system/weyl_group.py
  src/sage/groups/affine_gps/affine_group.py
  src/sage/groups/affine_gps/euclidean_group.py
  src/sage/groups/affine_gps/group_element.py
  src/sage/groups/group.pyx
  src/sage/groups/matrix_gps/binary_dihedral.py
  src/sage/groups/matrix_gps/coxeter_group.py
  src/sage/groups/matrix_gps/finitely_generated.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/groups/matrix_gps/group_element.pxd
  src/sage/groups/matrix_gps/group_element.pyx
  src/sage/groups/matrix_gps/group_element_gap.pxd
  src/sage/groups/matrix_gps/group_element_gap.pyx
  src/sage/groups/matrix_gps/heisenberg.py
  src/sage/groups/matrix_gps/isometries.py
  src/sage/groups/matrix_gps/linear.py
  src/sage/groups/matrix_gps/linear_gap.py
  src/sage/groups/matrix_gps/matrix_group.py
  src/sage/groups/matrix_gps/matrix_group_gap.py
  src/sage/groups/matrix_gps/named_group.py
  src/sage/groups/matrix_gps/named_group_gap.py
  src/sage/groups/matrix_gps/orthogonal.py
  src/sage/groups/matrix_gps/orthogonal_gap.py
  src/sage/groups/matrix_gps/pickling_overrides.py
  src/sage/groups/matrix_gps/symplectic.py
  src/sage/groups/matrix_gps/symplectic_gap.py
  src/sage/groups/matrix_gps/unitary.py
  src/sage/groups/matrix_gps/unitary_gap.py
  src/sage/matrix/matrix_space.py
  src/sage/modular/arithgroup/congroup_generic.py
Labels: s: positive review, c: group theory, t: refactoring

#35375 Fix minimal kernel basis corner cases
  src/sage/matrix/matrix_polynomial_dense.pyx
Labels: t: bug, s: positive review, c: linear algebra

#35389 `sage.rings.finite_rings.residue_field`: Modularization fixes
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/finite_rings/residue_field_givaro.pyx
  src/sage/rings/finite_rings/residue_field_ntl_gf2e.pyx
  src/sage/rings/finite_rings/residue_field_pari_ffelt.pyx
Labels: s: positive review, c: finite rings, t: refactoring

#35431 Documentation improvements for rounding methods
  src/sage/rings/real_arb.pyx
  src/sage/rings/real_double.pyx
  src/sage/rings/real_mpfr.pyx
Labels: t: enhancement, s: positive review, c: documentation

#35443 Fix slow doctests or mark # long time
  src/sage/calculus/tests.py
  src/sage/categories/pushout.py
  src/sage/combinat/crystals/affine_factorization.py
  src/sage/combinat/crystals/highest_weight_crystals.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/k_regular_sequence.py
  src/sage/combinat/rsk.py
  src/sage/combinat/words/paths.py
  src/sage/crypto/lwe.py
  src/sage/crypto/sbox.pyx
  src/sage/doctest/control.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/dynamics/complex_dynamics/mandel_julia.py
  src/sage/geometry/polyhedron/base6.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/groups/libgap_mixin.py
  src/sage/interacts/library.py
  src/sage/manifolds/differentiable/affine_connection.py
  src/sage/manifolds/differentiable/multivectorfield.py
  src/sage/manifolds/differentiable/symplectic_form.py
  src/sage/modular/local_comp/type_space.py
  src/sage/modular/modform/ambient_R.py
  src/sage/modular/modform/cuspidal_submodule.py
  src/sage/modular/modform/element.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/parallel/decorate.py
  src/sage/plot/animate.py
  src/sage/plot/plot3d/implicit_plot3d.py
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/padics/padic_extension_leaves.py
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/polynomial/ore_function_element.py
  src/sage/rings/tate_algebra_element.pyx
  src/sage/rings/tests.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/gp_simon.py
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
  src/sage/structure/coerce_dict.pyx
  src/sage/tests/cmdline.py
  src/sage/tests/gosper-sum.py
Labels: s: positive review, t: tests

#35446 add method is_simple to permutations
  src/sage/combinat/permutation.py
Labels: s: positive review, c: combinatorics

#35415 `givaro`, `zeromq`: Add patches for GCC 13 support
  build/pkgs/gcc/spkg-configure.m4
  build/pkgs/gfortran/spkg-configure.m4
  build/pkgs/givaro/patches/218.patch
  build/pkgs/zeromq/patches/438d5d88392baffa6c2c5e0737d9de19d6686f0d.patch
Labels: c: packages: standard, s: positive review, p: critical / 2, c: porting, c: build: configure
