Repository sagemath/sage, pull requests merged in 2023-08, with the labels that each got.

#35999 Run pytest for src tree if no filename is given
  src/bin/sage-runtests
Labels: s: positive review, p: critical / 2

#36002 partial cython-lint cleanup in mod_sym_num
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
Labels: s: positive review, c: elliptic curves, t: refactoring

#36003 pkgs/sagemath-meataxe/README.rst: Remove markup unknown to PyPI
  pkgs/sagemath-meataxe/README.rst
Labels: s: positive review, p: critical / 2, c: distribution

#36007 minor cleanup in binary quadratic forms over ZZ
  src/sage/quadratic_forms/binary_qf.py
Labels: s: positive review, c: quadratic forms, t: refactoring

#36011 Regular sequence: closing experimental phase of regular sequence module
  src/doc/en/reference/combinat/module_list.rst
  src/sage/combinat/all.py
  src/sage/combinat/recognizable_series.py
  src/sage/combinat/regular_sequence.py
Labels: p: major / 3, s: positive review, c: combinatorics

#36015 pkgs/sagemath*: Exclude all__*.py files of other distributions
  pkgs/sagemath-bliss/MANIFEST.in
  pkgs/sagemath-categories/MANIFEST.in.m4
  pkgs/sagemath-coxeter3/MANIFEST.in
  pkgs/sagemath-environment/MANIFEST.in
  pkgs/sagemath-mcqd/MANIFEST.in
  pkgs/sagemath-meataxe/MANIFEST.in
  pkgs/sagemath-objects/MANIFEST.in
  pkgs/sagemath-repl/MANIFEST.in
  pkgs/sagemath-sirocco/MANIFEST.in
  pkgs/sagemath-tdlib/MANIFEST.in
  src/MANIFEST.in
  src/sage/graphs/graph_decompositions/sage_tdlib.cpp
Labels: s: positive review, p: critical / 2, c: distribution

#36016 CI Build & Test: Fix test errors involving optional packages coxeter3, ...
  .github/workflows/build.yml
Labels: s: positive review, p: critical / 2

#36024 `sage -fixdoctests`: Handle directory names, call `sage -t` only once
  src/bin/sage-fixdoctests
  src/sage/doctest/control.py
Labels: t: enhancement, s: positive review, c: scripts, t: performance

#35717 `sage.calculus`: Modularization fixes, doctest cosmetics, `# needs`
  src/sage/calculus/calculus.py
  src/sage/calculus/desolvers.py
  src/sage/calculus/functional.py
  src/sage/calculus/functions.py
  src/sage/calculus/integration.pyx
  src/sage/calculus/interpolation.pyx
  src/sage/calculus/interpolators.pyx
  src/sage/calculus/ode.pyx
  src/sage/calculus/riemann.pyx
  src/sage/calculus/test_sympy.py
  src/sage/calculus/transforms/all.py
  src/sage/calculus/transforms/dft.py
  src/sage/calculus/transforms/dwt.pyx
  src/sage/calculus/transforms/fft.pyx
  src/sage/calculus/wester.py
  src/sage/structure/nonexact.py
Labels: s: positive review, c: calculus, t: refactoring

#35862 gap: revise make_gap_list, make_gap_matrix
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
Labels: c: packages: standard, s: positive review

#35882 avoid messing with the recursion limit
  src/sage/functions/transcendental.py
  src/sage/interfaces/sympy.py
  src/sage/misc/misc.py
  src/sage/repl/ipython_extension.py
  src/sage/rings/qqbar.py
Labels: s: positive review, t: refactoring

#35894 Regular sequences: implement convolution / ring structure
  src/sage/combinat/k_regular_sequence.py
  src/sage/combinat/recognizable_series.py
Labels: p: major / 3, s: positive review, c: combinatorics

#35958 note about docker in README.md
  README.md
Labels: s: positive review, c: documentation, c: docker

#35959 some details in dirichlet.py
  src/sage/modular/dirichlet.py
  src/sage/sandpiles/sandpile.py
Labels: s: positive review, c: number theory

#35979 refresh descent_two_isogeny.pyx
  src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
Labels: s: positive review, c: elliptic curves, t: refactoring

#35980 Adapt to new Singular sat API
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review

#35984 fix evaluation of isogenies on points of infinite order
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: t: bug, s: positive review, c: elliptic curves

#36001 regular sequences: use "positive" partial sums algorithm
  src/sage/combinat/k_regular_sequence.py
Labels: p: major / 3, s: positive review, c: linear algebra, c: combinatorics

#36017 fix accidental damage to classical_geometries.py from 94bca97cfe9
  src/sage/graphs/generators/classical_geometries.py
Labels: t: bug, s: positive review, c: graph theory

#35981 some improvements in sage/graphs/orientations.py
  src/sage/graphs/orientations.py
Labels: s: positive review, c: graph theory

#35982 some care in sage/graphs/domination.py
  src/sage/graphs/domination.py
Labels: s: positive review, c: graph theory

#36025 Use `# optional - gap_package_grape` etc. instead of `# optional - gap_packages`
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/databases.py
  src/sage/coding/guava.py
  src/sage/coding/linear_code.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/combinat/designs/block_design.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/design_catalog.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/designs/twographs.py
  src/sage/combinat/posets/posets.py
  src/sage/features/gap.py
  src/sage/graphs/generators/classical_geometries.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/groups/abelian_gps/abelian_aut.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/abelian_group_gap.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: t: enhancement, s: positive review, c: doctest framework, c: packages: optional

#36032 Fix pycodestyle warning E721
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/categories/pushout.py
  src/sage/combinat/growth.py
  src/sage/combinat/recognizable_series.py
  src/sage/combinat/words/paths.py
  src/sage/doctest/sources.py
  src/sage/dynamics/complex_dynamics/mandel_julia.py
  src/sage/geometry/cone.py
  src/sage/geometry/relative_interior.py
  src/sage/geometry/toric_lattice.py
  src/sage/homology/chain_complex.py
  src/sage/knots/knotinfo.py
  src/sage/manifolds/differentiable/symplectic_form_test.py
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/multi_filtered_vector_space.py
  src/sage/rings/algebraic_closure_finite_field.py
  src/sage/rings/asymptotic/asymptotic_ring.py
  src/sage/rings/asymptotic/growth_group.py
  src/sage/rings/asymptotic/growth_group_cartesian.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/fraction_field.py
  src/sage/rings/function_field/maps.py
  src/sage/rings/function_field/valuation.py
  src/sage/rings/invariants/invariant_theory.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/valuation/valuation.py
  src/sage/schemes/elliptic_curves/ell_tate_curve.py
  src/sage/schemes/elliptic_curves/ell_torsion.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/symbolic/subring.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: python3

#36035 cython-lint : further fixes in quadratic forms
  src/sage/quadratic_forms/count_local_2.pyx
  src/sage/quadratic_forms/quadratic_form__evaluate.pyx
Labels: s: positive review, c: quadratic forms, t: refactoring

#36036 Fix E721 warnings for .pyx files
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/libs/coxeter3/coxeter.pyx
  src/sage/matrix/action.pyx
  src/sage/matroids/extension.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/numerical/backends/generic_backend.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/number_field/totallyreal.pyx
  src/sage/structure/category_object.pyx
Labels: p: minor / 4, s: positive review, c: python3

#36037 `sage.typeset`: Update `# needs`
  src/sage/typeset/ascii_art.py
  src/sage/typeset/character_art.py
  src/sage/typeset/character_art_factory.py
  src/sage/typeset/unicode_art.py
Labels: s: positive review, t: refactoring

#36038 `sage.plot`: Add/update `# needs`
  src/sage/ext/fast_callable.pyx
  src/sage/misc/replace_dot_all.py
  src/sage/plot/animate.py
  src/sage/plot/arc.py
  src/sage/plot/arrow.py
  src/sage/plot/bezier_path.py
  src/sage/plot/circle.py
  src/sage/plot/colors.py
  src/sage/plot/complex_plot.pyx
  src/sage/plot/contour_plot.py
  src/sage/plot/density_plot.py
  src/sage/plot/disk.py
  src/sage/plot/ellipse.py
  src/sage/plot/graphics.py
  src/sage/plot/hyperbolic_arc.py
  src/sage/plot/hyperbolic_polygon.py
  src/sage/plot/hyperbolic_regular_polygon.py
  src/sage/plot/line.py
  src/sage/plot/matrix_plot.py
  src/sage/plot/misc.py
  src/sage/plot/multigraphics.py
  src/sage/plot/plot.py
  src/sage/plot/plot3d/base.pyx
  src/sage/plot/plot3d/implicit_plot3d.py
  src/sage/plot/plot3d/implicit_surface.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/plot/plot3d/list_plot3d.py
  src/sage/plot/plot3d/parametric_plot3d.py
  src/sage/plot/plot3d/parametric_surface.pyx
  src/sage/plot/plot3d/platonic.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/plot/plot3d/plot_field3d.py
  src/sage/plot/plot3d/revolution_plot3d.py
  src/sage/plot/plot3d/shapes.pyx
  src/sage/plot/plot3d/shapes2.py
  src/sage/plot/plot3d/tachyon.py
  src/sage/plot/plot_field.py
  src/sage/plot/point.py
  src/sage/plot/polygon.py
  src/sage/plot/step.py
  src/sage/plot/streamline_plot.py
  src/sage/plot/text.py
Labels: s: positive review, c: graphics, t: refactoring

#36039 cylint: some details in arith, algebras and crypto folders
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/arith/constants.pxd
  src/sage/arith/multi_modular.pyx
  src/sage/arith/numerical_approx.pyx
  src/sage/arith/power.pyx
  src/sage/arith/rational_reconstruction.pyx
  src/sage/crypto/boolean_function.pxd
  src/sage/crypto/boolean_function.pyx
  src/sage/crypto/sbox.pyx
Labels: s: positive review, t: refactoring

#36040 Fix failing doctest in sage/graphs/bliss.pyx
  src/sage/graphs/bliss.pyx
Labels: t: bug, s: positive review, p: critical / 2, c: graph theory

#36044 `sage.rings.number_field`: Modularization fixes, doctest cosmetics, `# needs`
  src/sage/rings/number_field/S_unit_solver.py
  src/sage/rings/number_field/galois_group.py
  src/sage/rings/number_field/homset.py
  src/sage/rings/number_field/maps.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_base.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_base.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/number_field_ideal_rel.py
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/number_field/order.py
  src/sage/rings/number_field/splitting_field.py
  src/sage/rings/number_field/structure.py
  src/sage/rings/number_field/totallyreal_phc.py
  src/sage/rings/number_field/totallyreal_rel.py
Labels: s: positive review, c: number fields, t: refactoring

#36045 `sage.rings.polynomial`: Modularization fixes, `# needs`
  src/sage/rings/polynomial/cyclotomic.pyx
  src/sage/rings/polynomial/flatten.py
  src/sage/rings/polynomial/groebner_fan.py
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/ideal.py
  src/sage/rings/polynomial/infinite_polynomial_element.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_ideal.py
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/omega.py
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/ore_polynomial_ring.py
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polydict.pyx
  src/sage/rings/polynomial/polynomial_complex_arb.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_number_field.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_quotient_ring_element.py
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_real_mpfr_dense.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring_constructor.py
  src/sage/rings/polynomial/polynomial_ring_homomorphism.pyx
  src/sage/rings/polynomial/polynomial_singular_interface.py
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
  src/sage/rings/polynomial/real_roots.pyx
  src/sage/rings/polynomial/refine_root.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
  src/sage/rings/polynomial/skew_polynomial_ring.py
  src/sage/rings/polynomial/symmetric_ideal.py
  src/sage/rings/polynomial/symmetric_reduction.pyx
  src/sage/rings/polynomial/term_order.py
  src/sage/rings/polynomial/toy_buchberger.py
  src/sage/rings/polynomial/toy_d_basis.py
  src/sage/rings/polynomial/toy_variety.py
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review, c: algebra, t: refactoring

#36051 `sage.{topology,homology}`: Update # needs, modularization fixes
  src/sage/homology/algebraic_topological_model.py
  src/sage/homology/chain_complex.py
  src/sage/homology/chain_complex_homspace.py
  src/sage/homology/chain_complex_morphism.py
  src/sage/homology/chain_homotopy.py
  src/sage/homology/chains.py
  src/sage/homology/free_resolution.py
  src/sage/homology/graded_resolution.py
  src/sage/homology/hochschild_complex.py
  src/sage/homology/homology_group.py
  src/sage/homology/homology_morphism.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/homology/tests.py
  src/sage/topology/all.py
  src/sage/topology/cell_complex.py
  src/sage/topology/cubical_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/filtered_simplicial_complex.py
  src/sage/topology/simplicial_complex.py
  src/sage/topology/simplicial_complex_catalog.py
  src/sage/topology/simplicial_complex_examples.py
  src/sage/topology/simplicial_complex_homset.py
  src/sage/topology/simplicial_complex_morphism.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_catalog.py
  src/sage/topology/simplicial_set_constructions.py
  src/sage/topology/simplicial_set_examples.py
  src/sage/topology/simplicial_set_morphism.py
Labels: s: positive review, c: algebraic topology, t: refactoring

#36052 `sage.rings.{padics,valuation}`: Modularization fixes, `# needs`
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/local_generic_element.pyx
  src/sage/rings/padics/misc.py
  src/sage/rings/padics/padic_base_generic.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/padics/padic_lattice_element.py
  src/sage/rings/valuation/valuation.py
  src/sage/rings/valuation/valuations_catalog.py
Labels: s: positive review, c: padics, t: refactoring

#36056 `sage.rings.finite_rings`: Modularization fixes, `# needs`
  src/sage/rings/finite_rings/conway_polynomials.py
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/finite_field_constructor.py
  src/sage/rings/finite_rings/finite_field_pari_ffelt.py
  src/sage/rings/finite_rings/finite_field_prime_modn.py
  src/sage/rings/finite_rings/hom_finite_field.pyx
  src/sage/rings/finite_rings/hom_prime_finite_field.pyx
  src/sage/rings/finite_rings/homset.py
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/finite_rings/maps_finite_field.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/finite_rings/residue_field_givaro.pyx
  src/sage/rings/finite_rings/residue_field_ntl_gf2e.pyx
  src/sage/rings/finite_rings/residue_field_pari_ffelt.pyx
Labels: s: positive review, c: finite rings, t: refactoring

#36062 Fix typo in docstring
  src/sage/modular/arithgroup/congroup_gammaH.py
Labels: s: positive review, c: documentation, c: modular forms

#36066 Fix link to tutorial in PDF docs. This fixes #35736.
  src/doc/en/website/root_index.html
Labels: s: positive review, c: documentation, p: trivial / 5

#36068 Speed-up matrix construction by ensuring MatrixArgs type MA_ENTRIES_ZERO
  src/sage/matrix/args.pyx
  src/sage/rings/padics/relaxed_template.pxi
Labels: s: positive review, c: linear algebra, t: performance

#36072 small cleanup of triangulation/base.pyx
  src/sage/geometry/triangulation/base.pyx
Labels: s: positive review, c: geometry, t: refactoring

#36073 Stop sorting Graph vertices and edges by default
  src/sage/geometry/polyhedron/base4.py
  src/sage/graphs/digraph.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/views.pyx
  src/sage/manifolds/subset.py
Labels: s: positive review, p: critical / 2, c: graph theory

#36074 Remove deprecation warnings renaming parameter verbosity to verbose in graphs
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/vertex_separation.pyx
Labels: s: positive review, c: graph theory

#36075 Remove rename warning in spanning_tree.pyx
  src/sage/graphs/spanning_tree.pyx
Labels: s: positive review, c: graph theory

#36076 Remove deprecated parameter circular from method `is_planar`
  src/sage/graphs/planarity.pyx
Labels: s: positive review, c: graph theory

#35884 `sage.{modular,schemes}`: Modularization fixes for imports; update `sage -fiximports`, add relint pattern
  src/.relint.yml
  src/sage/lfunctions/lcalc.py
  src/sage/lfunctions/sympow.py
  src/sage/misc/replace_dot_all.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/abvar/homspace.py
  src/sage/modular/arithgroup/all.py
  src/sage/modular/arithgroup/arithgroup_generic.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/btquotients/pautomorphicform.py
  src/sage/modular/cusps.py
  src/sage/modular/dirichlet.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/submodule.py
  src/sage/modular/local_comp/local_comp.py
  src/sage/modular/local_comp/smoothchar.py
  src/sage/modular/modform/all.py
  src/sage/modular/modform/ambient_eps.py
  src/sage/modular/modform/ambient_g0.py
  src/sage/modular/modform/ambient_g1.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/modform/cuspidal_submodule.py
  src/sage/modular/modform/eis_series.py
  src/sage/modular/modform/eisenstein_submodule.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform/hecke_operator_on_qexp.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/graded_ring_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/modular/modsym/all.py
  src/sage/modular/modsym/boundary.py
  src/sage/modular/modsym/heilbronn.pyx
  src/sage/modular/modsym/modsym.py
  src/sage/modular/modsym/space.py
  src/sage/modular/multiple_zeta.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/overconvergent/weightspace.py
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/modular/pollack_stevens/modsym.py
  src/sage/modular/pollack_stevens/padic_lseries.py
  src/sage/modular/quatalg/brandt.py
  src/sage/modular/ssmod/ssmod.py
  src/sage/modules/vector_space_homspace.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/ell_tate_curve.py
  src/sage/schemes/elliptic_curves/formal_group.py
  src/sage/schemes/elliptic_curves/gal_reps.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/schemes/elliptic_curves/padics.py
  src/sage/schemes/toric/library.py
Labels: s: positive review, c: modular forms, c: algebraic geometry, t: refactoring

#35903 Add parameter key to methods multiple_edges and edge_boundary
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#35935 add multiple= option to EllipticCurvePoint_field.set_order()
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#35969 Improve method reverse for digraphs
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/graphs/digraph.py
Labels: s: positive review, c: graph theory

#36103 upgrade msolve to 0.5.0, update interface
  build/pkgs/msolve/checksums.ini
  build/pkgs/msolve/package-version.txt
  src/sage/rings/polynomial/msolve.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review, c: commutative algebra

#36107 using mute variables in combinat
  src/sage/combinat/affine_permutation.py
  src/sage/combinat/bijectionist.py
  src/sage/combinat/binary_recurrence_sequences.py
  src/sage/combinat/e_one_star.py
  src/sage/combinat/finite_state_machine.py
  src/sage/combinat/free_module.py
  src/sage/combinat/fully_commutative_elements.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/knutson_tao_puzzles.py
  src/sage/combinat/partition_kleshchev.py
  src/sage/combinat/rsk.py
  src/sage/combinat/six_vertex_model.py
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/sloane_functions.py
  src/sage/combinat/symmetric_group_representations.py
  src/sage/combinat/tableau_tuple.py
  src/sage/combinat/tiling.py
  src/sage/combinat/yang_baxter_graph.py
Labels: s: positive review, c: combinatorics

#36108 some details in quadratic forms
  src/sage/combinat/sf/classical.py
  src/sage/crypto/lattice.py
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/genera/normal_form.py
  src/sage/quadratic_forms/quadratic_form__local_field_invariants.py
  src/sage/quadratic_forms/quadratic_form__ternary_Tornaria.py
Labels: s: positive review, c: quadratic forms

#36114 using `# needs` in posets folder
  src/sage/combinat/posets/elements.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review, t: refactoring

#36124 fix cardinality, #36119, #36118, #36116
  src/sage/combinat/plane_partition.py
Labels: s: positive review, c: combinatorics

#35810 Drop support for GCC < 8.4, drop testing of `debian-buster` and `fedora-29`
  .github/workflows/docker.yml
  README.md
  build/pkgs/gcc/SPKG.rst
  build/pkgs/gcc/spkg-configure.m4
  tox.ini
Labels: s: positive review, p: critical / 2, c: build: configure

#35947 Initial implementation of dynamical semigroups
  src/doc/en/reference/dynamics/index.rst
  src/sage/dynamics/arithmetic_dynamics/all.py
  src/sage/dynamics/arithmetic_dynamics/dynamical_semigroup.py
Labels: p: major / 3, s: positive review, c: dynamics

#35990 Working MCDS implementation using connectivity constraints
  src/sage/graphs/domination.py
Labels: s: positive review, c: graph theory

#35991 Implement Goss polynomials of Drinfeld modules
  src/doc/en/reference/references/index.rst
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
Labels: t: enhancement, s: positive review, c: algebra

#36000 New functions `is_chebyshev` and `is_Lattes` for one dimensional projective dynamical systems
  src/doc/en/reference/references/index.rst
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
Labels: t: enhancement, s: positive review, c: dynamics

#36018 Fix tests with singular 4.3.2p4
  src/sage/interfaces/singular.py
  src/sage/libs/singular/function.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review, p: critical / 2, c: commutative algebra

#36030 Implement algebra_containment from Singular (issue #34502)
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#36046 Fix sqrt(sqrt(2)) memory leak in ginac numeric.cpp
  src/sage/ext_data/valgrind/valgrind-python.supp
  src/sage/symbolic/ginac/numeric.cpp
  src/sage/tests/memcheck/__init__.py
  src/sage/tests/memcheck/run_tests.py
  src/sage/tests/memcheck/run_tests_in_valgrind.py
  src/sage/tests/memcheck/symbolic_expression.py
  src/sage/tests/memcheck/verify_no_leak.py
Labels: t: bug, s: positive review

#36047 New GitHub workflow to continue our images on Docker Hub
  .github/workflows/push_to_docker_hub.yml
  docker/Dockerfile
Labels: s: positive review, p: critical / 2, c: docker

#36050 normaliz: Update to 3.10.1
  build/pkgs/normaliz/checksums.ini
  build/pkgs/normaliz/package-version.txt
  build/pkgs/normaliz/patches/411.patch
Labels: s: positive review, c: packages: optional, c: geometry

#36053 cython-lint : add note about unused imports
  src/sage/libs/mpmath/ext_libmp.pyx
Labels: s: positive review, t: refactoring

#36057 `sage.arith`: Update `# needs`
  src/sage/arith/functions.pyx
  src/sage/arith/long.pxd
  src/sage/arith/misc.py
  src/sage/arith/numerical_approx.pxd
  src/sage/arith/numerical_approx.pyx
  src/sage/arith/srange.pyx
Labels: c: basic arithmetic, s: positive review, t: refactoring

#36059 Speed up the creation of submatrices of `Matrix_modn_dense_template` matrices
  src/sage/matrix/matrix1.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_modn_dense_template.pxi
Labels: t: enhancement, s: positive review, c: linear algebra, t: performance

#36067 `sage.{cpython,data_structures,databases,ext,parallel,structure}`: Update `# needs`
  src/sage/cpython/cython_metaclass.pyx
  src/sage/cpython/debug.pyx
  src/sage/cpython/getattr.pyx
  src/sage/cpython/string.pyx
  src/sage/cpython/wrapperdescr.pxd
  src/sage/cpython/wrapperdescr.pyx
  src/sage/data_structures/bitset.pyx
  src/sage/data_structures/blas_dict.pyx
  src/sage/data_structures/stream.py
  src/sage/databases/cremona.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/databases/db_modular_polynomials.py
  src/sage/databases/findstat.py
  src/sage/databases/jones.py
  src/sage/databases/oeis.py
  src/sage/databases/stein_watkins.py
  src/sage/ext/fast_callable.pyx
  src/sage/ext/fast_eval.pyx
  src/sage/ext/memory_allocator.pxd
  src/sage/ext/memory_allocator.pyx
  src/sage/parallel/decorate.py
  src/sage/parallel/map_reduce.py
  src/sage/parallel/use_fork.py
  src/sage/sets/recursively_enumerated_set.pyx
  src/sage/structure/category_object.pyx
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_actions.pyx
  src/sage/structure/coerce_dict.pyx
  src/sage/structure/coerce_maps.pyx
  src/sage/structure/element.pxd
  src/sage/structure/element.pyx
  src/sage/structure/element_wrapper.pyx
  src/sage/structure/factorization.py
  src/sage/structure/factory.pyx
  src/sage/structure/formal_sum.py
  src/sage/structure/global_options.py
  src/sage/structure/indexed_generators.py
  src/sage/structure/nonexact.py
  src/sage/structure/parent.pyx
  src/sage/structure/parent_gens.pyx
  src/sage/structure/parent_old.pyx
  src/sage/structure/proof/proof.py
  src/sage/structure/richcmp.pxd
  src/sage/structure/sage_object.pyx
  src/sage/structure/sequence.py
  src/sage/structure/unique_representation.py
Labels: s: positive review, t: refactoring

#36071 Correct typo in class name of `Polynomial_ZZ_pEX` in `.pxd` file
  src/sage/rings/polynomial/polynomial_zz_pex.pxd
Labels: s: positive review, c: commutative algebra

#36079 fix and activate pycodestyle E301 in pyx files
  src/sage/graphs/edge_connectivity.pyx
  src/sage/libs/giac/giac.pyx
  src/sage/matrix/constructor.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
  src/sage/matrix/strassen.pyx
  src/sage/misc/binary_tree.pyx
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/parser.pyx
  src/sage/misc/weak_dict.pyx
  src/sage/modules/vector_double_dense.pyx
  src/sage/numerical/backends/generic_backend.pyx
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/padics/padic_capped_relative_element.pyx
  src/sage/rings/padics/padic_floating_point_element.pyx
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polynomial_compiled.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/rings/real_double.pyx
  src/sage/structure/sage_object.pyx
  src/tox.ini
Labels: s: positive review, t: refactoring

#36083 build/pkgs/jupyter_core: Update to 4.12.0
  build/pkgs/jupyter_core/checksums.ini
  build/pkgs/jupyter_core/package-version.txt
Labels: c: packages: standard, s: positive review, p: critical / 2

#36085 some details in coxeter groups
  src/sage/categories/coxeter_groups.py
  src/sage/categories/monoids.py
Labels: s: positive review, c: combinatorics

#36086 using python-style for-loops in modular folder
  src/sage/modular/arithgroup/congroup.pyx
  src/sage/modular/modform/eis_series_cython.pyx
  src/sage/modular/modform/l_series_gross_zagier_coeffs.pyx
  src/sage/modular/modsym/apply.pyx
  src/sage/modular/modsym/p1list.pyx
Labels: s: positive review, t: refactoring

#36087 using python-style for loops in calculus
  src/sage/calculus/interpolation.pyx
  src/sage/calculus/ode.pyx
  src/sage/calculus/riemann.pyx
  src/sage/calculus/transforms/dwt.pyx
  src/sage/calculus/transforms/fft.pyx
Labels: s: positive review, t: refactoring

#36089 `sage.geometry.polyhedron`: fix doctest error due to modularization
  src/sage/geometry/polyhedron/base_ZZ.py
Labels: s: positive review, p: critical / 2, c: geometry, t: refactoring

#36093 Speed-up the creation of a zero matrix of type `Matrix_modn_dense_template`
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_modn_dense_template.pxi
Labels: s: needs work, c: linear algebra, t: performance

#36094 Height function for projective subvarieties
  src/sage/schemes/projective/projective_subscheme.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebraic geometry

#36096 add ordered set partitions as supported findstat collection
  src/sage/databases/findstat.py
Labels: s: positive review, c: combinatorics

#36097 Add additional bindings from NTL to `Polynomial_ZZ_pEX`
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
Labels: s: positive review, c: commutative algebra

#36098 Detect and use system MathJax-3.x
  build/pkgs/mathjax/distros/gentoo.txt
  build/pkgs/mathjax/spkg-configure.m4
  pkgs/sage-conf/_sage_conf/_conf.py.in
  src/sage_docbuild/conf.py
Labels: s: positive review

#36106 `sage.crypto`: Update `# needs`, modularization fixes
  src/sage/crypto/block_cipher/des.py
  src/sage/crypto/block_cipher/miniaes.py
  src/sage/crypto/block_cipher/present.py
  src/sage/crypto/block_cipher/sdes.py
  src/sage/crypto/boolean_function.pyx
  src/sage/crypto/cipher.py
  src/sage/crypto/classical.py
  src/sage/crypto/classical_cipher.py
  src/sage/crypto/cryptosystem.py
  src/sage/crypto/lattice.py
  src/sage/crypto/lfsr.py
  src/sage/crypto/lwe.py
  src/sage/crypto/mq/mpolynomialsystemgenerator.py
  src/sage/crypto/mq/rijndael_gf.py
  src/sage/crypto/mq/sr.py
  src/sage/crypto/public_key/blum_goldwasser.py
  src/sage/crypto/sbox.pyx
  src/sage/crypto/sboxes.py
  src/sage/crypto/stream.py
  src/sage/crypto/stream_cipher.py
  src/sage/crypto/util.py
Labels: s: positive review, c: cryptography, t: refactoring

#35084 build/pkgs/cython: Update to 0.29.36
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/package-version.txt
  build/pkgs/cython/patches/0001-cython.trashcan-directive-to-enable-the-Python-trash.patch
  build/pkgs/cython/patches/0001-rebased-PR2946.patch
Labels: c: packages: standard, s: positive review, p: critical / 2

#35399 libatomic_ops: Update to 7.8.0
  build/pkgs/libatomic_ops/SPKG.rst
  build/pkgs/libatomic_ops/checksums.ini
  build/pkgs/libatomic_ops/package-version.txt
Labels: c: packages: standard, s: positive review

#35404 Drop support for Python 3.8
  .github/workflows/dist.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  README.md
  build/pkgs/_python3.8/distros/arch.txt
  build/pkgs/_python3.8/distros/cygwin.txt
  build/pkgs/_python3.8/distros/debian.txt
  build/pkgs/_python3.8/distros/fedora.txt
  build/pkgs/_python3.8/distros/freebsd.txt
  build/pkgs/_python3.8/distros/homebrew.txt
  build/pkgs/_python3.8/distros/macports.txt
  build/pkgs/_python3.8/distros/opensuse.txt
  build/pkgs/backports_zoneinfo/SPKG.rst
  build/pkgs/backports_zoneinfo/checksums.ini
  build/pkgs/backports_zoneinfo/dependencies
  build/pkgs/backports_zoneinfo/distros/conda.txt
  build/pkgs/backports_zoneinfo/install-requires.txt
  build/pkgs/backports_zoneinfo/package-version.txt
  build/pkgs/backports_zoneinfo/spkg-install.in
  build/pkgs/backports_zoneinfo/type
  build/pkgs/python3/SPKG.rst
  build/pkgs/python3/spkg-configure.m4
  build/pkgs/tzlocal/dependencies
  m4/setup_cfg_metadata.m4
  pkgs/sage-docbuild/setup.cfg
  pkgs/sage-setup/setup.cfg
  pkgs/sagemath-categories/setup.cfg.m4
  pkgs/sagemath-environment/setup.cfg.m4
  pkgs/sagemath-objects/setup.cfg.m4
  pkgs/sagemath-repl/setup.cfg.m4
  pyrightconfig.json
  src/doc/en/developer/coding_basics.rst
  src/doc/en/developer/coding_in_python.rst
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/algebras/fusion_rings/shm_managers.pyx
  src/setup.cfg.m4
  tox.ini
Labels: c: packages: standard, s: positive review, p: critical / 2

#35716 `sage.functions`: Decouple from `sage.symbolic.expression` and `mpmath`, update `# needs`
  src/sage/calculus/calculus.py
  src/sage/functions/airy.py
  src/sage/functions/bessel.py
  src/sage/functions/error.py
  src/sage/functions/exp_integral.py
  src/sage/functions/gamma.py
  src/sage/functions/generalized.py
  src/sage/functions/hyperbolic.py
  src/sage/functions/hypergeometric.py
  src/sage/functions/jacobi.py
  src/sage/functions/log.py
  src/sage/functions/min_max.py
  src/sage/functions/orthogonal_polys.py
  src/sage/functions/other.py
  src/sage/functions/piecewise.py
  src/sage/functions/prime_pi.pyx
  src/sage/functions/special.py
  src/sage/functions/spike_function.py
  src/sage/functions/transcendental.py
  src/sage/functions/trig.py
  src/sage/functions/wigner.py
  src/sage/misc/derivative.pyx
  src/sage/misc/dev_tools.py
  src/sage/symbolic/constants.py
  src/sage/symbolic/constants_c_impl.pxi
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/expression_conversion_algebraic.py
  src/sage/symbolic/expression_conversion_sympy.py
  src/sage/symbolic/expression_conversions.py
  src/sage/symbolic/function.pyx
  src/sage/symbolic/ginac/numeric.cpp
  src/sage/symbolic/integration/external.py
  src/sage/symbolic/integration/integral.py
  src/sage/symbolic/pynac.pxi
  src/sage/symbolic/pynac_impl.pxi
  src/sage/symbolic/ring.pyx
  src/sage/symbolic/symbols.py
  src/sage/symbolic/symengine.py
Labels: s: positive review, c: symbolics, t: refactoring

#35743 gc: update to 8.2.4
  build/pkgs/gc/SPKG.rst
  build/pkgs/gc/checksums.ini
  build/pkgs/gc/package-version.txt
  build/pkgs/gc/spkg-install.in
Labels: c: packages: standard, s: positive review

#35914 Implement cocharacter and primitive Eulerian polynomials for hyperplane arrangements
  src/doc/en/reference/references/index.rst
  src/sage/geometry/hyperplane_arrangement/arrangement.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: geometry

#36132 Delete .zenodo.json
  .zenodo.json
Labels: s: positive review
