Repository sagemath/sage, pull requests merged in 2023-12, with the labels that each got.

#36653 clean E702 etc in integer.pyx
  src/sage/rings/integer.pyx
Labels: s: positive review, t: refactoring

#36368 Laurent polynomials, Fitting ideals and characteristic varieties
  src/sage/groups/finitely_presented.py
  src/sage/matrix/matrix_laurent_mpolynomial_dense.pxd
  src/sage/matrix/matrix_laurent_mpolynomial_dense.pyx
  src/sage/matrix/matrix_space.py
  src/sage/rings/polynomial/ideal.py
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_ideal.py
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: t: enhancement, s: positive review, c: group theory, c: commutative algebra

#36457 check coprimality of moduli in CRT_basis()
  src/sage/arith/misc.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#36562 `pkgs/sage-{docbuild,setup,sws2rst}`: Migrate from `setup.cfg` to `pyproject.toml`
  pkgs/sage-docbuild/pyproject.toml
  pkgs/sage-docbuild/setup.cfg
  pkgs/sage-setup/pyproject.toml
  pkgs/sage-setup/setup.cfg
  pkgs/sage-sws2rst/pyproject.toml
  pkgs/sage-sws2rst/setup.cfg
  pkgs/sagemath-bliss/pyproject.toml.m4
  pkgs/sagemath-categories/pyproject.toml.m4
  pkgs/sagemath-coxeter3/pyproject.toml.m4
  pkgs/sagemath-mcqd/pyproject.toml.m4
  pkgs/sagemath-meataxe/pyproject.toml.m4
  pkgs/sagemath-objects/pyproject.toml.m4
  pkgs/sagemath-sirocco/pyproject.toml.m4
  pkgs/sagemath-tdlib/pyproject.toml.m4
  src/pyproject.toml.m4
Labels: p: minor / 4, s: positive review, c: distribution

#36574 rename the backtrack algorithm of method `longest_path` with deprecation
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#36584 implemented power of graph function under basic methods
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#36589 Replace relative imports by absolute ones in a few packages
  src/sage/arith/all.py
  src/sage/arith/power.pyx
  src/sage/cpython/all.py
  src/sage/cpython/debug.pyx
  src/sage/data_structures/all.py
  src/sage/data_structures/bitset.pxd
  src/sage/data_structures/bitset.pyx
  src/sage/misc/all.py
  src/sage/misc/all__sagemath_environment.py
  src/sage/misc/all__sagemath_objects.py
  src/sage/misc/all__sagemath_repl.py
  src/sage/misc/benchmark.py
  src/sage/misc/copying.py
  src/sage/misc/cython.py
  src/sage/misc/func_persist.py
  src/sage/misc/lazy_import_cache.py
  src/sage/misc/misc.py
  src/sage/misc/sagedoc.py
Labels: s: positive review, t: refactoring

#36592 Add pull_from_function_field to curves
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/projective_curve.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebraic geometry

#36597 Replace relative imports by absolute ones in modules
  src/sage/modules/all.py
  src/sage/modules/complex_double_vector.py
  src/sage/modules/free_module.py
  src/sage/modules/free_module_morphism.py
  src/sage/modules/free_quadratic_module.py
  src/sage/modules/quotient_module.py
  src/sage/modules/real_double_vector.py
  src/sage/modules/submodule.py
  src/sage/modules/vector_callable_symbolic_dense.py
  src/sage/modules/vector_mod2_dense.pxd
  src/sage/modules/vector_space_morphism.py
  src/sage/modules/vector_symbolic_dense.py
  src/sage/modules/vector_symbolic_sparse.py
Labels: s: positive review, t: refactoring

#36623 cylint cleanup in combinatorial polyhedra
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/combinatorial_face.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/conversions.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_list_data_structure.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_list_data_structure.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/list_of_faces.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/list_of_faces.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pyx
Labels: s: positive review, c: geometry, t: refactoring

#36630 Allow to specify output directory for generated interpreters
  src/sage_setup/autogen/__init__.py
  src/sage_setup/autogen/interpreters/__main__.py
Labels: s: positive review

#36637 sums of elliptic-curve morphisms
  src/doc/en/reference/arithmetic_curves/index.rst
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_composite.py
  src/sage/schemes/elliptic_curves/hom_frobenius.py
  src/sage/schemes/elliptic_curves/hom_scalar.py
  src/sage/schemes/elliptic_curves/hom_sum.py
  src/sage/schemes/elliptic_curves/hom_velusqrt.py
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#36638 return Weierstrass scaling factor in base field for EllipticCurveIsogeny
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: t: bug, p: minor / 4, s: positive review, c: elliptic curves

#36643 `sage.combinat.species`: Update `# needs`
  src/sage/combinat/species/characteristic_species.py
  src/sage/combinat/species/composition_species.py
  src/sage/combinat/species/cycle_species.py
  src/sage/combinat/species/empty_species.py
  src/sage/combinat/species/functorial_composition_species.py
  src/sage/combinat/species/generating_series.py
  src/sage/combinat/species/library.py
  src/sage/combinat/species/linear_order_species.py
  src/sage/combinat/species/misc.py
  src/sage/combinat/species/partition_species.py
  src/sage/combinat/species/permutation_species.py
  src/sage/combinat/species/product_species.py
  src/sage/combinat/species/recursive_species.py
  src/sage/combinat/species/set_species.py
  src/sage/combinat/species/species.py
  src/sage/combinat/species/structure.py
  src/sage/combinat/species/subset_species.py
  src/sage/combinat/species/sum_species.py
Labels: s: positive review, t: refactoring

#36644 `sage.combinat.words`: Update `# needs`
  src/sage/combinat/words/abstract_word.py
  src/sage/combinat/words/alphabet.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/lyndon_word.py
  src/sage/combinat/words/morphic.py
  src/sage/combinat/words/morphism.py
  src/sage/combinat/words/paths.py
  src/sage/combinat/words/suffix_trees.py
  src/sage/combinat/words/word.py
  src/sage/combinat/words/word_char.pyx
  src/sage/combinat/words/word_generators.py
  src/sage/combinat/words/words.py
Labels: s: positive review, t: refactoring

#36654 More fixes for e221
  src/sage/groups/cubic_braid.py
  src/sage/misc/superseded.py
  src/sage/modules/free_module.py
  src/sage/modules/with_basis/morphism.py
  src/sage/plot/plot3d/platonic.py
  src/sage/plot/plot3d/tri_plot.py
Labels: s: positive review, t: refactoring

#36657 `sage.tests`: Update `# needs`
  src/sage/doctest/fixtures.py
  src/sage/ext/fast_callable.pyx
  src/sage/libs/coxeter3/__init__.py
  src/sage/libs/coxeter3/all__sagemath_coxeter3.py
  src/sage/structure/coerce.pyx
  src/sage/structure/factorization.py
  src/sage/structure/parent_old.pyx
  src/sage/symbolic/function.pyx
  src/sage/tests/article_heuberger_krenn_kropf_fsm-in-sage.py
  src/sage/tests/arxiv_0812_2725.py
  src/sage/tests/benchmark.py
  src/sage/tests/book_schilling_zabrocki_kschur_primer.py
  src/sage/tests/book_stein_ent.py
  src/sage/tests/book_stein_modform.py
  src/sage/tests/cmdline.py
  src/sage/tests/combinatorial_hopf_algebras.py
  src/sage/tests/finite_poset.py
  src/sage/tests/gap_packages.py
  src/sage/tests/gosper-sum.py
  src/sage/tests/lazy_imports.py
  src/sage/tests/modular_group_cohomology.py
  src/sage/tests/numpy.py
  src/sage/tests/parigp.py
  src/sage/tests/symbolic-series.py
  src/sage/tests/sympy.py
Labels: s: positive review, t: refactoring

#36658 `sage.sat`: Update `# needs`
  src/sage/sat/boolean_polynomials.py
  src/sage/sat/converters/__init__.py
  src/sage/sat/converters/polybori.py
  src/sage/sat/solvers/cryptominisat.py
  src/sage/sat/solvers/dimacs.py
  src/sage/sat/solvers/picosat.py
  src/sage/sat/solvers/sat_lp.py
  src/sage/sat/solvers/satsolver.pyx
Labels: s: positive review, t: refactoring

#35486 fix documentation and random doctest failure for Cornacchia algorithm
  src/sage/quadratic_forms/binary_qf.py
Labels: t: bug, p: minor / 4, s: positive review, c: documentation, t: tests, c: quadratic forms

#35799 test whether point is actually on the curve when evaluating elliptic-curve isomorphism
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
Labels: t: bug, p: minor / 4, s: positive review, c: elliptic curves

#35830 Bliss spkg config
  build/pkgs/bliss/SPKG.rst
  build/pkgs/bliss/distros/alpine.txt
  build/pkgs/bliss/distros/fedora.txt
  build/pkgs/bliss/spkg-configure.m4
Labels: s: positive review, c: packages: optional, c: build: configure

#35838 FriCAS spkg-configure and Feature
  build/pkgs/fricas/distros/debian.txt
  build/pkgs/fricas/distros/freebsd.txt
  build/pkgs/fricas/distros/gentoo.txt
  build/pkgs/fricas/distros/opensuse.txt
  build/pkgs/fricas/spkg-configure.m4
  src/sage/features/fricas.py
  src/sage/functions/special.py
  src/sage/interfaces/axiom.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/fricas.py
  src/sage/interfaces/frobby.py
  src/sage/interfaces/gfan.py
  src/sage/interfaces/gp.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/jmoldata.py
  src/sage/interfaces/kash.py
  src/sage/interfaces/kenzo.py
  src/sage/interfaces/lie.py
  src/sage/interfaces/macaulay2.py
  src/sage/interfaces/magma.py
  src/sage/interfaces/mathematica.py
  src/sage/interfaces/mathics.py
  src/sage/interfaces/matlab.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/mupad.py
  src/sage/interfaces/octave.py
  src/sage/interfaces/polymake.py
  src/sage/interfaces/qepcad.py
  src/sage/interfaces/quit.py
  src/sage/interfaces/rubik.py
  src/sage/interfaces/sage0.py
  src/sage/interfaces/sagespawn.pyx
  src/sage/interfaces/scilab.py
  src/sage/interfaces/sympy.py
  src/sage/interfaces/sympy_wrapper.py
  src/sage/interfaces/tests.py
  src/sage/interfaces/tides.py
  src/sage/misc/explain_pickle.py
Labels: s: positive review, c: packages: optional, c: build: configure

#35936 generalize EllipticCurve_field.division_field() to composite orders
  src/sage/schemes/elliptic_curves/ell_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#36031 Cythonize `LatticePolytope.normal_form(algorithm='palp_native')`, change to default, add as a `Polyhedron` method
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/palp_normal_form.pyx
  src/sage/geometry/polyhedron/base_ZZ.py
  src/sage/groups/perm_gps/permgroup_element.pxd
  src/sage/groups/perm_gps/permgroup_element.pyx
Labels: t: bug, s: positive review, c: geometry, t: performance

#36135 `sage -fixdistributions`
  src/bin/sage
  src/doc/en/developer/packaging_sage_library.rst
  src/sage/misc/package_dir.py
Labels: s: positive review, c: scripts

#36184 add class groups of binary quadratic forms
  src/doc/en/reference/quadratic_forms/index.rst
  src/sage/quadratic_forms/all.py
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/bqf_class_group.py
  src/sage/rings/number_field/order.py
Labels: p: major / 3, t: enhancement, t: feature, s: positive review, c: quadratic forms

#36190 establish interface for instantiated classical modular polynomials
  src/doc/en/reference/arithmetic_curves/index.rst
  src/sage/schemes/elliptic_curves/all.py
  src/sage/schemes/elliptic_curves/mod_poly.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#36223 src/sage/doctest/control.py: double the default test timeout
  src/sage/doctest/control.py
Labels: s: positive review, c: doctest framework

#36683 refresh the file plural.pyx
  src/sage/rings/polynomial/plural.pyx
Labels: s: positive review, c: algebra, c: categories, t: refactoring

#36689 less use of _an_element_impl
  src/sage/combinat/free_module.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/lie.py
  src/sage/interfaces/lisp.py
  src/sage/interfaces/r.py
  src/sage/modular/hecke/algebra.py
Labels: s: positive review, t: refactoring

#36691 Implement twisted homology of simplicial sets.
  src/sage/categories/simplicial_sets.py
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/topology/simplicial_set.py
Labels: t: enhancement, s: positive review, c: algebraic topology

#36695 Dark Mode Compatibility: Improved Crystals Visibility
  src/doc/en/thematic_tutorials/media/stand-a.png
  src/doc/en/thematic_tutorials/media/stand-b.png
  src/doc/en/thematic_tutorials/media/stand-c.png
  src/doc/en/thematic_tutorials/media/stand-d.png
  src/doc/en/thematic_tutorials/media/stand-g.png
  src/doc/en/thematic_tutorials/media/standard1.png
  src/doc/en/thematic_tutorials/media/tableau1.png
  src/doc/en/thematic_tutorials/media/tableau2.png
  src/doc/en/thematic_tutorials/media/tableau3.png
  src/doc/en/thematic_tutorials/media/tableau4.png
  src/doc/en/thematic_tutorials/media/tableaux.png
  src/doc/en/thematic_tutorials/media/tensor.png
Labels: s: positive review, c: documentation

#36697 CI Linux incremental: Set max_parallel = 8, reduce standard-sitepackages platforms
  .github/workflows/ci-linux-incremental.yml
Labels: s: positive review, p: critical / 2, c: scripts

#36701 some details in combinations
  src/sage/combinat/combination.py
Labels: s: positive review, c: combinatorics

#36703 make modform rings for triangle groups use Algebras
  src/sage/modular/modform_hecketriangle/abstract_ring.py
  src/sage/modular/modform_hecketriangle/graded_ring.py
Labels: s: positive review, c: modular forms, t: refactoring

#36704 convert Tate algebra to use Parent and category
  src/sage/rings/tate_algebra.py
Labels: s: positive review, c: padics, t: refactoring

#36705 add method to compute the length of a tree-decomposition
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/misc/latex.py
  src/sage/misc/latex_macros.py
Labels: s: positive review, c: graph theory

#36709 get rid of coerce_try
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/structure/parent_old.pyx
Labels: s: positive review, c: coercion, t: refactoring

#36715 build/bin/sage-logger [V=0]: Show more lines of the log of failing builds
  build/bin/sage-logger
Labels: s: positive review, c: build

#36716 Free space and repeatability for the Docker Hub workflow
  .ci/describe-system.sh
  .ci/protect-secrets.sh
  .github/workflows/docker_hub.yml
  .github/workflows/push_to_docker_hub.yml
  .gitlab-ci.yml
Labels: s: positive review, c: build

#36718 Adding cellular bases for the SymmetricGroupAlgebra over general fields
  src/sage/algebras/cellular_basis.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/libs/coxeter3/coxeter_group.py
  src/sage/modules/with_basis/cell_module.py
Labels: t: enhancement, s: positive review, c: algebra

#36724 Compute dimensions of simple symmetric group modules over positive characteristic
  src/sage/combinat/partition.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/combinat/tableau.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics, c: algebra

#36728 cython-lint for graphs/
  src/sage/graphs/base/static_sparse_graph.pxd
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/bliss.pyx
  src/sage/graphs/centrality.pyx
  src/sage/graphs/connectivity.pxd
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/edge_connectivity.pyx
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/genus.pyx
  src/sage/graphs/graph_coloring.pyx
  src/sage/graphs/graph_decompositions/vertex_separation.pyx
  src/sage/graphs/graph_generators_pyx.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/independent_sets.pxd
  src/sage/graphs/independent_sets.pyx
  src/sage/graphs/matchpoly.pyx
  src/sage/graphs/path_enumeration.pyx
  src/sage/graphs/planarity.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/graphs/weakly_chordal.pyx
Labels: s: positive review, c: graph theory

#36732 build/pkgs/pari: require pari-2.5.14, drop tests for patched v2.5.13
  build/pkgs/pari/spkg-configure.m4
Labels: c: packages: standard, s: positive review, c: build: configure

#36733 `meson_python` 0.15
  build/pkgs/cmake/checksums.ini
  build/pkgs/cmake/package-version.txt
  build/pkgs/meson_python/checksums.ini
  build/pkgs/meson_python/package-version.txt
  build/pkgs/trove_classifiers/checksums.ini
  build/pkgs/trove_classifiers/package-version.txt
Labels: c: packages: standard, s: positive review

#36736 avoid importing `DiGraph` from `sage.graphs.graph`
  src/sage/categories/coxeter_groups.py
  src/sage/combinat/binary_tree.py
  src/sage/geometry/lattice_polytope.py
  src/sage/graphs/bliss.pyx
  src/sage/graphs/graph.py
  src/sage/graphs/graph_generators_pyx.pyx
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/sets/disjoint_set.pyx
  src/sage/sets/set.py
Labels: s: positive review, c: graph theory, t: refactoring

#36738 `build/bin/sage-spkg`: Add options for checking, cleaning separately from build/install
  build/bin/sage-spkg
Labels: s: positive review, c: build

#36742 Plant anchors for hunks to create links in doc preview changes
  .ci/create-changes-html.sh
  .github/workflows/doc-build.yml
Labels: t: enhancement, s: positive review, c: scripts

#36743 Normal Python packages: postpone wheel installation to the post-install phase
  build/bin/sage-dist-helpers
  build/bin/sage-spkg
  build/pkgs/pip/spkg-pipinst.in
  build/pkgs/texttable/checksums.ini
  build/pkgs/texttable/package-version.txt
Labels: c: packages: standard, s: positive review, c: build

#36744 pep8 for maxima-lib interface
  src/sage/interfaces/maxima_lib.py
Labels: s: positive review

#36745 pep8 for axiom and sympy interfaces
  src/sage/interfaces/axiom.py
  src/sage/interfaces/sympy.py
Labels: s: positive review, t: refactoring

#36564 `pkgs/sagemath-{bliss,coxeter3,...}`: Move metadata from `setup.cfg` to `pyproject.toml`
  pkgs/sagemath-bliss/pyproject.toml.m4
  pkgs/sagemath-bliss/setup.cfg.m4
  pkgs/sagemath-coxeter3/pyproject.toml.m4
  pkgs/sagemath-coxeter3/setup.cfg.m4
  pkgs/sagemath-mcqd/pyproject.toml.m4
  pkgs/sagemath-mcqd/setup.cfg.m4
  pkgs/sagemath-meataxe/pyproject.toml.m4
  pkgs/sagemath-meataxe/setup.cfg.m4
  pkgs/sagemath-sirocco/pyproject.toml.m4
  pkgs/sagemath-sirocco/setup.cfg.m4
  pkgs/sagemath-tdlib/pyproject.toml.m4
  pkgs/sagemath-tdlib/setup.cfg.m4
Labels: p: minor / 4, s: positive review, c: distribution

#36645 `sage.libs.pari`, `sage.rings.real_mpfr`: Modularization fixes
  src/sage/interfaces/gp.py
  src/sage/libs/pari/__init__.py
  src/sage/libs/pari/convert_gmp.pyx
  src/sage/libs/pari/convert_sage.pyx
  src/sage/libs/pari/convert_sage_complex_double.pyx
  src/sage/libs/pari/convert_sage_matrix.pyx
  src/sage/libs/pari/convert_sage_real_mpfr.pxd
  src/sage/libs/pari/convert_sage_real_mpfr.pyx
  src/sage/libs/pari/tests.py
  src/sage/matrix/args.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/real_lazy.pyx
  src/sage/rings/real_mpfr.pxd
  src/sage/rings/real_mpfr.pyx
Labels: s: positive review, t: refactoring

#36665 implement Bröker's algorithm for constructing supersingular curves
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/all.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#36666 Replace relative imports by absolute ones in `sage.{algebras,arith,categories,cpython,data_structures,misc,modular,rings,sat,symbolic}`
  src/sage/algebras/quatalg/quaternion_algebra_cython.pyx
  src/sage/categories/action.pyx
  src/sage/categories/morphism.pyx
  src/sage/cpython/getattr.pyx
  src/sage/cpython/wrapperdescr.pyx
  src/sage/misc/cachefunc.pxd
  src/sage/misc/lazy_import.pyx
  src/sage/misc/persist.pyx
  src/sage/misc/sage_timeit_class.pyx
  src/sage/modular/modsym/heilbronn.pyx
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/hom_finite_field.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/element_polymod.pyx
  src/sage/rings/function_field/element_rational.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/number_field/totallyreal_data.pyx
  src/sage/rings/padics/morphism.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/padics/pow_computer.pyx
  src/sage/rings/padics/pow_computer_flint.pyx
  src/sage/rings/polynomial/evaluation.pxd
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/polynomial_number_field.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/real_double.pyx
  src/sage/rings/real_double_element_gsl.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/ring.pyx
  src/sage/sat/solvers/satsolver.pyx
  src/sage/structure/parent.pyx
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/function.pyx
  src/sage/symbolic/pynac_impl.pxi
  src/sage/symbolic/ring.pyx
Labels: s: positive review, t: refactoring

#36673 capitals to Hopf, Lie, Coxeter by appropriate mechanism
  src/sage/algebras/clifford_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/algebras/lie_algebras/lie_algebra.py
  src/sage/algebras/lie_algebras/morphism.py
  src/sage/algebras/lie_algebras/nilpotent_lie_algebra.py
  src/sage/algebras/lie_algebras/quotient.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/categories/category.py
  src/sage/categories/complex_reflection_groups.py
  src/sage/categories/complex_reflection_or_generalized_coxeter_groups.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/examples/hopf_algebras_with_basis.py
  src/sage/categories/filtered_hopf_algebras_with_basis.py
  src/sage/categories/finite_coxeter_groups.py
  src/sage/categories/finite_dimensional_graded_lie_algebras_with_basis.py
  src/sage/categories/finite_dimensional_hopf_algebras_with_basis.py
  src/sage/categories/finitely_generated_lambda_bracket_algebras.py
  src/sage/categories/finitely_generated_lie_conformal_algebras.py
  src/sage/categories/generalized_coxeter_groups.py
  src/sage/categories/graded_hopf_algebras.py
  src/sage/categories/graded_hopf_algebras_with_basis.py
  src/sage/categories/graded_lie_algebras_with_basis.py
  src/sage/categories/group_algebras.py
  src/sage/categories/hopf_algebras.py
  src/sage/categories/hopf_algebras_with_basis.py
  src/sage/categories/lambda_bracket_algebras.py
  src/sage/categories/lie_algebras.py
  src/sage/categories/lie_conformal_algebras.py
  src/sage/categories/primer.py
  src/sage/categories/realizations.py
  src/sage/categories/shephard_groups.py
  src/sage/categories/super_hopf_algebras_with_basis.py
  src/sage/categories/super_modules.py
  src/sage/categories/triangular_kac_moody_algebras.py
  src/sage/categories/weyl_groups.py
  src/sage/categories/with_realizations.py
  src/sage/combinat/chas/fsym.py
  src/sage/combinat/chas/wqsym.py
  src/sage/combinat/fqsym.py
  src/sage/combinat/ncsf_qsym/generic_basis_code.py
  src/sage/combinat/ncsf_qsym/ncsf.py
  src/sage/combinat/ncsf_qsym/qsym.py
  src/sage/combinat/ncsym/bases.py
  src/sage/combinat/sf/k_dual.py
  src/sage/combinat/sf/sf.py
  src/sage/combinat/sf/sfa.py
  src/sage/misc/c3_controlled.pyx
  src/sage/rings/derivation.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: categories

#36677 symengine and symengine_py 0.11
  build/pkgs/symengine/checksums.ini
  build/pkgs/symengine/distros/arch.txt
  build/pkgs/symengine/distros/homebrew.txt
  build/pkgs/symengine/package-version.txt
  build/pkgs/symengine/spkg-configure.m4
  build/pkgs/symengine_py/checksums.ini
  build/pkgs/symengine_py/distros/arch.txt
  build/pkgs/symengine_py/distros/freebsd.txt
  build/pkgs/symengine_py/distros/gentoo.txt
  build/pkgs/symengine_py/package-version.txt
  build/pkgs/symengine_py/spkg-configure.m4
  build/pkgs/symengine_py/type
  src/sage/features/symengine_py.py
Labels: t: bug, c: packages: experimental, s: positive review, p: critical / 2, c: packages: optional, c: build: configure

#36679 `src/doc`: Update `# needs`
  src/doc/de/tutorial/tour_plotting.rst
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/en/prep/Calculus.rst
  src/doc/en/prep/Quickstarts/Differential-Equations.rst
  src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst
  src/doc/en/prep/Symbolics-and-Basic-Plotting.rst
  src/doc/en/thematic_tutorials/geometry/polyhedra_tutorial.rst
  src/doc/en/thematic_tutorials/numerical_sage/cvxopt.rst
  src/doc/en/thematic_tutorials/steenrod_algebra_modules.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_advanced.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_cartesian.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_change.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_curvilinear.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_plane.rst
  src/doc/en/tutorial/tour_plotting.rst
  src/doc/es/tutorial/tour_rings.rst
  src/doc/fr/tutorial/tour_plotting.rst
  src/doc/ja/tutorial/tour_plotting.rst
  src/doc/pt/tutorial/tour_plotting.rst
  src/doc/ru/tutorial/tour_plotting.rst
Labels: s: positive review, c: documentation, t: refactoring

#36682 `src/sage/graphs`: some care with `# optional`
  src/sage/graphs/digraph.py
  src/sage/graphs/dot2tex_utils.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_generators.py
  src/sage/graphs/graph_latex.py
  src/sage/graphs/lovasz_theta.py
Labels: s: positive review, c: graph theory, t: refactoring

#36684 get rid of some ParentWithGens in real and complex fields
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/real_mpfr.pyx
Labels: s: positive review, c: commutative algebra, c: categories, t: refactoring

#36686 `.ci/merge-fixes.sh`: Obtain patches via URL, make customizable by repository variable
  .ci/merge-fixes.sh
  .github/workflows/build.yml
  .github/workflows/ci-conda.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/macos.yml
Labels: s: positive review, c: scripts

#36687 Codestyle improvements (mostly sort imports)
  src/sage/crypto/mq/sr.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/parallel/map_reduce.py
  src/sage/repl/ipython_kernel/install.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/pbori/fglm.py
  src/sage_setup/clean.py
Labels: s: positive review, t: refactoring

#36700 use less _element_constructor
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/posets/hasse_cython.pyx
  src/sage/rings/finite_rings/hom_prime_finite_field.pyx
Labels: s: positive review, t: refactoring

#36802 Python toolchain as wheel packages
  build/pkgs/flit_core/checksums.ini
  build/pkgs/flit_core/spkg-install.in
  build/pkgs/packaging/SPKG.rst
  build/pkgs/packaging/checksums.ini
  build/pkgs/packaging/dependencies
  build/pkgs/packaging/spkg-install.in
  build/pkgs/pyparsing/SPKG.rst
  build/pkgs/pyparsing/checksums.ini
  build/pkgs/pyparsing/dependencies
  build/pkgs/pyparsing/spkg-install.in
  build/pkgs/tomli/checksums.ini
  build/pkgs/tomli/dependencies
  build/pkgs/tomli/spkg-install.in
  build/pkgs/typing_extensions/SPKG.rst
  build/pkgs/typing_extensions/checksums.ini
  build/pkgs/typing_extensions/dependencies
  build/pkgs/typing_extensions/package-version.txt
  build/pkgs/typing_extensions/spkg-install.in
Labels: c: packages: standard, s: positive review, c: build

#36818 Corrected the typo in documentation - Permutation Groups
  src/sage/groups/perm_gps/permgroup.py
Labels: s: positive review, c: documentation

#36822 Fix linter failure in 10.3.beta0
  src/sage/schemes/elliptic_curves/mod_poly.py
Labels: s: positive review, p: blocker / 1

#36823 `ipython` 8.18 and related upgrades, remove `backcall`
  build/pkgs/backcall/SPKG.rst
  build/pkgs/backcall/checksums.ini
  build/pkgs/backcall/dependencies
  build/pkgs/backcall/distros/conda.txt
  build/pkgs/backcall/distros/gentoo.txt
  build/pkgs/backcall/distros/macports.txt
  build/pkgs/backcall/distros/repology.txt
  build/pkgs/backcall/distros/void.txt
  build/pkgs/backcall/install-requires.txt
  build/pkgs/backcall/package-version.txt
  build/pkgs/backcall/spkg-configure.m4
  build/pkgs/backcall/spkg-install.in
  build/pkgs/backcall/type
  build/pkgs/ipykernel/checksums.ini
  build/pkgs/ipykernel/package-version.txt
  build/pkgs/ipython/checksums.ini
  build/pkgs/ipython/dependencies
  build/pkgs/ipython/package-version.txt
  build/pkgs/pexpect/checksums.ini
  build/pkgs/pexpect/package-version.txt
  build/pkgs/pexpect/spkg-install.in
  build/pkgs/tornado/checksums.ini
  build/pkgs/tornado/package-version.txt
  build/pkgs/traitlets/checksums.ini
  build/pkgs/traitlets/package-version.txt
Labels: c: packages: standard, s: positive review

#36828 README.md: Update section on macOS arm64
  README.md
Labels: s: positive review, c: documentation

#36837 update qepcad to B 1.74
  build/pkgs/qepcad/SPKG.rst
  build/pkgs/qepcad/checksums.ini
  build/pkgs/qepcad/distros/debian.txt
  build/pkgs/qepcad/distros/fedora.txt
  build/pkgs/qepcad/distros/macports.txt
  build/pkgs/qepcad/package-version.txt
  build/pkgs/qepcad/patches/qepcad-B-destructor.patch
  build/pkgs/qepcad/patches/qepcad-B-gcc6.patch
  build/pkgs/qepcad/patches/qepcad-B-parens.patch
  build/pkgs/qepcad/patches/qepcad-B-return.patch
  build/pkgs/qepcad/patches/qepcad-B-signed.patch
  build/pkgs/qepcad/patches/qepcad-B-syntax.patch
  build/pkgs/qepcad/patches/qepcad-B-tty.patch
  build/pkgs/qepcad/patches/qepcad-B-uninit.patch
  build/pkgs/qepcad/patches/qepcad-B-unused.patch
  build/pkgs/qepcad/type
  build/pkgs/saclib/SPKG.rst
  build/pkgs/saclib/checksums.ini
  build/pkgs/saclib/distros/debian.txt
  build/pkgs/saclib/distros/fedora.txt
  build/pkgs/saclib/package-version.txt
  src/sage/interfaces/qepcad.py
Labels: c: packages: experimental, s: positive review, c: packages: optional

#36851 various details in group (ruff and pycodestyle)
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/abelian_group_morphism.py
  src/sage/groups/additive_abelian/qmodnz.py
  src/sage/groups/affine_gps/group_element.py
  src/sage/groups/artin.py
  src/sage/groups/braid.py
  src/sage/groups/conjugacy_classes.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/fqf_orthogonal.py
  src/sage/groups/free_group.py
  src/sage/groups/galois_group.py
  src/sage/groups/generic.py
  src/sage/groups/indexed_free_group.py
  src/sage/groups/libgap_mixin.py
  src/sage/groups/matrix_gps/linear.py
  src/sage/groups/matrix_gps/orthogonal.py
  src/sage/groups/matrix_gps/symplectic.py
  src/sage/groups/matrix_gps/unitary.py
  src/sage/groups/perm_gps/cubegroup.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/groups/semimonomial_transformations/semimonomial_transformation_group.py
Labels: s: positive review, c: group theory, t: refactoring

#36852 `failing doctest on Apple M1`: corrected the test case by sorting the result
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, t: tests

#36853 various details in algebras (ruff mostly)
  src/sage/algebras/clifford_algebra.py
  src/sage/algebras/cluster_algebra.py
  src/sage/algebras/free_algebra.py
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/algebras/hecke_algebras/cubic_hecke_algebra.py
  src/sage/algebras/hecke_algebras/cubic_hecke_matrix_rep.py
  src/sage/algebras/lie_algebras/affine_lie_algebra.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/algebras/lie_algebras/heisenberg.py
  src/sage/algebras/lie_algebras/rank_two_heisenberg_virasoro.py
  src/sage/algebras/lie_algebras/symplectic_derivation.py
  src/sage/algebras/lie_algebras/virasoro.py
  src/sage/algebras/lie_conformal_algebras/freely_generated_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_with_structure_coefs.py
  src/sage/algebras/orlik_solomon.py
  src/sage/algebras/orlik_terao.py
  src/sage/algebras/q_system.py
  src/sage/algebras/quantum_groups/fock_space.py
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/algebras/schur_algebra.py
  src/sage/algebras/splitting_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra_misc.py
  src/sage/algebras/weyl_algebra.py
Labels: s: positive review, c: algebra, t: refactoring

#36854 various details in categories (ruff C4 and UP02)
  src/sage/categories/aperiodic_semigroups.py
  src/sage/categories/cartesian_product.py
  src/sage/categories/category.py
  src/sage/categories/commutative_rings.py
  src/sage/categories/covariant_functorial_construction.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/crystals.py
  src/sage/categories/examples/commutative_additive_semigroups.py
  src/sage/categories/examples/with_realizations.py
  src/sage/categories/fields.py
  src/sage/categories/finite_complex_reflection_groups.py
  src/sage/categories/finite_coxeter_groups.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/finite_enumerated_sets.py
  src/sage/categories/finite_posets.py
  src/sage/categories/group_algebras.py
  src/sage/categories/h_trivial_semigroups.py
  src/sage/categories/highest_weight_crystals.py
  src/sage/categories/homsets.py
  src/sage/categories/j_trivial_semigroups.py
  src/sage/categories/l_trivial_semigroups.py
  src/sage/categories/poor_man_map.py
  src/sage/categories/pushout.py
  src/sage/categories/r_trivial_semigroups.py
  src/sage/categories/regular_crystals.py
  src/sage/categories/semigroups.py
  src/sage/categories/signed_tensor.py
  src/sage/categories/simplicial_sets.py
  src/sage/categories/tensor.py
  src/sage/categories/weyl_groups.py
Labels: s: positive review, c: categories, t: refactoring

#36855 some ruff details in modular (unicode)
  src/sage/modular/cusps.py
  src/sage/modular/etaproducts.py
  src/sage/modular/hypergeometric_motive.py
  src/sage/modular/local_comp/smoothchar.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/modular/modsym/manin_symbol_list.py
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/modular/pollack_stevens/modsym.py
  src/sage/modular/pollack_stevens/sigma0.py
Labels: s: positive review, c: modular forms, t: refactoring

#36856 various details in modules folder (ruff, cython-lint, roles)
  src/sage/modules/fg_pid/fgp_module.py
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/finite_submodule_iter.pyx
  src/sage/modules/free_module.py
  src/sage/modules/free_module_element.pyx
  src/sage/modules/free_module_integer.py
  src/sage/modules/free_quadratic_module.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/module.pyx
  src/sage/modules/tensor_operations.py
  src/sage/modules/vector_integer_sparse.pyx
  src/sage/modules/vector_mod2_dense.pyx
  src/sage/modules/vector_modn_sparse.pyx
  src/sage/modules/vector_numpy_dense.pyx
  src/sage/modules/vector_rational_sparse.pyx
  src/sage/modules/with_basis/invariant.py
  src/sage/modules/with_basis/morphism.py
Labels: s: positive review, t: refactoring

#36859 src/sage/libs/pari/convert_sage_matrix.pyx: Remove `sage_setup: distribution`
  src/sage/libs/pari/convert_sage_matrix.pyx
Labels: s: positive review, c: build, p: blocker / 1

#36640 Use GNU make tokenpool protocol to manage parallelism of doctesting
  build/pkgs/gnumake_tokenpool/SPKG.rst
  build/pkgs/gnumake_tokenpool/checksums.ini
  build/pkgs/gnumake_tokenpool/dependencies
  build/pkgs/gnumake_tokenpool/install-requires.txt
  build/pkgs/gnumake_tokenpool/package-version.txt
  build/pkgs/gnumake_tokenpool/type
  pkgs/sagemath-categories/tox.ini
  pkgs/sagemath-environment/tox.ini
  pkgs/sagemath-objects/tox.ini
  pkgs/sagemath-repl/tox.ini
  pkgs/sagemath-standard/tox.ini
  src/bin/sage-runtests
  src/doc/en/developer/doctesting.rst
  src/doc/en/installation/source.rst
  src/sage/doctest/forker.py
Labels: s: positive review, c: build, c: doctest framework

#36719 rectify docs around Tkinter
  src/doc/en/faq/faq-usage.rst
  src/doc/en/installation/source.rst
  src/doc/it/faq/faq-usage.rst
Labels: s: positive review, c: documentation

#36749 Choice of the name of primitive elements for subfields of QQbar
  src/sage/rings/qqbar.py
Labels: s: positive review, c: algebra

#36752 `numpy` 1.26.2, `scipy` 1.11.4
  build/pkgs/numpy/checksums.ini
  build/pkgs/numpy/package-version.txt
  build/pkgs/scipy/checksums.ini
  build/pkgs/scipy/package-version.txt
Labels: c: packages: standard, s: positive review

#36754 Relativize more header imports
  src/sage/cpython/debug.pyx
  src/sage/cpython/python_debug.pxd
  src/sage/graphs/cliquer.pyx
  src/sage/modular/arithgroup/farey.cpp
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/structure/coerce_dict.pyx
  src/sage_setup/autogen/interpreters/generator.py
  src/sage_setup/autogen/interpreters/specs/cc.py
  src/sage_setup/autogen/interpreters/specs/cdf.py
  src/sage_setup/autogen/interpreters/specs/element.py
  src/sage_setup/autogen/interpreters/specs/rr.py
Labels: s: positive review

#36758 Details in interfaces
  src/sage/interfaces/expect.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/mathematica.py
  src/sage/interfaces/mathics.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/polymake.py
  src/sage/interfaces/qepcad.py
Labels: s: positive review, c: interfaces, t: refactoring

#36764 Improve performance of __getitem__ of CFiniteSequence
  src/doc/en/reference/references/index.rst
  src/sage/rings/cfinite_sequence.py
Labels: s: positive review

#36765 Update to new conway-polynomials python package
  build/pkgs/conway_polynomials/SPKG.rst
  build/pkgs/conway_polynomials/checksums.ini
  build/pkgs/conway_polynomials/dependencies
  build/pkgs/conway_polynomials/distros/conda.txt
  build/pkgs/conway_polynomials/distros/gentoo.txt
  build/pkgs/conway_polynomials/install-requires.txt
  build/pkgs/conway_polynomials/package-version.txt
  build/pkgs/conway_polynomials/spkg-configure.m4
  build/pkgs/conway_polynomials/spkg-install.in
  build/pkgs/conway_polynomials/spkg-install.py
  src/sage/databases/all.py
  src/sage/databases/conway.py
  src/sage/env.py
  src/sage/features/__init__.py
  src/sage/features/databases.py
  src/setup.cfg.m4
Labels: c: packages: standard, s: positive review

#36767 Reduce execution time of conda workflow
  .github/workflows/ci-conda.yml
Labels: s: positive review, c: scripts

#36769 Do not fail when `java` is available but `jmol` is not.
  src/sage/interfaces/jmoldata.py
  src/sage/plot/plot3d/base.pyx
  src/sage/repl/rich_output/backend_ipython.py
Labels: s: positive review, p: blocker / 1

#36785 `build/pkgs/cython`: Update to 3.0.6
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/package-version.txt
Labels: c: packages: standard, s: positive review

#36794 `sage --package create --pypi`: Create a wheel package by default if possible
  build/make/Makefile.in
  build/pkgs/six/checksums.ini
  build/pkgs/six/dependencies
  build/pkgs/six/spkg-install.in
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
Labels: s: positive review, c: scripts, c: distribution

#36799 Create index-pdf.html in html build
  src/sage_docbuild/builders.py
Labels: s: positive review, c: documentation

#36812 made changes to the documentaiton of developer in python3 print
  src/doc/en/developer/coding_basics.rst
Labels: s: positive review

#36815 Add badges to README.md
  README.md
Labels: s: positive review, c: documentation

#36439 CVXpy 1.4.1, SCS 3.2.3, osqp_python 0.6.3, CVXOPT 1.3.2, CyLP 0.92.2, add `clarabel` solver
  build/pkgs/clarabel/SPKG.rst
  build/pkgs/clarabel/dependencies
  build/pkgs/clarabel/requirements.txt
  build/pkgs/clarabel/type
  build/pkgs/cvxopt/checksums.ini
  build/pkgs/cvxopt/package-version.txt
  build/pkgs/cvxpy/checksums.ini
  build/pkgs/cvxpy/dependencies
  build/pkgs/cvxpy/package-version.txt
  build/pkgs/cvxpy/spkg-install.in
  build/pkgs/cylp/checksums.ini
  build/pkgs/cylp/package-version.txt
  build/pkgs/cylp/spkg-install.in
  build/pkgs/ecos_python/spkg-install.in
  build/pkgs/osqp_python/checksums.ini
  build/pkgs/osqp_python/package-version.txt
  build/pkgs/osqp_python/spkg-install.in
  build/pkgs/scs/checksums.ini
  build/pkgs/scs/package-version.txt
  build/pkgs/scs/spkg-install.in
  src/sage/numerical/backends/cvxopt_backend.pyx
  src/sage/numerical/backends/cvxpy_backend.pyx
Labels: c: packages: standard, s: positive review, p: critical / 2, c: packages: optional, c: linear programming

#36895 fix qepcad doctest
  src/sage/interfaces/qepcad.py
Labels: s: positive review, t: tests

#36896 `src/sage/interfaces/{gap,kenzo,scilab}`: fix doctests warnings
  src/sage/interfaces/gap.py
  src/sage/interfaces/kenzo.py
  src/sage/interfaces/scilab.py
Labels: s: positive review, c: interfaces, t: refactoring

#36678 CI conda: Ignore baseline test failures
  .github/workflows/ci-conda-known-test-failures.json
  .github/workflows/ci-conda.yml
Labels: s: positive review, p: critical / 2, c: scripts

#36751 Switch sage-conf to modern editable install
  build/bin/sage-dist-helpers
  build/pkgs/sagelib/spkg-install.in
Labels: s: positive review, c: build

#36774 `build/pkgs/nauty`: Update to 2.8.8; use VERSION in all `upstream_url`s.
  build/bin/sage-spkg
  build/pkgs/4ti2/checksums.ini
  build/pkgs/cunningham_tables/checksums.ini
  build/pkgs/gf2x/checksums.ini
  build/pkgs/graphs/checksums.ini
  build/pkgs/kenzo/checksums.ini
  build/pkgs/nauty/checksums.ini
  build/pkgs/nauty/package-version.txt
  build/pkgs/nauty/patches/nauty-2.8.6-gentreeg-gentourng.patch
  build/pkgs/planarity/checksums.ini
  build/pkgs/plantri/checksums.ini
  build/pkgs/polytopes_db_4d/checksums.ini
  build/pkgs/sqlite/checksums.ini
  build/pkgs/symmetrica/checksums.ini
  build/pkgs/sympow/checksums.ini
  build/sage_bootstrap/cmdline.py
  build/sage_bootstrap/package.py
  build/sage_bootstrap/updater.py
  src/doc/en/developer/packaging.rst
Labels: c: packages: standard, s: positive review, c: distribution, c: graph theory

#36779 Remove the pycygwin package
  build/pkgs/pycygwin/SPKG.rst
  build/pkgs/pycygwin/checksums.ini
  build/pkgs/pycygwin/dependencies
  build/pkgs/pycygwin/distros/repology.txt
  build/pkgs/pycygwin/install-requires.txt
  build/pkgs/pycygwin/package-version.txt
  build/pkgs/pycygwin/spkg-install.in
  build/pkgs/pycygwin/type
  build/pkgs/sagelib/dependencies
  src/requirements.txt.m4
  src/sage/interfaces/jmoldata.py
  src/sage/plot/plot3d/base.pyx
  src/sage/repl/rich_output/backend_ipython.py
Labels: s: positive review, c: build

#36781 `libbraiding`: Actually update to version 1.2
  build/pkgs/libbraiding/checksums.ini
Labels: c: packages: standard, s: positive review, p: critical / 2

#36791 Improve the headings of the databases section of the reference manual
  src/doc/en/reference/databases/index.rst
  src/sage/databases/cremona.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/databases/cunningham_tables.py
  src/sage/databases/db_class_polynomials.py
  src/sage/databases/db_modular_polynomials.py
  src/sage/databases/findstat.py
  src/sage/databases/jones.py
  src/sage/databases/knotinfo_db.py
  src/sage/databases/odlyzko.py
  src/sage/databases/oeis.py
  src/sage/databases/sloane.py
  src/sage/databases/stein_watkins.py
  src/sage/databases/symbolic_data.py
Labels: s: positive review, c: documentation

#36792 Use the system GAP
  build/pkgs/gap/distros/debian.txt
  build/pkgs/gap/distros/fedora.txt
  build/pkgs/gap/spkg-configure.m4
  build/pkgs/gap/spkg-install.in
  build/pkgs/gap_packages/SPKG.rst
  build/pkgs/gap_packages/spkg-install.in
  pkgs/sage-conf/_sage_conf/_conf.py.in
  src/bin/sage
  src/doc/en/constructions/groups.rst
  src/doc/en/prep/Quickstarts/Abstract-Algebra.rst
  src/sage/env.py
  src/sage/ext_data/gap/sage.g
  src/sage/features/__init__.py
  src/sage/features/gap.py
  src/sage/graphs/generators/families.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/abelian_group_morphism.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/gap_workspace.py
  src/sage/libs/gap/sage.gaprc
  src/sage/libs/gap/saved_workspace.py
  src/sage/libs/gap/util.pyx
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/number_field/number_field.py
  src/sage/tests/books/judson-abstract-algebra/cyclic-sage.py
  src/sage/tests/gap_packages.py
  tox.ini
Labels: c: packages: standard, s: positive review, c: build: configure

#36814 Fast cardinality method for IntegerVectorsModPermutationGroup
  src/sage/combinat/integer_vectors_mod_permgroup.py
  src/sage/groups/group.pyx
  src/sage/groups/matrix_gps/matrix_group.py
  src/sage/groups/perm_gps/permgroup.py
Labels: s: positive review, c: combinatorics, c: group theory

#36830 improved integer vectors efficiency -Enhancement
  src/sage/combinat/integer_vector.py
Labels: t: enhancement, s: positive review, c: combinatorics

#36836 `sage --tox`, `sage --pytest`: Stop fallthrough when `tox`, `pytest` are not installed (yet)
  src/bin/sage
Labels: p: minor / 4, s: positive review, c: scripts

#36846 Resolve nice tree decomp bug in #36843, and allow `label_nice_tree_decomposition` to return a digraph
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
Labels: t: enhancement, s: positive review, c: combinatorics, c: graph theory

#36847 Symengine 0.11.2
  build/pkgs/symengine/checksums.ini
  build/pkgs/symengine/package-version.txt
  build/pkgs/symengine/spkg-configure.m4
Labels: s: positive review, p: critical / 2, c: packages: optional

#36849 Problem with orientations of simplices in simplicial complex maps.
  src/sage/topology/simplicial_complex_morphism.py
Labels: t: bug, p: minor / 4, s: positive review, c: algebraic topology

#36865 `sage.groups`, `sage.rings.number_field`: Modularization fixes, `# needs`
  src/sage/crypto/lattice.py
  src/sage/features/sagemath.py
  src/sage/groups/abelian_gps/dual_abelian_group.py
  src/sage/groups/abelian_gps/dual_abelian_group_element.py
  src/sage/groups/affine_gps/affine_group.py
  src/sage/groups/affine_gps/euclidean_group.py
  src/sage/groups/affine_gps/group_element.py
  src/sage/groups/braid.py
  src/sage/groups/galois_group.py
  src/sage/groups/galois_group_perm.py
  src/sage/groups/generic.py
  src/sage/groups/group.pyx
  src/sage/groups/matrix_gps/coxeter_group.py
  src/sage/groups/matrix_gps/finitely_generated.py
  src/sage/groups/matrix_gps/linear.py
  src/sage/groups/matrix_gps/matrix_group.py
  src/sage/groups/matrix_gps/named_group.py
  src/sage/groups/matrix_gps/orthogonal.py
  src/sage/groups/matrix_gps/symplectic.py
  src/sage/groups/matrix_gps/unitary.py
  src/sage/groups/pari_group.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/knots/knotinfo.py
  src/sage/libs/gap/libgap.pyx
  src/sage/quadratic_forms/quadratic_form__automorphisms.py
  src/sage/rings/number_field/galois_group.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/totallyreal_rel.py
Labels: s: positive review, t: refactoring

#36866 doc: update pip installation instructions
  README.md
Labels: s: positive review, c: documentation

#36871 Fix a bug for .ci/create-changes-html.sh
  .ci/create-changes-html.sh
Labels: s: positive review, p: blocker / 1, c: scripts

#36880 various details fixed in coding (ruff, pep8, links in the doc)
  src/sage/coding/abstract_code.py
  src/sage/coding/ag_code.py
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/databases.py
  src/sage/coding/delsarte_bounds.py
  src/sage/coding/guruswami_sudan/interpolation.py
  src/sage/coding/linear_code.py
  src/sage/coding/source_coding/huffman.py
Labels: s: positive review, c: coding theory, t: refactoring

#36883 `src/sage/modular/arithgroup/farey.cpp`: Fix `#include` for `farey_symbol.h`
  src/sage/modular/arithgroup/farey.cpp
Labels: s: positive review, p: blocker / 1

#36888 Fix failure of doc preview changes when an html is removed
  .ci/create-changes-html.sh
Labels: s: positive review, p: blocker / 1, c: scripts

#36890 pep8 cleanup for gap interface
  src/sage/interfaces/gap.py
Labels: s: positive review, c: interfaces, t: refactoring

#36894 Adjust the sync label bot to reflect recent GitHub CLI changes
  .github/sync_labels.py
Labels: s: positive review, c: build

#36899 some ruff fixes and error links in the graphs folder
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/base/graph_backends.pyx
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/bliss.pyx
  src/sage/graphs/digraph.py
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/domination.py
  src/sage/graphs/generators/basic.py
  src/sage/graphs/generators/chessboard.py
  src/sage/graphs/generators/degree_sequence.py
  src/sage/graphs/generators/families.py
  src/sage/graphs/generators/intersection.py
  src/sage/graphs/generators/platonic_solids.py
  src/sage/graphs/generators/random.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/generators/world_map.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/modular_decomposition.py
  src/sage/graphs/graph_generators.py
  src/sage/graphs/graph_input.py
  src/sage/graphs/graph_latex.py
  src/sage/graphs/hypergraph_generators.py
  src/sage/graphs/lovasz_theta.py
  src/sage/graphs/pq_trees.py
  src/sage/graphs/schnyder.py
  src/sage/graphs/tutte_polynomial.py
Labels: s: positive review, c: graph theory, t: refactoring

#35121 `sage.sets.family`: Cythonize; change `MIPVariable` to a subclass of `FiniteFamily`
  src/sage/combinat/root_system/type_relabel.py
  src/sage/numerical/mip.pxd
  src/sage/numerical/mip.pyx
  src/sage/sets/family.pxd
  src/sage/sets/family.pyx
Labels: t: enhancement, s: positive review, t: performance, c: linear programming

#36897 some ruff fixes (UP034 and UP039 codes) and error links in categories
  src/sage/categories/algebras_with_basis.py
  src/sage/categories/category.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/crystals.py
  src/sage/categories/enumerated_sets.py
  src/sage/categories/facade_sets.py
  src/sage/categories/fields.py
  src/sage/categories/filtered_modules_with_basis.py
  src/sage/categories/finite_groups.py
  src/sage/categories/finite_posets.py
  src/sage/categories/functor.pyx
  src/sage/categories/graded_algebras_with_basis.py
  src/sage/categories/hecke_modules.py
  src/sage/categories/highest_weight_crystals.py
  src/sage/categories/homset.py
  src/sage/categories/infinite_enumerated_sets.py
  src/sage/categories/map.pyx
  src/sage/categories/number_fields.py
  src/sage/categories/rings.py
  src/sage/categories/sets_cat.py
  src/sage/categories/simplicial_sets.py
Labels: s: positive review, c: categories, t: refactoring

#36902 `src/sage/libs/coxeter3/`: fix doctest warnings
  src/sage/libs/coxeter3/coxeter.pyx
  src/sage/libs/coxeter3/coxeter_group.py
Labels: s: positive review, t: refactoring

#36904 `src/sage/game_theory/`: fix doctest warnings due to modularization
  src/sage/game_theory/gambit_docs.py
  src/sage/game_theory/normal_form_game.py
  src/sage/game_theory/parser.py
Labels: s: positive review, c: game theory, t: refactoring

#36909 fix precision issue for 𝑗=0 and ℓ=3 in compute_isogeny_stark()
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: t: bug, p: minor / 4, s: positive review, c: elliptic curves

#36911 src/doc/bootstrap: Parallelize generation of SPKG.rst files
  build/bin/sage-spkg-info
  src/doc/bootstrap
Labels: p: minor / 4, s: positive review, c: build

#36916 `sage.combinat`: Update `# needs`
  src/sage/coding/binary_code.pyx
  src/sage/coding/codecan/autgroup_can_label.pyx
  src/sage/coding/goppa_code.py
  src/sage/combinat/binary_tree.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/latin_squares.py
  src/sage/combinat/free_module.py
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/partition.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/root_system/ambient_space.py
  src/sage/combinat/root_system/cartan_matrix.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/combinat/root_system/coxeter_group.py
  src/sage/combinat/root_system/coxeter_matrix.py
  src/sage/combinat/root_system/coxeter_type.py
  src/sage/combinat/root_system/fundamental_group.py
  src/sage/combinat/root_system/integrable_representations.py
  src/sage/combinat/root_system/non_symmetric_macdonald_polynomials.py
  src/sage/combinat/root_system/reflection_group_c.pyx
  src/sage/combinat/root_system/reflection_group_complex.py
  src/sage/combinat/root_system/reflection_group_element.pyx
  src/sage/combinat/root_system/reflection_group_real.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/root_system/root_space.py
  src/sage/combinat/root_system/root_system.py
  src/sage/combinat/root_system/weight_lattice_realizations.py
  src/sage/combinat/root_system/weyl_characters.py
  src/sage/combinat/species/composition_species.py
  src/sage/combinat/tiling.py
Labels: s: positive review, c: combinatorics, t: refactoring

#36919 refresh the doc about coercion and test the given example
  src/doc/en/reference/coercion/index.rst
Labels: s: positive review, c: documentation, c: coercion

#36924 add interface to nauty's genktreeg
  build/pkgs/nauty/package-version.txt
  build/pkgs/nauty/spkg-configure.m4
  build/pkgs/nauty/spkg-install.in
  src/sage/features/nauty.py
  src/sage/graphs/graph_generators.py
Labels: c: packages: standard, s: positive review, c: graph theory

#36925 src/sage/calculus/ode.pyx: constness fix for clang 16
  src/sage/calculus/ode.pyx
Labels: s: positive review, p: blocker / 1, c: porting

#36934 details fixed in cfinite_sequence.py
  src/sage/rings/cfinite_sequence.py
Labels: s: positive review, t: refactoring

#36935 src/sage/tests/gap_packages.py: Normalize package names in doctest
  src/sage/tests/gap_packages.py
Labels: s: positive review, t: tests, p: blocker / 1

#36943 some details in multi_polynomial base
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
Labels: s: positive review, c: commutative algebra, t: refactoring

#36948 `build/pkgs/gnumake_tokenpool`: Update to fix `AlarmInterrupt` problems
  build/pkgs/gnumake_tokenpool/checksums.ini
  build/pkgs/gnumake_tokenpool/install-requires.txt
  build/pkgs/gnumake_tokenpool/package-version.txt
  src/sage/doctest/forker.py
Labels: t: bug, c: packages: standard, s: positive review, p: critical / 2

#36786 CM elliptic curves missing isogenies
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/isogeny_class.py
Labels: s: positive review, c: elliptic curves

#36790 Combinat/sga murphy basis
  src/doc/en/reference/references/index.rst
  src/sage/algebras/cellular_basis.py
  src/sage/combinat/symmetric_group_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics, c: algebra

#36811 fixed warning while calling OEISSequence.is_dead() function
  src/sage/databases/oeis.py
Labels: s: positive review

#36845 Give more precise answer on symbolic power of a matrix
  src/sage/matrix/matrix2.pyx
Labels: s: positive review, c: symbolics

#36861 Use lualatex for better unicode support
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  build/pkgs/_recommended/dependencies
  build/pkgs/free_fonts/SPKG.rst
  build/pkgs/free_fonts/distros/alpine.txt
  build/pkgs/free_fonts/distros/arch.txt
  build/pkgs/free_fonts/distros/conda.txt
  build/pkgs/free_fonts/distros/debian.txt
  build/pkgs/free_fonts/distros/fedora.txt
  build/pkgs/free_fonts/distros/freebsd.txt
  build/pkgs/free_fonts/distros/gentoo.txt
  build/pkgs/free_fonts/distros/macports.txt
  build/pkgs/free_fonts/distros/opensuse.txt
  build/pkgs/free_fonts/distros/repology.txt
  build/pkgs/free_fonts/distros/void.txt
  build/pkgs/free_fonts/spkg-configure.m4
  build/pkgs/free_fonts/type
  build/pkgs/sagemath_doc_pdf/dependencies
  build/pkgs/texlive_luatex/SPKG.rst
  build/pkgs/texlive_luatex/dependencies
  build/pkgs/texlive_luatex/distros/alpine.txt
  build/pkgs/texlive_luatex/distros/arch.txt
  build/pkgs/texlive_luatex/distros/cygwin.txt
  build/pkgs/texlive_luatex/distros/debian.txt
  build/pkgs/texlive_luatex/distros/fedora.txt
  build/pkgs/texlive_luatex/distros/gentoo.txt
  build/pkgs/texlive_luatex/distros/macports.txt
  build/pkgs/texlive_luatex/distros/opensuse.txt
  build/pkgs/texlive_luatex/distros/repology.txt
  build/pkgs/texlive_luatex/spkg-configure.m4
  build/pkgs/texlive_luatex/type
  build/pkgs/xindy/SPKG.rst
  build/pkgs/xindy/distros/debian.txt
  build/pkgs/xindy/distros/macports.txt
  build/pkgs/xindy/distros/opensuse.txt
  build/pkgs/xindy/distros/repology.txt
  build/pkgs/xindy/spkg-configure.m4
  build/pkgs/xindy/type
  src/doc/fr/tutorial/conf.py
  src/doc/ja/a_tour_of_sage/conf.py
  src/doc/ja/tutorial/conf.py
  src/doc/ru/tutorial/conf.py
  src/sage/misc/latex.py
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation, c: packages: optional

#36874 ruff and pep E275 fixes in misc
  src/sage/misc/abstract_method.py
  src/sage/misc/banner.py
  src/sage/misc/call.py
  src/sage/misc/converting_dict.py
  src/sage/misc/cython.py
  src/sage/misc/edit_module.py
  src/sage/misc/element_with_label.py
  src/sage/misc/explain_pickle.py
  src/sage/misc/functional.py
  src/sage/misc/latex.py
  src/sage/misc/latex_standalone.py
  src/sage/misc/lazy_attribute.pyx
  src/sage/misc/mrange.py
  src/sage/misc/package.py
  src/sage/misc/package_dir.py
  src/sage/misc/random_testing.py
  src/sage/misc/sage_input.py
  src/sage/misc/sage_timeit.py
  src/sage/misc/sageinspect.py
  src/sage/misc/sphinxify.py
  src/sage/misc/temporary_file.py
  src/sage/misc/verbose.py
Labels: s: positive review, t: refactoring

#36879 update eclib to version 20231212
  build/pkgs/eclib/checksums.ini
  build/pkgs/eclib/package-version.txt
  build/pkgs/eclib/spkg-configure.m4
  build/pkgs/eclib/spkg-install.in
Labels: c: packages: standard, s: positive review

#36882 fixing one bug in the use of valuation
  src/sage/categories/discrete_valuation.py
  src/sage/modules/with_basis/indexed_element.pyx
Labels: t: bug, s: positive review, c: commutative algebra

#36884 Method braid of class Link loops when the Link contains loops
  src/sage/knots/link.py
Labels: t: bug, s: positive review, c: algebraic topology

#36901 `build/pkgs/e_antic`: Update to 2.0.0
  build/pkgs/e_antic/checksums.ini
  build/pkgs/e_antic/package-version.txt
Labels: s: positive review, p: critical / 2, c: packages: optional

#36903 ruff UP details and links to errors in doc in geometry folder
  src/sage/geometry/cone.py
  src/sage/geometry/fan.py
  src/sage/geometry/fan_morphism.py
  src/sage/geometry/hyperbolic_space/hyperbolic_coercion.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/geometry/hyperbolic_space/hyperbolic_interface.py
  src/sage/geometry/hyperbolic_space/hyperbolic_isometry.py
  src/sage/geometry/hyperbolic_space/hyperbolic_model.py
  src/sage/geometry/hyperbolic_space/hyperbolic_point.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/hyperplane_arrangement/hyperplane.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/geometry/integral_points.pxi
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/point_collection.pyx
  src/sage/geometry/polyhedral_complex.py
  src/sage/geometry/polyhedron/backend_cdd.py
  src/sage/geometry/polyhedron/backend_polymake.py
  src/sage/geometry/polyhedron/base7.py
  src/sage/geometry/polyhedron/library.py
  src/sage/geometry/polyhedron/plot.py
  src/sage/geometry/riemannian_manifolds/surface3d_generators.py
  src/sage/geometry/toric_lattice.py
  src/sage/geometry/toric_lattice_element.pyx
  src/sage/geometry/toric_plotter.py
  src/sage/geometry/triangulation/base.pyx
  src/sage/geometry/triangulation/point_configuration.py
Labels: s: positive review, c: geometry, t: refactoring

#36905 `src/sage/{categories,coding,plot,quadratic_forms}/`: Fix various doctest warnings
  src/sage/categories/finite_complex_reflection_groups.py
  src/sage/coding/ag_code_decoders.pyx
  src/sage/plot/graphics.py
  src/sage/quadratic_forms/ternary_qf.py
Labels: s: positive review, t: refactoring

#36906 various fixes in quadratic_forms (ruff, pep8, error links, etc)
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/qfsolve.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/quadratic_form__automorphisms.py
  src/sage/quadratic_forms/quadratic_form__equivalence_testing.py
  src/sage/quadratic_forms/quadratic_form__genus.py
  src/sage/quadratic_forms/quadratic_form__local_representation_conditions.py
  src/sage/quadratic_forms/quadratic_form__mass__Siegel_densities.py
Labels: s: positive review, c: quadratic forms, t: refactoring

#36913 adding corolla-related methods to free pre-Lie algebras
  src/sage/combinat/free_prelie_algebra.py
Labels: t: enhancement, s: positive review, c: combinatorics

#36917 `sage.rings`: Modularization fixes
  src/sage/calculus/test_sympy.py
  src/sage/ext/fast_callable.pyx
  src/sage/groups/generic.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/rings/bernoulli_mod_p.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/continued_fraction.py
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/galois_group.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/finite_rings/residue_field_pari_ffelt.pyx
  src/sage/rings/function_field/function_field_rational.py
  src/sage/rings/generic.py
  src/sage/rings/integer.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/rings/padics/padic_extension_leaves.py
  src/sage/rings/padics/padic_valuation.py
  src/sage/rings/polynomial/complex_roots.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/ore_function_element.py
  src/sage/rings/polynomial/ore_function_field.py
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/ore_polynomial_ring.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/skew_polynomial_element.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
  src/sage/rings/polynomial/skew_polynomial_ring.py
  src/sage/rings/polynomial/toy_d_basis.py
  src/sage/rings/power_series_mpoly.pyx
  src/sage/rings/power_series_poly.pyx
  src/sage/rings/power_series_ring.py
  src/sage/rings/puiseux_series_ring_element.pyx
  src/sage/rings/qqbar.py
  src/sage/rings/qqbar_decorators.py
  src/sage/rings/rational.pyx
  src/sage/rings/rational_field.py
  src/sage/rings/real_double.pyx
  src/sage/rings/real_field.py
  src/sage/rings/real_lazy.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/tate_algebra.py
  src/sage/rings/valuation/valuation.py
  src/sage/symbolic/expression_conversion_sympy.py
  src/sage/topology/simplicial_complex_examples.py
  src/sage/topology/simplicial_set.py
Labels: s: positive review, t: refactoring

#35823 `sage.arith.misc`: fixes error in binomial for p-adic numbers with negative valuation
  src/sage/arith/misc.py
Labels: c: basic arithmetic, s: positive review, c: padics

#36169 Implementation of representations of Lie algebras
  src/doc/en/reference/algebras/lie_algebras.rst
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
  src/sage/algebras/lie_algebras/representation.py
  src/sage/categories/lie_algebras.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#36346 Make sure the type detection for reducible Cartan types is correct
  src/sage/combinat/root_system/cartan_matrix.py
Labels: t: bug, s: positive review, c: combinatorics

#36487 Add a lift method to LieGenerator
  src/sage/algebras/lie_algebras/lie_algebra_element.pxd
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
Labels: p: major / 3, t: bug, s: positive review, c: algebra
