Repository sagemath/sage, pull requests merged in 2023-07, with the labels that each got.

#35843 Add a WSL prerequisites section
  src/doc/en/installation/source.rst
Labels: s: positive review, c: documentation

#35854 correct deprecation messages
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: documentation

#35645 Russian notation for tableaux and minor bug fix
  src/sage/combinat/output.py
  src/sage/combinat/tableau.py
  src/sage_docbuild/conf.py
Labels: t: enhancement, s: positive review, c: combinatorics

#35707 Make Sage work with maxima 5.47
  src/doc/de/tutorial/interfaces.rst
  src/doc/de/tutorial/tour_algebra.rst
  src/doc/en/constructions/linear_algebra.rst
  src/doc/en/tutorial/interfaces.rst
  src/doc/en/tutorial/tour_algebra.rst
  src/doc/es/tutorial/tour_algebra.rst
  src/doc/fr/tutorial/interfaces.rst
  src/doc/fr/tutorial/tour_algebra.rst
  src/doc/it/tutorial/tour_algebra.rst
  src/doc/ja/tutorial/interfaces.rst
  src/doc/ja/tutorial/tour_algebra.rst
  src/doc/pt/tutorial/interfaces.rst
  src/doc/pt/tutorial/tour_algebra.rst
  src/doc/ru/tutorial/interfaces.rst
  src/doc/ru/tutorial/tour_algebra.rst
  src/sage/calculus/calculus.py
  src/sage/calculus/desolvers.py
  src/sage/functions/bessel.py
  src/sage/functions/hypergeometric.py
  src/sage/functions/orthogonal_polys.py
  src/sage/functions/other.py
  src/sage/functions/special.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/maxima.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/maxima_lib.py
  src/sage/matrix/matrix1.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/symbolic/relation.py
Labels: c: packages: standard, s: positive review

#35755 Fix optional SnapPy doctests after #35665
  src/sage/knots/knotinfo.py
Labels: s: positive review, c: packages: optional

#35761 gap: switch more code to offical libgap APIs
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
  src/sage/libs/gap/util.pyx
Labels: c: packages: standard, s: positive review

#35774 Modularization fixes for `fast_callable` interpreters
  src/sage/ext/fast_callable.pyx
  src/sage_setup/autogen/interpreters/__init__.py
  src/sage_setup/autogen/interpreters/generator.py
  src/sage_setup/autogen/interpreters/instructions.py
  src/sage_setup/autogen/interpreters/memory.py
  src/sage_setup/autogen/interpreters/specs/base.py
  src/sage_setup/autogen/interpreters/specs/cc.py
  src/sage_setup/autogen/interpreters/specs/cdf.py
  src/sage_setup/autogen/interpreters/specs/element.py
  src/sage_setup/autogen/interpreters/specs/python.py
  src/sage_setup/autogen/interpreters/specs/rdf.py
  src/sage_setup/autogen/interpreters/specs/rr.py
Labels: c: basic arithmetic, s: positive review, t: refactoring

#35782 Allow partial result in minimal_model, and translate OS-algebra to cdga
  src/sage/algebras/commutative_dga.py
  src/sage/algebras/orlik_solomon.py
Labels: t: enhancement, s: positive review

#35785 build/pkgs/onetbb: Add distros/opensuse.txt
  build/pkgs/onetbb/distros/opensuse.txt
Labels: s: positive review, c: packages: optional, c: distribution

#35789 more arguments for simplify
  src/sage/calculus/functional.py
  src/sage/symbolic/expression.pyx
Labels: s: positive review, c: calculus, c: symbolics, t: refactoring

#35792 cleaning some things remaining from python 2
  src/doc/fr/tutorial/afterword.rst
  src/sage/combinat/tutorial.py
  src/sage/databases/findstat.py
  src/sage/rings/rational.pyx
  src/sage/rings/rational_field.py
  src/sage/structure/sage_object.pyx
Labels: s: positive review, t: refactoring

#35794 tox.ini, .github/workflows/docker.yml: Add almalinux
  .github/workflows/docker.yml
  tox.ini
Labels: s: positive review, c: porting

#35795 Fix copyright headers in function fields
  src/sage/rings/function_field/constructor.py
  src/sage/rings/function_field/derivations.py
  src/sage/rings/function_field/differential.py
  src/sage/rings/function_field/divisor.py
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/element_polymod.pyx
  src/sage/rings/function_field/element_rational.pyx
  src/sage/rings/function_field/function_field.py
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/function_field/function_field_rational.py
  src/sage/rings/function_field/hermite_form_polynomial.pyx
  src/sage/rings/function_field/ideal_polymod.py
  src/sage/rings/function_field/ideal_rational.py
  src/sage/rings/function_field/maps.py
  src/sage/rings/function_field/order.py
  src/sage/rings/function_field/order_basis.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/function_field/order_rational.py
  src/sage/rings/function_field/place.py
  src/sage/rings/function_field/place_polymod.py
  src/sage/rings/function_field/place_rational.py
  src/sage/rings/function_field/valuation.py
  src/sage/rings/function_field/valuation_ring.py
Labels: p: major / 3, s: positive review, c: documentation

#35798 Replace imports from `sage.geometry...all`, update relint pattern
  src/.relint.yml
  src/sage/combinat/root_system/plot.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/misc/replace_dot_all.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/schemes/toric/fano_variety.py
  src/sage/schemes/toric/library.py
  src/sage/schemes/toric/morphism.py
Labels: s: positive review, t: refactoring

#35805 gap: use libgap API for int conversion
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
Labels: c: packages: standard, s: positive review

#35808 .github/workflows/doc-build.yml: Fix generation of CHANGES.html
  .github/workflows/doc-build.yml
Labels: s: positive review, p: critical / 2

#35809 Ensure GCD in `normalize_coordinates` for projective morphisms
  src/sage/schemes/projective/projective_morphism.py
Labels: t: bug, s: positive review, c: algebraic geometry

#35816 `sage.misc.timing`: Split out from `sage.misc.misc`
  pkgs/sagemath-objects/MANIFEST.in
  src/sage/coding/binary_code.pyx
  src/sage/databases/cremona.py
  src/sage/doctest/forker.py
  src/sage/doctest/util.py
  src/sage/geometry/fan.py
  src/sage/geometry/fan_morphism.py
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pyx
  src/sage/interfaces/tests.py
  src/sage/matrix/benchmark.py
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_dense_hnf.py
  src/sage/matrix/matrix_modn_dense_template.pxi
  src/sage/misc/all.py
  src/sage/misc/all__sagemath_objects.py
  src/sage/misc/misc.py
  src/sage/misc/profiler.py
  src/sage/misc/timing.py
  src/sage/misc/verbose.py
  src/sage/modular/arithgroup/tests.py
  src/sage/modular/modform/eis_series.py
  src/sage/modular/modsym/tests.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/modular/quatalg/brandt.py
  src/sage/parallel/use_fork.py
  src/sage/quadratic_forms/quadratic_form__theta.py
  src/sage/rings/number_field/splitting_field.py
  src/sage/rings/padics/lattice_precision.py
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/polynomial/polynomial_gf2x.pyx
Labels: s: positive review, t: refactoring

#35818 fully get rid of xrange() in pyx files
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/algebras/quatalg/quaternion_algebra_cython.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/libs/ntl/ntl_GF2X_linkage.pxi
  src/sage/libs/ntl/ntl_mat_GF2E.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matrix/matrix_symbolic_dense.pyx
  src/sage/matrix/matrix_symbolic_sparse.pyx
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/polynomial/cyclotomic.pyx
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_gf2x.pyx
  src/sage/rings/polynomial/real_roots.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/tate_algebra_element.pyx
Labels: s: positive review, t: refactoring

#35819 advance the linter (add more checks)
  .vscode/settings.json
  src/doc/en/website/conf.py
  src/sage_docbuild/conf.py
  src/sage_setup/autogen/giacpy-mkkeywords.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#35822 most cython-lint suggestions fixed in algebras/
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
  src/sage/algebras/quatalg/quaternion_algebra_cython.pyx
  src/sage/algebras/quatalg/quaternion_algebra_element.pyx
Labels: s: positive review, c: algebra, t: refactoring

#35826 Fixes to support numpy 1.25.0
  src/sage/calculus/desolvers.py
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_numpy_dense.pyx
  src/sage/plot/plot3d/list_plot3d.py
  src/sage/plot/plot3d/plot3d.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#35827 some pep8 fixes in symbolic (E305 and others)
  src/sage/symbolic/callable.py
  src/sage/symbolic/constants.py
  src/sage/symbolic/operators.py
  src/sage/symbolic/random_tests.py
  src/sage/symbolic/units.py
Labels: s: positive review, c: symbolics, t: refactoring

#35831 Support setuptools 68.0.0
  src/sage/all__sagemath_repl.py
Labels: s: positive review

#35842 Fix tests with scipy 1.11
  src/doc/en/faq/faq-usage.rst
  src/doc/it/faq/faq-usage.rst
  src/sage/numerical/optimize.py
Labels: c: packages: standard, s: positive review

#35850 Remove mention of defunct magic command "%bg" from the tutorial
  src/doc/en/tutorial/interactive_shell.rst
  src/doc/fr/tutorial/interactive_shell.rst
  src/doc/ja/tutorial/interactive_shell.rst
  src/doc/pt/tutorial/interactive_shell.rst
Labels: s: positive review, c: documentation

#35344 Update to bliss 0.77
  build/pkgs/bliss/SPKG.rst
  build/pkgs/bliss/checksums.ini
  build/pkgs/bliss/dependencies
  build/pkgs/bliss/package-version.txt
  build/pkgs/bliss/patches/bliss-0.77-install.patch
  build/pkgs/bliss/spkg-install.in
  build/pkgs/bliss/spkg-src
  src/sage/graphs/bliss.pyx
  src/sage/graphs/bliss_cpp/bliss_find_automorphisms.h
Labels: s: positive review, c: packages: optional, c: graph theory

#35604 `sage -docbuild all FORMAT`: Run `make doc-FORMAT`
  src/doc/en/installation/conda.rst
  src/sage_docbuild/__main__.py
Labels: s: positive review, c: build, c: documentation

#35668 Hide features (PR to migrated Trac ticket #34185)
  src/bin/sage-runtests
  src/sage/doctest/control.py
  src/sage/features/__init__.py
  src/sage/features/join_feature.py
  src/sage/misc/lazy_import.pyx
  src/sage/misc/package.py
Labels: p: minor / 4, s: positive review, c: doctest framework

#35867 pkgs/*/setup.cfg: Reduce boilerplate by m4-include, reduce complexity of m4 use
  .gitignore
  bootstrap
  build/bin/sage-get-system-packages
  build/pkgs/sagelib/bootstrap
  m4/setup_cfg_metadata.m4
  pkgs/sagemath-categories/pyproject.toml.m4
  pkgs/sagemath-categories/setup.cfg.m4
  pkgs/sagemath-environment/pyproject.toml.m4
  pkgs/sagemath-environment/setup.cfg.m4
  pkgs/sagemath-objects/pyproject.toml.m4
  pkgs/sagemath-objects/setup.cfg.m4
  pkgs/sagemath-repl/pyproject.toml.m4
  pkgs/sagemath-repl/setup.cfg.m4
  src/setup.cfg.m4
Labels: s: positive review, c: distribution

#35876 correct parent for square root of constant polynomial
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review

#35877 cython-lint:some care for groups/perm_gps
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
  src/sage/groups/perm_gps/partn_ref/canonical_augmentation.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/double_coset.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_lists.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_python.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_sets.pyx
  src/sage/groups/perm_gps/permgroup_element.pyx
Labels: s: positive review, t: refactoring

#35879 various cython-lint fixes in algebras,arith,calculus,categories
  src/sage/algebras/letterplace/free_algebra_element_letterplace.pyx
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/algebras/octonion_algebra.pyx
  src/sage/algebras/quatalg/quaternion_algebra_element.pxd
  src/sage/arith/functions.pxd
  src/sage/arith/multi_modular.pxd
  src/sage/arith/multi_modular.pyx
  src/sage/calculus/interpolation.pyx
  src/sage/calculus/interpolators.pyx
  src/sage/calculus/ode.pxd
  src/sage/calculus/ode.pyx
  src/sage/calculus/riemann.pyx
  src/sage/calculus/transforms/dwt.pyx
  src/sage/calculus/transforms/fft.pyx
  src/sage/categories/functor.pyx
Labels: s: positive review, t: refactoring

#35880 cylint: some fixes in combinat/(crystals,matrices,words)
  src/sage/combinat/crystals/letters.pyx
  src/sage/combinat/crystals/pbw_datum.pxd
  src/sage/combinat/crystals/pbw_datum.pyx
  src/sage/combinat/crystals/spins.pxd
  src/sage/combinat/crystals/spins.pyx
  src/sage/combinat/crystals/tensor_product_element.pxd
  src/sage/combinat/crystals/tensor_product_element.pyx
  src/sage/combinat/matrices/dancing_links.pyx
  src/sage/combinat/words/word_char.pyx
  src/sage/combinat/words/word_datatypes.pxd
  src/sage/combinat/words/word_datatypes.pyx
Labels: s: positive review, t: refactoring

#35892 fixing some pep8 warnings in schemes/toric
  src/sage/schemes/toric/fano_variety.py
  src/sage/schemes/toric/ideal.py
  src/sage/schemes/toric/library.py
  src/sage/schemes/toric/morphism.py
  src/sage/schemes/toric/variety.py
  src/sage/schemes/toric/weierstrass_higher.py
Labels: s: positive review, t: refactoring

#35895 gap: make libgap APIs for function calls available
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
Labels: s: positive review

#35910 fix some pep8 in symbolic folder
  src/sage/symbolic/assumptions.py
  src/sage/symbolic/expression_conversions.py
  src/sage/symbolic/integration/external.py
  src/sage/symbolic/maxima_wrapper.py
  src/sage/symbolic/pynac_constant.py
  src/sage/symbolic/relation.py
  src/sage/symbolic/subring.py
  src/sage/symbolic/substitution_map.py
  src/sage/symbolic/tests.py
Labels: s: positive review, c: symbolics, t: refactoring

#35699 Fix weak Popov form testing
  src/sage/matrix/matrix_polynomial_dense.pyx
Labels: s: positive review

#35756 Change Rational's round method default rounding from away to even
  src/sage/modular/cusps.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/rational.pyx
Labels: s: positive review

#35783 full pep8 for preparser + little refreshing
  src/sage/repl/preparse.py
Labels: s: positive review, t: refactoring

#35802 Implementing Golod complexes
  src/sage/topology/simplicial_complex.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebraic topology

#35812 Decouple tuple
  src/sage/combinat/tuple.py
  src/sage/schemes/projective/projective_space.py
Labels: s: positive review, c: combinatorics, t: refactoring

#35825 Fix tests for singular 4.3.2p2
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
Labels: c: packages: standard, s: positive review, p: critical / 2

#35834 some pep8 for E272 in quadratic forms
  src/sage/quadratic_forms/constructions.py
  src/sage/quadratic_forms/quadratic_form__mass__Conway_Sloane_masses.py
  src/sage/quadratic_forms/quadratic_form__mass__Siegel_densities.py
  src/sage/quadratic_forms/quadratic_form__reduction_theory.py
  src/sage/quadratic_forms/special_values.py
Labels: s: positive review, c: quadratic forms, t: refactoring

#35847 Integer.{perfect_power,is_prime_power,is_irreducible}: Handle easy cases without PARI
  src/sage/rings/integer.pyx
Labels: s: positive review, p: critical / 2, c: number theory, t: refactoring

#35852 Fix typos on the link to the walkthrough.html
  src/doc/en/installation/index.rst
Labels: s: positive review, c: documentation

#35863 gap: stop using T_CHAR
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
Labels: c: packages: standard, s: positive review

#35865 CI build.yml, doc-build.yml: Fix handling of added files
  .github/workflows/build.yml
  .github/workflows/doc-build.yml
Labels: t: bug, s: positive review, p: critical / 2

#35868 Minor typo in Category documentation
  src/sage/categories/primer.py
Labels: p: minor / 4, s: positive review

#35295 put the actual description first in issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/failure_building_from_source.yml
  .github/ISSUE_TEMPLATE/feature_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s: positive review

#35925 cylint: clean the file ternary.pyx
  src/sage/quadratic_forms/ternary.pyx
Labels: s: positive review, c: quadratic forms, t: refactoring

#35929 update mpmath to 1.3.0
  build/pkgs/mpmath/SPKG.rst
  build/pkgs/mpmath/checksums.ini
  build/pkgs/mpmath/package-version.txt
Labels: c: packages: standard, s: positive review

#35937 cython-lint for imports in rings
  src/sage/libs/flint/nmod_poly_linkage.pxi
  src/sage/rings/bernoulli_mod_p.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/rational.pyx
Labels: s: positive review, t: refactoring

#35950 `bootstrap`: Accept SPKG arguments
  bootstrap
  build/pkgs/sagemath_doc_html/bootstrap
  build/pkgs/sagemath_doc_html/src
Labels: s: positive review, c: build

#35951 `sage.combinat.cluster_algebra_quiver`: Modularization fixes, update `# needs`
  src/sage/combinat/cluster_algebra_quiver/all.py
  src/sage/combinat/cluster_algebra_quiver/cluster_seed.py
  src/sage/combinat/cluster_algebra_quiver/interact.py
  src/sage/combinat/cluster_algebra_quiver/mutation_class.py
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/combinat/cluster_algebra_quiver/quiver_mutation_type.py
Labels: s: positive review, c: combinatorics, t: refactoring

#35778 Return the points in the ring of integers after renormalization
  src/sage/schemes/projective/proj_bdd_height.py
  src/sage/schemes/projective/projective_space.py
Labels: t: enhancement, s: positive review, c: algebraic geometry

#35824 add rooted product of graphs
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_decompositions/graph_products.pyx
Labels: s: positive review, c: graph theory

#35839 update barvinok to 0.41.7, add upstream_url
  build/pkgs/barvinok/SPKG.rst
  build/pkgs/barvinok/checksums.ini
  build/pkgs/barvinok/distros/freebsd.txt
  build/pkgs/barvinok/package-version.txt
Labels: c: packages: experimental, s: positive review

#35841 deprecate some imports
  src/sage/all.py
  src/sage/misc/abstract_method.py
  src/sage/misc/all.py
  src/sage/misc/banner.py
  src/sage/misc/dev_tools.py
  src/sage/misc/dist.py
  src/sage/misc/lazy_attribute.pyx
  src/sage/misc/package.py
  src/sage/misc/profiler.py
  src/sage/misc/trace.py
  src/sage/modular/hecke/module.py
  src/sage/repl/interpreter.py
  src/sage/tests/benchmark.py
Labels: t: enhancement, p: minor / 4, s: positive review

#35845 Allow sphinx <= 7.x and other conda related improvements
  .github/workflows/ci-conda.yml
  build/pkgs/sphinx/distros/conda.txt
  build/pkgs/sphinx/install-requires.txt
Labels: s: positive review, s: run conda ci

#35887 gap: switch to libgap API for GAP function calls
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/gap_includes.pxd
Labels: c: packages: standard, s: positive review

#35899 invariants are now (probably) linearly independent
  src/sage/groups/matrix_gps/finitely_generated_gap.py
Labels: s: positive review, c: commutative algebra

#35908 some pep8 fixes in homology/
  src/sage/homology/algebraic_topological_model.py
  src/sage/homology/cell_complex.py
  src/sage/homology/chain_complex.py
  src/sage/homology/chain_complex_homspace.py
  src/sage/homology/chain_complex_morphism.py
  src/sage/homology/chain_homotopy.py
  src/sage/homology/chains.py
  src/sage/homology/cubical_complex.py
  src/sage/homology/delta_complex.py
  src/sage/homology/graded_resolution.py
  src/sage/homology/hochschild_complex.py
  src/sage/homology/homology_group.py
  src/sage/homology/homology_morphism.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/homology/koszul_complex.py
  src/sage/homology/matrix_utils.py
  src/sage/homology/simplicial_complex_homset.py
  src/sage/homology/simplicial_complex_morphism.py
  src/sage/homology/simplicial_set_morphism.py
  src/sage/homology/tests.py
Labels: s: positive review, c: algebraic topology, t: refactoring

#35909 some pep8 fixes in topology/
  src/sage/topology/cell_complex.py
  src/sage/topology/cubical_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/simplicial_complex.py
  src/sage/topology/simplicial_complex_catalog.py
  src/sage/topology/simplicial_complex_examples.py
  src/sage/topology/simplicial_complex_homset.py
  src/sage/topology/simplicial_complex_morphism.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_constructions.py
  src/sage/topology/simplicial_set_examples.py
  src/sage/topology/simplicial_set_morphism.py
Labels: s: positive review, c: algebraic topology, t: refactoring

#35915 Is fully commutative for Coxeter group elements
  src/sage/categories/coxeter_groups.py
  src/sage/combinat/affine_permutation.py
  src/sage/combinat/fully_commutative_elements.py
  src/sage/combinat/root_system/braid_orbit.pyx
Labels: s: positive review, c: combinatorics

#35916 some pep8 cleanup in schemes/affine and schemes/curves
  src/sage/schemes/affine/affine_homset.py
  src/sage/schemes/affine/affine_morphism.py
  src/sage/schemes/affine/affine_point.py
  src/sage/schemes/affine/affine_rational_point.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/affine/affine_subscheme.py
  src/sage/schemes/berkovich/berkovich_space.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/closed_point.py
  src/sage/schemes/curves/constructor.py
  src/sage/schemes/curves/curve.py
  src/sage/schemes/curves/point.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/cyclic_covers/cycliccover_finite_field.py
Labels: s: positive review, c: algebraic geometry, t: refactoring

#35917 some pep8 fixes in combinat
  src/sage/combinat/composition.py
  src/sage/combinat/diagram.py
  src/sage/combinat/fully_packed_loop.py
  src/sage/combinat/growth.py
  src/sage/combinat/key_polynomial.py
  src/sage/combinat/permutation.py
  src/sage/combinat/posets/incidence_algebras.py
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/linear_extensions.py
  src/sage/combinat/recognizable_series.py
  src/sage/combinat/ribbon_shaped_tableau.py
  src/sage/combinat/rsk.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/subsets_hereditary.py
  src/sage/combinat/t_sequences.py
Labels: s: positive review, c: combinatorics, t: refactoring

#35918 pep8 cleanup in modular/btquotients and modular/modsym
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/btquotients/pautomorphicform.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/boundary.py
  src/sage/modular/modsym/element.py
  src/sage/modular/modsym/g1list.py
  src/sage/modular/modsym/ghlist.py
  src/sage/modular/modsym/manin_symbol_list.py
  src/sage/modular/modsym/modsym.py
  src/sage/modular/modsym/modular_symbols.py
  src/sage/modular/modsym/p1list_nf.py
  src/sage/modular/modsym/subspace.py
  src/sage/modular/modsym/tests.py
Labels: s: positive review, c: modular forms, t: refactoring

#35919 `sage.matroids`: Update `# needs`, modularization fixes for imports
  src/sage/matroids/advanced.py
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/catalog.py
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/constructor.py
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/extension.pyx
  src/sage/matroids/graphic_matroid.py
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/matroids/minor_matroid.py
  src/sage/matroids/set_system.pyx
  src/sage/matroids/unpickling.pyx
  src/sage/matroids/utilities.py
Labels: s: positive review, c: matroid theory, t: refactoring

#35920 replace basestring by str in cython files
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/libs/gap/libgap.pyx
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/matrix/args.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/misc/cachefunc.pyx
  src/sage/misc/citation.pyx
  src/sage/misc/lazy_import.pyx
  src/sage/misc/lazy_string.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/structure/category_object.pyx
  src/sage/structure/parent.pyx
  src/sage/symbolic/ring.pyx
Labels: s: positive review, t: refactoring

#35921 python-style syntax for loops in lean_matrix.pyx
  src/sage/matroids/lean_matrix.pyx
Labels: s: positive review, c: matroid theory, t: refactoring

#35922 using python-style loops in plot3d/*.pyx
  src/sage/plot/plot3d/implicit_surface.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/plot/plot3d/parametric_surface.pyx
  src/sage/plot/plot3d/shapes.pyx
  src/sage/plot/plot3d/transform.pyx
Labels: s: positive review, c: graphics, t: refactoring

#35923 some pycodestyle fixes in sets/
  src/sage/sets/cartesian_product.py
  src/sage/sets/condition_set.py
  src/sage/sets/disjoint_union_enumerated_sets.py
  src/sage/sets/family.py
  src/sage/sets/finite_enumerated_set.py
  src/sage/sets/finite_set_maps.py
  src/sage/sets/integer_range.py
  src/sage/sets/non_negative_integers.py
  src/sage/sets/positive_integers.py
  src/sage/sets/primes.py
  src/sage/sets/set_from_iterator.py
  src/sage/sets/totally_ordered_finite_set.py
Labels: s: positive review, t: refactoring

#35924 some pep8 fixes in functions/
  src/sage/functions/error.py
  src/sage/functions/exp_integral.py
  src/sage/functions/jacobi.py
  src/sage/functions/orthogonal_polys.py
  src/sage/functions/special.py
  src/sage/functions/transcendental.py
Labels: s: positive review, t: refactoring

#35928 first sketch for callable factorisations
  src/sage/structure/factorization.py
Labels: s: positive review, c: symbolics

#35931 cython-lint: full fix in cpython/ probability/ media/ and sat/ folders
  src/sage/cpython/atexit.pyx
  src/sage/cpython/debug.pyx
  src/sage/cpython/dict_del_by_value.pyx
  src/sage/cpython/string.pxd
  src/sage/cpython/string.pyx
  src/sage/cpython/wrapperdescr.pyx
  src/sage/media/channels.pyx
  src/sage/probability/probability_distribution.pyx
  src/sage/sat/solvers/satsolver.pyx
Labels: s: positive review, t: refactoring

#35940 fix and activate pycodestyle E252
  .vscode/settings.json
  src/sage/manifolds/scalarfield.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#35527 Improve morphisms between Drinfeld modules
  src/sage/categories/drinfeld_modules.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/homset.py
  src/sage/rings/function_field/drinfeld_modules/morphism.py
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_element.pyx
Labels: t: enhancement, s: positive review, c: algebra

#35682 guessing k-regular sequences
  src/sage/combinat/k_regular_sequence.py
Labels: p: major / 3, s: positive review, c: combinatorics

#35881 `sage.groups.perm_gps.partn_ref*`: Modularization fixes
  src/sage/groups/perm_gps/partn_ref/data_structures.pxd
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref2/refinement_generic.pxd
  src/sage/groups/perm_gps/partn_ref2/refinement_generic.pyx
Labels: s: positive review, c: combinatorics, c: group theory, t: refactoring

#35891 Deprecate sorting by default in connected component methods for graphs
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/categories/complex_reflection_or_generalized_coxeter_groups.py
  src/sage/categories/loop_crystals.py
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/combinat/constellation.py
  src/sage/combinat/crystals/littelmann_path.py
  src/sage/combinat/partition_algebra.py
  src/sage/combinat/posets/mobile.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/root_system/ambient_space.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/geometry/polyhedron/base_QQ.py
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/comparability.pyx
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/generators/world_map.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_coloring.pyx
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/graph_decompositions/graph_products.pyx
  src/sage/graphs/graph_decompositions/modular_decomposition.py
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/graphs/partial_cube.py
  src/sage/graphs/spanning_tree.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/tutte_polynomial.py
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/utilities.py
  src/sage/schemes/curves/zariski_vankampen.py
  src/sage/tests/books/computational-mathematics-with-sagemath/lp_doctest.py
  src/sage/topology/simplicial_complex.py
  src/sage/topology/simplicial_set_constructions.py
Labels: t: bug, s: positive review, c: graph theory

#35896 deal with bad chosen representations of k-regular sequences
  src/doc/en/reference/references/index.rst
  src/sage/combinat/k_regular_sequence.py
  src/sage/combinat/recognizable_series.py
Labels: p: major / 3, s: positive review, c: combinatorics

#35900 complex_dynamics, fix: mandelbrot_plot throws exception for z^2*(z-c) + c
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
Labels: s: positive review, c: dynamics

#35904 Make SubgraphSearch robust to vertex labels
  src/sage/graphs/generic_graph_pyx.pyx
Labels: s: positive review, c: graph theory

#35943 `sage.combinat.designs`: Modularization fixes, update `# needs`
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/block_design.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/difference_matrices.py
  src/sage/combinat/designs/evenly_distributed_sets.pyx
  src/sage/combinat/designs/gen_quadrangles_with_spread.pyx
  src/sage/combinat/designs/group_divisible_designs.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/designs/latin_squares.py
  src/sage/combinat/designs/orthogonal_arrays.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/combinat/designs/subhypergraph_search.pyx
  src/sage/combinat/designs/twographs.py
Labels: s: positive review, c: combinatorial designs, t: refactoring

#35956 Fix several issues in find_hamiltonian
  src/sage/graphs/generic_graph_pyx.pyx
Labels: p: major / 3, s: positive review, c: graph theory

#35962 Fix documentation formatting problem: kRegularSequence.partial_sums
  src/sage/combinat/k_regular_sequence.py
Labels: s: positive review, p: trivial / 5, c: combinatorics

#35965 Minor changes in is_chordal
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#35974 `src/sage/schemes/projective/proj_bdd_height.py`: Fix markup
  src/sage/schemes/projective/proj_bdd_height.py
Labels: t: bug, s: positive review, p: critical / 2

#35977 Move hilbert_numerator test to its proper place
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review

#35749 Add style guide / reference for `# optional - sage....` doctest tags, extend `sage -t` and `sage -fixdoctests` for modularization tasks
  src/bin/sage-fixdoctests
  src/bin/sage-runtests
  src/doc/de/tutorial/latex.rst
  src/doc/en/developer/coding_basics.rst
  src/doc/en/developer/doctesting.rst
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/fr/tutorial/latex.rst
  src/doc/ja/tutorial/latex.rst
  src/doc/pt/tutorial/latex.rst
  src/sage/calculus/ode.pyx
  src/sage/categories/category_singleton.pyx
  src/sage/categories/lie_algebras.py
  src/sage/categories/posets.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/linear_rank_metric.py
  src/sage/combinat/diagram.py
  src/sage/combinat/finite_state_machine.py
  src/sage/combinat/tutorial.py
  src/sage/doctest/control.py
  src/sage/doctest/external.py
  src/sage/doctest/fixtures.py
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
  src/sage/doctest/reporting.py
  src/sage/doctest/sources.py
  src/sage/doctest/test.py
  src/sage/doctest/util.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/features/__init__.py
  src/sage/features/all.py
  src/sage/features/gap.py
  src/sage/features/kenzo.py
  src/sage/features/sagemath.py
  src/sage/features/singular.py
  src/sage/geometry/polyhedron/base4.py
  src/sage/graphs/generic_graph.py
  src/sage/interfaces/gnuplot.py
  src/sage/interfaces/r.py
  src/sage/knots/knotinfo.py
  src/sage/misc/latex_standalone.py
  src/sage/misc/profiler.py
  src/sage/misc/sagedoc.py
  src/sage/quivers/algebra_elements.pyx
  src/sage/repl/user_globals.py
  src/sage/rings/big_oh.py
  src/sage/rings/cfinite_sequence.py
  src/sage/rings/function_field/ideal_polymod.py
  src/sage/rings/homset.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/schemes/cyclic_covers/cycliccover_finite_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/hom_frobenius.py
Labels: s: positive review, p: critical / 2, c: documentation, c: doctest framework

#35057 Implement basic j-invariants of Drinfeld modules
  src/doc/en/reference/references/index.rst
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
Labels: t: enhancement, s: positive review, c: algebra
