Repository sagemath/sage, pull requests merged in 2024-02, with the labels that each got.

#37166 add Pari file to L-function documentation
  src/doc/en/reference/lfunctions/index.rst
Labels: s: positive review, c: algebraic geometry, sd125

#37174 fixed bug in `is_linearly_dependent()`, returns true for linearly dependent univariate polynomial.
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/toy_variety.py
Labels: t: bug, s: positive review, c: algebra

#37175 search for a pair of pre- and post-isomorphism instead of just a post-isomorphism when computing dual isogeny
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: p: major / 3, t: bug, s: positive review, c: elliptic curves

#37179 `sage.categories.schemes`: Fix modularization regression
  src/sage/categories/schemes.py
Labels: s: positive review

#37181 Fix subtour elimination constraints in `longest_cycle`
  src/sage/graphs/generic_graph.py
Labels: t: bug, s: positive review, c: graph theory

#37187 implement E_polynomial of hypergeometric motive
  src/sage/modular/hypergeometric_motive.py
Labels: s: positive review, c: algebraic geometry, sd125

#37190 add lfunction to hypergeometric motives
  src/sage/lfunctions/pari.py
  src/sage/modular/hypergeometric_motive.py
Labels: s: positive review, c: algebraic geometry, c: number theory, sd125

#37194 Fix typo in pycore_long.h for Python <= 3.8.
  src/sage/cpython/pycore_long.h
Labels: t: bug, s: positive review, p: critical / 2, c: python3

#37201 Fix univariate polynomial reverse
  src/sage/matrix/matrix_polynomial_dense.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
Labels: t: bug, s: positive review, c: algebra, sd125

#37000 `build/pkgs/numpy`: Update to 1.26.3
  build/pkgs/numpy/checksums.ini
  build/pkgs/numpy/package-version.txt
Labels: c: packages: standard, s: positive review

#37035 Return a vector of monomial instead of a matrix in PolynomialSequence.coefficient_matrix()
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/pbori/pbori.pyx
Labels: s: positive review, sd125

#37056 Installation guide: Show system package commands using sphinx-inline-tabs
  build/bin/sage-print-system-package-command
  build/bin/sage-spkg-info
  build/pkgs/calver/distros/package-version.txt
  build/pkgs/sagemath_doc_html/dependencies
  build/pkgs/sphinx_inline_tabs/SPKG.rst
  build/pkgs/sphinx_inline_tabs/checksums.ini
  build/pkgs/sphinx_inline_tabs/dependencies
  build/pkgs/sphinx_inline_tabs/install-requires.txt
  build/pkgs/sphinx_inline_tabs/package-version.txt
  build/pkgs/sphinx_inline_tabs/spkg-configure.m4
  build/pkgs/sphinx_inline_tabs/type
  configure.ac
  src/doc/en/developer/github.rst
  src/doc/en/installation/source.rst
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation

#37087 use parent in Ore polynomials
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/rings.py
  src/sage/rings/polynomial/ore_function_field.py
  src/sage/rings/polynomial/ore_polynomial_ring.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: algebra, sd125

#37088 Remove deprecated methods from QuaternionFractionalIdeal_rational
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: minor / 4, s: positive review, c: algebra

#37102 fix random doctest failure in generic has_order() function
  src/sage/groups/generic.py
Labels: t: bug, p: minor / 4, s: positive review, c: group theory

#37105 minor details in asymptotic ring
  src/sage/rings/asymptotic/asymptotic_ring.py
Labels: s: positive review, c: commutative algebra, t: refactoring

#37106 Additive identity of EllipticCurve should always be minimum
  src/doc/en/constructions/elliptic_curves.rst
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/saturation.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/projective/projective_rational_point.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#37111 Add test if quaternion order is maximal
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37112 Tests to see if ideal in quaternion algebra is primitive (cyclic)
  src/doc/en/reference/references/index.rst
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37126 Fix `lift_x()` for characteristic 2 and add `is_x_coord()` to hyperelliptic curves
  src/sage/rings/integer.pyx
  src/sage/rings/rational.pyx
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
  src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
Labels: p: major / 3, t: bug, t: enhancement, s: positive review, c: algebraic geometry

#37133 use Parent in free_algebra_quotient
  src/sage/algebras/free_algebra_quotient.py
Labels: s: positive review, c: algebra

#37137 some details in infinity "ring"
  src/sage/rings/infinity.py
Labels: s: positive review, c: commutative algebra, c: symbolics

#37141 Format graphic_matroid.py
  src/sage/matroids/graphic_matroid.py
Labels: s: positive review, c: matroid theory, t: refactoring

#37142 throw ValueError instead of TypeError when logarithm doesn't exist in AdditiveAbelianGroupWrapper
  src/sage/groups/additive_abelian/additive_abelian_wrapper.py
  src/sage/modules/fg_pid/fgp_module.py
Labels: p: major / 3, t: bug, s: positive review, c: group theory

#37144 Minor ruff fixes in posets
  src/sage/combinat/posets/cartesian_product.py
  src/sage/combinat/posets/elements.py
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/incidence_algebras.py
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/linear_extensions.py
  src/sage/combinat/posets/mobile.py
  src/sage/combinat/posets/moebius_algebra.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#37145 Add matroid attribute girth()
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
Labels: t: enhancement, s: positive review, c: matroid theory

#37146 Fix a bug in reduction of element modulo ideal in exterior algebra
  src/sage/algebras/exterior_algebra_groebner.pyx
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#37152 provide Q.log(P) instead of P.discrete_log(Q) for elliptic-curve points
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves, t: refactoring

#37156 using Parent in integer rings instead of ParentWithGens
  src/sage/rings/integer_ring.pyx
Labels: s: positive review, t: refactoring

#37157 Add additional lattice methods for matrices over QQ
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_rational_dense.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: numerical

#37159 Fix `change_ring` method of multi-variate polynomials
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: s: positive review, p: critical / 2, c: algebra

#37161 Fix cvxopt build with suitesparse homebrew; fixes #37149.
  .homebrew-build-env
Labels: s: positive review

#37162 refreshing the file projective_subscheme
  src/sage/schemes/projective/projective_subscheme.py
Labels: s: positive review, c: algebraic geometry

#37163 moving modular stuff to "CommutativeRing" class
  src/sage/modular/hecke/algebra.py
Labels: s: positive review, c: modular forms, sd125

#37164 Fixes and simplifications for `.ramified_primes()`, `.discriminant()` and `.is_isomorphic` of quaternion algebras
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#37165 use Parent in quadratic number fields
  src/sage/rings/number_field/number_field_element_quadratic.pyx
Labels: s: positive review, c: number fields

#36396 implement Adams operator for lazy power series
  src/doc/en/developer/coding_in_other.rst
  src/sage/categories/bialgebras_with_basis.py
  src/sage/combinat/ncsf_qsym/ncsf.py
  src/sage/combinat/ncsf_qsym/qsym.py
  src/sage/combinat/sf/powersum.py
  src/sage/combinat/sf/sfa.py
  src/sage/matrix/compute_J_ideal.py
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/rings/lazy_series.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/tests/books/computational-mathematics-with-sagemath/linalg_doctest.py
  src/sage/tests/books/computational-mathematics-with-sagemath/sol/linalg_doctest.py
Labels: s: positive review, c: commutative algebra, sd125

#36726 CI Linux: Replace use of pkill
  .github/workflows/docker.yml
Labels: s: positive review, p: critical / 2, c: scripts, disputed

#36937 CI Conda: Add to known-test-failures
  .github/workflows/ci-conda-known-test-failures.json
  src/sage/doctest/reporting.py
Labels: s: positive review, t: tests, p: blocker / 1

#36938 CI Build & Test: Show doctest failures, warnings as annotations in the 'Files changed' tab
  .github/workflows/build.yml
  src/bin/sage-runtests
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
  src/tox.ini
Labels: s: positive review, c: doctest framework, c: scripts

#37005 `build/pkgs/openblas`: Update to 0.3.26
  build/pkgs/openblas/checksums.ini
  build/pkgs/openblas/package-version.txt
Labels: c: packages: standard, s: positive review

#37193 Some fixes & improvements to autogenerated flint .pxd
  src/sage/libs/arb/types.pxd
  src/sage/libs/flint/flint_sage.pyx
  src/sage/libs/flint/flint_wrap.h
  src/sage/libs/flint/types.pxd
  src/sage_setup/autogen/flint/templates/flint_sage.pyx.template
  src/sage_setup/autogen/flint/templates/flint_wrap.h.template
  src/sage_setup/autogen/flint/templates/types.pxd.template
Labels: s: positive review

#37195 general LU: gather several calls to field inversion into a single call
  src/sage/matrix/matrix2.pyx
Labels: p: minor / 4, s: positive review, c: linear algebra, t: performance, sd125

#37199 make FreeAlgebra graded and provide is_unit and __invert__
  src/sage/algebras/free_algebra.py
  src/sage/algebras/free_algebra_element.py
Labels: t: enhancement, s: positive review, c: algebra, sd125

#37207 allow algorithm=pari in LLL
  src/sage/matrix/matrix_integer_dense.pyx
Labels: s: positive review, c: linear algebra, sd125

#37209 Added rational Tamari lattices
  src/doc/en/reference/references/index.rst
  src/sage/combinat/tamari_lattices.py
Labels: s: positive review, c: combinatorics, sd125

#37215 Remove unnecessary bullet point
  src/doc/en/installation/index.rst
Labels: s: positive review, c: documentation, p: trivial / 5

#37218 Fix to ncsym.ncsym.nesting
  src/sage/combinat/ncsym/ncsym.py
Labels: t: bug, s: positive review, c: combinatorics

#37222 CI Linux Incremental: Do not require label "c: packages: ..." to be set
  .github/workflows/ci-linux-incremental.yml
Labels: s: positive review, c: scripts

#37223 Remove invariants commands in global namespace
  src/sage/schemes/hyperelliptic_curves/all.py
  src/sage/schemes/hyperelliptic_curves/invariants.py
Labels: p: minor / 4, s: positive review, t: refactoring

#37225 splitting_field: polred -> polredbest
  src/sage/rings/number_field/splitting_field.py
Labels: s: positive review, c: number fields, sd125

#37226 unit group of number field: do not expand product when S is empty
  src/sage/rings/number_field/unit_group.py
Labels: t: bug, s: positive review, c: number fields, t: performance, sd125

#37228 some pep8 fixes in rings, and activate E221
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/function_field/function_field_rational.py
  src/sage/rings/function_field/ideal_polymod.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/function_field/place_polymod.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/selmer_group.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/pbori/ll.py
  src/sage/rings/polynomial/term_order.py
  src/sage/rings/quotient_ring_element.py
  src/sage_docbuild/conf.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#37229 some pep8 fixes in coding, in particular E275
  src/sage/coding/abstract_code.py
  src/sage/coding/code_bounds.py
  src/sage/coding/cyclic_code.py
  src/sage/coding/grs_code.py
  src/sage/coding/linear_code.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/coding/punctured_code.py
  src/sage/coding/reed_muller_code.py
Labels: s: positive review, t: refactoring

#37230 some cython-lint fixes in ecl lib
  src/sage/libs/ecl.pyx
Labels: c: packages: standard, s: positive review

#37232 Still less use of isinstance of old-parents
  src/sage/algebras/algebra.py
  src/sage/algebras/all.py
  src/sage/categories/algebras.py
  src/sage/matrix/matrix0.pyx
  src/sage/modular/abvar/homology.py
  src/sage/modular/hecke/module.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/modsym/modsym.py
  src/sage/modular/quatalg/brandt.py
  src/sage/rings/commutative_algebra.py
  src/sage/rings/polynomial/skew_polynomial_ring.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/plane_conics/constructor.py
  src/sage/structure/element.pyx
Labels: s: positive review, t: refactoring

#37233 fix small mistake in BQFClassGroupQuotientMorphism documentation
  src/sage/quadratic_forms/bqf_class_group.py
Labels: t: bug, s: positive review, c: documentation, p: trivial / 5, c: quadratic forms

#37234 make a category of Dedekind domains, remove code from ring.pyx
  src/doc/en/tutorial/tour_coercion.rst
  src/doc/fr/tutorial/tour_coercion.rst
  src/doc/ja/tutorial/tour_coercion.rst
  src/doc/pt/tutorial/tour_coercion.rst
  src/sage/algebras/clifford_algebra.py
  src/sage/categories/all.py
  src/sage/categories/basic.py
  src/sage/categories/bimodules.py
  src/sage/categories/category.py
  src/sage/categories/category_types.py
  src/sage/categories/dedekind_domains.py
  src/sage/categories/fields.py
  src/sage/categories/homset.py
  src/sage/categories/modules.py
  src/sage/categories/morphism.pyx
  src/sage/categories/primer.py
  src/sage/matrix/matrix_space.py
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/modules/free_module.py
  src/sage/modules/free_module_homspace.py
  src/sage/modules/free_quadratic_module.py
  src/sage/rings/all.py
  src/sage/rings/complex_double.pxd
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpc.pxd
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/integer_ring.pyx
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/pari_ring.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pxd
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring_constructor.py
  src/sage/rings/qqbar.py
  src/sage/rings/real_mpfr.pxd
  src/sage/rings/ring.pyx
  src/sage/structure/category_object.pyx
  src/sage/tensor/modules/finite_rank_free_module.py
Labels: s: positive review, t: refactoring

#37240 add one method to integer-valued polynomials
  src/sage/rings/polynomial/integer_valued_polynomials.py
Labels: s: positive review, c: combinatorics, c: commutative algebra

#37245 a few details in combinat folder
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/latin_squares.py
  src/sage/combinat/designs/orthogonal_arrays.py
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/combinat/designs/steiner_quadruple_systems.py
  src/sage/combinat/finite_state_machine.py
  src/sage/combinat/partition.py
  src/sage/combinat/partition_algebra.py
  src/sage/combinat/partition_shifting_algebras.py
  src/sage/combinat/words/word_infinite_datatypes.py
Labels: s: positive review, c: combinatorics

#37246 minor details in modular
  src/sage/modular/arithgroup/arithgroup_generic.py
  src/sage/modular/arithgroup/arithgroup_perm.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/module.py
  src/sage/modular/hecke/submodule.py
  src/sage/modular/local_comp/smoothchar.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/modform/space.py
  src/sage/modular/modsym/apply.pyx
  src/sage/modular/modsym/element.py
  src/sage/modular/modsym/ghlist.py
  src/sage/modular/modsym/hecke_operator.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/modular/pollack_stevens/manin_map.py
  src/sage/modular/pollack_stevens/space.py
Labels: s: positive review, c: modular forms, t: refactoring

#37252 CI: Fix for failure in maximize-build-space
  .github/workflows/docker.yml
  .github/workflows/docker_hub.yml
Labels: s: positive review, p: critical / 2, c: scripts

#37256 general cleanup of words/paths.py
  src/sage/combinat/words/paths.py
Labels: s: positive review, c: combinatorics

#37258 add type annotations to gens methods
  src/sage/categories/examples/finite_dimensional_lie_algebras_with_basis.py
  src/sage/categories/finite_dimensional_modules_with_basis.py
  src/sage/categories/pushout.py
  src/sage/categories/semigroups.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/combinat/colored_permutations.py
  src/sage/combinat/free_dendriform_algebra.py
  src/sage/combinat/free_prelie_algebra.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/linear_expression.py
  src/sage/geometry/toric_lattice.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/dual_abelian_group.py
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/cactus_group.py
  src/sage/groups/kernel_subgroup.py
  src/sage/groups/lie_gps/nilpotent_lie_group.py
  src/sage/groups/matrix_gps/finitely_generated.py
  src/sage/groups/raag.py
  src/sage/libs/eclib/interface.py
  src/sage/modular/arithgroup/arithgroup_generic.py
  src/sage/modules/fg_pid/fgp_module.py
  src/sage/modules/free_module.py
  src/sage/modules/quotient_module.py
  src/sage/modules/submodule.py
  src/sage/modules/torsion_quadratic_module.py
  src/sage/monoids/free_abelian_monoid.py
  src/sage/monoids/monoid.py
  src/sage/quadratic_forms/bqf_class_group.py
  src/sage/quivers/algebra.py
  src/sage/quivers/path_semigroup.py
Labels: s: positive review, t: refactoring

#37269 sage_docbuild: add needs sphinx tags
  src/sage_docbuild/__main__.py
  src/sage_docbuild/builders.py
  src/sage_docbuild/sphinxbuild.py
Labels: s: positive review, p: critical / 2

#37272 enable the generation of acyclic orientations with `nauty_directg`
  src/sage/graphs/digraph_generators.py
Labels: s: positive review, c: graph theory

#37279 Fix some doctest warnings
  src/sage/geometry/polyhedron/backend_field.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/generic.py
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/schemes/curves/affine_curve.py
Labels: s: positive review

#36881 Fix cardinality of special linear group
  src/sage/categories/finite_groups.py
  src/sage/groups/libgap_wrapper.pyx
  src/sage/groups/matrix_gps/linear.py
Labels: s: positive review, c: group theory

#36927 src/sage/combinat/designs/subhypergraph_search.pyx: constness fix for clang 16
  src/sage/combinat/designs/subhypergraph_search.pyx
Labels: s: positive review, c: porting

#36983 Prepare python3 `spkg-configure.m4` for Python 3.12 (setuptools instead of distutils)
  build/pkgs/_python3.12/distros/debian.txt
  build/pkgs/python3/SPKG.rst
  build/pkgs/python3/distros/alpine.txt
  build/pkgs/python3/distros/debian.txt
  build/pkgs/python3/distros/fedora.txt
  build/pkgs/python3/distros/freebsd.txt
  build/pkgs/python3/distros/homebrew.txt
  build/pkgs/python3/distros/macports.txt
  build/pkgs/python3/distros/opensuse.txt
  build/pkgs/python3/distros/void.txt
  build/pkgs/python3/spkg-configure.m4
  m4/sage_check_python_for_venv.m4
Labels: c: packages: standard, s: positive review, p: critical / 2, c: build: configure

#36997 `build/pkgs/{givaro,fflas_ffpack,linbox}`: Accept matching set of new versions
  .github/workflows/ci-linux-incremental.yml
  build/pkgs/fflas_ffpack/spkg-configure.m4
  build/pkgs/givaro/spkg-configure.m4
  build/pkgs/linbox/spkg-configure.m4
Labels: c: packages: standard, s: positive review, p: critical / 2, c: build: configure

#37007 normalize projective points over (quotients of) Euclidean domains
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/projective/projective_point.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebraic geometry

#37014 Upgrade database_knotinfo to version 2024.2.1
  build/pkgs/database_knotinfo/checksums.ini
  build/pkgs/database_knotinfo/package-version.txt
  src/sage/databases/knotinfo_db.py
  src/sage/knots/all.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
Labels: s: positive review, c: packages: optional, c: algebraic topology

#37065 Installation guide: Use `.. envvar::` to define environment variables
  src/doc/en/installation/source.rst
Labels: s: positive review, c: documentation

#37073 `build/pkgs/free_fonts`: Fix fedora system package information
  build/pkgs/free_fonts/distros/fedora.txt
  build/pkgs/free_fonts/distros/nix.txt
  build/pkgs/free_fonts/distros/openbsd.txt
  build/pkgs/free_fonts/distros/repology.txt
  tox.ini
Labels: s: positive review, c: packages: optional, c: scripts

#37096 Fix `.multiplication_by_m` when m is not coprime to characteristic (#6413)
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_generic.py
Labels: p: major / 3, t: bug, s: positive review, c: elliptic curves

#37113 Define behaviour of < and > for fractional ideals in a quaternion algebra
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/modular/quatalg/brandt.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37143 special subs for fractions
  src/sage/rings/fraction_field_FpT.pyx
  src/sage/rings/fraction_field_element.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: commutative algebra, t: performance, sd125

#37148 Add class CircuitsMatroid
  src/doc/en/reference/matroids/index.rst
  src/sage/matroids/circuits_matroid.pxd
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/constructor.py
  src/sage/matroids/database_collections.py
  src/sage/matroids/database_matroids.py
  src/sage/matroids/matroid.pyx
  src/sage/matroids/unpickling.pyx
Labels: t: enhancement, s: positive review, c: matroid theory

#37170 Total refactor of `any_root()` to solve issue in characteristic two and clean up the code
  src/sage/rings/finite_rings/conway_polynomials.py
  src/sage/rings/finite_rings/hom_finite_field.pyx
  src/sage/rings/finite_rings/hom_finite_field_givaro.pyx
  src/sage/rings/finite_rings/homset.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_quotient_ring_element.py
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/ell_field.py
Labels: p: major / 3, t: bug, t: enhancement, s: positive review, c: algebra

#37182 Implement Auslander-Reiten quivers
  src/doc/en/reference/quivers/index.rst
  src/sage/graphs/digraph.py
  src/sage/quivers/ar_quiver.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics, c: algebra

#37185 Fix `sage_setup.clean` doctest
  src/sage/tests/books/__init__.py
Labels: s: positive review, p: blocker / 1

#36171 Implement Chevalley-Eilenberg complexes with module coefficients
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: t: enhancement, s: positive review, c: algebra

#36805 fast path for Vélu isogenies with a single kernel generator
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#36915 `configure.ac`: Remove tests for outdated platforms
  build/bin/testcc.sh
  build/bin/testcxx.sh
  build/pkgs/gfortran/spkg-configure.m4
  build/pkgs/gmp/spkg-install.in
  build/pkgs/lie/spkg-install.in
  build/pkgs/m4ri/spkg-install.in
  build/pkgs/m4rie/spkg-install.in
  build/pkgs/openblas/spkg-configure.m4
  build/pkgs/openssl/spkg-configure.m4
  build/pkgs/python3/spkg-build.in
  build/pkgs/r/spkg-configure.m4
  build/pkgs/rubiks/spkg-install.in
  configure.ac
  m4/sage_check_osx_supported.m4
Labels: s: positive review, c: build: configure, t: refactoring

#34976 compute isomorphisms between quaternion orders
  src/doc/en/reference/references/index.rst
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/algebras/quatalg/quaternion_algebra_element.pyx
  src/sage/rings/morphism.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#35503 add order_from_multiple() to sage.groups.all
  src/sage/groups/all.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: group theory

#37318 Allowing HeckeAlgebraSymmetricGroupT to accept elements of SymmetricGroup(n) as input
  src/sage/combinat/symmetric_group_algebra.py
Labels: t: enhancement, s: positive review, c: algebra

#37324 Basis completion for matrices over univariate polynomials
  src/doc/en/reference/references/index.rst
  src/sage/matrix/matrix_polynomial_dense.pyx
Labels: t: feature, s: positive review, c: linear algebra, c: commutative algebra, sd125

#37328 remove "known bug" marker for #6413 from doctest
  src/sage/schemes/elliptic_curves/hom_scalar.py
Labels: s: positive review, p: trivial / 5, t: tests, c: elliptic curves

#37329 add optional order= argument to .log() method for PARI finite-field elements
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: finite rings

#37333 fixing ruff UP037 (about type annotation)
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/modular/etaproducts.py
Labels: s: positive review, t: refactoring

#37338 Speedup database_matroids.py tests
  src/sage/matroids/database_matroids.py
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/matroid.pyx
Labels: s: positive review, t: performance, c: matroid theory

#37339 Removed whitespaces in `ncsym.py`
  src/sage/combinat/ncsym/ncsym.py
Labels: s: positive review, p: blocker / 1

#37341 Avoid algebra in polynomials
  src/sage/categories/commutative_rings.py
  src/sage/categories/rings.py
  src/sage/graphs/chrompoly.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/ring.pyx
  src/sage/structure/element.pyx
  src/sage/tests/books/computational-mathematics-with-sagemath/polynomes_doctest.py
Labels: s: positive review, c: commutative algebra

#37342 remove some old deprecations in functional.py
  src/sage/misc/all.py
  src/sage/misc/functional.py
Labels: s: positive review, p: trivial / 5, t: refactoring

#37350 `sage -package dependencies`
  build/bin/sage-spkg-info
  build/pkgs/giac/dependencies
  build/pkgs/giac/dependencies_optional
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
  build/sage_bootstrap/package.py
Labels: s: positive review, c: scripts

#37352 `sage --package create`: When re-creating with a different source type, clean up
  build/sage_bootstrap/creator.py
  src/doc/en/developer/packaging.rst
Labels: s: positive review, c: scripts

#37354 Allow submodule construction of a free module over a ring
  src/sage/modules/submodule.py
Labels: t: enhancement, s: positive review, c: algebra

#37355 less usage of method .is_commutative
  src/sage/combinat/descent_algebra.py
  src/sage/combinat/sf/sfa.py
  src/sage/modules/free_module.py
  src/sage/modules/free_quadratic_module.py
Labels: s: positive review, c: commutative algebra

#37360 Fix doctest for `multiplication_by_m`
  src/sage/schemes/elliptic_curves/ell_generic.py
Labels: t: bug, s: positive review, p: trivial / 5, c: elliptic curves

#37366 use Parent in skew polynomials
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
Labels: s: positive review, c: algebra

#37367 improve random sampling of quotient-ring elements
  src/sage/rings/quotient_ring.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#37375 Speed up square matrix times vector over GF(2)
  src/sage/matrix/matrix_mod2_dense.pyx
Labels: s: positive review, c: linear algebra, t: performance, c: finite rings

#37376 src/sage/rings/polynomial: Link to spkg page by label
  src/sage/rings/polynomial/msolve.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review, c: documentation, p: trivial / 5

#37385 Remove some last traces of Trac
  .gitpod-setup-trac-remote.sh
  CONTRIBUTING.md
  Makefile
  build/bin/sage-bootstrap-python
  build/bin/sage-build-env
  build/bin/sage-dist-helpers
  build/bin/sage-pip-install
  build/bin/sage-spkg
  build/make/Makefile.in
  build/make/install
  build/pkgs/_prereq/distros/opensuse.txt
  build/pkgs/brial/spkg-configure.m4
  build/pkgs/ccache/spkg-install.in
  build/pkgs/ecl/spkg-install.in
  build/pkgs/ecm/spkg-install.in
  build/pkgs/fplll/spkg-configure.m4
  build/pkgs/fplll/spkg-install.in
  build/pkgs/fricas/spkg-install.in
  build/pkgs/gcc/set-library-path
  build/pkgs/gcc/spkg-configure.m4
  build/pkgs/gf2x/spkg-install.in
  build/pkgs/gfortran/spkg-configure.m4
  build/pkgs/libffi/patches/libffi-3.2.1-disable-multi-os-directory.patch
  build/pkgs/libffi/spkg-install.in
  build/pkgs/libgd/spkg-configure.m4
  build/pkgs/matplotlib/distros/conda.txt
  build/pkgs/matplotlib/install-requires.txt
  build/pkgs/maxima/SPKG.rst
  build/pkgs/maxima/spkg-install.in
  build/pkgs/mpfi/spkg-install.in
  build/pkgs/openssl/spkg-configure.m4
  build/pkgs/openssl/spkg-install.in
  build/pkgs/packaging/install-requires.txt
  build/pkgs/pkgconf/spkg-postinst.in
  build/pkgs/planarity/spkg-install.in
  build/pkgs/pplpy/install-requires.txt
  build/pkgs/primecount/spkg-install.in
  build/pkgs/python3/spkg-build.in
  build/pkgs/python3/spkg-configure.m4
  build/pkgs/sagelib/spkg-install.in
  build/pkgs/sqlite/spkg-install.in
  build/pkgs/xz/spkg-configure.m4
  build/pkgs/zeromq/spkg-configure.m4
  build/pkgs/zlib/spkg-install.in
  build/sage_bootstrap/tarball.py
  configure.ac
  m4/sage_spkg_collect.m4
  sage
Labels: s: positive review, c: documentation, c: scripts

#37397 fix some ruff suggestions in cluster_algebra_quiver
  src/sage/combinat/cluster_algebra_quiver/cluster_seed.py
  src/sage/combinat/cluster_algebra_quiver/mutation_class.py
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/combinat/cluster_algebra_quiver/quiver_mutation_type.py
Labels: s: positive review, c: combinatorics

#37398 fix `relabel` for permutation groups
  src/sage/graphs/generic_graph.py
Labels: t: bug, s: positive review, c: group theory, c: graph theory

#37405 links for errors in doc of groups
  src/sage/groups/additive_abelian/qmodnz_element.py
  src/sage/groups/affine_gps/affine_group.py
  src/sage/groups/affine_gps/euclidean_group.py
  src/sage/groups/artin.py
  src/sage/groups/braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/fqf_orthogonal.py
  src/sage/groups/libgap_mixin.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/groups/matrix_gps/matrix_group.py
  src/sage/groups/matrix_gps/matrix_group_gap.py
  src/sage/groups/pari_group.py
  src/sage/groups/perm_gps/symgp_conjugacy_class.py
Labels: s: positive review, c: documentation, c: group theory

#37089 Implemented order computation and identity checking for automorphisms of elliptic curves
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#37186 Update debian.txt for various Python packages
  build/bin/sage-spkg-info
  build/pkgs/_sagemath/SPKG.rst
  build/pkgs/_sagemath/distros/debian.txt
  build/pkgs/beautifulsoup4/distros/debian.txt
  build/pkgs/cython/distros/debian.txt
  build/pkgs/fastjsonschema/distros/debian.txt
  build/pkgs/hatch_fancy_pypi_readme/distros/debian.txt
  build/pkgs/hatch_vcs/distros/debian.txt
  build/pkgs/importlib_resources/distros/debian.txt
  build/pkgs/ipykernel/distros/debian.txt
  build/pkgs/rpy2/distros/debian.txt
  build/pkgs/setuptools_scm/distros/debian.txt
  build/pkgs/sphinxcontrib_websupport/distros/debian.txt
  build/pkgs/tinycss2/distros/debian.txt
Labels: c: packages: standard, s: positive review

#37206 Various edits of developer guide
  src/doc/en/developer/portability_testing.rst
  src/doc/en/developer/tools.rst
  src/doc/en/developer/workspace.rst
Labels: s: positive review, c: documentation

#37221 Added the alt nu-tamari lattices
  src/sage/combinat/nu_tamari_lattice.py
Labels: s: positive review, c: combinatorics, sd125

#37227 build/pkgs/ipython/dependencies: Add matplotlib_inline
  build/pkgs/ipython/dependencies
Labels: t: bug, c: packages: standard, s: positive review

#37242 Improved algorithm choice for isogeny computation
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_composite.py
  src/sage/schemes/elliptic_curves/hom_velusqrt.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#37260 extend `all_paths_iterator` and `all_simple_paths` to Graph
  src/sage/graphs/digraph.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/path_enumeration.pyx
Labels: s: positive review, c: graph theory

#37268 Allow custom degree in `random_element` of polynomial quotient ring
  src/sage/rings/polynomial/polynomial_quotient_ring.py
Labels: p: minor / 4, s: positive review, c: commutative algebra

#37273 large pep8 cleanup in interfaces
  src/sage/interfaces/abc.py
  src/sage/interfaces/all.py
  src/sage/interfaces/chomp.py
  src/sage/interfaces/four_ti_2.py
  src/sage/interfaces/gap_workspace.py
  src/sage/interfaces/gfan.py
  src/sage/interfaces/gnuplot.py
  src/sage/interfaces/gp.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/magma.py
  src/sage/interfaces/magma_free.py
  src/sage/interfaces/matlab.py
  src/sage/interfaces/maxima.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/mupad.py
  src/sage/interfaces/mwrank.py
  src/sage/interfaces/octave.py
  src/sage/interfaces/polymake.py
  src/sage/interfaces/quit.py
  src/sage/interfaces/r.py
  src/sage/interfaces/rubik.py
  src/sage/interfaces/sage0.py
  src/sage/interfaces/scilab.py
  src/sage/interfaces/tests.py
  src/sage/interfaces/tides.py
Labels: s: positive review, c: interfaces

#37281 details in Zariski-Van-Kampen
  src/sage/schemes/curves/zariski_vankampen.py
Labels: p: minor / 4, s: positive review, c: algebraic geometry, t: refactoring

#37283 Fix RegularSequence.subsequence for zero sequence
  src/sage/combinat/regular_sequence.py
Labels: t: bug, s: positive review, c: combinatorics, c: finite state machines

#37286 sagemath-standard: fix manifest
  pkgs/sagemath-standard/setup.py
  src/MANIFEST.in
Labels: s: positive review, c: distribution

#37299 use parent in quaternions
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/categories/algebras.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: algebra, t: refactoring

#37302 use Parent instead of Algebra in finite_gca
  src/sage/algebras/finite_gca.py
Labels: s: positive review, t: refactoring

#37303 use Parent in Weyl algebra
  src/sage/algebras/weyl_algebra.py
  src/sage/structure/category_object.pyx
Labels: s: positive review, c: algebra, t: refactoring

#37306 Fix random test failures in `number_field_element_quadratic`
  src/sage/rings/number_field/number_field_element_quadratic.pyx
Labels: t: bug, p: minor / 4, s: positive review, c: number fields

#37311 Add tips for choosing an exception in developer guide
  src/doc/en/developer/coding_in_python.rst
Labels: s: positive review, c: documentation

#37313 Fix package install instructions in "Numerical Sage" tutorial
  src/doc/en/thematic_tutorials/numerical_sage/mpi4py.rst
Labels: p: minor / 4, s: positive review, c: documentation

#37316 use CommutativeRing in ring_extension
  src/sage/rings/ring_extension.pxd
  src/sage/rings/ring_extension.pyx
Labels: p: major / 3, s: positive review, c: commutative algebra, t: refactoring

#36587 Created functions to generate random k-tree and partial k-tree graphs
  src/sage/graphs/generators/random.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory

#36602 Tidy PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s: positive review

#36694 CI conda: On `pull_request`, only run 1 macOS job and 1 Linux job
  .github/workflows/ci-conda.yml
Labels: s: positive review, p: critical / 2, c: scripts, disputed

#36988 Adding support for sums, intersection, and equality of SubmodulesWithBasis
  src/sage/categories/modules_with_basis.py
  src/sage/modules/with_basis/subquotient.py
Labels: p: major / 3, t: enhancement, s: positive review, c: linear algebra, c: categories

#35103 SCIPBackend: Faster copy, remove_constraint methods
  src/sage/numerical/backends/generic_backend.pyx
  src/sage/numerical/backends/scip_backend.pyx
Labels: s: positive review, c: packages: optional, c: linear programming

#37470 src/sage_docbuild/ext/sage_autodoc.py: Fix linter failure
  src/sage_docbuild/ext/sage_autodoc.py
Labels: s: positive review, p: blocker / 1

#37261 `README.md`: Improve PyPI install instructions
  README.md
  pkgs/sage-conf/_sage_conf/__main__.py
  pkgs/sage-conf/sage_conf.py
Labels: s: positive review, c: documentation, p: blocker / 1, c: distribution

#37319 `build/pkgs/meson`: Update to 1.3.1, require >= 1.2.3 for Python 3.12 support, reject meson installed in inaccessible user schemes
  build/pkgs/meson/checksums.ini
  build/pkgs/meson/package-version.txt
  build/pkgs/meson/spkg-configure.m4
  build/pkgs/meson/spkg-install.in
  m4/sage_python_package_check.m4
Labels: t: bug, c: packages: standard, s: positive review, p: blocker / 1, c: build: configure

#37443 Fix bugs and regression in performance of `any_root()`
  src/sage/rings/finite_rings/conway_polynomials.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/schemes/elliptic_curves/cm.py
Labels: s: positive review, p: blocker / 1, c: algebra

#37177 `sage -t`: Fix handling of `--probe all` broken by #36989
  src/sage/doctest/parsing.py
Labels: s: positive review, c: doctest framework, p: blocker / 1

#37178 `sage.features.threejs`: Fix modularization regression after #37024
  src/sage/features/threejs.py
Labels: c: packages: standard, s: positive review, p: blocker / 1

#37237 CI macOS: Fix failure with macos-13-homebrew, add tests on M1 runners, add timeouts
  .github/workflows/ci-macos.yml
  .github/workflows/macos.yml
  build/pkgs/dsdp/spkg-install.in
  src/bin/sage-env
  tox.ini
Labels: s: positive review, p: blocker / 1, c: scripts
