Repository sagemath/sage, pull requests merged in 2024-05, with the labels that each got.

#37904 Change `SetSystem` representation
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/set_system.pyx
  src/sage/matroids/union_matroid.pyx
  src/sage/matroids/utilities.py
Labels: t: enhancement, s: positive review, c: matroid theory

#37911 Fix overflow in hypergeometric trace
  src/sage/modular/hypergeometric_misc.pyx
  src/sage/modular/hypergeometric_motive.py
Labels: s: positive review

#37681 Quaternion Ideal Pushforwards and Pullbacks
  src/doc/en/reference/references/index.rst
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: t: feature, s: positive review, c: algebra

#37692 `matrix`, `Graph.incidence_matrix`, `LinearMatroid.representation`: Support constructing `Hom(CombinatorialFreeModule)` elements
  src/sage/categories/finite_dimensional_modules_with_basis.py
  src/sage/graphs/generic_graph.py
  src/sage/matrix/args.pxd
  src/sage/matrix/args.pyx
  src/sage/matrix/constructor.pyx
  src/sage/matrix/matrix_space.py
  src/sage/matroids/linear_matroid.pyx
  src/sage/modules/free_module.py
  src/sage/modules/matrix_morphism.py
Labels: s: positive review, c: linear algebra, c: graph theory, c: matroid theory

#37722 Remove `CombinatorialClass`
  src/sage/categories/enumerated_sets.py
  src/sage/combinat/all.py
  src/sage/combinat/cartesian_product.py
  src/sage/combinat/combinat.py
  src/sage/combinat/crystals/tensor_product.py
  src/sage/combinat/free_module.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/species/structure.py
  src/sage/sets/family.pyx
  src/sage/sets/image_set.py
Labels: s: positive review, c: combinatorics, t: refactoring

#37738 CI Build&Test: Show segfaults using GitHub annotations
  src/sage/doctest/reporting.py
Labels: s: positive review, c: scripts

#37797 fix the category of quasi-modular form rings
  src/sage/modular/quasimodform/ring.py
Labels: t: bug, s: positive review, c: modular forms

#37808 Removed non-working and utterly old @rename_keyword in farey_symbol.pyx
  src/sage/modular/arithgroup/farey_symbol.pyx
Labels: s: positive review, t: refactoring

#37822 Fix bug in TensorField.apply_map
  src/sage/manifolds/differentiable/tensorfield.py
Labels: p: major / 3, t: bug, s: positive review, c: manifolds

#37823 Fix LaTeX output of FreeModuleTensor.display_comp
  src/sage/tensor/modules/free_module_tensor.py
Labels: p: major / 3, t: bug, s: positive review, c: linear algebra, good first issue, c: manifolds

#37825 `FiniteRankFreeModuleMorphism.display`: Show matrix decorated with basis element names
  src/sage/manifolds/differentiable/diff_map.py
  src/sage/tensor/modules/free_module_morphism.py
Labels: s: positive review, c: linear algebra

#37827 `sage.tensor`: Tiny doc fixes
  src/sage/tensor/modules/ext_pow_free_module.py
  src/sage/tensor/modules/free_module_basis.py
Labels: s: positive review, c: documentation, c: linear algebra

#37829 src/sage/manifolds/differentiable: Docstring/doctest edits
  src/sage/manifolds/differentiable/affine_connection.py
  src/sage/manifolds/differentiable/bundle_connection.py
  src/sage/manifolds/differentiable/differentiable_submanifold.py
  src/sage/manifolds/differentiable/multivectorfield.py
  src/sage/manifolds/differentiable/tangent_space.py
  src/sage/manifolds/differentiable/vector_bundle.py
Labels: s: positive review, c: documentation, p: trivial / 5, c: manifolds

#37833 `build/pkgs/{python3,setuptools}`: Update fedora distro info
  build/pkgs/python3/distros/fedora.txt
  build/pkgs/setuptools/distros/fedora.txt
Labels: s: positive review, c: build

#37835 Optimize `DisjointSet`
  src/sage/groups/perm_gps/partn_ref/data_structures.pxd
  src/sage/sets/disjoint_set.pxd
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review, c: combinatorics, t: performance, c: cython

#37836 fricas/do not get inputform twice
  src/sage/interfaces/fricas.py
Labels: s: positive review, c: interfaces: optional

#37841 `.ci/write-dockerfile.sh`: Move here from build/bin/
  .ci/write-dockerfile.sh
  .github/workflows/docker.yml
  src/doc/en/developer/portability_testing.rst
  tox.ini
Labels: p: minor / 4, s: positive review, c: scripts

#37851 Fix issue 37587 regarding the Link class plot method
  src/sage/knots/link.py
Labels: t: bug, s: positive review, c: graphics, c: algebraic topology

#37853 Work around inconsistent iteration in `multi_polynomial_sequence.py`
  src/sage/rings/polynomial/multi_polynomial_sequence.py
Labels: t: bug, p: minor / 4, s: positive review, c: commutative algebra, c: finite rings

#37856 `sage.misc.dist`: Remove; deprecated in #30207 (2022)
  src/doc/en/reference/misc/index.rst
  src/sage/misc/all.py
  src/sage/misc/dist.py
Labels: s: positive review, t: refactoring

#37868 `sage.misc.misc`: Remove deprecated code
  src/sage/misc/misc.py
Labels: s: positive review, t: refactoring

#37870 `sage.ext`: Remove deprecated code
  src/sage/ext/fast_eval.pyx
  src/sage/ext/memory_allocator.pxd
  src/sage/ext/memory_allocator.pyx
Labels: s: positive review, t: refactoring

#37872 sage.{topology,homology}: Remove deprecated chomp interface
  src/doc/en/developer/coding_basics.rst
  src/doc/en/reference/homology/index.rst
  src/sage/homology/chain_complex.py
  src/sage/homology/tests.py
  src/sage/interfaces/chomp.py
  src/sage/topology/cubical_complex.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review, c: algebraic topology, t: refactoring

#37882 eclib: fix doctests after 20240408 update
  src/sage/libs/eclib/interface.py
  src/sage/libs/eclib/mwrank.pyx
Labels: s: positive review

#37883 gap: don't use deprecated LaTeX() and LaTeXObj()
  src/sage/groups/libgap_wrapper.pyx
  src/sage/interfaces/gap.py
Labels: c: packages: standard, s: positive review

#37492 make sagelib work with singular>=4.3.2.p15 (future 4.4)
  src/sage/interfaces/singular.py
  src/sage/libs/singular/decl.pxd
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/libs/singular/singular.pxd
  src/sage/libs/singular/singular.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/term_order.py
Labels: s: positive review

#37693 Implement the hypercenter and upper central series for finite dimensional Lie algebras
  src/sage/algebras/lie_algebras/quotient.py
  src/sage/algebras/lie_algebras/subalgebra.py
  src/sage/categories/examples/finite_dimensional_lie_algebras_with_basis.py
  src/sage/categories/examples/lie_algebras.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: t: bug, t: enhancement, s: positive review, c: algebra

#37715 `sage.{calculus,functions,numerical,symbolic}`: Docstring/doctest cosmetics, `# needs`
  src/sage/calculus/functional.py
  src/sage/calculus/interpolators.pyx
  src/sage/calculus/riemann.pyx
  src/sage/calculus/transforms/dft.py
  src/sage/calculus/transforms/fft.pyx
  src/sage/functions/error.py
  src/sage/functions/exp_integral.py
  src/sage/functions/gamma.py
  src/sage/functions/generalized.py
  src/sage/functions/hyperbolic.py
  src/sage/functions/hypergeometric.py
  src/sage/functions/log.py
  src/sage/functions/orthogonal_polys.py
  src/sage/functions/other.py
  src/sage/functions/piecewise.py
  src/sage/functions/spike_function.py
  src/sage/functions/transcendental.py
  src/sage/functions/trig.py
  src/sage/functions/wigner.py
  src/sage/numerical/mip.pyx
  src/sage/numerical/optimize.py
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/function.pyx
  src/sage/symbolic/integration/integral.py
Labels: s: positive review, c: numerical, c: calculus, c: symbolics, t: refactoring

#36498 CI build, doc-build: Run containers explicitly, separate jobs for pyright, build, modularized tests, long tests
  .ci/create-changes-html.sh
  .ci/docker-exec-script.sh
  .github/workflows/build.yml
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/pyright.yml
  Makefile
  build/bin/write-dockerfile.sh
  build/pkgs/hatch_fancy_pypi_readme/checksums.ini
  build/pkgs/hatch_fancy_pypi_readme/package-version.txt
  build/pkgs/hatchling/checksums.ini
  build/pkgs/hatchling/package-version.txt
  build/pkgs/packaging/checksums.ini
  build/pkgs/packaging/package-version.txt
  build/pkgs/pip/checksums.ini
  build/pkgs/pip/package-version.txt
  build/pkgs/platformdirs/checksums.ini
  build/pkgs/platformdirs/package-version.txt
  build/pkgs/sagemath_objects/spkg-check
  build/pkgs/setuptools/checksums.ini
  build/pkgs/setuptools/package-version.txt
  build/pkgs/trove_classifiers/checksums.ini
  build/pkgs/trove_classifiers/package-version.txt
  build/pkgs/wheel/checksums.ini
  build/pkgs/wheel/package-version.txt
  pkgs/sage-conf_pypi/tox.ini
  pkgs/sage-docbuild/tox.ini
  pkgs/sage-setup/tox.ini
  pkgs/sagemath-categories/known-test-failures.json
  pkgs/sagemath-categories/requirements-editable.txt.m4
  pkgs/sagemath-categories/tox.ini
  pkgs/sagemath-environment/requirements-editable.txt.m4
  pkgs/sagemath-environment/tox.ini
  pkgs/sagemath-objects/requirements-editable.txt.m4
  pkgs/sagemath-objects/tox.ini
  pkgs/sagemath-repl/pyproject.toml.m4
  pkgs/sagemath-repl/requirements-editable.txt.m4
  pkgs/sagemath-repl/tox.ini
  pkgs/sagemath-standard/tox.ini
  src/sage/doctest/reporting.py
  src/sage/features/__init__.py
  src/sage/misc/package.py
  src/tox.ini
  tox.ini
Labels: s: positive review, p: critical / 2, c: documentation, c: scripts

#36768 Retrieve more information of fundamental groups of plane curves
  src/doc/en/reference/curves/index.rst
  src/doc/en/reference/discrete_geometry/index.rst
  src/sage/geometry/all.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/geometry/hyperplane_arrangement/ordered_arrangement.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/all.py
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/curves/zariski_vankampen.py
Labels: t: enhancement, s: positive review, c: algebraic geometry, c: algebraic topology

#36982 Make pyproject.toml the source for build dependencies
  .gitignore
  Makefile
  bootstrap
  build/bin/sage-get-system-packages
  build/pkgs/cypari/version_requirements.txt
  build/pkgs/cysignals/version_requirements.txt
  build/pkgs/cython/version_requirements.txt
  build/pkgs/gmpy2/version_requirements.txt
  build/pkgs/jupyter_core/version_requirements.txt
  build/pkgs/memory_allocator/version_requirements.txt
  build/pkgs/numpy/version_requirements.txt
  build/pkgs/pkgconfig/version_requirements.txt
  build/pkgs/pplpy/version_requirements.txt
  build/pkgs/setuptools/version_requirements.txt
  build/pkgs/wheel/version_requirements.txt
  pkgs/sagemath-standard/pyproject.toml.m4
  src/doc/en/developer/packaging.rst
  src/pyproject.toml
  src/pyproject.toml.m4
Labels: s: positive review, c: build, disputed

#37041 update FriCAS to 1.3.10, allow building with sbcl
  build/bin/sage-build-env-config.in
  build/pkgs/fricas/checksums.ini
  build/pkgs/fricas/package-version.txt
  build/pkgs/fricas/patches/extdecls.patch
  build/pkgs/fricas/patches/macos_lisp.patch
  build/pkgs/fricas/spkg-install.in
  build/pkgs/sbcl/SPKG.rst
  build/pkgs/sbcl/distros/alpine.txt
  build/pkgs/sbcl/distros/arch.txt
  build/pkgs/sbcl/distros/conda.txt
  build/pkgs/sbcl/distros/cygwin.txt
  build/pkgs/sbcl/distros/debian.txt
  build/pkgs/sbcl/distros/fedora.txt
  build/pkgs/sbcl/distros/freebsd.txt
  build/pkgs/sbcl/distros/gentoo.txt
  build/pkgs/sbcl/distros/homebrew.txt
  build/pkgs/sbcl/distros/macports.txt
  build/pkgs/sbcl/distros/nix.txt
  build/pkgs/sbcl/distros/openbsd.txt
  build/pkgs/sbcl/distros/opensuse.txt
  build/pkgs/sbcl/distros/repology.txt
  build/pkgs/sbcl/distros/void.txt
  build/pkgs/sbcl/math
  build/pkgs/sbcl/spkg-configure.m4
  build/pkgs/sbcl/type
  src/sage/interfaces/fricas.py
  src/sage/symbolic/expression_conversions.py
Labels: s: positive review, c: packages: optional

#37057 deprecated functions is_Cone, is_Polyhedron, is_LatticePolytope
  src/sage/geometry/cone.py
  src/sage/geometry/fan.py
  src/sage/geometry/hyperplane_arrangement/hyperplane.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/newton_polygon.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/geometry/polyhedron/base.py
  src/sage/geometry/polyhedron/parent.py
  src/sage/schemes/toric/variety.py
Labels: s: positive review, c: geometry, t: refactoring

#37099 GH Actions: Build platform-independent wheels of sagemath-environment, sage-setup, sage-sws2rst for PyPI
  .github/workflows/dist.yml
  build/make/Makefile.in
Labels: s: positive review, c: scripts, c: distribution

#35618 Use `pypa/build` instead of `pip wheel`
  build/bin/sage-dist-helpers
  build/make/Makefile.in
  build/pkgs/editables/checksums.ini
  build/pkgs/editables/dependencies
  build/pkgs/editables/spkg-install.in
  build/pkgs/importlib_metadata/dependencies
  build/pkgs/pyproject_hooks/dependencies
  build/pkgs/python_build/dependencies
  build/pkgs/uri_template/dependencies
Labels: s: positive review, c: build

#37839 Cythonize `GraphicMatroid`
  src/sage/matroids/graphic_matroid.pxd
  src/sage/matroids/graphic_matroid.pyx
Labels: s: positive review, t: performance, c: cython, c: matroid theory

#37854 Maximal angles between convex cones
  src/doc/en/reference/discrete_geometry/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/geometry/cone.py
  src/sage/geometry/cone_critical_angles.py
Labels: s: positive review, c: geometry

#37859 Implement the ladder idempotents of the symmetric group algebra
  src/doc/en/reference/references/index.rst
  src/sage/combinat/partition.py
  src/sage/combinat/symmetric_group_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics, c: algebra, v: small

#37867 `sage.misc.sageinspect`: Remove deprecated `loadable_module_extension`
  src/sage/misc/sageinspect.py
Labels: s: positive review, t: refactoring

#37869 `sage.geometry.polyhedron`: Remove deprecated code
  src/sage/geometry/polyhedron/backend_cdd.py
  src/sage/geometry/polyhedron/base3.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
Labels: s: positive review, c: geometry, t: refactoring, v: small

#37878 Run sage doc server for jupyterlab
  src/bin/sage-notebook
  src/sage/env.py
  src/sage/repl/ipython_kernel/kernel.py
Labels: s: positive review, p: critical / 2, c: documentation, v: small

#37881 Implement hypergeometric Euler factors for tame primes
  src/sage/modular/hypergeometric_motive.py
Labels: t: enhancement, s: positive review, c: number theory

#37894 sagemath-standard: some fixes in build dependencies
  build/pkgs/networkx/version_requirements.txt
  src/pyproject.toml
Labels: s: positive review, c: distribution

#37896 Deprecate `is_FreeAlgebra`, `is_QuaternionAlgebra`, `is_SymmetricFunctionAlgebra`
  src/sage/algebras/free_algebra.py
  src/sage/algebras/free_algebra_quotient.py
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/combinat/sf/sfa.py
Labels: s: positive review, t: refactoring, v: minimal

#37897 Deprecate `is_Monoid`, `is_FreeMonoid`, `is_FreeAbelianMonoid`
  src/sage/monoids/free_abelian_monoid.py
  src/sage/monoids/free_monoid.py
  src/sage/monoids/monoid.py
Labels: s: positive review, c: combinatorics, t: refactoring

#37898 Deprecate `is_AbelianGroup`, `is_DualAbelianGroup`, `is_MatrixGroup`
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/dual_abelian_group.py
  src/sage/groups/matrix_gps/matrix_group.py
  src/sage/matrix/matrix_space.py
  src/sage/modular/arithgroup/congroup_generic.py
Labels: s: positive review, c: group theory, t: refactoring, v: minimal

#37914 `build/pkgs/python3`: Update to 3.11.8, remove Cygwin patches, remove pointless rpaths on macOS
  build/pkgs/python3/checksums.ini
  build/pkgs/python3/package-version.txt
  build/pkgs/python3/patches/2.6.5-FD_SETSIZE.patch
  build/pkgs/python3/patches/2.7.3-dylib.patch
  build/pkgs/python3/patches/3.2.6-no-enable-new-dtags.patch
  build/pkgs/python3/spkg-build.in
Labels: c: packages: standard, s: positive review

#37916 structure/coerce actions
  src/sage/categories/pushout.py
  src/sage/structure/coerce_actions.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: coercion

#37925 Fix slow substitution in piecewise symbolic function
  src/sage/functions/piecewise.py
Labels: p: minor / 4, s: positive review, t: performance, c: symbolics, v: minimal

#37929 `.gitignore`: Ignore `requirements-editable.txt` files
  .gitignore
Labels: t: bug, s: positive review, c: build

#37932 fix the linter
  src/sage/interfaces/singular.py
Labels: s: positive review, p: blocker / 1, p: CI Fix

#37938 Updates to linbox-1.7.0, givaro-4.2.0, fflas-ffpack-2.5.0
  build/pkgs/fflas_ffpack/checksums.ini
  build/pkgs/fflas_ffpack/package-version.txt
  build/pkgs/fflas_ffpack/patches/0001-Do-not-use-variable-names-B0-B1-to-avoid-clash-with-.patch
  build/pkgs/fflas_ffpack/patches/357.patch
  build/pkgs/fflas_ffpack/patches/fix-ksh-pkgconfig.patch
  build/pkgs/fflas_ffpack/spkg-configure.m4
  build/pkgs/givaro/checksums.ini
  build/pkgs/givaro/package-version.txt
  build/pkgs/givaro/patches/197.patch
  build/pkgs/givaro/patches/226.patch
  build/pkgs/givaro/patches/fix-ksh-pkgconfig.patch
  build/pkgs/givaro/patches/givaro-26932_recintvsflint_longlong.patch
  build/pkgs/givaro/spkg-configure.m4
  build/pkgs/linbox/checksums.ini
  build/pkgs/linbox/package-version.txt
  build/pkgs/linbox/patches/292.patch
  build/pkgs/linbox/patches/294.patch
  build/pkgs/linbox/patches/310-backport.patch
  build/pkgs/linbox/patches/fix-ksh-pkgconfig.patch
  build/pkgs/linbox/patches/linbox-pr-256.patch
  build/pkgs/linbox/patches/remove-linboxsage-libs-from-pc.patch
  build/pkgs/linbox/spkg-configure.m4
  build/pkgs/linbox/spkg-install.in
Labels: s: positive review, p: critical / 2

#37939 Fix incompatible pointer type assignment error in implicit_surface
  src/sage/plot/plot3d/implicit_surface.pyx
Labels: s: positive review

#37940 Support morphisms in `Matroid` constructor
  src/sage/matroids/constructor.py
Labels: t: feature, s: positive review, c: matroid theory, v: small

#37941 Revert cif fast inversion 84ab655
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/polynomial/binary_form_reduce.py
  src/sage/rings/qqbar.py
  src/sage/schemes/curves/zariski_vankampen.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/symbolic/expression_conversion_algebraic.py
Labels: c: basic arithmetic, t: bug, s: positive review, p: critical / 2, v: large

#37942 Graph constructors: Remove gratuitous nondeterminism
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_decompositions/modular_decomposition.py
  src/sage/graphs/graph_input.py
Labels: s: positive review, c: graph theory, v: small

#37947 various ruff suggestions fixed in schemes
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/curves/zariski_vankampen.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/isogeny_small_degree.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
  src/sage/schemes/product_projective/space.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
  src/sage/schemes/toric/divisor.py
  src/sage/schemes/toric/morphism.py
  src/sage/schemes/toric/points.py
  src/sage/schemes/toric/sheaf/constructor.py
Labels: s: positive review, t: refactoring

#37948 some ruff fixes in misc folder
  src/sage/misc/abstract_method.py
  src/sage/misc/call.py
  src/sage/misc/classgraph.py
  src/sage/misc/cython.py
  src/sage/misc/decorators.py
  src/sage/misc/dev_tools.py
  src/sage/misc/edit_module.py
  src/sage/misc/element_with_label.py
  src/sage/misc/explain_pickle.py
  src/sage/misc/flatten.py
  src/sage/misc/latex.py
  src/sage/misc/latex_standalone.py
  src/sage/misc/object_multiplexer.py
  src/sage/misc/package_dir.py
  src/sage/misc/replace_dot_all.py
  src/sage/misc/sage_input.py
  src/sage/misc/sage_timeit.py
  src/sage/misc/sage_unittest.py
  src/sage/misc/sagedoc.py
  src/sage/misc/sageinspect.py
  src/sage/misc/sphinxify.py
  src/sage/misc/superseded.py
  src/sage/misc/temporary_file.py
  src/sage/misc/test_class_pickling.py
  src/sage/misc/test_nested_class.py
Labels: s: positive review, t: refactoring

#37949 Adapt length check in `sage.databases.conway` in preparation for database update
  src/sage/databases/conway.py
Labels: t: enhancement, s: positive review, c: databases, v: minimal

#37950 CI: Handle the "p: CI Fix" label
  .ci/merge-fixes.sh
Labels: s: positive review, c: scripts

#37953 Fix trivial typo
  src/sage/rings/ideal.py
Labels: s: positive review, v: minimal

#37954 direct implementations of some cliques related methods in `sage/graphs/graph.py`
  src/sage/graphs/graph.py
Labels: t: enhancement, s: positive review, c: graph theory, t: performance

#37955 `Graph.{[weighted_]adjacency_matrix,kirchhoff_matrix}`: Support constructing `End(CombinatorialFreeModule)` elements
  src/sage/graphs/generic_graph.py
  src/sage/matrix/args.pyx
  src/sage/matrix/constructor.pyx
Labels: s: positive review, c: linear algebra, c: graph theory, v: moderate

#37956 faster implementation of method `sage.graphs.generators.families.BalancedTree`
  src/sage/graphs/generators/families.py
Labels: s: positive review, c: graph theory, t: performance

#37958 various ruff fixes in combinat
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/combinat/nu_dyck_word.py
  src/sage/combinat/partition.py
  src/sage/combinat/permutation.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/morphism.py
  src/sage/combinat/words/paths.py
  src/sage/combinat/words/suffix_trees.py
  src/sage/combinat/yang_baxter_graph.py
Labels: s: positive review, c: combinatorics, t: refactoring, v: large

#37965 some polishing for pbori (ruff and pep8 mostly)
  src/sage/rings/polynomial/pbori/blocks.py
  src/sage/rings/polynomial/pbori/cnf.py
  src/sage/rings/polynomial/pbori/gbcore.py
  src/sage/rings/polynomial/pbori/gbrefs.py
  src/sage/rings/polynomial/pbori/interpolate.py
  src/sage/rings/polynomial/pbori/interred.py
  src/sage/rings/polynomial/pbori/ll.py
  src/sage/rings/polynomial/pbori/nf.py
  src/sage/rings/polynomial/pbori/parallel.py
  src/sage/rings/polynomial/pbori/randompoly.py
  src/sage/rings/polynomial/pbori/rank.py
  src/sage/rings/polynomial/pbori/specialsets.py
  src/sage/rings/polynomial/pbori/statistics.py
Labels: s: positive review, c: commutative algebra, t: refactoring, v: moderate

#37967 Modify tests in `ell_point.py` to be more generic for Conway database update
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: s: positive review, c: elliptic curves, t: refactoring, v: minimal

#37500 `sage --package`, `sage-get-system-packages`: Support PURLs `pkg:pypi/DISTRO-NAME`, obtain dependencies of wheels from PyPI
  build/bin/sage-get-system-packages
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
  build/sage_bootstrap/creator.py
  build/sage_bootstrap/download/cmdline.py
  build/sage_bootstrap/download/mirror_list.py
  build/sage_bootstrap/expand_class.py
  build/sage_bootstrap/package.py
  build/sage_bootstrap/pypi.py
  build/sage_bootstrap/tarball.py
  build/sage_bootstrap/uninstall.py
  src/doc/en/developer/packaging.rst
Labels: s: positive review, c: build, c: scripts, v: moderate

#37584 build/pkgs/cython: Update to 3.0.10
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/package-version.txt
Labels: c: packages: standard, s: positive review

#37713 `sage.sets`: Doctest cosmetics
  src/sage/sets/recursively_enumerated_set.pyx
  src/sage/sets/set.py
  src/sage/sets/totally_ordered_finite_set.py
Labels: s: positive review, c: combinatorics, t: refactoring, v: minimal

#37716 `sage.{misc,structure}`: Doctest cosmetics
  src/sage/misc/binary_tree.pyx
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/converting_dict.py
  src/sage/misc/dev_tools.py
  src/sage/misc/flatten.py
  src/sage/misc/function_mangling.pyx
  src/sage/misc/functional.py
  src/sage/misc/lazy_import.pyx
  src/sage/misc/misc.py
  src/sage/misc/sagedoc.py
  src/sage/misc/sageinspect.py
  src/sage/misc/timing.py
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_actions.pyx
  src/sage/structure/element.pyx
  src/sage/structure/factorization.py
  src/sage/structure/global_options.py
  src/sage/structure/indexed_generators.py
  src/sage/structure/proof/proof.py
Labels: s: positive review, t: refactoring

#37719 Refactor ring categories
  pkgs/sagemath-categories/known-test-failures.json
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/doc/en/tutorial/tour_coercion.rst
  src/doc/fr/tutorial/tour_coercion.rst
  src/doc/ja/tutorial/tour_coercion.rst
  src/doc/pt/tutorial/tour_coercion.rst
  src/sage/algebras/clifford_algebra.py
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/categories/bimodules.py
  src/sage/categories/category.py
  src/sage/categories/category_types.py
  src/sage/categories/commutative_rings.py
  src/sage/categories/fields.py
  src/sage/categories/group_algebras.py
  src/sage/categories/homset.py
  src/sage/categories/integral_domains.py
  src/sage/categories/modules.py
  src/sage/categories/morphism.pyx
  src/sage/categories/noetherian_rings.py
  src/sage/categories/primer.py
  src/sage/categories/principal_ideal_domains.py
  src/sage/categories/rings.py
  src/sage/matrix/args.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_space.py
  src/sage/misc/c3_controlled.pyx
  src/sage/modules/free_module.py
  src/sage/modules/free_module_homspace.py
  src/sage/rings/function_field/order.py
  src/sage/rings/integer_ring.pxd
  src/sage/rings/integer_ring.pyx
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring_constructor.py
  src/sage/rings/qqbar.py
  src/sage/rings/ring.pxd
  src/sage/rings/ring.pyx
  src/sage/structure/category_object.pyx
  src/sage/tensor/modules/finite_rank_free_module.py
Labels: s: positive review, t: refactoring, v: large

#37737 Follow up #36741: improve code structure
  src/sage/doctest/control.py
  src/sage/doctest/external.py
  src/sage/features/__init__.py
  src/sage/features/join_feature.py
Labels: s: positive review, c: doctest framework, v: small

#37762 `dist.yml`: Download optional/experimental tarballs for GitHub Release assets
  .github/workflows/dist.yml
  Makefile
  build/pkgs/deprecation/spkg-configure.m4
  build/pkgs/pcre/distros/alpine.txt
  build/pkgs/pycygwin/spkg-configure.m4
  build/pkgs/setuptools_scm_git_archive/distros/alpine.txt
  build/pkgs/setuptools_scm_git_archive/distros/arch.txt
  build/pkgs/setuptools_scm_git_archive/distros/debian.txt
  build/pkgs/setuptools_scm_git_archive/distros/fedora.txt
  build/pkgs/setuptools_scm_git_archive/distros/freebsd.txt
  build/pkgs/setuptools_scm_git_archive/distros/gentoo.txt
  build/pkgs/setuptools_scm_git_archive/spkg-configure.m4
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
Labels: s: positive review, p: critical / 2, c: scripts, c: distribution, v: moderate

#37787 modernize coercion for Hecke algebras
  src/sage/modular/hecke/algebra.py
Labels: s: positive review, c: modular forms, t: refactoring

#37818 Bump up actions
  .github/workflows/build.yml
  .github/workflows/ci-conda.yml
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/dist.yml
  .github/workflows/lint.yml
Labels: s: positive review, dependencies

#37828 Fix FAQ on DOIs. Put "universal" DOI to CITATION.cff*
  CITATION.cff
  CITATION.cff.in
  src/doc/en/faq/faq-general.rst
Labels: s: positive review, c: documentation, v: minimal

#37831 `FreeModuleHomset`: Create subclass `FreeModuleEndset`, add element methods for invariants `det`, `charpoly`, `fcp`, etc.
  src/sage/tensor/modules/free_module_homset.py
  src/sage/tensor/modules/free_module_morphism.py
Labels: s: positive review, c: linear algebra

#37861 Fix segfault for Weil polynomials
  src/sage/rings/polynomial/weil/weil_polynomials.pyx
Labels: t: bug, s: positive review, p: critical / 2

#37249 gc: update to 8.2.6
  build/pkgs/gc/checksums.ini
  build/pkgs/gc/package-version.txt
Labels: c: packages: standard, s: positive review

#36269 `coefficients` for `QuasiModularFormsElement`
  src/sage/modular/quasimodform/element.py
Labels: s: positive review, c: modular forms

#37922 Deprecate `is_Category`, `is_Endset`, `is_Homset`, `is_Parent`, `is_RingHomset`, `is_SimplicialComplexHomset`
  src/sage/categories/category.py
  src/sage/categories/functor.pyx
  src/sage/categories/homset.py
  src/sage/categories/poor_man_map.py
  src/sage/modules/matrix_morphism.py
  src/sage/rings/asymptotic/misc.py
  src/sage/rings/homset.py
  src/sage/rings/ring.pyx
  src/sage/sets/image_set.py
  src/sage/structure/parent.pyx
  src/sage/topology/simplicial_complex_homset.py
Labels: s: positive review, c: categories, t: refactoring, v: small

#37926 `Makefile`, `.ci/write-dockerfile.sh`: Update for `src/pyproject.toml` after #36982
  .ci/retrofit-worktree.sh
  .ci/write-dockerfile.sh
  .gitignore
  Makefile
  src/sage/misc/package_dir.py
  tox.ini
Labels: s: positive review, p: blocker / 1, c: scripts, p: CI Fix, v: small

#37930 Work on `CircuitsMatroid`
  src/sage/algebras/orlik_solomon.py
  src/sage/algebras/orlik_terao.py
  src/sage/matroids/circuits_matroid.pxd
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/matroid.pyx
Labels: t: feature, s: positive review, t: performance, c: matroid theory

#37951 declare the last arg to GAP_CallFunc3Args volatile
  src/sage/libs/gap/element.pyx
Labels: t: bug, c: packages: standard, s: positive review, c: interfaces, p: critical / 2, v: minimal

#37952 Adding add_bigoh methods to lazy power/Laurent series and coercions to the finite precision implementations
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/lazy_series.py
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/power_series_ring.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: commutative algebra

#37959 `configure`: Fix "command not found" error after #36776
  build/pkgs/importlib_metadata/spkg-configure.m4
  build/pkgs/importlib_resources/spkg-configure.m4
  build/pkgs/typing_extensions/spkg-configure.m4
Labels: s: positive review, c: build: configure, v: small

#37972 Fix comparison for divisors of curves (and FormalSum commutativity)
  src/sage/schemes/generic/divisor.py
  src/sage/schemes/generic/divisor_group.py
  src/sage/structure/formal_sum.py
Labels: t: bug, s: positive review, c: algebraic geometry, c: coercion

#37973 Remove legacy direct installation of sagelib (`configure --disable-editable --disable-wheels`)
  build/pkgs/sagelib/spkg-install.in
  build/pkgs/sagemath_bliss/spkg-install.in
  build/pkgs/sagemath_coxeter3/spkg-install.in
  build/pkgs/sagemath_mcqd/spkg-install.in
  build/pkgs/sagemath_meataxe/spkg-install.in
  build/pkgs/sagemath_sirocco/spkg-install.in
  build/pkgs/sagemath_tdlib/spkg-install.in
  configure.ac
  pkgs/sagemath-standard/setup.py
  src/sage_setup/clean.py
  src/sage_setup/command/sage_install.py
  src/sage_setup/find.py
Labels: s: positive review, c: build, v: large

#37980 Fix order computation for linear groups GL(n, R) and SL(n, R)
  src/sage/groups/matrix_gps/linear.py
Labels: t: bug, s: positive review, c: group theory

#37984 Ruff details in algebras and categories
  src/sage/algebras/cluster_algebra.py
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/algebras/lie_algebras/heisenberg.py
  src/sage/algebras/lie_algebras/lie_algebra.py
  src/sage/algebras/lie_algebras/representation.py
  src/sage/algebras/lie_conformal_algebras/finitely_freely_generated_lca.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_element.py
  src/sage/algebras/splitting_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/categories/bimodules.py
  src/sage/categories/drinfeld_modules.py
  src/sage/categories/fields.py
  src/sage/categories/simplicial_sets.py
Labels: s: positive review, t: refactoring, v: moderate

#37986 `.github/workflows/docker_hub.yml`: Do not fail when there are no credentials
  .github/workflows/docker_hub.yml
Labels: p: minor / 4, s: positive review, c: scripts, c: docker, v: minimal

#37993 `sage.calculus.expr`: Split out from `sage.calculus.all`
  src/doc/en/reference/calculus/index.rst
  src/sage/calculus/all.py
  src/sage/calculus/expr.py
Labels: s: positive review, c: calculus, t: refactoring, v: large

#37994 some care for empty lines in pyx files (pep8 codes E30)
  src/sage/data_structures/bitset.pyx
  src/sage/data_structures/bounded_integer_sequences.pyx
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/ext/fast_callable.pyx
  src/sage/ext/memory.pyx
  src/sage/games/sudoku_backtrack.pyx
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/libs/eclib/mwrank.pyx
  src/sage/libs/glpk/error.pyx
  src/sage/plot/plot3d/base.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/plot/plot3d/transform.pyx
  src/sage/sets/recursively_enumerated_set.pyx
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_maps.pyx
  src/sage/structure/element.pyx
  src/sage/structure/factory.pyx
  src/sage/structure/list_clone.pyx
  src/sage/structure/list_clone_demo.pyx
  src/sage/structure/mutability.pyx
Labels: s: positive review

#37995 Remove interactive confirmation for installing experimental packages
  build/bin/sage-spkg
Labels: s: positive review, c: build, v: minimal

#38005 Fix Help menu breakdown in external jupyterlab case
  src/sage/repl/ipython_kernel/kernel.py
Labels: t: bug, c: user interface, s: positive review, v: minimal

#38013 `DualMatroid`: Add `is_valid` and `relabel` methods
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/database_matroids.py
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/set_system.pyx
  src/sage/matroids/utilities.py
Labels: t: enhancement, s: positive review, c: matroid theory

#38016 `Arch Linux`: Remove `libgiac` and rename `texlive-collection-luatex`
  build/pkgs/giac/distros/arch.txt
  build/pkgs/texlive_luatex/distros/arch.txt
Labels: s: positive review, c: distribution, v: minimal

#38018 move Frobenius and derivations to category of Commutative Rings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/commutative_rings.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: commutative algebra, c: categories, t: refactoring, v: large

#38020 Workaround for passing givaro library to linker on OSX
  build/pkgs/fflas_ffpack/spkg-install.in
  build/pkgs/linbox/patches/310-backport.patch
Labels: s: positive review, p: critical / 2, c: build, v: minimal

#38021 `build/pkgs/flint/spkg-configure.m4`: Reject broken FLINT package on homebrew
  build/pkgs/flint/spkg-configure.m4
Labels: s: positive review, p: critical / 2, c: build: configure, v: minimal

#38022 `sage.schemes`: Deprecate `is_...` functions
  src/bin/sage-fixdoctests
  src/sage/categories/schemes.py
  src/sage/dynamics/arithmetic_dynamics/affine_ds.py
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/dynamics/arithmetic_dynamics/generic_ds.py
  src/sage/dynamics/arithmetic_dynamics/product_projective_ds.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/schemes/affine/affine_homset.py
  src/sage/schemes/affine/affine_point.py
  src/sage/schemes/affine/affine_rational_point.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/berkovich/berkovich_space.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/constructor.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/height.py
  src/sage/schemes/elliptic_curves/jacobian.py
  src/sage/schemes/elliptic_curves/weierstrass_morphism.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/generic/ambient_space.py
  src/sage/schemes/generic/divisor.py
  src/sage/schemes/generic/divisor_group.py
  src/sage/schemes/generic/homset.py
  src/sage/schemes/generic/hypersurface.py
  src/sage/schemes/generic/scheme.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
  src/sage/schemes/hyperelliptic_curves/jacobian_homset.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/jacobians/abstract_jacobian.py
  src/sage/schemes/plane_quartics/quartic_constructor.py
  src/sage/schemes/plane_quartics/quartic_generic.py
  src/sage/schemes/product_projective/homset.py
  src/sage/schemes/product_projective/morphism.py
  src/sage/schemes/product_projective/point.py
  src/sage/schemes/product_projective/rational_point.py
  src/sage/schemes/product_projective/space.py
  src/sage/schemes/projective/projective_homset.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/schemes/projective/projective_point.py
  src/sage/schemes/projective/projective_rational_point.py
  src/sage/schemes/projective/projective_space.py
  src/sage/schemes/projective/projective_subscheme.py
  src/sage/schemes/toric/chow_group.py
  src/sage/schemes/toric/divisor.py
  src/sage/schemes/toric/fano_variety.py
  src/sage/schemes/toric/homset.py
  src/sage/schemes/toric/morphism.py
  src/sage/schemes/toric/sheaf/constructor.py
  src/sage/schemes/toric/sheaf/klyachko.py
  src/sage/schemes/toric/variety.py
Labels: s: positive review, c: algebraic geometry, t: refactoring, v: large

#38023 tox.ini (local-homebrew): Fix homebrew auto-update breakage
  tox.ini
Labels: p: minor / 4, s: positive review, c: scripts, v: minimal

#38027 Work on `FlatsMatroid`
  src/sage/matroids/advanced.py
  src/sage/matroids/constructor.py
  src/sage/matroids/flats_matroid.pxd
  src/sage/matroids/flats_matroid.pyx
Labels: t: feature, s: positive review, t: performance, c: matroid theory

#38033 Avoid conflict with macro `minor`
  src/sage/matroids/graphic_matroid.pyx
Labels: s: positive review, p: critical / 2, c: porting, v: minimal

#38036 cython-lint for schemes
  src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
  src/sage/schemes/elliptic_curves/period_lattice_region.pyx
  src/sage/schemes/hyperelliptic_curves/hypellfrob.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38038 cython-lint in quivers/
  src/sage/quivers/algebra_elements.pxi
  src/sage/quivers/paths.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38041 Installation Guide: Remove some distracting wikipedia links
  src/doc/en/installation/source.rst
Labels: p: minor / 4, s: positive review, c: documentation, v: minimal

#38042 assign names to constructed Hadamard matrices
  src/sage/combinat/matrices/hadamard_matrix.py
Labels: s: positive review, c: combinatorics, v: moderate

#38045 simplify handling of dead oeis sequences
  src/sage/databases/oeis.py
Labels: s: positive review, c: combinatorics, v: minimal

#38046 Fix wrong urls in changes.html
  .ci/create-changes-html.sh
Labels: s: positive review, p: critical / 2, p: CI Fix, v: minimal

#37690 using pathlib.Path to handle attached files
  src/sage/misc/remote_file.py
  src/sage/misc/reset.pyx
  src/sage/repl/attach.py
  src/sage/repl/load.py
  src/sage/repl/preparse.py
Labels: s: positive review, t: refactoring, v: moderate

#37840 `sage-logger`: Replace use of `/usr/bin/time` by bash keyword `time`
  build/bin/sage-logger
Labels: p: minor / 4, s: positive review, c: build, v: minimal

#37864 `sage.numerical.interactive_simplex_method`: Remove dependency on SR
  src/sage/numerical/interactive_simplex_method.py
Labels: s: positive review, c: linear programming, t: refactoring, v: minimal

#37873 `sage.libs.pynac`: Remove, deprecated in #32386 (2021)
  src/sage/libs/pynac/__init__.py
  src/sage/libs/pynac/pynac.py
Labels: s: positive review, t: refactoring, v: minimal

#37886 Remove pointless rpaths on macOS; make sage-env polite when run on systems with no toolchain
  build/make/Makefile.in
  build/pkgs/bliss/spkg-install.in
  build/pkgs/primecount/spkg-install.in
  build/pkgs/primecountpy/spkg-install.in
  build/pkgs/symengine_py/spkg-install.in
  src/bin/sage-env
Labels: c: packages: standard, s: positive review, c: build, v: small

#37895 `sage.modular.hecke`: Deprecate `is_Hecke...` functions
  src/sage/modular/hecke/algebra.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/element.py
  src/sage/modular/hecke/hecke_operator.py
  src/sage/modular/hecke/homspace.py
  src/sage/modular/hecke/module.py
  src/sage/modular/hecke/morphism.py
  src/sage/modular/hecke/submodule.py
Labels: s: positive review, c: modular forms, t: refactoring, v: moderate

#37924 Deprecate `is_FGP_Module`, `is_FilteredVectorSpace`, `is_FreeQuadraticModule`, `is_FreeModule`, `is_FreeModuleHomspace`, `is_MatrixSpace`, `is_Module`, `is_VectorSpace`, `is_VectorSpaceHomspace`
  src/sage/geometry/polyhedron/parent.py
  src/sage/groups/matrix_gps/finitely_generated.py
  src/sage/groups/matrix_gps/isometries.py
  src/sage/manifolds/subsets/pullback.py
  src/sage/matrix/action.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_space.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/submodule.py
  src/sage/modular/modsym/ambient.py
  src/sage/modules/fg_pid/fgp_module.py
  src/sage/modules/fg_pid/fgp_morphism.py
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/free_module.py
  src/sage/modules/free_module_homspace.py
  src/sage/modules/free_module_morphism.py
  src/sage/modules/free_quadratic_module.py
  src/sage/modules/module.pyx
  src/sage/modules/vector_space_homspace.py
  src/sage/modules/vector_space_morphism.py
  src/sage/numerical/linear_tensor.py
Labels: s: positive review, c: linear algebra, t: refactoring, v: moderate

#37415 make EllipticCurvePoint_field inherit from EllipticCurvePoint
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves, v: small

#37453 tox.ini: Add environments `ruff`, `ruff-minimal`; GH Actions: run `ruff-minimal`
  .github/workflows/lint.yml
  ruff.toml
  src/doc/en/developer/tools.rst
  src/tox.ini
  tox.ini
Labels: s: positive review, c: scripts, v: moderate

#36525 GH Actions: Fix build of macOS x86_64 wheels, build wheels for sagemath-{bliss,coxeter3,mcqd,tdlib} for PyPI
  .github/workflows/dist.yml
  build/pkgs/sagemath_tdlib/dependencies
  build/pkgs/sirocco/dependencies
  pkgs/sagemath-coxeter3/pyproject.toml.m4
  pkgs/sagemath-meataxe/pyproject.toml.m4
Labels: t: bug, s: positive review, p: critical / 2, c: distribution, v: minimal
