Repository sagemath/sage, pull requests merged in 2024-08, with the labels that each got.

#37010 `src/tox.ini` (coverage:run): Set `concurrency = multiprocessing,threads`
  src/tox.ini
Labels: s: positive review, c: scripts, v: minimal

#37657 fix quadratic_defect
  src/sage/rings/number_field/number_field.py
Labels: t: bug, s: positive review, c: number theory, c: number fields, v: minimal

#38175 Implemented generators for Staircase graph, Biwheel graph and Truncated biwheel graph
  src/doc/en/reference/references/index.rst
  src/sage/graphs/generators/families.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory, v: moderate, gsoc: 2024

#38289 Deprecate `is_FunctionFieldElement`, `is_FunctionFieldElement`
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/function_field.py
  src/sage/schemes/berkovich/berkovich_cp_element.py
Labels: s: positive review, t: refactoring, v: small

#38374 Add framework for key exchange schemes and Diffie-Hellman
  src/doc/en/reference/cryptography/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/crypto/all.py
  src/sage/crypto/key_exchange/all.py
  src/sage/crypto/key_exchange/catalog.py
  src/sage/crypto/key_exchange/diffie_hellman.py
  src/sage/crypto/key_exchange/key_exchange_scheme.py
Labels: s: positive review, c: cryptography, v: large

#38425 Make CHANGES.html more useful
  .ci/create-changes-html.sh
  .github/workflows/doc-build.yml
Labels: s: positive review, c: scripts

#38436 Correct canonical heights on non-integral models of elliptic curves
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: s: positive review, c: elliptic curves

#38443 fix E302 in pxi files
  src/sage/data_structures/list_of_pairs.pxd
  src/sage/libs/linkages/padics/unram_shared.pxi
  src/sage/libs/symmetrica/kostka.pxi
  src/sage/libs/symmetrica/part.pxi
  src/sage/libs/symmetrica/plet.pxi
  src/sage/libs/symmetrica/sab.pxi
  src/sage/libs/symmetrica/sb.pxi
  src/sage/libs/symmetrica/schur.pxi
  src/sage/libs/symmetrica/symmetrica.pxi
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/symbolic/getitem_impl.pxi
  src/sage/symbolic/pynac_impl.pxi
Labels: s: positive review

#38450 fix annotations in `sage/matrix/matrix2.pyx` and `sage/rings/integer.pyx`
  src/sage/matrix/matrix2.pyx
  src/sage/rings/integer.pyx
Labels: s: positive review, c: documentation, p: CI Fix

#38451 Add view/edit buttons to docs
  build/pkgs/furo/checksums.ini
  build/pkgs/furo/package-version.txt
  src/doc/ca/intro/conf.py
  src/doc/de/a_tour_of_sage/conf.py
  src/doc/de/thematische_anleitungen/conf.py
  src/doc/de/tutorial/conf.py
  src/doc/el/a_tour_of_sage/conf.py
  src/doc/en/a_tour_of_sage/conf.py
  src/doc/en/constructions/conf.py
  src/doc/en/developer/conf.py
  src/doc/en/faq/conf.py
  src/doc/en/installation/conf.py
  src/doc/en/prep/conf.py
  src/doc/en/reference/conf.py
  src/doc/en/reference/conf_sub.py
  src/doc/en/thematic_tutorials/conf.py
  src/doc/en/tutorial/conf.py
  src/doc/es/a_tour_of_sage/conf.py
  src/doc/es/tutorial/conf.py
  src/doc/fr/a_tour_of_sage/conf.py
  src/doc/fr/tutorial/conf.py
  src/doc/hu/a_tour_of_sage/conf.py
  src/doc/it/a_tour_of_sage/conf.py
  src/doc/it/faq/conf.py
  src/doc/it/tutorial/conf.py
  src/doc/ja/a_tour_of_sage/conf.py
  src/doc/ja/tutorial/conf.py
  src/doc/pt/a_tour_of_sage/conf.py
  src/doc/pt/tutorial/conf.py
  src/doc/ru/tutorial/conf.py
  src/doc/tr/a_tour_of_sage/conf.py
  src/sage_docbuild/conf.py
Labels: t: enhancement, c: packages: standard, s: positive review, c: documentation

#37372 Strength 2 Covering Array constructions
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/covering_array.py
  src/sage/combinat/designs/database.py
Labels: s: positive review, c: combinatorial designs, v: large

#38185 Simplify doc build process by removing empty directories locally
  src/doc/Makefile
  src/sage_docbuild/__main__.py
Labels: s: positive review, c: build, c: documentation, v: minimal

#38273 Update the deprecation policy
  src/doc/en/developer/coding_in_python.rst
Labels: s: positive review, c: documentation, v: small

#38296 Deprecate `is_SchemeMorphism`, `is_SchemeTopologicalPoint`
  src/sage/categories/schemes.py
  src/sage/schemes/affine/affine_point.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/generic/divisor.py
  src/sage/schemes/generic/glue.py
  src/sage/schemes/generic/morphism.py
  src/sage/schemes/generic/point.py
  src/sage/schemes/generic/scheme.py
  src/sage/schemes/hyperelliptic_curves/jacobian_homset.py
  src/sage/schemes/projective/projective_point.py
  src/sage/schemes/toric/morphism.py
Labels: s: positive review, c: algebraic geometry, t: refactoring, v: moderate

#38323 some fixes for ruff code C41 (about loops and iteration)
  src/sage/combinat/specht_module.py
  src/sage/env.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/schnyder.py
  src/sage/knots/link.py
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/rings/lazy_series.py
  src/sage/rings/number_field/galois_group.py
  src/sage/rings/valuation/augmented_valuation.py
  src/sage/tensor/modules/comp.py
  src/sage/tensor/modules/free_module_tensor.py
Labels: s: positive review, v: small

#38330 Lattes to curve function code commits for enhancement #38329
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
Labels: t: enhancement, s: positive review, c: dynamics, v: moderate, gsoc: 2024

#38331 use pkg-config to find msolve, otherwise try to run it
  build/pkgs/msolve/spkg-configure.m4
Labels: s: positive review, c: packages: optional, c: build: configure, v: minimal

#38347 support passing two base points to .log() for elliptic-curve points
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves, v: small

#38395 get rid of some sage-eval in gap3-related code
  src/sage/combinat/root_system/reflection_group_complex.py
  src/sage/combinat/root_system/reflection_group_element.pyx
  src/sage/combinat/root_system/reflection_group_real.py
Labels: s: positive review, c: combinatorics, t: refactoring, v: minimal

#38409 `xgcd` for multiple arguments
  src/sage/arith/misc.py
Labels: c: basic arithmetic, s: positive review, v: small

#38414 Properly check dimension in curve constructor
  src/doc/en/reference/references/index.rst
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/projective_curve.py
Labels: s: positive review, c: algebraic geometry, v: small

#38432 fix memory leak in is_planar
  src/sage/graphs/planarity.pyx
Labels: t: bug, s: positive review, c: graph theory

#38433 Make # abs tol compare over the complex numbers
  pkgs/sagemath-categories/known-test-failures.json
  src/sage/doctest/check_tolerance.py
  src/sage/doctest/control.py
  src/sage/doctest/marked_output.py
  src/sage/doctest/parsing.py
  src/sage/doctest/rif_tol.py
Labels: s: positive review, c: doctest framework

#38442 `build/pkgs/gcc`: Update to 13.3
  build/pkgs/gcc/checksums.ini
  build/pkgs/gcc/package-version.txt
  build/pkgs/gcc/patches/68057560ff1fc0fb2df38c2f9627a20c9a8da5c5.patch
  build/pkgs/gcc/patches/e95ab9e60ce1d9aa7751d79291133fd5af9209d7.patch
  build/pkgs/gcc/patches/gcc-13-homebrew.patch
  build/pkgs/gcc/patches/gcc-13.3.0-arm.patch
  build/pkgs/gcc/patches/gcc-xcode15-warnings.patch
Labels: c: packages: standard, s: positive review

#38444 Moving ideal methods to category of rings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/rings.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/ring.pxd
  src/sage/rings/ring.pyx
  src/sage/rings/tate_algebra.py
Labels: s: positive review, c: algebra, c: categories, t: refactoring

#38458 simplify conversion code in cubic Hecke
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
Labels: s: positive review, c: algebra

#38466 introduce half-angle transformations
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/expression_conversions.py
Labels: s: positive review, c: symbolics

#38470 `build/pkgs/furo`: Set lower bound
  build/pkgs/furo/version_requirements.txt
Labels: c: packages: standard, s: positive review, c: distribution

#38476 Include modular composition for polynomial rings over finite fields
  src/sage/libs/ntl/ZZ_pEX.pxd
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/rings/polynomial/polynomial_gf2x.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
Labels: p: minor / 4, s: positive review, c: commutative algebra, t: performance

#38479 Choose special name to avoid '@c' by singular's absFactorize
  src/sage/rings/qqbar.py
Labels: t: bug, s: positive review
