Repository sagemath/sage, pull requests merged in 2024-09, with the labels that each got.

#34962 set reverse=True by default in basis_for_quaternion_lattice()
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/modular/quatalg/brandt.py
  src/sage/schemes/elliptic_curves/heegner.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#36641 `build/pkgs/sympy`: Upgrade to 1.13.2
  build/pkgs/sympy/checksums.ini
  build/pkgs/sympy/package-version.txt
  src/sage/doctest/forker.py
  src/sage/functions/hypergeometric.py
  src/sage/typeset/ascii_art.py
Labels: c: packages: standard, s: positive review, v: large

#37204 upgrade shipped suitesparse components to 7.8.0
  build/pkgs/cmake/spkg-configure.m4
  build/pkgs/suitesparse/SPKG.rst
  build/pkgs/suitesparse/checksums.ini
  build/pkgs/suitesparse/dependencies
  build/pkgs/suitesparse/package-version.txt
  build/pkgs/suitesparse/patches/01-no_cmake_project.patch
  build/pkgs/suitesparse/patches/02-darwin_blas.patch
  build/pkgs/suitesparse/patches/03-buildflags.patch
  build/pkgs/suitesparse/patches/04-cygwin.patch
  build/pkgs/suitesparse/spkg-install.in
Labels: c: packages: standard, s: positive review

#37434 Document building from the monorepo using `PIP_CONSTRAINT=$SAGE_ROOT/constraints_pkgs.txt`
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/ci-linux.yml
  build/make/Makefile.in
  constraints_pkgs.txt
  pkgs/sagemath-standard/README.rst
  pkgs/sagemath-standard/constraints_pkgs.txt
  pkgs/sagemath-standard/tox.ini
  src/pyproject.toml
  src/sage/matroids/basis_exchange_matroid.pxd
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pxd
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pxd
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pxd
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/flats_matroid.pxd
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/graphic_matroid.pxd
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/linear_matroid.pxd
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
  src/sage/matroids/union_matroid.pxd
  src/sage/matroids/union_matroid.pyx
  src/sage/sets/disjoint_set.pxd
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review, p: critical / 2, c: documentation, c: scripts, c: distribution, v: moderate

#37761 rings/infinite polynomial ring fixes
  src/sage/rings/polynomial/infinite_polynomial_element.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
Labels: s: positive review, c: coercion, c: commutative algebra

#38183 `build/pkgs/cypari` 2.2.0
  build/pkgs/cypari/checksums.ini
  build/pkgs/cypari/dependencies
  build/pkgs/cypari/package-version.txt
  build/pkgs/cypari/patches/trashcan.patch
Labels: c: packages: standard, s: positive review, v: small

#38224 `configure --disable-notebook`: Also disable `jupyter_sphinx`
  .ci/create-changes-html.sh
  .github/workflows/doc-build.yml
  build/pkgs/sagemath_doc_html/dependencies
  build/pkgs/sagemath_doc_html/dependencies_optional
  configure.ac
  src/doc/ca/intro/conf.py
  src/doc/de/a_tour_of_sage/conf.py
  src/doc/de/thematische_anleitungen/conf.py
  src/doc/de/tutorial/conf.py
  src/doc/el/a_tour_of_sage/conf.py
  src/doc/en/a_tour_of_sage/conf.py
  src/doc/en/constructions/conf.py
  src/doc/en/developer/conf.py
  src/doc/en/faq/conf.py
  src/doc/en/installation/conf.py
  src/doc/en/prep/conf.py
  src/doc/en/reference/conf.py
  src/doc/en/reference/conf_sub.py
  src/doc/en/thematic_tutorials/conf.py
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/conf.py
  src/doc/en/thematic_tutorials/numerical_sage/conf.py
  src/doc/en/tutorial/conf.py
  src/doc/en/tutorial/latex.rst
  src/doc/en/website/conf.py
  src/doc/es/a_tour_of_sage/conf.py
  src/doc/es/tutorial/conf.py
  src/doc/fr/a_tour_of_sage/conf.py
  src/doc/fr/tutorial/conf.py
  src/doc/hu/a_tour_of_sage/conf.py
  src/doc/it/a_tour_of_sage/conf.py
  src/doc/it/faq/conf.py
  src/doc/it/tutorial/conf.py
  src/doc/ja/a_tour_of_sage/conf.py
  src/doc/ja/tutorial/conf.py
  src/doc/pt/a_tour_of_sage/conf.py
  src/doc/pt/tutorial/conf.py
  src/doc/ru/tutorial/conf.py
  src/doc/tr/a_tour_of_sage/conf.py
  src/sage/features/sphinx.py
  src/sage_docbuild/conf.py
Labels: c: user interface, s: positive review, p: critical / 2, c: build: configure, v: minimal

#38291 Implement a custom class for tropical polynomials
  src/doc/en/reference/polynomial_rings/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/polydict.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_ring_constructor.py
  src/sage/rings/semirings/tropical_mpolynomial.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/semirings/tropical_variety.py
Labels: s: positive review, c: commutative algebra, gsoc: 2024

#38306 Reduce outdated `gdb` and `valgrind` packages to dummy packages
  build/pkgs/gdb/SPKG.rst
  build/pkgs/gdb/checksums.ini
  build/pkgs/gdb/dependencies
  build/pkgs/gdb/package-version.txt
  build/pkgs/gdb/spkg-install.in
  build/pkgs/gdb/type
  build/pkgs/valgrind/SPKG.rst
  build/pkgs/valgrind/checksums.ini
  build/pkgs/valgrind/dependencies
  build/pkgs/valgrind/package-version.txt
  build/pkgs/valgrind/spkg-install.in
  build/pkgs/valgrind/type
Labels: s: positive review, c: packages: optional, v: small

#38361 EllipticCurve: Raise error on unexpected keyword argument
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
Labels: s: positive review, c: elliptic curves, v: minimal

#38459 Fix coercion error on constant arguments to HypJac point construction
  src/sage/schemes/hyperelliptic_curves/jacobian_homset.py
Labels: t: bug, s: positive review, c: algebraic geometry

#38462 get rid of sage_eval in cfinite_sequence
  src/sage/rings/cfinite_sequence.py
Labels: s: positive review, c: combinatorics, t: refactoring

#38463 replace use of gp interface by pari lib in 3 files
  src/sage/arith/misc.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/quadratic_forms/genera/genus.py
Labels: s: positive review, c: interfaces

#38465 using pathlib.Path around SAGE_EXTCODE
  src/sage/features/threejs.py
  src/sage/graphs/graph_plot_js.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: s: positive review

#38485 Updated SPKG links for polymake as per #37532
  build/pkgs/polymake/SPKG.rst
Labels: s: positive review, c: documentation, c: packages: optional

#38488 implement smooth_part() and coprime_part()
  src/sage/arith/misc.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#38490 prevent crash in order_from_multiple() due to rounding error
  src/sage/groups/generic.py
Labels: p: major / 3, t: bug, s: positive review, c: group theory

#38491 Add _latex_ method for hyperelliptic curves
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
Labels: t: enhancement, s: positive review, c: elliptic curves

#38496 CI: Update `centos-stream-9`, add `fedora-41`
  .devcontainer/portability-centos-stream-9-minimal/devcontainer.json
  .devcontainer/portability-centos-stream-9-minimal/portability-Dockerfile
  .devcontainer/portability-centos-stream-9-python3.12-minimal/devcontainer.json
  .devcontainer/portability-centos-stream-9-python3.12-minimal/portability-Dockerfile
  .devcontainer/portability-centos-stream-9-python3.12-standard/devcontainer.json
  .devcontainer/portability-centos-stream-9-python3.12-standard/portability-Dockerfile
  .devcontainer/portability-centos-stream-9-standard/devcontainer.json
  .devcontainer/portability-centos-stream-9-standard/portability-Dockerfile
  .devcontainer/portability-fedora-41-minimal/devcontainer.json
  .devcontainer/portability-fedora-41-minimal/portability-Dockerfile
  .devcontainer/portability-fedora-41-standard/devcontainer.json
  .devcontainer/portability-fedora-41-standard/portability-Dockerfile
  .github/workflows/docker.yml
  build/pkgs/_python3.10/distros/fedora.txt
  build/pkgs/_python3.11/distros/fedora.txt
  build/pkgs/_python3.12/distros/fedora.txt
  build/pkgs/_python3.9/distros/fedora.txt
  src/doc/en/developer/portability_platform_table.rst
  tox.ini
Labels: s: positive review, c: scripts, c: porting

#38497 minor details in categories folder
  src/sage/categories/category_cy_helper.pyx
  src/sage/categories/category_singleton.pyx
  src/sage/categories/map.pxd
  src/sage/categories/map.pyx
Labels: s: positive review

#38499 CI / `tox docker-incremental`: Fix incremental build from a different Sage version
  .ci/write-dockerfile.sh
Labels: s: positive review, c: scripts, p: CI Fix

#38502 deprecate the class "Algebra"
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra.py
  src/sage/categories/category_with_axiom.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: algebra, c: categories, t: refactoring

#38503 Reviewer guide: Link to Eric Gourgoulhon's test notebook
  src/doc/en/developer/review.rst
Labels: s: positive review, c: documentation

#38505 Update list of Apple Silicon processors
  README.md
  build/pkgs/gcc/SPKG.rst
  src/doc/en/installation/conda.rst
Labels: s: positive review, c: documentation, p: trivial / 5

#38506 fixing all pep E302 warnings in folders [a-c]*
  src/sage/algebras/lie_algebras/bgg_dual_module.py
  src/sage/algebras/lie_algebras/bgg_resolution.py
  src/sage/coding/bch_code.py
  src/sage/coding/channel.py
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/decoder.py
  src/sage/coding/encoder.py
  src/sage/coding/extended_code.py
  src/sage/coding/golay_code.py
  src/sage/coding/goppa_code.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/guruswami_sudan/interpolation.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/linear_rank_metric.py
  src/sage/coding/punctured_code.py
  src/sage/coding/self_dual_codes.py
  src/sage/combinat/SJT.py
  src/sage/combinat/combinat.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/block_design.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/difference_matrices.py
  src/sage/combinat/designs/ext_rep.py
  src/sage/combinat/designs/orthogonal_arrays.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/designs/steiner_quadruple_systems.py
  src/sage/combinat/sf/dual.py
  src/sage/combinat/sf/orthotriang.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/symmetric_group_representations.py
  src/sage/combinat/tamari_lattices.py
  src/sage/cpython/_py2_random.py
  src/sage/crypto/block_cipher/miniaes.py
  src/sage/crypto/block_cipher/sdes.py
  src/sage/crypto/cipher.py
  src/sage/crypto/classical.py
  src/sage/crypto/classical_cipher.py
  src/sage/crypto/key_exchange/diffie_hellman.py
  src/sage/crypto/key_exchange/key_exchange_scheme.py
  src/sage/crypto/lattice.py
  src/sage/crypto/lwe.py
  src/sage/crypto/mq/sr.py
  src/sage/crypto/public_key/blum_goldwasser.py
  src/sage/crypto/stream.py
  src/sage/crypto/stream_cipher.py
  src/sage/crypto/util.py
  src/sage/databases/conway.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/databases/db_class_polynomials.py
  src/sage/databases/findstat.py
  src/sage/databases/knotinfo_db.py
  src/sage/databases/odlyzko.py
  src/sage/databases/sql_db.py
Labels: s: positive review, t: refactoring

#38507 some code details in asymptotic
  src/sage/rings/asymptotic/asymptotic_expansion_generators.py
Labels: s: positive review, c: asymptotic expansions, t: refactoring

#38512 details in moment-angle complex
  src/sage/topology/cell_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/moment_angle_complex.py
  src/sage/topology/simplicial_complex_examples.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_morphism.py
Labels: s: positive review

#38513 various details in arithgroup_generic
  src/sage/modular/arithgroup/arithgroup_generic.py
Labels: s: positive review, t: refactoring

#38516 avoid using reserved min and max in two files
  src/sage/monoids/trace_monoid.py
  src/sage/quadratic_forms/quadratic_form__theta.py
  src/tox.ini
Labels: s: positive review, p: CI Fix

#38519 GH Actions: Upload PyPI sdists also as GitHub Release Assets
  .github/workflows/dist.yml
Labels: s: positive review, c: scripts, c: distribution

#38521 Fix `sage_bootstrap.flock` for Python 3.13 (fedora-41)
  build/sage_bootstrap/compat/__init__.py
  build/sage_bootstrap/flock.py
Labels: s: positive review, p: blocker / 1, c: porting, c: python3

#38522 `build/pkgs/libpng`: Update to 1.6.43
  build/pkgs/libpng/checksums.ini
  build/pkgs/libpng/package-version.txt
  build/pkgs/libpng/spkg-install.in
Labels: c: packages: standard, s: positive review, p: critical / 2

#38523 CI Linux: Strip timestamps printed by docker buildkit
  .github/workflows/docker.yml
Labels: s: positive review, c: scripts

#38524 Sort #34892 doctest output vectors to fix randomness
  src/sage/modules/free_quadratic_module_integer_symmetric.py
Labels: s: positive review, c: documentation, p: trivial / 5, p: CI Fix

#38534 `build/pkgs/tachyon`: Fix rpath
  build/pkgs/tachyon/package-version.txt
  build/pkgs/tachyon/patches/Make-config.patch
  build/pkgs/tachyon/spkg-install.in
Labels: c: packages: standard, s: positive review, p: blocker / 1, c: graphics

#38535 fix issue 38527 with `spqr_tree_to_graph`
  src/sage/graphs/connectivity.pyx
Labels: s: positive review, c: graph theory

#38538 catch xgcd crash in flint nmod
  src/sage/libs/flint/nmod_poly_linkage.pxi
Labels: c: basic arithmetic, t: bug, p: minor / 4, s: positive review

#38546 use Parent in Hecke algebras
  src/sage/modular/hecke/algebra.py
Labels: s: positive review, c: modular forms, t: refactoring

#38549 Prepare sage for sphinx 8
  build/pkgs/sphinx/checksums.ini
  build/pkgs/sphinx/package-version.txt
  build/pkgs/sphinx/version_requirements.txt
  src/sage_docbuild/ext/sage_autodoc.py
Labels: c: packages: standard, s: positive review

#38553 Fix `DiGraph.dig6_string` when the digraph has loops
  src/sage/graphs/digraph.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_input.py
Labels: s: positive review, c: graph theory

#38554 Fix conda environments after `build` was removed from conda-forge in favor of `python-build`
  build/pkgs/python_build/distros/conda.txt
  src/environment-3.10-linux-aarch64.yml
  src/environment-3.10-linux.yml
  src/environment-3.10-macos-x86_64.yml
  src/environment-3.10-macos.yml
  src/environment-3.11-linux-aarch64.yml
  src/environment-3.11-linux.yml
  src/environment-3.11-macos-x86_64.yml
  src/environment-3.11-macos.yml
  src/environment-3.9-linux-aarch64.yml
  src/environment-3.9-linux.yml
  src/environment-3.9-macos-x86_64.yml
  src/environment-3.9-macos.yml
  src/environment-dev-3.10-linux-aarch64.yml
  src/environment-dev-3.10-linux.yml
  src/environment-dev-3.10-macos-x86_64.yml
  src/environment-dev-3.10-macos.yml
  src/environment-dev-3.11-linux-aarch64.yml
  src/environment-dev-3.11-linux.yml
  src/environment-dev-3.11-macos-x86_64.yml
  src/environment-dev-3.11-macos.yml
  src/environment-dev-3.9-linux-aarch64.yml
  src/environment-dev-3.9-linux.yml
  src/environment-dev-3.9-macos-x86_64.yml
  src/environment-dev-3.9-macos.yml
Labels: s: positive review, c: distribution, p: CI Fix

#38561 Period lattice: fix documentation error
  src/sage/schemes/elliptic_curves/period_lattice.py
Labels: s: positive review, c: documentation, c: elliptic curves

#38563 Tutorial: Remove remarks on Python 2 integers
  src/doc/en/tutorial/afterword.rst
Labels: s: positive review, c: documentation, c: python3

#38566 fix __iter__ method for point homsets
  src/sage/schemes/generic/homset.py
Labels: p: minor / 4, s: positive review, c: algebraic geometry

#38504 Demote `jmol` to optional
  build/pkgs/jmol/type
  build/pkgs/sagemath_doc_html/dependencies
  build/pkgs/sagetex/dependencies_check
  src/doc/en/faq/faq-usage.rst
  src/doc/en/prep/Symbolics-and-Basic-Plotting.rst
  src/doc/it/faq/faq-usage.rst
  src/sage/features/jmol.py
  src/sage/graphs/graph.py
Labels: c: packages: standard, s: positive review, c: graphics

#38572 `build/pkgs/nauty`: Update to 2.8.9
  build/pkgs/nauty/checksums.ini
  build/pkgs/nauty/package-version.txt
  build/pkgs/nauty/spkg-install.in
  src/sage/graphs/generators/families.py
Labels: c: packages: standard, s: positive review, c: group theory, c: graph theory

#38575 Fix `is_homogeneous` weight bug
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/polydict.pyx
Labels: t: bug, s: positive review, c: commutative algebra

#38576 `crypto/sbox.pyx`: remove unreachable code
  src/sage/crypto/sbox.pyx
Labels: t: bug, s: positive review, p: trivial / 5, c: cryptography

#38577 Add various project URLs for PyPI
  m4/pyproject_toml_metadata.m4
Labels: s: positive review, c: distribution

#38585 adding a warning about iteration over words
  src/sage/combinat/words/words.py
Labels: s: positive review, c: combinatorics

#38592 Add is_integral method to algebraic numbers
  src/sage/rings/qqbar.py
Labels: s: positive review, c: number fields

#38598 Add reflection_index_set() and reflection() methods for permutations
  src/sage/combinat/permutation.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: group theory

#38602 Allow for python sets to be counted as sets
  src/sage/combinat/subset.py
Labels: t: enhancement, s: positive review

#38608 Add warning filter for DeprecationWarning while doc build
  src/sage_docbuild/sphinxbuild.py
Labels: s: positive review, c: documentation

#38609 fix the linter
  src/sage/schemes/hyperelliptic_curves/constructor.py
Labels: s: positive review, p: CI Fix

#38610 fix and activate E303 check in pyx files
  src/sage/libs/coxeter3/decl.pxd
  src/sage/libs/ecl.pxd
  src/sage/libs/linbox/fflas.pxd
  src/sage/libs/m4rie.pxd
  src/sage/libs/meataxe.pxd
  src/sage/libs/ntl/GF2X.pxd
  src/sage/libs/singular/decl.pxd
  src/sage/libs/symmetrica/sb.pxi
  src/sage/libs/symmetrica/schur.pxi
  src/sage/matrix/matrix_modn_dense_template.pxi
  src/sage/rings/finite_rings/hom_finite_field.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
  src/tox.ini
Labels: s: positive review

#38611 pep and ruff cleanup in semirings and tropicals
  src/sage/rings/semirings/non_negative_integer_semiring.py
  src/sage/rings/semirings/tropical_mpolynomial.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/semirings/tropical_variety.py
Labels: s: positive review, c: finite rings, t: refactoring

#38612 pep8 cleanup in algebras
  src/sage/algebras/clifford_algebra.py
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/algebras/group_algebra.py
  src/sage/algebras/hall_algebra.py
  src/sage/algebras/hecke_algebras/ariki_koike_algebra.py
  src/sage/algebras/lie_algebras/bgg_dual_module.py
  src/sage/algebras/lie_algebras/center_uea.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/onsager.py
  src/sage/algebras/lie_algebras/rank_two_heisenberg_virasoro.py
  src/sage/algebras/lie_algebras/symplectic_derivation.py
  src/sage/algebras/lie_algebras/verma_module.py
  src/sage/algebras/lie_algebras/virasoro.py
  src/sage/algebras/lie_conformal_algebras/affine_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/free_bosons_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/free_fermions_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_with_structure_coefs.py
  src/sage/algebras/orlik_solomon.py
  src/sage/algebras/orlik_terao.py
  src/sage/algebras/q_system.py
  src/sage/algebras/quantum_groups/fock_space.py
  src/sage/algebras/quantum_groups/representations.py
  src/sage/algebras/quantum_oscillator.py
  src/sage/algebras/rational_cherednik_algebra.py
  src/sage/algebras/splitting_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra_mult.py
  src/sage/algebras/tensor_algebra.py
  src/sage/algebras/yangian.py
  src/sage/algebras/yokonuma_hecke_algebra.py
Labels: s: positive review, c: algebra, t: refactoring

#38613 `categories/morphism.pyx`: remove some `noexcept`s
  src/sage/categories/morphism.pyx
Labels: s: positive review, p: trivial / 5, c: cython, c: categories

#38614 some pep8 fixes in combinat/designs
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/block_design.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/designs/ext_rep.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/designs/orthogonal_arrays.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/combinat/designs/twographs.py
Labels: s: positive review, c: combinatorial designs, t: refactoring

#38615 `permgroup_element.pyx`: add some `const`s
  src/sage/groups/perm_gps/permgroup_element.pyx
Labels: s: positive review, p: trivial / 5, c: group theory

#38619 Re-add py3.9 support to sage_autodoc.py
  src/sage_docbuild/ext/sage_autodoc.py
Labels: t: bug, s: positive review, c: build, c: documentation, p: blocker / 1

#38620 cleaning the deprecation and removal of NoetherianRing class
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring

#38621 switch from `genbg` to `genbgL` in `nauty_genbg` to generate larger bipartite graphs.
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory

#38622 pep8 fixes in schemes/toric
  src/sage/schemes/toric/ideal.py
  src/sage/schemes/toric/library.py
  src/sage/schemes/toric/sheaf/klyachko.py
  src/sage/schemes/toric/toric_subscheme.py
Labels: s: positive review, t: refactoring

#38624 Fix issue report formatting
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/failure_building_from_source.yml
Labels: s: positive review

#38625 Remove outdated setting of `sphinx_source_suffix`
  src/sage_docbuild/conf.py
Labels: s: positive review, c: build, c: documentation

#38627 Require weaker Sphinx dependency for sagelib
  src/setup.cfg.m4
Labels: s: positive review, p: blocker / 1, p: CI Fix

#38628 Fix hypellfrob.pyx calling Python inside sig_on
  src/sage/schemes/hyperelliptic_curves/hypellfrob.pyx
Labels: t: bug, s: positive review, c: cython

#38635 fixing most ruff PERF4 warnings in combinat
  src/sage/combinat/composition_tableau.py
  src/sage/combinat/diagram.py
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/dlx.py
  src/sage/combinat/finite_state_machine.py
  src/sage/combinat/free_dendriform_algebra.py
  src/sage/combinat/free_prelie_algebra.py
  src/sage/combinat/gelfand_tsetlin_patterns.py
  src/sage/combinat/graph_path.py
  src/sage/combinat/integer_vector.py
  src/sage/combinat/knutson_tao_puzzles.py
  src/sage/combinat/misc.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/partition_algebra.py
  src/sage/combinat/ribbon_shaped_tableau.py
  src/sage/combinat/rsk.py
  src/sage/combinat/shifted_primed_tableau.py
  src/sage/combinat/skew_partition.py
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/combinat/tableau.py
  src/sage/combinat/tableau_tuple.py
Labels: s: positive review, c: combinatorics, t: refactoring

#38636 fix something in quadratic forms
  src/sage/quadratic_forms/quadratic_form__local_field_invariants.py
Labels: s: positive review, c: quadratic forms

#38638 interface to new nauty generator for Hasse diagrams
  src/sage/graphs/digraph_generators.py
Labels: s: positive review, c: combinatorics, c: graph theory

#38644 pathlib in simplicial sets examples
  src/sage/topology/simplicial_set_examples.py
Labels: s: positive review

#37569 Repair `sage -t --valgrind`
  src/bin/sage-runtests
  src/bin/sage-valgrind
  src/sage/doctest/__main__.py
  src/sage/doctest/control.py
Labels: s: positive review, p: critical / 2, c: doctest framework, c: scripts, v: large

#37821 Fix category of ModularFormsRing and documentation cleanup
  src/sage/modular/modform/ring.py
Labels: t: bug, s: positive review, c: documentation, c: modular forms, v: moderate

#38299 graphs: add implementation of slice decomposition via an extended LexBFS algorithm
  src/doc/en/reference/graphs/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/slice_decomposition.pxd
  src/sage/graphs/graph_decompositions/slice_decomposition.pyx
  src/sage/graphs/traversals.pyx
Labels: s: positive review, c: graph theory, v: minimal

#38341 Implement EllipticCurve_with_prime_order() constructor
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/all.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: s: positive review, c: elliptic curves, v: moderate

#38435 add method `is_edge_cut` to graphs
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#38501 `build/pkgs/cython`: Update to 3.0.11
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/package-version.txt
Labels: c: packages: standard, s: positive review

#38532 `build/pkgs/jupyter_jsmol`: Change to optional
  build/pkgs/jupyter_jsmol/type
Labels: c: packages: standard, s: positive review

#38539 some details in strassen.pyx
  src/sage/matrix/strassen.pyx
Labels: s: positive review, c: linear algebra

#38542 Fixes in pyx files
  src/sage/combinat/designs/evenly_distributed_sets.pyx
  src/sage/combinat/designs/subhypergraph_search.pyx
  src/sage/matroids/matroid.pyx
  src/sage/modular/arithgroup/congroup.pyx
  src/sage/modular/hypergeometric_misc.pxd
  src/sage/modular/hypergeometric_misc.pyx
  src/sage/modular/modform/eis_series_cython.pyx
  src/sage/modular/modsym/heilbronn.pyx
  src/sage/modular/modsym/p1list.pyx
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
  src/sage/structure/sage_object.pyx
Labels: s: positive review

#38548 `build/pkgs/pip` 24.2, `setuptools` 73.0.1 etc.
  build/pkgs/hatchling/checksums.ini
  build/pkgs/hatchling/package-version.txt
  build/pkgs/packaging/checksums.ini
  build/pkgs/packaging/package-version.txt
  build/pkgs/pip/checksums.ini
  build/pkgs/pip/package-version.txt
  build/pkgs/pyproject_api/checksums.ini
  build/pkgs/pyproject_api/package-version.txt
  build/pkgs/pyproject_hooks/checksums.ini
  build/pkgs/pyproject_hooks/package-version.txt
  build/pkgs/pyproject_metadata/checksums.ini
  build/pkgs/pyproject_metadata/dependencies
  build/pkgs/pyproject_metadata/package-version.txt
  build/pkgs/pyproject_metadata/spkg-install.in
  build/pkgs/setuptools/checksums.ini
  build/pkgs/setuptools/package-version.txt
  build/pkgs/trove_classifiers/checksums.ini
  build/pkgs/trove_classifiers/package-version.txt
  build/pkgs/typing_extensions/checksums.ini
  build/pkgs/typing_extensions/package-version.txt
  build/pkgs/wheel/checksums.ini
  build/pkgs/wheel/package-version.txt
Labels: c: packages: standard, s: positive review

#38558 `build/pkgs/python3`: Update to 3.12.5
  build/pkgs/python3/checksums.ini
  build/pkgs/python3/package-version.txt
Labels: c: packages: standard, s: positive review

#38568 Right align sage/python tabs and alter vertical spacing
  src/doc/common/static/custom-tabs.css
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation

#38571 `build/pkgs/primecount` 7.14, `primesieve`: 12.4
  build/pkgs/primecount/checksums.ini
  build/pkgs/primecount/package-version.txt
  build/pkgs/primesieve/checksums.ini
  build/pkgs/primesieve/package-version.txt
Labels: c: packages: standard, s: positive review

#38581 README.md, src/doc/en/installation: Replace release tours links
  README.md
  src/doc/en/installation/index.rst
  src/doc/en/installation/troubles.rst
Labels: s: positive review, c: documentation

#35050 Add missing commit when building large Cremona database
  src/sage/databases/cremona.py
Labels: s: positive review, c: elliptic curves, c: databases

#38174 New algorithms to compute the characteristic polynomial of the Frobenius endomorphism of a Drinfeld module
  src/doc/en/reference/references/index.rst
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
Labels: s: positive review, c: algebra, v: moderate

#38321 Implemented generators for some small graphs/ digraphs
  src/doc/en/reference/references/index.rst
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory, v: minimal, gsoc: 2024

#38540 fix ruff PLR1730 checks
  src/sage/calculus/desolvers.py
  src/sage/categories/finite_posets.py
  src/sage/combinat/matrices/latin.py
  src/sage/combinat/partition.py
  src/sage/combinat/rigged_configurations/bij_type_D.py
  src/sage/combinat/sloane_functions.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/paths.py
  src/sage/combinat/words/words.py
  src/sage/doctest/forker.py
  src/sage/dynamics/arithmetic_dynamics/endPN_minimal_model.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/geometry/toric_plotter.py
  src/sage/groups/additive_abelian/additive_abelian_wrapper.py
  src/sage/interfaces/ecm.py
  src/sage/interfaces/magma.py
  src/sage/interfaces/singular.py
  src/sage/knots/link.py
  src/sage/logic/boolformula.py
  src/sage/matrix/operation_table.py
  src/sage/modular/modform/space.py
  src/sage/modular/modsym/space.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/quadratic_forms/quadratic_form__equivalence_testing.py
  src/sage/rings/number_field/S_unit_solver.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/padics/lattice_precision.py
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/padic_base_leaves.py
  src/sage/rings/rational_field.py
  src/sage/schemes/affine/affine_morphism.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/BSD.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/padic_lseries.py
  src/sage/sets/real_set.py
  src/sage/stats/distributions/discrete_gaussian_lattice.py
  src/sage/symbolic/random_tests.py
  src/sage/topology/filtered_simplicial_complex.py
  src/sage/typeset/character_art_factory.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#38607 Add subs method for function field elements
  src/sage/rings/function_field/element.pyx
Labels: t: bug, s: positive review, c: algebraic geometry

#38641 some fixes for E241
  src/sage/categories/bimodules.py
  src/sage/categories/coalgebras.py
  src/sage/categories/examples/crystals.py
  src/sage/combinat/ncsf_qsym/qsym.py
  src/sage/combinat/root_system/cartan_matrix.py
  src/sage/combinat/root_system/coxeter_group.py
  src/sage/combinat/root_system/dynkin_diagram.py
  src/sage/combinat/root_system/type_A.py
  src/sage/combinat/root_system/type_C.py
  src/sage/combinat/root_system/type_D.py
  src/sage/combinat/root_system/type_E.py
  src/sage/combinat/root_system/type_F.py
  src/sage/combinat/root_system/type_G.py
  src/sage/combinat/sf/dual.py
  src/sage/combinat/sf/elementary.py
  src/sage/combinat/sf/homogeneous.py
  src/sage/combinat/sf/llt.py
  src/sage/combinat/sf/macdonald.py
  src/sage/combinat/sf/orthotriang.py
  src/sage/combinat/sf/powersum.py
  src/sage/combinat/sf/schur.py
  src/sage/combinat/species/misc.py
  src/sage/functions/spike_function.py
  src/sage/geometry/cone.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/backend_polymake.py
  src/sage/geometry/polyhedron/generating_function.py
  src/sage/graphs/generators/families.py
  src/sage/groups/cubic_braid.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/interacts/library.py
  src/sage/interfaces/four_ti_2.py
  src/sage/knots/knotinfo.py
  src/sage/manifolds/calculus_method.py
  src/sage/plot/animate.py
  src/sage/plot/plot3d/shapes2.py
  src/sage/repl/image.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/tensor/modules/free_module_alt_form.py
Labels: s: positive review, t: refactoring

#38647 fixing some mypy suggestions in algebras and abvar
  src/sage/algebras/cluster_algebra.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/algebras/lie_conformal_algebras/examples.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/abvar/abvar_ambient_jacobian.py
  src/sage/modular/abvar/abvar_newform.py
  src/sage/modular/abvar/constructor.py
  src/sage/modular/abvar/homspace.py
Labels: s: positive review, c: algebraic geometry, c: algebra

#38649 Fix all three CONDA ci failing tests
  src/sage/doctest/forker.py
  src/sage/functions/hypergeometric.py
  src/sage/typeset/ascii_art.py
Labels: s: positive review, p: CI Fix

#38653 get rid of sage-eval in dokchister.py
  src/sage/lfunctions/dokchitser.py
Labels: s: positive review

#38660 simplifications in some libgap calls
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/groups/perm_gps/permgroup.py
Labels: s: positive review

#38664 graphs: make init_short_digraph always sort neighbors but without the extra log complexity (2nd try)
  src/sage/graphs/asteroidal_triples.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/base/static_sparse_graph.pxd
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/centrality.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/isoperimetric_inequalities.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/weakly_chordal.pyx
Labels: s: positive review, c: graph theory

#38666 some care for pep8 E203 in pyx files
  src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.pyx
  src/sage/coding/codecan/codecan.pyx
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/libs/flint/fmpz_poly_sage.pyx
  src/sage/libs/giac/giac.pyx
  src/sage/libs/ntl/ntl_mat_ZZ.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/libs/singular/singular.pyx
  src/sage/matrix/matrix_dense.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matrix/strassen.pyx
  src/sage/misc/cachefunc.pyx
  src/sage/modular/modform/eis_series_cython.pyx
  src/sage/numerical/backends/glpk_graph_backend.pyx
  src/sage/numerical/mip.pyx
  src/sage/numerical/sdp.pyx
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/structure/element.pyx
Labels: s: positive review

#38667 Fix pyproject.toml use of inline tables
  m4/pyproject_toml_metadata.m4
Labels: s: positive review, p: blocker / 1, p: CI Fix

#38669 Remove giac integration from GiNaC
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/ginac/basic.h
  src/sage/symbolic/ginac/ex.h
  src/sage/symbolic/ginac/mpoly-giac.cpp
  src/sage/symbolic/ginac/mpoly-ginac.cpp
  src/sage/symbolic/ginac/mpoly-singular.cpp
  src/sage/symbolic/ginac/normal.cpp
  src/sage/symbolic/ginac/numeric.cpp
  src/sage/symbolic/ginac/numeric.h
  src/sage/symbolic/ginac/pynac-config.h
Labels: s: positive review

#38674 cythonize the chain polynomials of posets
  src/sage/combinat/posets/hasse_cython_flint.pyx
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#38687 Fix broken coverage ci
  .github/workflows/build.yml
Labels: s: positive review, p: blocker / 1, p: CI Fix

#38691 build/pkgs/mpmath/version_requirements.txt: Reject 1.4
  build/pkgs/mpmath/version_requirements.txt
Labels: s: positive review

#38692 Add make_set function for DisjointSets
  src/sage/groups/perm_gps/partn_ref/data_structures.pxd
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review

#38695 some care for pycodestyle E262 in pyx files
  src/sage/coding/codecan/codecan.pyx
  src/sage/data_structures/bounded_integer_sequences.pyx
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/libs/lcalc/lcalc_Lfunction.pyx
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/function_mangling.pyx
  src/sage/numerical/backends/cvxopt_backend.pyx
  src/sage/plot/plot3d/shapes.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/weil/weil_polynomials.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/stats/time_series.pyx
  src/sage/structure/element.pyx
Labels: s: positive review

#38696 some pep8 fixes in sage/all.py
  src/sage/all.py
Labels: s: positive review

#38697 fixes for ruff warning C416
  src/sage/crypto/mq/sr.py
  src/sage/databases/findstat.py
  src/sage/dynamics/arithmetic_dynamics/endPN_automorphism_group.py
  src/sage/geometry/cone.py
  src/sage/geometry/fan.py
  src/sage/geometry/hasse_diagram.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/linear_expression.py
  src/sage/geometry/polyhedron/backend_normaliz.py
  src/sage/geometry/polyhedron/base.py
  src/sage/geometry/polyhedron/plot.py
  src/sage/graphs/digraph.py
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_plot.py
  src/sage/interacts/library.py
  src/sage/interfaces/fricas.py
  src/sage/interfaces/kenzo.py
  src/sage/manifolds/differentiable/degenerate_submanifold.py
  src/sage/manifolds/differentiable/diff_map.py
  src/sage/manifolds/differentiable/integrated_curve.py
  src/sage/manifolds/differentiable/tensorfield_paral.py
  src/sage/numerical/optimize.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/polynomial/infinite_polynomial_element.py
  src/sage/symbolic/relation.py
Labels: s: positive review

#38698 some fixes for ruff UP warnings
  src/sage/combinat/combinat.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/dyck_word.py
  src/sage/combinat/parking_functions.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/subword.py
  src/sage/databases/cremona.py
  src/sage/databases/stein_watkins.py
  src/sage/env.py
  src/sage/ext_data/nbconvert/postprocess.py
  src/sage/game_theory/parser.py
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_plot_js.py
  src/sage/graphs/isgci.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/latte.py
  src/sage/interfaces/read_data.py
  src/sage/libs/gap/test.py
  src/sage/manifolds/differentiable/examples/symplectic_space.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/misc/package.py
  src/sage/modular/hecke/algebra.py
  src/sage/modular/multiple_zeta.py
  src/sage/modular/multiple_zeta_F_algebra.py
  src/sage/modules/with_basis/representation.py
  src/sage/plot/arc.py
  src/sage/repl/ipython_extension.py
  src/sage/rings/number_field/totallyreal_phc.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/sat/solvers/dimacs.py
  src/sage/sets/image_set.py
  src/sage/tensor/modules/finite_rank_free_module.py
  src/sage/tensor/modules/free_module_tensor.py
  src/sage/tests/memcheck/verify_no_leak.py
  src/sage/topology/simplicial_set_examples.py
  src/sage/typeset/character_art.py
Labels: s: positive review

#38702 fix WeylGroup of rank 0
  src/sage/combinat/root_system/weyl_group.py
Labels: t: bug, s: positive review, c: combinatorics

#38704 some details in permutations
  src/sage/combinat/permutation.py
Labels: s: positive review, c: combinatorics

#38705 update openblas to 0.3.28
  build/pkgs/openblas/checksums.ini
  build/pkgs/openblas/package-version.txt
Labels: c: packages: standard, s: positive review

#38706 better subs on piecewise functions
  src/sage/functions/piecewise.py
Labels: s: positive review, c: symbolics

#38715 Define feature `sage.libs.giac`
  src/sage/features/sagemath.py
Labels: t: bug, s: positive review, t: refactoring

#38718 Grammar fixes to documentation: an to a euclidean
  src/doc/en/thematic_tutorials/lie/lie_basics.rst
  src/sage/categories/euclidean_domains.py
  src/sage/categories/fields.py
  src/sage/coding/grs_code.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/manifolds/differentiable/examples/euclidean.py
  src/sage/matrix/matrix2.pyx
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/plot/plot3d/point_c.pxi
  src/sage/rings/integer.pyx
  src/sage/rings/padics/local_generic_element.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: documentation

#38720 Raise exception when factoring zero polynomial
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
Labels: s: positive review

#38721 Type of Z/nZ NTL polynomial evaluation should be scalar
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
Labels: s: positive review

#37128 Save and load finitely presented groups coming from libgap groups
  src/sage/groups/artin.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/free_group.py
  src/sage/libs/gap/element.pyx
  src/sage/schemes/curves/zariski_vankampen.py
Labels: s: positive review, c: group theory

#37357 allow the warning about root isolation failures in CBF[x] to be turned off
  src/sage/rings/complex_arb.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: commutative algebra

#38218 Implementing `is_matching_covered()` and `is_bicritical()`
  src/doc/en/reference/graphs/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/graphs/graph.py
  src/sage/graphs/matching.py
Labels: s: positive review, c: graph theory, v: minimal, gsoc: 2024

#38254 Extend the method get_knotinfo of the Link class to cover non-prime knots
  src/doc/en/reference/knots/index.rst
  src/sage/databases/knotinfo_db.py
  src/sage/knots/all.py
  src/sage/knots/free_knotinfo_monoid.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
Labels: p: major / 3, t: enhancement, s: positive review, c: databases, c: algebraic topology

#38453 Enhance augment method in Matrix_gf2e
  src/sage/matrix/matrix_gf2e_dense.pyx
Labels: s: positive review, c: linear algebra, c: finite rings

#38486 implement generalised PaleyII symmetric conference matrices
  src/sage/combinat/matrices/hadamard_matrix.py
Labels: s: positive review, c: combinatorics

#38556 Revert cysignals build constraint
  src/pyproject.toml
Labels: s: positive review, disputed, p: CI Fix

#38601 upgrade maxima to 5.47.0
  build/pkgs/maxima/checksums.ini
  build/pkgs/maxima/package-version.txt
Labels: c: packages: standard, s: positive review

#38606 number_field_elements_from_algebraics: Consistently use principal root
  src/sage/rings/qqbar.py
Labels: s: positive review, c: number fields

#38645 gc: update to 8.2.8
  build/pkgs/gc/checksums.ini
  build/pkgs/gc/package-version.txt
Labels: s: positive review

#38652 get rid of sage_eval in Mestre call of magma
  src/sage/schemes/hyperelliptic_curves/mestre.py
Labels: s: positive review, c: algebraic geometry

#38655 trying to refresh symbolic units
  src/sage/symbolic/units.py
Labels: s: positive review

#38656 advertise for libgap in src/doc
  src/doc/de/tutorial/interactive_shell.rst
  src/doc/en/constructions/groups.rst
  src/doc/en/constructions/interface_issues.rst
  src/doc/en/constructions/linear_algebra.rst
  src/doc/en/constructions/polynomials.rst
  src/doc/en/constructions/rep_theory.rst
  src/doc/en/constructions/rings.rst
  src/doc/en/developer/coding_in_other.rst
  src/doc/en/tutorial/interactive_shell.rst
  src/doc/fr/tutorial/interactive_shell.rst
  src/doc/ja/tutorial/interactive_shell.rst
  src/doc/pt/tutorial/interactive_shell.rst
  src/doc/ru/tutorial/interactive_shell.rst
Labels: s: positive review

#38658 configure.ac: add --disable-sagetex option
  configure.ac
Labels: c: packages: standard, s: positive review, c: build: configure

#38661 src/sage/misc/package.py: use gnulib instead of conway_polynomials in tests
  src/sage/misc/package.py
Labels: s: positive review, c: build: configure

#38662 configure.ac: disable more packages with --disable-notebook
  configure.ac
Labels: s: positive review, c: build: configure

#38663 Freetype fails to find freetype on macos
  build/pkgs/zlib/spkg-configure.m4
Labels: s: positive review

#38671 construct order ideals by default for number-field orders
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/nf_orders.rst
  src/sage/modular/dirichlet.py
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/order.py
  src/sage/rings/number_field/order_ideal.py
Labels: p: major / 3, t: enhancement, s: positive review, c: number fields

#38672 src/sage/features/giac.py: add new feature for the giac program
  src/sage/features/giac.py
Labels: c: packages: standard, s: positive review, c: packages: optional

#38676 Fix a bug in retrofit-worktree.sh
  .ci/retrofit-worktree.sh
Labels: s: positive review, p: blocker / 1, p: CI Fix

#38682 update fricas to version 1.3.11
  build/pkgs/fricas/checksums.ini
  build/pkgs/fricas/package-version.txt
Labels: s: positive review, c: packages: optional

#38685 Loosen tolerance in a few `expm()` tests
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/symbolic/constants_c_impl.pxi
Labels: s: positive review

#38689 Fix tests with singular 4.4.0p3
  src/sage/libs/singular/option.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review

#38690 Tweak a few tests to pass when giac is not installed
  src/sage/calculus/calculus.py
  src/sage/functions/piecewise.py
  src/sage/symbolic/integration/integral.py
Labels: s: positive review

#38693 Set partition to disjoint set
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review

#38694 Add robots.txt file to doc preview websites for PRs and releases
  .github/workflows/doc-build.yml
Labels: s: positive review, c: documentation, p: blocker / 1

#38701 some minor details in named permgroups
  src/sage/groups/perm_gps/permgroup_named.py
Labels: s: positive review
