Repository sagemath/sage, pull requests merged in 2024-12, with the labels that each got.

#38987 some work on deformed Burau matrix
  src/sage/groups/braid.py
Labels: s: positive review

#39019 simplify isogeny-enumeration code following #35949
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: t: enhancement, s: positive review, p: trivial / 5, c: elliptic curves

#39020 one more method in FHM-triangles
  src/sage/combinat/triangles_FHM.py
Labels: s: positive review, c: combinatorics

#39022 fix all ruff warnings SIM101
  src/sage/combinat/fully_packed_loop.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/words/words.py
  src/sage/dynamics/arithmetic_dynamics/generic_ds.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/geometry/voronoi_diagram.py
  src/sage/manifolds/differentiable/characteristic_cohomology_class.py
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/padics/factory.py
  src/sage/rings/polynomial/flatten.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_singular_interface.py
  src/sage/structure/sequence.py
Labels: s: positive review

#39023 Fix the right-border on unicode tables
  src/sage/combinat/bijectionist.py
  src/sage/misc/table.py
Labels: s: positive review

#39024 Automated the generation of changelogs in text format
  .github/workflows/changelog_trigger.yml
Labels: s: positive review, c: scripts

#39028 Numerical evaluation of modular form & implement conversion of more modular form spaces to Pari
  src/sage/modular/modform/ambient_eps.py
  src/sage/modular/modform/cuspidal_submodule.py
  src/sage/modular/modform/eisenstein_submodule.py
  src/sage/modular/modform/element.py
Labels: t: enhancement, s: positive review, c: interfaces

#39031 Remove pipfile
  .ci/write-dockerfile.sh
  .gitignore
  Makefile
  Pipfile.m4
  bootstrap
  src/Pipfile.m4
Labels: s: positive review

#39043 Some documentation clean-up
  src/sage/libs/eclib/interface.py
  src/sage/libs/eclib/mwrank.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/schemes/elliptic_curves/ell_rational_field.py
Labels: s: positive review, c: interfaces, c: documentation, c: elliptic curves

#39044 provide default argument for monomial_coefficients
  src/sage/algebras/commutative_dga.py
  src/sage/algebras/splitting_algebra.py
  src/sage/categories/modules_with_basis.py
  src/sage/rings/derivation.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/power_series_pari.pyx
  src/sage/rings/power_series_poly.pyx
Labels: s: positive review, c: commutative algebra

#39048 pep8 cleanup in libs
  src/sage/libs/coxeter3/coxeter_group.py
  src/sage/libs/eclib/interface.py
  src/sage/libs/gap/gap_globals.py
  src/sage/libs/gap/test_long.py
  src/sage/libs/giac/__init__.py
  src/sage/libs/pari/__init__.py
  src/sage/libs/singular/standard_options.py
Labels: s: positive review

#39049 Fixing typo with $g_i^{-1}$ implementation in Yokonuma-Hecke algebras.
  src/sage/algebras/yokonuma_hecke_algebra.py
Labels: t: bug, s: positive review, c: algebra

#39050 Fix exactify caching when interrupted
  src/sage/rings/qqbar.py
Labels: s: positive review

#39053 small-scale refresh for the sandpile file
  src/sage/sandpiles/sandpile.py
Labels: s: positive review

#39054 pep8 cleanup for structure/
  src/sage/structure/__init__.py
  src/sage/structure/all.py
  src/sage/structure/formal_sum.py
  src/sage/structure/gens_py.py
  src/sage/structure/indexed_generators.py
  src/sage/structure/list_clone_timings.py
  src/sage/structure/proof/all.py
  src/sage/structure/proof/proof.py
  src/sage/structure/sequence.py
  src/sage/structure/set_factories.py
  src/sage/structure/set_factories_example.py
  src/sage/structure/test_factory.py
Labels: s: positive review

#39055 pep8 cleanup in repl/ and sat/
  src/sage/repl/configuration.py
  src/sage/repl/interpreter.py
  src/sage/repl/ipython_extension.py
  src/sage/repl/rich_output/backend_doctest.py
  src/sage/repl/rich_output/backend_ipython.py
  src/sage/repl/rich_output/output_basic.py
  src/sage/repl/rich_output/output_catalog.py
  src/sage/repl/rich_output/test_backend.py
  src/sage/sat/boolean_polynomials.py
  src/sage/sat/converters/polybori.py
  src/sage/sat/solvers/picosat.py
  src/sage/sat/solvers/sat_lp.py
  src/sage/stats/distributions/catalog.py
Labels: s: positive review

#39056 miscellanous pep8 cleanup
  src/sage/matrix/matrix_misc.py
  src/sage/matroids/chow_ring.py
  src/sage/matroids/constructor.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/quadratic_forms/all.py
  src/sage/quadratic_forms/quadratic_form__local_density_congruence.py
  src/sage/quivers/ar_quiver.py
Labels: s: positive review

#39059 Make multivariate ideal reduce() work on integer
  src/sage/rings/polynomial/multi_polynomial_ideal.py
Labels: s: positive review

#39066 Add degree checks for Jacobian models
  src/sage/rings/function_field/jacobian_base.py
  src/sage/rings/function_field/jacobian_hess.py
  src/sage/rings/function_field/jacobian_khuri_makdisi.py
  src/sage/rings/function_field/khuri_makdisi.pyx
Labels: t: bug, s: positive review, c: number theory

#39067 unbreak "--disable-sage_conf"
  configure.ac
Labels: s: positive review, c: scripts

#39074 Fix the issue number format in deprecation comment
  src/doc/en/developer/coding_in_python.rst
Labels: s: positive review, c: documentation

#39084 linting : some fixes for pyx files in modular
  src/sage/modular/arithgroup/congroup.pyx
  src/sage/modular/arithgroup/farey_symbol.pyx
  src/sage/modular/modsym/heilbronn.pyx
  src/sage/modular/modsym/manin_symbol.pyx
  src/sage/modular/modsym/p1list.pxd
  src/sage/modular/modsym/p1list.pyx
  src/sage/modular/pollack_stevens/dist.pyx
Labels: s: positive review

#37446 Add dependency groups to `pyproject.toml`
  pyproject.toml
Labels: s: positive review, c: build

#38161 fix green function in projective_ds
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
Labels: t: bug, p: minor / 4, s: positive review, c: dynamics, gsoc: 2024

#38508 Hashing affine group elements
  src/sage/groups/affine_gps/group_element.py
Labels: t: bug, t: enhancement, s: positive review, c: group theory

#38686 Use the faster libgiac interface for "giac" integration
  src/sage/calculus/calculus.py
  src/sage/functions/piecewise.py
  src/sage/libs/giac/giac.pyx
  src/sage/symbolic/integration/external.py
  src/sage/symbolic/integration/integral.py
Labels: s: positive review, c: symbolics

#38834 Fast conversion from numpy ndarray to vector
  src/sage/modules/meson.build
  src/sage/modules/numpy_util.pxd
  src/sage/modules/numpy_util.pyx
  src/sage/modules/vector_mod2_dense.pyx
Labels: s: positive review, c: linear algebra, t: performance

#38843 Improve Matrix_mod2_dense solve_right performance
  src/sage/libs/m4ri.pxd
  src/sage/matrix/matrix_mod2_dense.pyx
Labels: s: positive review

#38874 Remove imports from `gsl.all`
  src/sage/calculus/integration.pyx
  src/sage/calculus/ode.pyx
  src/sage/probability/probability_distribution.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/real_double_element_gsl.pyx
  src/sage/symbolic/pynac_impl.pxi
Labels: s: positive review

#38883 provide the tilde species of a species
  src/sage/rings/species.py
Labels: s: positive review, c: combinatorics

#38887 libbraiding version bump
  build/pkgs/libbraiding/checksums.ini
  build/pkgs/libbraiding/package-version.txt
  build/pkgs/libbraiding/spkg-configure.m4
  src/sage/groups/braid.py
  src/sage/libs/braiding.pyx
Labels: c: packages: standard, s: positive review, c: group theory

#38892 Implemented methods pertaining to the canonical partition of a matching covered graph
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory, gsoc: 2024

#38895 Remove jupyter_execute directory after doc build finishes
  .github/workflows/doc-build.yml
  src/doc/Makefile
Labels: s: positive review, c: documentation

#38920 check for E302
  src/conftest.py
  src/doc/ja/tutorial/japanesesupport.py
  src/sage/algebras/splitting_algebra.py
  src/sage/arith/misc.py
  src/sage/doctest/control.py
  src/sage/doctest/external.py
  src/sage/doctest/reporting.py
  src/sage/doctest/util.py
  src/sage/features/__init__.py
  src/sage/features/dvipng.py
  src/sage/features/ffmpeg.py
  src/sage/features/fricas.py
  src/sage/features/gap.py
  src/sage/features/giac.py
  src/sage/features/igraph.py
  src/sage/features/imagemagick.py
  src/sage/features/kenzo.py
  src/sage/features/latex.py
  src/sage/features/msolve.py
  src/sage/features/palp.py
  src/sage/features/pdf2svg.py
  src/sage/features/poppler.py
  src/sage/features/symengine_py.py
  src/sage/games/quantumino.py
  src/sage/graphs/domination.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/interacts/library.py
  src/sage/interfaces/ecm.py
  src/sage/knots/knot.py
  src/sage/libs/eclib/constructor.py
  src/sage/libs/eclib/interface.py
  src/sage/libs/pari/__init__.py
  src/sage/libs/singular/standard_options.py
  src/sage/matroids/dual_matroid.py
  src/sage/modules/with_basis/representation.py
  src/sage/monoids/indexed_free_monoid.py
  src/sage/numerical/backends/cvxpy_backend_test.py
  src/sage/numerical/backends/generic_backend_test.py
  src/sage/numerical/backends/glpk_exact_backend_test.py
  src/sage/numerical/backends/interactivelp_backend_test.py
  src/sage/numerical/backends/logging_backend.py
  src/sage/numerical/backends/scip_backend_test.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/numerical/knapsack.py
  src/sage/probability/random_variable.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/tox.ini
Labels: s: positive review

#38927 moving "is_integrally_closed" to the category setup.
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/fields.py
  src/sage/categories/integral_domains.py
  src/sage/categories/rings.py
  src/sage/rings/integer_ring.pyx
  src/sage/rings/number_field/order.py
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring

#38935 src/sage/env.py: don't pass if mismatched SAGE_ROOT is None
  src/sage/env.py
Labels: s: positive review

#38940 Fix flaky simplicial set test
  src/sage/categories/simplicial_sets.py
Labels: s: positive review, p: CI Fix

#38945 Allow specifying arguments to Cython cell_magic
  src/sage/repl/ipython_extension.py
Labels: s: positive review, c: cython

#38952 adding the ring of quantum-valued polynomials
  src/doc/en/reference/polynomial_rings/polynomial_rings_univar.rst
  src/doc/en/reference/references/index.rst
  src/sage/rings/polynomial/all.py
  src/sage/rings/polynomial/meson.build
  src/sage/rings/polynomial/q_integer_valued_polynomials.py
Labels: s: positive review, c: algebra

#38955 Overwrote methods concerning loops for a matching covered graph
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory, gsoc: 2024

#38956 Hide GAP finiteness warnings during isomorphism check
  src/sage/groups/cubic_braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/finitely_presented_named.py
  src/sage/groups/libgap_mixin.py
  src/sage/schemes/curves/projective_curve.py
Labels: s: positive review, p: CI Fix

#38958 Allow powers of SignGroup elements to live in other parents
  src/sage/groups/misc_gps/argument_groups.py
  src/sage/rings/asymptotic/asymptotic_ring.py
Labels: s: positive review, c: asymptotic expansions

#38970 Do not allow order of AbelianGroup generator to be negative
  src/sage/groups/abelian_gps/abelian_group.py
Labels: s: positive review

#38972 Fix build of meataxe extension with meson
  src/meson.build
  src/sage/libs/meson.build
  src/sage/matrix/meson.build
Labels: s: positive review

#38974 allow incomparable labels in SetPartition
  src/sage/combinat/set_partition.py
Labels: s: positive review, c: combinatorics

#38975 support left and right actions for species
  src/sage/rings/species.py
Labels: t: enhancement, s: positive review, c: combinatorics

#38976 a few PERF4 suggestions by ruff fixed
  src/sage/modular/abvar/abvar.py
  src/sage/modular/etaproducts.py
  src/sage/modular/hecke/algebra.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hypergeometric_motive.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/rings/valuation/valuation.py
  src/sage/rings/valuation/valuation_space.py
  src/sage/rings/valuation/value_group.py
  src/sage/tensor/modules/finite_rank_free_module.py
  src/sage/tensor/modules/free_module_basis.py
  src/sage/typeset/character_art.py
Labels: s: positive review

#38977 minor details in some pyx files in sets
  src/sage/sets/family.pyx
  src/sage/sets/finite_set_map_cy.pyx
  src/sage/sets/pythonclass.pyx
  src/sage/sets/recursively_enumerated_set.pyx
Labels: s: positive review

#38978 avoid using isinstance IntegralDomain in modules
  src/sage/modules/free_module.py
  src/sage/modules/free_quadratic_module.py
Labels: s: positive review

#38980 Allow python ints in sage.groups.generic.has_order
  src/sage/groups/generic.py
Labels: t: bug, p: minor / 4, s: positive review, c: group theory

#38983 Use meson as backend for numpy.f2py
  src/sage/misc/inline_fortran.py
Labels: s: positive review, c: numerical

#38984 Fix detection of tdlib and mcqd with meson
  src/sage/graphs/graph_decompositions/meson.build
  src/sage/graphs/meson.build
Labels: s: positive review

#38989 tentative of free-Algebra functor
  src/sage/algebras/free_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/monoids/free_monoid.py
  src/sage/structure/coerce.pyx
Labels: t: enhancement, s: positive review, c: coercion, c: algebra

#39001 Fix crash when specify invalid base for RR and RIF construction
  src/sage/rings/convert/mpfi.pyx
  src/sage/rings/real_mpfr.pyx
Labels: s: positive review

#39014 Fix a few minor typos
  .vscode/settings.json
  src/sage/manifolds/manifold.py
Labels: s: positive review

#39021 hot-fix for ruff linter
  src/tox.ini
Labels: s: positive review, p: CI Fix

#38474 Implement period_lattice for elliptic curves over RealField, ComplexField, etc.
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/period_lattice.py
Labels: s: positive review, c: elliptic curves

#38844 remove a spurious adding of the same constraint twice
  src/sage/coding/delsarte_bounds.py
Labels: s: positive review, c: coding theory, c: linear programming

#38936 use `sig_realloc` in method `OP_make_set`
  src/sage/groups/perm_gps/partn_ref/data_structures.pxd
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review

#38997 Document RealIntervalField default printing configuration
  src/sage/rings/real_mpfi.pyx
Labels: s: positive review, c: documentation

#39036 implement elliptic-curve point addition for general rings
  src/doc/en/reference/references/index.rst
  src/sage/schemes/elliptic_curves/addition_formulas_ring.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/projective/projective_homset.py
  src/sage/schemes/projective/projective_point.py
  src/sage/structure/parent.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#39038 graphs: implementation of linear-time algorithm for modular decomposition
  src/doc/en/reference/references/index.rst
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/meson.build
  src/sage/graphs/graph_decompositions/modular_decomposition.hpp
  src/sage/graphs/graph_decompositions/modular_decomposition.pxd
  src/sage/graphs/graph_decompositions/modular_decomposition.pyx
Labels: s: positive review, c: graph theory

#39094 Fix numerical_integral with parameters
  src/sage/calculus/integration.pyx
Labels: t: bug, s: positive review, c: numerical, c: calculus

#39101 Add cython.binding(True) to occurrences of sage_wraps
  src/sage/misc/decorators.py
  src/sage/structure/element.pyx
  src/sage/structure/mutability.pyx
  src/sage/symbolic/expression.pyx
Labels: s: positive review

#39109 cython-lint fixes in misc/
  src/sage/misc/binary_tree.pxd
  src/sage/misc/binary_tree.pyx
  src/sage/misc/c3.pyx
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/cachefunc.pyx
  src/sage/misc/citation.pyx
  src/sage/misc/classcall_metaclass.pxd
  src/sage/misc/constant_function.pyx
  src/sage/misc/derivative.pyx
  src/sage/misc/fast_methods.pyx
  src/sage/misc/function_mangling.pyx
  src/sage/misc/inherit_comparison.pyx
  src/sage/misc/instancedoc.pyx
  src/sage/misc/lazy_attribute.pyx
  src/sage/misc/lazy_import.pyx
  src/sage/misc/lazy_list.pyx
  src/sage/misc/lazy_string.pyx
  src/sage/misc/nested_class.pyx
  src/sage/misc/persist.pyx
  src/sage/misc/randstate.pyx
  src/sage/misc/search.pxd
  src/sage/misc/stopgap.pyx
  src/sage/misc/weak_dict.pyx
Labels: s: positive review

#39111 build/pkgs/planarity/spkg-configure.m4: update header check
  build/pkgs/planarity/spkg-configure.m4
Labels: s: positive review

#35403 Adopt the “time window-based” policy for support of Python versions from Spec-0
  src/doc/en/developer/coding_basics.rst
Labels: s: positive review

#38207 Rename PolynomialRing_general to PolynomialRing_generic
  src/sage/algebras/weyl_algebra.py
  src/sage/categories/drinfeld_modules.py
  src/sage/crypto/lattice.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/ext/fast_callable.pyx
  src/sage/interfaces/singular.py
  src/sage/matrix/matrix_space.py
  src/sage/modular/drinfeld_modform/ring.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/functors.py
  src/sage/rings/asymptotic/asymptotic_ring.py
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/asymptotic/growth_group.py
  src/sage/rings/asymptotic/misc.py
  src/sage/rings/cfinite_sequence.py
  src/sage/rings/derivation.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/lazy_series.py
  src/sage/rings/morphism.pyx
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/padics/padic_valuation.py
  src/sage/rings/polynomial/cyclotomic.pyx
  src/sage/rings/polynomial/flatten.py
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring_constructor.py
  src/sage/rings/power_series_pari.pyx
  src/sage/rings/power_series_ring.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/valuation/augmented_valuation.py
  src/sage/rings/valuation/developing_valuation.py
  src/sage/rings/valuation/gauss_valuation.py
  src/sage/rings/valuation/limit_valuation.py
  src/sage/rings/valuation/valuation_space.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/plane_conics/constructor.py
  src/sage/schemes/projective/projective_space.py
  src/sage/schemes/toric/fano_variety.py
  src/sage/symbolic/ring.pyx
Labels: s: positive review, p: trivial / 5, t: refactoring

#39046 add a pairing heap data structure
  src/doc/en/reference/data_structures/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/data_structures/meson.build
  src/sage/data_structures/pairing_heap.h
  src/sage/data_structures/pairing_heap.pxd
  src/sage/data_structures/pairing_heap.pyx
Labels: s: positive review

#39075 Allow more rings to be used with libsingular & rework signal detection system
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/libs/singular/singular.pxd
  src/sage/libs/singular/singular.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/quotient_ring.py
Labels: s: positive review

#39108 cython-lint cleanup in matroids
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/union_matroid.pyx
Labels: s: positive review

#39110 Fix a crash when trying to build very large Reed-Muller codes
  src/sage/coding/linear_code_no_metric.py
  src/sage/coding/reed_muller_code.py
Labels: t: bug, s: positive review, c: coding theory

#39119 `build/pkgs/ccache`: Update to 4.10.2
  build/bin/sage-dist-helpers
  build/pkgs/bliss/spkg-install.in
  build/pkgs/ccache/checksums.ini
  build/pkgs/ccache/dependencies
  build/pkgs/ccache/distros/arch.txt
  build/pkgs/ccache/package-version.txt
  build/pkgs/ccache/patches/01-apple-gcc-id.patch
  build/pkgs/ccache/spkg-install.in
  build/pkgs/dsdp/spkg-install.in
  build/pkgs/primecount/spkg-install.in
  build/pkgs/primesieve/spkg-install.in
  build/pkgs/qhull/spkg-install.in
  build/pkgs/scip/spkg-install.in
  build/pkgs/scip_sdp/spkg-install.in
  build/pkgs/suitesparse/spkg-install.in
  build/pkgs/symengine/spkg-install.in
  src/doc/en/developer/packaging.rst
Labels: s: positive review, c: packages: optional

#39120 `build/pkgs/cmake`: Update to 3.31.2
  build/pkgs/cmake/checksums.ini
  build/pkgs/cmake/package-version.txt
Labels: c: packages: standard, s: positive review

#39125 some care for pep8 E262 (comments)
  src/sage/categories/category_with_axiom.py
  src/sage/categories/groupoid.py
  src/sage/categories/unital_algebras.py
  src/sage/coding/guruswami_sudan/interpolation.py
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/growth.py
  src/sage/combinat/k_tableau.py
  src/sage/combinat/partition_kleshchev.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/six_vertex_model.py
  src/sage/databases/db_class_polynomials.py
  src/sage/features/ffmpeg.py
  src/sage/geometry/hyperbolic_space/hyperbolic_isometry.py
  src/sage/geometry/polyhedron/modules/formal_polyhedra_module.py
  src/sage/manifolds/differentiable/automorphismfield.py
  src/sage/manifolds/differentiable/integrated_curve.py
  src/sage/manifolds/differentiable/tensorfield_paral.py
  src/sage/manifolds/differentiable/vectorframe.py
  src/sage/matroids/chow_ring_ideal.py
  src/sage/numerical/backends/logging_backend.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/plot/hyperbolic_regular_polygon.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/padics/relative_extension_leaves.py
  src/sage/tensor/modules/comp.py
Labels: s: positive review, t: refactoring

#39129 More information on build from source using meson
  src/doc/en/installation/meson.rst
Labels: s: positive review

#39131 avoid some imports of rings.Ring
  src/sage/graphs/chrompoly.pyx
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/rings/number_field/number_field.py
Labels: s: positive review

#39132 fixing pep8 E203 in pyx files
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/stats/time_series.pyx
Labels: s: positive review

#39133 Even less integral domain
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring.py
Labels: s: positive review, t: refactoring

#39134 a few details in master reference file
  src/doc/en/reference/references/index.rst
Labels: s: positive review, c: documentation

#39135 Fix ginac's ratlog method so log(int(0),2) does not hang
  src/sage/misc/functional.py
  src/sage/symbolic/ginac/numeric.cpp
Labels: s: positive review

#39143 fix linter warnings in sage_setup and sage_docbuild
  src/sage_docbuild/conf.py
  src/sage_docbuild/ext/sage_autodoc.py
  src/sage_setup/autogen/interpreters/internal/instructions.py
  src/sage_setup/autogen/interpreters/internal/memory.py
  src/sage_setup/autogen/interpreters/internal/specs/cc.py
  src/sage_setup/autogen/interpreters/internal/storage.py
  src/sage_setup/command/sage_build_cython.py
  src/sage_setup/command/sage_build_ext.py
  src/sage_setup/excepthook.py
  src/sage_setup/find.py
  src/sage_setup/run_parallel.py
  src/sage_setup/setenv.py
Labels: s: positive review, p: CI Fix

#39145 Don't use count as a positional argument in re.sub
  src/sage/interfaces/singular.py
  src/sage/misc/cython.py
  src/sage/rings/ring_extension_morphism.pyx
Labels: s: positive review

#39150 Fix a bug in Khuri-Makdisi small model of Jacobian
  src/sage/rings/function_field/khuri_makdisi.pyx
Labels: t: bug, s: positive review, c: algebraic geometry
