Repository sagemath/sage, pull requests merged in 2024-04, with the labels that each got.

#37707 Implement an iterator for absolute number fields
  src/sage/rings/number_field/number_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: number fields

#37763 Fix tolerance for scipy 1.13
  src/sage/matrix/matrix_double_dense.pyx
Labels: s: positive review, p: blocker / 1

#37497 remove zombie code
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
Labels: t: bug, s: positive review, c: linear algebra

#37546 Sphinx ext links for Sage source files
  src/doc/de/tutorial/sagetex.rst
  src/doc/en/developer/coding_basics.rst
  src/doc/en/developer/coding_in_other.rst
  src/doc/en/developer/coding_in_python.rst
  src/doc/en/developer/doctesting.rst
  src/doc/en/developer/packaging.rst
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/en/developer/portability_testing.rst
  src/doc/en/developer/sage_manuals.rst
  src/doc/en/developer/tools.rst
  src/doc/en/installation/source.rst
  src/doc/en/reference/repl/startup.rst
  src/doc/en/thematic_tutorials/group_theory.rst
  src/doc/en/tutorial/sagetex.rst
  src/doc/fr/tutorial/sagetex.rst
  src/doc/it/faq/faq-general.rst
  src/doc/ja/tutorial/sagetex.rst
  src/doc/pt/tutorial/sagetex.rst
  src/doc/ru/tutorial/sagetex.rst
  src/sage/misc/sagedoc.py
Labels: s: positive review, c: documentation

#37639 add Legendre transform and suspension for lazy symmetric functions
  src/sage/rings/lazy_series.py
Labels: s: positive review, c: combinatorics

#37661 some cross-references btw doc of RR, RBF, ...
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_interval_field.py
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/real_arb.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
Labels: c: basic arithmetic, s: positive review, c: documentation

#37120 build/pkgs/*/distros/pyodide.txt: New, corresponding to pyodide 0.25.0
  build/pkgs/boost_cropped/distros/pyodide.txt
  build/pkgs/ffmpeg/distros/pyodide.txt
  build/pkgs/glpk/distros/pyodide.txt
  build/pkgs/gmp/distros/pyodide.txt
  build/pkgs/gsl/distros/pyodide.txt
  build/pkgs/iconv/distros/pyodide.txt
  build/pkgs/liblzma/distros/pyodide.txt
  build/pkgs/libxml2/distros/pyodide.txt
  build/pkgs/mpc/distros/pyodide.txt
  build/pkgs/mpfr/distros/pyodide.txt
  build/pkgs/openblas/distros/pyodide.txt
  build/pkgs/openssl/distros/pyodide.txt
  build/pkgs/suitesparse/distros/pyodide.txt
  build/pkgs/zlib/distros/pyodide.txt
Labels: p: minor / 4, s: positive review, c: documentation, c: porting

#37266 Scipy 1.12
  build/pkgs/pythran/checksums.ini
  build/pkgs/pythran/package-version.txt
  build/pkgs/scipy/checksums.ini
  build/pkgs/scipy/package-version.txt
  build/pkgs/scipy/patches/numpy-include.patch
Labels: c: packages: standard, s: positive review

#37332 Cleaning in pautomorphicform.py
  src/sage/modular/btquotients/pautomorphicform.py
Labels: s: positive review, c: modular forms, p: trivial / 5, t: refactoring

#37340 Add class FlatsMatroid
  src/doc/en/reference/matroids/index.rst
  src/sage/matroids/advanced.py
  src/sage/matroids/constructor.py
  src/sage/matroids/flats_matroid.pxd
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/unpickling.pyx
Labels: s: positive review, c: matroid theory

#37391 Make installation of "wheel" packages less noisy
  build/bin/sage-dist-helpers
  build/bin/sage-logger
  build/bin/sage-spkg
  build/make/install
  build/pkgs/sagelib/spkg-install.in
  build/sage_bootstrap/uninstall.py
  src/doc/en/developer/packaging.rst
Labels: s: positive review, c: build

#36390 add simple function to count irreducible polynomials over 𝔽q
  src/doc/en/reference/references/index.rst
  src/sage/combinat/all.py
  src/sage/combinat/q_analogues.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#36965 Update system package info for slackware
  build/pkgs/_prereq/distros/slackware.txt
Labels: p: minor / 4, s: positive review, c: porting

#37615 Removed `BUG` method and include a docstring for `matrix_of_frobenius()`
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_rational_field.py
Labels: p: minor / 4, s: positive review, c: algebraic geometry, t: refactoring

#37644 Corrections in `.normalize_basis_at_p` and `.maximal_order()` of `quaternion_algebra.py`
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#37648 `sage.doctest`: Remove most uses of SAGE_SRC in doctests
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
  src/sage/doctest/reporting.py
  src/sage/doctest/sources.py
Labels: s: positive review, t: tests, c: doctest framework

#37665 `cypari2` 2.1.5, `memory_allocator` 0.1.4
  build/pkgs/cypari/checksums.ini
  build/pkgs/cypari/package-version.txt
  build/pkgs/memory_allocator/checksums.ini
  build/pkgs/memory_allocator/package-version.txt
Labels: c: packages: standard, s: positive review

#37670 Make matroid `copy` and `deepcopy` simply return `self`
  src/sage/matroids/advanced.py
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/graphic_matroid.py
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/minor_matroid.py
  src/sage/matroids/rank_matroid.py
Labels: s: positive review, c: matroid theory, t: refactoring

#37682 Implement the normalizer of a finite dimensional Lie algebra
  src/sage/algebras/lie_algebras/subalgebra.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: t: enhancement, s: positive review, c: algebra

#37687 provide a construction functor using a single functor for families
  src/sage/combinat/sf/dual.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/sf/witt.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: categories

#37710 Implement the Jordan decomposition of a matrix and is_semisimple() test
  src/sage/matrix/matrix2.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: linear algebra

#37724 Implement faithful representations of nilpotent Lie algebras
  src/doc/en/reference/references/index.rst
  src/sage/algebras/lie_algebras/representation.py
  src/sage/algebras/lie_algebras/structure_coefficients.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: t: enhancement, s: positive review, c: algebra

#37740 Disable most documentation notifications on GitHub
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/doc-publish.yml
Labels: s: positive review, disputed

#37746 clean suffix tries
  src/sage/combinat/words/suffix_trees.py
Labels: s: positive review, c: combinatorics

#37769 `src/sage/modules/with_basis/representation.py`: pycodestyle fix
  src/sage/modules/with_basis/representation.py
Labels: s: positive review, p: blocker / 1, p: CI Fix

#37771 some C4 fixes in combinat folder
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/arith/functions.pyx
  src/sage/combinat/sloane_functions.py
  src/sage/combinat/species/partition_species.py
  src/sage/combinat/subset.py
  src/sage/combinat/subword_complex.py
  src/sage/combinat/superpartition.py
  src/sage/combinat/tableau_residues.py
  src/sage/combinat/tableau_tuple.py
  src/sage/combinat/tamari_lattices.py
  src/sage/combinat/tiling.py
  src/sage/combinat/tuple.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/morphism.py
  src/sage/combinat/yang_baxter_graph.py
Labels: s: positive review, c: combinatorics

#37119 Implement `EllipticCurve_with_order`
  src/doc/en/reference/references/index.rst
  src/sage/quadratic_forms/binary_qf.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#37247 Miscellaneous system package updates
  build/pkgs/appnope/spkg-configure.m4
  build/pkgs/exceptiongroup/spkg-configure.m4
  build/pkgs/exceptiongroup/version_requirements.txt
  configure.ac
  src/sage/groups/abelian_gps/abelian_group.py
Labels: c: packages: standard, s: positive review

#37291 Support optional debugpy
  build/pkgs/debugpy/distros/gentoo.txt
  build/pkgs/debugpy/spkg-configure.m4
Labels: s: positive review, c: build: configure

#37351 CI: Update Linux platforms / runners, remove `ubuntu-trusty`, `opensuse-{15.3,15.4}`
  .devcontainer/portability-fedora-40-minimal/devcontainer.json
  .devcontainer/portability-fedora-40-minimal/portability-Dockerfile
  .devcontainer/portability-fedora-40-standard/devcontainer.json
  .devcontainer/portability-fedora-40-standard/portability-Dockerfile
  .devcontainer/portability-gentoo-python3.12-minimal/devcontainer.json
  .devcontainer/portability-gentoo-python3.12-minimal/portability-Dockerfile
  .devcontainer/portability-gentoo-python3.12-standard/devcontainer.json
  .devcontainer/portability-gentoo-python3.12-standard/portability-Dockerfile
  .devcontainer/portability-linuxmint-21.3-minimal/devcontainer.json
  .devcontainer/portability-linuxmint-21.3-minimal/portability-Dockerfile
  .devcontainer/portability-linuxmint-21.3-standard/devcontainer.json
  .devcontainer/portability-linuxmint-21.3-standard/portability-Dockerfile
  .devcontainer/portability-ubuntu-noble-minimal/devcontainer.json
  .devcontainer/portability-ubuntu-noble-minimal/portability-Dockerfile
  .devcontainer/portability-ubuntu-noble-standard/devcontainer.json
  .devcontainer/portability-ubuntu-noble-standard/portability-Dockerfile
  .github/workflows/build.yml
  .github/workflows/ci-conda.yml
  .github/workflows/ci-linux.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/docker.yml
  src/doc/en/developer/portability_platform_table.rst
  tox.ini
Labels: s: positive review, p: critical / 2, c: scripts, disputed

#37451 combinat/free module tensor construction
  src/sage/combinat/free_module.py
Labels: s: positive review, c: combinatorics, c: algebra

#37462 Add Temperley-Lieb algebras to the category of cellular algebras
  src/sage/combinat/diagram_algebras.py
  src/sage/modules/with_basis/indexed_element.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37506 Improving the documentation of Discrete Dynamical Systems by fixing typos and eliminating repeated sentences
  src/sage/dynamics/finite_dynamical_system.py
Labels: s: positive review, c: documentation, c: dynamics

#37733 Bell polynomials univariate variable fix, complete and ordinary variants
  src/doc/en/reference/references/index.rst
  src/sage/combinat/combinat.py
Labels: t: enhancement, s: positive review, c: combinatorics

#37757 dft for symmetric group algebra when p|n!
  src/sage/combinat/symmetric_group_algebra.py
Labels: t: bug, s: positive review, c: combinatorics, c: algebra

#37773 Allow construction of classical Lie algebras over finite fields
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#37781 `SetPartition` return empty iterator instead of erroring out in degenerate cases
  src/sage/combinat/set_partition.py
  src/sage/combinat/set_partition_iterator.pyx
Labels: t: enhancement, s: positive review, c: combinatorics

#37783 various changes about is_field and is_ring
  src/sage/combinat/descent_algebra.py
  src/sage/geometry/polyhedron/parent.py
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/modular/ssmod/ssmod.py
  src/sage/tests/books/computational-mathematics-with-sagemath/polynomes_doctest.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review, c: algebra, t: refactoring

#37784 Speed up symmetric group simple_module_rank()
  src/sage/combinat/specht_module.py
Labels: p: major / 3, s: positive review, c: combinatorics, t: performance, c: algebra

#37789 various ruff fixes in groups (PERF, etc)
  src/sage/groups/additive_abelian/additive_abelian_wrapper.py
  src/sage/groups/braid.py
  src/sage/groups/class_function.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/generic.py
  src/sage/groups/kernel_subgroup.py
  src/sage/groups/libgap_mixin.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/groups/matrix_gps/orthogonal.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/groups/semimonomial_transformations/semimonomial_transformation_group.py
Labels: s: positive review, c: group theory, t: refactoring

#37441 Bind to FLINT/NTL API for polynomial modular exponentiation (new version)
  src/sage/libs/ntl/ntl_ZZ_pX.pxd
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pxd
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/polynomial/polynomial_zz_pex.pxd
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
Labels: p: major / 3, s: positive review, t: performance, c: algebra

#37486 sagemath-{objects,categories} `pyproject.toml`: Add 'external' section according to draft PEP 725
  pkgs/sagemath-categories/pyproject.toml.m4
  pkgs/sagemath-objects/pyproject.toml.m4
Labels: s: positive review, c: distribution

#37503 GH Actions: Build macOS arm64 wheels
  .github/workflows/dist.yml
Labels: s: positive review, c: scripts, c: distribution

#37510 src/doc/*/tutorial/programming.rst: Update 'standalone script'
  src/doc/de/tutorial/programming.rst
  src/doc/en/tutorial/programming.rst
  src/doc/fr/tutorial/programming.rst
  src/doc/ja/tutorial/programming.rst
  src/doc/pt/tutorial/programming.rst
  src/doc/ru/tutorial/programming.rst
Labels: s: positive review, c: documentation, p: trivial / 5

#37512 FiniteRankFreeModule.isomorphism_with_fixed_basis: Make it an actual isomorphism
  src/sage/categories/map.pyx
  src/sage/categories/morphism.pxd
  src/sage/categories/morphism.pyx
  src/sage/tensor/modules/finite_rank_free_module.py
Labels: s: positive review, c: linear algebra

#37513 Define the zero polynomial to have degree `-Infinity` for `LaurentPolynomialRing`
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
Labels: s: positive review, c: commutative algebra

#37514 `MatrixSpace`: Support constructing `Hom(CombinatorialFreeModule)`
  src/sage/matrix/args.pyx
  src/sage/matrix/constructor.pyx
  src/sage/matrix/matrix_space.py
  src/sage/modules/free_module.py
Labels: s: positive review, c: linear algebra

#37582 build/pkgs/{gdb,gmp,libgd,python3,symmetrica}: Reduce xz to order-only dep
  build/pkgs/gdb/dependencies
  build/pkgs/gmp/dependencies
  build/pkgs/libgd/dependencies
  build/pkgs/python3/dependencies
  build/pkgs/symmetrica/dependencies
Labels: c: packages: standard, s: positive review, c: build

#37675 Allow `.maximal_order()` of `quaternion_algebra.py` to extend a given order
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#37676 pep8 and ruff fixes in the plot folder
  src/sage/plot/animate.py
  src/sage/plot/arc.py
  src/sage/plot/arrow.py
  src/sage/plot/bezier_path.py
  src/sage/plot/circle.py
  src/sage/plot/colors.py
  src/sage/plot/density_plot.py
  src/sage/plot/disk.py
  src/sage/plot/ellipse.py
  src/sage/plot/graphics.py
  src/sage/plot/histogram.py
  src/sage/plot/hyperbolic_arc.py
  src/sage/plot/hyperbolic_polygon.py
  src/sage/plot/hyperbolic_regular_polygon.py
  src/sage/plot/matrix_plot.py
  src/sage/plot/multigraphics.py
  src/sage/plot/plot.py
  src/sage/plot/plot3d/list_plot3d.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/plot/plot3d/revolution_plot3d.py
  src/sage/plot/plot3d/shapes2.py
  src/sage/plot/plot3d/tachyon.py
  src/sage/plot/plot3d/texture.py
  src/sage/plot/plot3d/tri_plot.py
  src/sage/plot/plot_field.py
  src/sage/plot/primitive.py
  src/sage/plot/text.py
Labels: s: positive review, c: graphics, t: refactoring

#37684 fix ascii_art of empty chain complex
  src/sage/homology/chain_complex.py
Labels: t: bug, s: positive review, c: algebraic topology

#37714 `sage.modular`: Docstring/doctest cosmetics
  src/sage/modular/arithgroup/arithgroup_element.pyx
  src/sage/modular/cusps_nf.py
  src/sage/modular/dirichlet.py
  src/sage/modular/hypergeometric_motive.py
  src/sage/modular/modform/ambient_R.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform_hecketriangle/graded_ring_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/modsym/p1list_nf.py
  src/sage/modular/overconvergent/genus0.py
Labels: s: positive review, c: documentation, c: modular forms

#37731 `MatrixMorphism_abstract`: Move endomorphism invariants to category
  src/sage/categories/finite_dimensional_modules_with_basis.py
  src/sage/categories/modules_with_basis.py
  src/sage/geometry/fan_morphism.py
  src/sage/modular/abvar/morphism.py
  src/sage/modules/free_module_morphism.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/vector_space_homspace.py
  src/sage/modules/vector_space_morphism.py
Labels: s: positive review, c: linear algebra

#37747 be more specific when raising "not a constant polynomial"
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/action.pyx
  src/sage/categories/map.pyx
  src/sage/categories/modules_with_basis.py
  src/sage/combinat/sf/sfa.py
  src/sage/dynamics/arithmetic_dynamics/dynamical_semigroup.py
  src/sage/matrix/matrix1.pyx
  src/sage/rings/polynomial/ore_function_element.py
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
Labels: s: positive review, c: commutative algebra

#37766 modules with basis/map coefficients
  src/sage/categories/modules_with_basis.py
Labels: s: positive review, c: categories

#37775 Add matroid `relabel`
  src/sage/matroids/basis_exchange_matroid.pxd
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pxd
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pxd
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pxd
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/database_matroids.py
  src/sage/matroids/flats_matroid.pxd
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/graphic_matroid.py
  src/sage/matroids/linear_matroid.pxd
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
  src/sage/matroids/set_system.pxd
  src/sage/matroids/set_system.pyx
Labels: t: feature, s: positive review, c: matroid theory

#37785 `sage-logger`: Suppress "No such file or directory" messages
  build/bin/sage-logger
Labels: p: minor / 4, s: positive review, c: build

#36869 `m4/pyproject_toml_metadata.m4`: Allow Python 3.12
  m4/pyproject_toml_metadata.m4
  m4/setup_cfg_metadata.m4
  pkgs/sage-docbuild/pyproject.toml
  pkgs/sage-setup/pyproject.toml
Labels: s: positive review, c: distribution, disputed

#37262 Added automatic size labeler
  .github/workflows/pr-labeler.yml
  .github/workflows/set_labels_by_changes.sh
Labels: s: positive review, c: scripts

#35467 Attach Jacobians to function fields and curves
  src/doc/en/reference/curves/index.rst
  src/doc/en/reference/function_fields/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/categories/all.py
  src/sage/categories/category.py
  src/sage/categories/schemes.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/function_field.py
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/function_field/jacobian_base.py
  src/sage/rings/function_field/jacobian_hess.py
  src/sage/rings/function_field/jacobian_khuri_makdisi.py
  src/sage/rings/function_field/khuri_makdisi.pyx
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/jacobian.py
  src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
  src/sage/schemes/jacobians/abstract_jacobian.py
Labels: s: positive review, c: algebraic geometry
