Repository sagemath/sage, pull requests merged in 2024-01, with the labels that each got.

#36877 Improve code style for matrix2.pyx file
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#36878 polymake 4.11
  build/pkgs/polymake/SPKG.rst
  build/pkgs/polymake/checksums.ini
  build/pkgs/polymake/dependencies
  build/pkgs/polymake/dependencies_optional
  build/pkgs/polymake/package-version.txt
  src/sage/geometry/polyhedron/base.py
Labels: s: positive review, c: packages: optional, c: geometry

#36889 more libgap in permutation groups ; get rid of _libgap_init_
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/combinat/matrices/latin.py
  src/sage/combinat/permutation.py
  src/sage/groups/class_function.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/groups/perm_gps/permgroup_morphism.py
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/libgap.pyx
  src/sage/modules/with_basis/invariant.py
  src/sage/structure/sage_object.pyx
  src/sage/tests/books/judson-abstract-algebra/homomorph-sage.py
Labels: s: positive review, c: interfaces

#36893 get rid of one ParentWithGens
  src/sage/rings/polynomial/ore_polynomial_element.pyx
Labels: s: positive review, c: algebra

#36921 various details in normaliz backend interface
  src/sage/geometry/polyhedron/backend_normaliz.py
Labels: s: positive review, c: interfaces: optional, t: refactoring

#36922 using less isinstance(..., Ring)
  src/sage/algebras/affine_nil_temperley_lieb.py
  src/sage/algebras/lie_algebras/lie_algebra.py
  src/sage/algebras/splitting_algebra.py
  src/sage/modular/abvar/homspace.py
  src/sage/modular/modform/space.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/boundary.py
  src/sage/modular/modsym/relation_matrix.py
Labels: s: positive review, c: categories, t: refactoring

#36933 More conversion to parent
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/real_mpfr.pyx
Labels: s: positive review, c: categories, t: refactoring

#36936 `src/sage/doctest/forker.py`: Show '# [failed in baseline]' earlier
  src/bin/sage-runtests
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
  src/sage/doctest/reporting.py
Labels: p: minor / 4, s: positive review, c: doctest framework, p: blocker / 1

#36940 new method "fraction" in integer-valued polynomials
  src/sage/rings/polynomial/integer_valued_polynomials.py
Labels: t: enhancement, s: positive review, c: commutative algebra

#36947 `sage -package download`: Fix argparse for `--no-check-certificate`
  build/sage_bootstrap/cmdline.py
Labels: t: bug, s: positive review, p: blocker / 1, c: scripts

#36957 tox.ini: Update voidlinux, update installation guide
  build/bin/write-dockerfile.sh
  build/pkgs/_prereq/distros/void.txt
  build/pkgs/_python3.11/distros/void.txt
  build/pkgs/python3/SPKG.rst
  build/pkgs/python3/spkg-configure.m4
  src/doc/bootstrap
  src/doc/en/installation/index.rst
  src/doc/en/installation/linux.rst
  src/doc/en/installation/source.rst
  tox.ini
Labels: s: positive review, c: documentation, c: scripts

#36959 `.devcontainer/downstream-archlinux-latest`: Fix maxima
  .devcontainer/downstream-archlinux-latest/devcontainer.json
Labels: s: positive review, c: docker

#36962 Add is_(sparse_)paving() and automorphism_group()
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
Labels: t: enhancement, s: positive review, c: matroid theory

#36963 some care for pep8 code E241 in some pyx files
  src/sage/coding/codecan/codecan.pyx
  src/sage/combinat/crystals/tensor_product_element.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/double_coset.pyx
  src/sage/matrix/action.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/misc/parser.pyx
  src/sage/numerical/sdp.pyx
  src/sage/plot/plot3d/shapes.pyx
  src/sage/quadratic_forms/ternary.pyx
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
  src/sage/stats/hmm/distributions.pyx
  src/sage/symbolic/expression.pyx
Labels: s: positive review, t: refactoring

#36967 fixing some details in graphs/ (pep E275; ruff UP024, etc)
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/digraph.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_decompositions/modular_decomposition.py
  src/sage/graphs/graph_generators.py
  src/sage/graphs/graph_latex.py
  src/sage/graphs/isgci.py
  src/sage/graphs/schnyder.py
Labels: s: positive review, c: graph theory, t: refactoring

#36976 Fix doctests in `src/sage/databases/oeis.py`
  src/sage/databases/oeis.py
Labels: s: positive review, c: databases

#36977 `sage --package metrics`: New tool to assist discussions of the Sage distribution
  .github/workflows/ci-linux-incremental.yml
  build/pkgs/tzdata/checksums.ini
  build/pkgs/tzdata/package-version.txt
  build/pkgs/tzdata/spkg-install.in
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
  build/sage_bootstrap/package.py
  src/doc/en/developer/packaging.rst
Labels: c: packages: standard, s: positive review, c: documentation, c: scripts

#36979 Fix `sage-get-system-packages install-requires` after #29665
  bootstrap
  build/bin/sage-get-system-packages
Labels: s: positive review, p: critical / 2, c: build

#35986 Use conda-lock for reproducible conda env
  .devcontainer/devcontainer.json
  .devcontainer/onCreate-conda.sh
  .github/workflows/ci-conda.yml
  .github/workflows/conda-lock-update.py
  .gitpod.yml
  .vscode/settings.json
  bootstrap-conda
  build/pkgs/sphinx/distros/conda.txt
  environment-3.10-linux-aarch.yml
  environment-3.10-linux-aarch64.yml
  environment-3.10-linux.yml
  environment-3.10-macos-arm.yml
  environment-3.10-macos-arm64.yml
  environment-3.10-macos.yml
  environment-3.11-linux-aarch.yml
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-arm.yml
  environment-3.11-macos-arm64.yml
  environment-3.11-macos.yml
  environment-3.9-linux-aarch.yml
  environment-3.9-linux-aarch64.yml
  environment-3.9-linux.yml
  environment-3.9-macos-arm.yml
  environment-3.9-macos-arm64.yml
  environment-3.9-macos.yml
  src/doc/en/installation/conda.rst
  src/environment-3.10-linux-aarch64.yml
  src/environment-3.10-linux.yml
  src/environment-3.10-macos-arm64.yml
  src/environment-3.10-macos.yml
  src/environment-3.11-linux-aarch64.yml
  src/environment-3.11-linux.yml
  src/environment-3.11-macos-arm64.yml
  src/environment-3.11-macos.yml
  src/environment-3.9-linux-aarch.yml
  src/environment-3.9-linux-aarch64.yml
  src/environment-3.9-linux.yml
  src/environment-3.9-macos-arm64.yml
  src/environment-3.9-macos.yml
  src/environment-dev-3.10-linux-aarch64.yml
  src/environment-dev-3.10-linux.yml
  src/environment-dev-3.10-macos-arm64.yml
  src/environment-dev-3.10-macos.yml
  src/environment-dev-3.11-linux-aarch64.yml
  src/environment-dev-3.11-linux.yml
  src/environment-dev-3.11-macos-arm64.yml
  src/environment-dev-3.11-macos.yml
  src/environment-dev-3.9-linux-aarch64.yml
  src/environment-dev-3.9-linux.yml
  src/environment-dev-3.9-macos-arm64.yml
  src/environment-dev-3.9-macos.yml
  src/pyproject.toml.m4
Labels: s: positive review, p: critical / 2

#36351 `gmp` 6.3.0, `mpc` 1.3.1, `mpfr` 4.2.1, `mpfrcx` 0.6.3, `gmpy2` 2.2.0a1
  build/pkgs/gmp/checksums.ini
  build/pkgs/gmp/package-version.txt
  build/pkgs/gmpy2/SPKG.rst
  build/pkgs/gmpy2/checksums.ini
  build/pkgs/gmpy2/dependencies_check
  build/pkgs/gmpy2/install-requires.txt
  build/pkgs/gmpy2/package-version.txt
  build/pkgs/hypothesis/SPKG.rst
  build/pkgs/hypothesis/dependencies
  build/pkgs/hypothesis/requirements.txt
  build/pkgs/hypothesis/type
  build/pkgs/mpc/checksums.ini
  build/pkgs/mpc/distros/repology.txt
  build/pkgs/mpc/package-version.txt
  build/pkgs/mpc/spkg-configure.m4
  build/pkgs/mpfr/checksums.ini
  build/pkgs/mpfr/package-version.txt
  build/pkgs/mpfr/spkg-configure.m4
  build/pkgs/mpfrcx/checksums.ini
  build/pkgs/mpfrcx/package-version.txt
Labels: c: packages: standard, s: positive review

#36456 implement .interpolation() method for ProductTree
  src/sage/rings/generic.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#36591 Test that everything can be imported during ci
  .github/workflows/build.yml
  .vscode/launch.json
  src/bin/sage
  src/conftest.py
Labels: s: positive review, c: scripts

#36651 enhancements in infinite polynomial rings
  src/sage/rings/polynomial/infinite_polynomial_ring.py
Labels: s: positive review, c: commutative algebra

#36759 allow passing a generating set (not necessarily a basis) for quaternion ideals
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#36760 print more information about number-field orders
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/nf_orders.rst
  src/sage/categories/homset.py
  src/sage/categories/pushout.py
  src/sage/categories/quotient_fields.py
  src/sage/categories/rings.py
  src/sage/matrix/matrix2.pyx
  src/sage/misc/functional.py
  src/sage/modular/dirichlet.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/modular/modform_hecketriangle/readme.py
  src/sage/modules/free_module.py
  src/sage/rings/complex_interval_field.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/number_field/class_group.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_base.pyx
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/number_field/order.py
  src/sage/rings/padics/padic_extension_generic.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/ring.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_element.pyx
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/structure/category_object.pyx
  src/sage/structure/formal_sum.py
  src/sage/tests/books/judson-abstract-algebra/domains-sage.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: number fields

#36776 Skip backport packages for newer python
  build/pkgs/importlib_metadata/install-requires.txt
  build/pkgs/importlib_resources/install-requires.txt
  build/pkgs/typing_extensions/install-requires.txt
  m4/sage_python_package_check.m4
Labels: s: positive review, c: build: configure

#36789 Make "large multiplication" larger in coerce_actions.pyx
  src/sage/structure/coerce_actions.pyx
Labels: s: positive review, t: tests, p: blocker / 1

#36796 rename 'divided difference operator'
  src/sage/algebras/quantum_groups/fock_space.py
Labels: t: enhancement, s: positive review, c: documentation

#36806 add generic has_order() function
  src/sage/groups/generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: p: major / 3, t: enhancement, s: positive review, c: group theory

#36829 CI Linux incremental: `make reconfigure` after uninstalling packages
  .github/workflows/ci-linux-incremental.yml
  Makefile
  m4/sage_spkg_collect.m4
  src/doc/en/developer/portability_testing.rst
Labels: s: positive review, c: scripts

#36841 Change default domain of SR.var()
  src/sage/symbolic/ring.pyx
Labels: s: positive review, c: calculus

#36857 use unicode characters to display tables
  src/doc/en/prep/Programming.rst
  src/sage/combinat/bijectionist.py
  src/sage/misc/table.py
  src/sage/schemes/toric/morphism.py
  src/sage/tests/gap_packages.py
Labels: s: positive review, c: documentation

#36918 Remove `spkg-src` scripts for packages with real upstream url
  build/pkgs/glpk/patches/src/01-zlib.patch
  build/pkgs/glpk/spkg-src
  build/pkgs/matplotlib/spkg-src
  build/pkgs/python_igraph/spkg-src
Labels: s: positive review, c: distribution

#36928 `build/pkgs/cython`: Update to 3.0.7
  build/pkgs/cython/checksums.ini
  build/pkgs/cython/package-version.txt
Labels: c: packages: standard, s: positive review

#37038 Add minimal_normal_subgroups and maximal_normal_subgroups functions for permutation groups
  src/sage/groups/libgap_wrapper.pyx
  src/sage/groups/perm_gps/permgroup.py
Labels: t: enhancement, s: positive review, c: group theory

#37043 src/sage/matrix/matrix_double_dense.pyx: increase an FP tolerance
  src/sage/matrix/matrix_double_dense.pyx
Labels: s: positive review, c: linear algebra, t: tests

#37044 update ECL to 23.9.9, remove obsolete stuff from spkg-install
  build/pkgs/ecl/checksums.ini
  build/pkgs/ecl/package-version.txt
  build/pkgs/ecl/spkg-install.in
Labels: c: packages: standard, s: positive review

#37053 Add reverse Cuthill-McKee ordering for graphs
  src/sage/graphs/base/boost_graph.pyx
Labels: t: enhancement, s: positive review, c: graph theory

#37062 clean singular interface (full pep8) + use standard open and zip
  src/sage/interfaces/gap.py
  src/sage/interfaces/singular.py
  src/sage/rings/asymptotic/asymptotic_ring.py
  src/sage/rings/asymptotic/growth_group_cartesian.py
  src/sage/rings/number_field/number_field.py
  src/sage/sets/cartesian_product.py
Labels: s: positive review, c: interfaces, t: refactoring

#37063 some little changes in polynomials (ruff PERF)
  src/sage/rings/polynomial/binary_form_reduce.py
  src/sage/rings/polynomial/complex_roots.py
  src/sage/rings/polynomial/groebner_fan.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/pbori/blocks.py
  src/sage/rings/polynomial/pbori/cnf.py
  src/sage/rings/polynomial/pbori/easy_polynomials.py
  src/sage/rings/polynomial/pbori/gbcore.py
  src/sage/rings/polynomial/pbori/randompoly.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/toy_variety.py
Labels: s: positive review, c: commutative algebra, t: refactoring

#37064 Fix build when linbox is build with fplll support
  src/sage/libs/flint/flint_wrap.h
Labels: s: positive review

#37069 Use Parent in number fields and QQ
  src/sage/rings/number_field/number_field.py
  src/sage/rings/rational_field.py
Labels: s: positive review, c: number fields, t: refactoring

#37070 use directly OSError everywhere
  src/sage/databases/cremona.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/databases/db_modular_polynomials.py
  src/sage/databases/findstat.py
  src/sage/databases/jones.py
  src/sage/databases/oeis.py
  src/sage/databases/sloane.py
  src/sage/databases/stein_watkins.py
  src/sage/databases/symbolic_data.py
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
  src/sage/doctest/sources.py
  src/sage/interfaces/axiom.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/four_ti_2.py
  src/sage/interfaces/fricas.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/giac.py
  src/sage/interfaces/lie.py
  src/sage/interfaces/magma.py
  src/sage/interfaces/maple.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/interfaces/mupad.py
  src/sage/interfaces/quit.py
  src/sage/interfaces/r.py
  src/sage/parallel/use_fork.py
  src/sage/repl/image.py
  src/sage/repl/inputhook.py
  src/sage/repl/ipython_extension.py
  src/sage/repl/load.py
  src/sage/sandpiles/sandpile.py
  src/sage/sets/set_from_iterator.py
  src/sage_docbuild/builders.py
  src/sage_docbuild/ext/inventory_builder.py
  src/sage_docbuild/ext/multidocs.py
  src/sage_setup/autogen/interpreters/utils.py
  src/sage_setup/command/sage_build_cython.py
Labels: s: positive review, t: refactoring

#37072 some cleanup in overconvergent and quaternion
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/overconvergent/genus0.py
Labels: s: positive review, c: modular forms, c: algebra

#37074 implement natural morphism from cl(f²D) to cl(D)
  src/sage/quadratic_forms/bqf_class_group.py
Labels: p: major / 3, t: enhancement, s: positive review, c: quadratic forms

#37078 use parent in weyl_algebra.py
  src/sage/algebras/weyl_algebra.py
Labels: s: positive review, c: algebra

#37079 use Parent in Monsky-Washnitzer
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
Labels: s: positive review, c: algebraic geometry

#37081 convenience method to construct elliptic-curve isomorphisms from u,r,s,t
  src/sage/schemes/elliptic_curves/ell_generic.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: elliptic curves

#37082 Fix NumberFieldElement_quadratic.is_integral() when D is not square-free
  src/sage/rings/number_field/number_field_element_quadratic.pyx
Labels: t: bug, s: positive review, c: number fields

#37085 remove entirely the legacy class EuclideanDomain
  src/sage/rings/abc.pyx
  src/sage/rings/all.py
  src/sage/rings/ring.pxd
  src/sage/rings/ring.pyx
Labels: s: positive review, c: categories

#37094 Fix bug with pari interface in `classical_modular_polynomial`
  src/sage/schemes/elliptic_curves/mod_poly.py
Labels: p: major / 3, t: bug, s: positive review, c: elliptic curves

#37098 Fixed random_element() for fractional ideals in rational quaternion algebras
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#36972 add a specialized parent object for elliptic-curve morphisms
  src/sage/categories/all.py
  src/sage/categories/category.py
  src/sage/categories/schemes.py
  src/sage/doctest/forker.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/constructor.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_scalar.py
  src/sage/schemes/elliptic_curves/hom_sum.py
  src/sage/schemes/elliptic_curves/homset.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/generic/scheme.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#36986 Fixed a bug in `AbelianGroup.Subgroup.gens_orders()`, which returns the reduced order of the subgroup
  src/sage/groups/abelian_gps/abelian_group.py
Labels: p: major / 3, t: bug, s: positive review, c: group theory

#36987 Doing some cleanup on Littelmann paths
  src/sage/combinat/crystals/littelmann_path.py
Labels: t: enhancement, s: positive review, c: documentation, c: combinatorics

#36989 OS-dependent doctest tags `# known bug: macos`, `# known bug: linux`
  src/doc/en/developer/coding_basics.rst
  src/sage/doctest/control.py
  src/sage/doctest/external.py
  src/sage/doctest/parsing.py
  src/sage/doctest/parsing_test.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/structure/coerce_maps.pyx
Labels: s: positive review, c: doctest framework

#36991 Fixed doc_test in `database.findstat` by adding new collection
  src/sage/databases/findstat.py
Labels: s: positive review, c: databases

#36994 Use PARI when computing the Tate pairing
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: s: positive review, c: elliptic curves

#37001 Implement absolute length fix
  src/doc/en/reference/references/index.rst
  src/sage/categories/coxeter_groups.py
  src/sage/categories/finite_coxeter_groups.py
  src/sage/combinat/posets/poset_examples.py
Labels: p: major / 3, t: bug, t: enhancement, s: positive review, c: combinatorics

#37004 Fixes in save_session()
  src/sage/doctest/forker.py
  src/sage/misc/session.pyx
Labels: t: bug, s: positive review, c: doctest framework

#37015 Implement the Aomoto complex of the Orlik-Solomon algebra and Hilbert series for filtered modules
  src/doc/en/reference/references/index.rst
  src/sage/algebras/orlik_solomon.py
  src/sage/categories/filtered_modules_with_basis.py
  src/sage/categories/finite_dimensional_graded_lie_algebras_with_basis.py
  src/sage/categories/graded_modules_with_basis.py
Labels: p: major / 3, t: enhancement, s: positive review, c: geometry, c: algebra

#37016 typo fix
  src/sage/geometry/polyhedron/backend_field.py
Labels: s: positive review, c: doctest framework

#37017 cosmetic little change in topology/ (some ruff UP and PERF)
  src/sage/topology/cell_complex.py
  src/sage/topology/cubical_complex.py
  src/sage/topology/delta_complex.py
  src/sage/topology/moment_angle_complex.py
  src/sage/topology/simplicial_complex.py
  src/sage/topology/simplicial_complex_examples.py
  src/sage/topology/simplicial_complex_morphism.py
  src/sage/topology/simplicial_set.py
  src/sage/topology/simplicial_set_constructions.py
  src/sage/topology/simplicial_set_morphism.py
Labels: s: positive review, c: algebraic topology

#37018 `sage --package properties`
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
  build/sage_bootstrap/package.py
Labels: s: positive review, c: build

#37020 `configure`: Fix quoting in system package notice
  m4/sage_spkg_collect.m4
Labels: s: positive review

#37023 Parent in plural
  src/sage/rings/polynomial/plural.pyx
Labels: s: positive review, c: algebra

#37024 Access database and other files through features, for simpler configuration
  src/sage/combinat/designs/MOLS_handbook_data.py
  src/sage/combinat/designs/latin_squares.py
  src/sage/databases/jones.py
  src/sage/databases/sql_db.py
  src/sage/env.py
  src/sage/features/__init__.py
  src/sage/features/databases.py
  src/sage/features/jmol.py
  src/sage/features/threejs.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/palp_database.py
  src/sage/graphs/graph_database.py
  src/sage/graphs/isgci.py
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/interfaces/jmoldata.py
  src/sage/repl/ipython_kernel/install.py
  src/sage/repl/rich_output/backend_ipython.py
  src/sage/repl/rich_output/display_manager.py
  src/sage/schemes/elliptic_curves/ec_database.py
Labels: s: positive review, c: databases

#37028 add method to compute the longest (induced) cycle in a (di)graph
  src/doc/en/reference/references/index.rst
  src/sage/graphs/generic_graph.py
Labels: t: enhancement, s: positive review, c: graph theory

#37030 Small update to Developer Guide section on portability testing
  src/doc/en/developer/portability_testing.rst
Labels: s: positive review, c: documentation

#37034 raise ValueError instead of IndexError in .any_root()
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: t: bug, p: minor / 4, s: positive review, c: algebra

#37039 some details in Galois group as permutation group
  src/sage/groups/galois_group_perm.py
Labels: s: positive review, c: group theory

#37045 Added third embedding in Cubegraph for oblique projection of hypercubes
  src/sage/graphs/generators/families.py
Labels: s: positive review, c: graph theory

#37049 Dont load all GAP packages when resetting a workspace
  src/sage/ext_data/gap/sage.g
  src/sage/interfaces/gap.py
  src/sage/libs/gap/sage.gaprc
Labels: s: positive review

#35762 ideals of non-maximal orders in number fields
  src/doc/en/reference/number_fields/index.rst
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/nf_orders.rst
  src/sage/categories/pushout.py
  src/sage/rings/ideal.py
  src/sage/rings/number_field/class_group.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/order.py
  src/sage/rings/number_field/order_ideal.py
  src/sage/schemes/plane_conics/con_number_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: number fields

#36233 Implement integration and Taylor series for lazy series
  src/sage/data_structures/stream.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
Labels: p: major / 3, t: enhancement, s: positive review, c: calculus, c: commutative algebra
