Repository sagemath/sage, pull requests merged in 2024-06, with the labels that each got.

#38099 Remove deprecated global imports
  src/sage/all.py
  src/sage/arith/all.py
  src/sage/manifolds/all.py
  src/sage/misc/all.py
  src/sage/modular/all.py
Labels: s: positive review, t: refactoring, v: minimal

#38110 Update `conway_polynomials`, `database_cubic_hecke`, `database_knotinfo`, `matroid_database`
  build/pkgs/conway_polynomials/checksums.ini
  build/pkgs/conway_polynomials/dependencies
  build/pkgs/conway_polynomials/package-version.txt
  build/pkgs/conway_polynomials/spkg-install.in
  build/pkgs/database_cubic_hecke/checksums.ini
  build/pkgs/database_cubic_hecke/package-version.txt
  build/pkgs/database_knotinfo/checksums.ini
  build/pkgs/database_knotinfo/package-version.txt
  build/pkgs/matroid_database/checksums.ini
  build/pkgs/matroid_database/package-version.txt
Labels: c: packages: standard, s: positive review, c: packages: optional, v: minimal

#37866 LPDictionary: Make it safe to copy dictionaries
  src/sage/numerical/interactive_simplex_method.py
Labels: s: positive review, c: linear programming, v: minimal

#37912 Filter "RuntimeWarning: networkx backend defined more than once for networkx"
  src/sage/all__sagemath_repl.py
Labels: s: positive review, c: graph theory, c: porting, v: minimal

#37931 libatomic_ops: Update to 7.8.2
  build/pkgs/libatomic_ops/SPKG.rst
  build/pkgs/libatomic_ops/checksums.ini
  build/pkgs/libatomic_ops/package-version.txt
Labels: c: packages: standard, s: positive review, v: minimal

#37988 CI Build&Test: Replace use of `sage -t --new`
  .ci/retrofit-worktree.sh
  .ci/write-dockerfile.sh
  .github/workflows/build.yml
Labels: s: positive review, p: blocker / 1, c: scripts, p: CI Fix, v: minimal

#37999 Fix broken pytest integration (including CI failure in `src/conftest_test.py`)
  src/conftest.py
  src/tox.ini
Labels: s: positive review, p: blocker / 1, c: scripts, p: CI Fix, v: minimal

#38009 `build/pkgs/ecl`: Update to 24.5.10
  build/pkgs/ecl/checksums.ini
  build/pkgs/ecl/package-version.txt
Labels: c: packages: standard, s: positive review, v: minimal

#38026 Do not create `spkg-*.log`, `spkg-*.time` files
  build/bin/sage-logger
  build/bin/sage-spkg
  build/sage_bootstrap/uninstall.py
Labels: t: bug, p: minor / 4, s: positive review, c: build, v: moderate

#38029 Fix interaction of # 32-bit / # 64-bit tag with block-scoped doctest tags
  src/sage/doctest/sources.py
Labels: s: positive review, c: doctest framework, p: CI Fix, v: minimal

#38032 `sage.combinat.finite_state_machine`: Deprecate `is_...` functions
  src/sage/combinat/finite_state_machine.py
Labels: s: positive review, c: finite state machines, t: refactoring, v: moderate

#38035 `sage.modular`: Deprecate `is_...` functions
  src/sage/matrix/matrix_space.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/abvar/abvar_ambient_jacobian.py
  src/sage/modular/abvar/abvar_newform.py
  src/sage/modular/abvar/constructor.py
  src/sage/modular/abvar/cuspidal_subgroup.py
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/abvar/homspace.py
  src/sage/modular/abvar/morphism.py
  src/sage/modular/abvar/torsion_subgroup.py
  src/sage/modular/arithgroup/all.py
  src/sage/modular/arithgroup/arithgroup_element.pyx
  src/sage/modular/arithgroup/arithgroup_generic.py
  src/sage/modular/arithgroup/congroup_gamma.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/arithgroup/congroup_gamma1.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/modular/arithgroup/congroup_generic.py
  src/sage/modular/arithgroup/congroup_sl2z.py
  src/sage/modular/arithgroup/farey_symbol.pyx
  src/sage/modular/cusps.py
  src/sage/modular/dims.py
  src/sage/modular/dirichlet.py
  src/sage/modular/modform/ambient.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform/space.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/boundary.py
  src/sage/modular/modsym/modsym.py
  src/sage/modular/modsym/space.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/space.py
  src/sage/modular/quasimodform/element.py
  src/sage/modular/quasimodform/ring.py
Labels: s: positive review, c: modular forms, t: refactoring, v: large

#38039 configure.ac: Check symlinks in the source tree
  configure.ac
Labels: s: positive review, p: critical / 2, c: build: configure, v: minimal

#38054 new iterators over the partitions of an integer
  src/doc/en/reference/references/index.rst
  src/sage/combinat/partition.py
  src/sage/combinat/partitions.pyx
Labels: t: enhancement, s: positive review, c: combinatorics

#38056 `SetSystem`: Minor change to accommodate set input
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/set_system.pyx
Labels: t: enhancement, s: positive review, c: matroid theory, v: small

#38059 `sage.ext.fast_callable`: Docstring cosmetics
  src/sage/ext/fast_callable.pyx
Labels: s: positive review, c: documentation, v: large

#38060 `sage.rings`: Modularization fixes for singular
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_singular_interface.py
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/rings/quotient_ring_element.py
Labels: s: positive review, t: refactoring, v: small

#38061 `sage.rings`: Modularization fixes (imports)
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/fraction_field.py
  src/sage/rings/infinity.py
  src/sage/rings/integer_ring.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/power_series_ring.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/tests.py
Labels: s: positive review, t: refactoring, v: moderate

#38065 `sage.graphs`: Doctest cosmetics
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/digraph.py
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/domination.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/generic_graph.py
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/graph.py
  src/sage/graphs/graph_coloring.pyx
  src/sage/graphs/graph_decompositions/vertex_separation.pyx
  src/sage/graphs/graph_plot_js.py
  src/sage/graphs/strongly_regular_db.pyx
Labels: s: positive review, c: graph theory, t: refactoring, v: moderate

#38066 `sage.geometry`: Modularization fixes (imports), `# needs`
  src/sage/geometry/cone.py
  src/sage/geometry/fan.py
  src/sage/geometry/fan_morphism.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/hyperplane_arrangement/check_freeness.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/geometry/hyperplane_arrangement/plot.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/geometry/polyhedron/backend_cdd_rdf.py
  src/sage/geometry/polyhedron/backend_polymake.py
  src/sage/geometry/polyhedron/base.py
  src/sage/geometry/polyhedron/base0.py
  src/sage/geometry/polyhedron/base4.py
  src/sage/geometry/polyhedron/base6.py
  src/sage/geometry/polyhedron/base7.py
  src/sage/geometry/polyhedron/base_QQ.py
  src/sage/geometry/polyhedron/base_RDF.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/geometry/polyhedron/constructor.py
  src/sage/geometry/polyhedron/generating_function.py
  src/sage/geometry/toric_lattice.py
  src/sage/geometry/toric_lattice_element.pyx
  src/sage/geometry/toric_plotter.py
  src/sage/geometry/triangulation/element.py
  src/sage/geometry/triangulation/point_configuration.py
  src/sage/geometry/voronoi_diagram.py
Labels: s: positive review, c: geometry, t: refactoring, v: moderate

#38067 `.ci/write-dockerfile.sh`: Quoting fix for `unminimize`
  .ci/write-dockerfile.sh
Labels: p: minor / 4, s: positive review, c: scripts, v: minimal

#38068 Correct developer guide's function template
  src/doc/en/developer/coding_basics.rst
Labels: s: positive review, c: documentation, v: minimal

#38070 Add skew Hadamard matrix of order 1588
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/difference_family.py
Labels: s: positive review, c: combinatorics, v: moderate

#38086 `all*.py` files: Use 'del lazy_import', 'del install_doc'
  src/sage/algebras/fusion_rings/all.py
  src/sage/algebras/hecke_algebras/all.py
  src/sage/algebras/lie_algebras/all.py
  src/sage/algebras/lie_conformal_algebras/all.py
  src/sage/algebras/quantum_groups/all.py
  src/sage/all__sagemath_objects.py
  src/sage/all__sagemath_repl.py
  src/sage/all_cmdline.py
  src/sage/arith/all.py
  src/sage/categories/all.py
  src/sage/categories/all__sagemath_objects.py
  src/sage/coding/all.py
  src/sage/combinat/chas/all.py
  src/sage/combinat/cluster_algebra_quiver/all.py
  src/sage/combinat/crystals/all.py
  src/sage/combinat/path_tableaux/all.py
  src/sage/combinat/rigged_configurations/all.py
  src/sage/combinat/species/all.py
  src/sage/crypto/all.py
  src/sage/crypto/block_cipher/all.py
  src/sage/crypto/public_key/all.py
  src/sage/doctest/all.py
  src/sage/dynamics/cellular_automata/all.py
  src/sage/dynamics/complex_dynamics/all.py
  src/sage/game_theory/all.py
  src/sage/geometry/hyperbolic_space/all.py
  src/sage/geometry/polyhedron/all.py
  src/sage/geometry/riemannian_manifolds/all.py
  src/sage/lfunctions/all.py
  src/sage/libs/ntl/all.py
  src/sage/manifolds/all.py
  src/sage/matroids/all.py
  src/sage/misc/all__sagemath_objects.py
  src/sage/modular/ssmod/all.py
  src/sage/modules/all.py
  src/sage/modules/with_basis/all.py
  src/sage/repl/all.py
  src/sage/rings/asymptotic/all.py
  src/sage/rings/polynomial/weil/all.py
  src/sage/rings/valuation/all.py
  src/sage/sandpiles/all.py
  src/sage/sat/all.py
  src/sage/schemes/product_projective/all.py
  src/sage/schemes/toric/all.py
  src/sage/stats/hmm/all.py
  src/sage/structure/all.py
  src/sage/tensor/modules/all.py
  src/sage/typeset/all.py
Labels: s: positive review, t: refactoring, v: moderate

#38090 CI Build&Test: Split test-long into multiple jobs, repair Coverage.py upload
  .github/workflows/build.yml
  src/sage/ext_data/nbconvert/postprocess.py
Labels: s: positive review, p: critical / 2, c: scripts, v: moderate

#38093 add doc on egf_to_ogf and inverse
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review, c: documentation, c: commutative algebra, v: minimal

#38095 `src/sage/algebras/steenrod/all.py`: Use lazy_import, remove deprecated global import
  src/sage/algebras/steenrod/all.py
  src/sage/misc/sageinspect.py
Labels: s: positive review, c: algebraic topology, t: refactoring, v: minimal

#38100 Remove nitpick_patch_config function
  src/sage_docbuild/__main__.py
  src/sage_docbuild/builders.py
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation, v: small

#38104 `sage.coding`: Update `# needs`
  src/sage/coding/abstract_code.py
  src/sage/coding/ag_code.py
  src/sage/coding/ag_code_decoders.pyx
  src/sage/coding/bch_code.py
  src/sage/coding/binary_code.pyx
  src/sage/coding/channel.py
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/codecan/codecan.pyx
  src/sage/coding/cyclic_code.py
  src/sage/coding/databases.py
  src/sage/coding/decoder.py
  src/sage/coding/delsarte_bounds.py
  src/sage/coding/encoder.py
  src/sage/coding/extended_code.py
  src/sage/coding/gabidulin_code.py
  src/sage/coding/golay_code.py
  src/sage/coding/goppa_code.py
  src/sage/coding/grs_code.py
  src/sage/coding/guava.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/guruswami_sudan/interpolation.py
  src/sage/coding/guruswami_sudan/utils.py
  src/sage/coding/hamming_code.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/kasami_codes.pyx
  src/sage/coding/linear_code.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/coding/linear_rank_metric.py
  src/sage/coding/parity_check_code.py
  src/sage/coding/punctured_code.py
  src/sage/coding/reed_muller_code.py
  src/sage/coding/self_dual_codes.py
  src/sage/coding/source_coding/huffman.py
  src/sage/coding/subfield_subcode.py
  src/sage/coding/two_weight_db.py
Labels: s: positive review, c: coding theory, t: refactoring, v: large

#38105 Fixing the index set of a rank 1 Cartan matrix
  src/sage/combinat/root_system/cartan_matrix.py
Labels: p: major / 3, t: bug, s: positive review, c: combinatorics

#38111 GH Actions: Fix upload of macOS wheels to PyPI
  .github/workflows/dist.yml
Labels: s: positive review, p: blocker / 1, c: scripts, v: minimal

#37848 Implement all G(r,p,m) complex reflection groups
  src/sage/combinat/colored_permutations.py
  src/sage/groups/misc_gps/misc_groups_catalog.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: group theory

#37857 Replace special handling of optional extensions (bliss, coxeter3, ....)
  build/pkgs/sagelib/spkg-install.in
  build/pkgs/sagemath_bliss/spkg-install.in
  build/pkgs/sagemath_meataxe/dependencies
  pkgs/sagemath-bliss/setup.py
  pkgs/sagemath-coxeter3/setup.py
  pkgs/sagemath-mcqd/setup.py
  pkgs/sagemath-meataxe/setup.py
  pkgs/sagemath-sirocco/setup.py
  pkgs/sagemath-standard/setup.py
  pkgs/sagemath-tdlib/setup.py
  src/MANIFEST.in
  src/sage/all__sagemath_bliss.py
  src/sage/all__sagemath_coxeter3.py
  src/sage/all__sagemath_mcqd.py
  src/sage/all__sagemath_meataxe.py
  src/sage/all__sagemath_sirocco.py
  src/sage/all__sagemath_tdlib.py
  src/sage/doctest/control.py
  src/sage/features/bliss.py
  src/sage/features/coxeter3.py
  src/sage/features/mcqd.py
  src/sage/features/meataxe.py
  src/sage/features/sirocco.py
  src/sage/features/tdlib.py
  src/sage/graphs/all__sagemath_bliss.py
  src/sage/graphs/all__sagemath_mcqd.py
  src/sage/graphs/all__sagemath_tdlib.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/all__sagemath_tdlib.py
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/libs/all__sagemath_coxeter3.py
  src/sage/libs/all__sagemath_meataxe.py
  src/sage/libs/all__sagemath_sirocco.py
  src/sage/matrix/all__sagemath_meataxe.py
  src/sage/matrix/matrix_space.py
  src/sage_setup/command/sage_build_py.py
  src/setup.cfg.m4
  src/setup.py
Labels: s: positive review, c: build, c: distribution, v: moderate

#36538 Implement Drinfeld modular forms
  src/doc/en/reference/modfrm/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/modular/all.py
  src/sage/modular/drinfeld_modform/all.py
  src/sage/modular/drinfeld_modform/element.py
  src/sage/modular/drinfeld_modform/ring.py
  src/sage/modular/drinfeld_modform/tutorial.py
Labels: t: enhancement, s: positive review, c: modular forms, v: large

#38132 some care for blank lines (pep E30) in groups/ and numerical/
  src/sage/groups/group.pyx
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/double_coset.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_graphs.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_lists.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_matrices.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_python.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_sets.pyx
  src/sage/groups/perm_gps/partn_ref2/refinement_generic.pyx
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/groups/semimonomial_transformations/semimonomial_transformation.pyx
  src/sage/numerical/backends/cvxopt_backend.pyx
  src/sage/numerical/backends/cvxopt_sdp_backend.pyx
  src/sage/numerical/backends/generic_backend.pyx
  src/sage/numerical/backends/generic_sdp_backend.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/backends/interactivelp_backend.pyx
  src/sage/numerical/backends/matrix_sdp_backend.pyx
  src/sage/numerical/backends/ppl_backend.pyx
  src/sage/numerical/gauss_legendre.pyx
  src/sage/numerical/linear_functions.pyx
  src/sage/numerical/sdp.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38133 some care for blank lines in coding and modules
  src/sage/coding/binary_code.pyx
  src/sage/coding/codecan/autgroup_can_label.pyx
  src/sage/coding/codecan/codecan.pyx
  src/sage/coding/kasami_codes.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/modules/vector_double_dense.pyx
  src/sage/modules/vector_integer_dense.pyx
  src/sage/modules/vector_integer_sparse.pyx
  src/sage/modules/vector_mod2_dense.pyx
  src/sage/modules/vector_modn_dense.pyx
  src/sage/modules/vector_rational_sparse.pyx
  src/sage/modules/vector_real_double_dense.pyx
  src/sage/modules/with_basis/indexed_element.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38134 some care for blank lines in matrix/
  src/sage/matrix/echelon_matrix.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/matrix/matrix_double_sparse.pyx
  src/sage/matrix/matrix_generic_dense.pyx
  src/sage/matrix/matrix_generic_sparse.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
  src/sage/matrix/matrix_sparse.pyx
  src/sage/matrix/matrix_window.pyx
  src/sage/matrix/strassen.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38136 Fix building fflas, linbox on 32-bit by disabling SSE, AVX
  build/pkgs/fflas_ffpack/patches/disable-sse-avx-on-32-bit.patch
Labels: c: packages: standard, s: positive review, p: critical / 2, c: porting, v: minimal

#38137 some care for blank lines in pyx in rings
  src/sage/rings/complex_arb.pyx
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/factorint.pyx
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/hermite_form_polynomial.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/number_field/totallyreal.pyx
  src/sage/rings/number_field/totallyreal_data.pyx
  src/sage/rings/padics/padic_ZZ_pX_element.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/power_series_poly.pyx
  src/sage/rings/real_arb.pyx
  src/sage/rings/real_lazy.pyx
  src/sage/rings/semirings/tropical_semiring.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38143 `sage.monoids`: Modularization fixes, `# needs`
  src/sage/monoids/automatic_semigroup.py
  src/sage/monoids/free_monoid_element.py
  src/sage/monoids/hecke_monoid.py
  src/sage/monoids/monoid.py
  src/sage/monoids/string_monoid_element.py
  src/sage/monoids/string_ops.py
  src/sage/monoids/trace_monoid.py
Labels: s: positive review, t: refactoring, v: moderate

#38152 Improve performance of computing columns of matrices over GF(2)
  src/sage/matrix/matrix_mod2_dense.pyx
Labels: p: minor / 4, s: positive review, c: linear algebra, t: performance, v: minimal

#38156 just a few details in permutation.py
  src/sage/combinat/permutation.py
Labels: s: positive review, c: combinatorics, v: minimal

#37662 Add parameter `sort_neighbors` to method `init_short_digraph`
  src/sage/graphs/asteroidal_triples.pyx
  src/sage/graphs/base/static_sparse_graph.pxd
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/centrality.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/isoperimetric_inequalities.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/weakly_chordal.pyx
Labels: s: positive review, c: graph theory, v: moderate

#37669 update (py)cryptominisat to version 5.11.21, remove no longer needed cryptominisat spkg
  build/pkgs/cryptominisat/SPKG.rst
  build/pkgs/cryptominisat/checksums.ini
  build/pkgs/cryptominisat/dependencies
  build/pkgs/cryptominisat/distros/conda.txt
  build/pkgs/cryptominisat/distros/homebrew.txt
  build/pkgs/cryptominisat/distros/repology.txt
  build/pkgs/cryptominisat/math
  build/pkgs/cryptominisat/package-version.txt
  build/pkgs/cryptominisat/patches/679.patch
  build/pkgs/cryptominisat/patches/cryptominisat-5.8.0-rm_extra_python_vars.patch
  build/pkgs/cryptominisat/spkg-install.in
  build/pkgs/cryptominisat/type
  build/pkgs/pycryptosat/SPKG.rst
  build/pkgs/pycryptosat/checksums.ini
  build/pkgs/pycryptosat/dependencies
  build/pkgs/pycryptosat/package-version.txt
  build/pkgs/pycryptosat/patches
  build/pkgs/pycryptosat/requirements.txt
  build/pkgs/pycryptosat/spkg-install.in
  src/sage/sat/solvers/cryptominisat.py
  src/sage/sat/solvers/satsolver.pyx
Labels: s: positive review, c: packages: optional, v: moderate

#37697 Implement the solvable and nil radicals of a finite dimensional Lie algebra
  src/sage/algebras/lie_algebras/lie_algebra_element.pxd
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
  src/sage/algebras/lie_algebras/quotient.py
  src/sage/algebras/lie_algebras/subalgebra.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix_space.py
Labels: t: enhancement, s: positive review, c: algebra

#37779 Implementing the faithful representation of a generic Lie algebra in positive characteristic
  src/sage/algebras/lie_algebras/representation.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: t: enhancement, s: positive review, c: algebra, v: moderate

#37819 `igraph`: Update to 0.10.12, fix spkg-check; `python_igraph`: Update to 0.11.5, remove spkg-install workarounds
  .ci/retrofit-worktree.sh
  .ci/write-dockerfile.sh
  .github/workflows/build.yml
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  build/bin/sage-dist-helpers
  build/pkgs/cmake/spkg-configure.m4
  build/pkgs/igraph/checksums.ini
  build/pkgs/igraph/package-version.txt
  build/pkgs/igraph/spkg-check.in
  build/pkgs/igraph/spkg-configure.m4
  build/pkgs/python_igraph/checksums.ini
  build/pkgs/python_igraph/package-version.txt
  build/pkgs/python_igraph/spkg-install.in
Labels: s: positive review, c: build, c: packages: optional, c: graph theory, v: moderate

#37850 Reverted changes from #36986
  src/sage/groups/abelian_gps/abelian_group.py
Labels: t: bug, s: positive review, p: critical / 2, c: group theory, v: minimal

#37871 Construct the composition series of Garsia-Procesi modules
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/modules_with_basis.py
  src/sage/categories/semigroups.py
  src/sage/combinat/partition.py
  src/sage/combinat/permutation.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/combinat/symmetric_group_representations.py
  src/sage/modules/with_basis/morphism.py
  src/sage/modules/with_basis/representation.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: group theory, c: algebra

#37977 Add a method to enumerate cographs
  src/doc/en/reference/graphs/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/graphs/cographs.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory, v: large

#38034 `sage.libs.giac`: Compile with std=c++11
  src/sage/libs/giac/giac.pyx
Labels: s: positive review, p: critical / 2, c: porting, v: minimal

#38053 work on letterplace algebras
  src/sage/algebras/letterplace/free_algebra_letterplace.pxd
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
Labels: s: positive review, c: algebra, t: refactoring, v: small

#38057 `matroids`: Declare function input and return types
  src/sage/algebras/orlik_solomon.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/matroids/advanced.py
  src/sage/matroids/all.py
  src/sage/matroids/basis_exchange_matroid.pxd
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/basis_matroid.pxd
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/catalog.py
  src/sage/matroids/circuit_closures_matroid.pxd
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pxd
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/constructor.py
  src/sage/matroids/database_matroids.py
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/flats_matroid.pxd
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/graphic_matroid.pxd
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/linear_matroid.pxd
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
  src/sage/matroids/minor_matroid.py
  src/sage/matroids/rank_matroid.py
  src/sage/matroids/union_matroid.pxd
  src/sage/matroids/union_matroid.pyx
Labels: t: enhancement, s: positive review, t: performance, c: matroid theory, v: large

#38103 Deprecate `is_Map`, `is_...Morphism`
  src/sage/categories/functor.pyx
  src/sage/categories/map.pyx
  src/sage/categories/morphism.pyx
  src/sage/groups/abelian_gps/abelian_group_morphism.py
  src/sage/groups/perm_gps/permgroup_morphism.py
  src/sage/homology/chain_complex_morphism.py
  src/sage/modules/fg_pid/fgp_morphism.py
  src/sage/quivers/morphism.py
  src/sage/quivers/representation.py
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/ideal.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/sets/image_set.py
  src/sage/topology/simplicial_complex_morphism.py
Labels: s: positive review, t: refactoring, v: small

#38114 Fixed bug in size labeler
  .ci/set_labels_by_changes.sh
  .github/workflows/pr-labeler.yml
Labels: s: positive review, c: scripts

#38117 Add small examples of common docstring styles
  src/doc/en/developer/coding_basics.rst
Labels: s: positive review, c: documentation, v: minimal

#38119 Fix hashing for Weyl algebra elements
  src/sage/algebras/weyl_algebra.py
Labels: t: enhancement, s: positive review, c: algebra

#38122 `sage.doctest.control`: In doctests, use Python floats for stats
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
Labels: s: positive review, t: tests, c: doctest framework, v: minimal

#38124 Deprecate `is_NumberFieldOrder`, `is_AbsoluteNumberField`, `is_RelativeNumberField`, `is_NumberFieldIdeal`, `is_NumberFieldFractionalIdeal`, `is_NumberFieldFractionalIdeal_rel`
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/number_field_ideal_rel.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/number_field/order.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring_element.py
  src/sage/schemes/elliptic_curves/ell_local_data.py
  src/sage/schemes/projective/projective_point.py
Labels: s: positive review, c: number fields, t: refactoring, v: moderate

#38125 Deprecate `is_MutablePoset`
  src/sage/data_structures/mutable_poset.py
Labels: s: positive review, c: combinatorics, t: refactoring, v: minimal

#38126 Deprecate `is_Fan`, `is_NefPartition`, `is_PointCollection`, `is_ToricLattice`, `is_ToricLatticeElement`, `is_ToricLatticeQuotient`
  src/sage/geometry/cone.py
  src/sage/geometry/fan.py
  src/sage/geometry/fan_morphism.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/point_collection.pyx
  src/sage/geometry/toric_lattice.py
  src/sage/geometry/toric_lattice_element.pyx
  src/sage/schemes/toric/divisor.py
Labels: s: positive review, c: geometry, t: refactoring, v: moderate

#38127 Add links to the PR in doc preview
  .github/workflows/doc-build.yml
  .github/workflows/doc-publish.yml
  src/sage_docbuild/conf.py
Labels: s: positive review, c: build, c: documentation, c: scripts, v: minimal

#38131 code polishing using list comprehension
  src/sage/calculus/desolvers.py
  src/sage/coding/code_bounds.py
  src/sage/coding/code_constructions.py
  src/sage/coding/linear_rank_metric.py
  src/sage/coding/subfield_subcode.py
  src/sage/combinat/affine_permutation.py
  src/sage/combinat/composition.py
  src/sage/game_theory/normal_form_game.py
  src/sage/homology/chain_complex.py
  src/sage/knots/link.py
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/btquotients/pautomorphicform.py
  src/sage/modular/cusps_nf.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/monoids/trace_monoid.py
  src/sage/numerical/interactive_simplex_method.py
  src/sage/parallel/map_reduce.py
  src/sage/plot/colors.py
  src/sage/plot/hyperbolic_polygon.py
  src/sage/repl/rich_output/preferences.py
  src/sage/sat/converters/polybori.py
  src/sage/symbolic/random_tests.py
  src/sage/tensor/modules/free_module_tensor.py
  src/sage/tests/arxiv_0812_2725.py
Labels: s: positive review, t: refactoring, v: moderate

#37526 Fix `monomial_coefficients` for submodules of free modules from sage.modules
  src/doc/en/thematic_tutorials/tutorial-implementing-algebraic-structures.rst
  src/sage/algebras/lie_algebras/affine_lie_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/categories/algebras_with_basis.py
  src/sage/categories/hopf_algebras_with_basis.py
  src/sage/categories/modules_with_basis.py
  src/sage/modular/btquotients/pautomorphicform.py
  src/sage/modules/free_module_element.pyx
  src/sage/quivers/algebra.py
  src/sage/quivers/algebra_elements.pyx
Labels: t: bug, s: positive review, c: linear algebra, v: moderate

#38196 Use equality '==' instead of 'is' for strings comparison
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/traversals.pyx
Labels: s: positive review, c: graph theory, v: minimal

#38197 Column and row stabilizers for skew tableaux
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/symmetric_group_algebra.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: algebra

#38200 build/pkgs/sagemath_{categories,environment,objects,repl}: Change to optional
  build/pkgs/sagemath_categories/type
  build/pkgs/sagemath_environment/type
  build/pkgs/sagemath_objects/type
  build/pkgs/sagemath_repl/type
  pkgs/sagemath-bliss/README.rst
  pkgs/sagemath-categories/README.rst
  pkgs/sagemath-coxeter3/README.rst
  pkgs/sagemath-environment/README.rst
  pkgs/sagemath-mcqd/README.rst
  pkgs/sagemath-meataxe/README.rst
  pkgs/sagemath-objects/README.rst
  pkgs/sagemath-repl/README.rst
  pkgs/sagemath-sirocco/README.rst
  pkgs/sagemath-tdlib/README.rst
Labels: s: positive review, p: blocker / 1, c: distribution, v: moderate

#38206 Lint: Install tox from ubuntu, as done in CI Build&Test etc.
  .github/workflows/lint.yml
Labels: p: minor / 4, s: positive review, c: scripts, v: minimal

#38212 bump prompt_toolkit/version_requirements.txt, more spkg-configures
  build/pkgs/httpcore/spkg-configure.m4
  build/pkgs/httpx/spkg-configure.m4
  build/pkgs/prompt_toolkit/version_requirements.txt
Labels: s: positive review, c: build: configure, v: minimal

#38213 Fix regex to remove spurious diffs in doc preview
  .github/workflows/doc-build.yml
Labels: s: positive review, c: documentation, c: scripts, v: minimal

#38215 Fix typo "sage.ring" in docstrings
  src/sage/modular/pollack_stevens/padic_lseries.py
  src/sage/rings/polynomial/padics/polynomial_padic.py
  src/sage/structure/factory.pyx
Labels: s: positive review, t: tests, v: minimal

#35396 Activate/fix rpy2 tests
  build/pkgs/r/SPKG.rst
  build/pkgs/r/distros/conda.txt
  build/pkgs/rpy2/SPKG.rst
  src/sage/features/standard.py
  src/sage/interfaces/r.py
  src/sage/repl/ipython_tests.py
Labels: t: bug, c: packages: standard, s: positive review, c: distribution, v: large

#36980 Specht modules for Ariki-Koike algebras
  src/doc/en/reference/algebras/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/algebras/hecke_algebras/ariki_koike_algebra.py
  src/sage/algebras/hecke_algebras/ariki_koike_specht_modules.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37312 `sage.plot.animate`: Use FFmpeg.absolute_filename; `sage.features`: Remove deprecated methods
  src/sage/features/__init__.py
  src/sage/features/join_feature.py
  src/sage/plot/animate.py
Labels: s: positive review, c: graphics, v: small

#37430 Refactor `bootstrap`, `bootstrap-conda`, `m4/sage_spkg_collect.m4`, `sage-spkg-info` through `sage --package properties`, `sage-get-system-packages`
  bootstrap
  bootstrap-conda
  build/bin/sage-get-system-packages
  build/bin/sage-spkg-info
  m4/sage_python_package_check.m4
  m4/sage_spkg_collect.m4
Labels: s: positive review, c: build, v: moderate

#37801 Drop custom GLPK patch and error handling
  build/pkgs/glpk/package-version.txt
  build/pkgs/glpk/patches/error_recovery.patch
  src/sage/libs/glpk/error.pyx
Labels: c: packages: standard, s: positive review, v: moderate

#37830 Implement the Schur functors applied to semigroup representations
  src/sage/categories/coxeter_groups.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/groups/matrix_gps/matrix_group.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/modules/with_basis/representation.py
Labels: p: major / 3, t: enhancement, s: positive review, c: group theory, c: algebra, v: large

#37834 `build/pkgs/python3`: Update to 3.12.4; declare support of Python 3.12.x stable
  build/pkgs/python3/SPKG.rst
  build/pkgs/python3/checksums.ini
  build/pkgs/python3/package-version.txt
  build/pkgs/python3/patches/0001-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
  build/pkgs/python3/patches/linux_linking_issue_25229.patch
  build/pkgs/python3/spkg-configure.m4
Labels: c: packages: standard, s: positive review, p: critical / 2, v: small

#38019 find integral solutions to matrix equations over PIDs
  src/sage/matrix/matrix2.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: linear algebra, v: moderate

#38064 Steinhaus-Johnson-Trotter algorithm for permutations
  src/sage/combinat/SJT.py
  src/sage/combinat/permutation.py
Labels: s: positive review, c: combinatorics, v: large

#38084 Implemented a generator for Möbius ladder graph
  src/sage/graphs/generators/basic.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory, v: large, gsoc: 2024

#38096 `sage.combinat`, `sage.games`: Use more `lazy_import` in all.py files
  src/sage/categories/weyl_groups.py
  src/sage/combinat/ncsf_qsym/all.py
  src/sage/combinat/ncsym/all.py
  src/sage/combinat/root_system/all.py
  src/sage/combinat/words/all.py
  src/sage/games/all.py
  src/sage/structure/parent.pyx
Labels: s: positive review, c: combinatorics, t: refactoring, v: minimal

#38097 Refactor `CachedRepresentation` through new class `WithPicklingByInitArgs`
  src/sage/categories/category_singleton.pyx
  src/sage/categories/sets_cat.py
  src/sage/structure/unique_representation.py
Labels: s: positive review, t: refactoring

#38102 Implement the intrinsic arrangement of a Specht module
  src/doc/en/reference/references/index.rst
  src/sage/combinat/specht_module.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics, c: geometry, c: algebra

#38129 Fix live doc build by saving runner space
  .github/workflows/doc-build.yml
Labels: s: positive review, p: critical / 2, c: scripts, v: minimal

#38140 e_antic 2.0.2, normaliz 3.10.3, pynormaliz 2.20, polymake 4.12
  build/pkgs/e_antic/checksums.ini
  build/pkgs/e_antic/package-version.txt
  build/pkgs/normaliz/checksums.ini
  build/pkgs/normaliz/package-version.txt
  build/pkgs/normaliz/patches/411.patch
  build/pkgs/normaliz/patches/flint3_d-torrance.patch
  build/pkgs/polymake/checksums.ini
  build/pkgs/polymake/package-version.txt
  build/pkgs/pynormaliz/checksums.ini
  build/pkgs/pynormaliz/package-version.txt
Labels: s: positive review, c: packages: optional, v: small

#38141 build/pkgs/sympy: Update to 1.12.1, change to wheel package
  build/pkgs/sympy/SPKG.rst
  build/pkgs/sympy/checksums.ini
  build/pkgs/sympy/dependencies
  build/pkgs/sympy/package-version.txt
  build/pkgs/sympy/spkg-install.in
Labels: c: packages: standard, s: positive review, v: minimal

#38153 Remove imports pyx
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/libs/gmp/pylong.pyx
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/libs/pari/convert_sage_real_mpfr.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_laurent_mpolynomial_dense.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/modular/arithgroup/farey_symbol.pyx
  src/sage/plot/plot3d/base.pyx
  src/sage/quadratic_forms/ternary.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/sets/family.pyx
Labels: s: positive review, t: refactoring, v: small

#38160 details in partition.py (code and pep8)
  src/sage/combinat/partition.py
Labels: s: positive review, c: combinatorics, v: moderate

#38165 simplify some calls to join
  src/sage/combinat/nu_tamari_lattice.py
  src/sage/geometry/integral_points.pxi
  src/sage/geometry/toric_lattice.py
  src/sage/graphs/graph_input.py
  src/sage/groups/finitely_presented.py
  src/sage/lfunctions/dokchitser.py
  src/sage/libs/eclib/mwrank.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/misc/cython.py
  src/sage/misc/sage_input.py
  src/sage/modules/fp_graded/steenrod/module.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/rings/valuation/value_group.py
Labels: s: positive review, t: refactoring, v: minimal

#38167 New methods for sparse graphs backend to enumerate neighbors in linear time
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/base/sparse_graph.pxd
  src/sage/graphs/base/sparse_graph.pyx
Labels: s: positive review, c: graph theory, v: large

#38168 some care about the documentation of graph generators
  src/doc/en/reference/references/index.rst
  src/sage/graphs/generators/basic.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/generators/families.py
  src/sage/graphs/generators/random.py
  src/sage/graphs/generators/smallgraphs.py
Labels: s: positive review, c: documentation, c: graph theory, v: moderate

#38170 `sage.categories`: Update `# needs`, modularization fixes (imports)
  src/sage/categories/chain_complexes.py
  src/sage/categories/examples/lie_algebras.py
  src/sage/categories/fields.py
  src/sage/categories/finite_dimensional_modules_with_basis.py
  src/sage/categories/finite_groups.py
  src/sage/categories/group_algebras.py
  src/sage/categories/groups.py
  src/sage/categories/pushout.py
  src/sage/categories/quantum_group_representations.py
  src/sage/categories/simplicial_sets.py
Labels: s: positive review, t: refactoring, v: moderate

#38171 fix some details in the documentation of digraph generators
  src/sage/graphs/digraph_generators.py
Labels: s: positive review, c: documentation, c: graph theory, v: minimal

#38176 fix and activate E305 in pyx files
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/cachefunc.pyx
  src/sage/misc/fpickle.pyx
  src/sage/misc/lazy_import.pyx
  src/sage/misc/lazy_string.pyx
  src/sage/misc/misc_c.pyx
  src/sage/misc/nested_class.pyx
  src/sage/misc/parser.pyx
  src/sage/misc/persist.pyx
  src/sage/misc/pickle_old.pyx
  src/sage/misc/randstate.pyx
  src/sage/misc/stopgap.pyx
  src/tox.ini
Labels: s: positive review, v: minimal

#38177 some care for blanklines in pyx in stats
  src/sage/stats/hmm/chmm.pyx
  src/sage/stats/hmm/distributions.pyx
  src/sage/stats/hmm/hmm.pyx
  src/sage/stats/hmm/util.pyx
  src/sage/stats/time_series.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38178 some care for blank lines in pyx in padics
  src/sage/rings/padics/morphism.pyx
  src/sage/rings/padics/padic_ZZ_pX_CR_element.pyx
  src/sage/rings/padics/padic_ZZ_pX_element.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/padics/pow_computer_flint.pyx
  src/sage/rings/padics/pow_computer_relative.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38179 `tox.ini`, `.github/workflows`, `.devcontainer`: Remove centos-stream-8 (EOL)
  .devcontainer/portability-centos-stream-8-python3.9-minimal/devcontainer.json
  .devcontainer/portability-centos-stream-8-python3.9-minimal/portability-Dockerfile
  .devcontainer/portability-centos-stream-8-python3.9-standard/devcontainer.json
  .devcontainer/portability-centos-stream-8-python3.9-standard/portability-Dockerfile
  .github/workflows/ci-linux.yml
  .github/workflows/docker.yml
  src/doc/en/developer/portability_platform_table.rst
  tox.ini
Labels: s: positive review, c: scripts, c: porting, v: moderate

#38180 `sage.interfaces`: More `lazy_import`
  src/sage/categories/pushout.py
  src/sage/doctest/forker.py
  src/sage/interfaces/all.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/gp.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/magma.py
  src/sage/interfaces/polymake.py
  src/sage/interfaces/singular.py
Labels: s: positive review, c: interfaces, t: refactoring, v: minimal

#38181 `sage.plot`, `sage.repl`: Modularization fixes (imports), `# needs`
  src/sage/plot/graphics.py
  src/sage/plot/hyperbolic_regular_polygon.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/repl/display/formatter.py
  src/sage/repl/image.py
  src/sage/repl/ipython_kernel/interact.py
  src/sage/repl/ipython_kernel/widgets.py
  src/sage/repl/preparse.py
  src/sage/repl/user_globals.py
Labels: c: user interface, s: positive review, c: graphics, t: refactoring, v: small

#38184 Deprecate `is_FreeAlgebraQuotientElement`, ...
  src/sage/algebras/free_algebra_quotient_element.py
  src/sage/categories/functor.pyx
  src/sage/groups/abelian_gps/abelian_group_element.py
  src/sage/groups/abelian_gps/dual_abelian_group.py
  src/sage/groups/abelian_gps/dual_abelian_group_element.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/homology/chain_complex_homspace.py
  src/sage/matrix/matrix2.pyx
  src/sage/misc/latex.py
  src/sage/modular/dirichlet.py
  src/sage/modular/modform/ambient_eps.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform/hecke_operator_on_qexp.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/boundary.py
  src/sage/modular/modsym/element.py
  src/sage/modular/modsym/manin_symbol.pyx
  src/sage/modules/free_module.py
  src/sage/modules/free_module_element.pyx
  src/sage/monoids/free_abelian_monoid_element.pyx
  src/sage/monoids/free_monoid_element.py
  src/sage/numerical/linear_functions.pyx
  src/sage/numerical/linear_tensor.py
  src/sage/numerical/linear_tensor_constraints.py
  src/sage/numerical/linear_tensor_element.pyx
  src/sage/numerical/mip.pyx
  src/sage/numerical/sdp.pyx
  src/sage/plot/graphics.py
  src/sage/probability/random_variable.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
Labels: s: positive review, t: refactoring, v: moderate

#38189 Improve DiGraph neighbor iterators
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/posets.py
  src/sage/geometry/fan.py
  src/sage/graphs/digraph.py
  src/sage/graphs/generic_graph.py
  src/sage/schemes/toric/variety.py
  src/sage/tests/books/judson-abstract-algebra/boolean-sage.py
Labels: s: positive review, c: graph theory, v: moderate

#38193 `sage.algebras`...`sage.topology`: Doctest cosmetics, `# needs`, import fixes
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_ideal.py
  src/sage/arith/functions.pyx
  src/sage/arith/misc.py
  src/sage/arith/srange.pyx
  src/sage/game_theory/matching_game.py
  src/sage/game_theory/normal_form_game.py
  src/sage/structure/formal_sum.py
  src/sage/topology/cell_complex.py
  src/sage/topology/moment_angle_complex.py
Labels: s: positive review, t: refactoring, v: small

#38198 Improve complexity comments for graphs
  src/sage/graphs/base/dense_graph.pyx
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/weakly_chordal.pyx
Labels: s: positive review, c: documentation, c: graph theory, v: small

#38209 Fix infinite loop bug in doctest from #36581
  src/sage/stats/distributions/discrete_gaussian_lattice.py
Labels: t: bug, s: positive review, p: blocker / 1, c: statistics

#38210 `sage.rings`: Modularization fixes (imports), `# needs`
  src/sage/rings/function_field/differential.py
  src/sage/rings/function_field/divisor.py
  src/sage/rings/function_field/drinfeld_modules/action.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/homset.py
  src/sage/rings/function_field/drinfeld_modules/morphism.py
  src/sage/rings/function_field/element.pyx
  src/sage/rings/function_field/element_polymod.pyx
  src/sage/rings/function_field/element_rational.pyx
  src/sage/rings/function_field/function_field.py
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/function_field/function_field_rational.py
  src/sage/rings/function_field/ideal.py
  src/sage/rings/function_field/ideal_polymod.py
  src/sage/rings/function_field/maps.py
  src/sage/rings/function_field/order.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/function_field/order_rational.py
  src/sage/rings/function_field/place.py
  src/sage/rings/function_field/place_polymod.py
  src/sage/rings/function_field/place_rational.py
  src/sage/rings/function_field/valuation_ring.py
  src/sage/rings/polynomial/binary_form_reduce.py
  src/sage/rings/polynomial/ideal.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/qqbar.py
  src/sage/rings/real_arb.pyx
Labels: s: positive review, t: refactoring, v: moderate

#37998 Update conda-lock files, rename macOS conda-lock files to match CI Conda, remove unexplained duplicate lock files
  .github/workflows/ci-conda-known-test-failures.json
  .github/workflows/ci-conda.yml
  .github/workflows/conda-lock-update.py
  build/pkgs/_prereq/distros/conda.txt
  build/pkgs/gap/distros/conda.txt
  build/pkgs/gap/spkg-configure.m4
  build/pkgs/rpy2/distros/conda.txt
  environment-3.10-linux-aarch.yml
  environment-3.10-linux-aarch64.yml
  environment-3.10-linux.yml
  environment-3.10-macos-arm.yml
  environment-3.10-macos-arm64.yml
  environment-3.10-macos-x86_64.yml
  environment-3.10-macos.yml
  environment-3.11-linux-aarch.yml
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-arm.yml
  environment-3.11-macos-arm64.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.9-linux-aarch.yml
  environment-3.9-linux-aarch64.yml
  environment-3.9-linux.yml
  environment-3.9-macos-arm.yml
  environment-3.9-macos-arm64.yml
  environment-3.9-macos-x86_64.yml
  environment-3.9-macos.yml
  src/environment-3.10-linux-aarch64.yml
  src/environment-3.10-linux.yml
  src/environment-3.10-macos-arm64.yml
  src/environment-3.10-macos-x86_64.yml
  src/environment-3.10-macos.yml
  src/environment-3.11-linux-aarch64.yml
  src/environment-3.11-linux.yml
  src/environment-3.11-macos-arm64.yml
  src/environment-3.11-macos-x86_64.yml
  src/environment-3.11-macos.yml
  src/environment-3.9-linux-aarch.yml
  src/environment-3.9-linux-aarch64.yml
  src/environment-3.9-linux.yml
  src/environment-3.9-macos-arm64.yml
  src/environment-3.9-macos-x86_64.yml
  src/environment-3.9-macos.yml
  src/environment-dev-3.10-linux-aarch64.yml
  src/environment-dev-3.10-linux.yml
  src/environment-dev-3.10-macos-arm64.yml
  src/environment-dev-3.10-macos-x86_64.yml
  src/environment-dev-3.10-macos.yml
  src/environment-dev-3.11-linux-aarch64.yml
  src/environment-dev-3.11-linux.yml
  src/environment-dev-3.11-macos-arm64.yml
  src/environment-dev-3.11-macos-x86_64.yml
  src/environment-dev-3.11-macos.yml
  src/environment-dev-3.9-linux-aarch64.yml
  src/environment-dev-3.9-linux.yml
  src/environment-dev-3.9-macos-arm64.yml
  src/environment-dev-3.9-macos-x86_64.yml
  src/environment-dev-3.9-macos.yml
  tox.ini
Labels: s: positive review, p: blocker / 1, c: scripts, p: CI Fix, v: large
