Repository sagemath/sage, pull requests merged in 2024-11, with the labels that each got.

#38722 Roots of polynomials mod n
  src/doc/en/reference/references/index.rst
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: number theory, c: finite rings

#38809 move orientation methods from `graph.py` to `orientations.py`
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph.py
  src/sage/graphs/orientations.py
Labels: s: positive review, c: graph theory

#38835 Remove redundant modulo operation in vector_modn_dense
  src/sage/modules/vector_modn_dense.pyx
Labels: s: positive review

#38842 fix issue #38832 about `canonical_label` in bipartite graphs
  src/sage/graphs/bipartite_graph.py
Labels: t: bug, s: positive review, c: graph theory

#38853 Add conversion dictionaries to trig.py
  src/sage/functions/trig.py
Labels: s: positive review, c: interfaces, c: calculus

#38854 Add LaTeX representation for function fields
  src/sage/rings/function_field/function_field_polymod.py
Labels: t: feature, s: positive review

#38858 autopep8 fixes for E302 in matrix,rings,groups,dynamics
  src/sage/dynamics/arithmetic_dynamics/affine_ds.py
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/dynamics/arithmetic_dynamics/endPN_automorphism_group.py
  src/sage/dynamics/arithmetic_dynamics/endPN_minimal_model.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/dynamics/cellular_automata/elementary.py
  src/sage/dynamics/cellular_automata/glca.py
  src/sage/dynamics/complex_dynamics/mandel_julia.py
  src/sage/dynamics/finite_dynamical_system.py
  src/sage/dynamics/finite_dynamical_system_catalog.py
  src/sage/dynamics/surface_dynamics_deprecation.py
  src/sage/groups/abelian_gps/abelian_aut.py
  src/sage/groups/abelian_gps/abelian_group_gap.py
  src/sage/groups/finitely_presented_named.py
  src/sage/groups/fqf_orthogonal.py
  src/sage/groups/indexed_free_group.py
  src/sage/groups/libgap_group.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/groups/matrix_gps/heisenberg.py
  src/sage/groups/matrix_gps/homset.py
  src/sage/groups/matrix_gps/morphism.py
  src/sage/groups/matrix_gps/named_group_gap.py
  src/sage/groups/perm_gps/cubegroup.py
  src/sage/matrix/benchmark.py
  src/sage/matrix/matrix_integer_dense_saturation.py
  src/sage/matrix/matrix_space.py
  src/sage/rings/asymptotic/growth_group.py
  src/sage/rings/asymptotic/growth_group_cartesian.py
  src/sage/rings/complex_interval_field.py
  src/sage/rings/finite_rings/conway_polynomials.py
  src/sage/rings/finite_rings/finite_field_pari_ffelt.py
  src/sage/rings/finite_rings/galois_group.py
  src/sage/rings/finite_rings/homset.py
  src/sage/rings/finite_rings/maps_finite_field.py
  src/sage/rings/function_field/constructor.py
  src/sage/rings/function_field/divisor.py
  src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/valuation.py
  src/sage/rings/function_field/valuation_ring.py
  src/sage/rings/ideal.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/monomials.py
  src/sage/rings/polynomial/complex_roots.py
  src/sage/rings/polynomial/ideal.py
  src/sage/rings/polynomial/laurent_polynomial_ideal.py
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/msolve.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/ore_function_element.py
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/term_order.py
  src/sage/rings/qqbar_decorators.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/ring_extension_homset.py
Labels: s: positive review

#38859 `build/pkgs/matroid_database`: mark as math
  build/pkgs/matroid_database/math
Labels: s: positive review, c: packages: optional, c: matroid theory

#38860 Fix test if SAGE_ROOT is not defined
  src/sage/env.py
Labels: s: positive review

#38861 remove some unused variables
  src/sage/algebras/down_up_algebra.py
  src/sage/algebras/lie_algebras/affine_lie_algebra.py
  src/sage/algebras/lie_algebras/center_uea.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/categories/filtered_modules_with_basis.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
  src/sage/categories/simplicial_sets.py
  src/sage/categories/triangular_kac_moody_algebras.py
  src/sage/geometry/lattice_polytope.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/knots/knotinfo.py
  src/sage/libs/gap/test_long.py
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/modular/drinfeld_modform/ring.py
  src/sage/modules/with_basis/representation.py
  src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
  src/sage/rings/lazy_series_ring.py
  src/sage/schemes/curves/projective_curve.py
Labels: s: positive review

#38862 some spaces around % in pyx files
  src/sage/coding/codecan/autgroup_can_label.pyx
  src/sage/combinat/rigged_configurations/rigged_partition.pyx
  src/sage/groups/group.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_python.pyx
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/groups/semimonomial_transformations/semimonomial_transformation.pyx
  src/sage/libs/coxeter3/coxeter.pyx
  src/sage/libs/eclib/homspace.pyx
  src/sage/libs/eclib/mat.pyx
  src/sage/libs/eclib/mwrank.pyx
  src/sage/libs/eclib/newforms.pyx
  src/sage/libs/giac/giac.pyx
  src/sage/libs/libecm.pyx
  src/sage/libs/pari/convert_sage.pyx
  src/sage/matrix/misc.pyx
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/cachefunc.pyx
  src/sage/misc/constant_function.pyx
  src/sage/misc/function_mangling.pyx
  src/sage/misc/lazy_list.pyx
  src/sage/misc/persist.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/modules/vector_integer_dense.pyx
  src/sage/modules/vector_mod2_dense.pyx
  src/sage/modules/vector_modn_sparse.pyx
  src/sage/modules/vector_rational_sparse.pyx
  src/sage/modules/with_basis/indexed_element.pyx
  src/sage/numerical/backends/glpk_graph_backend.pyx
  src/sage/plot/complex_plot.pyx
  src/sage/plot/plot3d/base.pyx
  src/sage/plot/plot3d/shapes.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/sets/finite_set_map_cy.pyx
  src/sage/stats/time_series.pyx
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_actions.pyx
Labels: s: positive review

#38863 Fix testing of installed rst files
  src/sage/doctest/control.py
Labels: s: positive review

#38866 Fix build of coxeter3 extension with meson
  src/sage/libs/coxeter3/meson.build
Labels: s: positive review

#38867 Fix duplicate install of config.py in meson build
  src/sage/meson.build
Labels: s: positive review

#38873 src/sage/parallel/map_reduce.py: fixup start_workers() test case
  src/sage/parallel/map_reduce.py
Labels: s: positive review, p: CI Fix

#38876 minor details in piecewise functions
  src/sage/functions/piecewise.py
Labels: s: positive review, c: symbolics

#38881 using Parent in ring extensions
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/rings.py
  src/sage/rings/morphism.pyx
  src/sage/rings/number_field/order.py
  src/sage/rings/ring.pyx
  src/sage/rings/ring_extension.pxd
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_element.pxd
  src/sage/rings/ring_extension_element.pyx
  src/sage/rings/ring_extension_morphism.pyx
Labels: s: positive review

#38882 src/sage: revert "touch libgap consumers"
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/libgap.pyx
  src/sage/libs/gap/util.pyx
Labels: s: positive review

#38894 be explicit about messages
  src/sage/interfaces/fricas.py
Labels: s: positive review

#35949 Compute composite degree (separable) isogenies of EllipticCurves
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/hom.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#38629 `build/pkgs/pari`: Update to 2.15.5
  build/pkgs/pari/checksums.ini
  build/pkgs/pari/package-version.txt
Labels: c: packages: standard, s: positive review

#38675 Update gperftools integration for python3/musl
  src/sage/misc/gperftools.py
Labels: s: positive review, t: performance

#38711 `matroids`: Add `certificate` argument to `is_valid`
  src/sage/matroids/basis_exchange_matroid.pxd
  src/sage/matroids/basis_exchange_matroid.pyx
  src/sage/matroids/circuits_matroid.pxd
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/flats_matroid.pxd
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/graphic_matroid.pxd
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/linear_matroid.pxd
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
Labels: t: feature, s: needs review, s: positive review, c: matroid theory

#38817 a few simplified isinstance (ruff SIM101)
  src/sage/calculus/calculus.py
  src/sage/calculus/functions.py
  src/sage/coding/reed_muller_code.py
  src/sage/functions/transcendental.py
  src/sage/matroids/constructor.py
  src/sage/modular/abvar/abvar_ambient_jacobian.py
  src/sage/modular/abvar/torsion_subgroup.py
  src/sage/modular/dirichlet.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/modform/hecke_operator_on_qexp.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/numerical/optimize.py
  src/sage/plot/plot3d/plot3d.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/ternary_qf.py
  src/sage/schemes/affine/affine_space.py
  src/sage/schemes/berkovich/berkovich_cp_element.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/plane_conics/constructor.py
  src/sage/schemes/projective/projective_space.py
  src/sage/schemes/toric/fano_variety.py
  src/sage/sets/set.py
Labels: s: positive review, t: refactoring

#38821 let the category setup handle the ideals
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/fields.py
  src/sage/categories/rings.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: categories, t: refactoring

#38847 Graph tikz method fixup
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#38857 various small details in combinat
  src/sage/combinat/alternating_sign_matrix.py
  src/sage/combinat/lr_tableau.py
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/output.py
  src/sage/combinat/shard_order.py
Labels: s: positive review, c: combinatorics

#38281 Addition of Chow ring ideal and Chow ring classes
  src/doc/en/reference/matroids/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/matroids/chow_ring.py
  src/sage/matroids/chow_ring_ideal.py
  src/sage/matroids/matroid.pyx
Labels: s: positive review, c: combinatorics, c: algebra, c: matroid theory, gsoc: 2024

#38441 number_field_elements_from_algebraics: Fix CyclotomicField embedding when embedding=False
  src/sage/rings/qqbar.py
Labels: s: positive review, c: number fields

#38482 Dokchitser: Pass internal parameter over properly
  src/sage/lfunctions/dokchitser.py
  src/sage/modular/modform/l_series_gross_zagier.py
Labels: s: positive review, c: modular forms

#38728 Improve conda setup
  .devcontainer/onCreate-conda.sh
  .github/workflows/ci-conda.yml
  .github/workflows/ci-meson.yml
  .github/workflows/conda-lock-update.py
  .gitignore
  .gitpod.yml
  .vscode/settings.json
  bootstrap
  bootstrap-conda
  condarc.yml
  environment-3.10-linux-aarch64.yml
  environment-3.10-linux.yml
  environment-3.10-macos-x86_64.yml
  environment-3.10-macos.yml
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.9-linux-aarch64.yml
  environment-3.9-linux.yml
  environment-3.9-macos-x86_64.yml
  environment-3.9-macos.yml
  environment-dev-3.10-linux-aarch64.yml
  environment-dev-3.10-linux.yml
  environment-dev-3.10-macos-x86_64.yml
  environment-dev-3.10-macos.yml
  environment-dev-3.11-linux-aarch64.yml
  environment-dev-3.11-linux.yml
  environment-dev-3.11-macos-x86_64.yml
  environment-dev-3.11-macos.yml
  environment-dev-3.9-linux-aarch64.yml
  environment-dev-3.9-linux.yml
  environment-dev-3.9-macos-x86_64.yml
  environment-dev-3.9-macos.yml
  src/doc/en/installation/conda.rst
  src/doc/en/installation/launching.rst
  src/environment-3.10-linux-aarch64.yml
  src/environment-3.10-linux.yml
  src/environment-3.11-linux-aarch64.yml
  src/environment-3.11-macos-x86_64.yml
  src/environment-3.9-macos-x86_64.yml
  src/environment-3.9-macos.yml
  src/environment-dev-3.10-linux.yml
  src/environment-dev-3.11-linux-aarch64.yml
  src/environment-dev-3.11-linux.yml
  src/environment-dev-3.11-macos.yml
  src/environment-dev-3.9-macos-x86_64.yml
  src/environment-dev-3.9-macos.yml
Labels: s: positive review

#38742 Introduced the class `MatchingCoveredGraph`
  src/doc/en/reference/graphs/index.rst
  src/sage/graphs/all.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/matching.py
  src/sage/graphs/matching_covered_graph.py
  src/sage/graphs/meson.build
Labels: s: positive review, c: graph theory, gsoc: 2024

#38791 non recursive version of method `gomory_hu_tree` for graphs
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#38875 libsemigroup upgrade to 2.7.3
  build/pkgs/libsemigroups/checksums.ini
  build/pkgs/libsemigroups/package-version.txt
Labels: s: positive review, p: blocker / 1

#38885 Follow-up to #38822: Add missing package update in build/pkgs
  build/pkgs/database_knotinfo/checksums.ini
  build/pkgs/database_knotinfo/package-version.txt
Labels: s: positive review, p: blocker / 1, c: packages: optional, c: databases

#38899 src/sage/interfaces/singular.py: use GNU Info to read Singular's info
  src/sage/algebras/letterplace/free_algebra_element_letterplace.pyx
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/algebras/letterplace/letterplace_ideal.pyx
  src/sage/features/info.py
  src/sage/interfaces/singular.py
  src/sage/libs/singular/function.pyx
  src/sage/misc/sageinspect.py
Labels: s: positive review, c: interfaces

#38903 a few details in combinat, following ruff and pycodestyle
  src/sage/combinat/rigged_configurations/kleber_tree.py
  src/sage/combinat/tableau.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/morphism.py
Labels: s: positive review

#38908 Don't (mis)use `prec_words_to_bits()`
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: s: positive review, p: critical / 2

#38910 Meson: minor revision
  .gitignore
  meson.build
  src/meson.build
  src/sage/meson.build
Labels: s: positive review

#38913 Meson: Improve handling of dependencies
  src/meson.build
  src/sage/coding/codecan/meson.build
  src/sage/combinat/meson.build
  src/sage/combinat/root_system/meson.build
  src/sage/geometry/meson.build
  src/sage/groups/matrix_gps/meson.build
  src/sage/groups/meson.build
  src/sage/groups/perm_gps/partn_ref2/meson.build
  src/sage/libs/mpmath/meson.build
  src/sage/matrix/meson.build
  src/sage/misc/meson.build
  src/sage/rings/finite_rings/meson.build
  src/sage/rings/meson.build
  src/sage/rings/number_field/meson.build
  src/sage/rings/polynomial/meson.build
  src/sage/structure/meson.build
  src/sage/symbolic/meson.build
Labels: s: positive review, c: build

#38914 Replace `os.uname` by more universal `platform.system`
  src/sage/doctest/external.py
  src/sage/doctest/forker.py
  src/sage/env.py
  src/sage/interfaces/singular.py
  src/sage/misc/viewer.py
  src/sage_docbuild/utils.py
  src/sage_setup/setenv.py
Labels: s: positive review

#38915 Remove `register` macro in Ginac
  src/sage/symbolic/ginac/constant.cpp
  src/sage/symbolic/ginac/ex.cpp
  src/sage/symbolic/ginac/fderivative.cpp
  src/sage/symbolic/ginac/function.cpp
  src/sage/symbolic/ginac/inifcns_hyperg.cpp
  src/sage/symbolic/ginac/numeric.cpp
Labels: s: positive review

#38916 Fix Ginac cast error
  src/sage/symbolic/ginac/upoly-ginac.cpp
Labels: s: positive review

#38921 fixing ruff E714
  src/sage/algebras/shuffle_algebra.py
  src/sage/crypto/block_cipher/miniaes.py
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/graphs/graph.py
  src/sage/groups/abelian_gps/abelian_aut.py
  src/sage/groups/abelian_gps/abelian_group_gap.py
  src/sage/groups/affine_gps/group_element.py
  src/sage/interfaces/psage.py
  src/sage/logic/boolformula.py
  src/sage/misc/rest_index_of_methods.py
  src/sage/modules/fp_graded/morphism.py
  src/sage/rings/finite_rings/galois_group.py
  src/sage/rings/invariants/invariant_theory.py
  src/sage/rings/localization.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/valuation/gauss_valuation.py
Labels: s: positive review

#38922 remove the last use of PrincipalIdealDomain
  src/sage/rings/polynomial/polynomial_ring.py
Labels: s: positive review

#38923 remove some deprecated functionality
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/finite_field_givaro.py
  src/sage/rings/finite_rings/finite_field_ntl_gf2e.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_scalar.py
Labels: t: enhancement, s: positive review, p: trivial / 5

#38930 expunge is_commutative from plural
  src/sage/rings/polynomial/plural.pyx
Labels: s: positive review, c: algebra

#38931 OS X: do not use -ld_classic
  src/bin/sage-env
  src/sage/doctest/parsing.py
  src/sage/tests/cmdline.py
Labels: t: bug, p: minor / 4, s: positive review, c: build

#38932 Artifacts v4
  .github/workflows/ci-macos.yml
  .github/workflows/docker.yml
  .github/workflows/macos.yml
Labels: s: positive review

#38934 keep meson.build file for ext/interpreters
  .gitignore
  Makefile
  src/sage/ext/interpreters/README
Labels: s: positive review, c: build

#38938 Sanity check parent of Vector_numpy_integer_dense
  src/sage/modules/vector_numpy_integer_dense.pyx
Labels: s: positive review

#38941 Details yang baxter
  src/sage/combinat/yang_baxter_graph.py
Labels: s: positive review, c: combinatorics

#38942 deprecate is_generator for is_gen
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, t: refactoring

#38944 no longer ignore errors in method `union` of `DisjointSet`
  src/sage/sets/disjoint_set.pxd
  src/sage/sets/disjoint_set.pyx
Labels: s: positive review, c: combinatorics

#38948 move spkg tarballs from user.ox.ac.uk
  build/pkgs/cunningham_tables/checksums.ini
  build/pkgs/graphs/checksums.ini
  build/pkgs/planarity/checksums.ini
  build/pkgs/rubiks/checksums.ini
  build/pkgs/symmetrica/checksums.ini
  build/pkgs/tachyon/checksums.ini
  build/pkgs/topcom/checksums.ini
Labels: c: packages: experimental, s: positive review, c: packages: optional

#38954 Fix configure script generated by pkgconf-2.3.0
  configure.ac
Labels: s: positive review, p: blocker / 1, c: scripts

#38957 rebase sage_autodoc to sphinx 8.1.3
  src/sage_docbuild/ext/sage_autodoc.py
Labels: s: positive review, c: documentation

#38961 Iteration over infinite abelian groups
  src/sage/groups/abelian_gps/abelian_group.py
Labels: s: positive review

#38963 Disallow scaling of quaternion fractional ideals by zero
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: t: bug, p: minor / 4, s: positive review, c: algebra

#38964 Drinfeld Modules: Default to zero endomorphism in `.hom` and avoid inversion of zero endomorphism
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/morphism.py
Labels: t: bug, t: enhancement, p: minor / 4, s: positive review, c: algebra

#38446 Implement basic multivariate polynomial species
  src/doc/en/reference/references/index.rst
  src/sage/categories/filtered_modules_with_basis.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/rings/species.py
Labels: s: positive review, c: combinatorics, c: algebra, gsoc: 2024

#38979 Python3 build does not find openssl without pkgconf
  build/pkgs/python3/dependencies
Labels: s: positive review, p: blocker / 1

#38810 Introduce negated optional tag
  src/doc/en/developer/coding_basics.rst
  src/sage/databases/sloane.py
  src/sage/doctest/parsing.py
  src/sage/features/dot2tex.py
  src/sage/features/sloane_database.py
  src/sage/graphs/graph_latex.py
  src/sage/groups/perm_gps/cubegroup.py
Labels: s: positive review, c: doctest framework, p: blocker / 1

#38982 Fix meson build by adding missing files
  src/meson.build
  src/sage/matroids/meson.build
  src/sage/rings/meson.build
Labels: s: positive review, p: blocker / 1

#39003 CI Fix: Do not upload logs artifact for the default job in CI Linux
  .github/workflows/ci-linux.yml
  .github/workflows/docker.yml
Labels: s: positive review, p: blocker / 1
