Repository sagemath/sage, pull requests merged in 2024-03, with the labels that each got.

#37198 Translate "A Tour of Sage" into Greek
  src/doc/el/a_tour_of_sage/conf.py
  src/doc/el/a_tour_of_sage/eigen_plot.png
  src/doc/el/a_tour_of_sage/index.rst
  src/doc/el/a_tour_of_sage/sin_plot.png
  src/doc/en/website/root_index.html
Labels: s: positive review, c: documentation, c: translations

#37251 ntl 11.5.1
  build/pkgs/ntl/checksums.ini
  build/pkgs/ntl/package-version.txt
Labels: c: packages: standard, s: positive review

#37257 `sage.groups.generic`: Fix incorrect identity testing
  src/sage/groups/generic.py
  src/sage/schemes/curves/point.py
  src/sage/schemes/generic/homset.py
  src/sage/schemes/projective/projective_morphism.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: group theory

#37264 PDF docbuild: Reduce verbosity
  src/doc/Makefile
Labels: s: positive review, c: build, c: documentation

#37288 Directly convert PermutationGroup element into sized Permutation
  src/sage/combinat/permutation.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: group theory

#37309 README.md: Move all mentions of release tarballs to the installation guide
  README.md
  src/doc/en/developer/doctesting.rst
  src/doc/en/developer/git_setup.rst
  src/doc/en/developer/walkthrough.rst
  src/doc/en/installation/source.rst
Labels: s: positive review, p: critical / 2, c: documentation

#37322 `sage --package create`: Attempt to bring SPKG.rst title to a common style
  build/pkgs/appdirs/SPKG.rst
  build/pkgs/appdirs/checksums.ini
  build/pkgs/appdirs/spkg-install.in
  build/pkgs/colorama/SPKG.rst
  build/pkgs/cvxpy/SPKG.rst
  build/pkgs/cylp/SPKG.rst
  build/pkgs/json5/SPKG.rst
  build/pkgs/jupyterlab_server/SPKG.rst
  build/pkgs/kiwisolver/SPKG.rst
  build/pkgs/mathics/SPKG.rst
  build/pkgs/mathics_scanner/SPKG.rst
  build/pkgs/mistune/SPKG.rst
  build/pkgs/nbclient/SPKG.rst
  build/pkgs/overrides/SPKG.rst
  build/pkgs/pari_jupyter/SPKG.rst
  build/pkgs/pathspec/SPKG.rst
  build/pkgs/phitigra/SPKG.rst
  build/pkgs/platformdirs/SPKG.rst
  build/pkgs/pluggy/SPKG.rst
  build/pkgs/py/SPKG.rst
  build/pkgs/python_json_logger/SPKG.rst
  build/pkgs/sage_flatsurf/SPKG.rst
  build/pkgs/soupsieve/SPKG.rst
  build/pkgs/sphinx_basic_ng/SPKG.rst
  build/pkgs/sphinx_copybutton/SPKG.rst
  build/pkgs/sphinx_inline_tabs/SPKG.rst
  build/pkgs/trove_classifiers/SPKG.rst
  build/pkgs/urllib3/SPKG.rst
  build/pkgs/webcolors/SPKG.rst
  build/sage_bootstrap/creator.py
Labels: p: minor / 4, s: positive review, c: documentation, c: scripts

#37331 Fixed the doc `sets/recursively_enumerated_set.py`
  src/sage/sets/recursively_enumerated_set.pyx
Labels: p: minor / 4, s: positive review, c: documentation

#37335 some details in modules (ruff and pep)
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/fp_graded/free_element.py
  src/sage/modules/fp_graded/morphism.py
  src/sage/modules/free_module.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/vector_space_morphism.py
Labels: s: positive review, t: refactoring

#37343 Add simple methods to convert to and from bytes for `ZZ` and finite fields
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/integer_ring.pyx
Labels: t: enhancement, p: minor / 4, s: positive review

#37345 implemented function for acyclic orientations
  src/doc/en/reference/references/index.rst
  src/sage/graphs/graph.py
  src/sage/graphs/orientations.py
Labels: p: major / 3, t: feature, s: positive review, c: graph theory

#36581 `sage/stats/distributions`: Implement non-spherical Gaussian sampling over lattices
  src/doc/en/reference/references/index.rst
  src/sage/stats/all.py
  src/sage/stats/distributions/all.py
  src/sage/stats/distributions/catalog.py
  src/sage/stats/distributions/discrete_gaussian_lattice.py
  src/sage/stats/distributions/discrete_gaussian_polynomial.py
Labels: p: major / 3, t: feature, s: positive review, c: statistics

#36741 Doctest hide option: Better detection of hidden packages
  src/sage/doctest/control.py
  src/sage/features/__init__.py
  src/sage/features/databases.py
  src/sage/features/gap.py
  src/sage/features/join_feature.py
Labels: s: positive review, c: doctest framework

#36748 Implement Specht modules in the tabloid basis
  src/sage/combinat/algebraic_combinatorics.py
  src/sage/combinat/catalog_partitions.py
  src/sage/combinat/composition.py
  src/sage/combinat/partition.py
  src/sage/combinat/permutation.py
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/modules/with_basis/subquotient.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: algebra

#36907 Implementation of the quantum oscillator algebra
  src/doc/en/reference/algebras/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/algebras/catalog.py
  src/sage/algebras/quantum_oscillator.py
Labels: t: enhancement, s: positive review, c: algebra

#36970 CI: Upload test stats as artifacts, improve output of "List Docker images"
  .github/workflows/docker.yml
  build/bin/write-dockerfile.sh
  build/pkgs/info/checksums.ini
  build/pkgs/info/package-version.txt
  tox.ini
Labels: c: packages: standard, s: positive review, c: scripts

#36971 add helper method to concatenate vectors
  src/sage/modules/free_module_element.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: linear algebra

#37011 allowing external ECM to be called gmp-ecm or ecm
  build/pkgs/ecm/spkg-configure.m4
  pkgs/sage-conf/_sage_conf/_conf.py.in
  src/sage/env.py
  src/sage/features/ecm.py
  src/sage/interfaces/ecm.py
Labels: s: positive review, c: build: configure

#37013 Implement the center of a universal enveloping algebra in the PBW basis
  src/doc/en/reference/algebras/lie_algebras.rst
  src/doc/en/reference/references/index.rst
  src/sage/algebras/lie_algebras/center_uea.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
  src/sage/algebras/lie_algebras/poincare_birkhoff_witt.py
  src/sage/algebras/lie_algebras/virasoro.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
  src/sage/categories/lie_algebras.py
  src/sage/categories/lie_algebras_with_basis.py
  src/sage/categories/magmatic_algebras.py
  src/sage/monoids/indexed_free_monoid.py
  src/sage/rings/polynomial/plural.pxd
  src/sage/rings/polynomial/plural.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37054 `CODE_OF_CONDUCT.md`: Do not send people to sage-flame
  CODE_OF_CONDUCT.md
Labels: s: positive review, c: documentation

#37083 HTML documentation: Show preparsed doctests using inline tabs
  .ci/merge-fixes.sh
  .github/workflows/build.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  src/doc/common/static/custom-jupyter-sphinx.css
  src/doc/common/static/jupyter-sphinx-furo.js
  src/doc/en/installation/source.rst
  src/sage_docbuild/__main__.py
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation

#37100 Quaternion Algebra Fractional Ideal improvements - equivalence and reduced bases
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/modular/quatalg/brandt.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37118 Fix random polynomial bias
  src/sage/crypto/lattice.py
  src/sage/crypto/lwe.py
  src/sage/misc/randstate.pyx
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/tests.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#37127 Rerun `configure` less often
  Makefile
Labels: p: minor / 4, s: positive review, c: build

#35517 implement the depth of a quasimodular form
  src/sage/modular/quasimodform/element.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: modular forms

#36329 Implement call method for elements in CDGA's
  src/sage/algebras/commutative_dga.py
Labels: t: enhancement, s: positive review, c: algebra

#35029 Implement basis_of_weight for rings of quasimodular forms
  src/sage/modular/quasimodform/ring.py
Labels: t: enhancement, p: minor / 4, s: positive review, c: modular forms

#37622 Ensure the `degree()` method of `Polynomial_generic_dense_inexact` returns an `Integer`
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: p: minor / 4, s: positive review

#37701 Default SAGE_ECMBIN to "ecm".
  src/sage/env.py
Labels: t: bug, c: packages: standard, s: positive review, p: blocker / 1

#37465 use Parent for the Pari pseudo-ring
  src/sage/rings/pari_ring.py
Labels: p: minor / 4, s: positive review, c: commutative algebra, t: refactoring

#37485 Developer Guide: Improve section on patching third-party packages
  src/doc/en/developer/packaging.rst
Labels: s: positive review, c: documentation

#37489 Fix failing docstring in random testing for `quaternion_algebra.py`
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: t: bug, s: positive review, t: tests, c: algebra, p: CI Fix

#37490 Include `random_element()` method to `LaurentPolynomialRing`
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
Labels: p: minor / 4, s: positive review, c: commutative algebra

#37498 build/pkgs/gnumake_tokenpool: Update to 0.0.7
  build/pkgs/gnumake_tokenpool/checksums.ini
  build/pkgs/gnumake_tokenpool/package-version.txt
Labels: c: packages: standard, s: positive review

#37499 use sparse polynomials for generating functions
  src/sage/databases/findstat.py
Labels: s: positive review, c: combinatorics

#37501 Code of conduct changes
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_COMMITTEE.md
Labels: s: positive review, p: critical / 2, c: documentation, pending

#37521 fix debian.txt for qhull
  build/pkgs/qhull/distros/debian.txt
Labels: s: positive review, p: trivial / 5, c: build: configure

#37522 Add `mypy.ini`
  src/mypy.ini
Labels: s: positive review, c: scripts

#37538 Improve genus method of function fields and curves
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/constructor.py
  src/sage/schemes/curves/curve.py
  src/sage/schemes/curves/projective_curve.py
Labels: s: positive review, c: algebraic geometry

#37540 Update the year in README.md
  README.md
Labels: s: positive review, c: documentation

#37542 Edit docstrings attached to free resolutions
  src/sage/homology/free_resolution.py
  src/sage/homology/graded_resolution.py
Labels: p: minor / 4, s: positive review, c: documentation, c: linear algebra, c: commutative algebra

#37545 various list-comprehension in combinat (ruff PERF)
  src/sage/combinat/chas/fsym.py
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/composition.py
  src/sage/combinat/designs/covering_design.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/rigged_configurations/rigged_configuration_element.py
  src/sage/combinat/set_partition.py
  src/sage/combinat/sf/new_kschur.py
  src/sage/combinat/sf/ns_macdonald.py
  src/sage/combinat/tableau.py
  src/sage/combinat/words/morphism.py
Labels: s: positive review, c: combinatorics

#37549 Faster chromatic symmetric function computation
  src/sage/graphs/graph.py
Labels: s: positive review, c: combinatorics, c: graph theory, t: performance

#37551 minor details + non-recursive algo in integer_valued_polynomials
  src/sage/rings/polynomial/integer_valued_polynomials.py
Labels: s: positive review, c: commutative algebra

#37552 convert Puiseux ring to Parent framework
  src/sage/rings/puiseux_series_ring.py
Labels: s: positive review, c: commutative algebra, t: refactoring

#37553 A minor change in the documentation of `__hash__` function of `FreeModuleElement` class
  src/sage/modules/free_module_element.pyx
Labels: s: positive review, c: documentation, c: linear algebra

#37554 Implemented the (local) Hilbert symbol for global function fields
  src/sage/rings/function_field/function_field.py
Labels: p: major / 3, t: feature, s: positive review, c: algebra

#37555 use Parent in Symbolic Ring
  src/sage/symbolic/ring.pyx
Labels: s: positive review, c: symbolics, t: refactoring

#37556 refresh sha_tate.py
  src/sage/schemes/elliptic_curves/sha_tate.py
Labels: s: positive review, c: elliptic curves

#37557 Modified quaternion algebra documentation
  src/doc/en/reference/references/index.rst
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: s: positive review, c: documentation, p: trivial / 5

#37561 enrich the test_karatsuba failure message with explicit elements
  src/sage/rings/tests.py
Labels: s: positive review

#37564 use Parent in infinity
  src/sage/rings/infinity.py
Labels: s: positive review, c: symbolics, t: refactoring

#37567 Improve documentation for `degree()` method of singular multivariate polynomials
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: p: minor / 4, s: positive review, c: commutative algebra

#37571 Improve method `_ford fulkerson chronicle` in `src/sage/combinat/posets/posets.py`
  src/sage/combinat/posets/posets.py
Labels: t: enhancement, s: positive review, c: combinatorics

#37573 Doctester: Abbreviate tracebacks in warnings
  src/sage/doctest/forker.py
Labels: s: positive review, c: doctest framework

#37575 Intersphinx for cvxopt, cvxpy, cypari2, cysignals, flint, fpylll, gmpy2, ipywidgets, matplotlib, mpmath, networkx, numpy, rpy2, scipy, sympy
  src/doc/common/_vendor/cvxopt.inv
  src/doc/common/_vendor/cvxpy.inv
  src/doc/common/_vendor/cypari2.inv
  src/doc/common/_vendor/cysignals.inv
  src/doc/common/_vendor/flint.inv
  src/doc/common/_vendor/fpylll.inv
  src/doc/common/_vendor/gmpy2.inv
  src/doc/common/_vendor/ipywidgets.inv
  src/doc/common/_vendor/matplotlib.inv
  src/doc/common/_vendor/mpmath.inv
  src/doc/common/_vendor/networkx.inv
  src/doc/common/_vendor/numpy.inv
  src/doc/common/_vendor/pplpy.inv
  src/doc/common/_vendor/python.inv
  src/doc/common/_vendor/rpy2.inv
  src/doc/common/_vendor/scipy.inv
  src/doc/common/_vendor/sympy.inv
  src/doc/common/python3.inv
  src/doc/common/update-python-inv.sh
  src/doc/en/developer/sage_manuals.rst
  src/doc/en/reference/matrices/index.rst
  src/sage/calculus/desolvers.py
  src/sage/graphs/generators/families.py
  src/sage/graphs/generic_graph.py
  src/sage/libs/flint/arith_sage.pyx
  src/sage/manifolds/differentiable/integrated_curve.py
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/modules/vector_double_dense.pyx
  src/sage/numerical/optimize.py
  src/sage/stats/basic_stats.py
  src/sage_docbuild/conf.py
  src/sage_docbuild/vendor.py
Labels: s: positive review, c: build, c: documentation

#37579 Update package dependencies for Fedora and Arch distros
  build/pkgs/cliquer/distros/arch.txt
  build/pkgs/fplll/distros/arch.txt
  build/pkgs/libbraiding/distros/fedora.txt
  build/pkgs/linbox/distros/fedora.txt
  build/pkgs/maxima/distros/fedora.txt
  build/pkgs/primecount/distros/debian.txt
Labels: c: packages: standard, s: positive review

#37589 Add links to sources in documentation
  src/doc/ca/intro/conf.py
  src/doc/common/static/custom-furo.css
  src/doc/de/a_tour_of_sage/conf.py
  src/doc/de/thematische_anleitungen/conf.py
  src/doc/de/tutorial/conf.py
  src/doc/en/a_tour_of_sage/conf.py
  src/doc/en/constructions/conf.py
  src/doc/en/developer/conf.py
  src/doc/en/faq/conf.py
  src/doc/en/installation/conf.py
  src/doc/en/prep/conf.py
  src/doc/en/reference/conf.py
  src/doc/en/reference/conf_sub.py
  src/doc/en/thematic_tutorials/conf.py
  src/doc/en/tutorial/conf.py
  src/doc/es/a_tour_of_sage/conf.py
  src/doc/es/tutorial/conf.py
  src/doc/fr/a_tour_of_sage/conf.py
  src/doc/fr/tutorial/conf.py
  src/doc/hu/a_tour_of_sage/conf.py
  src/doc/it/a_tour_of_sage/conf.py
  src/doc/it/faq/conf.py
  src/doc/it/tutorial/conf.py
  src/doc/ja/a_tour_of_sage/conf.py
  src/doc/ja/tutorial/conf.py
  src/doc/pt/a_tour_of_sage/conf.py
  src/doc/pt/tutorial/conf.py
  src/doc/ru/tutorial/conf.py
  src/doc/tr/a_tour_of_sage/conf.py
  src/sage/misc/sageinspect.py
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation

#37590 Do not canonicalize generators when building a permutation group from a libGAP group
  src/doc/en/prep/Quickstarts/Abstract-Algebra.rst
  src/doc/en/thematic_tutorials/group_theory.rst
  src/sage/categories/finite_groups.py
  src/sage/categories/groups.py
  src/sage/categories/monoids.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/abelian_gps/abelian_group_element.py
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/class_function.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/tests/books/judson-abstract-algebra/cosets-sage.py
  src/sage/tests/books/judson-abstract-algebra/galois-sage.py
  src/sage/tests/books/judson-abstract-algebra/homomorph-sage.py
  src/sage/tests/books/judson-abstract-algebra/sylow-sage.py
Labels: p: major / 3, t: bug, s: positive review, c: group theory

#37591 ruff PERF fixes in algebras/
  src/sage/algebras/free_algebra.py
  src/sage/algebras/free_zinbiel_algebra.py
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/algebras/schur_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra_bases.py
Labels: s: positive review, c: algebra

#37595 Simplify computation of all points for curves over finite fields
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: p: minor / 4, s: positive review, c: elliptic curves

#37596 fix performance regression in elliptic-curve point constructor
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/projective/projective_point.py
Labels: p: major / 3, t: bug, s: positive review, c: elliptic curves

#37598 Sphinx extlinks for ecl, gap, giac, maxima, meson, ppl, qepcad, scip, singular, soplex
  src/doc/en/developer/sage_manuals.rst
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/generic.py
  src/sage/groups/matrix_gps/finitely_generated_gap.py
  src/sage/libs/gap/util.pyx
  src/sage/misc/sagedoc.py
Labels: s: positive review, c: build, c: documentation

#37599 extend the definition of q-binomial coefficients to (k > 0, n < 0)
  src/sage/combinat/q_analogues.py
Labels: s: positive review, c: combinatorics

#37600 some details in lrcalc
  src/sage/libs/lrcalc/lrcalc.py
Labels: s: positive review, c: combinatorics, t: performance

#37602 `graphs.triangulations(3)` cannot return a triangle
  src/sage/graphs/graph_generators.py
Labels: t: enhancement, s: positive review, c: graph theory

#37604 Remove duplicated functions from genus two hyperelliptic curves
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_g2.py
Labels: s: positive review, p: trivial / 5, t: refactoring

#37605 Ensure returned degree of multivariate polynomial is type `Integer` for `MPolynomialRing_libsingular` class
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: p: minor / 4, s: positive review, c: commutative algebra

#37607 src/sage/matrix: Doctest cosmetics
  src/sage/matrix/action.pyx
  src/sage/matrix/args.pyx
  src/sage/matrix/compute_J_ideal.py
  src/sage/matrix/constructor.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_generic_sparse.pyx
  src/sage/matrix/matrix_space.py
  src/sage/matrix/matrix_sparse.pyx
  src/sage/matrix/symplectic_basis.py
Labels: s: positive review, c: linear algebra, t: refactoring

#37608 src/sage/modules: Doctest cosmetics
  src/sage/modules/free_module.py
  src/sage/modules/free_module_element.pyx
  src/sage/modules/free_module_homspace.py
  src/sage/modules/free_module_integer.py
  src/sage/modules/free_module_morphism.py
  src/sage/modules/free_quadratic_module.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/quotient_module.py
  src/sage/modules/torsion_quadratic_module.py
  src/sage/modules/vector_integer_dense.pyx
  src/sage/modules/vector_modn_dense.pyx
  src/sage/modules/with_basis/indexed_element.pyx
Labels: s: positive review, c: linear algebra, t: refactoring

#37609 src/sage/schemes: Doctest cosmetics
  src/sage/schemes/elliptic_curves/Qcurves.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_local_data.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/gal_reps_number_field.py
  src/sage/schemes/elliptic_curves/kraus.py
  src/sage/schemes/elliptic_curves/period_lattice.py
  src/sage/schemes/elliptic_curves/period_lattice_region.pyx
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/generic/ambient_space.py
  src/sage/schemes/hyperelliptic_curves/mestre.py
  src/sage/schemes/projective/proj_bdd_height.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/schemes/projective/projective_point.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
Labels: s: positive review, c: algebraic geometry, c: elliptic curves, t: refactoring

#37610 src/sage/combinat: Doctest cosmetics
  src/sage/combinat/binary_tree.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/free_dendriform_algebra.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/matrices/latin.py
  src/sage/combinat/necklace.py
  src/sage/combinat/partition.py
  src/sage/combinat/partition_tuple.py
  src/sage/combinat/path_tableaux/semistandard.py
  src/sage/combinat/permutation.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/posets/linear_extensions.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/q_bernoulli.pyx
  src/sage/combinat/schubert_polynomial.py
  src/sage/combinat/subword_complex.py
  src/sage/combinat/tableau_tuple.py
  src/sage/combinat/tiling.py
  src/sage/combinat/yang_baxter_graph.py
Labels: s: positive review, c: combinatorics, t: refactoring

#37611 Ensure degree and total degree return `Integer` type for `MPolynomial_polydict` class
  src/sage/rings/polynomial/multi_polynomial_element.py
Labels: p: minor / 4, s: positive review, c: commutative algebra, t: refactoring

#37613 Fix hyperelliptic curve dynamic class construction to allow proper method inheritance
  src/sage/schemes/hyperelliptic_curves/constructor.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_g2.py
Labels: p: major / 3, t: bug, s: positive review, c: elliptic curves

#37617 Updated README.md, added space after -p option
  docker/README.md
Labels: s: positive review, c: documentation, c: docker

#37619 Implement the Potts representation of the partition algebra
  src/doc/en/reference/references/index.rst
  src/sage/combinat/diagram_algebras.py
Labels: p: major / 3, t: enhancement, s: positive review, c: combinatorics, c: algebra

#37623 src/sage/rings: Doctest cosmetics
  src/sage/rings/complex_conversion.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/finite_rings/residue_field_givaro.pyx
  src/sage/rings/function_field/function_field_polymod.py
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/puiseux_series_ring_element.pyx
  src/sage/rings/qqbar.py
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/tate_algebra_element.pyx
  src/sage/rings/valuation/augmented_valuation.py
Labels: s: positive review, t: refactoring

#37624 test gap3 with gap3, not gap (gap4)
  src/sage/interfaces/gap3.py
Labels: c: packages: experimental, s: positive review

#37628 use the polynomial ring also for non-commutative baserings as _internal_poly_ring
  src/sage/rings/lazy_series_ring.py
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#37629 Implement a __bool__ for posets
  src/sage/combinat/posets/posets.py
Labels: t: bug, p: minor / 4, s: positive review, c: combinatorics

#37369 Faster scalar multiplication for python types
  src/sage/structure/parent.pyx
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#37377 fix bad Frac(sparse polynomial ring over finite field)
  src/sage/rings/fraction_field_FpT.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_ring.py
Labels: t: bug, s: positive review

#37392 `build/pkgs/pyscipopt`: Update to 4.4.0, add Cython 3 patch
  build/pkgs/pyscipopt/SPKG.rst
  build/pkgs/pyscipopt/checksums.ini
  build/pkgs/pyscipopt/package-version.txt
  build/pkgs/pyscipopt/patches/792.patch
Labels: s: positive review, p: critical / 2, c: packages: optional

#37393 Tensor, exterior, and symmetric product of semigroup representations
  src/sage/algebras/clifford_algebra.py
  src/sage/categories/coxeter_groups.py
  src/sage/groups/artin.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/modules/with_basis/indexed_element.pyx
  src/sage/modules/with_basis/representation.py
  src/sage/structure/indexed_generators.py
Labels: t: enhancement, s: positive review, c: algebra

#37399 Developer Guide: Document practices for data files
  src/doc/en/developer/coding_basics.rst
  src/doc/en/developer/coding_in_python.rst
Labels: s: positive review, c: documentation

#37400 minor ruff fixes in quadratic forms (C4, UP, PERF)
  src/sage/quadratic_forms/binary_qf.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quadratic_forms/genera/spinor_genus.py
  src/sage/quadratic_forms/quadratic_form__neighbors.py
Labels: s: positive review, c: quadratic forms, t: refactoring

#37401 Developer Guide: Improvements to explanation of version files
  src/doc/en/developer/packaging.rst
Labels: s: positive review, p: critical / 2, c: documentation

#37403 Use "Issue #" for github issue links
  build/pkgs/cylp/SPKG.rst
  src/doc/en/developer/packaging.rst
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/en/installation/source.rst
  src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst
  src/doc/en/reference/coercion/index.rst
  src/doc/en/reference/combinat/module_list.rst
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/nf_introduction.rst
  src/doc/en/thematic_tutorials/lie/weyl_groups.rst
  src/doc/en/thematic_tutorials/linear_programming.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_advanced.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_plane.rst
  src/sage/graphs/path_enumeration.pyx
  src/sage/libs/giac/giac.pyx
  src/sage/libs/ntl/ntl_GF2EX.pyx
  src/sage/libs/ntl/ntl_ZZ_p.pyx
  src/sage/libs/ntl/ntl_ZZ_pE.pyx
  src/sage/libs/ntl/ntl_ZZ_pX.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/misc/dev_tools.py
  src/sage/misc/reset.pyx
  src/sage/misc/sagedoc.py
  src/sage/modules/with_basis/indexed_element.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/polynomial/polynomial_real_mpfr_dense.pyx
  src/sage/rings/rational.pyx
  src/sage/sets/family.pyx
  src/sage/structure/factory.pyx
  src/sage/structure/parent.pyx
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/function.pyx
  src/sage_docbuild/builders.py
  src/sage_docbuild/conf.py
  src/sage_docbuild/sphinxbuild.py
  src/sage_docbuild/utils.py
  src/sage_setup/excepthook.py
Labels: s: positive review, c: documentation

#37404 add a polytope method to hypergeometric motives
  src/doc/en/reference/references/index.rst
  src/sage/modular/hypergeometric_motive.py
Labels: s: positive review, c: algebraic geometry

#37406 remove most references to Arb as an independent library
  COPYING.txt
  build/bin/sage-package
  build/sage_bootstrap/app.py
  build/sage_bootstrap/cmdline.py
  src/doc/en/developer/portability_testing.rst
  src/doc/en/reference/rings_numerical/index.rst
  src/sage/arith/misc.py
  src/sage/features/sagemath.py
  src/sage/matrix/matrix_complex_ball_dense.pxd
  src/sage/matrix/matrix_complex_ball_dense.pyx
  src/sage/misc/package.py
  src/sage/numerical/gauss_legendre.pyx
  src/sage/rings/complex_arb.pxd
  src/sage/rings/complex_arb.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pxd
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/polynomial/polynomial_complex_arb.pxd
  src/sage/rings/polynomial/polynomial_complex_arb.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/real_arb.pxd
  src/sage/rings/real_arb.pyx
  src/sage/schemes/elliptic_curves/cm.py
Labels: s: positive review, c: documentation, t: refactoring

#37411 src/doc/en/installation/source.rst: Add section on upgrading using worktrees
  src/doc/en/developer/git_basic.rst
  src/doc/en/installation/source.rst
Labels: t: enhancement, s: positive review, c: documentation

#37412 Add as_subscheme() method for rational points
  src/sage/schemes/affine/affine_point.py
  src/sage/schemes/projective/projective_point.py
Labels: t: enhancement, s: positive review, c: algebraic geometry

#37420 Remove long/int relic
  src/sage/rings/integer.pxd
  src/sage/rings/integer.pyx
  src/sage/rings/integer_ring.pyx
Labels: s: positive review, p: trivial / 5

#37421 Make `sage -b` equivalent to `make sagelib-no-deps` regarding parallelism
  src/bin/sage
  src/setup.py
Labels: s: positive review, c: build

#37422 `sage.parallel.ncpus`: Use `os.sched_getaffinity` or `os.cpu_count`
  src/sage/parallel/ncpus.py
Labels: s: positive review, t: refactoring

#37423 Fix docstring for polyhedron constructor
  src/sage/geometry/polyhedron/constructor.py
Labels: s: positive review, t: tests, c: geometry

#37424 Edit hypellfrob.pyx
  src/doc/en/reference/references/index.rst
  src/sage/schemes/hyperelliptic_curves/hypellfrob.pyx
  src/sage/schemes/hyperelliptic_curves/hypellfrob/README
Labels: p: minor / 4, s: positive review, c: documentation

#37432 `setup.py`: Remove `lazy_import_cache` use
  build/pkgs/sagelib/spkg-install.in
  pkgs/sagemath-standard/setup.py
  src/sage/misc/lazy_import_cache.py
  src/setup.py
Labels: s: positive review, c: build

#37433 src/sage/misc/lazy_import.pyx: Deprecate star imports
  src/sage/misc/lazy_import.pyx
Labels: s: positive review, t: refactoring

#37435 small cleanup in monoids
  src/sage/monoids/automatic_semigroup.py
  src/sage/monoids/free_abelian_monoid.py
  src/sage/monoids/free_abelian_monoid_element.pyx
  src/sage/monoids/free_monoid.py
  src/sage/monoids/free_monoid_element.py
  src/sage/monoids/hecke_monoid.py
  src/sage/monoids/indexed_free_monoid.py
  src/sage/monoids/monoid.py
  src/sage/monoids/string_monoid.py
  src/sage/monoids/string_monoid_element.py
  src/sage/monoids/string_ops.py
  src/sage/monoids/trace_monoid.py
Labels: s: positive review, c: algebra, t: refactoring

#37439 a few details in cython files in symbolic
  src/sage/symbolic/constants.py
  src/sage/symbolic/constants_c_impl.pxi
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/function.pyx
  src/sage/symbolic/getitem_impl.pxi
  src/sage/symbolic/ginac/function_info.cpp
  src/sage/symbolic/ginac/sum.cpp
  src/sage/symbolic/pynac.pxi
  src/sage/symbolic/pynac_constant_impl.pxi
  src/sage/symbolic/pynac_impl.pxi
  src/sage/symbolic/substitution_map_impl.pxi
Labels: s: positive review, t: refactoring

#37440 Strengthen inequality in rigorous_line_integral
  src/sage/schemes/riemann_surfaces/riemann_surface.py
Labels: t: bug, s: positive review, c: algebraic geometry, c: numerical

#37444 Remove mention of `SPKG.txt`
  build/bin/sage-site
  build/bin/sage-spkg-info
  build/pkgs/glpk/SPKG.rst
  build/pkgs/glpk/spkg-check.in
  build/pkgs/glpk/spkg-install.in
  src/doc/en/developer/packaging.rst
Labels: p: minor / 4, s: positive review, c: documentation

#37449 formal deprecation of old group class
  src/sage/categories/action.pyx
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/group.pyx
  src/sage/groups/old.pyx
  src/sage/modular/arithgroup/arithgroup_generic.py
Labels: s: positive review, c: group theory, t: refactoring

#37452 Add config for ruff (#36503, unbundled)
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  .vscode/settings.json
  ruff.toml
Labels: s: positive review, c: scripts, disputed

#37464 formal deprecation of old CommutativeAlgebra class
  src/sage/rings/commutative_algebra.py
  src/sage/rings/ring.pyx
Labels: p: minor / 4, s: positive review, c: commutative algebra, t: refactoring

#37466 remove almost all calls to is_Ring
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_rational_dense.pyx
  src/sage/matrix/matrix_sparse.pyx
  src/sage/matrix/special.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/dirichlet.py
  src/sage/modules/free_module_element.pyx
  src/sage/quadratic_forms/random_quadraticform.py
  src/sage/quadratic_forms/ternary_qf.py
  src/sage/rings/fraction_field.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_ring_constructor.py
  src/sage/schemes/elliptic_curves/constructor.py
Labels: p: minor / 4, s: positive review, c: commutative algebra, t: refactoring

#37468 some list comprehensions in rings (ruff PERF401)
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/derivation.py
  src/sage/rings/fraction_field.py
  src/sage/rings/function_field/divisor.py
  src/sage/rings/invariants/invariant_theory.py
  src/sage/rings/number_field/S_unit_solver.py
  src/sage/rings/number_field/bdd_height.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/qqbar.py
Labels: p: minor / 4, s: positive review, t: refactoring

#37469 various details in permutation.py (pep8 and ruff PERF)
  src/sage/combinat/permutation.py
Labels: t: enhancement, p: minor / 4, s: positive review

#37478 build/pkgs/pari_jupyter: Update to 1.4.3 (includes Cython 3 fix)
  build/pkgs/pari_jupyter/checksums.ini
  build/pkgs/pari_jupyter/package-version.txt
Labels: t: bug, s: positive review, p: critical / 2, c: packages: optional

#37172 Fix three polynomial SIGABRT bugs #37169 and #37317
  src/sage/libs/flint/nmod_poly_linkage.pxi
  src/sage/libs/ntl/ntl_ZZ_pEX_linkage.pxi
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/ring.pyx
Labels: t: bug, p: minor / 4, s: positive review, c: commutative algebra
