Repository sagemath/sage, pull requests merged in 2024-07, with the labels that each got.

#38201 Replace uses of `setup.py bdist_wheel` and direct uses of `python3 -m build`
  build/bin/sage-dist-helpers
  build/pkgs/sage_conf/spkg-install.in
  build/pkgs/sage_docbuild/spkg-install.in
  build/pkgs/sage_setup/spkg-install.in
  build/pkgs/sage_sws2rst/spkg-install.in
  build/pkgs/sagelib/spkg-install.in
  build/pkgs/sagemath_objects/spkg-install.in
  src/doc/en/developer/packaging.rst
Labels: s: positive review, c: build, p: blocker / 1, v: small

#38220 Fix doc deployment to netlify for releases
  .ci/create-changes-html.sh
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/doc-publish.yml
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation, p: blocker / 1, c: scripts, v: moderate

#38304 Fix sagelib install with `configure --disable-editable`
  build/pkgs/sagelib/spkg-install.in
Labels: s: positive review, c: build, p: blocker / 1, v: minimal

#38285 Add version selector to doc
  .github/workflows/doc-build.yml
  .github/workflows/doc-publish.yml
  src/bin/sage-update-version
  src/doc/common/static/custom-furo.css
  src/doc/common/static/custom-jupyter-sphinx.css
  src/doc/common/static/jupyter-sphinx-furo.js
  src/doc/common/templates-furo/sidebar/version-selector.html
  src/doc/en/website/versions.txt
  src/sage_docbuild/builders.py
  src/sage_docbuild/conf.py
Labels: s: positive review, c: documentation, p: blocker / 1, v: moderate

#38294 Filter out R warnings
  src/sage/doctest/parsing.py
Labels: s: positive review, p: blocker / 1, v: minimal

#38319 `build/pkgs/sage_numerical_backends_coin`, `sage_numerical_backends_cplex`, `sage_numerical_backends_gurobi`: Update to 10.4 (includes fix for Cython 3)
  build/pkgs/sage_numerical_backends_coin/checksums.ini
  build/pkgs/sage_numerical_backends_coin/package-version.txt
  build/pkgs/sage_numerical_backends_coin/spkg-install.in
  build/pkgs/sage_numerical_backends_cplex/checksums.ini
  build/pkgs/sage_numerical_backends_cplex/package-version.txt
  build/pkgs/sage_numerical_backends_cplex/spkg-install.in
  build/pkgs/sage_numerical_backends_gurobi/checksums.ini
  build/pkgs/sage_numerical_backends_gurobi/package-version.txt
  build/pkgs/sage_numerical_backends_gurobi/spkg-install.in
Labels: s: positive review, p: blocker / 1, c: packages: optional, v: minimal

#38378 CI: Create doc directory regardless of develop or PR
  .github/workflows/doc-build.yml
Labels: s: positive review, p: blocker / 1, c: scripts, v: minimal

#38349 little shoeshining for ncsym-dual
  src/sage/combinat/ncsym/dual.py
Labels: s: positive review, c: combinatorics, t: refactoring, v: small

#38352 Fix a minor typo
  src/sage/schemes/elliptic_curves/period_lattice.py
Labels: s: positive review, v: minimal

#38359 Homogenise `.log()` api across implementations of finite field elements
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
Labels: s: positive review, c: finite rings, v: small

#38366 Check input of composition
  src/sage/combinat/composition.py
Labels: s: positive review, c: combinatorics, v: minimal

#38371 Disjoint direct product decomposition of a permutation group
  src/doc/en/reference/references/index.rst
  src/sage/groups/perm_gps/permgroup.py
Labels: s: positive review, c: combinatorics, c: group theory, v: small, gsoc: 2024

#38372 Update ncsf.py documentation
  src/sage/combinat/ncsf_qsym/ncsf.py
Labels: s: positive review, c: combinatorics, v: minimal

#38375 moving ideal_monoid to the category of rings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra.py
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_ideal.py
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_morphism.py
  src/sage/categories/rings.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/ring.pxd
  src/sage/rings/ring.pyx
Labels: p: major / 3, s: positive review, c: algebra, c: categories, t: refactoring

#38377 pep8 cleanup in ode.pyx
  src/sage/calculus/ode.pyx
Labels: s: positive review, v: minimal

#38380 CI: Remove `centos-7`
  .devcontainer/portability-centos-7-devtoolset-gcc_11-minimal/devcontainer.json
  .devcontainer/portability-centos-7-devtoolset-gcc_11-minimal/portability-Dockerfile
  .devcontainer/portability-centos-7-devtoolset-gcc_11-standard/devcontainer.json
  .devcontainer/portability-centos-7-devtoolset-gcc_11-standard/portability-Dockerfile
  .github/workflows/docker.yml
  src/doc/en/developer/portability_platform_table.rst
  tox.ini
Labels: s: positive review, c: scripts, v: moderate

#37728 FareySymbol: set aspect_ratio to one in graph of fundamental domain.
  src/sage/modular/arithgroup/farey_symbol.pyx
Labels: s: positive review, c: modular forms, c: graphics, v: minimal

#38231 `build/pkgs/fpylll`: Update to 0.6.1
  build/pkgs/fpylll/checksums.ini
  build/pkgs/fpylll/package-version.txt
Labels: c: packages: standard, s: positive review, v: minimal

#38232 CI Build&Test: Show full logs, do not truncate
  .ci/write-dockerfile.sh
  build/bin/sage-logger
  tox.ini
Labels: s: positive review, c: build, c: scripts, v: minimal

#38256 `configure`: Check that the build directory is on a normal writable file system
  configure.ac
Labels: t: enhancement, s: positive review, c: build: configure, v: minimal

#38263 partial care for empty lines in pyx in rings ; activate E302 in pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/hom_finite_field_givaro.pyx
  src/sage/rings/fraction_field_element.pyx
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/polynomial/cyclotomic.pyx
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_compiled.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_gf2x.pyx
  src/sage/rings/polynomial/polynomial_number_field.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/weil/weil_polynomials.pyx
  src/sage/rings/power_series_mpoly.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/sum_of_squares.pyx
  src/sage/rings/tate_algebra_element.pyx
  src/sage/rings/tate_algebra_ideal.pyx
  src/tox.ini
Labels: s: positive review, v: minimal

#38278 Deprecate `is_Infinite`
  src/sage/geometry/fan_morphism.py
  src/sage/modular/arithgroup/arithgroup_element.pyx
  src/sage/rings/infinity.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review, t: refactoring, v: minimal

#38284 correct eclib's m4 file code to check version
  build/pkgs/eclib/spkg-configure.m4
Labels: s: positive review, c: build: configure, v: minimal

#38301 graph: modular decomposition of a single vertex should be a single tree node
  src/sage/graphs/graph.py
Labels: t: bug, s: positive review, c: graph theory, v: minimal

#38303 Fix DrinfeldModule is_isomorphic method absolutely' flag
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
Labels: s: positive review, c: documentation

#38305 `build/pkgs/surf`: Add to distros/
  build/pkgs/surf/distros/debian.txt
  build/pkgs/surf/distros/fedora.txt
Labels: s: positive review, c: distribution, v: minimal

#38308 `build/pkgs/libffi`: Update to 3.4.6
  build/pkgs/libffi/checksums.ini
  build/pkgs/libffi/package-version.txt
  build/pkgs/libffi/patches/libffi-3.2.1-disable-multi-os-directory.patch
Labels: c: packages: standard, s: positive review, v: small

#38322 Implement hypergeometric Euler factors at t=1
  src/sage/modular/hypergeometric_motive.py
Labels: s: positive review, c: number theory

#38326 Fix issue 37519
  src/sage/interfaces/qepcad.py
Labels: t: bug, s: positive review

#38333 Dimacs leaves junk files
  src/sage/sat/solvers/dimacs.py
Labels: s: positive review, v: minimal

#38334 Removing the automatic size labeler
  .ci/set_labels_by_changes.sh
  .github/workflows/pr-labeler.yml
Labels: s: positive review, c: scripts

#38343 fix mistake in category of fraction fields
  src/sage/rings/fraction_field.py
Labels: s: positive review, c: commutative algebra, c: categories, v: minimal

#38346 Updated `__repr__()` to `_repr_()` in ideals classes
  src/sage/rings/ideal.py
  src/sage/rings/number_field/number_field_ideal.py
Labels: c: user interface, s: positive review, t: refactoring

#38360 Reintroducing tight complex interval inverse
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/polynomial/binary_form_reduce.py
  src/sage/rings/qqbar.py
  src/sage/schemes/curves/zariski_vankampen.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/symbolic/expression_conversion_algebraic.py
Labels: s: positive review, v: large

#38344 Support ECM 7.0.6
  src/sage/interfaces/ecm.py
  src/sage/libs/libecm.pyx
Labels: s: positive review, v: minimal
