Repository sagemath/sage, pull requests merged in 2024-10, with the labels that each got.

#38339 Add sage.misc.latex.pdf to save the image of objects to pdf
  src/sage/misc/latex.py
  src/sage/misc/viewer.py
Labels: s: positive review, c: graphics, v: small

#38418 add method is_vertex_cut to (di)graphs
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory, v: moderate

#38461 work on Simon two-descent
  src/sage/schemes/elliptic_curves/BSD.py
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/gp_simon.py
Labels: s: positive review, c: elliptic curves

#38483 allow supplying a value of q for special_supersingular_curve()
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#38677 Added a method to compute the Tutte Symmetric function of a graph
  src/doc/en/reference/references/index.rst
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#38717 NotImplementedError when pow() called with modulus
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
Labels: p: major / 3, t: bug, s: positive review, c: algebra

#38719 Change wrapping of FLINT Z/nZ polynomial gcd failure
  src/sage/libs/flint/nmod_poly_linkage.pxi
  src/sage/rings/polynomial/polynomial_template.pxi
Labels: s: positive review, c: interfaces, c: commutative algebra

#38725 fix issue in `edge_cut`
  src/sage/graphs/generic_graph.py
Labels: t: bug, s: positive review, c: graph theory

#38729 provide monomial_coefficients for polynomials and allow single argument for MPolynomialRing_base.monomial
  src/sage/algebras/cluster_algebra.py
  src/sage/algebras/commutative_dga.py
  src/sage/algebras/free_algebra.py
  src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.pyx
  src/sage/algebras/fusion_rings/poly_tup_engine.pyx
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/algebras/letterplace/free_algebra_element_letterplace.pyx
  src/sage/algebras/quantum_clifford.py
  src/sage/algebras/rational_cherednik_algebra.py
  src/sage/algebras/splitting_algebra.py
  src/sage/algebras/weyl_algebra.py
  src/sage/combinat/ncsf_qsym/qsym.py
  src/sage/combinat/root_system/root_lattice_realization_algebras.py
  src/sage/combinat/sf/monomial.py
  src/sage/combinat/sf/sfa.py
  src/sage/combinat/triangles_FHM.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/geometry/polyhedron/generating_function.py
  src/sage/groups/braid.py
  src/sage/libs/singular/singular.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/polynomial/flatten.py
  src/sage/rings/polynomial/laurent_polynomial.pxd
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/laurent_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/omega.py
  src/sage/rings/polynomial/ore_polynomial_element.pxd
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/padics/polynomial_padic_capped_relative_dense.py
  src/sage/rings/polynomial/plural.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_element_generic.py
  src/sage/rings/polynomial/polynomial_ring_homomorphism.pyx
  src/sage/rings/power_series_mpoly.pyx
  src/sage/rings/power_series_pari.pyx
  src/sage/rings/power_series_poly.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/qqbar.py
  src/sage/rings/semirings/tropical_mpolynomial.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/semirings/tropical_variety.py
  src/sage/rings/tate_algebra_element.pyx
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/plane_conics/con_rational_function_field.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
  src/sage/schemes/toric/ideal.py
  src/sage/schemes/toric/weierstrass_covering.py
  src/sage/structure/parent.pyx
  src/sage/symbolic/expression.pyx
Labels: t: enhancement, s: positive review, c: commutative algebra

#38730 Expose Coxeter and dual Coxeter numbers in RootSystem class
  src/sage/combinat/root_system/root_system.py
Labels: t: enhancement, s: positive review, c: combinatorics

#38731 Docbuild: Fix conditionalization of documentation on features
  src/sage_docbuild/builders.py
Labels: t: bug, s: positive review, c: build, c: documentation

#38732 `sage.rings.function_field`: Update `# needs`
  src/sage/rings/function_field/element.pyx
Labels: s: positive review, t: refactoring

#38733 `sage.categories`: Update `# needs`
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/semigroups.py
  src/sage/categories/triangular_kac_moody_algebras.py
Labels: s: positive review, t: refactoring

#38738 activate linter check of E275 and clean one file
  src/sage/knots/free_knotinfo_monoid.py
  src/sage/knots/link.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#38741 move power series to Parent
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/power_series_ring.py
Labels: s: positive review, c: commutative algebra, t: refactoring

#38743 various pep8 fixes in modular folder
  src/sage/modular/abvar/constructor.py
  src/sage/modular/abvar/cuspidal_subgroup.py
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/abvar/torsion_subgroup.py
  src/sage/modular/arithgroup/arithgroup_perm.py
  src/sage/modular/arithgroup/congroup_gamma.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/arithgroup/congroup_gamma1.py
  src/sage/modular/arithgroup/congroup_generic.py
  src/sage/modular/arithgroup/congroup_sl2z.py
  src/sage/modular/drinfeld_modform/element.py
  src/sage/modular/drinfeld_modform/ring.py
  src/sage/modular/hypergeometric_motive.py
  src/sage/modular/local_comp/local_comp.py
  src/sage/modular/local_comp/smoothchar.py
  src/sage/modular/local_comp/type_space.py
  src/sage/modular/modform/ambient_R.py
  src/sage/modular/modform/ambient_eps.py
  src/sage/modular/modform/constructor.py
  src/sage/modular/modform/cuspidal_submodule.py
  src/sage/modular/modform/eis_series.py
  src/sage/modular/modform/eisenstein_submodule.py
  src/sage/modular/modform/half_integral.py
  src/sage/modular/modform/hecke_operator_on_qexp.py
  src/sage/modular/modform/j_invariant.py
  src/sage/modular/modform/numerical.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform/space.py
  src/sage/modular/modform/theta.py
  src/sage/modular/modform/vm_basis.py
  src/sage/modular/modform/weight1.py
  src/sage/modular/modform_hecketriangle/constructor.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/modular/overconvergent/weightspace.py
  src/sage/modular/pollack_stevens/modsym.py
  src/sage/modular/pollack_stevens/sigma0.py
  src/sage/modular/quasimodform/element.py
Labels: s: positive review

#38747 Fix build.yml broken for releases
  .ci/write-dockerfile.sh
  .github/workflows/build.yml
Labels: s: positive review, p: blocker / 1, p: CI Fix

#38750 Corrects some inner products in root systems
  src/sage/combinat/root_system/ambient_space.py
  src/sage/combinat/root_system/root_space.py
Labels: t: bug, s: positive review, c: combinatorics

#38751 `sage.sets`: Modularization fixes (imports)
  src/sage/sets/disjoint_set.pyx
  src/sage/sets/image_set.py
Labels: s: positive review, t: refactoring

#38752 build/pkgs/sagetex/dependencies: add $(PYTHON_TOOLCHAIN)
  build/pkgs/sagetex/dependencies
Labels: t: bug, c: packages: standard, s: positive review

#38755 Added two missing difference sets, updated URLs
  src/sage/combinat/designs/covering_design.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/design_catalog.py
  src/sage/combinat/designs/difference_family.py
Labels: s: positive review, c: combinatorics, c: combinatorial designs

#38756 src/sage/symbolic/integration: make libgiac integration optional
  src/sage/symbolic/integration/external.py
  src/sage/symbolic/integration/integral.py
Labels: s: positive review, c: symbolics

#38757 fix the output of method `acyclic_orientations`
  src/sage/graphs/orientations.py
Labels: s: positive review, c: graph theory

#38763 use StructureDescription() in gap/element.pyx tests
  src/sage/libs/gap/element.pyx
Labels: s: positive review, c: group theory

#38765 Fix time limitation in magma_free docstring
  src/sage/interfaces/magma_free.py
Labels: s: positive review, c: documentation

#38772 Do not allow external Pari 2.17 or later
  build/pkgs/pari/spkg-configure.m4
Labels: s: positive review, p: critical / 2, c: build: configure

#38774 rpy2 (standard) cannot depend on r (optional)
  build/pkgs/rpy2/dependencies
Labels: s: positive review, p: blocker / 1

#38775 Set explicit install name path on macOS suitesparse
  build/pkgs/suitesparse/spkg-install.in
Labels: c: packages: standard, s: positive review

#38776 Fix test failures due to global mpmath state
  src/sage/functions/orthogonal_polys.py
  src/sage/libs/mpmath/ext_main.pyx
Labels: c: packages: standard, s: positive review

#38777 Check the system R in SPKG rpy2
  build/pkgs/r/spkg-configure.m4
  build/pkgs/r_jupyter/dependencies
  build/pkgs/rpy2/dependencies
  build/pkgs/rpy2/spkg-configure.m4
Labels: s: positive review, p: blocker / 1, p: CI Fix

#38786 slightly enhanced convolution of piecewise functions
  src/sage/functions/piecewise.py
Labels: t: enhancement, s: positive review, c: symbolics

#38788 Ruff e713
  .github/sync_labels.py
  src/sage/coding/gabidulin_code.py
  src/sage/dynamics/arithmetic_dynamics/endPN_minimal_model.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/functions/bessel.py
  src/sage/games/hexad.py
  src/sage/geometry/hyperplane_arrangement/plot.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/generators/classical_geometries.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_latex.py
  src/sage/graphs/orientations.py
  src/sage/interfaces/maxima_lib.py
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/manifolds/point.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/repl/rich_output/display_manager.py
  src/sage/rings/function_field/order_basis.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/function_field/order_rational.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/order.py
  src/sage/rings/pari_ring.py
  src/sage/rings/polynomial/pbori/ll.py
  src/sage/rings/valuation/augmented_valuation.py
  src/sage/rings/valuation/inductive_valuation.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/curves/zariski_vankampen.py
  src/sage/symbolic/callable.py
  src/sage/topology/simplicial_complex.py
  src/tox.ini
Labels: s: positive review

#38790 avoid some type comparisons in combinat
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/combinat/cluster_algebra_quiver/quiver_mutation_type.py
  src/sage/combinat/core.py
  src/sage/combinat/root_system/integrable_representations.py
  src/sage/combinat/shard_order.py
Labels: s: positive review, c: combinatorics

#38793 fix docstring, fix whitespace around = and ,
  src/sage/modular/arithgroup/farey_symbol.pyx
Labels: s: positive review, c: documentation

#36226 Use CPU time for --warn-long
  pkgs/sagemath-repl/MANIFEST.in
  pkgs/sagemath-repl/pyproject.toml.m4
  src/bin/sage
  src/doc/en/developer/doctesting.rst
  src/sage/doctest/__main__.py
  src/sage/doctest/control.py
  src/sage/doctest/forker.py
  src/sage/doctest/reporting.py
  src/sage/doctest/test.py
  src/sage/doctest/util.py
  src/sage/interfaces/cleaner.py
  src/sage/interfaces/quit.py
Labels: s: positive review, c: doctest framework

#38259 Fixed and improvements in `is_LLL_reduced` and `approximate_closest_vector`
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/modules/free_module_integer.py
Labels: s: positive review, c: linear algebra, c: geometry, v: small

#38487 convenience methods for field embeddings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/matrix/matrix2.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/rational_field.py
  src/sage/rings/ring.pyx
Labels: t: enhancement, p: minor / 4, s: positive review, c: algebra

#38680 Improve counting of local solutions for QuadraticForm at p=2
  src/sage/quadratic_forms/count_local_2.pyx
  src/sage/quadratic_forms/quadratic_form__local_density_congruence.py
Labels: p: major / 3, t: enhancement, s: positive review, c: quadratic forms

#38734 GH Actions: Build sagemath-tdlib wheel
  .github/workflows/dist.yml
Labels: s: positive review, c: distribution

#38770 Add "needs" tags for giac and libgiac
  src/doc/en/prep/Calculus.rst
  src/sage/calculus/calculus.py
  src/sage/calculus/functional.py
  src/sage/functions/exp_integral.py
  src/sage/functions/generalized.py
  src/sage/functions/other.py
  src/sage/functions/piecewise.py
  src/sage/interfaces/giac.py
  src/sage/interfaces/interface.py
  src/sage/libs/giac/__init__.py
  src/sage/libs/giac/giac.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/integration/integral.py
  src/sage/symbolic/relation.py
Labels: s: positive review

#38797 make sure .division_points() returns the correct result for m=-1
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: t: bug, p: minor / 4, s: positive review, c: elliptic curves

#38798 adding method tikz to class Graph
  src/sage/graphs/generic_graph.py
Labels: s: positive review

#38804 GAP 4.13.1
  .ci/write-dockerfile.sh
  build/pkgs/gap/SPKG.rst
  build/pkgs/gap/checksums.ini
  build/pkgs/gap/distros/conda.txt
  build/pkgs/gap/distros/gentoo.txt
  build/pkgs/gap/package-version.txt
  build/pkgs/gap/patches/0001-Makefile.rules-Darwin-Remove-use-of-single_module-ob.patch
  build/pkgs/gap/patches/gap-4.13.1-hash-fixes.patch
  build/pkgs/gap/spkg-check.in
  build/pkgs/gap/spkg-configure.m4
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/categories/simplicial_sets.py
  src/sage/combinat/matrices/latin.py
  src/sage/features/gap.py
  src/sage/groups/cubic_braid.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/libgap.pyx
  src/sage/libs/gap/util.pyx
  tox.ini
Labels: s: positive review

#38805 use specialized 2-dimensional .log() method in .matrix_on_subgroup()
  src/sage/schemes/elliptic_curves/hom.py
Labels: p: major / 3, s: positive review, c: elliptic curves, t: performance

#38808 faster comparison of elliptic-curve morphisms
  src/sage/schemes/elliptic_curves/hom.py
Labels: p: minor / 4, s: positive review, c: elliptic curves, t: performance

#38812 Make codecov/patch informational (not fail)
  .codecov.yml
Labels: s: positive review

#38819 fixing some typos
  src/sage/algebras/fusion_rings/shm_managers.pyx
  src/sage/algebras/lie_algebras/representation.py
  src/sage/all__sagemath_repl.py
  src/sage/combinat/diagram.py
  src/sage/combinat/matrices/hadamard_matrix.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/specht_module.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/functions/piecewise.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_list_data_structure.pxd
  src/sage/graphs/edge_connectivity.pyx
  src/sage/graphs/generators/basic.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/graph.py
  src/sage/knots/free_knotinfo_monoid.py
  src/sage/knots/link.py
  src/sage/libs/ntl/ntl_mat_GF2.pyx
  src/sage/manifolds/continuous_map.py
  src/sage/matrix/matrix2.pyx
  src/sage/matroids/database_matroids.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/with_basis/invariant.py
  src/sage/plot/plot3d/base.pyx
  src/sage/rings/asymptotic/term_monoid.py
  src/sage/rings/complex_interval.pyx
  src/sage/rings/continued_fraction.py
  src/sage/rings/number_field/selmer_group.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/universal_cyclotomic_field.py
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/curves/zariski_vankampen.py
  src/sage/schemes/elliptic_curves/ell_rational_field.py
  src/sage/schemes/elliptic_curves/saturation.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
  src/sage/sets/real_set.py
  src/sage/stats/distributions/discrete_gaussian_lattice.py
  src/sage/structure/dynamic_class.py
  src/sage/symbolic/ginac/matrix.cpp
Labels: s: positive review, t: refactoring

#38822 Upgrade database_knotinfo to version 2024.10.1
  src/sage/databases/knotinfo_db.py
  src/sage/knots/knotinfo.py
Labels: s: positive review, c: interfaces, c: algebraic topology

#38825 Fix two tests that fail on a heavily-loaded machine
  src/sage/parallel/decorate.py
  src/sage/parallel/map_reduce.py
Labels: s: positive review

#38826 src/sage/env.py: canonicalize paths in a test
  src/sage/env.py
Labels: s: positive review

#38833 Respect sparse=True in vector constructor when passed ndarray
  src/sage/modules/free_module_element.pyx
Labels: s: positive review

#38837 Fix bug in covering map of simplicial set with degenerate faces.
  src/sage/categories/simplicial_sets.py
Labels: t: bug, s: positive review, c: algebraic topology

#38841 Fix `transformation` parameter for LLL on matrices over QQ
  src/sage/matrix/matrix_rational_dense.pyx
Labels: p: major / 3, t: bug, s: positive review, c: linear algebra

#38845 Fix docstring format for `EllipticCurve_with_prime_order`
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: t: bug, s: positive review, c: documentation, p: trivial / 5, c: elliptic curves

#38851 src/sage/graphs/generic_graph.py: work around doctest hang
  src/sage/graphs/generic_graph.py
Labels: s: positive review, t: tests, c: graph theory, c: linear programming
