Repository sagemath/sage, pull requests merged in 2025-05, with the labels that each got.

#40001 Remove giac as dependency, and add sagemath_giac as optional dependency
  pyproject.toml
Labels: s: positive review

#40002 fix some typos in various places
  src/sage/combinat/colored_permutations.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/rsk.py
  src/sage/combinat/t_sequences.py
  src/sage/combinat/triangles_FHM.py
  src/sage/crypto/block_cipher/des.py
  src/sage/crypto/block_cipher/present.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/graphs/graph_generators.py
  src/sage/graphs/line_graph.pyx
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
  src/sage/modular/arithgroup/arithgroup_perm.py
  src/sage/modular/drinfeld_modform/ring.py
  src/sage/modules/with_basis/invariant.py
  src/sage/quivers/ar_quiver.py
  src/sage/rings/continued_fraction.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/polynomial/pbori/randompoly.py
  src/sage/rings/rational_field.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/semirings/tropical_variety.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
Labels: s: positive review

#40006 some typos
  src/sage/graphs/generators/families.py
  src/sage/knots/knotinfo.py
  src/sage/rings/integer.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/schemes/curves/plane_curve_arrangement.py
Labels: s: positive review

#40007 Fixed issue in CRT_vectors where moduli are not allowed to be coprime.
  src/sage/arith/misc.py
Labels: s: positive review

#40010 using doi when possible
  src/doc/en/reference/references/index.rst
  src/sage/graphs/genus.pyx
Labels: s: positive review

#40014 set correct default algorithm for the diameter of (un)weighted graphs
  src/sage/graphs/graph.py
Labels: t: bug, s: positive review, c: graph theory

#40022 clean error messages in algebras
  src/sage/algebras/finite_gca.py
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/algebras/letterplace/letterplace_ideal.pyx
  src/sage/algebras/lie_algebras/examples.py
  src/sage/algebras/lie_conformal_algebras/free_fermions_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/weyl_lie_conformal_algebra.py
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra_bases.py
  src/sage/algebras/steenrod/steenrod_algebra_misc.py
Labels: s: positive review

#40024 implement naive default inverse methods for finite monoids
  src/sage/categories/finite_monoids.py
  src/sage/categories/semigroups.py
Labels: s: positive review, c: categories

#40025 Follow the PR #39990, revert "src/doc/zh/**/conf.py: Fix handling of tags"
  src/doc/zh/a_tour_of_sage/conf.py
  src/doc/zh/tutorial/conf.py
  src/doc/zh/tutorial/interfaces.rst
  src/doc/zh/tutorial/latex.rst
  src/doc/zh/tutorial/programming.rst
  src/doc/zh/tutorial/tour_algebra.rst
  src/doc/zh/tutorial/tour_polynomial.rst
Labels: s: positive review

#40026 just a few pep8 details
  src/sage/groups/matrix_gps/binary_dihedral.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/schemes/generic/algebraic_scheme.py
  src/sage/schemes/generic/divisor.py
  src/sage/schemes/plane_conics/con_field.py
Labels: s: positive review

#40031 fix E228 in pyx in matrix
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_generic_sparse.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_integer_sparse.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
  src/sage/matrix/matrix_window.pyx
Labels: s: positive review

#40032 various small fixes, some after ruff
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/combinat/crystals/fast_crystals.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/words/finite_word.py
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/geometry/hyperbolic_space/hyperbolic_model.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_decompositions/graph_products.pyx
  src/sage/knots/link.py
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/rings/invariants/reconstruction.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/rings/polynomial/msolve.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/plane_conics/con_rational_field.py
  src/sage/schemes/product_projective/homset.py
  src/sage/symbolic/expression_conversions.py
  src/sage/topology/delta_complex.py
  src/sage/topology/simplicial_complex_examples.py
Labels: s: positive review

#40036 Fix Generalized Petersen graph name and update others to f-string syntax
  src/sage/graphs/generators/families.py
Labels: s: positive review, c: graph theory

#40043 Clean mut type
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
Labels: s: positive review, c: combinatorics

#40044 Remove Pipfiles
  Pipfile
  src/Pipfile
Labels: s: positive review, c: build

#40046 Precision issue in the normalization of a Tate series
  src/sage/rings/tate_algebra_element.pyx
Labels: t: bug, s: positive review, c: padics

#40048 Fix primes_of_bounded_norm for noninteger entries
  src/sage/rings/number_field/number_field.py
Labels: s: positive review, c: number theory

#40049 Replace dead HTTP links in docs
  src/doc/de/thematische_anleitungen/sage_gymnasium.rst
  src/doc/de/tutorial/programming.rst
  src/doc/en/constructions/algebraic_geometry.rst
  src/doc/en/developer/coding_basics.rst
  src/doc/en/faq/faq-contribute.rst
  src/doc/en/faq/faq-general.rst
  src/doc/en/faq/faq-usage.rst
  src/doc/en/prep/Advanced-2DPlotting.rst
  src/doc/en/prep/Quickstarts/NumAnalysis.rst
  src/doc/en/reference/references/index.rst
  src/doc/en/reference/repl/environ.rst
  src/doc/en/reference/sat/index.rst
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/half_integral.rst
  src/doc/en/thematic_tutorials/functional_programming.rst
  src/doc/en/thematic_tutorials/numerical_sage/comparison_to_cython.rst
  src/doc/en/thematic_tutorials/numerical_sage/ctypes.rst
  src/doc/en/thematic_tutorials/numerical_sage/f2py.rst
  src/doc/en/thematic_tutorials/numerical_sage/f2py_examples.rst
  src/doc/en/thematic_tutorials/numerical_sage/numerical_tools.rst
  src/doc/en/thematic_tutorials/numerical_sage/scipy.rst
  src/doc/en/thematic_tutorials/sandpile.rst
  src/doc/en/thematic_tutorials/tutorial-implementing-algebraic-structures.rst
  src/doc/en/thematic_tutorials/tutorial-objects-and-classes.rst
  src/doc/en/thematic_tutorials/tutorial-programming-python.rst
  src/doc/en/tutorial/programming.rst
  src/doc/fr/tutorial/programming.rst
  src/doc/it/faq/faq-contribute.rst
  src/doc/it/faq/faq-general.rst
  src/doc/it/faq/faq-usage.rst
  src/doc/ja/tutorial/bibliography.rst
  src/doc/ja/tutorial/programming.rst
  src/doc/ru/tutorial/programming.rst
  src/sage/calculus/desolvers.py
  src/sage/graphs/tutte_polynomial.py
  src/sage/modular/modform/half_integral.py
  src/sage/plot/plot.py
  src/sage/sat/solvers/satsolver.pyx
Labels: s: positive review

#40059 add extra time tolerance to a doctest in `src/sage/doctest/util.py`
  src/sage/doctest/util.py
Labels: s: positive review

#40061 avoid using bytes_to_str in gperftools
  src/sage/misc/gperftools.py
Labels: s: positive review

#38493 compute endomorphism orders for elliptic curves over finite fields (rank-2 case)
  src/sage/schemes/elliptic_curves/ell_finite_field.py
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#39355 p-typical Witt vectors
  src/doc/en/reference/padics/index.rst
  src/sage/rings/padics/all.py
  src/sage/rings/padics/meson.build
  src/sage/rings/padics/witt_vector.py
  src/sage/rings/padics/witt_vector_ring.py
Labels: t: enhancement, s: positive review, c: padics, sd128

#39478 use decomposition into biconnected components in Gomory-Hu tree
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#39520 move is_field from Ring to Rings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/algebras/cellular_basis.py
  src/sage/categories/examples/magmas.py
  src/sage/categories/fields.py
  src/sage/categories/magmas.py
  src/sage/categories/monoids.py
  src/sage/categories/rings.py
  src/sage/modules/with_basis/cell_module.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/ring.pyx
  src/sage/structure/parent.pyx
  src/sage/tests/books/computational-mathematics-with-sagemath/domaines_doctest.py
Labels: s: positive review, t: refactoring, sd128

#39633 added as_tuples as an optional argument to Combinations to facilitate hashing in Combination objects
  src/sage/combinat/combination.py
Labels: s: positive review, c: combinatorics

#39805 Changed calculate_voronoi_cell to use the orthogonal complement as it's artificial points.
  src/sage/modules/diamond_cutting.py
Labels: s: positive review

#39812 Adds limit(expr, v, a) syntax
  src/sage/calculus/calculus.py
Labels: s: positive review, c: calculus

#39837 Richcmp for pseudomorphisms
  src/sage/modules/free_module_pseudomorphism.py
Labels: t: bug, s: positive review

#39923 add parameter immutable to GraphQuery `src/sage/graphs/graph_database.py`
  src/sage/graphs/graph_database.py
Labels: s: positive review, c: graph theory

#39924 add parameter immutable to methods in `src/sage/graphs/graph_list.py`
  src/sage/graphs/generators/basic.py
  src/sage/graphs/graph_decompositions/graph_products.pyx
  src/sage/graphs/graph_list.py
Labels: s: positive review, c: graph theory

#39929 Add and update some conda.txt files
  build/pkgs/bliss/distros/conda.txt
  build/pkgs/boost_cropped/distros/conda.txt
  build/pkgs/calver/distros/conda.txt
  build/pkgs/cmake/distros/conda.txt
  build/pkgs/libgd/distros/conda.txt
  build/pkgs/meson/distros/conda.txt
  build/pkgs/meson_python/distros/conda.txt
  build/pkgs/patchelf/distros/conda.txt
  build/pkgs/pynormaliz/version_requirements.txt
  build/pkgs/pyproject_metadata/distros/conda.txt
  build/pkgs/pytest_mock/distros/conda.txt
  build/pkgs/pythran/distros/conda.txt
  build/pkgs/scipy/distros/conda.txt
  build/pkgs/sphinx_inline_tabs/distros/conda.txt
  build/pkgs/tzdata/distros/conda.txt
Labels: s: positive review

#39943 remove patch spkg
  README.md
  build/bin/sage-apply-patches
  build/pkgs/_prereq/distros/alpine.txt
  build/pkgs/_prereq/distros/arch.txt
  build/pkgs/_prereq/distros/conda.txt
  build/pkgs/_prereq/distros/debian.txt
  build/pkgs/_prereq/distros/fedora.txt
  build/pkgs/_prereq/distros/freebsd.txt
  build/pkgs/_prereq/distros/gentoo.txt
  build/pkgs/_prereq/distros/nix.txt
  build/pkgs/_prereq/distros/opensuse.txt
  build/pkgs/_prereq/distros/slackware.txt
  build/pkgs/_prereq/distros/void.txt
  build/pkgs/patch/SPKG.rst
  build/pkgs/patch/checksums.ini
  build/pkgs/patch/dependencies
  build/pkgs/patch/distros/alpine.txt
  build/pkgs/patch/distros/arch.txt
  build/pkgs/patch/distros/conda.txt
  build/pkgs/patch/distros/debian.txt
  build/pkgs/patch/distros/fedora.txt
  build/pkgs/patch/distros/freebsd.txt
  build/pkgs/patch/distros/homebrew.txt
  build/pkgs/patch/distros/macports.txt
  build/pkgs/patch/distros/opensuse.txt
  build/pkgs/patch/distros/repology.txt
  build/pkgs/patch/distros/slackware.txt
  build/pkgs/patch/distros/void.txt
  build/pkgs/patch/package-version.txt
  build/pkgs/patch/patch.exe.manifest
  build/pkgs/patch/spkg-configure.m4
  build/pkgs/patch/spkg-install.in
  build/pkgs/patch/type
  build/pkgs/pkgconf/dependencies
  src/doc/en/developer/portability_testing.rst
Labels: c: packages: standard, s: positive review, p: critical / 2, p: blocker / 1

#39948 fix enumeration of implicitly finite sets of partitions
  src/sage/combinat/integer_lists/base.pyx
  src/sage/combinat/partition.py
Labels: s: positive review, c: combinatorics

#39977 allow gcc-15 from the system
  build/pkgs/ecl/spkg-install.in
  build/pkgs/gcc/spkg-configure.m4
  build/pkgs/gfortran/spkg-configure.m4
Labels: s: positive review

#39978 Added a bandwidth feature
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#39985 linbox patches for gcc-15 and Apple clang-17
  build/pkgs/linbox/patches/41.patch
  build/pkgs/linbox/patches/42.patch
  build/pkgs/linbox/patches/43.patch
Labels: s: positive review

#39986 fix: log as method gives symbolic output for non positive base
  src/sage/rings/integer.pyx
Labels: s: positive review

#39988 Adding an implementation of the Abreu-Nigro symmetric functions
  src/doc/en/reference/combinat/module_list.rst
  src/doc/en/reference/references/index.rst
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/sf/abreu_nigro.py
  src/sage/combinat/sf/all.py
  src/sage/combinat/sf/sf.py
  src/sage/combinat/sf/sfa.py
Labels: t: enhancement, s: positive review, c: combinatorics

#39990 Remove ability to conditionalize parts of the documentation
  src/doc/ca/intro/conf.py
  src/doc/de/a_tour_of_sage/conf.py
  src/doc/de/thematische_anleitungen/conf.py
  src/doc/de/tutorial/conf.py
  src/doc/el/a_tour_of_sage/conf.py
  src/doc/en/a_tour_of_sage/conf.py
  src/doc/en/constructions/conf.py
  src/doc/en/developer/conf.py
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/en/developer/sage_manuals.rst
  src/doc/en/faq/conf.py
  src/doc/en/installation/conf.py
  src/doc/en/prep/conf.py
  src/doc/en/reference/conf.py
  src/doc/en/reference/conf_sub.py
  src/doc/en/reference/polynomial_rings/index.rst
  src/doc/en/thematic_tutorials/conf.py
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/conf.py
  src/doc/en/thematic_tutorials/numerical_sage/conf.py
  src/doc/en/tutorial/conf.py
  src/doc/en/tutorial/latex.rst
  src/doc/en/website/conf.py
  src/doc/es/a_tour_of_sage/conf.py
  src/doc/es/tutorial/conf.py
  src/doc/fr/a_tour_of_sage/conf.py
  src/doc/fr/tutorial/conf.py
  src/doc/hu/a_tour_of_sage/conf.py
  src/doc/it/a_tour_of_sage/conf.py
  src/doc/it/faq/conf.py
  src/doc/it/tutorial/conf.py
  src/doc/ja/a_tour_of_sage/conf.py
  src/doc/ja/tutorial/conf.py
  src/doc/pt/a_tour_of_sage/conf.py
  src/doc/pt/tutorial/conf.py
  src/doc/ru/tutorial/conf.py
  src/doc/tr/a_tour_of_sage/conf.py
  src/sage_docbuild/builders.py
  src/sage_docbuild/conf.py
Labels: s: positive review

#39996 Always use python to run the pexpect interface
  src/sage/interfaces/expect.py
  src/sage/interfaces/sage0.py
Labels: s: positive review

#39997 Run python3 directly instead of `sage -python` in sage/tests/startup.py
  src/sage/tests/startup.py
Labels: s: positive review

#39999 handle permutations in S_n with n > 2^16
  src/sage/groups/perm_gps/permgroup_element.pyx
Labels: s: positive review

#40027 fix pep E228 in all cython files in rings
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/factorint.pyx
  src/sage/rings/finite_rings/element_ntl_gf2e.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/finite_rings/residue_field.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/padics/pow_computer_relative.pyx
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_compiled.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_gf2x.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/polynomial/polynomial_zz_pex.pyx
  src/sage/rings/sum_of_squares.pyx
Labels: s: positive review

#38848 Adding a tikz method to FinitePoset class
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#39010 Don't import cysignals.alarm on Windows
  src/sage/all.py
  src/sage/all__sagemath_objects.py
  src/sage/matrix/benchmark.py
  src/sage/parallel/use_fork.py
  src/sage/tests/benchmark.py
Labels: s: positive review

#39262 Add script for checking for old deprecations
  pyproject.toml
  tools/README.md
  tools/check_deprecations.py
  tools/update-meson.py
Labels: s: positive review, c: scripts

#39532 move finite field methods
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/finite_fields.py
  src/sage/categories/rings.py
  src/sage/rings/finite_rings/finite_field_base.pyx
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring, sd128

#39548 Create PyPI source distribution of meson-based setup
  .github/workflows/dist.yml
Labels: s: positive review

#39583 Handle various extension degrees in pAdicGenericElement initialisation
  src/sage/rings/padics/padic_template_element.pxi
Labels: s: positive review, c: padics

#39595 Add fricas-homebrew
  build/pkgs/fricas/distros/homebrew.txt
Labels: s: positive review

#39721 Implement theYokonuma-Hecke algebras for other Weyl groups
  src/doc/en/reference/references/index.rst
  src/sage/algebras/yokonuma_hecke_algebra.py
Labels: s: positive review, c: algebra

#39763 Updated methods concerning addition of edges in a matching covered graph
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory

#39900 cli: remove default from -n argument
  src/sage/cli/notebook_cmd.py
Labels: s: positive review

#39901 Add --quiet and --simple-prompt command line arguments
  src/sage/cli/__init__.py
  src/sage/cli/interactive_shell_cmd.py
  src/sage/cli/options.py
Labels: s: positive review

#39953 replacing many vector*matrix with matrix*matrix
  src/sage/modules/free_quadratic_module_integer_symmetric.py
Labels: s: positive review, t: performance

#40008 more typos fixed
  src/bin/sage
  src/sage/combinat/key_polynomial.py
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/functions/orthogonal_polys.py
  src/sage/geometry/polyhedron/face.py
  src/sage/geometry/polyhedron/library.py
  src/sage/interfaces/gap.py
  src/sage/interfaces/giac.py
  src/sage/manifolds/differentiable/metric.py
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/ore_function_element.py
  src/sage/symbolic/ginac/matrix.cpp
Labels: s: positive review

#40021 more typing annotations in combinat/posets
  src/sage/combinat/posets/elements.py
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/incidence_algebras.py
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/linear_extensions.py
  src/sage/combinat/posets/moebius_algebra.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review

#40057 get_embedding(): remove vertices that do not exist
  src/sage/graphs/generic_graph.py
  src/sage/topology/simplicial_complex_examples.py
Labels: s: positive review, c: graph theory

#40064 cleaning the groebner_fan file
  src/sage/rings/polynomial/groebner_fan.py
Labels: s: positive review, c: commutative algebra

#40068 fixes for reading .pc planar code files
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory

#40072 avoid using bytes_to_str in matrix/ (pyx files)
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_rational_dense.pyx
Labels: s: positive review

#40077 using _an_element_ in algebras
  src/sage/algebras/askey_wilson.py
  src/sage/algebras/rational_cherednik_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
Labels: s: positive review, c: algebra

#40078 using _an_element_ in groups
  src/sage/groups/additive_abelian/qmodnz.py
  src/sage/groups/artin.py
  src/sage/groups/braid.py
  src/sage/groups/group_exp.py
Labels: s: positive review, c: group theory

#40079 typing annotation in Dirichlet characters
  src/sage/modular/dirichlet.py
Labels: s: positive review, c: number theory

#40083 using _an_element_ in modular/
  src/sage/modular/multiple_zeta.py
  src/sage/modular/multiple_zeta_F_algebra.py
Labels: s: positive review, c: modular forms

#40084 more fixes for E228 in pyx files
  src/sage/coding/binary_code.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pxd
  src/sage/stats/distributions/discrete_gaussian_integer.pyx
  src/sage/stats/hmm/chmm.pyx
  src/sage/stats/hmm/hmm.pyx
Labels: s: positive review

#40085 fix the pycodestyle-minimal linter
  src/sage/arith/misc.py
  src/sage/calculus/calculus.py
  src/sage/combinat/posets/poset_examples.py
Labels: s: positive review, p: CI Fix

#40096 use _an_element_ and type annotations in ore_module
  src/sage/modules/ore_module.py
Labels: s: positive review

#40097 using _an_element_ in combinat
  src/sage/combinat/chas/wqsym.py
  src/sage/combinat/composition_tableau.py
  src/sage/combinat/debruijn_sequence.pyx
  src/sage/combinat/fqsym.py
  src/sage/combinat/free_dendriform_algebra.py
  src/sage/combinat/free_prelie_algebra.py
  src/sage/combinat/grossman_larson_algebras.py
  src/sage/combinat/hillman_grassl.py
  src/sage/combinat/integer_vectors_mod_permgroup.py
  src/sage/combinat/k_tableau.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/root_system/fundamental_group.py
  src/sage/combinat/sf/k_dual.py
  src/sage/combinat/sf/new_kschur.py
  src/sage/combinat/subset.py
  src/sage/combinat/tableau.py
  src/sage/combinat/tableau_residues.py
Labels: s: positive review

#40100 cypari 2.2.2
  build/pkgs/cypari/checksums.ini
  build/pkgs/cypari/package-version.txt
Labels: c: packages: standard, s: positive review

#40102 fix conversion of expressions like SR(oo)
  src/sage/symbolic/expression_conversions.py
Labels: s: positive review, c: interfaces: optional

#40103 some cleaning in newton_polygon
  src/sage/geometry/newton_polygon.py
Labels: s: positive review

#40104 fix some typos and other details
  src/sage/combinat/SJT.py
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/modules/diamond_cutting.py
Labels: s: positive review

#40109 Fix docstring for enumerate_totallyreal_fields_rel
  src/sage/rings/number_field/totallyreal_rel.py
Labels: s: positive review, c: documentation

#40110 Fix "NotImplementedError: an immutable graph does not change name"
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory
