Repository sagemath/sage, pull requests merged in 2025-07, with the labels that each got.

#39831 Matrix singular values
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#39931 fix issue #39930 in `src/sage/graphs/matchpoly.pyx`
  src/sage/graphs/matchpoly.pyx
Labels: t: bug, s: positive review, c: graph theory

#39932 add parameter immutable to method `is_planar`
  src/sage/graphs/generic_graph.py
  src/sage/graphs/planarity.pyx
Labels: s: positive review, c: graph theory

#39944 Include optional packages in `pyproject.toml` and conda environments
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.11-win.yml
  environment-3.12-linux-aarch64.yml
  environment-3.12-linux.yml
  environment-3.12-macos-x86_64.yml
  environment-3.12-macos.yml
  environment-3.12-win.yml
  environment-3.13-win.yml
  pyproject.toml
  tools/update-conda.py
Labels: s: positive review

#39973 Migrate CI build-doc to Meson
  .github/workflows/doc-build.yml
  environment-3.11-linux.yml
  meson.build
  pyproject.toml
  src/build-docs.py
  src/doc/Makefile
  src/doc/bootstrap
  src/doc/en/installation/meson.rst
  src/doc/en/reference/conf_sub.py
  src/doc/en/reference/repl/meson.build
  src/doc/meson.build
  src/meson.build
  src/sage/repl/ipython_kernel/all_jupyter.py
  src/sage_docbuild/__main__.py
  src/sage_docbuild/build_options.py
  src/sage_docbuild/builders.py
  src/sage_docbuild/conf.py
  uv.lock
Labels: s: positive review, p: blocker / 1

#40098 remove deprecation in `connected_components`
  src/sage/graphs/connectivity.pyx
Labels: s: positive review, c: graph theory

#40129 combinatorial log
  src/sage/rings/lazy_species.py
  src/sage/rings/species.py
Labels: s: positive review, c: combinatorics

#40133 brial update to 1.2.14
  build/pkgs/brial/checksums.ini
  build/pkgs/brial/package-version.txt
Labels: c: packages: standard, s: positive review, p: blocker / 1

#40163 faster generating series for species
  src/sage/data_structures/stream.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_species.py
Labels: s: positive review

#40175 Fix tests with rpy2 3.6
  src/sage/all__sagemath_repl.py
  src/sage/interfaces/r.py
Labels: s: positive review

#40232 Improve signal handling on Windows in doctest reporting module
  src/sage/doctest/reporting.py
Labels: s: positive review, c: doctest framework

#40239 Simplify matrix construction in btquotient
  src/sage/modular/btquotients/btquotient.py
Labels: s: positive review

#40243 special case for principal specialization of order 1
  src/sage/combinat/sf/elementary.py
  src/sage/combinat/sf/homogeneous.py
  src/sage/combinat/sf/monomial.py
  src/sage/combinat/sf/powersum.py
  src/sage/combinat/sf/schur.py
Labels: s: positive review

#40250 Improve _element_constructor_ of image set
  src/sage/sets/image_set.py
Labels: s: positive review

#40257 trying to move Laurent rings to use Parent only
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/power_series_ring.py
Labels: s: positive review, c: coercion, c: commutative algebra

#40258 use ruff to auto-simplify SIM110
  src/sage/categories/regular_crystals.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/combinat/bijectionist.py
  src/sage/combinat/designs/covering_design.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/ncsym/ncsym.py
  src/sage/combinat/partition_algebra.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/set_partition.py
  src/sage/combinat/sf/ns_macdonald.py
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/morphism.py
  src/sage/crypto/util.py
  src/sage/doctest/external.py
  src/sage/functions/piecewise.py
  src/sage/geometry/polyhedron/base1.py
  src/sage/geometry/polyhedron/face.py
  src/sage/geometry/polyhedron/ppl_lattice_polytope.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/isgci.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/manifolds/differentiable/degenerate_submanifold.py
  src/sage/manifolds/differentiable/vector_bundle.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/modform/space.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/quadratic_forms/genera/genus.py
  src/sage/quivers/representation.py
  src/sage/rings/derivation.py
  src/sage/rings/ideal.py
  src/sage/rings/polynomial/laurent_polynomial_ring_base.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/tate_algebra.py
  src/sage/sandpiles/sandpile.py
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/sets/finite_set_maps.py
  src/sage/sets/real_set.py
  src/sage/tensor/modules/comp.py
  src/sage/topology/simplicial_complex_morphism.py
Labels: s: positive review, t: refactoring

#40274 Add flatter support
  src/sage/features/flatter.py
  src/sage/matrix/matrix_integer_dense.pyx
Labels: s: positive review, c: interfaces: optional

#40276 Avoid hermite_form in solve_right if possible
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#40283 Fix segmentation fault in module element multiplication
  src/sage/modules/free_module_element.pyx
Labels: s: positive review

#40284 PNC k shortest simple path (for directed graphs)
  src/doc/en/reference/references/index.rst
  src/sage/graphs/path_enumeration.pyx
Labels: s: positive review, c: graph theory, gsoc: 2025

#40294 Fix loading symbolic expressions containing symbolic functions
  src/sage/symbolic/function.pyx
  src/sage/symbolic/pynac_impl.pxi
Labels: s: positive review

#40302 Fixed small typo in p-adic Smith form
  src/sage/rings/padics/local_generic.py
Labels: s: positive review

#40309 Fix lint
  src/sage/rings/number_field/number_field.py
Labels: s: positive review, p: CI Fix

#40310 fix typo
  src/sage/combinat/bijectionist.py
Labels: s: positive review

#40311 When installing prerequisite, include `_prereq`
  .github/workflows/ci-macos.yml
  .github/workflows/dist.yml
Labels: s: positive review, c: distribution

#40314 avoid using networkx in `src/sage/matroids/transversal_matroid.pyx`
  src/sage/matroids/transversal_matroid.pxd
  src/sage/matroids/transversal_matroid.pyx
Labels: s: positive review, c: graph theory, c: matroid theory

#40322 various small details in padics
  src/sage/rings/padics/common_conversion.pyx
  src/sage/rings/padics/local_generic_element.pyx
  src/sage/rings/padics/morphism.pyx
  src/sage/rings/padics/padic_ZZ_pX_CR_element.pyx
  src/sage/rings/padics/padic_ext_element.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/padics/padic_printing.pyx
  src/sage/rings/padics/padic_template_element_header.pxi
  src/sage/rings/padics/pow_computer.pyx
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/padics/pow_computer_flint.pyx
  src/sage/rings/padics/relative_ramified_FM.pyx
Labels: s: positive review, c: padics

#40324 Remove 'archlinux-latest' from sage-the-distro CI tests
  .github/workflows/docker.yml
Labels: s: positive review

#40325 minor details in doc and code of algebras/
  src/sage/algebras/affine_nil_temperley_lieb.py
  src/sage/algebras/free_algebra_element.py
  src/sage/algebras/fusion_rings/fusion_double.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
Labels: s: positive review, c: algebra

#40326 avoid using Field in free quadratic modules
  src/sage/modules/free_quadratic_module.py
Labels: s: positive review, c: linear algebra

#40329 cylint cleanup in calculus
  src/sage/calculus/integration.pyx
  src/sage/calculus/riemann.pyx
  src/sage/calculus/transforms/dwt.pyx
Labels: s: positive review, c: calculus

#40330 cylint cleanup in geometry
  src/sage/geometry/integral_points.pxi
  src/sage/geometry/point_collection.pyx
  src/sage/geometry/toric_lattice_element.pyx
Labels: s: positive review, c: geometry

#40331 remove unused variables in rings/
  src/sage/rings/bernoulli_mod_p.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/function_field/khuri_makdisi.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_morphism.pyx
  src/sage/rings/tate_algebra_element.pyx
  src/sage/rings/tate_algebra_ideal.pyx
Labels: s: positive review, c: algebra

#40334 minor fixes in a pyx file in quadratic_forms
  src/doc/en/reference/references/index.rst
  src/sage/graphs/generators/smallgraphs.py
  src/sage/quadratic_forms/count_local_2.pyx
Labels: s: positive review, c: quadratic forms

#40336 more uses of doi role in master reference file
  src/doc/en/reference/references/index.rst
Labels: s: positive review, c: documentation

#40338 Fix 32-bit segfault in m4ri
  build/pkgs/m4ri/patches/b178ed36bdd841a76b6595edb77631886e099406.patch
Labels: s: positive review

#40347 remove deprecated methods in combinat/words
  src/sage/combinat/words/finite_word.py
Labels: s: positive review, c: combinatorics

#40348 Fix a small typo
  src/sage/combinat/root_system/reflection_group_element.pyx
Labels: s: positive review

#40349 remove the auld historic "Group" class
  src/sage/groups/meson.build
  src/sage/groups/old.pxd
  src/sage/groups/old.pyx
Labels: s: positive review, c: group theory

#40354 correct syntax in maxima's spkg-configure.m4
  build/pkgs/maxima/spkg-configure.m4
Labels: s: positive review, c: build: configure

#39208 Rename module-global test methods
  src/doc/en/developer/doctesting.rst
  src/sage/algebras/fusion_rings/fusion_ring.py
  src/sage/categories/category_with_axiom.py
  src/sage/crypto/mq/sr.py
  src/sage/databases/oeis.py
  src/sage/graphs/graph_decompositions/modular_decomposition.pyx
  src/sage/interfaces/sympy.py
  src/sage/libs/gap/test.py
  src/sage/libs/gap/test_long.py
  src/sage/misc/explain_pickle.py
  src/sage/misc/random_testing.py
  src/sage/repl/interpreter.py
  src/sage/rings/infinity.py
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/tests.py
  src/sage/schemes/elliptic_curves/kraus.py
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/random_tests.py
  src/sage/symbolic/relation.py
  src/sage/tests/__init__.py
  src/sage/tests/cmdline.py
  src/sage/tests/finite_poset.py
  src/sage/tests/memcheck/symbolic_expression.py
  src/sage/tests/startup.py
Labels: s: positive review

#39586 Simplify implementation of solve()
  src/sage/symbolic/relation.py
Labels: s: positive review, c: symbolics

#39646 Use TemporaryFile for test code compilation
  src/sage/features/__init__.py
  src/sage/repl/load.py
Labels: s: positive review

#39657 Overwrote methods concerning connectivity in a matching covered graph
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory

#39975 Fix two floating point bugs in the hyperbolic geometry code
  src/sage/geometry/hyperbolic_space/hyperbolic_coercion.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
Labels: s: positive review

#40415 Remove precisely the prefix instead of strip
  src/sage/interfaces/singular.py
  src/sage/plot/misc.py
Labels: s: positive review, t: refactoring

#40419 Remove unnecessary empty string in print function
  build/sage_bootstrap/download/cmdline.py
  src/sage/combinat/cluster_algebra_quiver/cluster_seed.py
  src/sage/logic/logic.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/sandpiles/sandpile.py
  src/sage_setup/autogen/flint/writer.py
Labels: s: positive review, t: refactoring

#40420 Method A-field for Drinfeld modules
  src/sage/categories/drinfeld_modules.py
Labels: s: positive review

#40421 Limit the use of RingExtensions in Drinfeld modules
  src/sage/categories/drinfeld_modules.py
  src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/morphism.py
Labels: s: positive review

#40422 use generic isogeny call to opportunistically use velusqrt
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
Labels: p: minor / 4, s: positive review, c: algebraic geometry

#40424 src/sage/interfaces/maxima_lib.py: remove old workaround
  src/sage/interfaces/maxima_lib.py
Labels: s: positive review

#40429 Remove unnecessary range start
  src/sage/crypto/mq/sr.py
  src/sage/graphs/generators/families.py
  src/sage/graphs/generic_graph.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/homology/chain_complex.py
  src/sage/interacts/library.py
  src/sage/manifolds/differentiable/examples/symplectic_space.py
  src/sage/manifolds/differentiable/symplectic_form.py
  src/sage/matroids/database_collections.py
  src/sage/matroids/database_matroids.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/plot/hyperbolic_polygon.py
  src/sage/plot/plot3d/tri_plot.py
  src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/totallyreal_rel.py
  src/sage/schemes/elliptic_curves/isogeny_small_degree.py
  src/sage/schemes/projective/projective_morphism.py
  src/sage/topology/simplicial_complex_examples.py
Labels: s: positive review

#40439 simplify some nested for loops
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/categories/finite_semigroups.py
  src/sage/combinat/partition.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/orientations.py
Labels: s: positive review

#38902 division of elliptic-curve morphisms
  src/doc/en/reference/arithmetic_curves/index.rst
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_fractional.py
  src/sage/schemes/elliptic_curves/meson.build
Labels: p: major / 3, t: enhancement, s: positive review, c: elliptic curves

#39089 Change __call__ to _element_constructor_ in multipolynomial ring
  src/sage/combinat/integer_vector.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/rings/polynomial/multi_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/structure/coerce.pyx
Labels: s: positive review

#39359 Addition of new presentations to Chow rings of matroids
  src/doc/en/reference/references/index.rst
  src/sage/categories/kahler_algebras.py
  src/sage/matroids/chow_ring.py
  src/sage/matroids/chow_ring_ideal.py
  src/sage/matroids/matroid.pyx
Labels: s: positive review

#39428 Replace `arithgroup.all` imports
  src/sage/modular/abvar/abvar_ambient_jacobian.py
  src/sage/modular/abvar/abvar_newform.py
  src/sage/modular/abvar/constructor.py
  src/sage/modular/abvar/cuspidal_subgroup.py
  src/sage/modular/abvar/torsion_subgroup.py
  src/sage/modular/arithgroup/arithgroup_generic.py
  src/sage/modular/arithgroup/congroup_gamma.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/arithgroup/congroup_gamma1.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/modular/arithgroup/tests.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/cusps.py
  src/sage/modular/dims.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/hecke_operator.py
  src/sage/modular/hecke/submodule.py
  src/sage/modular/local_comp/type_space.py
  src/sage/modular/modform/ambient.py
  src/sage/modular/modform/ambient_eps.py
  src/sage/modular/modform/ambient_g0.py
  src/sage/modular/modform/ambient_g1.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform/numerical.py
  src/sage/modular/modform/ring.py
  src/sage/modular/modform/space.py
  src/sage/modular/modform/weight1.py
  src/sage/modular/modsym/space.py
  src/sage/modular/modsym/tests.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/space.py
  src/sage/modular/ssmod/ssmod.py
Labels: s: positive review

#39802 Module and Graph method for Projective planarity via forbidden minors
  src/doc/en/reference/graphs/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/graphs/generators/families.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory

#40090 Overwrote methods concerning subdivision of edge(s) in a matching covered graph
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory, gsoc: 2025

#40211 detect unsolvable systems when solving integer linear systems
  src/sage/matrix/matrix2.pyx
Labels: p: major / 3, t: bug, s: positive review, c: linear algebra

#40251 Implement kernel_points and inverse_image for elliptic curve hom
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_composite.py
Labels: s: positive review

#40259 Upgrade to flint-3.3.1
  build/pkgs/eclib/checksums.ini
  build/pkgs/eclib/package-version.txt
  build/pkgs/eclib/spkg-configure.m4
  build/pkgs/flint/checksums.ini
  build/pkgs/flint/package-version.txt
  build/pkgs/flint/spkg-build.in
  build/pkgs/singular/patches/flint-3.3.0-compatibility.patch
Labels: s: positive review, p: blocker / 1

#40277 Check that vectors are not passed to matrix.block
  src/sage/matrix/special.py
Labels: s: positive review

#40315 Document that valuation can be called
  src/sage/rings/padics/padic_valuation.py
Labels: s: positive review, c: documentation, c: padics

#40351 remove deprecated function about Simon 2-descent in BSD
  src/sage/schemes/elliptic_curves/BSD.py
Labels: s: positive review, c: elliptic curves

#40358 add convenient factor method to FHM triangles
  src/sage/combinat/triangles_FHM.py
Labels: s: positive review, c: combinatorics

#40365 minor details in matchings of graphs
  src/sage/graphs/matching.py
Labels: s: positive review, c: graph theory

#40369 Build sirocco extension with C++
  src/sage/libs/meson.build
Labels: s: positive review, p: critical / 2

#40374 Fix a memory leak
  src/sage/rings/real_arb.pyx
Labels: s: positive review

#40380 Silence more rpy2 3.6 warnings
  src/sage/all__sagemath_repl.py
Labels: s: positive review

#40381 Implement random unitary matrices
  src/doc/en/reference/references/index.rst
  src/sage/matrix/special.py
Labels: s: positive review

#40382 rectify gentoo package name details for lcalc and qhull
  build/pkgs/lcalc/distros/gentoo.txt
  build/pkgs/qhull/distros/gentoo.txt
Labels: s: positive review

#40383 Update conda environment to include rpy2
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.11-win.yml
  environment-3.12-linux-aarch64.yml
  environment-3.12-linux.yml
  environment-3.12-macos-x86_64.yml
  environment-3.12-macos.yml
  environment-3.12-win.yml
  environment-3.13-win.yml
  pyproject.toml
  tools/update-conda.py
Labels: s: positive review

#40384 src/sage/geometry/cone.py: speed up a random_cone() test
  src/sage/geometry/cone.py
Labels: s: positive review

#40385 Fix lint
  src/sage/doctest/reporting.py
  src/sage/geometry/hyperbolic_space/hyperbolic_coercion.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/interfaces/r.py
Labels: s: positive review, p: CI Fix

#40387 Refactor Hilbert_basis() and replace a slow test
  src/sage/geometry/cone.py
Labels: s: positive review

#40388 Do not ignore env.py fallbacks for empty variables in config.py
  src/sage/env.py
Labels: s: positive review

#40389 Less spaces in function calls
  src/sage/categories/homset.py
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/padics/morphism.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/tests/books/computational-mathematics-with-sagemath/programmation_doctest.py
  src/sage/tests/books/computational-mathematics-with-sagemath/sol/numbertheory_doctest.py
Labels: s: positive review

#40390 remove some unused variables in libs/
  src/sage/libs/flint/fmpz_poly_sage.pyx
  src/sage/libs/gap/element.pyx
  src/sage/libs/gap/util.pyx
  src/sage/libs/lcalc/lcalc_Lfunction.pyx
  src/sage/libs/meataxe.pyx
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/libs/mpmath/utils.pyx
  src/sage/libs/ntl/ntl_ZZ_p.pyx
  src/sage/libs/ntl/ntl_mat_ZZ.pyx
  src/sage/libs/pari/convert_sage.pyx
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/polynomial.pyx
  src/sage/libs/sirocco.pyx
Labels: s: positive review

#40392 moving two methods to the categories of rings and fields
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/fields.py
  src/sage/categories/rings.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: categories

#40393 cleanup and code details in cluster_algebra_quiver
  src/sage/combinat/cluster_algebra_quiver/all.py
  src/sage/combinat/cluster_algebra_quiver/cluster_seed.py
  src/sage/combinat/cluster_algebra_quiver/interact.py
  src/sage/combinat/cluster_algebra_quiver/mutation_class.py
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/cluster_algebra_quiver/quiver.py
  src/sage/combinat/cluster_algebra_quiver/quiver_mutation_type.py
Labels: s: positive review, c: combinatorics

#40400 faster Hochschild lattices
  src/sage/combinat/posets/hochschild_lattice.py
Labels: s: positive review, c: combinatorics

#40408 simpler code in delta complexes
  src/sage/topology/delta_complex.py
Labels: s: positive review, c: algebraic topology

#40409 minor details in modular/
  src/sage/modular/abvar/abvar.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/modform/element.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/quasimodform/element.py
Labels: s: positive review, c: modular forms

#40411 large cleanup of master reference file
  src/doc/en/reference/references/index.rst
Labels: s: positive review, c: documentation

#40413 Show long time warnings as GitHub annotations
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
  src/sage/doctest/sources.py
  src/sage/doctest/test.py
  src/sage/doctest/tests/sleep2.rst
Labels: s: positive review

#40414 Add some missing "long time" annotations
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_change.rst
  src/doc/en/thematic_tutorials/vector_calculus/vector_calc_curvilinear.rst
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/doctest/forker.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/graphs/hypergraph_generators.py
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/interacts/test_jupyter.rst
Labels: s: positive review

#40417 bump cibuildwheel version and various other versions
  .github/workflows/dist.yml
  docker/Dockerfile
Labels: s: positive review
