Repository sagemath/sage, pull requests merged in 2025-03, with the labels that each got.

#39610 adding the check for pycodestyle E222 in pyx files
  src/tox.ini
Labels: s: positive review

#39613 some typing in Permutation
  src/sage/combinat/permutation.py
Labels: s: positive review, c: combinatorics

#39617 Fixed _positive_roots_reflections for index_set different from {1, 2, …, n}
  src/sage/groups/matrix_gps/coxeter_group.py
Labels: t: bug, s: positive review, c: combinatorics

#39619 remove unused imports in rings
  src/sage/rings/finite_rings/finite_field_constructor.py
  src/sage/rings/function_field/drinfeld_modules/homset.py
  src/sage/rings/number_field/order_ideal.py
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/polynomial/polynomial_singular_interface.py
  src/sage/rings/power_series_ring.py
Labels: s: positive review, t: refactoring

#39621 Fix documentation diff for cython()
  src/sage/misc/cython.py
Labels: s: positive review

#39624 Fix Commutator subgroup of permutation group
  src/sage/groups/perm_gps/permgroup.py
Labels: s: positive review, c: group theory

#39625 some fixes by ruff about nested max
  src/sage/combinat/rigged_configurations/rigged_configuration_element.py
  src/sage/combinat/set_partition.py
  src/sage/combinat/words/finite_word.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/matroids/matroids_plot_helpers.py
  src/sage/sat/solvers/cryptominisat.py
  src/sage/sat/solvers/picosat.py
Labels: s: positive review, t: refactoring

#39631 remove pkg combinatorial_designs
  build/pkgs/combinatorial_designs/SPKG.rst
  build/pkgs/combinatorial_designs/checksums.ini
  build/pkgs/combinatorial_designs/dependencies
  build/pkgs/combinatorial_designs/distros/arch.txt
  build/pkgs/combinatorial_designs/distros/conda.txt
  build/pkgs/combinatorial_designs/distros/repology.txt
  build/pkgs/combinatorial_designs/math
  build/pkgs/combinatorial_designs/package-version.txt
  build/pkgs/combinatorial_designs/spkg-install.in
  build/pkgs/combinatorial_designs/type
Labels: s: positive review, c: combinatorial designs

#39634 some details in lean_matrix
  src/sage/matroids/lean_matrix.pyx
Labels: s: positive review

#38455 unitary DFT for symmetric group algebra
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/combinat/symmetric_group_representations.py
  src/sage/matrix/matrix2.pyx
Labels: s: positive review, c: combinatorics, c: algebra

#39102 Show continuation lines when doctest crashes
  .github/workflows/build.yml
  src/sage/doctest/forker.py
  src/sage/doctest/test.py
  src/sage/doctest/tests/fail_and_die.rst
Labels: s: positive review

#39256 Add check for zero monomial in monomial_coefficient
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: t: bug, s: positive review

#39269 add parameter immutable to generators in `sage/graphs/digraph_generators.py` (part 3)
  src/sage/graphs/digraph_generators.py
  src/sage/graphs/graph_generators_pyx.pyx
Labels: s: positive review, c: graph theory

#39286 Migrate pyright workflow to use conda
  .github/workflows/pyright.yml
Labels: s: positive review

#39287 add parameter `immutable` to transitive closure methods in `sage/graphs/generic_graph.py`
  src/sage/categories/kahler_algebras.py
  src/sage/combinat/posets/lattices.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/matroids/chow_ring.py
  src/sage/matroids/chow_ring_ideal.py
Labels: s: positive review, c: graph theory

#39369 Test pip editable install with meson
  .github/workflows/ci-meson.yml
Labels: s: positive review

#39413 Fix compilation and doctests with flintlib 3.2
  src/sage/libs/flint/flint.pxd
  src/sage/libs/flint/flint_wrap.h
  src/sage/libs/flint/types.pxd
  src/sage/rings/complex_arb.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/real_arb.pyx
  src/sage/symbolic/ginac/numeric.cpp
  src/sage_setup/autogen/flint/templates/flint_wrap.h.template
  src/sage_setup/autogen/flint/templates/types.pxd.template
Labels: s: positive review

#39467 Disable broken and outdated CI
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/ci-linux.yml
  .github/workflows/ci-macos.yml
  .github/workflows/docker.yml
  .github/workflows/macos.yml
  src/doc/en/developer/github.rst
  src/doc/en/developer/portability_testing.rst
Labels: s: positive review, disputed

#39519 Provide an iterative version on some functions on trees
  src/sage/combinat/abstract_tree.py
Labels: s: positive review, c: combinatorics, sd128

#39546 Fixes error causing period function in BinaryRecurrenceSequence to stall and added enhancement
  src/sage/combinat/binary_recurrence_sequences.py
Labels: s: positive review

#39559 Remove defining ideal hack
  src/sage/rings/quotient_ring.py
Labels: s: positive review, c: algebra

#39562 Meson: Remove unused build dependencies ppl and fplll
  pyproject.toml
  src/meson.build
  src/sage/libs/linbox/meson.build
Labels: s: positive review

#39571 Bump pillow and cffi
  build/pkgs/cffi/checksums.ini
  build/pkgs/cffi/distros/homebrew.txt
  build/pkgs/cffi/package-version.txt
  build/pkgs/pillow/checksums.ini
  build/pkgs/pillow/distros/homebrew.txt
  build/pkgs/pillow/package-version.txt
Labels: s: positive review

#39579 some details in schemes, typing annotation for gens
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/generic/ambient_space.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/schemes/plane_conics/con_field.py
  src/sage/schemes/toric/chow_group.py
  src/sage/schemes/toric/divisor.py
  src/sage/schemes/toric/variety.py
Labels: s: positive review, t: refactoring

#39593 remove traces of experimental package `modular_decomposition`
  build/pkgs/modular_decomposition/SPKG.rst
  build/pkgs/modular_decomposition/checksums.ini
  build/pkgs/modular_decomposition/distros/repology.txt
  build/pkgs/modular_decomposition/math
  build/pkgs/modular_decomposition/package-version.txt
  build/pkgs/modular_decomposition/spkg-install.in
  build/pkgs/modular_decomposition/type
Labels: c: packages: experimental, s: positive review

#39594 fix latex code in one crystal file
  src/sage/combinat/crystals/generalized_young_walls.py
Labels: s: positive review

#39597 extract _front_back_facets method out of _tikz_3d_in_3d polyhedron method
  src/sage/geometry/polyhedron/plot.py
Labels: s: positive review, c: geometry, sd128

#39602 bump executing to 2.2.0
  build/pkgs/executing/checksums.ini
  build/pkgs/executing/package-version.txt
Labels: s: positive review

#39605 minor details in boolean_polynomials
  src/sage/sat/boolean_polynomials.py
Labels: s: positive review

#39606 minor details in invariant_theory (pep8)
  src/sage/rings/asymptotic/asymptotic_ring.py
  src/sage/rings/invariants/invariant_theory.py
Labels: s: positive review

#39607 add missing parenthesis in magma conversion file
  src/sage/ext_data/magma/sage/basic.m
Labels: s: positive review, c: interfaces: optional

#39609 some minor details in fusion_double
  src/sage/algebras/fusion_rings/fusion_double.py
Labels: s: positive review, t: refactoring

#39611 remove unused import + pep8 cleanup in modform/element
  src/sage/modular/modform/element.py
Labels: s: positive review, c: modular forms

#39612 Improve documentation of discrete valuations
  src/sage/rings/valuation/augmented_valuation.py
  src/sage/rings/valuation/developing_valuation.py
Labels: s: positive review

#39623 Fix spacing for documentation
  src/sage/combinat/dyck_word.py
  src/sage/combinat/posets/posets.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/matrix/matrix_modn_dense_template.pxi
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: s: positive review, c: documentation

#39626 Fixed issue the caused random element in for Tuples to stall by adding unrank method.
  src/sage/categories/enumerated_sets.py
  src/sage/combinat/tuple.py
  src/sage/sets/finite_enumerated_set.py
Labels: s: positive review

#39629 add magma as optional algorithm for Coxeter polynomial of posets
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#39632 Implement matrix Schubert variety ideals
  src/doc/en/reference/references/index.rst
  src/sage/combinat/diagram.py
  src/sage/combinat/permutation.py
Labels: t: enhancement, s: positive review, c: algebraic geometry, c: combinatorics

#37189 Constructor quaternion algebra over number fields from ramification
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: enhancement, s: positive review, c: algebra

#38703 Implementation of Ore modules
  src/doc/en/reference/categories/index.rst
  src/doc/en/reference/index.rst
  src/doc/en/reference/oremodules/conf.py
  src/doc/en/reference/oremodules/index.rst
  src/sage/categories/meson.build
  src/sage/categories/ore_modules.py
  src/sage/modules/free_module_pseudomorphism.py
  src/sage/modules/meson.build
  src/sage/modules/ore_module.py
  src/sage/modules/ore_module_element.py
  src/sage/modules/ore_module_homspace.py
  src/sage/modules/ore_module_morphism.py
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/ore_polynomial_ring.py
Labels: s: positive review, c: linear algebra, c: algebra, sd128

#38879 Run meson-ci for MacOS
  .github/workflows/ci-meson.yml
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.12-linux-aarch64.yml
  environment-3.12-linux.yml
  environment-3.12-macos-x86_64.yml
  environment-3.12-macos.yml
  pyproject.toml
  src/sage/doctest/control.py
  src/sage/interfaces/sage0.py
  src/sage/libs/linbox/meson.build
  src/sage/matrix/meson.build
  src/sage/repl/configuration.py
  src/sage/repl/ipython_extension.py
  tools/update-conda.py
Labels: s: positive review

#39069 Mention .coerce() method in coercion tour
  src/doc/en/tutorial/tour_coercion.rst
  src/doc/fr/tutorial/tour_coercion.rst
  src/doc/ja/tutorial/tour_coercion.rst
  src/doc/pt/tutorial/tour_coercion.rst
Labels: s: positive review, c: documentation

#39221 new implementation of method `is_transitive` with linear memory space
  src/sage/graphs/comparability.pyx
Labels: s: positive review, c: graph theory

#39234 more uses of cached_method in modular folder
  src/sage/modular/modform/space.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/manin_symbol_list.py
  src/sage/modular/modsym/space.py
  src/sage/modular/modsym/subspace.py
  src/sage/modular/ssmod/ssmod.py
Labels: s: positive review, c: modular forms

#39274 Remove `--fiximports` helper
  src/.relint.yml
  src/bin/sage
  src/doc/en/developer/packaging_sage_library.rst
  src/sage/features/all.py
  src/sage/misc/all.py
  src/sage/misc/dev_tools.py
  src/sage/misc/meson.build
  src/sage/misc/replace_dot_all.py
  src/sage/misc/sageinspect.py
Labels: s: positive review

#39296 fix the behavior for immutable graphs in methods related to isomorphisms in `sage/graphs/generic_graph.py`
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/bliss.pyx
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39444 Improve is_empty and is_finite in a few cases
  src/sage/categories/euclidean_domains.py
  src/sage/categories/homset.py
  src/sage/categories/sets_cat.py
  src/sage/categories/unique_factorization_domains.py
  src/sage/combinat/words/words.py
  src/sage/geometry/polyhedron/representation.py
  src/sage/groups/additive_abelian/additive_abelian_group.py
  src/sage/groups/group.pyx
  src/sage/modular/arithgroup/congroup_generic.py
  src/sage/modular/hecke/algebra.py
  src/sage/modular/modform/element.py
  src/sage/modules/free_module.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/sets/family.pyx
  src/sage/sets/pythonclass.pyx
  src/sage/sets/set.py
  src/sage/symbolic/ring.pyx
Labels: s: positive review

#39574 Fixed issue causing the quotient of vector subspaces to throw an exception when divisor is the zero space
  src/sage/modules/quotient_module.py
Labels: s: positive review, c: linear algebra

#39622 Fix CI documentation diff
  .github/workflows/doc-build.yml
  tools/update-conda.py
  tools/update-meson.py
Labels: s: positive review

#39637 large cleanup in one cluster file
  src/sage/combinat/cluster_algebra_quiver/quiver.py
Labels: s: positive review

#39638 fix typo in ladder_idempotent
  src/sage/combinat/symmetric_group_algebra.py
Labels: s: positive review

#39645 Remove deprecated PseudoQuaternionicProjectivePlane alias
  src/sage/topology/simplicial_complex_examples.py
Labels: s: positive review, c: algebraic topology

#39652 pythran 0.17.0, switch to wheel
  build/pkgs/pythran/checksums.ini
  build/pkgs/pythran/package-version.txt
  build/pkgs/pythran/spkg-install.in
  build/pkgs/pythran/version_requirements.txt
Labels: s: positive review

#39653 ninja_build: Update to 1.12.1
  build/pkgs/ninja_build/checksums.ini
  build/pkgs/ninja_build/package-version.txt
Labels: s: positive review

#39654 Pybind11, version 2.13.6
  build/pkgs/pybind11/checksums.ini
  build/pkgs/pybind11/package-version.txt
  build/pkgs/pybind11/spkg-install.in
  build/pkgs/pybind11/version_requirements.txt
Labels: s: positive review

#39664 Add some 'not tested' marks to avoid CI failure
  src/sage/knots/link.py
  src/sage/rings/polynomial/symmetric_ideal.py
  src/sage/rings/semirings/tropical_variety.py
  src/sage/schemes/elliptic_curves/ell_point.py
Labels: s: positive review, p: CI Fix

#39665 Added example in digits function to showcase that the sum of digits can be computed
  src/sage/rings/integer.pyx
Labels: s: positive review

#39670 CI: Remove broken Linux Mint and openSUSE runs
  .github/workflows/docker.yml
Labels: s: positive review

#39673 en/thematic_tutorials/profiling.rst: update runsnake docs
  src/doc/en/thematic_tutorials/profiling.rst
Labels: s: positive review

#39675 update trove_classifiers to 2025.3.3
  build/pkgs/pillow/dependencies
  build/pkgs/trove_classifiers/checksums.ini
  build/pkgs/trove_classifiers/package-version.txt
  build/pkgs/trove_classifiers/version_requirements.txt
Labels: c: packages: standard, s: positive review

#39678 Optimize MatchingCoveredGraph’s add_edge method
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory

#39680 sphinxcontrib-htmlhelp 2.1.0
  build/pkgs/sphinxcontrib_htmlhelp/checksums.ini
  build/pkgs/sphinxcontrib_htmlhelp/package-version.txt
  build/pkgs/sphinxcontrib_htmlhelp/version_requirements.txt
Labels: c: packages: standard, s: positive review, p: blocker / 1

#39683 spaces around modulo in combinat and rings
  src/sage/combinat/designs/evenly_distributed_sets.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/combinat/designs/subhypergraph_search.pyx
  src/sage/rings/fraction_field_element.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/number_field/number_field_morphisms.pyx
  src/sage/rings/number_field/totallyreal_data.pyx
  src/sage/rings/padics/common_conversion.pyx
  src/sage/rings/padics/pow_computer_ext.pyx
  src/sage/rings/polynomial/weil/weil_polynomials.pyx
  src/sage/rings/power_series_ring_element.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/sum_of_squares.pyx
Labels: s: positive review

#39685 handling a few unused variables in geometry,graphs,numerical,structure
  src/sage/geometry/palp_normal_form.pyx
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/traversals.pyx
  src/sage/numerical/backends/cvxopt_backend.pyx
  src/sage/numerical/backends/matrix_sdp_backend.pyx
  src/sage/numerical/mip.pyx
  src/sage/numerical/sdp.pyx
  src/sage/structure/coerce.pyx
  src/sage/structure/coerce_actions.pyx
  src/sage/structure/element.pyx
  src/sage/structure/parent.pyx
Labels: s: positive review

#39686 update sphinxcontrib packages
  build/pkgs/sphinxcontrib_applehelp/checksums.ini
  build/pkgs/sphinxcontrib_applehelp/package-version.txt
  build/pkgs/sphinxcontrib_devhelp/checksums.ini
  build/pkgs/sphinxcontrib_devhelp/package-version.txt
  build/pkgs/sphinxcontrib_qthelp/checksums.ini
  build/pkgs/sphinxcontrib_qthelp/package-version.txt
  build/pkgs/sphinxcontrib_serializinghtml/checksums.ini
  build/pkgs/sphinxcontrib_serializinghtml/package-version.txt
  build/pkgs/sphinxcontrib_websupport/checksums.ini
  build/pkgs/sphinxcontrib_websupport/package-version.txt
Labels: c: packages: standard, s: positive review

#39693 Added the rank method under ModulesWithBasis.ParentMethod.
  src/sage/categories/modules_with_basis.py
Labels: s: positive review, c: categories

#39699 Fixing the ruff linting
  src/sage/combinat/abstract_tree.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/interfaces/axiom.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
  src/sage/topology/cubical_complex.py
Labels: s: positive review, p: CI Fix

#39700 Fix typo in SAGE_PARI_MINVER
  build/pkgs/pari/spkg-configure.m4
Labels: s: positive review, p: blocker / 1

#39701 Use uv for linter workflow
  .github/workflows/lint.yml
  build/sage_bootstrap/package.py
  renovate.json5
  src/doc/en/developer/tools.rst
  uv.lock
Labels: s: positive review

#39711 Allow negative shift for flint rational polynomial
  src/sage/rings/laurent_series_ring_element.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
Labels: s: positive review

#39724 Fixing the cartesian product of a CFM and a generic object.
  src/sage/combinat/free_module.py
Labels: t: bug, s: positive review, c: algebra, c: categories

#39732 Update docstring on E2
  src/sage/modular/quasimodform/ring.py
Labels: s: positive review, c: documentation, c: modular forms

#39738 update msolve to version 7.5
  build/pkgs/msolve/checksums.ini
  build/pkgs/msolve/package-version.txt
Labels: s: positive review

#39671 fix overflow in Matrix_modn_dense
  src/sage/matrix/matrix_modn_dense_template.pxi
Labels: s: positive review, p: critical / 2
