Repository sagemath/sage, pull requests merged in 2025-04, with the labels that each got.

#38762 Added a Tutte Embedding Layout for Graphs
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_plot.py
Labels: s: positive review, c: graph theory

#39007 Fix cpu time on Windows
  src/sage/interfaces/interface.py
  src/sage/misc/timing.py
Labels: s: positive review

#39015 Meson: add sage cli
  pyproject.toml
  src/.relint.yml
  src/sage/cli/__init__.py
  src/sage/cli/__main__.py
  src/sage/cli/eval_cmd.py
  src/sage/cli/eval_cmd_test.py
  src/sage/cli/interactive_shell_cmd.py
  src/sage/cli/notebook_cmd.py
  src/sage/cli/notebook_cmd_test.py
  src/sage/cli/options.py
  src/sage/cli/version_cmd.py
  src/sage/meson.build
  src/sage/misc/abstract_method.py
  src/sage/misc/banner.py
  src/sage/misc/lazy_attribute.pyx
  src/sage/tests/cmdline.py
Labels: s: positive review

#39419 trying to get rid of coerce_c_impl
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_ring_base.pxd
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
Labels: s: positive review, c: coercion, c: commutative algebra, t: refactoring

#39511 Macaulay matrix for Sequence Multivariate Polynomials
  src/doc/en/reference/references/index.rst
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/polynomial_ring.py
Labels: s: positive review, c: commutative algebra, sd128

#39641 CI: Migrate test-new to meson
  .github/workflows/build.yml
  .github/workflows/ci-meson.yml
Labels: s: positive review

#39647 Redirect warning output from stderr to stdout in doctests
  src/sage/doctest/forker.py
Labels: s: positive review

#39694 Ruff: move config to `pyproject.toml`
  .vscode/settings.json
  pyproject.toml
  ruff.toml
Labels: s: positive review

#39728 CI: Remove broken wheel building for sagemath-categories
  .github/workflows/dist.yml
Labels: s: positive review

#39757 Ensure _charpoly_df is interruptible
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#39758 Improve crosslink between matrix methods and small optimization
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_dense.pyx
  src/sage/matrix/matrix_double_dense.pyx
Labels: s: positive review

#39766 Fix Derangements(0) to return 1 and yield the empty permutation
  src/sage/combinat/derangements.py
Labels: s: positive review, c: combinatorics

#39776 Safeguard _sage_getargspec_cython
  src/sage/misc/sageinspect.py
Labels: s: positive review

#39779 Fix reference in chrompoly.pyx and add to master reference file
  src/doc/en/reference/references/index.rst
  src/sage/graphs/chrompoly.pyx
Labels: s: positive review, c: documentation, c: graph theory

#39781 magma interface: fix typo in a comment
  src/sage/interfaces/magma.py
Labels: s: positive review, c: interfaces: optional

#39785 Kostka-Foulkes polynomials now also for skew shapes
  src/sage/combinat/sf/kfpoly.py
Labels: s: positive review, c: combinatorics

#39787 Changed single colon to double colon after WARNING in relevant files
  src/sage/algebras/cluster_algebra.py
  src/sage/combinat/sf/sfa.py
  src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/schemes/hyperelliptic_curves/jacobian_endomorphism_utils.py
Labels: s: positive review, c: documentation

#39789 bump matplotlib (with its deps) to 3.10.1
  build/pkgs/contourpy/checksums.ini
  build/pkgs/contourpy/package-version.txt
  build/pkgs/cycler/checksums.ini
  build/pkgs/cycler/package-version.txt
  build/pkgs/cycler/version_requirements.txt
  build/pkgs/fonttools/checksums.ini
  build/pkgs/fonttools/package-version.txt
  build/pkgs/kiwisolver/checksums.ini
  build/pkgs/kiwisolver/package-version.txt
  build/pkgs/kiwisolver/version_requirements.txt
  build/pkgs/matplotlib/checksums.ini
  build/pkgs/matplotlib/package-version.txt
  build/pkgs/matplotlib/spkg-install.in
  build/pkgs/matplotlib/version_requirements.txt
  build/pkgs/numpy/checksums.ini
  build/pkgs/numpy/package-version.txt
  build/pkgs/packaging/checksums.ini
  build/pkgs/packaging/package-version.txt
  build/pkgs/packaging/version_requirements.txt
  build/pkgs/pyparsing/checksums.ini
  build/pkgs/pyparsing/package-version.txt
  build/pkgs/pyparsing/version_requirements.txt
  build/pkgs/six/checksums.ini
  build/pkgs/six/package-version.txt
  build/pkgs/six/version_requirements.txt
Labels: s: positive review

#39797 Small changes in matroids
  src/sage/matroids/database_matroids.py
  src/sage/matroids/matroids_plot_helpers.py
Labels: s: positive review, c: matroid theory

#39799 typing annotation in Chow ring ideal
  src/sage/matroids/chow_ring_ideal.py
Labels: s: positive review, c: matroid theory

#36029 k-regular sequences: boundedness
  src/doc/en/reference/combinat/module_list.rst
  src/doc/en/reference/references/index.rst
  src/sage/combinat/meson.build
  src/sage/combinat/regular_sequence.py
  src/sage/combinat/regular_sequence_bounded.py
Labels: p: major / 3, s: positive review, c: linear algebra, c: combinatorics

#39695 Remove obsolete `sage-conf_conda` package
  .vscode/settings.json
  pkgs/sage-conf/README.rst
  pkgs/sage-conf_conda/.gitignore
  pkgs/sage-conf_conda/MANIFEST.in
  pkgs/sage-conf_conda/README.rst
  pkgs/sage-conf_conda/VERSION.txt
  pkgs/sage-conf_conda/_sage_conf
  pkgs/sage-conf_conda/bin
  pkgs/sage-conf_conda/pyproject.toml
  pkgs/sage-conf_conda/sage_conf.py
  pkgs/sage-conf_conda/sage_root
  pkgs/sage-conf_conda/setup.cfg
  pkgs/sage-conf_conda/setup.py
  src/doc/en/installation/conda.rst
Labels: s: positive review

#39771 Remove conda-ci
  .github/workflows/ci-conda-known-test-failures.json
  .github/workflows/ci-conda.yml
Labels: s: positive review

#39773 Meson: install jupyter kernel spec
  src/doc/en/installation/launching.rst
  src/sage/ext_data/notebook-ipython/kernel.json.in
  src/sage/meson.build
Labels: s: positive review

#39794 implement doubly_lexical_ordering of 01-matrix in ```src/sage/matrix/matrix_mod2_dense.pyx```
  src/doc/en/reference/references/index.rst
  src/sage/matrix/matrix_mod2_dense.pyx
Labels: s: positive review

#39796 fix: added check for FriCAS version
  build/pkgs/fricas/spkg-configure.m4
  src/sage/features/fricas.py
Labels: s: positive review

#39810 adding alias in polytope, plus doc formatting
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/base5.py
Labels: s: positive review

#39825 Fix typo in :meth: link for is_edge_cut
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39830 Implement conjugate method for RealBall
  src/sage/rings/real_arb.pyx
Labels: s: positive review

#39844 Improve documentation in diamond_cutting.py
  src/doc/en/reference/references/index.rst
  src/sage/modules/diamond_cutting.py
Labels: s: positive review, c: documentation

#39847 refresh a little bit the autogen scripts in sage_setup
  src/sage_setup/autogen/interpreters/internal/generator.py
  src/sage_setup/autogen/interpreters/internal/specs/cdf.py
  src/sage_setup/autogen/interpreters/internal/specs/element.py
  src/sage_setup/autogen/interpreters/internal/specs/python.py
  src/sage_setup/autogen/interpreters/internal/specs/rr.py
Labels: s: positive review, c: scripts

#39848 Correctly passing kwargs in short_vectors
  src/sage/modules/free_quadratic_module_integer_symmetric.py
Labels: s: positive review

#39851 add pari algo for polynomial interpolation
  src/sage/rings/polynomial/polynomial_ring.py
Labels: s: positive review, c: commutative algebra

#39859 New oeis
  src/sage/databases/oeis.py
Labels: s: positive review

#39862 adding some pyx modules to the documentation
  src/doc/en/reference/algebras/index.rst
  src/doc/en/reference/categories/index.rst
  src/doc/en/reference/graphs/index.rst
  src/doc/en/reference/matroids/index.rst
  src/doc/en/reference/modfrm/index.rst
  src/doc/en/reference/modules/index.rst
  src/doc/en/reference/quat_algebras/index.rst
  src/sage/algebras/exterior_algebra_groebner.pyx
  src/sage/graphs/graph_decompositions/fast_digraph.pyx
  src/sage/matroids/union_matroid.pyx
  src/sage/modular/hypergeometric_misc.pyx
  src/sage/modular/modform/l_series_gross_zagier.py
  src/sage/modular/modform/l_series_gross_zagier_coeffs.pyx
Labels: s: positive review, c: documentation

#39863 add missing doc in combinat
  src/doc/en/reference/combinat/module_list.rst
  src/sage/combinat/SJT.py
  src/sage/combinat/cluster_algebra_quiver/interact.py
  src/sage/combinat/integer_lists/nn.py
  src/sage/combinat/lr_tableau.py
Labels: s: positive review, c: documentation

#39865 include more files in doc (schemes)
  src/doc/en/reference/arithmetic_curves/index.rst
  src/doc/en/reference/schemes/index.rst
  src/sage/schemes/elliptic_curves/BSD.py
  src/sage/schemes/elliptic_curves/addition_formulas_ring.py
Labels: s: positive review, c: documentation

#39867 Run long test in test-new
  .github/workflows/ci-meson.yml
Labels: s: positive review

#39877 some pep8 cleanups
  src/sage/algebras/steenrod/steenrod_algebra_mult.py
  src/sage/algebras/yokonuma_hecke_algebra.py
  src/sage/combinat/derangements.py
  src/sage/doctest/external.py
  src/sage/doctest/fixtures.py
  src/sage/rings/function_field/jacobian_hess.py
Labels: s: positive review

#39882 fix issue 39864 in `src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx`
  src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
Labels: t: bug, s: positive review, c: elliptic curves

#39885 Provided a default value for SAGE_ROOT that can be overridden by an environment variable or configuration file
  src/sage/env.py
  src/sage/meson.build
Labels: s: positive review

#39888 some cleanup in matrix1.pyx
  src/sage/matrix/matrix1.pyx
Labels: s: positive review, c: linear algebra

#39889 Implement algorithm parameter for .series()
  src/sage/symbolic/expression.pyx
Labels: s: positive review

#39891 Speed up binomial
  src/sage/arith/misc.py
  src/sage/functions/other.py
  src/sage/functions/transcendental.py
  src/sage/symbolic/function.pxd
  src/sage/symbolic/function.pyx
Labels: s: positive review, c: symbolics

#39892 some care for assert and not in pyx files
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/combinat/posets/hasse_cython.pyx
  src/sage/combinat/rigged_configurations/rigged_partition.pyx
  src/sage/crypto/boolean_function.pyx
  src/sage/graphs/path_enumeration.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/numerical/linear_tensor_element.pyx
  src/sage/numerical/mip.pyx
  src/sage/plot/plot3d/implicit_surface.pyx
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review

#39894 Fix typo in quaternion algebra docstring
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: s: positive review, c: documentation

#39895 minor typographical corrections on fano_variety.py
  src/sage/schemes/toric/fano_variety.py
Labels: s: positive review, c: documentation

#39906 Fix error in exception handling code of gap interface
  src/sage/interfaces/gap.py
Labels: s: positive review

#39915 update lcalc to version 2.1.0
  build/pkgs/lcalc/checksums.ini
  build/pkgs/lcalc/package-version.txt
Labels: s: positive review

#39919 lidia: support modern compilers that default to C++17
  build/pkgs/lidia/spkg-install.in
Labels: s: positive review

#39921 cli: Add -V alias for --version
  src/sage/cli/version_cmd.py
Labels: s: positive review

#39926 Fix gap spkg-configure.m4
  build/pkgs/gap/spkg-configure.m4
Labels: s: positive review

#39928 Support flint 3.2 spkg-configure
  build/pkgs/flint/distros/conda.txt
  build/pkgs/flint/spkg-configure.m4
Labels: s: positive review

#39938 Add is_chordal_bipartite In `sage/graphs/graph.py`
  src/doc/en/reference/references/index.rst
  src/sage/graphs/graph.py
  src/sage/matrix/matrix_mod2_dense.pyx
Labels: s: positive review, c: graph theory

#39032 Move `sage-update-version` to `tools`
  .github/workflows/ci-macos.yml
  .upstream.d/20-github.com-sagemath-sage-releases
  build/pkgs/configure/SPKG.rst
  src/doc/en/developer/packaging_sage_library.rst
  src/doc/en/website/versions.txt
  src/setup.cfg.m4
  tools/README.md
  tools/update-conda.py
  tools/update-version
Labels: s: positive review

#39204 Speed up multimodular algorithm in bad case
  src/sage/matrix/misc.pyx
Labels: s: positive review, c: linear algebra, t: performance

#39733 Make rational matrix rref default to flint_multimodular, add suboptions for flint algorithm
  src/sage/matrix/matrix_rational_dense.pyx
  src/sage/matrix/misc.pyx
Labels: s: positive review

#39743 Make inverse_mod use Singular in a few cases
  src/sage/algebras/splitting_algebra.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring_element.py
Labels: s: positive review, c: commutative algebra

#39754 Fix bipartite graph constructor for reduced adjacency matrix with `immutable=True`
  src/sage/graphs/bipartite_graph.py
Labels: s: positive review, c: graph theory

#39804 Implement more algorithms for computing eigenvalues
  src/doc/en/prep/Quickstarts/Linear-Algebra.rst
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/matrix/matrix1.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_double_dense.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/structure/element.pyx
Labels: s: needs review, s: positive review, c: linear algebra

#39821 add helper method to copy attributes in graphs
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/digraph.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/orientations.py
Labels: s: positive review, c: graph theory

#39827 fix random doctest error in `src/sage/data_structures/bitset.pyx`
  src/sage/data_structures/bitset.pyx
Labels: t: bug, s: positive review

#39842 Make sure truncate_neg works correctly
  src/sage/rings/laurent_series_ring_element.pxd
  src/sage/rings/laurent_series_ring_element.pyx
Labels: s: positive review, c: commutative algebra

#39279 Show signature for binding=False cython functions
  src/sage/misc/sageinspect.py
  src/sage/repl/ipython_extension.py
  src/sage/repl/ipython_tests.py
Labels: s: positive review

#39436 Refactor O() and fix O() for lazy power series ring
  src/sage/rings/big_oh.py
Labels: s: positive review, t: refactoring

#39480 Added enhancement for power series that allows access to the coefficients of specific terms
  src/sage/rings/multi_power_series_ring_element.py
Labels: s: positive review

#39636 cython-lint for calculus/ folder
  src/sage/calculus/integration.pyx
  src/sage/calculus/ode.pxd
  src/sage/calculus/ode.pyx
  src/sage/calculus/riemann.pyx
Labels: s: positive review, c: calculus

#39660 Changed gens to tuple in AbstractLinearCodeNoMetric, mwrank_EllipticCurve, and FiniteSubgroup.
  src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/modabvar.rst
  src/sage/coding/linear_code_no_metric.py
  src/sage/libs/eclib/interface.py
  src/sage/modular/abvar/abvar.py
  src/sage/modular/abvar/cuspidal_subgroup.py
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/abvar/torsion_subgroup.py
  src/sage/schemes/elliptic_curves/sha_tate.py
Labels: s: positive review

#39661 Changed gens to tuple in ModularFormsSpace.
  src/sage/modular/modform/space.py
Labels: s: positive review

#39716 Added code to calculate crt for non-coprime moduli in Integer
  src/sage/rings/integer.pyx
Labels: s: positive review

#39783 Add LINS to gap_packages
  Pipfile
  build/pkgs/gap_packages/SPKG.rst
  build/pkgs/gap_packages/spkg-install.in
  src/Pipfile
Labels: s: positive review

#39792 Add Simplified Chinese translation of a_tour_of_sage and tutorial
  .ci/write-dockerfile.sh
  build/pkgs/texlive/distros/arch.txt
  build/pkgs/texlive/distros/debian.txt
  build/pkgs/texlive/distros/fedora.txt
  build/pkgs/texlive/distros/gentoo.txt
  build/pkgs/texlive/package-list.txt
  src/doc/en/website/root_index.html
  src/doc/zh/a_tour_of_sage/conf.py
  src/doc/zh/a_tour_of_sage/eigen_plot.png
  src/doc/zh/a_tour_of_sage/index.rst
  src/doc/zh/a_tour_of_sage/sin_plot.png
  src/doc/zh/tutorial/afterword.rst
  src/doc/zh/tutorial/appendix.rst
  src/doc/zh/tutorial/bibliography.rst
  src/doc/zh/tutorial/conf.py
  src/doc/zh/tutorial/index.rst
  src/doc/zh/tutorial/interactive_shell.rst
  src/doc/zh/tutorial/interfaces.rst
  src/doc/zh/tutorial/introduction.rst
  src/doc/zh/tutorial/latex.rst
  src/doc/zh/tutorial/programming.rst
  src/doc/zh/tutorial/sagetex.rst
  src/doc/zh/tutorial/tour.rst
  src/doc/zh/tutorial/tour_advanced.rst
  src/doc/zh/tutorial/tour_algebra.rst
  src/doc/zh/tutorial/tour_assignment.rst
  src/doc/zh/tutorial/tour_coercion.rst
  src/doc/zh/tutorial/tour_functions.rst
  src/doc/zh/tutorial/tour_groups.rst
  src/doc/zh/tutorial/tour_help.rst
  src/doc/zh/tutorial/tour_linalg.rst
  src/doc/zh/tutorial/tour_numtheory.rst
  src/doc/zh/tutorial/tour_plotting.rst
  src/doc/zh/tutorial/tour_polynomial.rst
  src/doc/zh/tutorial/tour_rings.rst
Labels: s: positive review, c: documentation

#39852 Handle empty matrices over univariate polynomials
  src/sage/matrix/matrix_polynomial_dense.pyx
Labels: s: positive review

#39856 Improve NotImplementedError for sqrt(Mod(a,n), all=True)
  src/sage/rings/finite_rings/integer_mod.pyx
Labels: s: positive review

#39884 Make generic polynomial multiplication interruptible
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review

#39925 add parameter immutable to methods in `src/sage/graphs/line_graph.pyx`
  src/sage/graphs/line_graph.pyx
Labels: s: positive review, c: graph theory

#39935 improve graph backends to fix bug in `lex_BFS`
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/base/dense_graph.pxd
  src/sage/graphs/base/dense_graph.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/graph_decompositions/slice_decomposition.pyx
  src/sage/graphs/traversals.pyx
Labels: t: bug, s: positive review, c: graph theory

#39936 update givaro to 4.2.1
  build/pkgs/givaro/checksums.ini
  build/pkgs/givaro/package-version.txt
  build/pkgs/givaro/patches/197.patch
  build/pkgs/givaro/patches/218.patch
  build/pkgs/givaro/patches/226.patch
Labels: s: positive review

#39939 Add sphinx-copybutton to dependency of sage-docbuild
  pkgs/sage-docbuild/pyproject.toml
Labels: s: positive review

#39942 Fix various issues with CI
  .github/workflows/ci-linux-incremental.yml
  .github/workflows/ci-macos.yml
  .github/workflows/docker.yml
  .github/workflows/macos.yml
Labels: s: positive review

#39946 add parameter immutable to methods in `src/sage/graphs/graph_decompositions/graph_products.pyx`
  src/sage/graphs/graph_decompositions/graph_products.pyx
Labels: s: positive review, c: graph theory

#39954 Meson: automatically install into venv if activated
  meson.build
  src/doc/en/installation/meson.rst
Labels: s: positive review

#39958 some care for unused variables in rings/polynomial/ pyx files
  src/sage/rings/polynomial/hilbert.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal_libsingular.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/ore_polynomial_element.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_field.pyx
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
Labels: s: positive review

#39962 Docs: Migrate developer walkthrough to Meson
  src/doc/en/developer/git_basic.rst
  src/doc/en/developer/review.rst
  src/doc/en/developer/walkthrough.rst
  src/doc/en/installation/binary.rst
  src/doc/en/installation/index.rst
  src/doc/en/installation/linux.rst
  src/doc/en/installation/source.rst
Labels: s: positive review

#39963 Add offset argument to diagonal method
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#39965 Modified iterator & counter type from int to Py_ssize_t throughout Matrix class
  src/sage/matrix/args.pyx
  src/sage/matrix/echelon_matrix.pyx
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_mpolynomial_dense.pyx
  src/sage/matrix/matrix_rational_dense.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
  src/sage/matrix/matrix_sparse.pyx
Labels: s: positive review, c: linear algebra, c: cython

#39968 fix again the pycodestyle linter
  src/sage/combinat/sf/kfpoly.py
  src/sage/schemes/elliptic_curves/addition_formulas_ring.py
Labels: s: positive review

#39969 Replace conda with mamba for consistency
  src/doc/en/installation/meson.rst
Labels: s: positive review

#39970 convert between two implementations of fin-dim algebras
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra.py
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_element.pxd
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra_element.pyx
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/finite_dimensional_semisimple_algebras_with_basis.py
  src/sage/categories/magmatic_algebras.py
  src/sage/categories/modules_with_basis.py
Labels: s: positive review

#39971 micro details in pyx files in matroids
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
Labels: s: positive review

#39972 some fixes for ruff C4
  src/sage/algebras/free_algebra.py
  src/sage/combinat/root_system/ambient_space.py
  src/sage/combinat/root_system/cartan_type.py
  src/sage/combinat/root_system/type_folded.py
  src/sage/combinat/root_system/type_reducible.py
  src/sage/combinat/root_system/weight_lattice_realizations.py
  src/sage/combinat/similarity_class_type.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/crypto/mq/sr.py
  src/sage/manifolds/utilities.py
  src/sage/matroids/chow_ring_ideal.py
  src/sage/misc/package_dir.py
  src/sage/rings/species.py
Labels: s: positive review

#39976 fix e_antic patch header
  build/pkgs/e_antic/patches/gmp-header.patch
Labels: s: positive review

#39982 Implement conversion of log(2) to Giac
  src/sage/symbolic/constants.py
Labels: s: positive review

#39987 add some typing annotations in modular folder
  src/sage/modular/abvar/abvar.py
  src/sage/modular/abvar/cuspidal_subgroup.py
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/abvar/morphism.py
  src/sage/modular/arithgroup/arithgroup_perm.py
  src/sage/modular/arithgroup/congroup_gamma0.py
  src/sage/modular/arithgroup/congroup_gamma1.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/modular/arithgroup/congroup_generic.py
  src/sage/modular/arithgroup/congroup_sl2z.py
  src/sage/modular/btquotients/btquotient.py
  src/sage/modular/btquotients/pautomorphicform.py
  src/sage/modular/cusps.py
  src/sage/modular/cusps_nf.py
  src/sage/modular/dirichlet.py
  src/sage/modular/drinfeld_modform/element.py
  src/sage/modular/hecke/algebra.py
  src/sage/modular/hecke/ambient_module.py
  src/sage/modular/hecke/module.py
  src/sage/modular/hecke/submodule.py
  src/sage/modular/local_comp/local_comp.py
  src/sage/modular/local_comp/type_space.py
  src/sage/modular/modform/ambient.py
  src/sage/modular/modform/cuspidal_submodule.py
  src/sage/modular/modform/element.py
  src/sage/modular/modform/space.py
  src/sage/modular/modform_hecketriangle/abstract_ring.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/graded_ring_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py
  src/sage/modular/modform_hecketriangle/hecke_triangle_groups.py
  src/sage/modular/modform_hecketriangle/readme.py
  src/sage/modular/modsym/ambient.py
  src/sage/modular/modsym/boundary.py
  src/sage/modular/modsym/space.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/overconvergent/hecke_series.py
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/modular/pollack_stevens/distributions.py
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/modular/pollack_stevens/modsym.py
  src/sage/modular/quasimodform/element.py
Labels: s: positive review, c: modular forms

#39989 Refactor imports in PoorManMap and Sequence classes
  src/sage/categories/poor_man_map.py
  src/sage/structure/sequence.py
Labels: s: positive review

#39994 typing annotation for is_something in modules/
  src/sage/modules/fg_pid/fgp_module.py
  src/sage/modules/filtered_vector_space.py
  src/sage/modules/fp_graded/free_module.py
  src/sage/modules/fp_graded/module.py
  src/sage/modules/fp_graded/morphism.py
  src/sage/modules/fp_graded/steenrod/morphism.py
  src/sage/modules/free_module.py
  src/sage/modules/free_module_element.pyx
  src/sage/modules/free_module_integer.py
  src/sage/modules/free_module_morphism.py
  src/sage/modules/free_quadratic_module_integer_symmetric.py
  src/sage/modules/matrix_morphism.py
  src/sage/modules/multi_filtered_vector_space.py
  src/sage/modules/ore_module.py
  src/sage/modules/ore_module_element.py
  src/sage/modules/ore_module_morphism.py
  src/sage/modules/torsion_quadratic_module.py
  src/sage/modules/vector_space_morphism.py
  src/sage/modules/with_basis/subquotient.py
Labels: s: positive review
