Repository sagemath/sage, pull requests merged in 2025-06, with the labels that each got.

#39726 Optimize AdditiveMonoids sum() method
  src/sage/arith/misc.py
  src/sage/categories/additive_monoids.py
  src/sage/misc/misc_c.pyx
Labels: s: positive review

#39918 add add_entry and anti_restrict methods to SkewTableau
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/tableau.py
Labels: s: positive review

#39993 Update conda lock files
  .devcontainer/onCreate-conda.sh
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.12-linux-aarch64.yml
  environment-3.12-linux.yml
  environment-3.12-macos-x86_64.yml
  environment-3.12-macos.yml
  src/sage/doctest/parsing.py
  tools/update-conda.py
Labels: s: positive review

#40034 Clean affine permutation
  src/sage/combinat/affine_permutation.py
Labels: s: positive review, c: combinatorics, c: group theory

#40080 cleanup in number_field.py
  src/sage/rings/number_field/number_field.py
Labels: s: positive review, c: number fields

#40093 Jacobi theta functions implemented as lazy series
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
Labels: t: enhancement, s: positive review, c: number theory, c: algebra

#40094 msolve tarball got ./configure - sha*s are changed
  build/pkgs/msolve/checksums.ini
Labels: s: positive review, c: packages: optional

#40107 Add retry mechanism for Conda environment setup in CI workflow
  .github/workflows/ci-meson.yml
Labels: s: positive review

#40114 add weighted cycle enumeration in digraph
  src/sage/graphs/digraph.py
Labels: s: positive review, c: graph theory

#40119 cli: restore ability to run a file from the command line
  src/sage/cli/__init__.py
  src/sage/cli/options.py
  src/sage/cli/run_file_cmd.py
Labels: s: positive review

#40123 adding typing annotations on many has_* methods
  src/sage/algebras/affine_nil_temperley_lieb.py
  src/sage/categories/algebras.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/examples/finite_coxeter_groups.py
  src/sage/categories/examples/finite_weyl_groups.py
  src/sage/combinat/colored_permutations.py
  src/sage/combinat/fully_commutative_elements.py
  src/sage/combinat/permutation.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/root_system/root_lattice_realizations.py
  src/sage/combinat/root_system/type_super_A.py
  src/sage/combinat/root_system/weyl_group.py
  src/sage/crypto/boolean_function.pyx
  src/sage/crypto/sbox.pyx
  src/sage/crypto/util.py
  src/sage/databases/conway.py
  src/sage/doctest/external.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/polyhedron/base_ZZ.py
  src/sage/geometry/polyhedron/ppl_lattice_polytope.py
  src/sage/graphs/dot2tex_utils.py
  src/sage/graphs/graph_latex.py
  src/sage/groups/generic.py
  src/sage/groups/matrix_gps/coxeter_group.py
  src/sage/groups/perm_gps/permgroup_element.pyx
  src/sage/libs/coxeter3/coxeter_group.py
  src/sage/manifolds/manifold.py
  src/sage/manifolds/subset.py
  src/sage/manifolds/vector_bundle.py
  src/sage/misc/sage_ostools.pyx
  src/sage/modular/modform/element.py
  src/sage/modular/modform/space.py
  src/sage/modular/modform_hecketriangle/abstract_ring.py
  src/sage/modules/fg_pid/fgp_module.py
  src/sage/modules/fp_graded/free_module.py
  src/sage/plot/plot3d/index_face_set.pyx
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/quadratic_forms/quadratic_form__equivalence_testing.py
  src/sage/repl/ipython_kernel/install.py
  src/sage/rings/polynomial/real_roots.pyx
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
  src/sage/sets/family.pyx
  src/sage/sets/set.py
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/relation.py
  src/sage_setup/util.py
Labels: s: positive review

#40124 Update Meson and Conda install instructions
  .devcontainer/onCreate-meson.sh
  .github/workflows/ci.yml
  .vscode/settings.json
  src/doc/en/installation/conda.rst
  src/doc/en/installation/meson.rst
Labels: s: positive review

#40125 Fix superscript for 2^{32} in prime_pi.pyx
  src/sage/functions/prime_pi.pyx
Labels: s: positive review

#40126 Simplify QuiverRep_generic.linear_combination_of_basis method
  src/sage/quivers/representation.py
Labels: s: positive review

#40132 update m4ri to gcc-15-supporting version
  build/pkgs/m4ri/checksums.ini
  build/pkgs/m4ri/package-version.txt
  build/pkgs/m4ri/spkg-configure.m4
  build/pkgs/m4rie/checksums.ini
  build/pkgs/m4rie/package-version.txt
  build/pkgs/m4rie/patches/use_AM_LDLFAGS.patch
Labels: c: packages: standard, s: positive review, p: blocker / 1

#40138 update primecount(py) to the latest versions
  build/pkgs/primecount/checksums.ini
  build/pkgs/primecount/package-version.txt
  build/pkgs/primecountpy/checksums.ini
  build/pkgs/primecountpy/package-version.txt
  build/pkgs/primecountpy/version_requirements.txt
Labels: c: packages: standard, s: positive review

#40140 move some methods to the category of fields
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/fields.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: categories

#40145 add simple cycle enumeration by k shortest simple path algorithm
  src/sage/graphs/digraph.py
Labels: s: positive review, c: graph theory

#40148 fixing a large lot of typos
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/combinat/abstract_tree.py
  src/sage/combinat/combinat.py
  src/sage/combinat/diagram.py
  src/sage/combinat/free_module.py
  src/sage/combinat/fully_commutative_elements.py
  src/sage/combinat/matrices/hadamard_matrix.py
  src/sage/combinat/nu_dyck_word.py
  src/sage/combinat/symmetric_group_algebra.py
  src/sage/data_structures/blas_dict.pyx
  src/sage/databases/cubic_hecke_db.py
  src/sage/databases/knotinfo_db.py
  src/sage/doctest/__main__.py
  src/sage/doctest/parsing.py
  src/sage/ext_data/pari/dokchitser/computel.gp
  src/sage/ext_data/pari/dokchitser/computel.gp.template
  src/sage/features/latte.py
  src/sage/functions/orthogonal_polys.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/geometry/polyhedron/base4.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/face_iterator.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pxd
  src/sage/geometry/polyhedron/combinatorial_polyhedron/polyhedron_face_lattice.pyx
  src/sage/geometry/polyhedron/library.py
  src/sage/geometry/pseudolines.py
  src/sage/graphs/generators/random.py
  src/sage/graphs/generic_graph.py
  src/sage/graphs/graph_decompositions/slice_decomposition.pyx
  src/sage/graphs/matching_covered_graph.py
  src/sage/groups/matrix_gps/coxeter_group.py
  src/sage/groups/misc_gps/argument_groups.py
  src/sage/groups/misc_gps/imaginary_groups.py
  src/sage/interfaces/ecm.py
  src/sage/interfaces/kenzo.py
  src/sage/interfaces/r.py
  src/sage/knots/link.py
  src/sage/manifolds/differentiable/characteristic_cohomology_class.py
  src/sage/matrix/strassen.pyx
  src/sage/modules/multi_filtered_vector_space.py
  src/sage/plot/bezier_path.py
  src/sage/quadratic_forms/quadratic_form.py
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/function_field/drinfeld_modules/morphism.py
  src/sage/rings/number_field/S_unit_solver.py
  src/sage/rings/padics/padic_template_element.pxi
  src/sage/rings/polynomial/skew_polynomial_finite_order.pyx
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/semirings/tropical_variety.py
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/elliptic_curves/cm.py
  src/sage/schemes/elliptic_curves/ell_finite_field.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/schemes/plane_conics/con_field.py
  src/sage/schemes/projective/proj_bdd_height.py
  src/sage/symbolic/expression_conversions.py
  src/sage/symbolic/ginac/expairseq.cpp
  src/sage/symbolic/ginac/inifcns_nstdsums.cpp
  src/sage/typeset/character_art.py
Labels: s: positive review, c: documentation

#40149 Revision of the Khovanov polynomial
  src/sage/knots/knotinfo.py
  src/sage/knots/link.py
Labels: p: major / 3, t: bug, s: positive review, c: algebraic topology

#40150 significantly faster BQFClassGroupQuotientMorphism
  src/doc/en/reference/references/index.rst
  src/sage/quadratic_forms/bqf_class_group.py
Labels: p: major / 3, s: positive review, c: quadratic forms, t: performance

#40152 Use platformdirs to improve database path handling
  pyproject.toml
  src/sage/env.py
  src/sage/features/databases.py
Labels: s: positive review

#40155 Add check for Arch Linux in configure to recommend meson build
  .github/workflows/ci-linux-incremental.yml
  configure.ac
Labels: s: positive review

#40156 Support Cython 3.1
  pkgs/sagemath-categories/known-test-failures.json
  src/doc/en/reference/cpython/index.rst
  src/sage/algebras/lie_algebras/lie_algebra_element.pyx
  src/sage/combinat/sloane_functions.py
  src/sage/cpython/meson.build
  src/sage/cpython/wrapperdescr.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/misc/c3_controlled.pyx
  src/sage/misc/sageinspect.py
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_element.pyx
  src/sage/structure/richcmp.pxd
  src/sage/structure/richcmp.pyx
Labels: s: positive review

#40157 Add back ubuntu-noble-standard to ci-linux
  .github/workflows/docker.yml
Labels: s: positive review, p: CI Fix

#40159 moved some is_noetherian to categories
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/number_field/order.py
Labels: s: positive review, c: categories

#40160 get rid of CommutativeRing in p-adics
  src/sage/rings/padics/local_generic.py
  src/sage/rings/padics/witt_vector_ring.py
Labels: s: positive review, c: padics

#40162 Add documentation for packaging SageMath downstream
  .vscode/settings.json
  src/doc/en/developer/downstream.rst
  src/doc/en/developer/index.rst
  src/doc/en/developer/packaging_sage_library.rst
Labels: s: positive review

#40170 generic implementation of _element_of_factored_order in finite-fields…
  src/sage/categories/finite_fields.py
Labels: s: positive review, c: finite rings, c: categories

#40171 much faster count for linear intervals
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics, t: performance

#40172 remove old stuff in relint.yml
  src/.relint.yml
Labels: s: positive review

#40173 Trac #40127: Pass factor_on_left in linear_combination
  src/sage/data_structures/blas_dict.pyx
Labels: s: positive review

#39112 check base to decide whether singular supports the ring
  src/sage/rings/polynomial/polynomial_singular_interface.py
Labels: s: positive review

#40225 Complete function prototype gmp for C23 compatibility
  build/pkgs/gmp/patches/gmp-6.3.0-c23.patch
Labels: c: packages: standard, s: positive review

#40226 glpk build fix for gcc-15 (remove duplicate bool typedef)
  build/pkgs/glpk/patches/glpk-5.0-bool.patch
Labels: c: packages: standard, s: positive review

#40227 Upgrade to symmetrica 3.1.0
  build/pkgs/symmetrica/checksums.ini
  build/pkgs/symmetrica/package-version.txt
Labels: c: packages: standard, s: positive review

#40228 Apply gap build fix for gcc-15
  build/pkgs/gap/patches/gap-c23.patch
Labels: c: packages: standard, s: positive review

#40230 Port ECL to C23
  build/pkgs/ecl/patches/1aec8f741f69fd736f020b7fe4d3afc33e60ae6a.patch
  build/pkgs/ecl/patches/f69ded9777c43df20021788d2a4bfc0e9c6b4566.patch
Labels: c: packages: standard, s: positive review

#40234 some details in ternary quadratic forms
  src/sage/quadratic_forms/ternary_qf.py
Labels: s: positive review, c: quadratic forms

#40240 Fix a bug in khuri-makdisi small model
  src/sage/rings/function_field/khuri_makdisi.pyx
Labels: t: bug, s: positive review, c: algebraic geometry

#39854 Typo in doc - missing `\`
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: s: positive review

#39713 Fix AttributeError in PowerSeriesRing for division
  src/sage/categories/commutative_rings.py
  src/sage/categories/fields.py
Labels: s: positive review, c: commutative algebra
