Repository sagemath/sage, pull requests merged in 2025-01, with the labels that each got.

#38946 Allow Cython compilation to open a web browser containing the annotated HTML file
  src/sage/misc/cython.py
  src/sage/repl/ipython_extension.py
Labels: s: positive review, c: cython

#38993 Meson: find more dependencies via pkg-config
  src/meson.build
  src/sage/libs/meson.build
Labels: s: positive review

#39011 Correctly print import errors in `sage.all`
  ruff.toml
  src/sage/repl/ipython_extension.py
Labels: s: positive review

#39099 Fix more ruff issues in ̀ sage.manifolds`
  src/sage/manifolds/calculus_method.py
  src/sage/manifolds/catalog.py
  src/sage/manifolds/chart.py
  src/sage/manifolds/chart_func.py
  src/sage/manifolds/continuous_map.py
  src/sage/manifolds/continuous_map_image.py
  src/sage/manifolds/family.py
  src/sage/manifolds/manifold_homset.py
  src/sage/manifolds/operators.py
Labels: s: positive review, c: manifolds, t: refactoring

#39127 Minor docfix of interpolation() method
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
Labels: s: positive review

#39146 simplify some call of isinstance in pyx files
  src/sage/libs/ntl/ntl_mat_GF2.pyx
  src/sage/libs/ntl/ntl_mat_GF2E.pyx
  src/sage/libs/singular/function.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_gfpn_dense.pyx
  src/sage/numerical/mip.pyx
  src/sage/numerical/sdp.pyx
  src/sage/rings/finite_rings/element_givaro.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/morphism.pyx
  src/sage/rings/padics/common_conversion.pyx
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/polynomial/polynomial_template.pxi
  src/sage/symbolic/ring.pyx
Labels: s: positive review

#39157 Mark artin_symbol doctest as random to avoid failure
  src/sage/rings/number_field/galois_group.py
  src/sage/rings/number_field/number_field.py
  src/sage/rings/number_field/number_field_ideal.py
Labels: s: positive review

#39175 `build/pkgs`: Remove `libtheora`
  build/pkgs/libtheora/SPKG.rst
  build/pkgs/libtheora/checksums.ini
  build/pkgs/libtheora/dependencies
  build/pkgs/libtheora/distros/conda.txt
  build/pkgs/libtheora/distros/fedora.txt
  build/pkgs/libtheora/distros/homebrew.txt
  build/pkgs/libtheora/distros/macports.txt
  build/pkgs/libtheora/distros/opensuse.txt
  build/pkgs/libtheora/distros/repology.txt
  build/pkgs/libtheora/distros/void.txt
  build/pkgs/libtheora/package-version.txt
  build/pkgs/libtheora/spkg-install.in
  build/pkgs/libtheora/type
Labels: c: packages: experimental, s: positive review

#39176 Improve Meson CI workflow
  .github/workflows/ci-meson.yml
Labels: s: positive review

#39178 Fix test failure with giac 1.9.0.998
  src/sage/libs/giac/giac.pyx
Labels: s: positive review

#39179 Fix CremonaDatabase constructor
  src/sage/databases/cremona.py
Labels: s: positive review, s: run conda ci

#39187 Fix tests output for Python 3.13
  src/doc/de/tutorial/tour_linalg.rst
  src/doc/en/tutorial/tour_linalg.rst
  src/doc/fr/tutorial/tour_linalg.rst
  src/doc/ja/tutorial/tour_linalg.rst
  src/doc/pt/tutorial/tour_linalg.rst
  src/doc/ru/tutorial/tour_linalg.rst
  src/sage/categories/map.pyx
  src/sage/misc/bindable_class.py
  src/sage/misc/sagedoc.py
  src/sage/misc/sageinspect.py
  src/sage/modular/modsym/modsym.py
  src/sage/repl/attach.py
  src/sage/repl/rich_output/pretty_print.py
Labels: s: positive review

#39190 Update the copyright year in README.md
  README.md
Labels: s: positive review

#39193 Some improvements to findstat._submit
  src/sage/databases/findstat.py
Labels: s: positive review

#39194 Reimplement release creation workflow
  .github/workflows/dist.yml
Labels: s: positive review

#39206 Pytest: Improve doctest integration
  .gitignore
  .vscode/settings.json
  build/pkgs/sagemath_doc_html/dependencies
  conftest.py
  pyproject.toml
  src/conftest.py
  src/sage/doctest/forker.py
  src/sage/repl/rich_output/display_manager.py
  src/sage/repl/user_globals.py
  src/tox.ini
Labels: s: positive review

#39209 Fix docstring formatting to use raw string literals in multiple files
  src/sage/algebras/free_algebra_quotient_element.py
  src/sage/algebras/lie_algebras/bgg_dual_module.py
  src/sage/algebras/steenrod/steenrod_algebra_misc.py
  src/sage/misc/inline_fortran.py
Labels: s: positive review

#39210 Switch devcontainer to use meson
  .devcontainer/onCreate-conda.sh
Labels: s: positive review

#39217 improve graph traversal methods
  src/sage/graphs/traversals.pyx
Labels: s: positive review, c: graph theory

#39219 Faster conversion from numpy array to matrix mod 2
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/modules/numpy_util.pxd
  src/sage/modules/numpy_util.pyx
Labels: s: positive review, c: interfaces

#39222 Remove outdated note from docstring of `cliques_maximal`
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#39227 deprecate fully the auld class IntegralDomain
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring

#39229 fixing pycodestyle E222 in many cython files
  src/sage/coding/binary_code.pyx
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/evenly_distributed_sets.pyx
  src/sage/combinat/designs/subhypergraph_search.pyx
  src/sage/combinat/integer_lists/base.pyx
  src/sage/games/sudoku_backtrack.pyx
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
  src/sage/groups/perm_gps/partn_ref/canonical_augmentation.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/double_coset.pyx
  src/sage/libs/flint/fq_nmod_mpoly.pxd
  src/sage/libs/linbox/fflas.pxd
  src/sage/libs/singular/decl.pxd
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/polynomial.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/libs/singular/singular.pyx
  src/sage/libs/symmetrica/symmetrica.pxi
  src/sage/matrix/args.pxd
  src/sage/matrix/matrix0.pyx
  src/sage/matrix/matrix_gf2e_dense.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/misc.pyx
  src/sage/modules/vector_mod2_dense.pyx
  src/sage/modules/vector_modn_dense.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/plot/plot3d/base.pyx
  src/sage/rings/complex_interval.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
  src/sage/rings/puiseux_series_ring_element.pyx
  src/sage/stats/hmm/chmm.pyx
  src/sage/stats/time_series.pyx
Labels: s: positive review, t: refactoring

#39230 refresh MacMahon Omega file
  src/sage/rings/polynomial/omega.py
Labels: s: positive review, c: commutative algebra

#39231 fix and activate some checks in ruff-minimal
  src/sage/combinat/matrices/latin.py
  src/sage/doctest/control.py
  src/sage/functions/airy.py
  src/sage/functions/log.py
  src/sage/graphs/generators/random.py
  src/sage/misc/package_dir.py
  src/sage/modules/with_basis/representation.py
  src/sage/quadratic_forms/quadratic_form__ternary_Tornaria.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/tests/arxiv_0812_2725.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#39232 minor tweaks in Ore polynomials
  src/sage/rings/polynomial/ore_function_element.py
  src/sage/rings/polynomial/ore_function_field.py
  src/sage/rings/polynomial/ore_polynomial_ring.py
Labels: s: positive review, t: refactoring

#39235 fixing a few typos
  docker/.gitpod.Dockerfile
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
  src/sage/categories/finite_enumerated_sets.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/matrices/hadamard_matrix.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/regular_sequence.py
  src/sage/combinat/specht_module.py
  src/sage/combinat/t_sequences.py
  src/sage/ext_data/valgrind/pyalloc.supp
  src/sage/geometry/polyhedral_complex.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/graphs/matching_covered_graph.py
  src/sage/interfaces/mathics.py
  src/sage/knots/knotinfo.py
  src/sage/matrix/matrix2.pyx
  src/sage/modules/with_basis/cell_module.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/valuation/valuation.py
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/topology/cell_complex.py
Labels: s: positive review, t: refactoring

#39236 minor details in modular symbols / boundary
  src/sage/modular/modsym/boundary.py
Labels: s: positive review, c: modular forms

#39302 adding the category keyword to padic rings and fields classes
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/generic_nodes.py
  src/sage/rings/padics/padic_base_generic.py
  src/sage/rings/padics/padic_base_leaves.py
Labels: s: positive review, t: refactoring

#39306 simplify many range(0,n) to range(n)
  src/sage/calculus/desolvers.py
  src/sage/coding/grs_code.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/coding/guruswami_sudan/interpolation.py
  src/sage/crypto/mq/sr.py
  src/sage/data_structures/stream.py
  src/sage/dynamics/arithmetic_dynamics/affine_ds.py
  src/sage/dynamics/arithmetic_dynamics/endPN_minimal_model.py
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/geometry/hyperplane_arrangement/library.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/geometry/riemannian_manifolds/parametrized_surface3d.py
  src/sage/geometry/triangulation/base.pyx
  src/sage/interfaces/phc.py
  src/sage/interfaces/r.py
  src/sage/knots/knot.py
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/structure/global_options.py
  src/sage/tensor/modules/free_module_tensor.py
  src/sage/topology/delta_complex.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review, t: refactoring

#39325 [DOC] Allow Sphinx PDF build to reflow long decimal expansions in code-blocks to avoid them extending beyond page limits
  src/sage_docbuild/conf.py
Labels: s: positive review

#39332 some changes about dict in combinat (ruff PLC0206)
  src/sage/combinat/binary_recurrence_sequences.py
  src/sage/combinat/chas/wqsym.py
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/difference_family.py
  src/sage/combinat/parallelogram_polyomino.py
  src/sage/combinat/posets/incidence_algebras.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/rigged_configurations/kleber_tree.py
  src/sage/combinat/root_system/weyl_characters.py
  src/sage/combinat/sf/classical.py
  src/sage/combinat/sf/kfpoly.py
  src/sage/combinat/sine_gordon.py
  src/sage/combinat/tableau.py
Labels: s: positive review

#38823 Graph Plotting updates
  src/sage/graphs/graph_plot.py
Labels: s: positive review

#38904 provide a class for partitions with bounded length and minimal part
  src/sage/algebras/quantum_groups/fock_space.py
  src/sage/combinat/partition.py
Labels: t: enhancement, s: positive review, c: combinatorics

#38965 adding an example of semiring
  src/doc/en/reference/categories/index.rst
  src/sage/categories/examples/meson.build
  src/sage/categories/examples/semirings.py
  src/sage/categories/semirings.py
Labels: s: positive review, c: algebra, c: categories

#39008 Add Meson-specific settings to vscode settings
  .vscode/settings.json
Labels: s: positive review

#39123 change ore_algebra package to latest version
  build/pkgs/ore_algebra/requirements.txt
Labels: s: positive review, c: packages: optional

#39147 Fix doctesting with Python 3.13
  src/sage/doctest/forker.py
Labels: s: positive review

#39151 add parameter `forbidden_vertices` to some connectivity methods
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39153 Mark several tests as random to avoid test failure
  src/sage/rings/number_field/number_field.py
  src/sage/rings/qqbar.py
Labels: s: positive review

#39164 Update conda to use Python 3.12, drop 3.9 and 3.10
  .github/workflows/ci-conda.yml
  .github/workflows/ci-meson.yml
  .gitignore
  Makefile
  bootstrap
  environment-3.10-linux-aarch64.yml
  environment-3.10-linux.yml
  environment-3.10-macos.yml
  environment-3.11-linux-aarch64.yml
  environment-3.11-linux.yml
  environment-3.11-macos-x86_64.yml
  environment-3.11-macos.yml
  environment-3.12-linux-aarch64.yml
  environment-3.12-linux.yml
  environment-3.12-macos-x86_64.yml
  environment-3.12-macos.yml
  environment-3.9-macos-x86_64.yml
  pyproject.toml
  tools/update-conda.py
Labels: s: positive review, c: distribution, c: build: configure

#39168 Addition of Kähler algebras as a category
  src/doc/en/reference/categories/index.rst
  src/sage/categories/category_types.py
  src/sage/categories/graded_algebras_with_basis.py
  src/sage/categories/kahler_algebras.py
  src/sage/categories/meson.build
  src/sage/matroids/chow_ring.py
  src/sage/matroids/chow_ring_ideal.py
Labels: s: positive review, c: algebra, c: categories

#39182 Define __iter__ method in iterator types
  src/sage/matroids/extension.pyx
  src/sage/matroids/set_system.pyx
Labels: s: positive review

#39184 Refactor produce_latex_macro
  src/sage/misc/latex_macros.py
Labels: s: positive review

#39185 Fix find_replacements with Python 3.13
  src/sage/misc/replace_dot_all.py
Labels: s: positive review

#39188 Declare Python 3.13 as supported in sagelib
  pyproject.toml
  src/setup.cfg.m4
Labels: s: positive review

#39201 Fix `spyx_tmp()` cleanup.
  src/sage/misc/temporary_file.py
Labels: s: positive review

#39220 some care in `src/sage/graphs/comparability.pyx`
  src/sage/graphs/comparability.pyx
Labels: s: positive review, c: graph theory

#39228 faster bidirectional dijkstra using pairing heap
  src/sage/data_structures/pairing_heap.pxd
  src/sage/graphs/base/c_graph.pyx
  src/sage/graphs/generic_graph.py
  src/sage/graphs/path_enumeration.pyx
Labels: s: positive review, c: graph theory

#39233 add some typing annotations to gens methods (-> tuple)
  src/sage/rings/algebraic_closure_finite_field.py
  src/sage/rings/asymptotic/growth_group.py
  src/sage/rings/asymptotic/growth_group_cartesian.py
  src/sage/rings/derivation.py
  src/sage/rings/function_field/ideal.py
  src/sage/rings/function_field/ideal_polymod.py
  src/sage/rings/function_field/ideal_rational.py
  src/sage/rings/ideal.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/localization.py
  src/sage/rings/number_field/class_group.py
  src/sage/rings/number_field/number_field_ideal.py
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/number_field/order_ideal.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
  src/sage/rings/polynomial/laurent_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/rings/qqbar.py
  src/sage/rings/rational_field.py
  src/sage/rings/semirings/tropical_mpolynomial.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/tate_algebra.py
  src/sage/rings/valuation/value_group.py
Labels: s: positive review, c: algebra

#39252 minor annotation details in posets to please mypy
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/incidence_algebras.py
  src/sage/combinat/posets/linear_extensions.py
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#39253 some type annotations in modular folder
  src/sage/modular/cusps.py
  src/sage/modular/cusps_nf.py
  src/sage/modular/dims.py
  src/sage/modular/dirichlet.py
  src/sage/modular/etaproducts.py
  src/sage/modular/hypergeometric_motive.py
  src/sage/modular/multiple_zeta.py
Labels: s: positive review, c: modular forms

#39261 Fix tests with scipy 1.15
  src/sage/functions/special.py
  src/sage/matrix/matrix2.pyx
Labels: s: positive review

#39263 Remove old deprecations in `algebras` and `categories`
  src/sage/algebras/algebra.py
  src/sage/algebras/meson.build
  src/sage/categories/modules.py
Labels: s: positive review

#39264 add parameter immutable to generators in `sage/graphs/digraph_generators.py` (part 1)
  src/sage/graphs/digraph_generators.py
Labels: s: positive review, c: graph theory

#39268 Upgrade dependency requirements in accordance with Spec 0
  pyproject.toml
Labels: s: positive review

#39271 return correct error message when trying to add/delete vertex/edge from a static graph
  src/sage/graphs/base/static_sparse_backend.pyx
Labels: t: bug, s: positive review, c: graph theory

#39277 Fix import duplication in `sage.rings.all`
  src/sage/rings/all.py
  src/sage/rings/all__sagemath_categories.py
  src/sage/rings/meson.build
Labels: s: positive review

#39278 Meson: build groups even without gap
  src/sage/groups/meson.build
Labels: s: positive review

#39281 fix and activate the ruff check for F811
  src/sage/algebras/weyl_algebra.py
  src/sage/categories/basic.py
  src/sage/coding/guruswami_sudan/gs_decoder.py
  src/sage/modules/with_basis/representation.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/polynomial/polynomial_ring.py
  src/sage/schemes/curves/affine_curve.py
  src/sage/schemes/elliptic_curves/ell_point.py
  src/sage/symbolic/expression_conversions.py
  src/tox.ini
Labels: s: positive review

#39282 Fix tests for Python 3.13
  src/sage/repl/ipython_extension.py
Labels: s: positive review

#39284 Remove failing modular ci tests
  .github/workflows/build.yml
Labels: s: positive review, p: CI Fix

#39288 Fix the new release workflow by escaping special characters
  .github/workflows/dist.yml
Labels: s: positive review, p: blocker / 1

#39291 Workaround to allow flint to be compiled with numpy 2
  src/sage/libs/flint/flint_wrap.h
  src/sage_setup/autogen/flint/templates/flint_wrap.h.template
Labels: s: positive review

#39293 Fix segmentation fault in singular interface code
  src/sage/libs/singular/singular.pyx
Labels: s: positive review

#39298 small cleanup in tropical files
  src/sage/rings/semirings/tropical_mpolynomial.py
  src/sage/rings/semirings/tropical_polynomial.py
  src/sage/rings/semirings/tropical_variety.py
Labels: s: positive review

#39301 Using a new functions in libbraiding in zariski_vankampen
  src/sage/geometry/hyperplane_arrangement/ordered_arrangement.py
  src/sage/schemes/curves/plane_curve_arrangement.py
  src/sage/schemes/curves/projective_curve.py
  src/sage/schemes/curves/zariski_vankampen.py
Labels: t: enhancement, s: positive review, c: packages: optional

#39303 let the categories handle "is_commutative" for rings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/algebras/clifford_algebra.py
  src/sage/algebras/finite_dimensional_algebras/finite_dimensional_algebra.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/categories/commutative_rings.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/lie_algebras.py
  src/sage/categories/magmas.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/real_double.pyx
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring

#39305 fixing some ruff PLR warnings
  src/sage/algebras/hecke_algebras/cubic_hecke_algebra.py
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
  src/sage/categories/affine_weyl_groups.py
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/necklace.py
  src/sage/combinat/non_decreasing_parking_function.py
  src/sage/combinat/tableau.py
  src/sage/combinat/tableau_tuple.py
  src/sage/combinat/words/suffix_trees.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/graphs/bipartite_graph.py
  src/sage/graphs/matching_covered_graph.py
  src/sage/groups/cubic_braid.py
  src/sage/interfaces/octave.py
  src/sage/lfunctions/dokchitser.py
  src/sage/matrix/operation_table.py
  src/sage/matroids/utilities.py
  src/sage/plot/hyperbolic_arc.py
  src/sage/quadratic_forms/quadratic_form__neighbors.py
  src/sage/rings/lazy_series.py
  src/sage/rings/tests.py
Labels: s: positive review, t: refactoring

#39312 use memory allocator in `sage/coding/binary_code.pyx`
  src/sage/coding/binary_code.pxd
  src/sage/coding/binary_code.pyx
Labels: s: positive review, c: coding theory

#39315 partial pep8 cleanup in Lie conformal algebras
  src/sage/algebras/lie_conformal_algebras/abelian_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/affine_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/bosonic_ghosts_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/fermionic_ghosts_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/free_bosons_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/free_fermions_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/freely_generated_lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra.py
  src/sage/algebras/lie_conformal_algebras/lie_conformal_algebra_with_structure_coefs.py
Labels: s: positive review, t: refactoring

#39316 use memory allocator in `sage/combinat/designs/`
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/evenly_distributed_sets.pyx
Labels: s: positive review, c: combinatorial designs

#39322 Implement the chi function in sage.crypto.sboxes
  src/sage/crypto/sboxes.py
Labels: s: positive review

#39324 less use of ParentWithGens
  src/sage/rings/fraction_field_element.pyx
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/quotient_ring.py
  src/sage/rings/ring.pyx
  src/sage/structure/element.pyx
Labels: s: positive review, t: refactoring

#39330 fix a bunch of typos and add some spaces after commas
  src/sage/algebras/fusion_rings/f_matrix.py
  src/sage/algebras/hecke_algebras/cubic_hecke_algebra.py
  src/sage/homology/homology_vector_space_with_basis.py
  src/sage/rings/complex_interval.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/schemes/elliptic_curves/ell_number_field.py
Labels: s: positive review, c: documentation, t: refactoring

#38924 avoid unnecessary divisions and calls to gcd
  src/sage/arith/misc.py
  src/sage/categories/fields.py
  src/sage/categories/unique_factorization_domains.py
  src/sage/dynamics/arithmetic_dynamics/berkovich_ds.py
  src/sage/schemes/affine/affine_morphism.py
Labels: s: positive review, c: number theory

#39013 Replace `os.killpg` on Windows
  src/sage/interfaces/quit.py
Labels: s: positive review, c: build

#39018 Fix Singular polynomial comparison
  src/doc/de/tutorial/tour_advanced.rst
  src/doc/en/tutorial/tour_advanced.rst
  src/doc/fr/tutorial/tour_advanced.rst
  src/doc/ja/tutorial/tour_advanced.rst
  src/doc/pt/tutorial/tour_advanced.rst
  src/doc/ru/tutorial/tour_advanced.rst
  src/sage/algebras/hecke_algebras/ariki_koike_algebra.py
  src/sage/algebras/hecke_algebras/cubic_hecke_algebra.py
  src/sage/algebras/hecke_algebras/cubic_hecke_base_ring.py
  src/sage/algebras/iwahori_hecke_algebra.py
  src/sage/algebras/lie_algebras/examples.py
  src/sage/calculus/wester.py
  src/sage/categories/coxeter_group_algebras.py
  src/sage/combinat/root_system/hecke_algebra_representation.py
  src/sage/combinat/root_system/non_symmetric_macdonald_polynomials.py
  src/sage/combinat/root_system/root_lattice_realization_algebras.py
  src/sage/combinat/sf/hall_littlewood.py
  src/sage/combinat/sf/llt.py
  src/sage/combinat/sf/macdonald.py
  src/sage/combinat/sf/sfa.py
  src/sage/databases/cubic_hecke_db.py
  src/sage/libs/singular/decl.pxd
  src/sage/libs/singular/polynomial.pyx
  src/sage/rings/invariants/invariant_theory.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/localization.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/symmetric_ideal.py
  src/sage/rings/polynomial/toy_variety.py
  src/sage/schemes/curves/point.py
  src/sage/tests/books/computational-mathematics-with-sagemath/mpoly_doctest.py
Labels: s: positive review

#39124 unify and simplify orientation methods
  src/sage/graphs/graph.py
  src/sage/graphs/orientations.py
Labels: s: positive review, c: graph theory

#39138 Fix comment on ginac NegInfinity constant
  src/sage/symbolic/ginac/infinity.cpp
Labels: s: positive review

#39155 Salvage work on gammoids
  src/doc/en/reference/matroids/index.rst
  src/doc/en/reference/references/index.rst
  src/sage/matroids/basis_matroid.pyx
  src/sage/matroids/circuit_closures_matroid.pyx
  src/sage/matroids/circuits_matroid.pyx
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/extension.pyx
  src/sage/matroids/flats_matroid.pyx
  src/sage/matroids/gammoid.py
  src/sage/matroids/graphic_matroid.pyx
  src/sage/matroids/lean_matrix.pyx
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/meson.build
  src/sage/matroids/minor_matroid.py
  src/sage/matroids/rank_matroid.py
  src/sage/matroids/transversal_matroid.pxd
  src/sage/matroids/transversal_matroid.pyx
  src/sage/matroids/union_matroid.pyx
  src/sage/matroids/unpickling.pyx
Labels: t: feature, s: positive review, c: matroid theory

#39223 avoid some conversions to `short_digraph` in `distances_all_pairs.pyx`
  src/sage/graphs/distances_all_pairs.pyx
Labels: s: positive review, c: graph theory

#39226 Unpoison `http_proxy` for optional pkgs
  build/bin/sage-spkg
  build/pkgs/ccache/spkg-install.in
Labels: s: positive review, c: build, c: packages: optional

#39247 add parameter immutable to generators in `src/sage/graphs/graph_generators.py`
  src/sage/graphs/graph_generators.py
Labels: s: positive review, c: graph theory

#39254 some details in string_ops
  src/sage/monoids/string_ops.py
Labels: s: positive review, t: refactoring

#39300 faster method `__mul__` for graphs
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39304 ignoring one more ruff check
  src/tox.ini
Labels: s: positive review, p: CI Fix

#39310 expand and explain doctest of _preprocess_intertwining_relations
  src/sage/combinat/bijectionist.py
Labels: s: positive review

#39311 move krull_dimension to the category framework
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/commutative_rings.py
  src/sage/categories/dedekind_domains.py
  src/sage/categories/fields.py
  src/sage/misc/functional.py
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring

#39313 Bijectionist/improve init
  src/sage/combinat/bijectionist.py
Labels: s: positive review

#39317 add parameter immutable to all methods in `sage/graphs/generators/basic.py`
  src/sage/graphs/generators/basic.py
Labels: s: positive review, c: graph theory

#39326 [DOC] src/doc/fr/tutorial/conf.py: remove obsolete latex work-around
  src/doc/fr/a_tour_of_sage/conf.py
  src/doc/fr/tutorial/conf.py
Labels: s: positive review

#39327 totally trivial space adding ticket
  src/sage/calculus/interpolators.pyx
  src/sage/calculus/riemann.pyx
  src/sage/categories/homset.py
  src/sage/coding/binary_code.pyx
  src/sage/combinat/crystals/pbw_datum.pyx
  src/sage/combinat/crystals/spins.pyx
  src/sage/combinat/permutation_cython.pyx
  src/sage/combinat/rooted_tree.py
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/geometry/integral_points_generic_dense.pyx
  src/sage/geometry/integral_points_integer_dense.pyx
  src/sage/graphs/base/c_graph.pxd
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/graph_database.py
  src/sage/groups/perm_gps/partn_ref2/refinement_generic.pyx
  src/sage/libs/sirocco.pyx
  src/sage/modular/modform/space.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modules/free_module_element.pyx
  src/sage/quadratic_forms/quadratic_form__mass__Conway_Sloane_masses.py
  src/sage/rings/finite_rings/element_givaro.pxd
  src/sage/rings/number_field/number_field_rel.py
  src/sage/rings/padics/factory.py
  src/sage/rings/padics/padic_generic.py
  src/sage/rings/padics/pow_computer_ext.pxd
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/elliptic_curves/mod_sym_num.pyx
  src/sage/schemes/generic/morphism.py
  src/sage/structure/category_object.pyx
  src/sage/topology/cubical_complex.py
Labels: s: positive review

#39335 fixes ruff PLC in categories
  src/sage/categories/finite_complex_reflection_groups.py
  src/sage/categories/loop_crystals.py
  src/sage/categories/simplicial_sets.py
Labels: s: positive review

#39337 a few fixes for ruff PLC
  src/sage/interfaces/lie.py
  src/sage/knots/free_knotinfo_monoid.py
  src/sage/knots/link.py
  src/sage/misc/sage_input.py
  src/sage/modular/modsym/relation_matrix.py
  src/sage/monoids/string_monoid_element.py
  src/sage/plot/colors.py
  src/sage/plot/primitive.py
Labels: s: positive review

#39339 fixing most of ruff-minimal outside of src/sage
  build/sage_bootstrap/download/mirror_list.py
  pkgs/sage-conf_conda/setup.py
  pkgs/sage-conf_pypi/setup.py
  pkgs/sage-sws2rst/sage_sws2rst/worksheet2rst.py
  src/doc/el/a_tour_of_sage/conf.py
  src/doc/en/a_tour_of_sage/conf.py
  src/doc/tr/a_tour_of_sage/conf.py
  src/sage_docbuild/conf.py
  src/sage_setup/autogen/giacpy-mkkeywords.py
  src/setup.py
Labels: s: positive review

#39340 fix pycodestyle E115 and activate this check in the linter
  src/sage/arith/misc.py
  src/sage/categories/modules_with_basis.py
  src/sage/coding/self_dual_codes.py
  src/sage/geometry/hyperbolic_space/hyperbolic_coercion.py
  src/sage/manifolds/differentiable/integrated_curve.py
  src/sage/manifolds/differentiable/manifold_homset.py
  src/sage/manifolds/differentiable/tensorfield.py
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/plot/plot.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/generic/homset.py
  src/sage/tensor/modules/format_utilities.py
  src/tox.ini
Labels: s: positive review

#39341 add an iterator over the minimal separators of a graph
  src/doc/en/reference/references/index.rst
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#39342 simplify some .extend in combinat
  src/sage/combinat/designs/bibd.py
  src/sage/combinat/designs/database.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/partition.py
  src/sage/combinat/partition_tuple.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/rigged_configurations/kr_tableaux.py
  src/sage/combinat/root_system/branching_rules.py
  src/sage/combinat/root_system/reflection_group_real.py
  src/sage/combinat/root_system/type_C.py
  src/sage/combinat/root_system/type_D.py
  src/sage/combinat/skew_partition.py
Labels: s: positive review, c: combinatorics

#39343 use Parent in Laurent series
  src/sage/rings/laurent_series_ring.py
Labels: s: positive review, t: refactoring

#39344 Fix broken sat solvers feature tests
  src/sage/features/sat.py
Labels: s: positive review

#39346 some fixes after cython-lint
  src/sage/dynamics/arithmetic_dynamics/projective_ds_helper.pyx
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/interacts/library_cython.pyx
  src/sage/matroids/matroid.pyx
  src/sage/quadratic_forms/ternary.pyx
  src/sage/quivers/algebra_elements.pyx
  src/sage/schemes/elliptic_curves/period_lattice_region.pyx
  src/sage/schemes/toric/divisor_class.pyx
  src/sage/structure/list_clone_demo.pyx
  src/sage/symbolic/pynac_function_impl.pxi
Labels: s: positive review

#39348 fix details in q_numbers
  src/sage/algebras/quantum_groups/q_numbers.py
Labels: s: positive review, c: algebra

#39349 fix bug for zero-dimension Ehrhart polynomial
  src/sage/geometry/polyhedron/base_QQ.py
  src/sage/geometry/polyhedron/base_ZZ.py
Labels: s: positive review, c: geometry

#39354 some fixes for PLR1716
  src/sage/combinat/composition_tableau.py
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/gray_codes.py
  src/sage/combinat/ncsf_qsym/combinatorics.py
  src/sage/combinat/permutation.py
  src/sage/functions/spike_function.py
  src/sage/graphs/graph.py
  src/sage/graphs/graph_latex.py
  src/sage/graphs/isgci.py
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/matrix/symplectic_basis.py
  src/sage/plot/arc.py
  src/sage/rings/number_field/bdd_height.py
  src/sage/schemes/elliptic_curves/ell_field.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
  src/sage/sets/integer_range.py
Labels: s: positive review

#39358 upgrade `igraph` to 0.10.15 and `python_igraph` to 0.11.8
  build/pkgs/igraph/checksums.ini
  build/pkgs/igraph/package-version.txt
  build/pkgs/igraph/spkg-configure.m4
  build/pkgs/python_igraph/checksums.ini
  build/pkgs/python_igraph/package-version.txt
Labels: s: positive review, c: packages: optional, c: graph theory

#39360 doc tweaks in padics
  src/sage/rings/padics/common_conversion.pyx
  src/sage/rings/padics/misc.py
Labels: s: positive review, c: padics

#39367 Shorten pickle for matrix_mod2_dense
  src/sage/matrix/matrix_mod2_dense.pyx
Labels: s: positive review

#39368 fix doctests for singular 4.4.1
  src/doc/de/tutorial/interfaces.rst
  src/doc/en/constructions/algebraic_geometry.rst
  src/doc/en/constructions/rings.rst
  src/doc/en/developer/coding_in_other.rst
  src/doc/en/tutorial/interfaces.rst
  src/doc/fr/tutorial/interfaces.rst
  src/doc/ja/tutorial/interfaces.rst
  src/doc/pt/tutorial/interfaces.rst
  src/doc/ru/tutorial/interfaces.rst
  src/sage/categories/pushout.py
  src/sage/interfaces/expect.py
  src/sage/interfaces/interface.py
  src/sage/interfaces/singular.py
  src/sage/libs/singular/function.pyx
  src/sage/libs/singular/ring.pyx
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/rings/polynomial/polynomial_singular_interface.py
  src/sage/rings/polynomial/term_order.py
  src/sage/rings/quotient_ring.py
  src/sage/rings/quotient_ring_element.py
Labels: s: positive review

#39375 adding some annotations in polyhedral complex
  src/sage/geometry/polyhedral_complex.py
Labels: s: positive review
