Repository sagemath/sage, pull requests merged in 2025-08, with the labels that each got.

#40142 Meson: test archlinux on CI and migrate devcontainer
  .devcontainer/portability-archlinux-latest-minimal/devcontainer.json
  .devcontainer/portability-archlinux-latest-minimal/portability-Dockerfile
  .devcontainer/portability-archlinux-latest-standard/devcontainer.json
  .devcontainer/portability-archlinux-latest-standard/portability-Dockerfile
  .devcontainer/portability-archlinux/Dockerfile
  .devcontainer/portability-archlinux/devcontainer.json
  .github/workflows/ci.yml
  build/pkgs/ecm/distros/arch.txt
  build/pkgs/mpfi/distros/arch.txt
  src/meson.build
Labels: s: positive review

#40641 remove one deprecated method in difference_family
  src/sage/combinat/designs/difference_family.py
Labels: s: positive review

#40642 bump nauty to version 2.9.0
  build/pkgs/nauty/checksums.ini
  build/pkgs/nauty/package-version.txt
Labels: c: packages: standard, s: positive review, c: graph theory

#40644 bump plantri to version 5.5
  build/pkgs/plantri/checksums.ini
  build/pkgs/plantri/package-version.txt
Labels: s: positive review, c: packages: optional, c: graph theory

#40647 remove deprecated method in manifolds/subset
  src/sage/manifolds/subset.py
Labels: s: positive review

#40656 remove deprecated method in matroid.pyx
  src/sage/matroids/matroid.pxd
  src/sage/matroids/matroid.pyx
Labels: s: positive review

#40659 remove 2 deprecated functions in symbolic/
  src/sage/symbolic/expression.pyx
  src/sage/symbolic/ring.pyx
Labels: s: positive review

#40660 remove a deprecated class in structure
  src/sage/structure/coerce_maps.pxd
  src/sage/structure/coerce_maps.pyx
  src/sage/structure/parent.pyx
Labels: s: positive review

#40668 remove some deprecations in plot folder
  src/sage/plot/graphics.py
  src/sage/plot/histogram.py
  src/sage/plot/matrix_plot.py
  src/sage/plot/plot3d/list_plot3d.py
Labels: s: positive review

#40673 bump meataxe to 1.0.2
  build/pkgs/meataxe/checksums.ini
  build/pkgs/meataxe/package-version.txt
Labels: s: positive review

#40651 StandardTableaux_residue passes incorrect args on its super().__init__() call
  src/sage/combinat/tableau_tuple.py
Labels: t: bug, s: positive review, c: combinatorics
