Repository sagemath/sage, pull requests merged in 2025-09, with the labels that each got.

#36773 Raise a power series to a power series
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review, c: combinatorics, c: algebra

#39753 move tree generation methods to `src/sage/graphs/generators/trees.pyx`
  src/doc/en/reference/graphs/index.rst
  src/sage/graphs/generators/families.py
  src/sage/graphs/generators/meson.build
  src/sage/graphs/generators/random.py
  src/sage/graphs/generators/trees.pxd
  src/sage/graphs/generators/trees.pyx
  src/sage/graphs/graph_generators.py
  src/sage/graphs/meson.build
  src/sage/graphs/trees.pyx
Labels: s: positive review, c: graph theory

#39876 Faster implementation of is_invertible() by checking full rank
  src/sage/matrix/matrix_gf2e_dense.pyx
Labels: s: positive review

#40273 Avoid PariError on finite field construction
  src/sage/rings/finite_rings/element_pari_ffelt.pyx
  src/sage/rings/finite_rings/finite_field_pari_ffelt.py
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: finite rings

#40279 Fix RealLiteral to float conversion
  src/sage/rings/real_mpfr.pyx
Labels: s: positive review

#40317 Implement partial integer factorization using flint
  src/sage/arith/misc.py
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/misc/sageinspect.py
  src/sage/rings/factorint_flint.pyx
  src/sage/rings/integer.pyx
Labels: s: positive review

#40370 Interface for Regina (3-manifold topology and normal surface theory)
  build/pkgs/regina/SPKG.rst
  build/pkgs/regina/dependencies
  build/pkgs/regina/requirements.txt
  build/pkgs/regina/spkg-configure.m4
  build/pkgs/regina/type
  src/doc/en/reference/interfaces/index.rst
  src/sage/doctest/external.py
  src/sage/features/interfaces.py
  src/sage/groups/finitely_presented.py
  src/sage/groups/free_group.py
  src/sage/interfaces/all.py
  src/sage/interfaces/meson.build
  src/sage/interfaces/regina.py
  src/sage/knots/link.py
  src/sage/rings/integer.pyx
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/rational.pyx
  src/sage/structure/sage_object.pyx
Labels: s: positive review, c: packages: optional, c: algebraic topology

#40401 Implement Square Roots to FiniteFields Category
  src/sage/categories/commutative_rings.py
  src/sage/categories/finite_fields.py
  src/sage/rings/polynomial/polynomial_quotient_ring.py
  src/sage/structure/element.pyx
Labels: s: positive review, c: number theory, c: finite rings

#40568 fixes in spkg-configure.m4's
  build/pkgs/flint/spkg-configure.m4
  build/pkgs/roman_numerals/SPKG.rst
  build/pkgs/roman_numerals/checksums.ini
  build/pkgs/roman_numerals/dependencies
  build/pkgs/roman_numerals/distros/arch.txt
  build/pkgs/roman_numerals/distros/conda.txt
  build/pkgs/roman_numerals/distros/fedora.txt
  build/pkgs/roman_numerals/distros/freebsd.txt
  build/pkgs/roman_numerals/distros/gentoo.txt
  build/pkgs/roman_numerals/distros/macports.txt
  build/pkgs/roman_numerals/distros/opensuse.txt
  build/pkgs/roman_numerals/package-version.txt
  build/pkgs/roman_numerals/spkg-configure.m4
  build/pkgs/roman_numerals/type
  build/pkgs/roman_numerals/version_requirements.txt
  build/pkgs/roman_numerals_py/spkg-configure.m4
  build/pkgs/sphinx/dependencies
Labels: s: positive review

#40592 Update `uv.lock`
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  build/pkgs/p_group_cohomology/distros/repology.txt
  pyproject.toml
  src/doc/en/developer/tools.rst
  uv.lock
Labels: s: positive review

#40638 Method to add multiples of a matrix row to another, ending at some column index
  src/sage/matrix/matrix0.pxd
  src/sage/matrix/matrix0.pyx
Labels: s: positive review

#40666 is_commutative for coxeter3
  src/sage/categories/coxeter_groups.py
  src/sage/groups/matrix_gps/coxeter_group.py
  src/sage/libs/coxeter3/coxeter.pyx
  src/sage/libs/coxeter3/coxeter_group.py
Labels: s: positive review, c: combinatorics, c: categories

#40672 src/sage/doctest/sources.py: add "long time" for two tests
  src/sage/doctest/sources.py
Labels: s: positive review, p: CI Fix

#40688 check for presense of the patch utility
  configure.ac
Labels: s: positive review, c: build: configure

#39258 Create pyi stub files for cython modules in `misc` and `rings`
  src/sage/misc/abstract_method.pyi
  src/sage/misc/allocator.pyi
  src/sage/misc/binary_tree.pyi
  src/sage/misc/c3.pyi
  src/sage/misc/cachefunc.pyi
  src/sage/misc/callable_dict.pyi
  src/sage/misc/citation.pyi
  src/sage/rings/abc.pyi
  src/sage/rings/bernmm.pyi
  src/sage/rings/bernoulli_mod_p.pyi
  src/sage/rings/complex_arb.pyi
  src/sage/rings/complex_conversion.pyi
  src/sage/rings/complex_double.pyi
  src/sage/rings/complex_interval.pyi
  src/sage/rings/complex_mpc.pyi
  src/sage/rings/complex_mpfr.pyi
  src/sage/rings/factorint.pyi
  src/sage/rings/factorint_flint.pyi
  src/sage/rings/factorint_pari.pyi
  src/sage/rings/fast_arith.pyi
  src/sage/rings/fraction_field_FpT.pyi
  src/sage/rings/fraction_field_element.pyi
  src/sage/rings/function_field/element.pyi
  src/sage/rings/function_field/element_polymod.pyi
  src/sage/rings/function_field/element_rational.pyi
  src/sage/rings/function_field/hermite_form_polynomial.pyi
  src/sage/rings/integer.pyi
  src/sage/rings/integer_fake.pyi
  src/sage/rings/integer_ring.pyi
  src/sage/rings/khuri_makdisi.pyi
  src/sage/rings/laurent_series_ring_element.pyi
  src/sage/rings/morphism.pyi
  src/sage/rings/number_field/number_field_base.pyi
Labels: s: positive review

#39259 Add pyi stub files for cython modules in `symbolic`
  src/sage/symbolic/callable.pyi
  src/sage/symbolic/comparison_impl.pyi
  src/sage/symbolic/constants_c_impl.pyi
  src/sage/symbolic/function.pyi
  src/sage/symbolic/function_factory.pyi
  src/sage/symbolic/getitem_impl.pyi
  src/sage/symbolic/operators.pyi
  src/sage/symbolic/pynac_constant_impl.pyi
  src/sage/symbolic/pynac_function_impl.pyi
  src/sage/symbolic/ring.pyi
  src/sage/symbolic/series_impl.pyi
Labels: s: positive review

#39260 Add pyi stubs for cython modules in `structure`
  src/sage/structure/category_object.pyi
  src/sage/structure/coerce_actions.pyi
  src/sage/structure/coerce_dict.pyi
  src/sage/structure/coerce_maps.pyi
  src/sage/structure/element_wrapper.pyi
  src/sage/structure/mutability.pyi
  src/sage/structure/parent_base.pyi
Labels: s: positive review

#40489 Remove unnecessary `all_sagemath_xyz.py` files
  src/doc/en/developer/doctesting.rst
  src/sage/all.py
  src/sage/all__sagemath_bliss.py
  src/sage/all__sagemath_coxeter3.py
  src/sage/all__sagemath_environment.py
  src/sage/all__sagemath_mcqd.py
  src/sage/all__sagemath_meataxe.py
  src/sage/all__sagemath_objects.py
  src/sage/all__sagemath_repl.py
  src/sage/all__sagemath_sirocco.py
  src/sage/all__sagemath_tdlib.py
  src/sage/arith/all__sagemath_objects.py
  src/sage/arith/meson.build
  src/sage/categories/all.py
  src/sage/categories/all__sagemath_objects.py
  src/sage/categories/meson.build
  src/sage/ext/all__sagemath_objects.py
  src/sage/ext/meson.build
  src/sage/graphs/all__sagemath_bliss.py
  src/sage/graphs/all__sagemath_mcqd.py
  src/sage/graphs/all__sagemath_tdlib.py
  src/sage/graphs/graph_decompositions/all__sagemath_tdlib.py
  src/sage/graphs/graph_decompositions/meson.build
  src/sage/graphs/meson.build
  src/sage/interfaces/all__sagemath_polyhedra.py
  src/sage/interfaces/meson.build
  src/sage/libs/all__sagemath_coxeter3.py
  src/sage/libs/all__sagemath_meataxe.py
  src/sage/libs/all__sagemath_objects.py
  src/sage/libs/all__sagemath_sirocco.py
  src/sage/libs/coxeter3/all__sagemath_coxeter3.py
  src/sage/libs/coxeter3/meson.build
  src/sage/libs/meson.build
  src/sage/matrix/all__sagemath_meataxe.py
  src/sage/matrix/meson.build
  src/sage/meson.build
  src/sage/misc/all.py
  src/sage/misc/all__sagemath_environment.py
  src/sage/misc/all__sagemath_objects.py
  src/sage/misc/all__sagemath_repl.py
  src/sage/misc/lazy_import.pyx
  src/sage/misc/meson.build
  src/sage/misc/sageinspect.py
  src/sage/numerical/all__sagemath_polyhedra.py
  src/sage/numerical/backends/all__sagemath_polyhedra.py
  src/sage/numerical/backends/meson.build
  src/sage/numerical/meson.build
  src/sage/repl/ipython_extension.py
  src/sage/rings/all__sagemath_objects.py
  src/sage/rings/meson.build
  src/sage/sets/all__sagemath_objects.py
  src/sage/sets/meson.build
  src/sage_setup/autogen/interpreters/internal/__init__.py
Labels: s: positive review

#40508 Add functions for computation of krylov basis and krylov kernel basis
  src/doc/en/reference/references/index.rst
  src/sage/matrix/matrix2.pyx
Labels: t: feature, s: positive review, c: linear algebra, t: performance, gsoc: 2025

#40533 remove automatic methods of polynomials in InfinitePolynomialRing
  src/sage/algebras/weyl_algebra.py
  src/sage/combinat/key_polynomial.py
  src/sage/rings/polynomial/infinite_polynomial_element.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
Labels: s: positive review, c: commutative algebra

#40555 Sirocco update to a pkg-config enabled version
  build/pkgs/sirocco/checksums.ini
  build/pkgs/sirocco/package-version.txt
  build/pkgs/sirocco/spkg-configure.m4
Labels: c: packages: standard, s: positive review, c: packages: optional

#40571 Add lattice utility functions
  src/sage/modules/free_module_integer.py
Labels: s: positive review

#40630 test random_element for uniform generation
  src/sage/categories/classical_crystals.py
  src/sage/categories/crystals.py
  src/sage/categories/examples/crystals.py
  src/sage/categories/examples/finite_enumerated_sets.py
  src/sage/categories/examples/finite_monoids.py
  src/sage/categories/examples/finite_semigroups.py
  src/sage/categories/finite_crystals.py
  src/sage/categories/finite_enumerated_sets.py
  src/sage/categories/finite_permutation_groups.py
  src/sage/categories/highest_weight_crystals.py
  src/sage/categories/primer.py
  src/sage/categories/regular_crystals.py
  src/sage/categories/regular_supercrystals.py
  src/sage/coding/binary_code.pyx
  src/sage/combinat/colored_permutations.py
  src/sage/combinat/constellation.py
  src/sage/combinat/derangements.py
  src/sage/combinat/designs/incidence_structures.py
  src/sage/combinat/gelfand_tsetlin_patterns.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/multiset_partition_into_sets_ordered.py
  src/sage/combinat/permutation.py
  src/sage/combinat/tableau.py
  src/sage/geometry/cone.py
  src/sage/graphs/graph_decompositions/modular_decomposition.pyx
  src/sage/groups/abelian_gps/abelian_group.py
  src/sage/groups/libgap_mixin.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/misc/randstate.pxd
  src/sage/misc/randstate.pyx
  src/sage/misc/sage_unittest.py
  src/sage/quivers/ar_quiver.py
  src/sage/sets/cartesian_product.py
  src/sage/tensor/modules/finite_rank_free_module.py
Labels: s: positive review

#40662 Implement the weighted chromatic symmetric functions
  src/sage/graphs/graph.py
Labels: s: positive review, c: combinatorics, c: graph theory

#40687 Drop all cython binding=True declarations
  src/sage/combinat/combinat_cython.pyx
  src/sage/combinat/posets/hasse_cython.pyx
  src/sage/combinat/posets/hasse_cython_flint.pyx
  src/sage/combinat/posets/linear_extension_iterator.pyx
  src/sage/combinat/set_partition_iterator.pyx
  src/sage/dynamics/complex_dynamics/mandel_julia_helper.pyx
  src/sage/graphs/asteroidal_triples.pyx
  src/sage/graphs/base/boost_graph.pyx
  src/sage/graphs/base/static_dense_graph.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/chrompoly.pyx
  src/sage/graphs/cliquer.pyx
  src/sage/graphs/comparability.pyx
  src/sage/graphs/connectivity.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/distances_all_pairs.pyx
  src/sage/graphs/edge_connectivity.pyx
  src/sage/graphs/graph_coloring.pyx
  src/sage/graphs/graph_decompositions/bandwidth.pyx
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/graph_decompositions/cutwidth.pyx
  src/sage/graphs/graph_decompositions/graph_products.pyx
  src/sage/graphs/graph_decompositions/rankwidth.pyx
  src/sage/graphs/graph_decompositions/slice_decomposition.pyx
  src/sage/graphs/graph_decompositions/tree_decomposition.pyx
  src/sage/graphs/graph_decompositions/vertex_separation.pyx
  src/sage/graphs/hyperbolicity.pyx
  src/sage/graphs/isoperimetric_inequalities.pyx
  src/sage/graphs/line_graph.pyx
  src/sage/graphs/matchpoly.pyx
  src/sage/graphs/path_enumeration.pyx
  src/sage/graphs/spanning_tree.pyx
  src/sage/graphs/traversals.pyx
  src/sage/graphs/weakly_chordal.pyx
  src/sage/libs/linkages/padics/unram_shared.pxi
  src/sage/matrix/constructor.pyx
  src/sage/misc/decorators.py
  src/sage/misc/fpickle.pyx
  src/sage/misc/sageinspect.py
  src/sage/modules/free_module_element.pyx
  src/sage/quivers/paths.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/rational.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/rings/ring_extension_element.pyx
  src/sage/stats/intlist.pyx
  src/sage/stats/time_series.pyx
  src/sage/structure/element.pyx
  src/sage/structure/mutability.pyx
  src/sage/structure/richcmp.pxd
  src/sage/structure/richcmp.pyx
  src/sage/symbolic/expression.pyx
Labels: s: positive review

#40695 Faster Golay code graph construction
  src/sage/graphs/generators/distance_regular.pyx
  src/sage/graphs/generators/generators_test.py
  src/sage/graphs/generators/meson.build
  src/sage/graphs/generators/shortened_000_111_extended_binary_Golay_code_graph.pickle.xz
Labels: s: positive review, c: graph theory

#40701 remove deprecated trace of surface dynamics, now an independent package
  src/sage/dynamics/meson.build
  src/sage/dynamics/surface_dynamics_deprecation.py
Labels: s: positive review

#40705 use the finer new categories for some lattice posets in library
  src/sage/categories/finite_coxeter_groups.py
  src/sage/combinat/nu_tamari_lattice.py
  src/sage/combinat/posets/bubble_shuffle.py
  src/sage/combinat/posets/hochschild_lattice.py
  src/sage/combinat/posets/lattices.py
  src/sage/combinat/posets/poset_examples.py
Labels: s: positive review, c: combinatorics

#40727 Explicitly check signum in GAP error handler
  src/sage/doctest/util.py
  src/sage/libs/gap/util.pyx
Labels: s: positive review

#40756 Find roots of low degree poly over Zmod
  src/sage/rings/finite_rings/integer_mod_ring.py
Labels: s: positive review

#40762 Fix is_cactus() for small disconnected graphs
  src/sage/graphs/graph.py
Labels: s: positive review, c: graph theory

#40763 is_geodetic: change documentation to match implementation
  src/sage/graphs/convexity_properties.pyx
Labels: s: positive review, c: graph theory

#40768 src/sage/matrix/matrix_integer_dense_hnf.py: more reliable HNF
  src/sage/matrix/matrix_integer_dense_hnf.py
Labels: s: positive review, c: linear algebra, p: CI Fix

#40769 src/sage/modular/modform/numerical.py: increase tolerance, again
  src/sage/modular/modform/numerical.py
Labels: s: positive review, c: modular forms, p: CI Fix

#40772 Coerce `int` to `ZZ` for `lift_x` method
  src/sage/schemes/elliptic_curves/ell_generic.py
Labels: s: positive review, c: algebraic geometry, p: trivial / 5

#40773 Faster determinant for matrices over gf2e (M4RIE)
  src/sage/libs/m4rie.pxd
  src/sage/matrix/matrix_gf2e_dense.pyx
Labels: s: positive review, c: linear algebra, t: performance

#40777 remove one deprecated alias in orthogonal polys
  src/sage/functions/orthogonal_polys.py
Labels: s: positive review, c: calculus

#40779 removing some unused imports in pyx files
  src/sage/graphs/path_enumeration.pyx
  src/sage/libs/gap/element.pyx
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/modules/free_module_element.pyx
  src/sage/rings/ring.pyx
Labels: s: positive review

#40782 some fixes for ruff SIM113
  src/sage/categories/enumerated_sets.py
  src/sage/categories/regular_crystals.py
  src/sage/combinat/dyck_word.py
  src/sage/combinat/finite_state_machine.py
  src/sage/combinat/gray_codes.py
  src/sage/combinat/ncsf_qsym/qsym.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/posets/poset_examples.py
  src/sage/combinat/sf/dual.py
  src/sage/combinat/words/paths.py
  src/sage/topology/cubical_complex.py
Labels: s: positive review

#36892 Decapitalize filenames in PREP doc
  src/doc/en/prep/Quickstarts/meson.build
  src/doc/en/prep/advanced-2D-plotting.rst
  src/doc/en/prep/calculus.rst
  src/doc/en/prep/index.rst
  src/doc/en/prep/intro-tutorial.rst
  src/doc/en/prep/logging-on.rst
  src/doc/en/prep/meson.build
  src/doc/en/prep/programming.rst
  src/doc/en/prep/quickstart.rst
  src/doc/en/prep/quickstarts/abstract-algebra.rst
  src/doc/en/prep/quickstarts/differential-equations.rst
  src/doc/en/prep/quickstarts/graphs-and-discrete.rst
  src/doc/en/prep/quickstarts/interact.rst
  src/doc/en/prep/quickstarts/linear-algebra.rst
  src/doc/en/prep/quickstarts/meson.build
  src/doc/en/prep/quickstarts/multivariable-calculus.rst
  src/doc/en/prep/quickstarts/number-theory.rst
  src/doc/en/prep/quickstarts/numerical-analysis.rst
  src/doc/en/prep/quickstarts/statistics-and-distributions.rst
  src/doc/en/prep/symbolics-and-basic-plotting.rst
Labels: s: positive review, c: documentation, v: minimal

#38589 FiniteField: make GF(p,n) the same as GF(p^n)
  src/sage/groups/perm_gps/permgroup_named.py
  src/sage/rings/finite_rings/finite_field_constructor.py
Labels: s: positive review, c: finite rings

#39512 Add test for github format of doctest report
  src/sage/doctest/forker.py
  src/sage/doctest/reporting.py
Labels: s: positive review

#39718 Add a note regarding element containment testing
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
Labels: s: positive review, c: documentation, c: coercion

#39905 Improve documentation of various gap-related methods
  src/sage/libs/gap/util.pxd
  src/sage/libs/gap/util.pyx
  src/sage/structure/sage_object.pyx
Labels: s: positive review, c: interfaces

#40587 Minor documentation formatting improvement
  pkgs/sage-docbuild/README.rst
  src/doc/en/developer/sage_manuals.rst
  src/sage_docbuild/builders.py
Labels: s: positive review

#40681 Add subsection Documentation Previews to developer guide
  src/doc/en/developer/github.rst
Labels: s: positive review, c: documentation

#40716 Make computation of LU decomposition of matrix over GF(2^e) interruptible
  src/sage/matrix/matrix_gf2e_dense.pyx
Labels: s: positive review

#40799 Move typing imports to TYPE_CHECKING block and enable relevant ruff checks
  .github/workflows/lint.yml
  conftest.py
  pyproject.toml
  src/sage/combinat/cluster_algebra_quiver/mutation_type.py
  src/sage/combinat/combinat.py
  src/sage/combinat/dyck_word.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/parking_functions.py
  src/sage/combinat/permutation.py
  src/sage/combinat/plane_partition.py
  src/sage/combinat/posets/bubble_shuffle.py
  src/sage/combinat/posets/hasse_diagram.py
  src/sage/combinat/posets/hochschild_lattice.py
  src/sage/combinat/subword.py
  src/sage/groups/semimonomial_transformations/semimonomial_transformation_group.py
  src/sage/interacts/library.py
  src/sage/manifolds/differentiable/symplectic_form.py
  src/sage/modular/arithgroup/congroup_gammaH.py
  src/sage/modular/multiple_zeta.py
  src/sage/modular/multiple_zeta_F_algebra.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/rings/padics/witt_vector_ring.py
  src/sage/rings/polynomial/groebner_fan.py
  src/sage/tensor/modules/finite_rank_free_module.py
  src/sage/tests/memcheck/verify_no_leak.py
  src/sage_docbuild/ext/inventory_builder.py
  src/tox.ini
Labels: s: positive review, t: refactoring, github_actions

#40808 add Newton polytopes in one variable
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, c: algebraic geometry, c: commutative algebra, c: geometry

#40811 Fixes incorrect jordan form issue
  src/sage/interfaces/interface.py
  src/sage/interfaces/maxima_abstract.py
  src/sage/matrix/matrix2.pyx
  src/sage/matrix/matrix_symbolic_dense.pyx
  src/sage/matrix/matrix_symbolic_sparse.pyx
Labels: s: positive review, c: interfaces, c: linear algebra

#40815 Speed up computation of radical of polynomial
  src/sage/categories/fields.py
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review

#40817 some details about imports in combinat
  src/sage/combinat/colored_permutations.py
  src/sage/combinat/crystals/infinity_crystals.py
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/fully_commutative_elements.py
  src/sage/combinat/regular_sequence_bounded.py
  src/sage/combinat/symmetric_group_algebra.py
Labels: s: positive review, c: combinatorics

#40818 add Newton polytopes for Laurent polynomials
  src/sage/rings/polynomial/laurent_polynomial.pyx
  src/sage/rings/polynomial/laurent_polynomial_mpair.pyx
Labels: s: positive review, c: commutative algebra, c: geometry

#40819 various details in algebras, categories
  src/sage/algebras/lie_algebras/quotient.py
  src/sage/categories/coxeter_groups.py
  src/sage/categories/crystals.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
  src/sage/categories/finite_lattice_posets.py
  src/sage/categories/highest_weight_crystals.py
  src/sage/categories/ore_modules.py
  src/sage/categories/pushout.py
  src/sage/categories/rings.py
  src/sage/categories/supercrystals.py
Labels: s: positive review, c: algebra

#40821 Devcontainer: use devcontainer id as key for venv and build directory
  .devcontainer/onCreate-meson.sh
  .devcontainer/portability-archlinux/devcontainer.json
  .devcontainer/portability-fedora-41/devcontainer.json
  .devcontainer/portability-fedora-42/devcontainer.json
  .devcontainer/portability-ubuntu-2204/devcontainer.json
  .devcontainer/portability-ubuntu-2404/devcontainer.json
  .devcontainer/portability-ubuntu-2504/devcontainer.json
  .devcontainer/portability-void/devcontainer.json
Labels: s: positive review

#40829 a few fixes for pycodestyle
  src/sage/graphs/connectivity.pyx
  src/sage/interfaces/khoca.py
  src/sage/interfaces/regina.py
  src/sage/libs/gap/element.pyx
  src/sage/matrix/matrix2.pyx
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/function_field/element.pyi
  src/sage/rings/function_field/element_polymod.pyi
  src/sage/rings/function_field/element_rational.pyi
  src/sage/structure/element.pyx
  src/sage/symbolic/function_factory.pyi
Labels: s: positive review, p: CI Fix

#40830 Add every path in XDG_DATA_DIRS to `sage_data_paths`
  src/sage/env.py
Labels: s: positive review

#40837 adding a comment about chain_polynomial
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#40842 git-ignore sagemath.egg-info
  .gitignore
Labels: s: positive review

#40848 type annotation for is_simple and is_smooth
  src/sage/algebras/lie_algebras/verma_module.py
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/geometry/cone.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/polyhedron/base3.py
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/groups/libgap_mixin.py
  src/sage/groups/perm_gps/permgroup.py
  src/sage/rings/qqbar.py
  src/sage/rings/semirings/tropical_variety.py
  src/sage/schemes/affine/affine_subscheme.py
  src/sage/schemes/cyclic_covers/cycliccover_generic.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
  src/sage/schemes/plane_conics/con_field.py
  src/sage/schemes/product_projective/subscheme.py
  src/sage/schemes/toric/toric_subscheme.py
  src/sage/schemes/toric/variety.py
Labels: s: positive review

#40849 some details in arith/misc
  src/sage/arith/misc.py
Labels: s: positive review
