Repository sagemath/sage, pull requests merged in 2025-02, with the labels that each got.

#39392 Test that the Sage git repo is clean.
  Makefile
Labels: s: positive review, p: critical / 2

#39393 breaking lines after else: in pyx files
  src/sage/coding/binary_code.pyx
  src/sage/libs/mpmath/ext_impl.pyx
  src/sage/libs/mpmath/utils.pyx
  src/sage/libs/singular/singular.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/rings/finite_rings/element_base.pyx
  src/sage/rings/finite_rings/integer_mod.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
Labels: s: positive review, t: refactoring

#39403 conversion of symmetric functions to and from magma
  src/sage/combinat/sf/elementary.py
  src/sage/combinat/sf/homogeneous.py
  src/sage/combinat/sf/monomial.py
  src/sage/combinat/sf/powersum.py
  src/sage/combinat/sf/schur.py
  src/sage/ext_data/magma/sage/basic.m
  src/sage/modules/with_basis/indexed_element.pyx
Labels: s: positive review, c: combinatorics, c: interfaces: optional

#39405 Resolve error in `transversal_matroid.pyx`
  src/sage/matroids/transversal_matroid.pyx
Labels: t: bug, s: positive review, c: cython, c: matroid theory, p: CI Fix

#39415 Implementation of the general Burau representation for Artin groups
  src/doc/en/reference/references/index.rst
  src/sage/groups/artin.py
  src/sage/groups/braid.py
Labels: t: enhancement, s: positive review, c: group theory

#39418 more spkg-configures (new/fixes)
  build/pkgs/h11/spkg-configure.m4
  build/pkgs/symengine_py/spkg-configure.m4
Labels: s: positive review, c: build: configure

#39422 fix one optional internet doctest in oeis.py
  src/sage/databases/oeis.py
Labels: s: positive review

#39424 Fix bug with sage_getfile in meson editable install
  src/sage/misc/sageinspect.py
Labels: s: positive review

#39425 Fix basis of multivariate polynomial ring
  src/sage/combinat/integer_vector.py
  src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
  src/sage/rings/polynomial/polydict.pyx
Labels: t: bug, s: positive review, c: linear algebra, c: commutative algebra

#39429 Declare `del_edge` as `cpdef`
  src/sage/graphs/base/static_sparse_backend.pyx
Labels: s: positive review, c: build, c: graph theory

#39430 Delay LaTeX feature tests as long as possible
  src/sage/misc/latex.py
Labels: c: user interface, s: positive review

#39431 Fixed FFT setting function that assumed that values were uninitialized
  src/sage/calculus/transforms/fft.pyx
Labels: s: positive review

#39432 Fixed randomly failing test in bigraphical hyperplane function
  src/sage/geometry/hyperplane_arrangement/library.py
Labels: s: positive review

#39435 bump GAP to 4.14.0
  build/pkgs/gap/checksums.ini
  build/pkgs/gap/package-version.txt
  build/pkgs/gap/patches/0001-Makefile.rules-Darwin-Remove-use-of-single_module-ob.patch
  build/pkgs/gap/patches/gap-4.13.1-hash-fixes.patch
  build/pkgs/gap/spkg-check.in
Labels: c: packages: standard, s: positive review, p: blocker / 1, c: packages: optional

#39438 enhanced details in link.py
  src/sage/knots/link.py
Labels: s: positive review

#39439 using next in isogeny plotting
  src/sage/schemes/elliptic_curves/isogeny_class.py
Labels: s: positive review

#39440 introduce the alias "is_congruence_uniform" in lattices
  src/doc/en/reference/references/index.rst
  src/sage/combinat/posets/lattices.py
Labels: s: positive review

#39441 some details in KR crystals
  src/sage/combinat/crystals/kirillov_reshetikhin.py
Labels: s: positive review, c: combinatorics

#39451 Fixes incorrect behaviour when taking the derivative of a constant matrix
  src/sage/matrix/matrix_dense.pyx
  src/sage/matrix/matrix_sparse.pyx
Labels: s: positive review

#39457 Remove all__sagemath_categories
  pkgs/sagemath-categories/MANIFEST.in.m4
  src/sage/all__sagemath_categories.py
  src/sage/meson.build
  src/sage/misc/fpickle.pyx
  src/sage/misc/package_dir.py
Labels: s: positive review

#39461 remove old deprecation in modular symbols
  src/sage/modular/modsym/p1list.pyx
Labels: s: positive review, c: modular forms

#39462 remove a deprecation simplicial complexes
  src/sage/topology/simplicial_complex.py
Labels: s: positive review, c: algebraic topology

#39463 remove deprecated stuff in cremona_database
  src/sage/databases/cremona.py
Labels: s: positive review, c: elliptic curves

#39465 remove deprecated stuff in polyhedron plot
  src/sage/geometry/polyhedron/plot.py
Labels: s: positive review, c: geometry

#39468 Fix documentation of integral_points
  src/sage/geometry/integral_points.py
Labels: s: positive review, c: documentation

#35944 Fix incorrect exponentiation of modular forms
  src/sage/modular/modform/element.py
  src/sage/modular/modform/ring.py
Labels: t: bug, p: minor / 4, s: positive review, c: modular forms, t: refactoring, v: moderate

#38794 convert magma power series rings
  src/sage/ext_data/magma/sage/basic.m
  src/sage/interfaces/magma.py
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/modular/btquotients/btquotient.py
  src/sage/rings/laurent_series_ring.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/polynomial_rational_flint.pyx
  src/sage/rings/power_series_ring.py
  src/sage/rings/puiseux_series_ring.py
  src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
Labels: t: enhancement, s: positive review, c: interfaces

#39012 Remove SAGE_DB from public interface
  src/sage/graphs/isgci.py
  src/sage/misc/all.py
  src/sage/misc/misc.py
  src/sage/misc/persist.pyx
Labels: s: positive review

#39065 Implemented methods concerning bricks and braces of a matching covered graph
  src/sage/graphs/matching.py
  src/sage/graphs/matching_covered_graph.py
Labels: s: positive review, c: graph theory

#39137 Minor refactor for is_exact
  src/sage/matrix/matrix_space.py
  src/sage/modules/free_module.py
  src/sage/rings/ring.pyx
  src/sage/schemes/elliptic_curves/ell_generic.py
  src/sage/structure/parent.pyx
Labels: s: positive review, t: refactoring

#39142 Fix alarm tests
  src/doc/en/developer/coding_basics.rst
  src/sage/coding/linear_code.py
  src/sage/data_structures/bounded_integer_sequences.pyx
  src/sage/doctest/util.py
  src/sage/geometry/integral_points.pxi
  src/sage/libs/flint/nmod_poly_linkage.pxi
  src/sage/libs/gap/element.pyx
  src/sage/libs/libecm.pyx
  src/sage/matrix/matrix_integer_dense.pyx
  src/sage/matrix/matrix_mod2_dense.pyx
  src/sage/rings/complex_arb.pyx
  src/sage/rings/factorint_pari.pyx
  src/sage/rings/integer.pyx
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_zmod_flint.pyx
  src/sage/rings/qqbar.py
  src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
  src/sage/sets/recursively_enumerated_set.pyx
  src/sage/structure/coerce_actions.pyx
Labels: s: positive review

#39160 Add _make_named_class_key for several categories, miscellaneous changes
  src/sage/categories/category.py
  src/sage/categories/filtered_modules.py
  src/sage/categories/homset.py
  src/sage/categories/homsets.py
  src/sage/groups/perm_gps/permgroup_named.py
Labels: s: positive review

#39186 Remove backslash hack in doctest
  src/doc/en/developer/coding_basics.rst
  src/doc/en/thematic_tutorials/lie/branching_rules.rst
  src/doc/en/thematic_tutorials/lie/crystals.rst
  src/doc/en/thematic_tutorials/sandpile.rst
  src/sage/coding/delsarte_bounds.py
  src/sage/coding/extended_code.py
  src/sage/coding/information_set_decoder.py
  src/sage/coding/linear_code.py
  src/sage/coding/linear_code_no_metric.py
  src/sage/combinat/designs/gen_quadrangles_with_spread.pyx
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
  src/sage/dynamics/arithmetic_dynamics/affine_ds.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/features/__init__.py
  src/sage/geometry/polyhedron/base4.py
  src/sage/graphs/graph.py
  src/sage/groups/conjugacy_classes.py
  src/sage/groups/group.pyx
  src/sage/interfaces/qepcad.py
  src/sage/knots/knotinfo.py
  src/sage/libs/ntl/ntl_mat_GF2.pyx
  src/sage/manifolds/differentiable/affine_connection.py
  src/sage/matrix/matrix_polynomial_dense.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/backends/interactivelp_backend.pyx
  src/sage/rings/multi_power_series_ring.py
  src/sage/rings/multi_power_series_ring_element.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/pbori/gbcore.py
  src/sage/schemes/jacobians/abstract_jacobian.py
  src/sage/schemes/product_projective/rational_point.py
  src/sage/schemes/product_projective/subscheme.py
  src/sage/schemes/projective/projective_space.py
  src/sage/symbolic/expression.pyx
  src/sage/tensor/modules/tensor_with_indices.py
  src/sage/tests/book_stein_ent.py
  src/sage/tests/books/computational-mathematics-with-sagemath/float_doctest.py
  src/sage/tests/books/computational-mathematics-with-sagemath/integration_doctest.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review

#39242 Make tests compatible with numpy 2.1
  src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst
  src/doc/en/thematic_tutorials/numerical_sage/numpy.rst
  src/sage/combinat/fully_packed_loop.py
  src/sage/functions/special.py
  src/sage/numerical/optimize.py
  src/sage/plot/arrow.py
  src/sage/plot/multigraphics.py
  src/sage/plot/streamline_plot.py
  src/sage/rings/integer.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/schemes/elliptic_curves/period_lattice_region.pyx
  src/sage/stats/basic_stats.py
  src/sage/structure/coerce.pyx
  src/sage/symbolic/function.pyx
  src/sage/symbolic/ring.pyx
Labels: s: positive review

#39275 Specify use_sources=True in cython compilation
  src/sage/misc/cython.py
Labels: s: positive review

#39280 add parameter `immutable` to some graph operations in `sage/graphs/generic_graph.py`
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39285 add parameter `immutable` to some graph products in `sage/graphs/generic_graph.py`
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39297 more care about parameter `immutable` in `sage/graphs/generic_graph.py`
  src/sage/graphs/generic_graph.py
Labels: s: positive review, c: graph theory

#39347 activate check for ruff PLW0127
  src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
  src/sage/combinat/skew_tableau.py
  src/sage/interacts/library.py
  src/tox.ini
Labels: s: positive review, t: refactoring

#39353 bump fpylll to 0.6.3, fplll to 5.5.0
  build/pkgs/fplll/checksums.ini
  build/pkgs/fplll/package-version.txt
  build/pkgs/fplll/spkg-configure.m4
  build/pkgs/fpylll/checksums.ini
  build/pkgs/fpylll/dependencies
  build/pkgs/fpylll/package-version.txt
Labels: c: packages: standard, s: positive review

#39362 Add doctest that integral of 0 function is 0
  src/sage/misc/functional.py
Labels: s: positive review

#39374 Updated random_diagonal_matrix function so it works for any ring
  src/sage/matrix/special.py
Labels: s: positive review

#39378 Fix build with meson documentation
  src/doc/en/installation/meson.rst
Labels: s: positive review

#39380 inline an inner function in random two-sphere (for speed)
  src/sage/graphs/generators/random.py
Labels: s: positive review, c: graph theory

#39382 Correct method `is_sparse_paving`
  src/doc/en/reference/references/index.rst
  src/sage/matroids/matroid.pyx
Labels: t: bug, s: positive review, c: matroid theory

#39384 fixing PLW0120
  src/sage/combinat/diagram_algebras.py
  src/sage/combinat/regular_sequence.py
  src/sage/combinat/words/finite_word.py
  src/sage/combinat/words/morphic.py
  src/sage/combinat/words/morphism.py
  src/sage/combinat/words/word_generators.py
  src/sage/modular/modform/element.py
  src/sage/rings/polynomial/binary_form_reduce.py
  src/sage/schemes/elliptic_curves/hom.py
  src/sage/schemes/elliptic_curves/hom_velusqrt.py
Labels: s: positive review, t: refactoring

#39385 use the faster binomial in combinat
  src/sage/combinat/affine_permutation.py
  src/sage/combinat/baxter_permutations.py
  src/sage/combinat/blob_algebra.py
  src/sage/combinat/cluster_algebra_quiver/cluster_seed.py
  src/sage/combinat/dyck_word.py
  src/sage/combinat/interval_posets.py
  src/sage/combinat/posets/posets.py
  src/sage/combinat/root_system/pieri_factors.py
  src/sage/combinat/words/shuffle_product.py
Labels: s: positive review, c: combinatorics, t: performance, t: refactoring

#39387 minor changes about faster binomial in modular
  src/sage/modular/dirichlet.py
  src/sage/modular/pollack_stevens/dist.pyx
  src/sage/modular/pollack_stevens/padic_lseries.py
Labels: s: positive review, c: modular forms, t: refactoring

#39388 using the binomial method in categories + cleanup
  src/sage/categories/examples/graded_connected_hopf_algebras_with_basis.py
  src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
Labels: s: positive review, c: categories, t: refactoring

#39389 minor detail in combin. polyhedron
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
Labels: s: positive review

#39390 `matroids/database_collections.py`: Single quotes
  src/sage/matroids/database_collections.py
Labels: t: bug, s: positive review, c: matroid theory

#39391 Add wrapper for FLINT's `acb_dirichlet_zeta_zeros`
  src/sage/rings/complex_arb.pyx
Labels: s: positive review

#39394 move methods into category of fields
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/fields.py
  src/sage/rings/ring.pyx
Labels: s: positive review, c: categories, t: refactoring

#39402 Simplify __invert__ for polynomial quotient ring element
  src/sage/rings/polynomial/polynomial_element.pyx
  src/sage/rings/polynomial/polynomial_integer_dense_ntl.pyx
  src/sage/rings/polynomial/polynomial_quotient_ring_element.py
Labels: s: positive review, t: performance, t: refactoring

#39061 Fix some errors in documentation of cachefunc
  src/sage/misc/cachefunc.pyx
Labels: s: positive review

#39214 Add keyword prec for exponential and logarithm of Drinfeld modules
  src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
Labels: s: positive review, sd128

#39251 Require Python 3.11 or newer; remove outdated workarounds
  .github/workflows/build.yml
  .github/workflows/dist.yml
  .github/workflows/doc-build-pdf.yml
  .github/workflows/doc-build.yml
  .github/workflows/pyright.yml
  .gitignore
  README.md
  pyproject.toml
  pyrightconfig.json
  ruff.toml
  src/MANIFEST.in
  src/doc/en/developer/coding_in_python.rst
  src/doc/en/installation/conda.rst
  src/doc/en/installation/launching.rst
  src/sage/all__sagemath_repl.py
  src/sage/cpython/atexit.pyx
  src/sage/cpython/cython_metaclass.h
  src/sage/cpython/debug.pyx
  src/sage/cpython/debugimpl.c
  src/sage/cpython/pycore_long.h
  src/sage/doctest/forker.py
  src/sage/libs/gmp/pylong.pyx
  src/sage/misc/fpickle.pyx
  src/sage/misc/inherit_comparison_impl.c
  src/sage_docbuild/ext/sage_autodoc.py
  src/sage_setup/command/sage_build_cython.py
  src/setup.cfg.m4
Labels: s: positive review

#39266 add parameter immutable to generators in `sage/graphs/digraph_generators.py` (part 2)
  src/sage/graphs/digraph_generators.py
Labels: s: positive review, c: graph theory

#39365 Allow coercion from Frac(QQ[x]) to LaurentSeriesRing(QQ)
  src/sage/rings/laurent_series_ring.py
Labels: s: positive review, c: algebra

#39366 Add documentation to LaurentSeries point to accessors
  src/sage/rings/laurent_series_ring_element.pyx
Labels: c: basic arithmetic, s: positive review

#39381 Allow system python 3.13
  build/pkgs/python3/spkg-configure.m4
  pkgs/sage-setup/pyproject.toml
Labels: s: positive review

#39397 details in braid groups
  src/sage/groups/braid.py
Labels: s: positive review, c: group theory

#39423 Use import_module instead of find_spec
  src/sage/misc/dev_tools.py
Labels: s: positive review

#39449 Magma padics
  src/sage/ext_data/magma/sage/basic.m
  src/sage/rings/padics/padic_base_leaves.py
Labels: s: positive review, c: interfaces: optional, sd128

#39454 remove deprecated stuff in permutation.py
  src/sage/combinat/permutation.py
Labels: s: positive review, c: combinatorics

#39456 Trivial simplifications for arccos
  src/doc/de/thematische_anleitungen/sage_gymnasium.rst
  src/sage/functions/trig.py
  src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
  src/sage/symbolic/ginac/inifcns_trig.cpp
  src/sage/tests/books/computational-mathematics-with-sagemath/premierspas_doctest.py
Labels: s: positive review, c: calculus

#39466 remove some deprecations in groups
  src/doc/en/reference/groups/index.rst
  src/sage/groups/matrix_gps/homset.py
  src/sage/groups/matrix_gps/meson.build
  src/sage/groups/matrix_gps/morphism.py
  src/sage/groups/perm_gps/permgroup.py
Labels: s: positive review, c: group theory

#39473 add tuple typing to gens methods in algebras
  src/sage/algebras/askey_wilson.py
  src/sage/algebras/clifford_algebra.py
  src/sage/algebras/cluster_algebra.py
  src/sage/algebras/down_up_algebra.py
  src/sage/algebras/free_zinbiel_algebra.py
  src/sage/algebras/hecke_algebras/ariki_koike_algebra.py
  src/sage/algebras/hecke_algebras/cubic_hecke_algebra.py
  src/sage/algebras/jordan_algebra.py
  src/sage/algebras/letterplace/free_algebra_letterplace.pyx
  src/sage/algebras/lie_algebras/classical_lie_algebra.py
  src/sage/algebras/lie_algebras/free_lie_algebra.py
  src/sage/algebras/lie_algebras/heisenberg.py
  src/sage/algebras/lie_algebras/lie_algebra.py
  src/sage/algebras/lie_algebras/subalgebra.py
  src/sage/algebras/lie_algebras/verma_module.py
  src/sage/algebras/octonion_algebra.pyx
  src/sage/algebras/q_commuting_polynomials.py
  src/sage/algebras/q_system.py
  src/sage/algebras/quantum_clifford.py
  src/sage/algebras/quantum_groups/quantum_group_gap.py
  src/sage/algebras/quantum_matrix_coordinate_algebra.py
  src/sage/algebras/quatalg/quaternion_algebra.py
  src/sage/algebras/steenrod/steenrod_algebra.py
  src/sage/algebras/yangian.py
  src/sage/algebras/yokonuma_hecke_algebra.py
Labels: s: positive review, t: refactoring

#39474 convert gens method in modular to return tuple
  src/sage/modular/abvar/finite_subgroup.py
  src/sage/modular/abvar/homspace.py
  src/sage/modular/dirichlet.py
  src/sage/modular/drinfeld_modform/ring.py
  src/sage/modular/drinfeld_modform/tutorial.py
  src/sage/modular/hecke/algebra.py
  src/sage/modular/hecke/module.py
  src/sage/modular/modform/space.py
  src/sage/modular/modform_hecketriangle/abstract_space.py
  src/sage/modular/modform_hecketriangle/readme.py
  src/sage/modular/modform_hecketriangle/space.py
  src/sage/modular/modform_hecketriangle/subspace.py
  src/sage/modular/overconvergent/genus0.py
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/modular/pollack_stevens/manin_map.py
  src/sage/modular/quasimodform/element.py
  src/sage/modular/quasimodform/ring.py
Labels: s: positive review, t: refactoring

#39476 typing annotation for gens method in rings and groups (pyx files)
  src/sage/groups/libgap_wrapper.pyx
  src/sage/rings/complex_arb.pyx
  src/sage/rings/integer_ring.pyx
  src/sage/rings/polynomial/pbori/pbori.pyx
  src/sage/rings/polynomial/symmetric_reduction.pyx
  src/sage/rings/real_arb.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/rings/ring_extension.pyx
  src/sage/rings/semirings/tropical_semiring.pyx
Labels: s: positive review, c: group theory, c: algebra

#39477 typing and details in tableaux files
  src/sage/combinat/ribbon_tableau.py
  src/sage/combinat/skew_tableau.py
  src/sage/combinat/tableau.py
  src/sage/combinat/tableau_tuple.py
Labels: s: positive review

#39479 Fixed crash when exp(0) of p-adic numbers is called
  src/sage/rings/padics/padic_generic_element.pyx
Labels: s: positive review

#39481 Fixed issue in list_plot where it assumed data had been enumerated when it might not have been
  src/sage/plot/plot.py
Labels: s: positive review

#39482 fix one typo
  src/sage/graphs/cographs.py
Labels: s: positive review, sd128

#39485 Implement conversion from laurent series to rational function field
  src/sage/rings/fraction_field.py
Labels: s: positive review

#39486 Finish changing Rational's round method default rounding to even
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/rational.pyx
Labels: s: positive review, sd128

#39487 Improvement of the rendering of the documentation in polynomial sequence
  src/sage/rings/polynomial/multi_polynomial_sequence.py
Labels: s: positive review, c: documentation, sd128

#39488 Fix issue on matrix construction over integer mod ring for large coefficients
  src/sage/matrix/matrix_modn_dense_template.pxi
Labels: s: positive review, sd128

#39489 fix several oeis related doctests
  src/doc/en/developer/coding_basics.rst
  src/sage/combinat/quickref.py
  src/sage/combinat/species/library.py
  src/sage/rings/lazy_series.py
Labels: s: positive review, sd128

#39491 fixing doctests failures in misc/latex*.py
  src/sage/misc/latex.py
  src/sage/misc/latex_standalone.py
Labels: s: positive review, t: tests, sd128

#39494 Fix more doctests in meson_editable install
  src/sage/doctest/external.py
  src/sage/doctest/sources.py
  src/sage/env.py
  src/sage/features/meson_editable.py
  src/sage/misc/package_dir.py
Labels: s: positive review

#39495 Add documentation of Gabidulin codes in the reference manual
  src/doc/en/reference/coding/index.rst
Labels: s: positive review, c: documentation, sd128

#39496 Add deformation cones and checking for regularity for Point Configurations and normal fans of Polyhedra
  src/doc/en/reference/references/index.rst
  src/sage/geometry/fan.py
  src/sage/geometry/polyhedron/base5.py
  src/sage/geometry/triangulation/point_configuration.py
Labels: t: enhancement, s: positive review, c: geometry, sd128

#39497 moving random_element to category of rings
  src/doc/en/thematic_tutorials/coercion_and_categories.rst
  src/sage/categories/rings.py
  src/sage/categories/sets_cat.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/ring.pyx
Labels: s: positive review, t: refactoring, sd128

#39498 Apply sort and filter of walk_packages consistently
  src/sage/misc/package_dir.py
Labels: s: positive review

#39499 Improve sage_getfile by looking at __init__
  src/sage/misc/sageinspect.py
Labels: s: positive review

#39504 Implement im_gens in the class fraction_field_FpT
  src/sage/rings/fraction_field_FpT.pyx
Labels: s: positive review, sd128

#39505 Improve handling of strings supplied as matrix entries
  src/sage/matrix/args.pyx
Labels: s: positive review

#39506 New algorithm for cuts of a Poset
  src/sage/combinat/posets/posets.py
Labels: s: positive review, sd128

#39508 Fix some typo
  src/sage/rings/padics/factory.py
  src/sage/rings/polynomial/binary_form_reduce.py
Labels: s: positive review

#39510 add of the function rank_support_of_vector
  src/sage/coding/linear_rank_metric.py
Labels: s: positive review, sd128

#39513 Show test failures of ci-meson as annotations
  .github/workflows/ci-meson.yml
Labels: s: positive review

#39518 line_graph for multigraphs
  src/sage/graphs/line_graph.pyx
Labels: s: positive review, c: graph theory, sd128

#39521 rename also set-like species
  src/sage/rings/species.py
Labels: s: positive review, c: combinatorics, sd128

#39523 multi polynomial element/repr
  src/sage/rings/polynomial/multi_polynomial_element.py
  src/sage/rings/semirings/tropical_mpolynomial.py
Labels: s: positive review, t: performance, sd128

#39527 Test on CI that update-meson is properly ran
  .github/workflows/ci-meson.yml
  .gitignore
  Makefile
  src/sage/data_structures/meson.build
  tools/test-git-no-uncommitted-changes
Labels: s: positive review

#39530 Improvement to flint_autogen reader
  src/sage_setup/autogen/flint/reader.py
  src/sage_setup/autogen/flint/templates/flint_sage.pyx.template
  src/sage_setup/autogen/flint/templates/types.pxd.template
Labels: c: packages: standard, s: positive review

#39533 build/pkgs: update eclib to version 20250122
  build/pkgs/eclib/SPKG.rst
  build/pkgs/eclib/checksums.ini
  build/pkgs/eclib/package-version.txt
  build/pkgs/eclib/spkg-configure.m4
  src/sage/libs/eclib/__init__.pxd
  src/sage/libs/eclib/mat.pyx
Labels: s: positive review

#37158 use Parent in quotient rings too
  src/sage/categories/commutative_rings.py
  src/sage/categories/finite_dimensional_algebras_with_basis.py
  src/sage/categories/rings.py
  src/sage/categories/rngs.py
  src/sage/rings/finite_rings/finite_field_prime_modn.py
  src/sage/rings/function_field/ideal.py
  src/sage/rings/function_field/order.py
  src/sage/rings/function_field/order_polymod.py
  src/sage/rings/morphism.pyx
  src/sage/rings/quotient_ring.py
Labels: s: positive review, t: refactoring, v: moderate, sd128

#37173 Implemented `.ramified_places` and modified further methods to extend quaternion algebra functionality to number fields
  src/sage/algebras/quatalg/quaternion_algebra.py
Labels: p: major / 3, t: enhancement, t: feature, s: positive review, c: algebra, v: large, sd128

#38108 Implicit function solver for lazy series
  src/sage/combinat/sf/orthotriang.py
  src/sage/combinat/sf/sf.py
  src/sage/combinat/species/generating_series.py
  src/sage/combinat/species/species.py
  src/sage/data_structures/stream.py
  src/sage/rings/lazy_series.py
  src/sage/rings/lazy_series_ring.py
  src/sage/rings/polynomial/infinite_polynomial_ring.py
  src/sage/rings/polynomial/multi_polynomial.pyx
  src/sage/rings/polynomial/multi_polynomial_sequence.py
Labels: t: enhancement, s: positive review, c: combinatorics, c: algebra

#38650 Add support for pseudomorphisms
  src/doc/en/reference/modules/index.rst
  src/sage/modules/free_module.py
  src/sage/modules/free_module_pseudohomspace.py
  src/sage/modules/free_module_pseudomorphism.py
  src/sage/modules/meson.build
  src/sage/rings/polynomial/ore_polynomial_ring.py
Labels: s: positive review, c: linear algebra, c: algebra, sd128

#38824 Turn some doctests in `ell_rational_field.py` into long tests
  src/sage/schemes/elliptic_curves/ell_rational_field.py
Labels: t: bug, s: positive review, t: tests, c: elliptic curves, sd128

#38986 Allow CRT_list() to be called with one argument
  src/sage/arith/misc.py
Labels: s: positive review

#39025 Add reseed_rng option to p_iter_fork
  src/sage/parallel/decorate.py
  src/sage/parallel/use_fork.py
Labels: t: enhancement, s: positive review

#39092 Remove erroneous member declaration in farey_symbol
  src/sage/modular/arithgroup/farey_symbol.pyx
Labels: s: positive review

#39093 Improve hack used in debug_options
  src/sage/structure/debug_options.pyx
Labels: s: positive review

#39128 Add note about makeflags and ninja parallelism
  README.md
  src/doc/en/faq/faq-usage.rst
  src/doc/en/installation/source.rst
  src/doc/it/faq/faq-usage.rst
Labels: s: positive review

#39215 Class polynomial for Drinfeld modules
  src/doc/en/reference/references/index.rst
  src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
  src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
  src/sage/rings/ring_extension_element.pyx
Labels: s: positive review, sd128

#39248 introduce new apozeta polynomial for posets
  src/sage/combinat/posets/posets.py
Labels: s: positive review, c: combinatorics

#39309 Add inversion function for sage.crypto.sboxes
  src/sage/crypto/sboxes.py
Labels: s: positive review, c: cryptography

#39417 adding the super delta continued fractions, after G.-N. Han
  src/doc/en/reference/references/index.rst
  src/sage/rings/power_series_ring_element.pyx
Labels: s: positive review

#39420 Replace reproducible_repr() with usage of displayhook
  src/doc/en/developer/doctesting.rst
  src/sage/doctest/fixtures.py
  src/sage/misc/converting_dict.py
  src/sage/plot/animate.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/polynomial/multi_polynomial_sequence.py
  src/sage/rings/polynomial/pbori/pbori.pyx
Labels: s: positive review

#39426 Minor code improvement in `sage.doctest`
  src/sage/doctest/control.py
  src/sage/doctest/external.py
  src/sage/doctest/forker.py
  src/sage/doctest/parsing.py
Labels: s: positive review

#39427 Remove deprecated sage-cython script
  src/bin/sage-cython
  src/setup.cfg.m4
Labels: s: positive review

#39445 Fixed issue causing random elements of a quadratic field to always be integral
  src/sage/matrix/special.py
  src/sage/rings/number_field/number_field_element.pyx
  src/sage/rings/number_field/number_field_element_quadratic.pyx
  src/sage/rings/tests.py
Labels: s: positive review

#39464 remove deprecated method in normal_form_game
  src/sage/game_theory/normal_form_game.py
  src/sage/game_theory/parser.py
Labels: s: positive review, c: game theory

#39483 Improved Efficiency of mutually_orthogonal_latin_squares function
  src/doc/en/reference/references/index.rst
  src/sage/combinat/designs/latin_squares.py
Labels: s: positive review

#39484 Implemented error when incorrect bounds cause discrete_log to give incorrect answer
  src/sage/groups/generic.py
Labels: s: positive review

#39492 update meson and meson-python to the latest versions, 1.7.0 and 0.7.1
  build/pkgs/meson/checksums.ini
  build/pkgs/meson/package-version.txt
  build/pkgs/meson_python/checksums.ini
  build/pkgs/meson_python/package-version.txt
Labels: c: packages: standard, s: positive review

#39516 Add minimal relation bases for univariate polynomial matrices
  src/sage/matrix/matrix_polynomial_dense.pyx
Labels: t: enhancement, s: positive review, c: linear algebra, sd128

#39522 infinite polynomial element/gcd
  src/sage/rings/polynomial/infinite_polynomial_element.py
Labels: s: positive review, sd128

#39542 Hide more chronic diff on CI
  .github/workflows/doc-build.yml
Labels: s: positive review

#39547 Fixed issue causing logarithm of base 0 to not give either of the possible correct answers.
  src/sage/misc/functional.py
Labels: s: positive review

#39549 Add Ideal.radical and Ring.nilradical
  src/sage/categories/rings.py
  src/sage/rings/finite_rings/integer_mod_ring.py
  src/sage/rings/ideal.py
  src/sage/rings/polynomial/multi_polynomial_ideal.py
  src/sage/rings/quotient_ring.py
Labels: t: enhancement, s: positive review, c: algebra

#39550 no meaning for gp in pari/gp
  src/doc/de/tutorial/interfaces.rst
  src/doc/en/tutorial/interfaces.rst
  src/doc/fr/tutorial/interfaces.rst
  src/doc/ja/tutorial/interfaces.rst
  src/doc/pt/tutorial/interfaces.rst
  src/doc/ru/tutorial/interfaces.rst
Labels: s: positive review, c: documentation, p: trivial / 5

#39551 Correct an error message.
  src/sage/sat/solvers/dimacs.py
Labels: s: positive review

#39552 fix and activate the check for pep E272
  src/sage/combinat/designs/resolvable_bibd.py
  src/sage/dynamics/arithmetic_dynamics/projective_ds.py
  src/tox.ini
Labels: s: positive review

#39553 make algdep always an alias for algebraic_dependency
  src/sage/arith/all.py
  src/sage/arith/misc.py
  src/sage/calculus/calculus.py
  src/sage/rings/complex_double.pyx
  src/sage/rings/complex_mpc.pyx
  src/sage/rings/complex_mpfr.pyx
  src/sage/rings/padics/padic_ZZ_pX_element.pyx
  src/sage/rings/padics/padic_generic_element.pyx
  src/sage/rings/real_double.pyx
  src/sage/rings/real_mpfi.pyx
  src/sage/rings/real_mpfr.pyx
  src/sage/schemes/elliptic_curves/heegner.py
  src/sage/schemes/riemann_surfaces/riemann_surface.py
Labels: s: positive review, t: refactoring

#39555 Added option to return explicit polynomial in .in_subalgebra
  src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
Labels: s: positive review

#39556 Fixed issue where Partitions() was caching results when an error happens.
  src/sage/combinat/partition.py
Labels: s: positive review

#39557 Fixed issue where insert_row in dense integer matrices would not accept python integers.
  src/sage/matrix/matrix_integer_dense.pyx
Labels: s: positive review

#39558 cleaning the maximal orders in rational function fields
  src/sage/rings/function_field/order_rational.py
Labels: s: positive review, c: commutative algebra

#39564 some fixes for E114
  src/sage/dynamics/arithmetic_dynamics/wehlerK3.py
  src/sage/game_theory/matching_game.py
  src/sage/groups/free_group.py
  src/sage/interfaces/maxima.py
  src/sage/modular/pollack_stevens/fund_domain.py
  src/sage/plot/plot.py
  src/sage/rings/algebraic_closure_finite_field.py
  src/sage/rings/padics/lattice_precision.py
  src/sage/schemes/generic/algebraic_scheme.py
Labels: s: positive review

#39565 remove many unused imports
  src/sage/algebras/jordan_algebra.py
  src/sage/algebras/lie_algebras/verma_module.py
  src/sage/categories/kahler_algebras.py
  src/sage/coding/guruswami_sudan/utils.py
  src/sage/combinat/combinat.py
  src/sage/combinat/root_system/reflection_group_complex.py
  src/sage/combinat/specht_module.py
  src/sage/crypto/key_exchange/diffie_hellman.py
  src/sage/crypto/util.py
  src/sage/env.py
  src/sage/features/__init__.py
  src/sage/features/fricas.py
  src/sage/features/latex.py
  src/sage/features/meson_editable.py
  src/sage/features/pkg_systems.py
  src/sage/functions/transcendental.py
  src/sage/geometry/cone_critical_angles.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedron/backend_polymake.py
  src/sage/geometry/polyhedron/base.py
  src/sage/geometry/triangulation/point_configuration.py
  src/sage/graphs/graph_database.py
  src/sage/graphs/orientations.py
  src/sage/groups/class_function.py
  src/sage/homology/chain_complex.py
  src/sage/interfaces/jmoldata.py
  src/sage/manifolds/chart_func.py
  src/sage/matrix/operation_table.py
  src/sage/misc/compat.py
  src/sage/misc/cython.py
  src/sage/misc/misc.py
  src/sage/modules/with_basis/representation.py
  src/sage/repl/rich_output/backend_ipython.py
  src/sage/rings/number_field/morphism.py
  src/sage/rings/number_field/order_ideal.py
  src/sage/schemes/affine/affine_morphism.py
  src/sage/schemes/affine/affine_point.py
  src/sage/symbolic/expression_conversions.py
  src/sage/symbolic/function_factory.py
  src/sage/tensor/modules/free_module_morphism.py
  src/sage/topology/cubical_complex.py
  src/sage/topology/simplicial_complex.py
Labels: s: positive review

#39566 some fixes for E272 in pyx files
  src/sage/coding/codecan/codecan.pyx
  src/sage/combinat/designs/designs_pyx.pyx
  src/sage/combinat/designs/orthogonal_arrays_find_recursive.pyx
  src/sage/geometry/polyhedron/combinatorial_polyhedron/base.pyx
  src/sage/graphs/graph_decompositions/slice_decomposition.pyx
  src/sage/graphs/strongly_regular_db.pyx
  src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
  src/sage/groups/perm_gps/partn_ref/data_structures.pyx
  src/sage/groups/perm_gps/partn_ref/double_coset.pyx
  src/sage/groups/perm_gps/partn_ref/refinement_sets.pyx
  src/sage/libs/mpmath/ext_main.pyx
  src/sage/matrix/matrix_cyclo_dense.pyx
  src/sage/modules/vector_rational_dense.pyx
  src/sage/numerical/backends/glpk_backend.pyx
  src/sage/numerical/mip.pyx
  src/sage/stats/hmm/chmm.pyx
  src/sage/stats/hmm/util.pyx
Labels: s: positive review

#39567 Make test deterministic to fix CI
  src/sage/schemes/elliptic_curves/ell_rational_field.py
Labels: s: positive review, c: elliptic curves, p: CI Fix

#39568 simplify empty sets
  src/sage/algebras/orlik_solomon.py
  src/sage/algebras/orlik_terao.py
  src/sage/calculus/desolvers.py
  src/sage/combinat/root_system/pieri_factors.py
  src/sage/doctest/util.py
  src/sage/geometry/fan.py
  src/sage/geometry/hasse_diagram.py
  src/sage/geometry/hyperplane_arrangement/arrangement.py
  src/sage/geometry/lattice_polytope.py
  src/sage/geometry/polyhedral_complex.py
  src/sage/graphs/generators/families.py
  src/sage/graphs/generators/smallgraphs.py
  src/sage/matrix/matrix_modn_sparse.pyx
  src/sage/matrix/matrix_rational_sparse.pyx
  src/sage/matroids/dual_matroid.py
  src/sage/matroids/linear_matroid.pyx
  src/sage/matroids/matroid.pyx
  src/sage/matroids/minor_matroid.py
  src/sage/matroids/utilities.py
  src/sage/rings/polynomial/pbori/specialsets.py
  src/sage/symbolic/relation.py
Labels: s: positive review

#39570 bump python to at least 3.11 in spkg-configure.m4
  build/pkgs/python3/spkg-configure.m4
Labels: s: positive review

#39572 Change some instances of "gens" method to return tuples
  src/sage/rings/polynomial/symmetric_reduction.pyx
  src/sage/schemes/elliptic_curves/ell_number_field.py
  src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
Labels: s: positive review

#39573 Doctest for defining multivariate polynomial ring over InfinityRing
  src/sage/rings/polynomial/polynomial_ring_constructor.py
Labels: s: positive review

#39575 full cython-lint cleanup in data_structure pyx files
  src/sage/data_structures/binary_matrix.pxd
  src/sage/data_structures/binary_search.pxd
  src/sage/data_structures/bitset.pxd
  src/sage/data_structures/bitset.pyx
  src/sage/data_structures/bitset_base.pxd
  src/sage/data_structures/bitset_base.pyx
  src/sage/data_structures/blas_dict.pyx
  src/sage/data_structures/bounded_integer_sequences.pyx
Labels: s: positive review

#39577 py3.9 support cleanup in sage_autodoc and sphinx bump
  build/pkgs/sphinx/checksums.ini
  build/pkgs/sphinx/package-version.txt
  src/sage_docbuild/ext/sage_autodoc.py
Labels: s: positive review

#39578 adding some type annotations in lattices
  src/sage/combinat/posets/lattices.py
Labels: s: positive review, t: refactoring

#39584 pep8 and mypy cleanup of arith/misc.py
  src/sage/arith/misc.py
Labels: s: positive review

#39216 avoid some conversions to `short_digraph` when the input is an instance of `StaticSparseBackend`
  src/sage/graphs/asteroidal_triples.pyx
  src/sage/graphs/base/static_sparse_backend.pyx
  src/sage/graphs/base/static_sparse_graph.pyx
  src/sage/graphs/centrality.pyx
  src/sage/graphs/convexity_properties.pyx
  src/sage/graphs/generic_graph_pyx.pyx
  src/sage/graphs/graph_decompositions/clique_separators.pyx
  src/sage/graphs/isoperimetric_inequalities.pyx
  src/sage/graphs/weakly_chordal.pyx
Labels: s: positive review, c: graph theory
